### ISSUE TITLE
https mini web server

### ISSUE THREAD

**Issue by gene-git** [Motion-Project/motion#100]
I have a question rather than an issue.

Is there any way to have motion mini server be https instead of http. I am using a web server on same domain which has HSTS turned on (which requires https) for all subdomains.  HSTS is now considered best practice.

The motion software is running on an internal server which is a sub domain of the domain used on the public web server.

Browsers now cache the HSTS data set and  insist on connecting to motion using https, which doesn't work. 

Your version of motion has been working great for many months - but now in the world of increased security HSTS has bitten me.

I have tried to clear the browser settings  (chrome and firefox) to no avail. Both browsers will not connect to motion without SSL.

Any suggestions gratefully accepted.

Thanks for making motion so much better.

gene

**Comment by gene-git** [comment]
My work around was to create a completely new domain - and move motion to that domain. This may or may not be a good work around in more general case.

**Comment by tosiara** [comment]
Yeah, unfortunately motion internal web server is very limitted. You can
use other 3rd party software as a fronted. Like apache reverse proxy with
ssl

**Comment by gene-git** [comment]
Doh - why didn't I think of that ... could also stunnel which would be very straightforward to wrap https around the stream. 

Thank you - very good point. Looking sheepish for not thinking of that ... this is far cleaner approach than adding ssl  to motion too.

Thank you!
