### ISSUE TITLE
Feature request: output to multiple files at once

### ISSUE THREAD

**Issue by RenaKunisaki** [Motion-Project/motion#1001]
I've installed Motion on a Raspberry Pi in an outdoor enclosure and set it up to record to an NFS mount over wifi. I want to have the recordings also saved to a hard drive inside the enclosure in case of connection failure.

I've considered some other options, but none are ideal:

- Record to hard drive; have a script copy to NFS mount (I'd rather the recordings be saved to both ASAP)
- Record to hard drive only (footage would be lost if the disk failed or was damaged)
- Fall back to hard drive if connection fails (too messy)
- Cache on hard drive until connection is back (too unreliable)

Maybe there's some way to achieve this already? Ideally I'd be able to just specify multiple output paths in the config file.

**Comment by tosiara** [comment]
NFS over WIFI is a bad idea. Writing into a network share will cause a thread lock in case there is a network outage. It is only recommended to write into disk and copy file asynchronously using a script after the recording is completed (your option "1")

**Comment by RenaKunisaki** [comment]
Ah, I hadn't thought of that. I wonder how commercial wireless cameras deal with this?

If the connection goes down for a few minutes and I just let it lock, will it continue to work normally again once the connection comes back (even if that footage is lost) or will it crash or hang? I do plan to put in other cameras on a wired connection, so I might be able to just let this one fail, as long as it can come back online gracefully.
