### ISSUE TITLE
Feature request: writing video+audio and video on sound detection

### ISSUE THREAD

**Issue by denisio** [Motion-Project/motion#1002]
1) How to configure motion for video + audio ?
2) How to configure motion for sound detection ?

**Comment by tosiara** [comment]
Motion does not support sound recording

**Comment by jgwinner** [comment]
Which would be why it's a feature request, right?

Or do you mean it will never support sound recording?

If so, is there a way that anyone could help?

        == John ==

**Comment by jgwinner** [comment]
Also, it's probably a good idea to put this in the documentation (the fact it doesn't record sound). I couldn't find any mention of sound or audio in the docs or configuration pages.

Is there a licensing issue with MP4?

        == John ==
