### ISSUE TITLE
No issues, just not sure where to ask

### ISSUE THREAD

**Issue by testbughub** [Motion-Project/motion#1003]
Sorry if I'm not allowed to post a question here.
I just thought I'd get a better response here.

So my question is this;
Can I somehow _zoom_ the video feed?
If it's not possible inside motion, maybe it's possible with some other application. If so, I would love a recommendation.

Any help is much appreciated!

**Comment by Mr-Dave** [comment]
This is the link to the [support page](https://motion-project.github.io/motion_support.html)
