### ISSUE TITLE
 mmalcam_control_params roi not working

### ISSUE THREAD

**Issue by rdrgzlng** [Motion-Project/motion#1004]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: Motion 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: .deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mmal 
5. hardware [x86, ARM, other]: RPi 3+
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian Buster 

I have configured "mmalcam_control_params" with "-roi 0.33,0.37,0.30,0.30"

It was working with previous version of motion and Raspbian Stretch but after upgrade to Buster and Motion 4.2.2 with the .deb file of the releases page, this setup not work.

I can set other mmal params, "-hf" for example, and it work.

raspistill work correctly.

**Comment by Mr-Dave** [comment]
Tested against master branch and is functional.
