### ISSUE TITLE
Motion detection add "suppression_time"

### ISSUE THREAD

**Issue by MrPumo** [Motion-Project/motion#101]
Please evaluate adding "suppression time" between motion detection start. 
So after FIRST event start for a defined amount of time NEXT event start will not trigger.
THX a lot

**Comment by Mr-Dave** [comment]
How would this be different than the event_gap parameter?

**Comment by MrPumo** [comment]
"event_gap" is the seconds of no motion detection that triggers the end of an event.

"event_suppression" should be the seconds of time range during which every new event start after the first get suppressed (all new motion detection during this suppresion time range should be dropped).

So is possible, in a frequently motion detection fired context, to track and record just the first every "event_suppression" seconds.... avoiding have many small recordings for each detection (with event_gap low) or one big movie (with event_gap high).
