### ISSUE TITLE
Feature request: relative paths in motion.conf

### ISSUE THREAD

**Issue by angrycoding** [Motion-Project/motion#1017]
Hi, would be great if the paths that starting from "./" would be resolved relative to motion.conf file itself, instead of obligatory absolute paths.

**Comment by tosiara** [comment]
Which path do you mean? Like, for `picture_filename`?

**Comment by angrycoding** [comment]
> Which path do you mean? Like, for `picture_filename`?

log_file, target_dir, webcontrol_key, webcontrol_cert, camera_dir

**Comment by tosiara** [comment]
IMO, that would be very confusing. Many Linux distributions tend to override default config and bin directories. But one thing always remains the same - process current dir. Changing the behavior to depend on config file's location would be quite unexpected for most users

There is still `target_dir` variable which can be used to achieve what you suggest

**Comment by angrycoding** [comment]
> IMO, that would be very confusing. Many Linux distributions tend to override default config and bin directories. But one thing always remains the same - process current dir. Changing the behavior to depend on config file's location would be quite unexpected for most users
> 
> There is still `target_dir` variable which can be used to achieve what you suggest

Just consider the case:
I have kind of a package dirs with scripts, masks and camera configs, which works perfectly on one machine. But then what I need to move it to another machine easy and quick? Right now I have to either recreate dir structure same way as on the first one or edit configuration file in order to reflect it's location. But okay, if you say that it's confusing, then I'm fine with it. In any case in my setup I generate this config file from the template - inserting real absolute paths to the desired placeholders.
