### ISSUE TITLE
[doc] Documentation needs to be updated to require Gettext version 0.19

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#1018]
Latest https://github.com/Motion-Project/motion/commit/1dd05e678939afe10e6012e4d522788709a1a35b
Linux Mint 19.1

Pulled latest master and executed `autoreconf -fiv`:
```
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Copying file ABOUT-NLS
Copying file config.rpath
Creating directory m4
Copying file m4/codeset.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:11: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:11: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:11: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:3: installing './compile'
configure.ac:8: installing './config.guess'
configure.ac:8: installing './config.sub'
configure.ac:2: installing './install-sh'
configure.ac:2: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
```
Is this output expected?

**Comment by Mr-DaveDev** [comment]
Yes.  This seems to be an upstream warning from macros of automake.  I do not know of any method to eliminate or solve it.

**Comment by vilhelmgray** [comment]
There's a [section in the Automake about obsolete macros](https://www.gnu.org/software/automake/manual/html_node/Obsolete-Macros.html). Under the `AM_PROG_MKDIR_P` section, users of this macro are expected to migrate to the [modern Autoconf equivalent `AC_PROG_MKDIR_P`](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Particular-Programs.html).

**Comment by vilhelmgray** [comment]
Hmm, it doesn't look like you're using `AM_PROG_MKDIR_P` in your configure.ac file though. Is it being used somewhere else?

**Comment by vilhelmgray** [comment]
I discovered the cause: https://github.com/Motion-Project/motion/blob/1dd05e678939afe10e6012e4d522788709a1a35b/configure.ac#L12

This line causes the **Gettext 0.18** files to be pulled in and those use `AM_PROG_MKDIR_P`. A newer version of Gettext is required in order to avoid the error message.

In pull request #956, this warning is avoided by [requiring Gettext version 0.19: `AM_GNU_GETTEXT_VERSION([0.19])`](https://github.com/vilhelmgray/motion/blob/79ef57405c49ca1226fc00af1995bdab287ae9ea/configure.ac#L311).

In addition, consider adding the `AM_GNU_GETTEXT_REQUIRE_VERSION([0.19])` line -- so that newer versions of Gettext can be used -- as well as the `LIBS="$LIBINTL $LIBS"` line so that the Gettext libraries are added for the later Autoconf checks.

**Comment by tosiara** [comment]
Than you for analysis!
