### ISSUE TITLE
Ubuntu 14 build break

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#1019]
Compiling latest master https://github.com/Motion-Project/motion/commit/1dd05e678939afe10e6012e4d522788709a1a35b on Ubuntu 14:
```
ffmpeg.c: In function ‘ffmpeg_alloc_video_buffer’:
ffmpeg.c:929:10: error: ‘AVFrame’ has no member named ‘buf’
     frame->buf[0] = av_buffer_alloc(ret + 4*plane_padding);
          ^
ffmpeg.c:929:5: warning: implicit declaration of function ‘av_buffer_alloc’ [-Wimplicit-function-declaration]
     frame->buf[0] = av_buffer_alloc(ret + 4*plane_padding);
     ^
ffmpeg.c:930:15: error: ‘AVFrame’ has no member named ‘buf’
     if (!frame->buf[0]) {
               ^
ffmpeg.c:932:9: warning: implicit declaration of function ‘av_frame_unref’ [-Wimplicit-function-declaration]
         av_frame_unref(frame);
         ^
ffmpeg.c:935:10: error: ‘AVFrame’ has no member named ‘buf’
     frame->buf[1] = av_buffer_alloc(ret + 4*plane_padding);
          ^
ffmpeg.c:936:15: error: ‘AVFrame’ has no member named ‘buf’
     if (!frame->buf[1]) {
               ^
ffmpeg.c:942:27: error: ‘AVFrame’ has no member named ‘buf’
     frame->data[0] = frame->buf[0]->data;
                           ^
ffmpeg.c:943:27: error: ‘AVFrame’ has no member named ‘buf’
     frame->data[1] = frame->buf[1]->data;
                           ^
make[2]: *** [ffmpeg.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/motion/git/motion/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/motion/git/motion'
make: *** [all] Error 2
```
Full configure and make log: https://gist.github.com/tosiara/d7e9138fe462dcf3ddc65b2bed82126c

**Comment by Mr-DaveDev** [comment]
14.04 is at EoL so hopefully we can say goodbye to libav.

**Comment by tosiara** [comment]
Well, I agree that Ubuntu 14 is too old to support. But everything worked fine until this commit a week ago: https://github.com/Motion-Project/motion/commit/11da9efef6210241bb7c36dd08f2afce52d6f381 which introduced "Special allocation of video buffer for v4l2m2m codec". IMO, this feature could be implemented in a way that does not break legacy code (which we still have plenty of)

Anyway, for anyone who finds this thread, you can still use motion with Ubuntu 14 by compiling ffmpeg from sources

**Comment by tosiara** [comment]
Also, for future searchers of Ubuntu 14 support, if `configure` fails because of too old gettext, you can download and compile  gettext from sources, and 4.3.1 motion will work fine:
https://ftp.gnu.org/pub/gnu/gettext/gettext-0.20.2.tar.gz
