### ISSUE TITLE
HTTPS NGINX e auth Enabled

### ISSUE THREAD

**Issue by aledv** [Motion-Project/motion#1021]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: installed by apt
3. standalone or part of third party [motion, MotionEyeOS, other]: motion standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian Buster

Hi All, I have a problem with my configuration using nginx with https by letsencrypt and auth Enabled.

I tried to use proxy_pass with nginx using port 80 and the streaming work fine (lan e wan).
If I configure https ingress in this way, I get this behaviour: apper the popup login, I type the right username and password after the popup re-show and ask me again the credentials.

If disable the auth the streaming in https works fine.

this is my configuration:
```
server {
	listen 80;
	listen [::]:80;
	server_name motion.mydomain.xx;
	return 301 https://$server_name$request_uri;  # enforce https
}

server {
	# SSL configuration
	listen 443 ssl;
	listen [::]:443 ssl;

	ssl_certificate /etc/letsencrypt/live/mydomain.xx/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/mydomain.xx/privkey.pem;

	server_name motion.mydomain.xx;

	location / {
	  proxy_pass http://192.168.1.X:8081;
	  proxy_redirect off;
	  proxy_set_header Host $host:$server_port;
	  proxy_set_header X-Real-IP $remote_addr;
	}
}

```
someone with the same issue?

**Comment by Pi-DD** [comment]
Not identical issue, but similar. Trying to access on localhost:8765 and get no response at all.

**Comment by kluszczyn** [comment]
Try with backslash after port #, like ``proxy_pass http://192.168.1.X:8081/``.

**Comment by tosiara** [comment]
There have been issues with motion running behind a reverse proxy when motion auth is enabled: https://github.com/Motion-Project/motion/issues/540
The solution would be to use auth in reverse proxy, instead of motion. I'm using such setup with Apache and SSL, and it works fine
