### ISSUE TITLE
Failure to connect to MySQL

### ISSUE THREAD

**Issue by PossumTV** [Motion-Project/motion#103]
Sometimes on startup I've had Motion fail with the message:

_"Cannot connect to MySQL database"_

This has happened with Motion 3.2.11 and Mr-Dave's fork, and with MySQL 5.1.44 and MariaDB 10.1.11.

It seemed that although the call to **mysql_real_connect()** in **motion.c** was failing, the actual issue was **mysql_init()**, which was returning a null (something that isn't tested for).

Since my server automatically started MySQL and then Motion, I initially thought that the problem was simply that MySQL was taking some time to start up and wasn't quite ready by the time Motion tried to open the connection. I therefore put in code to retry the mysql_init() call if it returned a null. I used three retries at 5 second intervals.

This worked but I wasn't happy about it; I could put a long static delay before starting Motion and it would still fail to connect to MySQL, but retrying after even a very short delay would always succeed on the first retry, implying it wasn't a simple timing issue.

However, last night I looked into this further and I believe the problem might be that mysql_init() isn't thread safe. See:

http://dev.mysql.com/doc/refman/5.1/en/mysql-init.html

I have not conducted any tests to verify whether this is truly the issue, but it would seem that from the above link that something needs to be done to protect the mysql_init() function.

**Comment by jogu** [comment]
@PossumTV I've fixed the thread safety issue you found in https://github.com/Motion-Project/motion/issues/162

I don't know if this will fix your underlying problem or not, if you have time perhaps you can test with that patch?

**Comment by PossumTV** [comment]
I've applied the patch and restarted Motion quite a few times without the problem recurring, so it looks like it's been fixed. The problem was always somewhat intermittent so I suppose you can never be 100% certain, but it certainly looks good so far.

**Comment by jogu** [comment]
Great, thanks @PossumTV !
