### ISSUE TITLE
minimum motion detection frame interval

### ISSUE THREAD

**Issue by xenpac** [Motion-Project/motion#1035]
dear developers,
this is going to be a discussion rather than an issue:

1. the motion detect algorithm needs a certain minimum time interval of supplied frames.
Is there one? is it 3fps or maybe 5fps? any maximum??

2. stills instead of streams
let say you have a config of 15 netcams.
to run them on 25 fps would somehow overload your LAN.(maybe software too)
If you capture stills from each cam 3 times a second, well that might be just the lower end of motion detection.
maybe 5 stills per second would be a workable config.
so capturing stills instead of streams would be a solution to overcome LAN overload.
possibly timestamped.
is that possible?

many thanks;-)

**Comment by tosiara** [comment]
It is better to ask questions on the mail list as described here: https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md
Issue tracker is only used for issues tracking
