### ISSUE TITLE
Reset encoded video PTS when movie_max_time is reached

### ISSUE THREAD

**Issue by jasaw** [Motion-Project/motion#1043]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: master head
2. installed as a package or compiled from sources [deb, rpm, git, other]: source
3. standalone or part of third party [motion, MotionEyeOS, other]: motion, MotionEyeOS
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: not relevent
5. hardware [x86, ARM, other]:  ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: MotionEyeOS

Expectation:
When `movie_max_time` is non-zero, motion creates a new video file when `movie_max_time` seconds is reached. In the newly created video file, the video frame PTS value is reset back to zero.
Alternatively, send USR1 signal to create a new video file rather than setting `movie_max_time` to non-zero.

Observed:
Newly created video files have their PTS start from very large values (22196 rather than 1000 in my set up). This causes playback problem on some players.

Below is what motion sets as PTS for the first 4 frames of the video file.

First video file:
```
  PTS   Frame Type
    0    I
 1017    P
 2035    P
 3072    P
```

2nd video file (after sending USR1 signal):
```
  PTS   Frame Type
    0    I
22596    P
23603    P
24610    P
```

**Comment by jasaw** [comment]
I had `minimum_motion_frames` set to 20 frames. I think `minimum_motion_frames` is triggering this bug.

Analysis:
I have recorded the PTS for the first 30 frames in the first video file, and PTS for the first 10 frames in the 2nd video file. Notice that in the 2nd video file 2nd frame onwards, the PTS values are very close to first video frame 22 onwards, meaning the 2nd video file has skipped 20 frames, and only starts the PTS from frame 21 onwards (we always set first frame PTS to zero, so frame 22 is the first non-zero PTS used for comparison).

```
Video part 1:
Frame #    PTS    Frame Type 
 1           0    I          
 2        1017    P          
 3        2035    P          
 4        3072    P          
 5        4090    P          
 6        5107    I          
 7        6186    P          
 8        7203    P          
 9        8221    P          
10        9258    P          
11       10276    I          
12       11293    P          
13       12371    P          
14       13388    P          
15       14406    P          
16       15444    I          
17       16461    P          
18       17479    P          
19       18558    P          
20       19575    P          
21       20593    I          
22       22690    P          
23       23697    P          
24       24704    P          
25       25711    P          
26       26718    I          
27       27726    P          
28       28735    P          
29       29743    P          
30       30752    P          

Video part 2:
Frame #    PTS    Frame Type 
 1           0    I            
 2       22596    P            
 3       23603    P            
 4       24610    P            
 5       25618    P            
 6       26626    I            
 7       27635    P            
 8       28643    P            
 9       29651    P            
10       30660    P            
```

**Comment by Mr-DaveDev** [comment]
I commented first on the PR then saw this.  I think you are correct on the minimum frames.  We set the timestamp to the first image in the ring but upon processing the ring for the second movie, the images have already been tagged as saved. I have limited experience with bit-wise operators so please use your expertise to comment on the following revision.  

The Motion code first tags images as `IMAGE_SAVE` then once they are processed via the `process_image_ring` it adds a `IMAGE_SAVED` to the flags.  In the snippet below, we want to send the event with the earliest image which has a `IMAGE_SAVE` but not a `IMAGE_SAVED` tag.  This should allow for the correct timestamp on the first movie when we have pre_capture as well as when a second movie is created.

```
            int indx;
            indx = cnt->imgs.image_ring_out;
            while (indx != cnt->imgs.image_ring_in ){
                if ((cnt->imgs.image_ring[cnt->imgs.image_ring_out].flags & (IMAGE_SAVE | IMAGE_SAVED)) == IMAGE_SAVE){
                    event(cnt, EVENT_FIRSTMOTION, img, NULL, NULL, &cnt->imgs.image_ring[indx].timestamp_tv);
                    indx = cnt->imgs.image_ring_in;
                } else {
                    indx++;
                    if (indx == cnt->imgs.image_ring_size) indx = 0;
                }
            }
```
