### ISSUE TITLE
Red Picture

### ISSUE THREAD

**Issue by onlize** [Motion-Project/motion#1048]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: I do not know how to check the version, but I installed it today
2. installed as a package or compiled from sources [deb, rpm, git, other]: I use Raspberry Pi Zero
3. standalone or part of third party [motion, MotionEyeOS, other]: motion. I installed it using sudo apt-get install motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: Raspberry Pi camera module
5. hardware [x86, ARM, other]: Raspberry Pi Zero with latest Stretch. I installed it today
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Stretch, I installed it today

For some reason the camera shows everything with red colors. How can I fix it?

![camera_red](https://user-images.githubusercontent.com/28982031/67640358-3a7e1580-f8c8-11e9-98e3-aba79aebca64.JPG)

**Comment by tosiara** [comment]
Try to change https://motion-project.github.io/motion_config.html#vid_control_params 
Does it change colors?

**Comment by onlize** [comment]
Sorry, but I do not understand this. What should I do?

**Comment by tosiara** [comment]
If you need help using motion please send your question to the user mail group as it described here:
https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md
