### ISSUE TITLE
Unable to stream rtsp 

### ISSUE THREAD

**Issue by TriptonPt** [Motion-Project/motion#1049]
Running motionEye Version	0.41
Motion Version	4.1.1
OS Version	Raspbian 8.0

Rtsp stream will not work properly, and similarly to many other users I am getting the error "Unable to open video device" .

The Rtsp stream works great in every other platform I threw it at (VLC, blueiris, etc)

So far I have tried to use motion latest version and to revert back to motion 4.1.1 and the problem happens on both .

Another thing I have tried was to set the camera to udp mode, but that logically didn't work as my stream clearly states it's TCP :  rtsp://192.168.0.1:10554/tcp/av0_0

If I try to run the camera as http mjpeg the stream is displayed properly but ofcourse I lose all the features like motion, ability to resize etc .

**Comment by TriptonPt** [comment]
Forgot to mention, there is authentication , possible there might be a problem in the way Motioneye is authenticating to the camera ?

**Comment by TriptonPt** [comment]
Forgot to mention, there is authentication , possible there might be a problem in the way Motioneye is authenticating to the camera ?

**Comment by TriptonPt** [comment]
Edit: I have now been able to stream to motioneye using UDP by changing rtsp link to :

rtsp://192.168.0.1:10554/udp/av0_0

TCP for some reason does not seem to work in motioneye, although it works fine everywhere else .

Limitations : Seems I am unable to change the default 1280x720 resolution, other supported resolutions will not stream and result in the error unable to open video device !

**Comment by tosiara** [comment]
MotionEYE is a separate project, you can try to ask there: https://github.com/ccrisan/motioneye

**Comment by Mr-DaveDev** [comment]
FYI.  For us to help, you will need to Motion standalone and we'd need to see the resulting Motion log, configuration file and validation that the tcp connection stream works using a ffmpeg tool such as ffplay.

Since you also referenced authentication, validate that anything that is uploaded here has redacted the user id and password.
