### ISSUE TITLE
camera buffering no video

### ISSUE THREAD

**Issue by om111** [Motion-Project/motion#1056]
0. Reviewed guide and contributing documents? Yes
1. version- 20180602
2. installed as a package or compiled from sources - git 
3. standalone or part of third party  MotionEyeOS 
4. video stream source- web cam 
5. hardware- rasberrypi
hi i just install the motion eye OS version 20180602 and my camera is buffering i have no idea what to do please help me out in this.
2) do i have to update the  OS to 2019011 and if i have to please help me how to do

**Comment by tosiara** [comment]
Can you try to ask this question in MotionEYE first? Link: https://github.com/ccrisan/motioneye

**Comment by Mr-Dave** [comment]
Closing.  For instructions and videos only related to Motion (not Motioneye), please see the documentation [page](https://motion-project.github.io/motion_guide.html)
