### ISSUE TITLE
Detecting fast motions

### ISSUE THREAD

**Issue by AdvancedStyle** [Motion-Project/motion#1057]
0. Reviewed guide and contributing documents? Yes
1. motion Version 4.0,
2. apt-get
3. standalone
4. webcam max resolution 640x480 usb 2.0 (v4l2 device)
5. 64GB ram, and 36core CPU
6. Ubuntu 18.04

I'm trying to detect relatively fast motions, but the framerate seems too low to pick up anything fast.

I've set config:
```
framerate 100
webcam_maxrate 100
minimum_motion_frames 1
threshold 10
threshold_tune off
noise_level 10
noise_tune off
```

But for example if i wave my hand in front of the camera it does not pick up motion.  I have to move my hand quite slowly across to detect a motion.

**Comment by usernamepi** [comment]
1. At start, motion will log the actual fps received, you did not mention the the frame rate that motion reports. If this around 1 fps or worse, than you need to take a look at the fps settings of the camera.
2. The frame rate from a device is in most cases not the frame rate used for motion detection. Motion limits the frame rate for motion detection (only looks at every n-th frame coming in).
From the source, motion.c::
>     /*
>      * Calculate detection rate limit. Above 5fps we limit the detection
>      * rate to 3fps to reduce load at higher framerates.
>      */

**Comment by tosiara** [comment]
First, @usernamepi is correct, motion detection does not run at full fps to save cpu
Second, thing is that not necessarily your camera provides the framerate you asked, check logs and v4l2-ctl utility 
And third, you can try to save `movie_output_motion` debug videos to see if your movements are really exceeds noise level and noticeable enough fro motion
