### ISSUE TITLE
File storage notification when motion is set to save only one image of motion

### ISSUE THREAD

**Issue by Dinth** [Motion-Project/motion#1059]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  4.2.2
3. standalone or part of third party [motion, MotionEyeOS, other]: motioneye docker container 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: netcam (rtsp)
5. hardware [x86, ARM, other]: x86

Ive noticed a weird behaviour with notifications in Motion.
Ive got motion notifications and file storage notification set up to control mosquitto_pub.
Motion notifications work ok - the command is being run as soon as motion is detected and another command is being run when the motion is no longer detected. 
When i set up motion to save a JPG with every frame of movement also everything is fine. As soon as motion is detected JPG files are being saved and im getting notification about each file saved. 
But setting up motion to save a JPG with only first frame of motion makes things weird. The command notification of JPG being saved is being run not directly after motion is detected as i would expect, but instead its run immediately before the notification after motion no longer being detected.

**Comment by tosiara** [comment]
Could you provide your log, the full config and all scripts involved so we can reproduce the issue?

**Comment by Mr-DaveDev** [comment]
This is just how it was built.  The code for processing `picture_output first` and `picture_output best` is together and runs when the event ends.

**Comment by Dinth** [comment]
@Mr-DaveDev thanks for confirming. This means that this behaviour is not a big, but I'm not sure if it is an optimal design though. I can see many potential uses for getting a picture when the motion is detected (notifications, intimations, controlling an alarm, sending a file for an AI analysis and acting accordingly, etc), but can hardly find an use for getting a photo of motion after the motion is no longer detected. For example I want to know about a burglary when the burglar tries to break in, not after he already left the property with his loot. I want to know that a courier stands in front of my door when he arrives, not after he left leaving "Sorry we missed you" card behind. Would it be ok for me to request this feature?

**Comment by Mr-Dave** [comment]
Well, I would think that in the scenarios indicated that the configuration option of choice would be `on_event_start` rather than using `picture_output first` combined with a 'on_picture_save`  

I can mark it as an enhancement and put it into the long list of non optimal design items.

**Comment by baudev** [comment]
It's true that this behavior is very strange. When you make a motion detection system you expect to get the picture as quickly as possible. 
In this case, if the movement lasts more than 5 minutes for example, then the event is only triggered at the end of these long minutes.

The two solutions I found: 
- Use the `event_start` and make a snapshot manually (because the `event_start` doesn't provide the %f parameter)
- Record all frames of the motion, use `on_picture_save` and in the executed script, consider only the first frame.
