### ISSUE TITLE
How to disable /dev/video ?

### ISSUE THREAD

**Issue by mpmendespt** [Motion-Project/motion#1062]
How to disable /dev/video0 to prevent log file from growing with error 
[ERR] [ALL] init_camera_type: Unable to determine camera type (MMAL, Netcam, V4L2, BKTR)?
I only use network cameras (and Raspberry). 
(I've tested compiling motion with: ./configure --without-v4l2 --without-mmal --without-bktr --with-webp)
But I still have the error:
[ERR] [ALL] init_camera_type: Unable to determine camera type (MMAL, Netcam, V4L2, BKTR)
[ERR] [VID] vid_close: No Camera Device Cleanup (MMAL, Netcam, V4L2, BKTR)

How can i fix this?

Thanks

**Comment by genius3000** [comment]
How are you defining your camera in the configuration? Those messages are saying that Motion can't determine what kind of camera you're trying to use from how you've configured it.

**Comment by mpmendespt** [comment]
I have in montion.conf:
camera /etc/motioneye/camera-5.conf
camera /etc/motioneye/camera-3.conf

and in /etc/motioneye/camera-3.conf:
netcam_url http://192.168.1.220/VIDEO.CGI

and in /etc/motioneye/camera-5.conf:
netcam_url rtsp://192.168.1.221:554/0/video0

and everything is working correctly

The problem is the log file. Which currently has 35617 lines. ( journalctl -u motioneye)

[motion.conf.txt](https://github.com/Motion-Project/motion/files/3902295/motion.conf.txt)
[camera-3.conf.txt](https://github.com/Motion-Project/motion/files/3902296/camera-3.conf.txt)
[camera-5.conf.txt](https://github.com/Motion-Project/motion/files/3902297/camera-5.conf.txt)

**Comment by Mr-DaveDev** [comment]
It looks like you are running two instances of the Motion application at the same time.  I also suspect that they were installed into different locations.  Reboot and check via `top` and then check how you set up your services.  

By default, Motion will not start upon reboot so if it running, something was modified with respect to the services.  The method for enabling the service in Motion is in the [guide](https://motion-project.github.io/motion_config.html#basic_setup_service) and it may be required to reverse those steps if they were completed at some time in the past.

**Comment by mpmendespt** [comment]
looks like i have only one instance:
root@kali:~# ps aux |grep motion
root       453  4.0  2.2  57396 20328 ?        Ssl  16:39   0:07 /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
root       510  157 13.3 368480 119652 ?       SLl  16:39   4:37 /usr/bin/motion -n -c /etc/motioneye/motion.conf -d 5
root       526  0.0  1.4  28164 12664 ?        S    16:39   0:00 /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
root      1096  0.0  0.0   2132   516 pts/0    S+   16:42   0:00 grep motion

I use motioneye, with the setting from: https://github.com/ccrisan/motioneye/wiki/Install-On-Debian

  cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
  systemctl daemon-reload
  systemctl enable motioneye
  systemctl start motioneye
