### ISSUE TITLE
Can't detect large areas of motion

### ISSUE THREAD

**Issue by lmarceg** [Motion-Project/motion#1065]
Hi everybody,
I am running MotionEyeOS (on a RaspBerry 3b) which is using Motion 4.2.2 and I am writing here because I believe this is a motion configuration issue I have, rather than a MotionEyeOS one.
I have setup two cameras which have very similar configurations and actually, basically the same problems:
when the object that moves is small, detection is working fine; when the object becomes bigger and bigger, then I start to have problems: I see D:0 and L:0 in setup mode, which is rather strange.

The configuration of the two cameras is the following:

camera-1:

```
camera_name Terrazza

height 352
stream_quality 85
threshold 2477
picture_quality 75
noise_level 31
smart_mask_speed 0
pre_capture 3
noise_tune on
stream_maxrate 25
picture_output best
stream_localhost off
movie_quality 100
movie_bps 3615000
movie_codec mp4:h264_omx
text_changes on
movie_filename %Y-%m-%d/%H-%M-%S
auto_brightness off
stream_port 8081
rotate 0
stream_auth_method 0
lightswitch_percent 2
framerate 20
emulate_motion off
snapshot_filename %Y-%m-%d/%H-%M-%S
despeckle_filter EedDl
snapshot_interval 0
minimum_motion_frames 7
stream_motion off
target_dir /data/output/Camera1
netcam_url rtsp://192.168.1.130:554/12
text_scale 2
width 640
post_capture 100
picture_output_motion off
on_picture_save /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/data/etc/motioneye.conf" picture_save %t %f
on_movie_end /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/data/etc/motioneye.conf" movie_end %t %f
text_left CamID:%t
picture_filename %Y-%m-%d/%H-%M-%S
locate_motion_style redbox
locate_motion_mode on
netcam_keepalive off
movie_max_time 0
on_event_end /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/data/etc/motioneye.conf" stop %t
text_right
on_event_start /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/data/etc/motioneye.conf" start %t
event_gap 60
netcam_tolerant_check on
mask_file /data/etc/mask_1.pgm

threshold_maximum 0
threshold_tune off
```

camera-2:

```
camera_name Sala

movie_output off
height 360
stream_quality 85
threshold 1000
picture_quality 85
noise_level 31
movie_output_motion off
smart_mask_speed 0
pre_capture 10
noise_tune on
stream_maxrate 25
picture_output best
stream_localhost off
movie_quality 1
movie_bps 3615000
movie_codec mp4:h264_omx
text_changes on
movie_filename %Y-%m-%d/%H-%M-%S
auto_brightness off
stream_port 8082
rotate 0
stream_auth_method 0
lightswitch_percent 4
framerate 20
emulate_motion off
snapshot_filename %Y-%m-%d/%H-%M-%S
despeckle_filter EedDl
snapshot_interval 0
minimum_motion_frames 10
stream_motion off
target_dir /data/output/Camera2
netcam_url rtsp://192.168.1.131:554/live/ch1
text_scale 2
width 640
post_capture 60
stream_authentication user:user
picture_output_motion off
on_picture_save /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/data/etc/motioneye.conf" picture_save %t %f
on_movie_end /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/data/etc/motioneye.conf" movie_end %t %f
text_left
picture_filename %Y-%m-%d/%H-%M-%S
locate_motion_style redbox
locate_motion_mode on
netcam_keepalive off
movie_max_time 0
on_event_end /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/data/etc/motioneye.conf" stop %t
text_right
on_event_start /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/data/etc/motioneye.conf" start %t
event_gap 60
netcam_tolerant_check on
mask_file /data/etc/mask_2.pgm

threshold_maximum 0
threshold_tune on
```
I have created two videos which exactly show how detection works when I am far from the camera only.

[camid1 - MP4 video](https://www.pianetaluca.com/_private/camid1.mp4)
[camid2 - MP4 video](https://www.pianetaluca.com/_private/camid2.mp4)

I cannot find any way to solve this, but it must be a configuration issue.
Any help would be really appreciated.
Thanks

**Comment by usernamepi** [comment]
Try disabling "ligthswitch" functionality: lightswitch_percent=0.
See [the documentation on lightswitch functionality](https://motion-project.github.io/4.2/motion_config.html#lightswitch_percent
)

**Comment by lmarceg** [comment]
I will try with your suggestion. I used those values (with a trial and error approach, as I couldn't find any way to monitor lightswitch activities in the logs) to avoid false positive when the light is switched on in my living room (it switches on automatically through a WiFi plug whenever the sun sets). 
Thanks, I will post the results as soon as I have some time to play with it

**Comment by lmarceg** [comment]
I removed the lightswitch_percent as you were suggesting and actually it all worked perfectly!! That’s really amazing. 
The problem is that whenever the light turns on in the room, this triggers an unwanted motion alarm. Moreover, my house is near a street and the lights of the car passing by enlighten part of the walls so that this will also be seen as an alarm. 
How can I solve this? By changing the value of the percentage or the number of lightswitch frames? But it’s difficult to find the right values...
Thanks for sharing your thoughts!!

Inviato da iPhone

**Comment by angrycoding** [comment]
> I removed the lightswitch_percent as you were suggesting and actually it all worked perfectly!! That’s really amazing. The problem is that whenever the light turns on in the room, this triggers an unwanted motion alarm. Moreover, my house is near a street and the lights of the car passing by enlighten part of the walls so that this will also be seen as an alarm. How can I solve this? By changing the value of the percentage or the number of lightswitch frames? But it’s difficult to find the right values... Thanks for sharing your thoughts!! Inviato da iPhone
> […](#)
> Il giorno 1 dic 2019, alle ore 20:20, usernamepi ***@***.***> ha scritto: ﻿ Try disabling "ligthswitch" functionality: lightswitch_percent=0. See the documentation on lightswitch functionality — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Try to play with camera settings itself, adjust BLC, DWDR, AE, AE sensitivity and so on. The goal is to make your cam less sensitive to those unwanted light changes.

**Comment by usernamepi** [comment]
Angrycoding is partly correct.
You can still try lightswitch_percent setting, start with high values and tuning it down. Study your false alarms, geuss the percentage of the image that causes false "lightswitch" alarms. 2 and 4 % make it really sensitive, not usefull in your situation, start with values above 50 and go down if too many false alarms still appear. Lightswitch frames needs to be set to a suitable value, related to the unwanted alarms you saw (example: average-time-it-takes-for-a-car-to-pass-in-seconds/fps-camera)
Cars-driving-past-events often start and end with some small reflections on static objects that are in view. If these reflections of lightswitch events are equal or greater than the "threshold" value but smaller than the lightswitch percentage they may still trigger an alarm. So "threshold" may also need some tuning.

With all the tuning, including camera setting tuning, you must take care that you do not overdo it (like using lightwsitch_percentage=2), otherwise you will miss alarms that do matter. It is better to have some false alarms instead of some missed alarms.

**Comment by lmarceg** [comment]
Got your point. Thanks a lot for your suggestions. Will play with it!

**Comment by lmarceg** [comment]
As promised, I am back to you with my findings. I have increase lightswitch to around 20 and this gives perfect results indoor. Now detection is much more reliable. As for the outdoor camera, this is a bit trickier and I am playing with lightswitch of 15-18; probably I will also play twith lightswitch_frames.
Anyway the concept is clear and I have improved the detection a lot.
Thanks for your help, I can close this issue.
Ciao!
