### ISSUE TITLE
How to disable /dev/video0?

### ISSUE THREAD

**Issue by mpmendespt** [Motion-Project/motion#1074]
**I am sorry to reopen this issue,** but I still have the /dev/video0 errors. (Because I don't have /dev/video0)

(I've tested compiling motion with: ./configure --prefix = / usr --without-v4l2 --without-mmal --without-bktr --with-webp)
But I still have the error:
**[ERR] [ALL] init_camera_type: Unable to determine camera type (MMAL, Netcam, V4L2, BKTR)
[ERR] [VID] vid_close: No Camera Device Cleanup (MMAL, Netcam, V4L2, BKTR)**

Mr-DaveDev https://github.com/Motion-Project/motion/issues/1062#issuecomment-559553549
said “It looks like you are running two instances of the Motion”

But I have only one instance:
root@kali:~# ps aux |grep motion
root 453 4.0 2.2 57396 20328 ? Ssl 16:39 0:07 /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
root 510 157 13.3 368480 119652 ? SLl 16:39 4:37 /usr/bin/motion -n -c /etc/motioneye/motion.conf -d 5
root 526 0.0 1.4 28164 12664 ? S 16:39 0:00 /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
root 1096 0.0 0.0 2132 516 pts/0 S+ 16:42 0:00 grep motion

I use motioneye, with the setting from: https://github.com/ccrisan/motioneye/wiki/Install-On-Debian
cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
systemctl daemon-reload
systemctl enable motioneye
systemctl start motioneye

**How can i fix this /dev/video0 error  in motion?**
( to prevent the log file from growing )
( besides it works well as expected)

I restarted the raspberry at:
Dec 06 16:38:39 kali systemd[1]: Started motionEye Server.
...
Dec 06 17:31:32 kali motion[510]: [4:ml4] [ERR] [VID] vid_close: No Camera device cleanup (MMAL, Netcam, V4L2, BKTR)
lines 6197-6239/6239 (END)

**and I already have 6239 log file lines.**

Thanks

**Comment by tosiara** [comment]
Since you seems to compile motion from sources, try to take motion-dist sample config, add your netcam and run motion with only this config. Upload full log here and we will see what is wrong

**Comment by mpmendespt** [comment]
I found that using:
camera1-dist.conf motion-dist.conf, with proper changes, there were no errors. 

**So it was a configuration problem associated with motioneye**.

Then I verified that
Initially I had in /etc/motioneye/motion.conf:
camera /etc/motioneye/camera-5.conf
camera /etc/motioneye/camera-3.conf
camera camera-5.conf
camera camera-3.conf

now fix, I have  /etc/motioneye/motion.conf:

#camera /etc/motioneye/camera-5.conf
#camera /etc/motioneye/camera-3.conf
camera camera-3.conf

**I no longer have errors**…

In any way I appreciate your availability.
Thank you.
