### ISSUE TITLE
Can motion be a netcam for another motion daemon?

### ISSUE THREAD

**Issue by mxk1235** [Motion-Project/motion#1076]
More of a question.  I could not find a doc section covering this.  I have two RPi's, both running motion with different cameras.  Can RPi2 consume RPi1 stream as a netcam_url?

thanks in advance!

0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: built from source
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: raspbian

**Comment by tosiara** [comment]
Motion produces standard MJPEG stream, so, yes, you can use it to feed another motion, for example:
`netcam_url http://motion:8081/1/stream`
However, using motion as MJPEG streamer is highly inefficient and will cause significant CPU overhead. You can use better tools, like `mjpg_streamer` instead

**Comment by mxk1235** [comment]
i see.  thanks!  can you comment on where the inefficiency comes from?

**Comment by tosiara** [comment]
Motion will decode and re-encode frames back. Mjpeg-streamer with pass through mjpeg as is without decoding/encoding

**Comment by mxk1235** [comment]
i see.  makes sense.
