### ISSUE TITLE
Question: Temperature Addition

### ISSUE THREAD

**Issue by Stephanieq97** [Motion-Project/motion#1077]
I don't know how viable this is but I wanted to try and configure the motion to have one of the texts from below print out a string from any language with the temperature on it, so that it is able to display the temperature of the weather on stream. I know it currently only supports text is there any type of workaround for reading in an output from a program? I plan to use some API data to fetch the temperature and hopefully have it be on one of the bottom corners.

Thank you!

**Comment by tosiara** [comment]
You could do that using HTTP API. See this for more info: https://github.com/Motion-Project/motion/pull/594

**Comment by angrycoding** [comment]
Btw this is not going to work in case of movie_passthrough set to on. So in case if you need movie_passthrough, consider to add overlay using ffmpeg.
