### ISSUE TITLE
Record from multiple cams when motion is detected in one cam

### ISSUE THREAD

**Issue by josvanr** [Motion-Project/motion#1078]
Hello

I have a usage scenario for motion with multiple cameras and what I'd like
to do is to start/stop recording on *all* cams when motion is detected
in *any one* of the cams (or in a single one of the cams).
 Not sure if this is possible. One way to kind of 
do it would be to have one cam detect the motion, and have that send an 
external command to start/stop recording on the other cams with mencoder
or a similar tool. Disadvantage in that case is that one cannot monitor
the other cams simultaneously.

Is here any other way to achieve this? Thnx.

Jos

(Version 4.2.2 on ubuntu 18.04.3 LTS using usb webcam on x86 laptop)

**Comment by genius3000** [comment]
For future reference, questions like this are better suited to the mailing list as listed [here](https://motion-project.github.io/motion_support.html).

I'll extend your thought about sending a command to be motion specific. Use a script ran on event start and end to send the event start/end to the other cameras via the web interface. This keeps all cameras monitored but could prove problematic. You could have multiple event start calls, motion moves from camera to camera but the event gets ended prematurely, etc. You might have to experiment a bit with it and possibly incorporate some form of tracking (think lockfile(s)) in the script to know when an event is already going and when to end.

**Comment by josvanr** [comment]
Oh ok sorry :)

Aha I didn't know that with the webinterface, good idea. Will try...

**Comment by angrycoding** [comment]
That might give you a little bit funny results in case if those cams are using different framerate :)
