### ISSUE TITLE
Authentication login page keep asking for password

### ISSUE THREAD

**Issue by ade-x1** [Motion-Project/motion#1086]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: both
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: raspberry
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Stretch

Hello guys, both with the version provided by the repo and with the latest 4.2.2 compiled from source I have a login issue. 

If I use firefox I am able to login to my raspberry and look the camera live without issue, if I try from Safari (desktop or mobile) the page keep asking for the username and password (even if is correct).

This happens both if I select MD5 or basic auth.

Any suggestions?

**Comment by tosiara** [comment]
Could you clarify about "MD5"? Where do you select it?

**Comment by ade-x1** [comment]
Hello @tosiara , the MD5 setting is:

stream_auth_method 2

Then I have also set:

webcontrol_authentication myusername:mypassword

Thanks!

**Comment by tosiara** [comment]
I could only test with very old Safari version - 6.1.6, and it worked fine
What version of desktop Safari are you using?

**Comment by ade-x1** [comment]
Hey @tosiara , I am currently traveling in holiday and I don’t have my mac with me. However I am running the latest version of safari on Catalina and I am using the latest iOS version on an iPhone 7 (iOS 13.13)

**Comment by ade-x1** [comment]
I just tried on Chrome on iOS with version

79.0.3945.73

Same issue there too, keeps asking for the credentials ( which are 100% correct as they are my name and surname )

**Comment by tosiara** [comment]
Verified Safari 12.1.2 - no issues
If you wish to troubleshoot the issue make sure you are not using proxy and provide Wireshark network trace

**Comment by davidkingzyb** [comment]
Same problem, I solve it by setting stream_auth_method 1.
