### ISSUE TITLE
 Unable to open camera: Server returned 401 Unauthorized (authorization failed)

### ISSUE THREAD

**Issue by AndreB52** [Motion-Project/motion#1089]
0. Reviewed guide and contributing documents? (Yes/No):yes
1. version [x.y.z, hash, other]: motionEyeOS 20190911
2. installed as a package or compiled from sources [deb, rpm, git, other]: package
3. standalone or part of third party [motion, MotionEyeOS, other]: MotioneyeOS
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: netcam evziz C4S rtsp
5. hardware [x86, ARM, other]: 
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 

Title says it all.
I am using  aan EZVIZ netcam C4S
As far as I know default login is admin
                           default password is the verificationcode
(I have used the login/passwordsettings in the evziz app where it works correctly)
URL is rtsp://ipadress/
Tried every configuration I could find but keep getting a grey screen.
Even tried using an older MotioneyeOS
The logs tells me that there is an authentication failure
Don't know what to do anymore.

[dmesg.log](https://github.com/Motion-Project/motion/files/4016163/dmesg.log)
[messages.log](https://github.com/Motion-Project/motion/files/4016165/messages.log)
[motioneye.log](https://github.com/Motion-Project/motion/files/4016166/motioneye.log)
[motion.log](https://github.com/Motion-Project/motion/files/4016167/motion.log)

**Comment by tosiara** [comment]
Are you able to access your camera using `ffplay` from the same box?

**Comment by AndreB52** [comment]
Sorry forgot to mention that.
I have tried it in VLC. Got the same error. 
VLC keeps asking for login and pw.
But I am pretty sure that the default login an pw are the right ones. Camera is new out of the box. No modifications made. 
In the Lan area of the ezviz app it works flawless. Login name (admin) is already filled in by default there.

**Comment by AndreB52** [comment]
I close the issue. Abandoned motioneye os. Switched to hardware nvr. C4s worked perfect now
