### ISSUE TITLE
How to execute Python scripts using on_motion_detected or on_movie_start?

### ISSUE THREAD

**Issue by tejas-adg** [Motion-Project/motion#1091]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb, installed using dpkg
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mmal, PiCamera
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian (buster)

I would like to know how to use the `on_motion_detedted` and `on_movie_start` commands/tags.
I looked into the documentation ([here](https://motion-project.github.io/motion_config.html#on_movie_start)) and ([here](https://motion-project.github.io/motion_config.html#on_motion_detected)) it seems confusing and unclear.
Could someone please help, I am looking to run a python script on the above events occuring
Thank you

**Comment by tejas-adg** [comment]
An addition to the above issue, I would like to run a python script, if not would like to know how to use it to run a bash script

**Comment by tosiara** [comment]
What exactly is confusing and unclear? Which value did you try to put and which error did you get?

**Comment by tejas-adg** [comment]
How does it work? 
What kind of command is he supplied? 
How is that command (the string written after the tag in config) executed?

These are my questions

**Comment by tosiara** [comment]
`/usr/bin/python /home/user/myscript.py`

**Comment by tejas-adg** [comment]
Tried and doesn’t work

**Comment by shaven** [comment]
You might try creating a bash script file and making it executable. That way you can verify that the file will run separately from motion.

**Comment by tejas-adg** [comment]
> on_movie_start /usr/bin/python /home/user/myscript.py

why cannot the same work with on_motion_detected?

**Comment by tejas-adg** [comment]
> You might try creating a bash script file and making it executable. That way you can verify that the file will run separately from motion.

Yeah tried that, works as expected in the terminal, does not at all work when put in the motion config file.

**Comment by tejas-adg** [comment]
Also, is there a way of seeing an output?
Like if I say `echo "Hello there"` where can I see the output?

**Comment by shaven** [comment]
You could do something like

- echo "Hello There" > /tmp/on_movie_end.log

That put the output of the line into the log file.

**Comment by tejas-adg** [comment]
All right so I tried this and nothing happens not for movie end or movie start or on motion detected. I’m suspecting something wrong when the config file is read

> You could do something like
> 
> * echo "Hello There" > /tmp/on_movie_end.log
> 
> That put the output of the line into the log file.

**Comment by tejas-adg** [comment]
It still doesn’t work

**Comment by tosiara** [comment]
You did not provide any files, logs or screenshots. Github is used to track issues. For questions how to use motion there is a mail list

**Comment by agustinscaz** [comment]
Still not working... could you please take a look at your code... @tejas-adg did you find any solution?

**Comment by tejas-adg** [comment]
My solution was to let go of motion completely and use FFmpeg
