### ISSUE TITLE
movie start time

### ISSUE THREAD

**Issue by dia-de-muertos** [Motion-Project/motion#1092]
Hi,

ist there a a variable with the timestamp
of the movie/motion-detect start time?
Currently I pass %s to my external script:

`  on_movie_end /opt/bin/convert.sh %f %s`

But %s contains the time when the movie
was saved/ended.
Any chance to get the start timestamp?

**Comment by tosiara** [comment]
No, motion does not have a variable with motion start time. But you can run a script ` on_motion_detected` and save the needed timestamp somewhere locally
