### ISSUE TITLE
Continuous recording issue with mmal and usb camera

### ISSUE THREAD

**Issue by JohanD78** [Motion-Project/motion#1093]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: package 
3. standalone or part of third party [motion, MotionEyeOS, other]: MotioneyeOS
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: MMAL
5. hardware [x86, ARM, other]: Rpi 3B and RPi4 4GB
6. operating system [16.04, Stretch, etc, FreeBSD, other]: MotioneyeOS

I have a issue with continuous recording on my rpi´s and it shows itself by only recording a single video of selected length and then stops. 
If i set 10 Seconds it records 10 seconds and stops. If i set 3600 seconds it recordes fine for an hour but then stops.

I have mine setup to use 600 seconds continuous recording with 2 days retention and i know for sure it worked with motioneyeOS up untill their 20191010 dev build. After that i just know that the December builds have had this issue.

Issue where reported to motioneyeOS here: https://github.com/ccrisan/motioneyeos/issues/2235

I have followed the motioneyeOS advice on testing and running motion isolated, per instructions from this page. https://github.com/ccrisan/motioneyeos/wiki/Report-Motion-Issue and the issue remains

Attached are the relevant logs.

[logs.zip](https://github.com/Motion-Project/motion/files/4050910/logs.zip)

**Comment by tosiara** [comment]
By `motion stops` you mean motion continues to run and continues to detect, but does not record movies?

**Comment by JohanD78** [comment]
Yes, that is correct.

**Comment by hgw77** [comment]
I have the same problem and reported the issue here ccrisan/motioneye#1653

**Comment by tosiara** [comment]
Are you also running mmal? Can you provide detailed logs?

**Comment by JohanD78** [comment]
Actually never tried a USB cam. Doing that now, with csi cam also hooked up and will report back when done testing that.

**Comment by JohanD78** [comment]
That was a quick test. Same problem with usb cam. First movie, set to max leanght of  20 seconds, finish as it should but it wont save anything after it.

What commands do u want me to put into shell and ill post logs.

**Comment by tosiara** [comment]
Try to run motion with USB camera only with `-d 7` switch, reproduce the issue and upload the fresh log

**Comment by JohanD78** [comment]
Sorry for delay.
Here is logs with latest dev version 200223 with only usb cam attached

[camera-1.zip](https://github.com/Motion-Project/motion/files/4301930/camera-1.zip)

**Comment by tosiara** [comment]
Can you change `movie_codec` to a default one and retry your test? Does it work that way?

**Comment by JohanD78** [comment]
Tried all codecs, same outcome

**Comment by tosiara** [comment]
Can you build the latest motion from sources and upload the new log with the default codec used?

**Comment by JohanD78** [comment]
I am a windows user with very poor linux skills. I will wait for ccrisan to update motioneyeos and try out next dev build.
