### ISSUE TITLE
Stream hls, mp4 etc.

### ISSUE THREAD

**Issue by DewGew** [Motion-Project/motion#1098]
Is it possible to get a stream url to send to Google Assisant with smart home server. Just need to send a stream url.

The stream would have to be in one of the following protocols (ie, not mjpg):

HLS (HTTP Live Streaming)
DASH (Dynamic Adaptive Streaming over HTTP)
Smooth Streaming
Progressive MP4 (most likely to be used only for Clips)
https://developers.google.com/actions/smarthome/traits/camerastream

Example convert rtsp to hls or mp4 using ffmpeg:

```
ffmpeg -rtsp_transport tcp -i rtsp://admin:123456@192.168.0.218/live/ch1 \
  -acodec copy \
  -vcodec copy \
  -hls_wrap 40 \
  -flags -global_header \
  /var/www/html/cam/cam.m3u8
```
```
ffmpeg -rtsp_transport tcp -i rtsp://admin:123456@192.168.0.218/live/ch1 \
  -c:a aac \
  -vcodec copy \
  -f mp4 \
  -y \
  -flags -global_header \
  /var/www/html/cam/cam.mp4
```

**Comment by tosiara** [comment]
Motion only provides mjpeg
