### ISSUE TITLE
Brightness slowly decreases, then increases

### ISSUE THREAD

**Issue by RichMStudios** [Motion-Project/motion#1099]
Hello, this might not be entirely a Motion issue, but here's the problem.
I have the timelapse activated, and I noticed that the brightness of the timelapse video decreases and then increases; this is happening throughout the entire timelapse.
I have auto brightness off as I believe it might not fix the issue.
Here's a part of the timelapse (it's a recording of our garden, the sun was setting at the moment. I expected a timelapse where the brightness would just slowly fade.) 
https://drive.google.com/open?id=1Ed9ytE6bPFhPpoh3HGU7RazhSkOAQt0H

**Comment by tosiara** [comment]
Maybe it's your camera auto adjusting exposure? Try to disable using `vid_control_params`
