### ISSUE TITLE
Possible way to lower CPU / MEM usage when using passtrough

### ISSUE THREAD

**Issue by angrycoding** [Motion-Project/motion#1100]
Hi,

I've got an idea how to decrease resource usage when using passthrough. So when using passthrough we have two different streams. One is used for detection only and another one is used to record the video. What if it would be possible to decrease FPS on motion detection stream to let's say one frame per second and in the mean time use normal FPS on the high res stream (let's say 25 fps). Then motion would need a lot less resources to catch only one frame per second and compare those two frames rather than doing it 25 times per second.

Now problem is that there is some weird behaviour when I'm trying to do that. I'm not sure what is happening, but setting low-res stream to 1fps gives me really really wrong duration of the movies recorded from the high-res stream.

What am I doing wrong? Or currently it's not possible to set different fps on low and high -res stream?

**Comment by tosiara** [comment]
Motion already has built-in hardcoded limitation for motion detection - 3fps

**Comment by tosiara** [comment]
Here: https://github.com/Motion-Project/motion/blob/master/src/motion.c#L1868

**Comment by angrycoding** [comment]
> Here: https://github.com/Motion-Project/motion/blob/master/src/motion.c#L1868

In other words there is nothing has to be done in the config right? It will limit low-res stream fps to 3 by itself?

**Comment by tosiara** [comment]
Yes, correct

**Comment by angrycoding** [comment]
> Yes, correct

Cool thanks!
