### ISSUE TITLE
USB cameras with Nanopi M4 using motion package

### ISSUE THREAD

**Issue by priyankajadli** [Motion-Project/motion#1101]
I am using 3 low light HD USB cameras (details on the link below) for my application. https://bluerobotics.com/store/sensors-sonars-cameras/cameras/cam-usb-low-light-r1/
The application requires me to have all 3 cameras live streaming simultaneously on 3 different local host ports of a PC. For the controller, I am using a Nanopi M4 (it is connected to my laptop by a 20m long, CAT-6 ethernet cable)
I am using the motion package to work the cameras

These are the problems I faced - 
1. When all 3 cameras are connected to controller and stream is checked, at any given time I am able to see the livestream of only 2 of the streams. On restarting motion, any one of the hosts shows a grey screen while the other two give me the proper stream. I have tested this multiple times and would appreciate if help on how to go about this issue
We also tried connecting the cameras to my laptop directly using threads in my motion package and all the 3 streams were visible to me simultaneously
2. A few of the times the port number (seen on dev in the form - video0) have changed while the cameras have been plugged in and left as it is. If anyone has come across this problem, please tell me how you went about this
3. Attached below is a screenshot of the Tcptrack app when all three cameras were connected at 100% stream quality (set in the motion.conf file)
![tcptrack](https://user-images.githubusercontent.com/52131313/73630710-e334d180-467c-11ea-9ef5-e8c5ca243bd9.JPG)

The first three rows represent each camera and the rates are unequal for all of them which is not expected. Can anyone help me with a possible explanation to this?
Also when that screenshot was taken, the camera streaming to localhost 8083, was showing up as a grey screen on my laptop, so what is the rate signifying?

Also, to make sure there were no problems with the Nanopi M4 USB ports sourcing the current drawn by the cameras, we gave an external 5V power supply to them – We could only see any 2 out of 3 streams

I have also attached a screenshot from my Nanopi M4 Top showing the CPU usage when all three cameras were connected to stream at 100% quality
![top](https://user-images.githubusercontent.com/52131313/73630729-f182ed80-467c-11ea-9132-ae4c568b3a40.JPG)

4. As a last resort, if we are only able to work 2 cameras at a time, please advise if anyone has used switching between the three cameras to choose which ones stay on at any given time

Thank you for your time

**Comment by tosiara** [comment]
Do you get any error related to USB in `dmesg`. Like `no space left on device`? http://www.ideasonboard.org/uvc/faq/

**Comment by priyankajadli** [comment]
Hey, sorry for the late reply
I have verified the what you suggested but I don't see any error regarding space on the device
![image](https://user-images.githubusercontent.com/52131313/73843135-0bbaf800-4844-11ea-83ea-f421ebe29435.png)

**Comment by tosiara** [comment]
Please upload the full `dmesg`

**Comment by priyankajadli** [comment]
This is the complete dmesg, starting from when none of the cameras are connected, till when all of them have been
Correct me if I'm wrong, this isn't my area of expertise. But these are the problems I see -
1. I see the bandwidth issue (for altsetting? Any idea what this is?) that wasn't there for the first two cameras in the below code
2. [  310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84                                                                                                                   
    [  320.677421] uvcvideo: Failed to resubmit video URB (-1).
Please tell me if I'm missing something else or if any of these would not affect the working of the camera
Meanwhile I am also trying to look into it
All help will be appreciated

`[  281.994025] usb 5-1.3: new high-speed USB device number 6 using xhci-hcd                                                                                                 [  282.197578] usb 5-1.3: New USB device found, idVendor=05a3, idProduct=9422                                                                                               [  282.197626] usb 5-1.3: New USB device strings: Mfr=2, Product=1, SerialNumber=3                                                                                          [  282.197650] usb 5-1.3: Product: H264 USB Camera                                                                                                                          [  282.197672] usb 5-1.3: Manufacturer: Sonix Technology Co., Ltd.                                                                                                          [  282.197694] usb 5-1.3: SerialNumber: SN0001                                                                                                                              [  282.209310] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422)                                                                                                  [  282.247744] uvcvideo: Unable to create debugfs 5-6 directory.                                                                                                            [  282.250676] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.3/5-1.3:1.0/input/input6                                         [  282.291742] usb 5-1.3: 4:1: cannot get freq at ep 0x84                                                                                                                   [  309.862303] usb 5-1.2: new high-speed USB device number 7 using xhci-hcd                                                                                                 [  310.066212] usb 5-1.2: New USB device found, idVendor=05a3, idProduct=9422                                                                                               [  310.066250] usb 5-1.2: New USB device strings: Mfr=2, Product=1, SerialNumber=3                                                                                          [  310.066260] usb 5-1.2: Product: H264 USB Camera                                                                                                                          [  310.066268] usb 5-1.2: Manufacturer: Sonix Technology Co., Ltd.                                                                                                          [  310.066373] usb 5-1.2: SerialNumber: SN0001                                                                                                                              [  310.080516] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422)                                                                                                  [  310.122203] uvcvideo: Unable to create debugfs 5-7 directory.                                                                                                            [  310.123972] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.2/5-1.2:1.0/input/input7                                         [  310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84                                                                                                                   [  320.677421] uvcvideo: Failed to resubmit video URB (-1).                                                                                                                 [  340.327792] usb 5-1.4: new high-speed USB device number 8 using xhci-hcd                                                                                                 [  340.535685] usb 5-1.4: New USB device found, idVendor=05a3, idProduct=9422                                                                                               [  340.535721] usb 5-1.4: New USB device strings: Mfr=2, Product=1, SerialNumber=3                                                                                          [  340.535729] usb 5-1.4: Product: H264 USB Camera                                                                                                                          [  340.535736] usb 5-1.4: Manufacturer: Sonix Technology Co., Ltd.                                                                                                          [  340.535744] usb 5-1.4: SerialNumber: SN0001                                                                                                                              [  340.546671] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422)                                                                                                  [  340.596071] uvcvideo: Unable to create debugfs 5-8 directory.                                                                                                            [  340.610087] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.4/5-1.4:1.0/input/input8                                         [  340.661870] usb 5-1.4: 4:1: cannot get freq at ep 0x84                                                                                                                   [  347.641745] usb 5-1.4: Not enough bandwidth for new device state.                                                                                                        [  347.641828] usb 5-1.4: Not enough bandwidth for altsetting 5 
![dmesg](https://user-images.githubusercontent.com/52131313/73915498-825a0300-48e1-11ea-9d43-22e5ff0f730c.JPG)
`

**Comment by priyankajadli** [comment]
This is the complete dmesg, starting from when none of the cameras are connected, till when all of them have been
Correct me if I'm wrong, this isn't my area of expertise. But these are the problems I see -
1. I see the bandwidth issue (for altsetting? Any idea what this is?) that wasn't there for the first two cameras in the below code
2. [  310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84                                                                                                                   
    [  320.677421] uvcvideo: Failed to resubmit video URB (-1).
Please tell me if I'm missing something else or if any of these would not affect the working of the camera
Meanwhile I am also trying to look into it
All help will be appreciated

`[  281.994025] usb 5-1.3: new high-speed USB device number 6 using xhci-hcd                                                                                                 [  282.197578] usb 5-1.3: New USB device found, idVendor=05a3, idProduct=9422                                                                                               [  282.197626] usb 5-1.3: New USB device strings: Mfr=2, Product=1, SerialNumber=3                                                                                          [  282.197650] usb 5-1.3: Product: H264 USB Camera                                                                                                                          [  282.197672] usb 5-1.3: Manufacturer: Sonix Technology Co., Ltd.                                                                                                          [  282.197694] usb 5-1.3: SerialNumber: SN0001                                                                                                                              [  282.209310] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422)                                                                                                  [  282.247744] uvcvideo: Unable to create debugfs 5-6 directory.                                                                                                            [  282.250676] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.3/5-1.3:1.0/input/input6                                         [  282.291742] usb 5-1.3: 4:1: cannot get freq at ep 0x84                                                                                                                   [  309.862303] usb 5-1.2: new high-speed USB device number 7 using xhci-hcd                                                                                                 [  310.066212] usb 5-1.2: New USB device found, idVendor=05a3, idProduct=9422                                                                                               [  310.066250] usb 5-1.2: New USB device strings: Mfr=2, Product=1, SerialNumber=3                                                                                          [  310.066260] usb 5-1.2: Product: H264 USB Camera                                                                                                                          [  310.066268] usb 5-1.2: Manufacturer: Sonix Technology Co., Ltd.                                                                                                          [  310.066373] usb 5-1.2: SerialNumber: SN0001                                                                                                                              [  310.080516] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422)                                                                                                  [  310.122203] uvcvideo: Unable to create debugfs 5-7 directory.                                                                                                            [  310.123972] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.2/5-1.2:1.0/input/input7                                         [  310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84                                                                                                                   [  320.677421] uvcvideo: Failed to resubmit video URB (-1).                                                                                                                 [  340.327792] usb 5-1.4: new high-speed USB device number 8 using xhci-hcd                                                                                                 [  340.535685] usb 5-1.4: New USB device found, idVendor=05a3, idProduct=9422                                                                                               [  340.535721] usb 5-1.4: New USB device strings: Mfr=2, Product=1, SerialNumber=3                                                                                          [  340.535729] usb 5-1.4: Product: H264 USB Camera                                                                                                                          [  340.535736] usb 5-1.4: Manufacturer: Sonix Technology Co., Ltd.                                                                                                          [  340.535744] usb 5-1.4: SerialNumber: SN0001                                                                                                                              [  340.546671] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422)                                                                                                  [  340.596071] uvcvideo: Unable to create debugfs 5-8 directory.                                                                                                            [  340.610087] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.4/5-1.4:1.0/input/input8                                         [  340.661870] usb 5-1.4: 4:1: cannot get freq at ep 0x84                                                                                                                   [  347.641745] usb 5-1.4: Not enough bandwidth for new device state.                                                                                                        [  347.641828] usb 5-1.4: Not enough bandwidth for altsetting 5 
![dmesg](https://user-images.githubusercontent.com/52131313/73915498-825a0300-48e1-11ea-9d43-22e5ff0f730c.JPG)
`
![dmesg](https://user-images.githubusercontent.com/52131313/73915850-33f93400-48e2-11ea-80ce-4bc27679d0fc.JPG)

**Comment by priyankajadli** [comment]
This is the complete dmesg, starting from when none of the cameras are connected, till when all of them have been
Correct me if I'm wrong, this isn't my area of expertise. But these are the problems I see -

I see the bandwidth issue (for altsetting? Any idea what this is?) that wasn't there for the first two cameras in the below code
[ 310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84
[ 320.677421] uvcvideo: Failed to resubmit video URB (-1).
Please tell me if I'm missing something else or if any of these would not affect the working of the camera
Meanwhile I am also trying to look into it
All help will be appreciated
[ 281.994025] usb 5-1.3: new high-speed USB device number 6 using xhci-hcd [ 282.197578] usb 5-1.3: New USB device found, idVendor=05a3, idProduct=9422 [ 282.197626] usb 5-1.3: New USB device strings: Mfr=2, Product=1, SerialNumber=3 [ 282.197650] usb 5-1.3: Product: H264 USB Camera [ 282.197672] usb 5-1.3: Manufacturer: Sonix Technology Co., Ltd. [ 282.197694] usb 5-1.3: SerialNumber: SN0001 [ 282.209310] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422) [ 282.247744] uvcvideo: Unable to create debugfs 5-6 directory. [ 282.250676] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.3/5-1.3:1.0/input/input6 [ 282.291742] usb 5-1.3: 4:1: cannot get freq at ep 0x84 [ 309.862303] usb 5-1.2: new high-speed USB device number 7 using xhci-hcd [ 310.066212] usb 5-1.2: New USB device found, idVendor=05a3, idProduct=9422 [ 310.066250] usb 5-1.2: New USB device strings: Mfr=2, Product=1, SerialNumber=3 [ 310.066260] usb 5-1.2: Product: H264 USB Camera [ 310.066268] usb 5-1.2: Manufacturer: Sonix Technology Co., Ltd. [ 310.066373] usb 5-1.2: SerialNumber: SN0001 [ 310.080516] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422) [ 310.122203] uvcvideo: Unable to create debugfs 5-7 directory. [ 310.123972] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.2/5-1.2:1.0/input/input7 [ 310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84 [ 320.677421] uvcvideo: Failed to resubmit video URB (-1). [ 340.327792] usb 5-1.4: new high-speed USB device number 8 using xhci-hcd [ 340.535685] usb 5-1.4: New USB device found, idVendor=05a3, idProduct=9422 [ 340.535721] usb 5-1.4: New USB device strings: Mfr=2, Product=1, SerialNumber=3 [ 340.535729] usb 5-1.4: Product: H264 USB Camera [ 340.535736] usb 5-1.4: Manufacturer: Sonix Technology Co., Ltd. [ 340.535744] usb 5-1.4: SerialNumber: SN0001 [ 340.546671] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422) [ 340.596071] uvcvideo: Unable to create debugfs 5-8 directory. [ 340.610087] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.4/5-1.4:1.0/input/input8 [ 340.661870] usb 5-1.4: 4:1: cannot get freq at ep 0x84 [ 347.641745] usb 5-1.4: Not enough bandwidth for new device state. [ 347.641828] usb 5-1.4: Not enough bandwidth for altsetting 5 

![image](https://user-images.githubusercontent.com/52131313/73915974-7c185680-48e2-11ea-8530-b8c675b51563.png)

**Comment by priyankajadli** [comment]
This is the complete dmesg, starting from when none of the cameras are connected, till when all of them have been
Correct me if I'm wrong, this isn't my area of expertise. But these are the problems I see -

I see the bandwidth issue (for altsetting? Any idea what this is?) that wasn't there for the first two cameras in the below code
[ 310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84
[ 320.677421] uvcvideo: Failed to resubmit video URB (-1).
Please tell me if I'm missing something else or if any of these would not affect the working of the camera
Meanwhile I am also trying to look into it
All help will be appreciated
[ 281.994025] usb 5-1.3: new high-speed USB device number 6 using xhci-hcd [ 282.197578] usb 5-1.3: New USB device found, idVendor=05a3, idProduct=9422 [ 282.197626] usb 5-1.3: New USB device strings: Mfr=2, Product=1, SerialNumber=3 [ 282.197650] usb 5-1.3: Product: H264 USB Camera [ 282.197672] usb 5-1.3: Manufacturer: Sonix Technology Co., Ltd. [ 282.197694] usb 5-1.3: SerialNumber: SN0001 [ 282.209310] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422) [ 282.247744] uvcvideo: Unable to create debugfs 5-6 directory. [ 282.250676] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.3/5-1.3:1.0/input/input6 [ 282.291742] usb 5-1.3: 4:1: cannot get freq at ep 0x84 [ 309.862303] usb 5-1.2: new high-speed USB device number 7 using xhci-hcd [ 310.066212] usb 5-1.2: New USB device found, idVendor=05a3, idProduct=9422 [ 310.066250] usb 5-1.2: New USB device strings: Mfr=2, Product=1, SerialNumber=3 [ 310.066260] usb 5-1.2: Product: H264 USB Camera [ 310.066268] usb 5-1.2: Manufacturer: Sonix Technology Co., Ltd. [ 310.066373] usb 5-1.2: SerialNumber: SN0001 [ 310.080516] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422) [ 310.122203] uvcvideo: Unable to create debugfs 5-7 directory. [ 310.123972] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.2/5-1.2:1.0/input/input7 [ 310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84 [ 320.677421] uvcvideo: Failed to resubmit video URB (-1). [ 340.327792] usb 5-1.4: new high-speed USB device number 8 using xhci-hcd [ 340.535685] usb 5-1.4: New USB device found, idVendor=05a3, idProduct=9422 [ 340.535721] usb 5-1.4: New USB device strings: Mfr=2, Product=1, SerialNumber=3 [ 340.535729] usb 5-1.4: Product: H264 USB Camera [ 340.535736] usb 5-1.4: Manufacturer: Sonix Technology Co., Ltd. [ 340.535744] usb 5-1.4: SerialNumber: SN0001 [ 340.546671] uvcvideo: Found UVC 1.00 device H264 USB Camera (05a3:9422) [ 340.596071] uvcvideo: Unable to create debugfs 5-8 directory. [ 340.610087] input: H264 USB Camera as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.9.auto/usb5/5-1/5-1.4/5-1.4:1.0/input/input8 [ 340.661870] usb 5-1.4: 4:1: cannot get freq at ep 0x84 [ 347.641745] usb 5-1.4: Not enough bandwidth for new device state. [ 347.641828] usb 5-1.4: Not enough bandwidth for altsetting 5
![image](https://user-images.githubusercontent.com/52131313/73916201-fc3ebc00-48e2-11ea-8354-9a4f0fd6388d.png)

**Comment by priyankajadli** [comment]
This is the complete dmesg, starting from when none of the cameras are connected, till when all of them have been
Correct me if I'm wrong, this isn't my area of expertise. But these are the problems I see -

I see the bandwidth issue (for altsetting? Any idea what this is?) that wasn't there for the first two cameras in the below code
[ 310.164923] usb 5-1.2: 4:1: cannot get freq at ep 0x84
[ 320.677421] uvcvideo: Failed to resubmit video URB (-1).
Please tell me if I'm missing something else or if any of these would not affect the working of the camera
Meanwhile I am also trying to look into it
All help will be appreciated

![image](https://user-images.githubusercontent.com/52131313/73916292-33ad6880-48e3-11ea-9429-a885f7c3b5d2.png)

**Comment by tosiara** [comment]
`Failed to resubmit video URB` indicates issues with USB. Ant it is clearly printed `Not enough bandwidth` - this is USB limitation for uncompressed stream. Try to configure motion to use MJPEG pixel format

**Comment by priyankajadli** [comment]
I tried starting from the lowest resolution and increased it gradually. I am able to see the livestream of all the 3 cameras up to the width x height of 384 x 288. Attached below is the dmesg that I get at that resolution with all 3 working at 100% stream quality 
![image](https://user-images.githubusercontent.com/52131313/74331039-d456c900-4db8-11ea-97b7-8d8f5b6fcf77.png)

The bandwidth error is gone now
I tried to find more information about the 'Failed to resubmit video URB (-19)' error, but couldn't find anything particularly useful. I would appreciate help on this

But there are a few other issues
1. Is there a way for me to increase the resolution and still have the three cameras working? The stream window is really small right now, and my application requires to monitor details regarding the surroundings on it, which is proving to be difficult right now. I mean to ask if there is any other way we can reduce the bandwidth used or is it fixed and only dependent on the cameras (hardware), assuming that is the only issue here?
Below is the 384 x 288 resolution window
![image](https://user-images.githubusercontent.com/52131313/74331129-0a944880-4db9-11ea-8647-9a52b31e0fec.png)

2. There are times when the cameras are plugged in and the nanopi m4 reboots, that the video device of the third camera changes from video18 to video19 whereas those of camera1 and camera2 remain what they were. Can anyone point out a way to avoid this because in my application, the end user at the workstation will be unable to troubleshoot and check for video device changing every time the streams stops.

**Comment by priyankajadli** [comment]
tried starting from the lowest resolution and increased it gradually. I am able to see the livestream of all the 3 cameras up to the width x height of 384 x 288. Attached below is the dmesg that I get at that resolution with all 3 working at 100% stream quality
![image](https://user-images.githubusercontent.com/52131313/74331366-9017f880-4db9-11ea-8609-120ae588c669.png)

The bandwidth error is gone now
I tried to find more information about the 'Failed to resubmit video URB (-19)' error, but couldn't find anything particularly useful. I would appreciate help on this

But there are a few other issues

Is there a way for me to increase the resolution and still have the three cameras working? The stream window is really small right now, and my application requires to monitor details regarding the surroundings on it, which is proving to be difficult right now. I mean to ask if there is any other way we can reduce the bandwidth used or is it fixed and only dependent on the cameras (hardware), assuming that is the only issue here?

There are times when the cameras are plugged in and the nanopi m4 reboots, that the video device of the third camera changes from video18 to video19 whereas those of camera1 and camera2 remain what they were. Can anyone point out a way to avoid this because in my application, the end user at the workstation will be unable to troubleshoot and check for video device changing every time the streams stops.

**Comment by priyankajadli** [comment]
Below is the 384 x 288 window
![384 x 288](https://user-images.githubusercontent.com/52131313/74331457-b6d62f00-4db9-11ea-8355-df06f5f50181.JPG)

**Comment by priyankajadli** [comment]
tried starting from the lowest resolution and increased it gradually. I am able to see the livestream of all the 3 cameras up to the width x height of 384 x 288. Attached below is the dmesg that I get at that resolution with all 3 working at 100% stream quality
![image](https://user-images.githubusercontent.com/52131313/74331599-04529c00-4dba-11ea-8a76-e412ab730a7d.png)


The bandwidth error is gone now
I tried to find more information about the 'Failed to resubmit video URB (-19)' error, but couldn't find anything particularly useful. I would appreciate help on this

But there are a few other issues

Is there a way for me to increase the resolution and still have the three cameras working? The stream window is really small right now, and my application requires to monitor details regarding the surroundings on it, which is proving to be difficult right now. I mean to ask if there is any other way we can reduce the bandwidth used or is it fixed and only dependent on the cameras (hardware), assuming that is the only issue here?

There are times when the cameras are plugged in and the nanopi m4 reboots, that the video device of the third camera changes from video18 to video19 whereas those of camera1 and camera2 remain what they were. Can anyone point out a way to avoid this because in my application, the end user at the workstation will be unable to troubleshoot and check for video device changing every time the streams stops.

**Comment by priyankajadli** [comment]
I tried starting from the lowest resolution and increased it gradually. I am able to see the livestream of all the 3 cameras up to the width x height of 384 x 288. Attached below is the dmesg that I get at that resolution with all 3 working at 100% stream quality
![dmesgafterworking](https://user-images.githubusercontent.com/52131313/74331718-45e34700-4dba-11ea-8a7f-a2b102b8afb3.JPG)


The bandwidth error is gone now
I tried to find more information about the ‘Failed to resubmit video URB (-19)’ error, but couldn’t find anything particularly useful. I would appreciate help on this
But there are a few other issues

Is there a way for me to increase the resolution and still have the three cameras working? The stream window is really small right now, and my application requires to monitor details regarding the surroundings on it, which is proving to be difficult right now. I mean to ask if there is any other way we can reduce the bandwidth used or is it fixed and only dependent on the cameras (hardware), assuming that is the only issue here?

There are times when the cameras are plugged in and the nanopi m4 reboots, that the video device of the third camera changes from video18 to video19 whereas those of camera1 and camera2 remain what they were. Can anyone point out a way to avoid this because in my application, the end user at the workstation will be unable to troubleshoot and check for video device changing every time the streams stops.

**Comment by priyankajadli** [comment]
Below is the 384 x 288 resolution window
![384 x 288](https://user-images.githubusercontent.com/52131313/74331802-75924f00-4dba-11ea-8901-709892bd202c.JPG)
As you can see, it gets difficult to look for minute details on the stream

**Comment by priyankajadli** [comment]
Below is the 384 x 288 resolution window
![384 x 288](https://user-images.githubusercontent.com/52131313/74331802-75924f00-4dba-11ea-8901-709892bd202c.JPG)
As you can see, it gets difficult to look for minute details on the stream

**Comment by tosiara** [comment]
Have you tried `MJPEG`?

**Comment by priyankajadli** [comment]
Yes I tried MJPEG and this is the output I'm getting on all three cameras with highest stream quality, max frame rate and frame width x height = 1280 x 720

Camera 1  
![image](https://user-images.githubusercontent.com/52131313/76136933-29ef6000-605d-11ea-9bf9-5f6e80f577db.png)

Camera 2
![image](https://user-images.githubusercontent.com/52131313/76136959-691db100-605d-11ea-90ef-6998b39e0ee4.png)

Camera 3
![image](https://user-images.githubusercontent.com/52131313/76136966-7c308100-605d-11ea-8b24-f65fb37e8818.png)

This choppiness is like a dynamic disturbance on the streams. Kindly suggest how this can be dealt with

Below is my mask file (I don't want to detect motion. Only to show the stream as it is)
![image](https://user-images.githubusercontent.com/52131313/76136990-d3ceec80-605d-11ea-8483-e612c10ae4f7.png)
 
But when I change the stream to YU12, two streams work properly and the third one shows this
![image](https://user-images.githubusercontent.com/52131313/76137052-8acb6800-605e-11ea-899f-339eaf16aaf8.png)

Can't figure out what the cause could be

**Comment by tosiara** [comment]
You cannot use uncompressed pixel format with more than one camera. Only use MJPEG

**Comment by priyankajadli** [comment]
I request you to open this issue again so that if anyone else has faced this issue, they can provide solutions too

The cameras I am using provide onboard compression, is that helpful?
https://bluerobotics.com/store/sensors-sonars-cameras/cameras/cam-usb-low-light-r1/

On using MJPEG I see a choppiness in my feed but atleast all 3 are working (which doesn't happen when I use YU12 palette), which is great. But the disturbance is creating a problem

Can you suggest what could be causing this choppiness and disturbance in feed and how to deal with it?

Could it have something to do with the mask.pgm file?

**Comment by tosiara** [comment]
If you want to resolve "choppiness" and you really think this is because of motion bug, not because of the hardware used, please start a new issue and provide all the required logs
For motion usega questions you can also use mail list
