### ISSUE TITLE
motion 4.1.1 - snapshot

### ISSUE THREAD

**Issue by DieselDriver** [Motion-Project/motion#1103]
Hello,

I use motion 4.1.1 for my camera.

The motion detection works fine and every hour I take a snapshot with following command through the webif.

curl http://localhost:8080/0/action/snapshot

Is it possible that these snapshots will be taken with other parametes (x,y resolution and quality) than for normal snapshots made by the motion detection?

I want that some snapshot will be taken with highest resolution of the cam.

Thanks.

**Comment by tosiara** [comment]
No, there is no way to change the resolution of snapshots

**Comment by DieselDriver** [comment]
Ok, thanks.
**This would be a nice feature.**
As workaround I kill motion process, use raspistill for taking a snapshot and then I start motion again.
