### ISSUE TITLE
RTSP Connection fails sometimes but only when it is dark

### ISSUE THREAD

**Issue by hspaay** [Motion-Project/motion#1104]
I've looked through the mailing list and documents but did not find an issue related to connection failure when it is dark.

0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]:  deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motioneye
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  Ubuntu 19.10

Other info:
  ffmpeg version 4.1.4-1build2 
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100

Problem: 
Six Hikvision and Dahua cameras running motion via motioneye. Configured with rtsp, h264, frame rate is 2 at 1080p. During the day this setup works fine and the camera images all show. When it gets dark some cameras fail to connect via motion. It seems to be random. When restarting motioneye, usually the same cameras fail to connect but sometimes others fail and the ones that previously failed now work. Most of the time however, it is the same ones that fail. Disabling camera's until the few that fail are left does not make a difference.

In the morning, when daylight returns, the same cameras remain disconnected until a camera configuration is updated in motioneye, or motion is restarted.

VLC has no problem showing the camera stream that fails to connect so the camera continues to provide a rtsp stream.

My suspicion is that the cameras are slower to respond when it gets dark as their internal frame rate drops. Motion times out too quickly and assumes the connection fails. 

Is there a way to increase the timeout to connect to the camera?
Thanks,
Henk

Debug info:
```
[0:motion] [NTC] [ALL] main: Motion thread 1 restart
[0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 0 is from camera-5.conf
[0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 0 Camera Name: Cam 5 Service: rtsp:
[1:ml1:Cam 5] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
[1:ml1:Cam 5] [NTC] [VID] vid_start: Opening Netcam RTSP
[1:ml1:Cam 5] [INF] [NET] netcam_rtsp_set_parms: Setting up Normal resolution stream.
[1:ml1:Cam 5] [INF] [NET] netcam_url_parse: Using port number 554
[1:ml1:Cam 5] [INF] [NET] netcam_rtsp_set_path: Setting up rtsp via ffmpeg netcam
[1:ml1:Cam 5] [INF] [NET] netcam_rtsp_set_rtsp: Normal resolution: Setting rtsp transport to tcp
[1:ml1:Cam 5] [INF] [NET] netcam_rtsp_open_context: Normal resolution: Opened camera(Cam 5)
[1:ml1:Cam 5] [INF] [NET] netcam_rtsp_interrupt: Normal resolution: Camera (Cam 5) timed out
[1:ml1:Cam 5] [ERR] [NET] Above message repeats 1 times
[1:ml1:Cam 5] [ERR] [NET] netcam_rtsp_open_context: Normal resolution: Unable to find stream info: Success
[1:ml1:Cam 5] [INF] [NET] netcam_rtsp_interrupt: Normal resolution: Camera (Cam 5) timed out
[1:ml1:Cam 5] [INF] [NET] netcam_rtsp_cleanup: Normal resolution: Shutting down network camera.
[1:ml1:Cam 5] [NTC] [NET] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
[1:ml1:Cam 5] [ERR] [VID] vid_start: Netcam RTSP failed to open
[1:ml1:Cam 5] [WRN] [ALL] motion_init: Could not fetch initial image from camera 
[1:ml1:Cam 5] [WRN] [ALL] motion_init: Motion continues using width and height from config file(s)
[1:ml1:Cam 5] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
[1:ml1:Cam 5] [INF] [ALL] motion_init: Maskfile "/home/nuc1/motioneye/mask_5.pgm" loaded.
[1:ml1:Cam 5] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 7 items
[1:ml1:Cam 5] [WRN] [ALL] mlp_retry: Retrying until successful connection with camera
```

[camera-5.conf.txt](https://github.com/Motion-Project/motion/files/4151066/camera-5.conf.txt)

**Comment by tosiara** [comment]
Test with `ffplay`, not VLC

**Comment by hspaay** [comment]
Thank you for the suggestion tosiara.
I've updated the setting of one camera and after saving it three failed in motioneye. Using ffplay it took about a minute before the image showed up but after that it streamed fine. The stdout below:

$ ffplay rtsp://10.3.3.11/streaming/channels/1

ffplay version 4.1.4-1build2 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
  configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[rtsp @ 0x7fe684000bc0] max delay reached. need to consume packet   
[rtsp @ 0x7fe684000bc0] RTP: missed 46 packets
[h264 @ 0x7fe684004900] error while decoding MB 52 32, bytestream -11
[h264 @ 0x7fe684004900] concealing 4317 DC, 4317 AC, 4317 MV errors in P frame
[rtsp @ 0x7fe684000bc0] max delay reached. need to consume packet   
[rtsp @ 0x7fe684000bc0] RTP: missed 52 packets
[h264 @ 0x7fe684004900] error while decoding MB 3 32, bytestream -19
[h264 @ 0x7fe684004900] concealing 4366 DC, 4366 AC, 4366 MV errors in P frame
[rtsp @ 0x7fe684000bc0] max delay reached. need to consume packet   
[rtsp @ 0x7fe684000bc0] RTP: missed 64 packets
[h264 @ 0x7fe684004900] error while decoding MB 60 25, bytestream -7
[h264 @ 0x7fe684004900] concealing 5149 DC, 5149 AC, 5149 MV errors in P frame
[rtsp @ 0x7fe684000bc0] max delay reached. need to consume packet   
[rtsp @ 0x7fe684000bc0] RTP: missed 68 packets
Input #0, rtsp, from 'rtsp://10.3.3.11/streaming/channels/1':=0/0   
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 2.559644, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 6.25 tbr, 90k tbn, 180k tbc
[h264 @ 0x7fe684aada80] error while decoding MB 52 32, bytestream -11
[h264 @ 0x7fe684aada80] concealing 4317 DC, 4317 AC, 4317 MV errors in P frame
[swscaler @ 0x7fe67c33da80] deprecated pixel format used, make sure you did set range correctly
[h264 @ 0x7fe6854fd640] error while decoding MB 3 32, bytestream -19
[h264 @ 0x7fe6854fd640] concealing 4366 DC, 4366 AC, 4366 MV errors in P frame
[h264 @ 0x7fe6840401c0] error while decoding MB 60 25, bytestream -7
[h264 @ 0x7fe6840401c0] concealing 5149 DC, 5149 AC, 5149 MV errors in P frame
[h264 @ 0x7fe685456300] error while decoding MB 103 26, bytestream -9
[h264 @ 0x7fe685456300] concealing 4986 DC, 4986 AC, 4986 MV errors in P frame
   7.26 M-V:  0.046 fd=   0 aq=    0KB vq= 3371KB sq=    0B f=0/0

**Comment by tosiara** [comment]
If the camera fails to provide the stream in a timeout period - motion will time out, obviously. Try to tune your camera, maybe there is a setting for that

**Comment by hspaay** [comment]
Thank you for your explanation @tosiara. This is what I thought as well.
The question is whether this can be addressed by shortening a timeout or continuing after it has expried. I'm not clear what it is timing out on but it doesn't seem to be critical to viewing the stream as after the timeout has passed the stream can be viewed just fine with ffplay. VLC doesn't seem to be bothered by it so I think it is a ffmpeg default setting.
The problem is that motion or motioneye decides the camera can't produce an image while it can happily do so after the timeout expires. As  a result motion does not produce a video stream. IMHO this is a problem with motion, not the camera.
I hope that makes sense @tosiara. Please let me know if I can help in any way to resolve this.

**Comment by tosiara** [comment]
What do you think would be a reasonable time out value for motion until it should not try to restart the stream?

**Comment by hspaay** [comment]
@tosiara, that is a good question, so I did some further testing.

In short, the frame rate, exposure time, and h264/265 selection affect the timeout in ffplay. From the table below it looks like 30 seconds would be a workable timeout, although a bit higher like 60 seconds is preferred. I don't know what the impact would be on motion, so this is just my suggestion based on the measurements below.

My cameras are running at a 2-3 FPS with low exposure for night vision. This way motion can handle 8 cameras on a Intel Nuc :+1: 
For the 2CD3345-I Hik camera it looks like they must be run at 10 FPS with H265 otherwise the timeout kicks in.

These are the test results. The numbers at the end are the time in seconds before ffplay shows the image.
```
Camera 1 Hikvision DS-2CD3345-I
Exposure: Manual 1/3 second
| C/VBR | H264/265 | speed | FPS | IFrame | seconds delay  (multiple runs)
|-------|----------|-------|-----|--------|----------------------------|
| CBR   | H265     | 4Kbps |  2  |   2    |  78 77 77
| CBR   | H264     | 4Kbps |  2  |   2    |  64 69 74
| CBR   | H265     | 4Kbps |  4  |   4    |  40 45 43
| VBR   | H265     | 4Kbps |  4  |   4    |  40 45 44
| CBR   | H264     | 4Kbps |  4  |   4    |  52 52 48
| CBR   | H264     | 4Kbps |  4  |   1    |  54 53 52
| CBR   | H265     | 4Kbps |  4  |   1    |  42 43 42
| CBR   | H264     | 8Kbps |  4  |   4    |  52 50 50
| VBR   | H264     | 4Kbps |  10 |  10    |  25 25 25
| VBR   | H265     | 4Kbps |  10 |  10    |  20 21 20
| CBR   | H265     | 4Kbps |  10 |  10    |  21 25 22

This shows that FPS and H264/265 have the biggest impact on the timeout by ffplay.

Camera 5 Hikvision DS-2CD3345-I
Exposure: Manual 1/6 second
| C/VBR | H264/265 | speed | FPS | IFrame | seconds delay  (multiple runs)
|-------|----------|-------|-----|--------|----------------------------|
| CBR   | H265     | 4Kbps |  4  |   4    |  20 24 24

Camera 5 suggests that exposure settings could be a factor. Unfortunately I can't test this as these cameras need Active-X to run to modify exposure time and this doesn't seem to work any more in IE 11 or even an old Windows XP  :( 
If someone has API info for these cameras then that would help.
Thanks for your help @tosiara 

```

**Comment by tosiara** [comment]
So, you suggest 60 seconds of doing nothing for motion before it tries to reconnect?

**Comment by hspaay** [comment]
If the user can't see what is happening best to limit it to 30 seconds.
If there is a way to show that it is trying to connect, eg a dummy image or so, then yes 60 seconds would handle most cases.
Thanks again!
