### ISSUE TITLE
Error 401 accessing rtsp stream with blank password

### ISSUE THREAD

**Issue by roleoroleo** [Motion-Project/motion#1105]
0. Reviewed guide and contributing documents? Yes
1. version: motionEye Version | 0.36.1- Motion Version | 4.0.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: package
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86_64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: OS Version | Ubuntu 14.04

My cam runs with basic auth and blank password. I can't make it work: I get error 401.
I tried using username and password fields through motionEye and I tried the syntax rtsp://user:@IP-ADDRESS. No luck, the same error.
Unfortunately I can't change credentials on the cam.
Is there a solution I can try?

**Comment by tosiara** [comment]
Do you have motion log with `-d 7`?

**Comment by roleoroleo** [comment]
After upgrading to motionEye 0.42 and Motion 4.2.2, it works correctly.
Thank you.
