### ISSUE TITLE
Motion Camera ID's changing

### ISSUE THREAD

**Issue by D3nnisd** [Motion-Project/motion#1109]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]:  deb
3. standalone or part of third party [motion, MotionEyeOS, other]:  Motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  combination
5. hardware [x86, ARM, other]:  x64 i7 
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  Debian 

Since a few days, Camera ID's seem to be changing. This without stuff being added or removed. I use the API to pause or start a motiondetection, but as the ID changes, the API url breaks.

Is this a known issue?

Kind regards,

**Comment by tosiara** [comment]
Do you have corresponding log with `-d 7` that contains records from the process start till you notice ID change?
