### ISSUE TITLE
general protection error with "netcam_cleanup"

### ISSUE THREAD

**Issue by codefalk** [Motion-Project/motion#111]
The following protection error occurs SOMETIMES
`motion: [17] [ERR] [NET] netcam_cleanup: No response from camera handler - it must have already died
Jun 27 07:26:05 mx-hd kernel: [188690.467250] traps: motion[5070] general protection ip:425f3a sp:7f749bce6df0 error:0 in motion[400000+3d000]
`
when doing this:
- Camera lost connection, wait for a while (e.g. 8 minutes)
- set "CAM_THREAD/action/quit" in motion web interface
- camera does not reconnect

Log is not showing anything special before the netcam_cleanup. I worked around this by just not deactivating the camera before motion is able to clean the thread.

System is: Ubuntu 14.04 LTS with 3.13.0-88-generic, libav from repo, motion is current master

**Comment by jogu** [comment]
Can you retry with the latest master?

If it still crashes, can you try doing ulimit -c unlimited before running motion, then inspect the core file after to see what crashed (gdb ./motion <corefilename>     then "bt" and paste in all the output).

**Comment by Mr-Dave** [comment]
Please re-open if issue still occurs with current version.
