### ISSUE TITLE
Incorrect timing with low fps and movie_passthrough

### ISSUE THREAD

**Issue by angrycoding** [Motion-Project/motion#1110]
Related with the question asked here:
https://github.com/Motion-Project/motion/issues/1100
So in the issue tosiara said: "Motion already has built-in hardcoded limitation for motion detection - 3fps".
So I've set low-res stream on the camera itself to 3fps. Result is somehow looks strange, motion on the recorded videos starts way to late (approximately in the middle of the video). My config is:

pre_capture 1
minimum_motion_frames 5
framerate 25

cam config is:

camera_id 1
width 704
height 576
movie_passthrough on
netcam_url lowres_stream
netcam_highres highres_stream

Expected: motion records fragment with no motion for 1 second (3fps * precapture=1).
Actual: motion records fragment with no motion for about 9 seconds.

Looks like there are incorrect calculations somewhere inside the motion detector?

**Comment by tosiara** [comment]
Can you perform the same test but without passthrough?

**Comment by tosiara** [comment]
And clarify those statements:
```
So I've set low-res stream on the camera itself to 3fps
framerate 25
```

**Comment by angrycoding** [comment]
> Can you perform the same test but without passthrough?

Just set movie_passthrough to off in the config?

**Comment by angrycoding** [comment]
> And clarify those statements:
> 
> ```
> So I've set low-res stream on the camera itself to 3fps
> framerate 25
> ```

My IP camera has two streams, first one I use to pass it to netcam_highres and second one into netcam_url. Logging in into IP camera control panel, and setting second stream fps (which is used as low-res stream and passed to netcam_url) to 3. At the end first stream is 25fps, and second one is 3fps

**Comment by tosiara** [comment]
passthrough is not that precise as you may think, especially when you have two so different streams (with different frame rate). I think if you disable passthrough - you will get expected results
One more thing that you could try - configure both streams to have `I-frame` every 1 frame

**Comment by angrycoding** [comment]
Thanks, I'll try to set iframes to 1 on both streams (currently both are set to 2). Unfortunately disabling passthrough is not an option, as it will lead to really high CPU usage in my case.

**Comment by tosiara** [comment]
I made a test with a cheap BESDER camera that provides two streams: 1280x960@25 and 704x576@10. And I did not find any significant lag

First of all, `pre_capture 1` means 1 frame in current FPS. If you have 3fps, `pre_capture 1` means 1/3 of second

In my test I did not find any significant lag. With `pre_capture 75` I got ~6 seconds pre_captured. Which is pretty much close to my 10 fps and acceptable

Please reopen the issue if you have the exact steps to reproduce to replicate issue with streams that we could reach
