### ISSUE TITLE
Missing prebuild packages on releases page

### ISSUE THREAD

**Issue by angrycoding** [Motion-Project/motion#1111]
Hi, on the realeases page: https://github.com/Motion-Project/motion/releases
Missing prebuild packages (.deb, .rpm and so on) for version 4.3.0

**Comment by KarlBaumann** [comment]
confirm

**Comment by fkammere** [comment]
Still missing prebuild packages. 
Would be great if someone could add them.

**Comment by tosiara** [comment]
Motion-Project never provided any rpm, only deb packages which you can build yourself with a single command: https://github.com/Motion-Project/motion-packaging

**Comment by tosiara** [comment]
Since there is currently an issue with the build script, you should use this command to build deb package:
```
DEB_BUILD_OPTIONS=nocheck ./builddeb.sh
```
https://github.com/Motion-Project/motion-packaging/issues/8#issuecomment-590200706

**Comment by Pi-DD** [comment]
@tosiara - thanks for point at the builddeb.sh - never done it before, but because I need 4.3.0 and its implementation of "greyworld" parameter I took a small step into the unknown and used it. Worked perfectly! Thanks.

**Comment by angrycoding** [comment]
Unfortunately this buildeb.sh does not support linux mint (((

**Comment by tosiara** [comment]
Yes, only major platforms like Debian, Ubuntu and Raspbian are supported. We are open for a PR with developed and maintained Linux Mint build script.
For now you can build for Linux Mint with this change:
```
diff --git a/builddeb.sh b/builddeb.sh
index 2689b33..e7e9d97 100755
--- a/builddeb.sh
+++ b/builddeb.sh
@@ -44,6 +44,7 @@ if [ -z "$DISTO" ]; then
 fi
 
 if [ $DISTO != "Ubuntu" ] &&
+   [ $DISTO != "LinuxMint" ] &&
    [ $DISTO != "Debian" ] &&
    [ $DISTO != "Raspbian" ] ; then
   echo "This script is only functional for Debian, Ubuntu and Raspbian"
@@ -223,6 +224,8 @@ fi
     else
       git checkout 16.04
     fi
+  elif [ "$DISTO" = "LinuxMint" ]; then
+    git checkout master
   else
     echo "Unsupported Distribution: $DISTO"
     rm -rf $TEMPDIR
```

**Comment by tosiara** [comment]
I have built latest 4.3.1 and added binaries:
https://github.com/Motion-Project/motion/releases/tag/release-4.3.1
