### ISSUE TITLE
How to add openssl to the project

### ISSUE THREAD

**Issue by Shaker1978** [Motion-Project/motion#1114]
This is a question abour building motion from source, which worked when cloned on my Raspbian. More precise: I want to add a library to the project, but I am not familiar with autoconv and configure and make and all this. Please forgive me.

I need a pretty detailed set of instructions how to add openSSL to the project, so that I can use classes and types of openSSL in motion. This is not about the header files, but the library itself, because the project won't compile at the moment. I don't know where to put or change lines in the config or build files. Please help.

**Comment by tosiara** [comment]
For questions like this we have mail list, issue tracker is for issues

**Comment by Shaker1978** [comment]
I'm very sorry. How do I access the mail lists? And can I move the topic there?

**Comment by tosiara** [comment]
Take a look here: https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md

**Comment by Shaker1978** [comment]
Thanks, I'll try to figure out how this works, after I subscribed ;)
