### ISSUE TITLE
Segfault: free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by rdorsch** [Motion-Project/motion#1120]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb from Debian sid compiled for Debian buster 
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone motion 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: netcam_url file:// (but probably that does not matter)
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Debian 10

```
rd@master:~/Motion$ motion -c motion/motion.conf -d 9
[0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file motion/motion.conf
[0:motion] [ALR] [ALL] read_camera_dir: Camera directory config /home/rd/Motion/motion/conf-x.d not found: No such file or directory
[0:motion] [NTC] [ALL] read_camera_dir: Processing config file /home/rd/Motion/motion/conf.d/cam0-replay.conf
[0:motion] [NTC] [ALL] config_camera: Processing camera config file /home/rd/Motion/motion/conf.d/cam0-replay.conf
free(): double free detected in tcache 2
Aborted
rd@master:~/Motion$ 

```
I triggered this issue by adding a second camera_dir (the first one does not exist)
```

camera_dir /home/rd/Motion/motion/conf-x.d
camera_dir /home/rd/Motion/motion/conf.d
```

If you cannot repro and need further info, please let me know.

**Comment by tosiara** [comment]
Could you verify this on the latest 4.3 built from sources?

**Comment by rdorsch** [comment]
On Mittwoch, 26. Februar 2020 13:43:06 CET tosiara wrote:
> Could you verify this on the latest 4.3 built from sources?

Yes, it is still there:

rd@master:~/Motion$ ~/tmp.nobackup/git/motion/src/motion -c motion/motion.conf 
-d 9 -n
[0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file motion/
motion.conf
[0:motion] [ALR] [ALL] read_camera_dir: Camera directory config /home/rd/
Motion/motion/conf-x.d not found: No such file or directory
[0:motion] [NTC] [ALL] read_camera_dir: Processing config file /home/rd/Motion/
motion/conf.d/cam0-replay.conf
[0:motion] [NTC] [ALL] config_camera: Processing camera config file /home/rd/
Motion/motion/conf.d/cam0-replay.conf
free(): double free detected in tcache 2
Aborted
rd@master:~/Motion$ ~/tmp.nobackup/git/motion/src/motion -v
/home/rd/tmp.nobackup/git/motion/src/motion: invalid option -- 'v'
motion Version 4.3.0, Copyright 2000-2019 Jeroen Vreeken/Folkert van Heusden/
Kenneth Lavrsen/Motion-Project maintainers

Home page :      https://motion-project.github.io/ 

usage:  motion [options]


Possible options:

-b                      Run in background (daemon) mode.
-n                      Run in non-daemon mode.
-s                      Run in setup mode.
-c config               Full path and filename of config file.
-d level                Log level (1-9) (EMG, ALR, CRT, ERR, WRN, NTC, INF, 
DBG, ALL). default: 6 / NTC.
-k type                 Type of log (COR, STR, ENC, NET, DBL, EVT, TRK, VID, 
ALL). default: ALL.
-p process_id_file      Full path and filename of process id file (pid file).
-l log file             Full path and filename of log file.
-m                      Disable motion detection at startup.
-h                      Show this screen.

Motion is configured using a config file only. If none is supplied,
it will read motion.conf from current directory, ~/.motion or /usr/local/etc/
motion.

rd@master:~/Motion$


To repro, I just added 

camera_dir /home/rd/Motion/motion/conf-x.d

before the camera_dir in the motion.conf shipped by Debian (any might work).

Thanks
Rainer

**Comment by tosiara** [comment]
I cannot reproduce it. Please upload your full log with `-d 9`

**Comment by rdorsch** [comment]
On Donnerstag, 27. Februar 2020 12:21:08 CET tosiara wrote:
> I cannot reproduce it. Please upload your full log with `-d 9`

I think by the time it crashes, it has not yet started to write a log at least 
I cannot find it at the place specified with log_file (where it is usually).

Also I found that the two camera_dir entries are not sufficient, if the second 
camera_dir points to another empty directory I do not see the crash.

I uploaded the config file, which causes the crash for me:

http://scw.bokomoko.de/~rd/motion/

I hope that helps you to repro the issue.

Thanks
Rainer

**Comment by tosiara** [comment]
Does not crash with your config:
```
[0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file motion.conf
[0:motion] [ALR] [ALL] read_camera_dir: Camera directory config conf-x.d not found: No such file or directory
[0:motion] [NTC] [ALL] read_camera_dir: Processing config file conf.d/cam0-replay.conf
[0:motion] [NTC] [ALL] config_camera: Processing camera config file conf.d/cam0-replay.conf
[0:motion] [NTC] [ALL] motion_startup: Logging to syslog
[0:motion] [NTC] [ALL] motion_startup: Motion 4.3.0+git20200122-346ad0d Started
[0:motion] [NTC] [ALL] motion_startup: Using default log type (ALL)
[0:motion] [NTC] [ALL] motion_startup: Using log type (ALL) log level (NTC)
[0:motion] [NTC] [ALL] motion_startup: Motion running in setup mode.
[0:motion] [NTC] [STR] webu_start_strm: Starting all camera streams on port 8081
[0:motion] [NTC] [STR] webu_strm_ntc: Started camera 100 stream on port/camera_id 8081/100
[0:motion] [NTC] [STR] webu_start_ctrl: Starting webcontrol on port 8080
[0:motion] [NTC] [STR] webu_start_ctrl: Unable to start MHD
[0:motion] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version 57.107.100 libavformat version 57.83.100
[0:motion] [NTC] [ALL] translate_init: Language: English
[0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 100 is from conf.d/cam0-replay.conf
[0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 100 Camera Name: Cam0-replay Service: file:
```

**Comment by rdorsch** [comment]
On Donnerstag, 27. Februar 2020 14:48:44 CET tosiara wrote:
> Does not crash with your config:
> ```
> [0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file
> motion.conf [0:motion] [ALR] [ALL] read_camera_dir: Camera directory config
> conf-x.d not found: No such file or directory [0:motion] [NTC] [ALL]
> read_camera_dir: Processing config file conf.d/cam0-replay.conf [0:motion]
> [NTC] [ALL] config_camera: Processing camera config file
> conf.d/cam0-replay.conf [0:motion] [NTC] [ALL] motion_startup: Logging to
> syslog
> [0:motion] [NTC] [ALL] motion_startup: Motion 4.3.0+git20200122-346ad0d
> Started [0:motion] [NTC] [ALL] motion_startup: Using default log type (ALL)
> [0:motion] [NTC] [ALL] motion_startup: Using log type (ALL) log level (NTC)
> [0:motion] [NTC] [ALL] motion_startup: Motion running in setup mode.
> [0:motion] [NTC] [STR] webu_start_strm: Starting all camera streams on port
> 8081 [0:motion] [NTC] [STR] webu_strm_ntc: Started camera 100 stream on
> port/camera_id 8081/100 [0:motion] [NTC] [STR] webu_start_ctrl: Starting
> webcontrol on port 8080 [0:motion] [NTC] [STR] webu_start_ctrl: Unable to
> start MHD
> [0:motion] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version
> 57.107.100 libavformat version 57.83.100 [0:motion] [NTC] [ALL]
> translate_init: Language: English
> [0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 100 is from
> conf.d/cam0-replay.conf [0:motion] [NTC] [ALL] motion_start_thread: Camera
> ID: 100 Camera Name: Cam0-replay Service: file: ```

Strange, but memory issues are sometimes had to repro. What OS are you testing 
on?

I run Debian 10, I can try to repro it on a Debian 10 server and give you 
access to it.

Thanks
Rainer

**Comment by rdorsch** [comment]
On Donnerstag, 27. Februar 2020 14:48:44 CET tosiara wrote:
> Does not crash with your config:
> ```
> [0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file
> motion.conf [0:motion] [ALR] [ALL] read_camera_dir: Camera directory config
> conf-x.d not found: No such file or directory [0:motion] [NTC] [ALL]
> read_camera_dir: Processing config file conf.d/cam0-replay.conf [0:motion]
> [NTC] [ALL] config_camera: Processing camera config file
> conf.d/cam0-replay.conf [0:motion] [NTC] [ALL] motion_startup: Logging to
> syslog
> [0:motion] [NTC] [ALL] motion_startup: Motion 4.3.0+git20200122-346ad0d
> Started [0:motion] [NTC] [ALL] motion_startup: Using default log type (ALL)
> [0:motion] [NTC] [ALL] motion_startup: Using log type (ALL) log level (NTC)
> [0:motion] [NTC] [ALL] motion_startup: Motion running in setup mode.
> [0:motion] [NTC] [STR] webu_start_strm: Starting all camera streams on port
> 8081 [0:motion] [NTC] [STR] webu_strm_ntc: Started camera 100 stream on
> port/camera_id 8081/100 [0:motion] [NTC] [STR] webu_start_ctrl: Starting
> webcontrol on port 8080 [0:motion] [NTC] [STR] webu_start_ctrl: Unable to
> start MHD
> [0:motion] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version
> 57.107.100 libavformat version 57.83.100 [0:motion] [NTC] [ALL]
> translate_init: Language: English
> [0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 100 is from
> conf.d/cam0-replay.conf [0:motion] [NTC] [ALL] motion_start_thread: Camera
> ID: 100 Camera Name: Cam0-replay Service: file: ```

I have done  quick setup on Debian 10 for you

tosiara@lansol:~/motion/src$ ./motion -c ../../conf/motion.conf -d 9 -n
[0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file ../../conf/
motion.conf
[0:motion] [ALR] [ALL] read_camera_dir: Camera directory config /home/rd/
Motion/motion/conf-x.d not found: No such file or directory
[0:motion] [NTC] [ALL] read_camera_dir: Processing config file /home/tosiara/
conf/conf.d/cam0-replay.conf
[0:motion] [NTC] [ALL] config_camera: Processing camera config file /home/
tosiara/conf/conf.d/cam0-replay.conf
free(): double free detected in tcache 2
Abgebrochen
tosiara@lansol:~/motion/src$ 

I did not find your email address.

Can you provide your email address to tosiara@bokomoko.de for the purpose of 
sending you the login data?

Thanks
Rainer

**Comment by tosiara** [comment]
Confirmed
Could not reproduce locally, but the reporter provided the remote access to a machine, where the issue was reproducible:
```
tosiara@lansol:~/motion$ uname -a
Linux lansol 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

tosiara@lansol:~/motion$ cat /etc/issue
Debian GNU/Linux 10 \n \l

tosiara@lansol:~/motion$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ free -m
              total        used        free      shared  buff/cache   available
Mem:            981          75         610           2         295         884
Swap:          1023          14        1009

```
Steps to repro:
```
1. take a default config
2. append:

camera_dir nonexisting
camera_dir conf.d

3. mkdir conf.d
4. touch conf.d/dummy.conf
5. start motion
6. crash:

(gdb) bt
#0  0x00007ffff5b7f7bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff5b6a535 in __GI_abort () at abort.c:79
#2  0x00007ffff5bc1508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff5ccc28d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff5bc7c1a in malloc_printerr (str=str@entry=0x7ffff5ccdfb0 "double free or corruption (fasttop)") at malloc.c:5341
#4  0x00007ffff5bc95d7 in _int_free (av=0x7ffff5d03c40 <main_arena>, p=0x5555555dbd70, have_lock=<optimized out>) at malloc.c:4258
#5  0x0000555555569d1e in mystrcpy (to=<optimized out>, from=from@entry=0x7fffffffb06b "/home/tosiara/conf/conf.d") at conf.c:2836
#6  0x0000555555569d73 in copy_string (cnt=cnt@entry=0x5555555da490, str=str@entry=0x7fffffffb06b "/home/tosiara/conf/conf.d", val_ptr=val_ptr@entry=12392) at conf.c:2644
#7  0x0000555555569fe7 in read_camera_dir (cnt=0x5555555da490, str=0x7fffffffb06b "/home/tosiara/conf/conf.d", val=12392) at conf.c:3056
#8  0x0000555555569466 in conf_cmdparse (arg1=<optimized out>, cmd=<optimized out>, cnt=0x5555555da490) at conf.c:2195
#9  0x0000555555569466 in conf_process (cnt=cnt@entry=0x5555555da490, fp=fp@entry=0x5555555ce890) at conf.c:2195
#10 0x000055555556a1be in conf_load (cnt=0x5555555da490) at conf.c:2404
#11 0x0000555555562d87 in cntlist_create (argv=0x7fffffffe408, argc=5) at motion.c:3128
#12 0x0000555555562d87 in motion_startup (daemonize=1, argc=5, argv=0x7fffffffe408) at motion.c:3275
#13 0x00005555555602d1 in main (argc=5, argv=0x7fffffffe408) at motion.c:3645

```
Patch that seems to resolve the issue:
```
diff --git a/src/conf.c b/src/conf.c
index 81e1147..5df381a 100644
--- a/src/conf.c
+++ b/src/conf.c
@@ -3050,6 +3050,8 @@ struct context **read_camera_dir(struct context **cnt, const char *str, int val)
     {
         MOTION_LOG(ALR, TYPE_ALL, SHOW_ERRNO
             ,_("Camera directory config %s not found"), str);
+
+       return cnt;
     }
 
     /* Store the given config value to allow writing it out */
```
