### ISSUE TITLE
Random stop working on Raspberry Pi 1 Model B,700Mhz / 512MB

### ISSUE THREAD

**Issue by chenshaoju** [Motion-Project/motion#1121]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.0
2. installed as a package or compiled from sources [deb, rpm, git, other]: git (Build from 4.3.0 release source, on a raspberry pi)
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone.
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: USB WebCam
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian 10 buster

Sorry for my English.

Hi, I install motion on my Raspberry Pi (RPi 1 Model B,700Mhz / 512MB ), but somehow, The motion after the start, It's will randomly stop working.

I try to search the issue list, There is a similar issue: https://github.com/Motion-Project/motion/issues/780 , But I'm not using FFmpeg, Only local network stream.

I try a clean install 4.2.2 version, Same issue.

Here is the log, If need any information, please let me know, Thank you:
[motion_4.3.0_inf.txt](https://github.com/Motion-Project/motion/files/4255887/motion_4.3.0_inf.txt)

PS: I'm using htop to monitoring CPU usage, It's under 40% when motion is running, I think it's good?

**Comment by tosiara** [comment]
Are you trying to watch motion's mjpeg stream at the same time?

**Comment by chenshaoju** [comment]
Yes, I'm watching the stream, And most time the mjpeg is freeze or very slow from browser.

**Comment by tosiara** [comment]
Try to leave motion running without opening the stream. Will it run smoothly?

**Comment by chenshaoju** [comment]
If you meaning no viewer, It's still stop working after sometimes, Here is log:

[motion_4.3.0_inf_WithoutViewer.txt](https://github.com/Motion-Project/motion/files/4257099/motion_4.3.0_inf_WithoutViewer.txt)

**Comment by tosiara** [comment]
I think this is a resource issue. `RPi 1 Model B,700Mhz` is not able to run motion. Your camera provides 30 fps, but motion movie reports only 1 fps:
```
v4l2_fps_set: Trying to set fps to 15
v4l2_fps_set: Device set fps to 30
event_new_video: Source FPS 1
```
That means that motion drops 29 of 30 frames. This usually indicates CPU or I/O  load issue

**Comment by tosiara** [comment]
You can also search internet and check similar threads. Some suggests using different rpi firmware

https://github.com/Motion-Project/motion/issues/433
https://github.com/Motion-Project/motion/issues/780
https://github.com/Motion-Project/motion/issues/888

**Comment by chenshaoju** [comment]
I try using `rpi-update` to update the newest firmware, but still not working.

But this device it a bit out of date, looks it's time to buy a new one, thanks for your patience. 😃
