### ISSUE TITLE
Question: 360° equirectanular ffmpeg camera filter 

### ISSUE THREAD

**Issue by careyer** [Motion-Project/motion#1129]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]:  other
3. standalone or part of third party [motion, MotionEyeOS, other]: MotionEyeOS
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 4VL 
5. hardware [x86, ARM, other]: RPi
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  MotionEyeOS

Hi,

I am a long term MotionEyeOS user (>5y) and Calin refered me to the "motion" issue section. 

In my current project I am experimenting with a 360° v4l2 sytle USB camera (insta360 AIR). Can you please let me know where in the code I can influnce the v4l2 pipeline? The output of my camera is a dual fisheye picture at 2560x1280p30 and I developed a v4l2 filter to convert it to an equirectangular video (https://github.com/careyer/Insta360-Air-remap). 

The code generates remapping projections for [ffmpeg](http://ffmpeg.org) to convert from dual-fish-eye images/video (spherical) to equirectangular output. It can be used to map both images and video:
<img src="https://github.com/careyer/Insta360-Air-remap/raw/master/Insta360-Air-remap/pictures/input.gif" width="400"> &#x2794; <img src="https://github.com/careyer/Insta360-Air-remap/raw/master/Insta360-Air-remap/pictures/output.gif" width="400">

I would like to add this filter to the pipeline so that motionEyeOs shows the converted equirectanular picture and detects motion on basis of this equirectanular picture instead of on the dual fisheye. My usecase is a home surveilance system!

You simply cannot hide from a 360 camera ;-)

Thank you very much!
Cheers!
Thomas

**Comment by tosiara** [comment]
If you already implemented it in ffmpeg, you could pipe your changed stream through a virtual v4l-loopback device, or, alternatively, convert into rtsp and use netcam in motion

If you would like to make your conversion inside the motion's code, depending on which pixel format your usb camera uses, you would need edit buffer in those functions: https://github.com/Motion-Project/motion/blob/master/src/video_common.c#L413

**Comment by careyer** [comment]
@tosiara thank you for your timely answer! I haven't had thought about v4l2loopback yet.... It really is a clever idea! I will most likely give it a try. Just hoping that motionEyeOS gives enough freedom to install additonal software on top of it.  Thanks!!

**Comment by careyer** [comment]
Quick update: It didn't work with MotionEyeOS (no package installer), but with a standard Raspbian, the installation of MotionEye and v4l2loopback driver and my remapping filter it worked fine!
![motioneyeos](https://user-images.githubusercontent.com/6156251/77120805-fe477f00-6a39-11ea-9c3e-f1d863017347.JPG)
