### ISSUE TITLE
Wrong range for ffmpeg_variable_bitrate option

### ISSUE THREAD

**Issue by ccrisan** [Motion-Project/motion#113]
Playing with ffmpeg_variable_bitrate I noticed it had no effect whatsoever. Digging in deeper I discovered that the actual range for the quality used by ffmpeg/libav/whatever is 1 to 32767 (see [AVFrame::quality](https://www.ffmpeg.org/doxygen/3.0/structAVFrame.html#a791c071afd3e95fcae14cb781829754d) and [FF_LAMBDA_MAX](https://www.ffmpeg.org/doxygen/3.0/group__lavu__enc.html#gabc22a7ffbd4a73e81dd69e8c45e6cf8c)). Whereas the motion docs say valid values are 0 and 2 to 31.

Now I have tested higher values and indeed, at say 31000, the movie quality is pretty bad (expected). I believe somehow, somewhere there's a missing factor of 1000.

Should the docs be updated or should motion be patched to multiply the values by 1000 (or something)?

I'm not sure if this is the best place to open/discuss this issue. Anyways, I believe however that @tosiara, @sackmotion and @Mr-Dave may have a good input on this matter.

**Comment by ccrisan** [comment]
Not only the range for ffmpeg_variable_bitrate is wrong, but the effect seems to be non-linear (exponential, most likely). Reasonable movie quality range appears to be achieved between values 1 and, say, 5000, while movies are of a constantly bad quality throughout 32767.

This might be common sense to ffmpeg experts, but for me it's a bit odd, at least when trying to implement a 1 to 100% quality slider.

**Comment by Mr-Dave** [comment]
Is this the situation using the patch that was submitted or via the base code set?  I  think that the effect of the bit rate would also have varying effects based upon the codec that is selected.  Which codecc are you using so that I can replicate?

**Comment by ccrisan** [comment]
It happens with and without the [patch](https://github.com/Motion-Project/motion/pull/112) (I hope this is what you were referring to). All codecs except h264/mp4 and hevc seem to be affected. This can be easily reproduced with e.g.

    ffmpeg_video_codec msmpeg4
    ffmpeg_variable_bitrate 10

and then with values like 500, 1000, 5000 and 32767. Up to 500, the video looks good enough. The perceived quality degrades a bit with 1000, and considerably throughout 5000. My personal feeling is that values above 5000 won't make any serious difference.

Prior to my patch, the `ffmpeg_variable_bitrate` wouldn't have any effect at all on the resulted video when using h264 or hevc. The changes that I propose affect *only* h264 and hvec codecs and the quality is (seemingly) linear with the given `ffmpeg_variable_bitrate` value.

The questions that still remain open are:

1. What is in fact the expected range for this setting? Is it 0 and 2 to 32 as indicated by the config help? Or is it 0 and 1 to 32767, as inferred from [FF_LAMBDA_MAX](https://www.ffmpeg.org/doxygen/3.0/structAVFrame.html#a791c071afd3e95fcae14cb781829754d)?
2. What is the expected perceived video quality with regards to this setting?

**Comment by Mr-Dave** [comment]
I found the following link that illustrates the variations by codec. http://slhck.info/video-encoding.html  From reviewing this, I believe the answer to your question is that "it depends on the codec".  Looking at the ffmeg documentation, I do see the same variations between the codec. https://trac.ffmpeg.org/wiki/Encode/MPEG-4 versus https://trac.ffmpeg.org/wiki/Encode/H.264  Each of these have different ranges and interpretations for setting the quality.  Mpeg4 is setting a variable bit rate from 1-31 whereas quality in h264 is setting a 0-51 constant bit rate parameter.    The most immediate solution may be for motion to use the vbr parameter in the h264 options for crf.  Long term would be to rename the parameter.

**Comment by ccrisan** [comment]
Thanks for taking the time to look over this. Given the rather complex situation I decided to take care of it in my code by applying the required transforms on various codec cases.

My proposed patch still applies and does exactly this: using vbr to set the h264 crf parameter (while using the same 1..32767 range as input).
