### ISSUE TITLE
How to add second webcam on raspberry?

### ISSUE THREAD

**Issue by hl4roc** [Motion-Project/motion#1135]
0. Reviewed guide and contributing documents? (Yes/No):
1. version [x.y.z, hash, other]: motion 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: from git 
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: USB 
5. hardware [x86, ARM, other]: Raspberry Pi 3
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian 

I would like to build streaming web camera.
I used double USB camera, but it was connected only one camera.

How to set streaming_port of ' /etc/motion/motion.conf '?(I have two USB camera with the port 8081 and 8082)
>>  # The port number for the live stream.
         stream_port 8081

![2020-03-22-235041_1824x984_scrot](https://user-images.githubusercontent.com/62509346/77252669-ad819180-6c98-11ea-90a9-24fdfd2fdd69.png)

**Comment by baudev** [comment]
The `stream_port` config must be set into the individual configuration file of each camera.

Then:
- In `camera0.conf`, `stream_port = 8081`
- In `camera1.conf`, `stream_port = 8082`

**Comment by hl4roc** [comment]
> The `stream_port` config must be set into the individual configuration file of each camera.
> 
> Then:
> 
> * In `camera0.conf`, `stream_port = 8081`
> * In `camera1.conf`, `stream_port = 8082`

thank you for reply, but it doesn't work.
I changed the `stream_port` configuration file of each camera.
* In `camera0.conf`,
<before>  ' webcam_port 8081'
<after>     `stream_port = 8081`
* In `camera1.conf`,
<before>  ' webcam_port 8082'
<after>     `stream_port = 8082`

In 'motion.conf', Is there anything I need to fix?

I attached files.
![2020-03-26-002921_1824x984_scrot](https://user-images.githubusercontent.com/62509346/77555205-5549ca00-6efa-11ea-8b51-693afa180849.png)
![2020-03-26-003128_1824x984_scrot](https://user-images.githubusercontent.com/62509346/77555259-65fa4000-6efa-11ea-8920-c77aecb60d8d.png)
![2020-03-26-003207_1824x984_scrot](https://user-images.githubusercontent.com/62509346/77555457-980ba200-6efa-11ea-900e-ee8af68ed9b5.png)
![2020-03-26-003413_1824x984_scrot](https://user-images.githubusercontent.com/62509346/77555524-aa85db80-6efa-11ea-8eb2-471f817da9b2.png)
![2020-03-26-003424_1824x984_scrot](https://user-images.githubusercontent.com/62509346/77555536-aeb1f900-6efa-11ea-8ddf-ff7fdda10ddf.png)

**Comment by tosiara** [comment]
There is no such option - `webcam_port`. If `stream_port` is not working for you, attach the log file. Or even better - use mail list for usage related questions, there are more people to help

**Comment by baudev** [comment]
You should try:

In `motion.conf`

```
##############################################################
# Camera config files - One for each camera.
##############################################################
camera /path/to/camera1.conf
camera /path/to/camera2.conf
```

In `camera1.conf`

```
# Video device (e.g. /dev/video0) to be used for capturing.
videodevice /dev/video0
# The port number for the live stream.
stream_port 8081
# Remove restriction stream connections to the localhost (according to your screens).
stream_localhost off
```

In `camera2.conf`

```
# Video device (e.g. /dev/video0) to be used for capturing.
videodevice /dev/video1
# The port number for the live stream.
stream_port 8082
# Remove restriction stream connections to the localhost (according to your screens).
stream_localhost off
```
