### ISSUE TITLE
can't configure to use just a single port for accessing streams to all cameras

### ISSUE THREAD

**Issue by deividnastri** [Motion-Project/motion#1139]
Hi, i'm new to Motion.

I managed to get images from my cameras using the rtsp protocol, and stream each camera on a port successfully.
I would like to use the same port for the stream as stated in https://motion-project.github.io/motion_config.html#OptDetail_Stream could you help me?
I put the stream_port parameter only in the motion.conf file and it didn't work, I also tried to set the files in the cameras * .conf with the same port and it didn't work.
In all cases it shows the same image when I access:

http: // xxxxxxxxxxxxxx: 8788/1 / stream
http: // xxxxxxxxxxxxxx: 8788/2 / stream

Best regards.

**Comment by tosiara** [comment]
Why do you duplicate your question on both mail list and issue tracker?

**Comment by deividnastri** [comment]
sorry, i don't know how to use email list, i thought i hadn't sent it correctly.

**Comment by tosiara** [comment]
You question has been successfully submitted: https://sourceforge.net/p/motion/mailman/message/36969077/
Please be patient until it gets answered
