### ISSUE TITLE
Crop the output video

### ISSUE THREAD

**Issue by xrv0** [Motion-Project/motion#1141]
0. Reviewed guide and contributing documents? (Yes/No):
1. version [x.y.z, hash, other]: Latest stable from apt
2. installed as a package or compiled from sources [deb, rpm, git, other]: as package
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mjpeg
5. hardware [x86, ARM, other]: ARM (Pi 4b)
6. operating system [16.04, Stretch, etc, FreeBSD, other]: RPi Stretch

Is it possible to crop the output video? I only need a part of the image and my project heavily relays on latency and speed. I would probably be able to compile it myself, so a reference to a part of the code would also help.

**Comment by tosiara** [comment]
Which output video do you mean? Motion's stream output video? No, not possible
You could ask on the mail list as described here: https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md

**Comment by xrv0** [comment]
Yeah, I meant the stream output.
Im going to write an email then
