### ISSUE TITLE
Weird out-of sync issue on recording

### ISSUE THREAD

**Issue by angrycoding** [Motion-Project/motion#1142]
Hi, not sure if this is the actual motion issue, however I need to ask you if this could possibly be the case in the motion itself. I have a camera with two streams (LO, HI), passthrough on the high stream and everything is pretty straight forward. Everything works as expected, but sometimes (and I think this happens when internet lag happening), some kind of out of sync happens, which looks like this:
Motion still performs well, but recorded videos contains huge amount of still (no motion fragment) in the beginning of the recorded video file. For instance: 
- normally when motion is happening then according to the settings I use, I'm getting 5second fragment still video at the beginning and then the actual motion happens.
- Situation I'm in to is following: 30 seconds of still video, and then at the very end of the recorded video, I see actual movement which triggered the motion.

I doubt that this issue is related with some kind of frame accumulation. In the camera buffer, or receive buffer on my side. It more looks like motion calculates the time in some incorrect way. Maybe it takes the time from the frame timestamp's or all the way around. Could you please give me a tip of how to resolve this issue, or at least point me to the right direction?

**Comment by tosiara** [comment]
Would be great to have a sample video and a corresponding motion log as well

**Comment by angrycoding** [comment]
> Would be great to have a sample video and a corresponding motion log as well

Yes, I will as soon as I'll catch it again. Will post additional information here, so don't close it for a while, I'll come back

**Comment by angrycoding** [comment]
Allright, so I've finally catched it again. Nothing strange in motion.log:

[3:ml3:ceb9c0c5e8b] [INF] [EVT] [Apr 15 20:06:52] event_new_video: Source FPS 25
[3:ml3:ceb9c0c5e8b] [INF] [NET] [Apr 15 20:06:52] util_check_passthrough: pass-through is enabled but is still experimental.
[3:ml3:ceb9c0c5e8b] [INF] [ENC] [Apr 15 20:06:52] ffmpeg_passthru_codec: Pass-through stream opened
[3:ml3:ceb9c0c5e8b] [NTC] [EVT] [Apr 15 20:06:52] event_newfile: File of type 8 saved to: /home/streaming-server/movies/ceb9c0c5e8bbb632_2020_04_15_20:06:51.mp4
[3:ml3:ceb9c0c5e8b] [NTC] [ALL] [Apr 15 20:06:52] motion_detected: Motion detected - starting event 35
[3:ml3:ceb9c0c5e8b] [DBG] [EVT] [Apr 15 20:07:21] exec_command: Executing external command '/usr/local/bin/node /home/streaming-server/send-video.js ceb9c0c5e8bbb632 /home/streaming-server/movies/ceb9c0c5e8bbb632_2020_04_15_20:06:51.mp4'
[3:ml3:ceb9c0c5e8b] [NTC] [ALL] [Apr 15 20:07:21] mlp_actions: End of event 35

And here is two videos that were recorded during this:

https://drive.google.com/file/d/1MJzImttbSpdEzqFnF3SBdzIAPlwTfE-q/view?usp=sharing
https://drive.google.com/file/d/12LpXznY8Pg86LluV6z_hfE-DxZMl7Mhd/view?usp=sharing

To me it looks like at some point camera due the lack of internet connection hanged for a minute maybe, then connection was restored, but something inside the motion did not picked up this lack and still continued to record it as there was no missing frames at all. Then error is accumulated.

**Comment by tosiara** [comment]
Do you the the original file `XXXX_2020_04_15_20:06:51.mp4`? I'd like to see an issue in a file that was produced by motion and not cut by other software

**Comment by angrycoding** [comment]
> Do you the the original file `XXXX_2020_04_15_20:06:51.mp4`? I'd like to see an issue in a file that was produced by motion and not cut by other software

No, but I use mp4box to split it half by half, nothing more than it

**Comment by tosiara** [comment]
And do you know what  is the time shift between motion and camera's clock?

**Comment by angrycoding** [comment]
> And do you know what is the time shift between motion and camera's clock?

What time? Do you mean time set on the camera and server? Both are in sync with time.google.com every 5 minutes, to gmt+3. Is this important?

**Comment by tosiara** [comment]
So videos are lined like this:
```
motion:                             20:06:52-------------------------20:07:21 (29 sec)
camera: 20:05:54---------------------------------20:07:07                     (73 sec)
```
Some more questions:
1. what pre-capture/post-capture settings are you using?
2. is motion connecting directly to the camera or through some proxy or streaming server?

**Comment by angrycoding** [comment]
1.pre_capture, post_capture 1
2. Reverse proxy. Camera is connected to my server, motion connected to the same server as well. Piping data between them

**Comment by tosiara** [comment]
You did not provide the full log as it is usually required for issues, so I need to ask a lot of additional questions.

Are you using TCP or UDP?

**Comment by angrycoding** [comment]
> You did not provide the full log as it is usually required for issues, so I need to ask a lot of additional questions.
> 
> Are you using TCP or UDP?

TCP

**Comment by angrycoding** [comment]
> You did not provide the full log as it is usually required for issues, so I need to ask a lot of additional questions.
> 
> Are you using TCP or UDP?

Full log btw is about 300mb, so i dont think it makes sense

**Comment by tosiara** [comment]
I would like to try to add some extra logging into RTSP code. How did you setup your proxy? Do you have an exact command or config so I could replicate that?
And if you can upload the full log - that will also help. 300Mb is acceptable size. See the bottom of this wiki https://github.com/Motion-Project/motion/wiki/Privacy how to encrypt the file or the link, if you want to share privately

**Comment by angrycoding** [comment]
> I would like to try to add some extra logging into RTSP code. How did you setup your proxy? Do you have an exact command or config so I could replicate that?
> And if you can upload the full log - that will also help. 300Mb is acceptable size. See the bottom of this wiki https://github.com/Motion-Project/motion/wiki/Privacy how to encrypt the file or the link, if you want to share privately

No, there is no way you can replicate my setup standalone, cause it includes custom firmware for cam and receiving part written in c and nodejs by me. Log file, does it make any sense for you?

I have to possible suggestions:
1. Tell me what to look in the log file.
2. Tell me where in the motion source code you're expanding ring buffer. Since Im receiving only one huge video, must be something that holds such long video fragment.

**Comment by angrycoding** [comment]
Or if you maybe could give me source code with additional logging, i can compile and try to reproduce the issue, recording extended logging

**Comment by tosiara** [comment]
Motion has never been tested using any kind of reverse proxy, especially when running custom made proxy

**Comment by tosiara** [comment]
You can find RTSP code (including passthrough) here: https://github.com/Motion-Project/motion/blob/master/src/netcam_rtsp.c

**Comment by angrycoding** [comment]
> You can find RTSP code (including passthrough) here: https://github.com/Motion-Project/motion/blob/master/src/netcam_rtsp.c

Allright, thanks. I think I'll spend quite some time figuring out whats going on there )

**Comment by tosiara** [comment]
Please create a new issue when you find the root cause. And always use ISSUE_TEMPLATE when filing issues. Thanks!
