### ISSUE TITLE
Time offset live image - MotionEyeOs image

### ISSUE THREAD

**Issue by JBSullivan** [Motion-Project/motion#1144]
Hello, I am using MotionEyeOS (4.2.2.) with a Raspberry 3b+.
I have 5 network (2 x LAN - 3 x Wlan) cameras connected there. The settings for all 5 cameras are identical. 

Here are the settings: 640x480 / 2 Frames
Only the "Video Device" option is enabled - all other settings are disabled.

I have the problem that between the realtime image and the images MotionEyeOS send via streaming URL to my home automation system is sometimes several minutes delayed.

Is this a performance problem, even though I have already turned the settings down completely?
Is there somthing i can do to eleminate this problem?

Here is the result from TOP 

Mem: 360096K used, 405500K free, 168K shrd, 14740K buff, 40256K cached
CPU:  93% usr   1% sys   0% nic   4% idle   0% io   0% irq   1% sirq
Load average: 4.89 5.26 5.26 8/131 1369
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 3979  1131 root     S     418m  56%  93% /usr/bin/motion -n -c /data/etc/motion
 1131     1 root     R    54216   7%   3% /usr/bin/python /usr/lib/python2.7/sit
 1831  1085 root     S     5644   1%   0% sshd: admin@pts/0
 1849  1835 root     R     2592   0%   0% top
    9     2 root     SW       0   0%   0% [ksoftirqd/0]
   26     2 root     SW       0   0%   0% [ksoftirqd/3]
  838     2 root     IW       0   0%   0% [kworker/0:0-eve]
 1086     2 root     IW       0   0%   0% [kworker/3:1-eve]
 1166  1131 root     S    23020   3%   0% /usr/bin/python /usr/lib/python2.7/sit
 1035     1 root     S     8180   1%   0% /usr/sbin/ntpd -g -c /data/etc/ntp.con
 1085     1 root     S     5644   1%   0% /usr/sbin/sshd -f /var/run/ssh/sshd_co
  291     1 root     S     4216   1%   0% /sbin/udevd --daemon --resolve-names=n
  966     1 root     S     3804   0%   0% dhclient -cf /var/cache/dhclient.conf
 1835  1831 root     S     3580   0%   0% -sh
 1178     1 root     S     3320   0%   0% {S85motioneye} /bin/bash /etc/init.d/S
  265     1 root     S     3320   0%   0% {S11throttlewatc} /bin/bash /etc/init.
  874     1 root     S     2832   0%   0% /usr/sbin/rngd
 1050     1 root     S     2592   0%   0% /usr/sbin/crond -c /etc/crontabs
    1     0 root     S     2464   0%   0% init
  229     1 root     S     2464   0%   0% /sbin/syslogd

**Comment by tosiara** [comment]
It is better to ask questions on the mail list
For MotioneyeOS related issues use https://github.com/ccrisan/motioneyeos
