### ISSUE TITLE
put rtsp timestamp to filename

### ISSUE THREAD

**Issue by EZ-Phantom** [Motion-Project/motion#1149]
Is it possible to put timestamp from rtsp camera to the filename? "movie_filename" has not such options in docs, but it could be quite usefull.

Am i missing something, or it is impossible right now?

**Comment by tosiara** [comment]
Which timestamp do you mean? Can you provide a screenshot?

**Comment by EZ-Phantom** [comment]
If I am not missing anything in this standard then [this](https://tools.ietf.org/html/rfc7826#section-18.45) section describes some details. I wish to be able to operate with timestamp from rtsp. When recording is started I want to add a camera timestamp to a filename to be able to synchronize different videos from different cameras which shows exactly one moment. For example camera in front of my house and in rear entrance of my house (it is just simplified example)

**Comment by tosiara** [comment]
No, motion does not read any meta data from RTSP stream, it only decides the video stream
