### ISSUE TITLE
Motion update on RPi

### ISSUE THREAD

**Issue by titithebad** [Motion-Project/motion#1150]
Hello,

How simply update Motion on my pi ? I am with 4.2.2 version and I would like to update to the last version ? Is there an automatic procedure for that ?

Regards

**Comment by tosiara** [comment]
Remove old version `apt-get remove motion`
Download pi_buster_motion_4.3.1-1_armhf.deb from https://github.com/Motion-Project/motion/releases
Install it `dpkg -i pi_buster_motion_4.3.1-1_armhf.deb`

**Comment by titithebad** [comment]
Thanks ! It works !
