### ISSUE TITLE
Overlapping debug stamp on recorded videos if text_scale used

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#1151]
1. version [x.y.z, hash, other]: https://github.com/Motion-Project/motion/commit/392779e90bf101eeaebb2f95309963281d55395e

The debug stamp is printed only if non default debug level specified, and it is overlapping if `text_scale 4` used:

https://github.com/Motion-Project/motion/blob/392779e90bf101eeaebb2f95309963281d55395e/src/motion.c#L619

![image](https://user-images.githubusercontent.com/3600973/80304003-391c9f80-87bc-11ea-8cc1-96824272ff1f.png)

Also noted strange thing: `Precap` appears at the end of the recorded video right after `Postacp`

![image](https://user-images.githubusercontent.com/3600973/80303910-c3183880-87bb-11ea-9794-fe2990b9b97c.png)

**Comment by Mr-Dave** [comment]
Turn off text_scale when in debug?

**Comment by tosiara** [comment]
Maybe. But on higher res picture size (ex, 1920x1080) it is going to be hard to read anything
