### ISSUE TITLE
Web UI authentication isn't passed to the streams

### ISSUE THREAD

**Issue by vankxr** [Motion-Project/motion#1152]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86-64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 18.04

If you setup authentication both on the main webcontrol port and on the stream port, you can't view the streams in the webcontrol UI main page. That's due to the credentials not being inherited when embedding the streams in the main page.

I had to work around it using a nginx frontend.

**Comment by tosiara** [comment]
This seems to be browser's limitation and not motion's. There is currently no way to force the browser to ask for credentials of the embedded image

**Comment by tosiara** [comment]
Note, that if you open the stream in another tab - login will pop up. After login, you can return to webcontrol page and refresh - page will load

**Comment by tosiara** [comment]
See this for explanation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
```
A potential security hole that has recently been fixed by browsers is authentication of cross-site images. From Firefox 59 onwards, image resources loaded from different origins to the current document are no longer able to trigger HTTP authentication dialogs (bug 1423146), preventing user credentials being stolen if attackers were able to embed an arbitrary image into a third-party page.
```
