### ISSUE TITLE
Network I/O related performance issue with rtsp netcam

### ISSUE THREAD

**Issue by dgwynne** [Motion-Project/motion#1154]
0. Reviewed guide and contributing documents? (Yes/No): No
1. version [x.y.z, hash, other]: 4.3.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: OpenBSD package
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: OpenBSD

I have a Reolink 4MP RLC-420 (I think they've renamed it to D400 because they have a new 5MP RLC-420 now) which provides "sub" (rtsp://192.168.0.205:554/h264Preview_01_sub) and "main" (rtsp://192.168.0.205:554/h264Preview_01_sub) streams, which maps perfectly to to the `netcam_url` and `netcam_highres` configuration options respectively in motion. If I set motion up with only `netcam_url rtsp://192.168.0.205:554/h264Preview_01_sub` pointing at the low resolution stream, it works well. It generally sits around 1% CPU usage, and produces plausible events. I'm not currently capturing images or video, I'm currently just using it to provide a binary sensor to another system via `on_event_start` and `on_event_end`.

The problem is that any time I add the "main" stream in any way, CPU time goes through the roof. ie, it doesn't matter if I use the main stream with `netcam_url`, if I add it as `netcam_highres`, or use `movie_passthrough on`, the CPU usage goes to 80 to 100 percent. However, I do not think this is related to decoding because if I run ffmpeg with the null sink (`ffmpeg -i rtsp://192.168.0.205:554/h264Preview_01_sub -f null /dev/null`), it happily reads the stream, decodes it, and discards the output, all within about 25 to 30 percent CPU utilisation.

My theory is that this is I/O related.

I tried tracing the motion process, and discovered it spends most of its time doing 1 byte reads (well, `recvfrom`s). My best guess is that the recvfrom calls are in the avcodec or avformat libraries from ffmpeg, but for some reason the way that motion ends up using those libraries means it gets stuck doing 1 byte reads from the rtsp stream. To compare, ffmpeg seems end up doing mostly 1448 byte reads from the rtsp stream, while motion does orders of magnitude more 1 byte reads than anything else, and struggles to keep up with the data coming from the camera.

As a quick comparison:

```
$ sudo kdump -f /tmp/ffmpeg.ktrace  | grep RET.*recvfrom | cut -d / -f 1 | sort | uniq -c | sort -n | tail -n4 
  10  66071 ffmpeg   RET   recvfrom 264
 104  66071 ffmpeg   RET   recvfrom 1
 152  66071 ffmpeg   RET   recvfrom 265
8469  66071 ffmpeg   RET   recvfrom 1448
$ sudo kdump -f /tmp/motion.ktrace  | grep RET.*recvfrom | cut -d / -f 1 | sort | uniq -c | sort -n | tail -n4                                                                                              
  13  86555 motion   RET   recvfrom 4
 416  86555 motion   RET   recvfrom 1448
 521  86555 motion   RET   recvfrom 3
290547  86555 motion   RET   recvfrom 1
```

I tried to get my head around the code, but I don't have a lot of time at the moment and both `motion` and `ffmpeg` are too alien for me to figure out quickly. I'm hoping this report means someone who does understand the code can take a quick look.

**Comment by tosiara** [comment]
Could you provide a full log with `-d 7` for the case?

**Comment by dgwynne** [comment]
I think this is what you want. Looks like the output includes the relevant config options, so I won't repeat them.

[motion.txt](https://github.com/Motion-Project/motion/files/4544013/motion.txt)

**Comment by tosiara** [comment]
In this example log file you have 640x352 15fps low-res stream and some high-res stream with pass-through enabled. And this setup gives you 100% cpu, right?

**Comment by dgwynne** [comment]
Yes.

Note that I get 100% CPU with any use of the high-res main stream from the camera.

With the main stream used with `netcam_url` I'd expect CPU usage to be like ffmpeg with the null output filter, ie, 30% with some extra for the actual motion detection.

With main used with `netcam_highres` and `movie_passthrough`, I'd expect performance in the same ballpark as `ffmpeg -i rtsp://user:password@192.168.0.205:554/h264Preview_01_main -vcodec copy -acodec copy main.mkv`, which basically copies the stream into a different container. That uses about 3% CPU.

**Comment by tosiara** [comment]
Could you please do the following test:
```
1. Disable passthrough: movie_passthrough off
2. Comment out `netcam_highres`
3. Make sure you specified the correct width and height
4. keep picture and movie off
5. keep netcam_url with your low-res rtsp url
```
In this setup motion should only read low-res stream, decode it and do nothing
What CPU usage do you get with this test?

**Comment by dgwynne** [comment]
>  If I set motion up with only `netcam_url rtsp://192.168.0.205:554/h264Preview_01_sub` pointing at the low resolution stream, it works well. It generally sits around 1% CPU usage

I do notice that even with that config, I occasionally see a data waiting on the socket's recvq:

```
$ netstat -na -f inet -p tcp                
Active Internet connections (including servers)
Proto   Recv-Q Send-Q  Local Address          Foreign Address        (state)
[snip]
tcp        369      0  192.168.0.15.38954     192.168.0.205.554      ESTABLISHED
[snip]
```

That socket is motion reading from the "sub" stream.

It might just be bad lack that I manage to catch it between when the kernel receives data from the camera and before motion reads it for processing, but it is the only program on my system I've managed to catch with data waiting in the Recv-Q. This implies that motion is struggling to efficiently read data, even on the low bandwidth stream.

**Comment by tosiara** [comment]
Unfortunately, this issue may be camera-related. Would it be possible to temporarily create port forwardings to so could try reproduce the issue?

**Comment by dgwynne** [comment]
I am inclined to agree with you about the camera and rstp. After a lot of tinkering, I discovered that the camera also provides rtmp, and I've been using that instead of rtsp with motion and ffmpeg and it's working a lot better.

I'm pretty sure the rtsp issues are inside ffmpeg. If you still want to play around with it, we can look at a port forward.

**Comment by tosiara** [comment]
Yes, I would still like to check the issue myself. If possible, please follow this wiki article: https://github.com/Motion-Project/motion/wiki/Privacy to safely encrypt RTSP URL details

**Comment by dgwynne** [comment]
Try the following:

```
-----BEGIN PGP MESSAGE-----

hQEMAzwWtUGzwX+nAQf/cnR+Wn6unfYzChK0ISdLhvf3cCVkS+BeEWLnLc/GGj8t
5b+jNJMfd1E+BoSZllbTStO+HsqfgHhYykXxFuIaQVEoU/Ut4CRv5nywpwzDcKbA
nekswFlzFKGmrhHJuiWNTuK6FSSYgaqqgxJFXxRiN4QNjh/ZjahET02omy0SJglG
RCyUDVLL69dN6n7txUgP/A/8i6/TdjV7dnROM+9x8RwSx3GiI+3ByRm1xCYzmDIa
DV7XaviYWndVLSb4zKH9LsAo2yvxQPsOIui8CHzNiOKPYZsYsyIy6hLHK9WvhicV
1K/40q786XpaXPTRe3lhQwrvWSKFDfB1a/VqtlXeSdJ8ASh4XgcfwrMuggmxXSEJ
CdEFR1i45vAcv9+T6BwE/cMgeGFHDlgBz93A+22BnQAYcOLA+xwRmoVbdLhlRhqA
xhnuqXh+DJuFXrA/jhosjlIijI9hLyLcaKPxCoz0xeNtAvJdIYM4TcFwpxsrUnQe
6rnUDLJn6GZGj5APnw==
=NIIw
-----END PGP MESSAGE-----
```

**Comment by tosiara** [comment]
Thanks, I got your info. Will come back to you soon

**Comment by dgwynne** [comment]
OK, let me know if I forgot anything.

**Comment by dgwynne** [comment]
I'm going to tear the external access down

**Comment by tosiara** [comment]
Is there any chance to have it for at least for a few days?

**Comment by dgwynne** [comment]
Sure. I'll set it up again when I get a chance. Have you found anything interesting yet?

**Comment by tosiara** [comment]
Not yet, I was planning to spend some time today

**Comment by dgwynne** [comment]
Should be available again now.

**Comment by tosiara** [comment]
Not accessible. Can you verify your provided links are available from outside?

**Comment by dgwynne** [comment]
All seems to behave when I connect from an external host. It looks like the camera streams are talking to you at least?

**Comment by tosiara** [comment]
Forced TCP and now I can reach. Thanks

**Comment by tosiara** [comment]
I tried setting up your camera with passthrough - but that did not work at all.

When viewing the highres stream using `ffplay` it throws tons of errors and the picture is full of artefacts. I could barely understand what it is showging.

Substream plays with `ffplay` fine. Not a single error and clear view

Motion also throws same tons of errors, but also it is not able to decode a single frame from your highres stream, the watchdog keeps restarting the motion thread

I have seen such errors which may indicate the highres is not compatible with `ffmpeg`:
```
[1:ml1] [ERR] [NET] netcam_rtsp_open_context: Normal resolution: Unable to open camera((null)): Server returned 400 Bad Request
[1:ml1] [ERR] [ENC] ffmpeg_passthru_codec: RTSP context not available.
[1:ml1] [ERR] [ENC] ffmpeg_open: Could not setup passthru!
[1:ml1] [ERR] [EVT] event_ffmpeg_newfile: Error opening context for movie output.
[0:motion] [ERR] [ALL] motion_watchdog: Thread 1 - Watchdog timeout. Trying to do a graceful restart
```
When I tried to access RTMP url, I got `Input/output error` from ffplay

Compiled latest ffmpeg and that did not help either

**Comment by dgwynne** [comment]
I just opened UDP up too. Pretty sure motion was using TCP to talk RTMP to the camear though.

**Comment by dgwynne** [comment]
Also, are you quoting the & characters in the URI when passing it as an argument in the shell?

**Comment by tosiara** [comment]
Good point. I escaped `&` chars, but only now noticed it was `&amp;` html-encoded. Corrected, and now `ffplay` is able open the stream, and actually plays smooth. Motion is also able to access it and pass-through is working at about ~12% cpu
So, I can confirm, that RTMP does work fine

Tried RTSP using UDP, this time it failed to connect this way:
```
[1:ml1] [INF] [NET] netcam_rtsp_set_rtsp: Normal resolution: Setting rtsp transport to udp
[1:ml1] [INF] [NET] netcam_rtsp_open_context: Normal resolution: Opened camera((null))
[1:ml1] [INF] [ENC] ffmpeg_avcodec_log: Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[1:ml1] [ERR] [NET] netcam_rtsp_open_context: Normal resolution: Camera image size is invalid
```

**Comment by tosiara** [comment]
After n-th try, RTSP stream was able to decode the first image and started, throuwing tons of ffmpeg errors into log. The recorded pass-through videos contain half of garbage and green frames. And I can only see 10-20% of cpu when the stream is active, when it tries to reconnect there is no cpu usage at all

**Comment by tosiara** [comment]
But RTSP stream keeps restarting for me in motion
`ffplay` also failing randomly:
```
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[rtsp @ 0x7f1c50000b80] CSeq 2 expected, 0 received.=    0B f=0/0   
rtsp://********: Server returned 400 Bad Request
```

**Comment by dgwynne** [comment]
OK. So the conclusion is the camera sucks at RTSP and I should use RTMP.

**Comment by tosiara** [comment]
Probably, yes. Motion only as good with the RTSP/RTMP as `ffplay`. If the stream plays in ffplay fine - expect it to work in motion
In your case, RTMP plays fine in ffplay, but not RTSP. There is nothing motion can change for RTSP in this case

**Comment by tosiara** [comment]
Would you like to try compiling motion with the latest ffmpeg just to see if makes any difference on your end?

**Comment by dgwynne** [comment]
I've been poking at it from a Fedora 32 box (cos ffplay works better there than on a headless system), and it ships with ffmpeg 4.2.2 which is the latest release. It still seems to struggle with the main stream using RTSP over TCP. Everything else seems mostly ok. The main stream with RTSP over UDP is generally ok, but any packet loss causes visual artifacts.

I'm going to stick with RTMP for now.

Is it worth reporting the RTSP over TCP issues to ffmpeg?

**Comment by tosiara** [comment]
Yes, I think it is worth to confirm the issue with the latest ffmpeg before reporting any issues
```
git clone https://github.com/ffmpeg/ffmpeg
cd ffmpeg
./configure --prefix=/your/any/path
make
```
```
sudo apt-get remove libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libavdevice-dev
cd motion
autoreconf -fiv
./configure --with-ffmpeg=/your/any/path
make
```

**Comment by dgwynne** [comment]
I couldn't any code changes between 4.2.2 and HEAD that would affect this, so I haven't tried to run the code.
