### ISSUE TITLE
Unable to open video device

### ISSUE THREAD

**Issue by to4ko** [Motion-Project/motion#1155]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]:  4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: package
3. standalone or part of third party [motion, MotionEyeOS, other]: MotionEye
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: netcam rtsp 
5. hardware [x86, ARM, other]:  x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  Ubuntu Server 20.04 LTS

Hi! I'm using aliexpress pinhole IP camera. It was working just fine (motion detection, video saving, picture saving). But recently (1-2 days ago) it stops working at all.  

Same time i'm able to view video via VLC, built in webUI and even with ffplay (ffplay -rtsp_transport tcp rtsp://192.168.1.108:554/rtsp_live0 - it gives some errors but shows video just fine).

No any updates\software install were don on this machine for last 4-5 days.

[ffplay.txt](https://github.com/Motion-Project/motion/files/4571879/ffplay.txt)
[motion.log](https://github.com/Motion-Project/motion/files/4571893/motion.log)

**Comment by tosiara** [comment]
What do you mean by `built in webUI`? And how does `it stops working at all` looks like?

**Comment by to4ko** [comment]
> What do you mean by `built in webUI`? And how does `it stops working at all` looks like?

Built in WebUI - i meant camera UI.

Stops working - it's unable to connect to camera (screenshot below). 


![motionEye](https://user-images.githubusercontent.com/45161980/81310593-f8126e00-908c-11ea-852c-99b0008eba60.JPG)

**Comment by tosiara** [comment]
It's Motioneye web UI
Motion log says:
```
[1:ml1:pinhole] [INF] [NET] netcam_rtsp_decode_video: Error sending packet to codec: Invalid data found when processing input
[1:ml1:pinhole] [INF] [NET] netcam_rtsp_cleanup: Normal resolution: Shutting down network camera.
[1:ml1:pinhole] [NTC] [NET] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
[1:ml1:pinhole] [ERR] [VID] vid_start: Netcam RTSP failed to open
[1:ml1:pinhole] [WRN] [ALL] motion_init: Could not fetch initial image from camera 
```
There is an issue with the RTSP stream

Can you try to open `ffplay rtsp://your_url` on the motion box and paste output here?

**Comment by to4ko** [comment]
Same camera work just fine from Vlc and ffplay(log attached above).

How can i run “ffplay in motion box”?

**Comment by tosiara** [comment]
You can try this `ffmpeg -i rtsp://your_url -vcodec copy -an out.mp4`

**Comment by to4ko** [comment]
> You can try this `ffmpeg -i rtsp://your_url -vcodec copy -an out.mp4`

![image](https://user-images.githubusercontent.com/45161980/81401460-0d90a200-9138-11ea-882c-559c91fd1542.png)

**Comment by tosiara** [comment]
You used incomplete url. Use the same as you used form motion netcam_url

**Comment by to4ko** [comment]
oops...please find below

**Comment by tosiara** [comment]
Try to upgrade to the latest 4.3.1 motion

**Comment by to4ko** [comment]
please advise which one to use for ubuntu 20.04 running on Xeon CPU?
![image](https://user-images.githubusercontent.com/45161980/81411540-2f475480-914b-11ea-980c-1e868c8574c3.png)

**Comment by tosiara** [comment]
Try again, I have added a build for Focal 64bit: https://github.com/Motion-Project/motion/releases/download/release-4.3.1/focal_motion_4.3.1-1_amd64.deb

**Comment by to4ko** [comment]
> Try again, I have added a build for Focal 64bit: https://github.com/Motion-Project/motion/releases/download/release-4.3.1/focal_motion_4.3.1-1_amd64.deb

Thanks!!! It's working now!!!!
