### ISSUE TITLE
can we utilize installed graphic card for processing images?

### ISSUE THREAD

**Issue by mohannad2hamed** [Motion-Project/motion#1158]
Hello 
just new here i have installed motion and it works great but as i am using an old PC i noticed that it consumes a good amount of CPU processing power as i think this is related processing images.
but if i have a graphic card (an old type in my case it is  VGA compatible controller: NVIDIA Corporation GT218 [GeForce 210] (rev a2)) can motion utilize it's processing power instead of PC CPU?
is this sound good idea ?
if it is it can have an option (as suggestion) to choose what cameras will be utilized using PC CPU and what to be utilized using graphic card.

**Comment by tosiara** [comment]
No, motion does not support GPU
