### ISSUE TITLE
Exposure reset if v4l2_autobright doesn't make change

### ISSUE THREAD

**Issue by bmerry** [Motion-Project/motion#1162]
0. Reviewed guide and contributing documents? (Yes/No): Yes (but not recently)
1. version [x.y.z, hash, other]: 4.3.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: compiled from git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L2, USB
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 18.04

I had problems with auto-brightness: it would go into a loop of turning exposure to almost full (white out) then gradually correcting to a good level before whiting out again. I debugged the code and found that if `v4l2_autobright` decides *not* to adjust brightness (because the brightness is already within the window) then the exposure gets set back to the control's default value. In my case that default value was for high exposure.

I think the problem might be [this line](https://github.com/Motion-Project/motion/blob/392779e90bf101eeaebb2f95309963281d55395e/src/video_v4l2.c#L349), although I don't yet follow all the logic about how and when `ctrl_currval` and `ctrl_newval` are supposed to interact. That function gets called immediately before `v4l2_autobright`, and causes the control's `ctrl_newval` to be different to `ctrl_currval` on entry to `v4l2_autobright`.

**Comment by tosiara** [comment]
Did you try to find an easy way to reproduce the issue? I'd like to check this issue, but this may be camera-dependant

**Comment by bmerry** [comment]
I would guess it probably is camera-dependant if it hasn't been a common problem. It probably also depends on what the "default" exposure value is - I'm not too familiar with v4l2 so I don't know where that comes from.

My guess is that you can make this more likely to occur by editing the code to increase parm_hysteresis, since that'll increase the chance that the brightness doesn't need to be adjusted. However, it shouldn't be increased so much that there is no adjustment at all - you want there to be an initial adjustment, but a large enough hysteresis that you fall into the window. I've had to edit my version of motion to increase parm_hysteresis a lot (because the camera seems to have quantised exposure levels and was bouncing between two levels either side of the target), which may explain this.

You'll also see a commit  above that I used to work around this - if you're happy with the approach I can generalise it to the other autobrightness modes and submit it as a PR.

**Comment by bmerry** [comment]
@tosiara ping - do you have an opinion about the approach I took in the commit referenced above?

**Comment by tosiara** [comment]
I cannot comment on this change as I'm not the author of those lines and have never seen this behaviour, and default values are usually fail-safe.
If we cannot reproduce the issue it would be hard to validate the fix and test for regression
