### ISSUE TITLE
does not work with "service motion start"

### ISSUE THREAD

**Issue by KarlBaumann** [Motion-Project/motion#1164]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: latest 
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]:  motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  mmal
5. hardware [x86, ARM, other]: arm32
6. operating system [16.04, Stretch, etc, FreeBSD, other]: debian buster

Hi!

I am using motion on Raspberry pi 4 (4GB version) with latest Debian Buster.

When I start it with "service motion start", it does not work properly. Looks like it is not able to detect camera.
Only when I start it with "motion", then it works as it should.

Also after reboot it does not work as it should.

Any idea whats wrong?

**Comment by tosiara** [comment]
Please upload the full motion.log

Also, try to start motion directly: `motion -c yourconfig.conf -n`

**Comment by KarlBaumann** [comment]
I was actually able to solve this by removing "--chuid motion" in /etc/init.d/motion

**Comment by tosiara** [comment]
Are you now running motion as root?

**Comment by KarlBaumann** [comment]
probably yes. I am not that good with linux, but I suppose it wants to start on boot as a root. Otherwise it probably does not get needed access

**Comment by tosiara** [comment]
I recommend you not to use motion as root, but rather investigate why it does not work under `motion` user. See my comment https://github.com/Motion-Project/motion/issues/1164#issuecomment-639330665

**Comment by KarlBaumann** [comment]
I think the problem was that the user 'motion' simply did not exist. I created it manually and now it works also with that --chuid option
Not sure if it was supposed to be created by install script or I just missed the manual creation step

**Comment by tosiara** [comment]
motion user is created by postinstall script, here: https://github.com/Motion-Project/motion-packaging/blob/master/debian/motion.postinst

**Comment by vatw** [comment]
Just to add- I got here years after the fact.

It's clear in the documentation but I didn't notice it. to run Motion as a service you need to NOT set it to starting daemon mode in your config file.  A simple two character change, and everything works great!  (not running on a Rpi, but just in case anyone is like me)

**Comment by nishishailesh** [comment]
when using as service  in systemd,
`# Start in daemon (background) mode and release terminal.
daemon on
`
it is against logic. but, it works
