### ISSUE TITLE
Issue with motion detection

### ISSUE THREAD

**Issue by juancuellar14** [Motion-Project/motion#1166]
[Camera1_11-53-46.zip](https://github.com/Motion-Project/motion/files/4766228/Camera1_11-53-46.zip)

So i have the next issue i am running MotionEye on a hassio installation as an add-on and i set my camera with a RTSP address its a Reolink thru wifi, and from time to time it happens what you can see in the video and that triggers the motion detection saving houndreds of short files, can you guys help and point me in the right direction i dont know wht kind of manuals to check for this specific issue i tried to reset the addon every 12 hours but i sitill have the issue (After a reset it will work normally again), these are the versions:
motionEye Version | 0.42
-- | --
Motion Version | 4.3.1
OS Version | Linux 4.19.126-v7l
Hardware is a Raspberry PI 4 Running HASSIO and MotionEye running as an add-on

**Comment by tosiara** [comment]
I would recommend you asking such question on the mail list: https://sourceforge.net/p/motion/mailman/motion-user/
It has wider audience of experienced motion user that could help you tuning your config
