### ISSUE TITLE
stream_cors_header will not allow port

### ISSUE THREAD

**Issue by MarcGraham** [Motion-Project/motion#1168]
0. Reviewed guide and contributing documents? (Yes/No): 
yes
1. version [x.y.z, hash, other]: 
4.3 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
from deb as specified at motion site 
3. standalone or part of third party [motion, MotionEyeOS, other]: 
motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
raspberry pi camera
5. hardware [x86, ARM, other]: 
arm7 
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 
Raspbian Buster

I require basic auth on the stream server. 

I have this in motion.conf
```
# The port number for the live stream.
stream_port 8081

# Restrict stream connections to the localhost.
stream_localhost off

stream_maxrate 30
stream_motion on

stream_tls on
webcontrol_tls on
webcontrol_key /home/pi/ssl/privatekey.pem
webcontrol_cert /home/pi/ssl/certificate.pem
stream_auth_method 1
stream_authentication pi:raspberry
stream_cors_header https://raspisentry.local:5000
```
When I start motion this in the log:
```
Jun 23 15:59:48 raspisentry systemd[1]: Starting LSB: Start Motion detection...
Jun 23 15:59:48 raspisentry motion[11625]: Starting motion detection daemon: motion.
Jun 23 15:59:48 raspisentry systemd[1]: Started LSB: Start Motion detection.
Jun 23 15:59:48 raspisentry motion[11630]: [0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motion/motion.co
Jun 23 15:59:48 raspisentry motion[11630]: [0:motion] [ERR] [STR] copy_uri: Invalid origin for cors_header in copy_uri
Jun 23 15:59:48 raspisentry motion[11630]: [0:motion] [NTC] [ALL] motion_startup: Logging to file (/var/log/motion/motion.log)
```
removing the port from the uri and the server starts correctly.

**Comment by tosiara** [comment]
Looks like regex here: https://github.com/Motion-Project/motion/blob/master/src/conf.c#L2783 does not cover all the valid URIs
