### ISSUE TITLE
Proj Transition:  Code Transfer

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#117]
Update repo to include the 3.2, 3.2.10, 3.2.11 branches from SVN.  
Skip the import of the motion4 SVN branch.
Add release tags on to the older version.

**Comment by jogu** [comment]
I've added the branches you mention to the main git repo.

I've converted the following tags from the svn too:
3.2.10
3.2.11
3.2.11.1
3.2.9

The 3.2.9 tag is particularly weird as the 3.2.9 branch has been deleted from svn. There's a few oddities in the conversion with the tags but generally I'm confident that the contents of the branches/tags is all there.

**Comment by Mr-Dave** [comment]
This looks good and I'm going to check it off.  If others observe some code history we need, please re-open issue.
