### ISSUE TITLE
Log timestamp 

### ISSUE THREAD

**Issue by hemskgren** [Motion-Project/motion#1172]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]:  latest 4.3.1
2. installed as a package or compiled from sources [deb, rpm, git, other]:  deb from motion
3. standalone or part of third party: both motion and motioneye 
4. video stream source: net cam rtsp
5. hardware: arm
6. operating system : Debian 10 

I like to have timestamp in the motion log file.
Timestamp simplify rtsp troubleshooting.

**Comment by genius3000** [comment]
Are you logging to file or to syslog? Logging to file has a timestamp. If using syslog, you'd have to modify that if it's missing the timestamp.
Also make sure motioneye isn't interfering or complicating the issue here - I've never used it so can't say what it might do in this regard.

**Comment by hemskgren** [comment]
It was me not logging to file only starting motion and piping output to file. 
Any reason not all log have timestamp?
