### ISSUE TITLE
typo that may confuse newbies (me)?

### ISSUE THREAD

**Issue by Johnslow45** [Motion-Project/motion#1176]
page edit possible.

on the page for dockers

https://github.com/ccrisan/motioneye/wiki/Install-In-Docker

the line 

If using additional   services that make use of ports in the 808x range, then default mapping can   be edited to avoid conflicting by mapping higher range port numbers that are   not in use by other services (i.e., -p 8765:8765 **-p 58081:8081 -p 58082:8082**)

were these two suppose be **-p 8081:8081 -p 8082:8082)** ??

i am a newbie when it come to Linux and i am reading closely on the issues or needs that i have :)
thanks for all the hard work you do.

**Comment by genius3000** [comment]
You've posted this in the wrong repo, as motionEye is not motion.
To answer your question though, I do not believe those are typos. Docker's `-p x:y` maps the port `y` inside the container to port `x` on the Docker host.
