### ISSUE TITLE
Proj Transition:  Issues

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#118]
Review and copy over to issues in git the following from the old web page if the items is still appropriate:
	Support Requests
	Feature Requests
	Patches
	Bug reports

**Comment by Mr-Dave** [comment]
I have reviewed the list and have pulled out the items that I believe are still appropriate.  For some of the items, it is very subjective.  I invite others to review the lists and determine whether a particular item needs to be carried forward into the project.

**Comment by jogu** [comment]
I think you've done well, I find those pages hard to digest.

I'd say we've made a best efforts pass and are done. If anything important was missed, I'm sure someone will report it again in due course. :)

**Comment by Mr-Dave** [comment]
Having received no additional comments on items missed from the reading of the historic issues, I am closing this issue.  If problems previously reported do arise, users are advised to create a new issue on this repo for tracking.  Only issues reported here will be monitored.
