### ISSUE TITLE
How to get the duration of a saved movie file?

### ISSUE THREAD

**Issue by sagargp** [Motion-Project/motion#1180]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.1+git20200412-392779e
2. installed as a package or compiled from sources [deb, rpm, git, other]: Deb from git
3. standalone or part of third party [motion, MotionEyeOS, other]: Standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 19.10

I've tried using the various `on_movie_start`, `on_movie_end`, `on_event_start`, `on_event_end` but each one logs the end time as exactly 1 minute from the start event. This seems to correspond to my `event_gap` and `movie_max_time`. The movies get saved successfully, but they are each less than 60 seconds long. They range from 1-60 seconds.

I've also used the `sql_*` commands, and I get the same results. Perhaps I'm misunderstanding the meaning of `end`... is this possible in `motion`?

**Comment by tosiara** [comment]
Movie file contains only motion frames + pre_capture + post_capture. You can calculate the real length by running script on_movie_end with something like `mediainfo` and parse the results

**Comment by sagargp** [comment]
Got it, I misunderstood from the docs but this clears it up for me. And thanks for the suggestion of `mediainfo`.
