### ISSUE TITLE
Dependency check missing in builddeb.sh

### ISSUE THREAD

**Issue by gusarg81** [Motion-Project/motion#1181]
Hi,

This script is missing dependency check for fakeroot, which is necessary to build a deb package. Is why fails to build (even when It ends with "no errors", but checking in the script log you will see the error about fakeroot).

**Comment by tosiara** [comment]
Is it a duplicate of https://github.com/Motion-Project/motion-packaging/issues/9 ?

**Comment by gusarg81** [comment]
Yes, indeed!
