### ISSUE TITLE
Writing the configuration from the web interface looses the parameter "text_double"

### ISSUE THREAD

**Issue by BertLindeman** [Motion-Project/motion#1182]
0. Reviewed guide and contributing documents?: yes
1. version [x.y.z, hash, other]:  Motion 4.3.1+git20200412-392779e
2. installed as a package or compiled from sources [deb, rpm, git, other]: build via builddeb 
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: v4l USB
5. hardware [x86, ARM, other]: x86_64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 20.04

Was "playing" on the motion web interface via "action" - "pause" and saw the video on the web page **not** stop. This maybe related to #765 

So wanted to look if there would be anything changed if I rewrote the config from "action" - "Write configuration".
Found the only change was that I lost:

`diff motion.conf{,_before_write_from_web}`
`4c4`
`< # at 2020-08-02T15:49:52`
`---`
`> # at 2020-08-02T15:32:45`
`118a119,121`
`>`
`> # make the text twice as large`
`> text_double on`

Thanks for the great package,
Bert

**Comment by genius3000** [comment]
> Was "playing" on the motion web interface via "action" - "pause" and saw the video on the web page not stop.

If you mean the live stream (direct or on the web interface), that's proper. `pause` is for pausing/disabling motion detection and not the whole stream.

As for `text_double` being lost, this is expected as it was replaced with `text_scale` after version 4.1.1. What should be happening though is `text_double` read in and converted to `text_scale`. Can you confirm if both pre and post web write out files contain the `text_scale` parameter?

**Comment by BertLindeman** [comment]
> > Was "playing" on the motion web interface via "action" - "pause" and saw the video on the web page not stop.
> 
> If you mean the live stream (direct or on the web interface), that's proper. `pause` is for pausing/disabling motion detection and not the whole stream.
> 

@genius3000  My mistake. The stream goes on (as I intended).
Should I set wider logging to effectively see that motion-detection indeed has been disabled?


> As for `text_double` being lost, this is expected as it was replaced with `text_scale` after version 4.1.1. What should be happening though is `text_double` read in and converted to `text_scale`. Can you confirm if both pre and post web write out files contain the `text_scale` parameter?

You are correct, I overlooked the `text_scale` that is in **both** pre and post configurations.

Thank you. 
Bert

**Comment by BertLindeman** [comment]
As this issue was a false statement, I will close this issue.
