### ISSUE TITLE
libmicrohttpd changed API in 0.9.71

### ISSUE THREAD

**Issue by neheb** [Motion-Project/motion#1183]
Several functions now return MHD_Result.

**Comment by tosiara** [comment]
Does it break anything? Do you have build log?

**Comment by neheb** [comment]
Yeah. It doesn't compile.

Don't have a build log.

**Comment by neheb** [comment]
https://github.com/openwrt/packages/blob/master/multimedia/motion/patches/020-libmicrohttpd.patch

No compatibility defines were added since I don't really care for old versions.

**Comment by tosiara** [comment]
Thanks, this needs to be addressed as soon mainstream vendors include this version
So far, Ubuntu 20 ships `0.9.66`
Adding `bug` tag for visibility

**Comment by Mr-Dave** [comment]
closed by #1190

**Comment by neheb** [comment]
That PR is not a full solution. Compare my patch to that one. The types of retcd need to be changed as well.

**Comment by Mr-Dave** [comment]
Well, fair enough.  

That PR completed the process of getting Motion to compile without warnings/errors. 

There are many more return codes than the ones indicated in the patch that would need to be addressed to get it all in sync and cascading.
