### ISSUE TITLE
Excessive CPU usage - causes system shutdown

### ISSUE THREAD

**Issue by Rick-Hill** [Motion-Project/motion#1184]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: motion Version 4.2.2, 

2. installed as a package or compiled from sources [deb, rpm, git, other]: apt-get package:
$>uname -a
Linux pb-nuc01 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

3. standalone or part of third party [motion, MotionEyeOS, other]: Stand-alone

4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rstp 

5. hardware [x86, ARM, other]: Intel NUC - 4 hard core - Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz

6. operating system [16.04, Stretch, etc, FreeBSD, other]: Linux - Xubuntu 20.04

Notes:

6 rtsp cams and 1 /dev/videoX cam

CPU overheats and crashes os

Files:

syslog showing cpu overheating
motion log
motion conf
camera conf files
shell script to print output of top
nohup file capturing output of shell script
[motion_configs.tar.gz](https://github.com/Motion-Project/motion/files/5076900/motion_configs.tar.gz)
[top_out.tar.gz](https://github.com/Motion-Project/motion/files/5076945/top_out.tar.gz)

**Comment by tosiara** [comment]
7 streams are quite a lot, and depending on resolution and config file will take lots of CPU. But you can lower CPU usage by configuring high-res pass-through video recording and low-res input for motion detection
