### ISSUE TITLE
High CPU usage in Pine Rock64 SBC (RK3328)

### ISSUE THREAD

**Issue by gusarg81** [Motion-Project/motion#1185]
0. Reviewed guide and contributing documents?: Yes
1. Version: 4.3.1+git20200412-392779e 
2. Installed as a package or compiled from sources: packaged using builddeb.sh script
3. Standalone or part of third party: with Motioneye (not MotionEyeOS)
4. Video stream source: Netcam - RTSP 
5. Hardware: Pine Rock64 - RK3328 CPU 
6. Operating system: Ubuntu 18.04.3 LTS - aarch64 - Kernel 4.4.190-1233-rockchip-ayufan-gd3f1be0ed310

CPU usage is extremely high 100%. Currently  I have 3 cameras configured as RTSP.
FFmpeg version 4.3.1, compiled with --enable-rkmpp (hardware encoding, which enables h264_rkmpp decoder)

How do I know if Motion is using hardware encoding?

Thanks.

**Comment by tosiara** [comment]
So you are expecting motion to use hardware acceleration for H264 decoding?
I don't think this will happen out of the box. But you can lower CPU usage by configuring high-res pass-through video recording and low-res input for motion detection

**Comment by gusarg81** [comment]
I don't know what to expect. I just want to know if possible to use Hardware Acceleration instead of CPU with this hardware.

**Comment by gusarg81** [comment]
> The method to specify hwaccel for ffmpeg in Motion is what I've indicated. Use the netcam_decoder.

Sorry, I meant hwaccel_device

**Comment by gusarg81** [comment]
More info: in armbian forum they told me that ffmpeg does not support hardware encoding for Rockchip (only hw decoding with codecs h264_rkmpp hevc_rkmpp vp8_rkmpp vp9_rkmpp) and the only way to hw encoding is using gstreamer (with the rockchip plugin).

**Comment by Mr-Dave** [comment]
This is now mixing various issues of decoding, encoding and extpipe.  Closing as it seems that this issue is explained.
