### ISSUE TITLE
Multipart boundary parameter not recognized with older Panasonic cameras

### ISSUE THREAD

**Issue by chi01** [Motion-Project/motion#1187]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam mjpeg
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Buster

Some older Panasonic cameras, like the WV-NP series, insert a space before the equal sign in the boundary parameter.
(`boundary =SOME_BOUNDARY` instead of the expected `boundary=SOME_BOUNDARY`)
I'm not sure if this is allowed by the HTTP rules, but it is simple to fix with no side effects i am aware of.

Suggested fix in netcam_http.c:

```
if ((boundary = strstr(header, "boundary"))) {
                    /* On error recovery this may already be set. */
                    free(netcam->boundary);

                    /* Some older Panasonic cameras insert a space before
                     * the equal sign. The boundary starts with the char
                     * after the equal sign.
                     */
                    netcam->boundary = mystrdup(strchr(boundary,'=') + 1);
```

**Comment by tosiara** [comment]
Do you have an example of full HTTP response headers (all of them)?

**Comment by chi01** [comment]
> I'm curious, can you try change netcam url to be mjpeg:// this would force motion to use ffmpeg library for input. Would that work?

No, this doesn't work either. With this option, motion seems to try opening a connection to port 0.

I can read the stream with ffprobe, ffmpeg and webbrowsers, but not with motion. Is there a way to pass the pass the input file parameter direct to the ffmpeg library?

**Comment by tosiara** [comment]
if you could show your full config and log file - maybe I could answer your question
