### ISSUE TITLE
Proj Transition:  Wiki

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#119]
Create wiki pages to support 
	Related projects
	FAQ
	Developers corner
		Checklist for release
		Pull request->Unstable etc
		Coding standards
		Road map

**Comment by Mr-Dave** [comment]
Anyone see an issue opening the wiki to the public?

**Comment by jogu** [comment]
> Anyone see an issue opening the wiki to the public?

That seems reasonable to me.

**Comment by ccrisan** [comment]
Have you guys found a method to be notified via email whenever someone edits the wiki on github? This is the only reason why I keep my projects' wiki pages private - I have no means to see who changed what and people tend to mess things up and treat wiki pages as they were drafts or scratch paper.

**Comment by Mr-Dave** [comment]
Not yet.  @tosiara made changes yesterday and I didn't get any notifications.  We'll leave it private until we can figure this out and also see about being able to revert scratch paper changes.

**Comment by jogu** [comment]
There's an rss feed, or there's a webhook we could send to a server to generate emails, perhaps to the motion-devel list.

**Comment by tosiara** [comment]
I wonder, is it possible to restrict somehow pull requests so users can only send pulls to `unstable` branch?

**Comment by jogu** [comment]
I think there's a default branch setting in github.

I think the conclusion on https://github.com/Motion-Project/motion/issues/128 may have been that pull requests go to master though. I guess it will become clear once some of our own pull requests start to be merged :-)

**Comment by Mr-Dave** [comment]
I did read that the wiki is a repo.  I just can not find it to put a "watch" on it.  If you see the repo associated with the wiki, can you point us to it?  (Hint taken on the other issue)

**Comment by jogu** [comment]
You can clone it from https://github.com/Motion-Project/motion.wiki.git - but you don't seem to be able to access it like a normal github git repo to watch. I think hook -> server -> email to devel list is probably the only properly supported way.
