### ISSUE TITLE
Error using QSV as encoder (H264/QSV .mp4)

### ISSUE THREAD

**Issue by gusarg81** [Motion-Project/motion#1194]
Hi,

I've compiled ffmpeg (in Ubuntu Focal) with QSV support for encoder and decoder.
I setup netcam_decoder vp9_qsv and movie_codec mp4:h264_qsv and in Logs I see:

[1:ml1:Doorbell] [NTC] [ENC] ffmpeg_set_codec_preferred: Usando el códec h264_qsv
[1:ml1:Doorbell] [INF] [ENC] ffmpeg_set_quality: h264_qsv codec vbr / crf / bit rate: 0
[1:ml1:Doorbell] [INF] [ENC] ffmpeg_avcodec_log: Undefined constant or missing '(' in 'ultrafast'
[1:ml1:Doorbell] [INF] [ENC] ffmpeg_avcodec_log: Unable to parse option value "ultrafast"
[1:ml1:Doorbell] [INF] [ENC] ffmpeg_avcodec_log: Error setting option preset to value ultrafast.

Is there a way to fix this?

I use/compiled with QSV since it seems is the one that is working better (at least for hw decoder) with UHD Graphics 605.

Latest Motion (running with Motioneye).

Thanks in advance.

**Comment by tosiara** [comment]
Seems like your codec `h264_qsv` does not support profiles, note, `ultrafast` is the error is profile's name

It comes from this line: https://github.com/Motion-Project/motion/blob/master/src/ffmpeg.c#L638

You can try to comment out his line and recompile motion. Does that change anything?

**Comment by gusarg81** [comment]
Now I got:

> [1:ml1:Doorbell] [NTC] [ENC] ffmpeg_set_codec_preferred: Usando el códec h264_qsv
> [1:ml1:Doorbell] [INF] [ENC] ffmpeg_set_quality: h264_qsv codec vbr / crf / bit rate: 0
> [1:ml1:Doorbell] [INF] [ENC] ffmpeg_avcodec_log: Specified pixel format yuv420p is invalid or not supported
> [1:ml1:Doorbell] [ERR] [ENC] Above message repeats 35 times
> [1:ml1:Doorbell] [ERR] [ENC] ffmpeg_set_codec: No se pudo abrir el códec Invalid argument
> [1:ml1:Doorbell] [ERR] [ENC] ffmpeg_open: ¡Error al asignar el códec!
> [1:ml1:Doorbell] [ERR] [EVT] event_ffmpeg_newfile: Error al abrir el contexto para la salida de la película.

Translated starting from line 5, would be like something:

> [1:ml1:Doorbell] [ERR] [ENC] ffmpeg_set_codec: Could not open the codec Invalid argument
> [1:ml1:Doorbell] [ERR] [ENC] ffmpeg_open: Error assigning codec!
> [1:ml1:Doorbell] [ERR] [EVT] event_ffmpeg_newfile: Failed to open context for movie output.

**Comment by tosiara** [comment]
Motion decodes frames and analyses in yuv420 format. Your codec does not support this format:
`Specified pixel format yuv420p is invalid or not supported`

**Comment by gusarg81** [comment]
Are you sure? I am not an expect in this area, but in an encoding example in https://trac.ffmpeg.org/wiki/Hardware/QuickSync I believe is using -pix_fmt yuv420p.

In other hand, is there a way to output all the options that is using motion for ffmpeg decoding and encoding?

**Comment by gusarg81** [comment]
Yeah, seems right. When I issue it using ffmpeg command, I get:

> Incompatible pixel format 'yuv420p' for codec 'h264_qsv', auto-selecting format 'nv12'

**Comment by gusarg81** [comment]
So basically is not possible to use hardware acceleration on Intel GPUs ([Quick Sync](https://trac.ffmpeg.org/wiki/Hardware/QuickSync)) using h264_qsv in Motion?

**Comment by Mr-Dave** [comment]
You would need to use the `movie_extpipe` option for implementing  the `h264_qsv` encoder.

**Comment by gusarg81** [comment]
@Mr-Dave but I mean in the decoder side.

**Comment by gusarg81** [comment]
I've added movie_extpipe (and netcam_decoder as h264_vaapi) and does not encode video:

> [2:ml2:Ipcam_in] [NTC] [ENC] ffmpeg_set_codec_preferred: Usando el códec h264_qsv
> [2:ml2:Ipcam_in] [INF] [ENC] ffmpeg_set_quality: h264_qsv codec vbr / crf / bit rate: 12
> [2:ml2:Ipcam_in] [INF] [ENC] ffmpeg_avcodec_log: Undefined constant or missing '(' in 'ultrafast'
> [2:ml2:Ipcam_in] [INF] [ENC] ffmpeg_avcodec_log: Unable to parse option value "ultrafast"
> [2:ml2:Ipcam_in] [INF] [ENC] ffmpeg_avcodec_log: Error setting option preset to value ultrafast.
> [2:ml2:Ipcam_in] [INF] [ENC] ffmpeg_avcodec_log: Specified pixel format yuv420p is invalid or not supported
> [2:ml2:Ipcam_in] [ERR] [ENC] Above message repeats 34 times
> [2:ml2:Ipcam_in] [ERR] [ENC] ffmpeg_set_codec: No se pudo abrir el códec Invalid argument
> [2:ml2:Ipcam_in] [ERR] [ENC] ffmpeg_open: ¡Error al asignar el códec!
> [2:ml2:Ipcam_in] [ERR] [EVT] event_ffmpeg_newfile: Error al abrir el contexto para la salida de la película.

movie_extpipe: 

> movie_extpipe ffmpeg -init_hw_device qsv=hw -filter_hw_device hw -f rawvideo -pix_fmt yuv420p -s:v %wx%h -framerate %fps -i pipe:0 -vf hwupload=extra_hw_frames=64,format=qsv -c:v h264_qsv -b:v 5M %f.mp4

It is something wrong with this one?

**Comment by gusarg81** [comment]
Also tried with gstreamer:

`gst-launch-1.0 fdsrc ! rawvideoparse format=nv12 width=%w height=%h framerate=30/1 ! vaapidecode ! filesink location=%f.mp4`

But gives me the same error: Broken pipe

**Comment by gusarg81** [comment]
I made it work with h264_vaapi:

> movie_extpipe ffmpeg -y -f rawvideo -pix_fmt yuv420p -video_size %wx%h -framerate %fps -vaapi_device /dev/dri/renderD128 -i pipe:0 -vf 'format=nv12,hwupload' -c:v h264_vaapi %f.mp4

But, I would like to know if someone made it with qsv. Thanks
