### ISSUE TITLE
Possible syslog deadlock

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#1198]
1. version: https://github.com/Motion-Project/motion/commit/392779e90bf101eeaebb2f95309963281d55395e
4. video stream source: v4l
5. hardware: ARM
6. operating system: 16.04

One of my cameras has experienced some instability with the storage which caused motion to hang forever in a deadlock:
```
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb5ac7c8e in __lll_lock_wait_private (futex=0xb5b1bd20 <syslog_lock>) at ./lowlevellock.c:33
#2  0xb5abbd7c in __GI___vsyslog_chk (pri=<optimized out>, flag=1, fmt=0x496a90 "%s", fmt@entry=0xbef37e4c "\004\213\363\276motion", ap=..., ap@entry=...) at ../misc/syslog.c:258
#3  0xb5abbe2e in __syslog_chk (pri=<optimized out>, flag=<optimized out>, fmt=0x496a90 "%s") at ../misc/syslog.c:129
#4  0x004627fe in motion_log ()
#5  0x0046a648 in vid_close ()
#6  0x0045cb34 in motion_cleanup ()
#7  0x0045c40a in main ()
```

The last log entries were:
```
[0:motion] [ERR] [ALL] motion_watchdog: Thread 1 - Watchdog timeout. Trying to do a graceful restart
[0:motion] [ERR] [ALL] motion_watchdog: Thread 1 - Watchdog timeout did NOT restart, killing it!
```

Killed and restarted motion - it started to function normally.

I don't know what exactly caused this deadlock. But probably would be good to somehow prevent locking. Maybe move `motion_log` into an asynchronous thread?

Any ideas?

**Comment by Mr-DaveDev** [comment]
I am not sure that moving the log to run on another thread would resolve this.  From my observations, it seems like the implementation of the log has many design challenges with respect to threading that could cause issues.  

Probably better to revise the routines to first be thread safe regardless of which thread they run upon.

**Comment by rkarlsba** [comment]
Keep in mind that Ubuntu 16.04 won't be supported much longer, so upgrading to a newer version (sudo do-release-upgrade) is a good start.

**Comment by tosiara** [comment]
Unfortunately, only happened once. Haven't seen this on ARM Ubuntu 18 anymore

**Comment by tosiara** [comment]
Damn, just happened again :/
```
Thread 1 (Thread 0xade27010 (LWP 1246)):
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb5915e88 in __lll_lock_wait_private (futex=0xb59befa4 <syslog_lock>) at ./lowlevellock.c:35
#2  0xb595d0fa in __vsyslog_internal (pri=<optimized out>, fmt=fmt@entry=0xbec75e0c "\324^Ǿ\002", ap=..., ap@entry=..., mode_flags=2) at ../misc/syslog.c:269
#3  0xb595d1d2 in __syslog_chk (pri=<optimized out>, flag=<optimized out>, fmt=0x4c34e0 "%s") at ../misc/syslog.c:136
#4  0x0048e998 in motion_log ()
#5  0x00496cb8 in vid_close ()
#6  0x0048a38a in motion_cleanup ()
#7  0x0048950e in main ()
```
```
$ uptime
 16:33:45 up 82 days, 23:10,  1 user,  load average: 0.27, 0.29, 0.31
```
```
Jul 08 17:12:50 odroid motion[1246]: [1:ml1:the] [NTC] [EVT] event_extpipe_end: CLOSING: extpipe file desc 10, error state 0
Jul 08 17:13:19 odroid motion[1246]: [0:motion] [ERR] [ALL] motion_watchdog: Thread 1 - Watchdog timeout. Trying to do a graceful restart
Jul 08 17:13:29 odroid motion[1246]: [0:motion] [ERR] [ALL] motion_watchdog: Thread 1 - Watchdog timeout did NOT restart, killing it!
```
When the issue happened, there was an extensive i/o operation going on the main sd card: from 17:06 to 17:15. After that the device restored to normal operation. But motion stayed hanging

**Comment by Praveenmonk** [comment]
@tosiara - I hope the issue is not consistent. 

I'm facing the same issue in my module & my backtrace pointed out the same location.

#1  0xb5915e88 in __lll_lock_wait_private (**futex=0xb59befa4** <syslog_lock>) at **./lowlevellock.c:35**

@tosiara - Do we have any open issues for this behavior?

**Comment by tosiara** [comment]
Did you find how to reproduce it?

**Comment by Praveenmonk** [comment]
@tosiara - No but im also facing same issue randomly
