### ISSUE TITLE
ability to set tag on hevc video "-tag:v hvc1 "

### ISSUE THREAD

**Issue by gsustek** [Motion-Project/motion#1202]
0. Reviewed guide and contributing documents? (**Yes**/No):
1. version [**4.3.1**, hash, other]: 
2. installed as a package or compiled from sources [**deb**, rpm, git, other]: 
3. standalone or part of third party [**motion**, MotionEyeOS, other]: 
4. video stream source [**V4L (card or USB)**, net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [**x86**, ARM, other]: 
6. operating system [**20.04**, Stretch, etc, FreeBSD, other]: 

To support HEVC playing on Safari web browser in mp4 container it is needed to re-tag during encoding with ffmpeg with parameter hvc1 instead hev1.

documentation:  https://motion-project.github.io/motion_config.html#movie_codec
**mkv:libx265** _-tag:v hvc1_ 
cause this error:
 ffmpeg_set_codec_preferred: Preferred codec libx265 -tag:v hvc1 not found
Please provide posibility to add this parameter.

**Comment by tosiara** [comment]
What about running a script `on_movie_end` to change the tag of a recorded movie file?

**Comment by gsustek** [comment]
i actually do that now, but would be really nice if we can do it in the first place.
Thnx.

**Comment by Mr-Dave** [comment]
Custom tags would be via the `movie_extpipe` option.

**Comment by gsustek** [comment]
My point was: to make this enhancement clear: Today modern web browser on computers and on mobile platform play movies with mkv: using libx265 with tag:v hvc1 **automatically** when you click on file. That was my suggestion, that hvc1 become a default tag instead hev1.
