### ISSUE TITLE
Enabling RTSP?

### ISSUE THREAD

**Issue by fatjuice** [Motion-Project/motion#1211]
Hello guys, 

I am fairly a noob in Linux otherwise, but bear with me.
I'm trying to use my raspberry pi 3b+ as a NVR as such.

I've successfully in the past installed many rpi as a fast network camera, using motioneyeOS or as a mod installed on the pi itself.
Now I want to try something else.

I have these chinese cameras Besder, they are IP cameras, but I cannot access a live feed on a browser.
I found a way how to connect these cameras easily on iSpy on my windows. I want to try to use the RTSP protocol, but I get a message :"Protocol "rtsp" not supported or disabled in libcurl".

Now I have always used the guide to install either motioneye or motioneyeOS and always succesfully.

Now, my understanding of rasbian is very limited as I am a long time windows user (I know, horrible).

Could I somehow enable RTSP so I can perhaps get these cameras to work on motioneye?

Thanks in advance, best regards

**Comment by tosiara** [comment]
To access RTSP of a Besder camera use:
`rtsp://ip:554/user=admin&password=&channel=1&stream=0.sdp?real_stream`
or
`rtsp://ip:554/user=admin&password=&channel=1&stream=1.sdp?real_stream`
