### ISSUE TITLE
Super Slow on Motion Detection using i7 x86

### ISSUE THREAD

**Issue by Commander-Crash** [Motion-Project/motion#1217]
0. Reviewed guide and contributing documents? (Yes/No):
1. motion Version 4.0
2. installed as a package or compiled from sources [deb, rpm, git, other]: DEB
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  Both V4L and USB
5. hardware [x86, ARM, other]: X86 64bit arch
6. operating system [16.04, Stretch, etc, FreeBSD, other]: On multiple Linux distros.

so when using Motion as a secerity cam on linux it is very slow when it detects motion. This is on a i7 at 2Ghz clock speed. with 8gb ddr4 ram I have seen $15 phones that can keep up better. Why is this?

**Comment by Mr-Dave** [comment]
My six HD cameras run just fine.
