### ISSUE TITLE
Get a Snapshot as jpg - like snapshot.cgi?

### ISSUE THREAD

**Issue by Licht2002** [Motion-Project/motion#1219]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mjpeg
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Buster

Hi,

is it possible to get a Snapshot as jpg like the Foscam-URL eg: http://harbourbar.dyndns.org:8080/img/snapshot.cgi?

I can only get the Stream on Port 8081- but i need a only a single JPG in Browser on an another System.

Thanks
Tom

**Comment by tosiara** [comment]
`{IP}:{port}/{camid}/action/snapshot`
https://motion-project.github.io/motion_config.html#OptTopic_Webcontrol

**Comment by Licht2002** [comment]
Thanks for your answer...

this /action/snapshot takes a snapshot on the raspberrey - i am searching for a Snapshot (with HTTP-Get) to store/show it on another PC with e.g. Chrome on a Windows-PC.

Thx
Tom

**Comment by tosiara** [comment]
motion does not provide access to saved movies, pictures or snapshots. either install a web server on the motion box to serve files for you, or use the existing stream to extract a single frame, like:

`ffmpeg -i http://motion:8081/1/stream -vframes 1 snapshot.jpg`

**Comment by tosiara** [comment]
I'm sorry, my bad. This is the URL for obtaining a snapshot:

`http://motion:8081/1/current`
