### ISSUE TITLE
Digest Authentication

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#122]
Add digest authentication for http cameras, web stream and http control.

**Comment by jwater7** [comment]
I would LOVE to see this added to motion *finally* - I've been using a hack to get my Trendnet PoE 720p outdoor IP camera (TVIP320PI) to work by running a "digest proxy" (see https://gist.github.com/jwater7/675830a3a708d62b4be6fde2a2c4a1aa) and then adding something like this to the motion.conf:
```
snapshot_filename camhostname
target_dir /media/share/cam/camhostname
netcam_http 1.1
netcam_url http://192.168.1.14:8020/VFYtSVAzMjBQSS91c2VybmFtZTpwYXNzd2RAY2FtaG9zdG5hbWUvU3RyZWFtaW5nL2NoYW5uZWxzLzEvcGljdHVyZQ==
;encoded portion after / is by running: python -c "import base64; print base64.b64encode('TV-IP320PI/username:passwd@camhostname/Streaming/channels/1/picture')"
```

It works most of the time, but needs to be restarted periodically, looking forward to seeing this implemented at some point, but until then, just wanted to share my workaround.  Thanks.

**Comment by Mr-Dave** [comment]
@jwater7 Thanks for the information.  In your situation, you may want to consider using the RTSP instead of HTTP for your camera.  Issue #121 reports that the digest authentication is functional for that protocol and the camera you referenced appears to support RTSP.

**Comment by jwater7** [comment]
This is great news!  Thanks for the info for my specific situation - It seems like the last time/version I tried it, it wasn't working but I just tried again via rtsp and now it is working properly with a line like this in the file (for the TVIP320PI camera):
netcam_url rtsp://username:passwd@camhostname/

**Comment by tosiara** [comment]
@jwater7 one small note on your workaround. Digest auth is used to protect credentials so you don't send them in plain text over the network. In your case you are transferring your credentials in plain text to a 'digest proxy', If it is on the same box (localhost) - no worries. But if it is another box - your credentials may leak. In tha case suggestion - either encrypt your credentials (instead of base64), or use SSL

**Comment by jwater7** [comment]
Thanks for the note @tosiara - that's right and I actually do use it locally and not sure why I originally put the network IP in the example above.  I updated the original comment in case anyone ever uses it.

**Comment by Mr-Dave** [comment]
The motion protocol of MJPEG should resolve this since it is using http via ffmpeg.
