### ISSUE TITLE
Is there a way to have on_motion_detected trigger with a specified detection frequency? 

### ISSUE THREAD

**Issue by abolotnov** [Motion-Project/motion#1220]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mmal
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Stretch

I got it setup, it's great, it triggers the right scripts, everything is great. Thanks for the great software! The only thing I can't figure out how to configure is if I can have motion only trigger `on_motion_detected` once in `n` seconds. In other words, if it has detected motion, can it not trigger another one until after `n` seconds?

**Comment by genius3000** [comment]
I'm fairly certain this has been asked before, maybe it was on the mailing list though. There's currently no way to do this directly in Motion. Just thinking out loud here (haven't reviewed the code right now), I believe adding an interval to the code would be fairly easy and non-invasive.

For now, the recommended and simplest solution is to use a script that writes the timestamp to a file and checks against that at each call. Then just limit the actual activity to when the interval is passed.
