### ISSUE TITLE
Is there a way to trigger a motion event externally? such as via bash script?

### ISSUE THREAD

**Issue by xekon** [Motion-Project/motion#1229]
I am wondering if there is a way to trigger a motion event (fake/emulate motion) via external scripts.
There are probably a LOT of use cases for this, such as lazer sensor tripped, sound detected, vibration detected.

I ask because of my vibration sensors. If somebody is Bashing on a door then I would like the cameras to record, the motion on the inside of the door might show a slight vibration but not change the picture enough to trigger an event until they have actually managed to break the door down.

I imagine I would somehow send an event flag to the motion program and it would record for whatever your defined event_gap variable is set to.

0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  motion (4.2.2-1ubuntu1)
2. installed as a package or compiled from sources [deb, rpm, git, other]:  deb
3. standalone or part of third party [motion, MotionEyeOS, other]:  motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  mjpeg
5. hardware [x86, ARM, other]: AMD64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 20.04

**Comment by Mr-Dave** [comment]
> Reviewed guide and contributing documents? (Yes/No): Yes

Probably want to re-review the [documentation](https://motion-project.github.io/motion_config.html#OptDetail_Webcontrol) and [contributing](https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md)  a bit.  What you've described certainly seems to be exactly what was built in and documented in the guide.

**Comment by xekon** [comment]
so the only way to do it is with web control? I had hoped to leave that disabled, from a security standpoint that seems safer.

maybe i can find a way to only enable certain parts of web control.
