### ISSUE TITLE
video darker than still images

### ISSUE THREAD

**Issue by gatosyperros** [Motion-Project/motion#1230]
I was facing the same Issue in reference to:
https://github.com/ccrisan/motioneyeos/issues/799

The still image would turn out "great" while the video would be too dark to see what I could see in the image.
It turns out it's because of what software you you to play the video:
https://forum.doom9.org/showthread.php?t=171599
post by wonkey_monkey and Asmodian
Wonkey said:
"If my memory serves me correctly, this is a bug in some MJPEG codecs."
then Asmodian said:
"Most video is YUV limited scale so a lot of decoders do not expect full range video and AVI has no in-spec way to identify full-range video."

It turns out that if I just crank up the brighness in VLC or any video processing software I get the same image as in the still image.
https://imgur.com/a/ei1MFIc

So I don't think it's a bug from motion or motioneyeos, but rather a problem how the video is encoded.
I think this should bee added the documentation

**Comment by Mr-Dave** [comment]
Well, Motion does encode the video.  

Unfortunately, this is not a complete issue that can be worked.  The issue template is missing and we have no method or path to reproduce what is being indicated.  

We would need the information requested as part of the issue template, the Motion logs of when this issue occurred (at the log level of INF(7) or higher),  a small sample video, and validation that it occurs with version 4.3.1 .
