### ISSUE TITLE
build for debian jessie failed for v 4.3.2

### ISSUE THREAD

**Issue by i300220** [Motion-Project/motion#1236]
webu.o: dans la fonction « webu_parseurl »:
/tmp/motion.nK8W6Q/motion/src/webu.c:419: référence indéfinie vers « MHD_http_unescape »
collect2: error: ld returned 1 exit status

[jessie_motion_4.3.2-buildlog-x86_64.txt](https://github.com/Motion-Project/motion/files/5439640/jessie_motion_4.3.2-buildlog-x86_64.txt)

**Comment by tosiara** [comment]
You can try to download https://ftpmirror.gnu.org/libmicrohttpd/libmicrohttpd-latest.tar.gz and install it on your Jessie.
```
cd libmicrohttpd-0.9.71
./configure
make
sudo make install
```

**Comment by i300220** [comment]
Thanks tosiara,

If one to go ahead and install it on jessie, gettext would have to be updated as well before compiling libmicrohttpd-0.9.71

Best!
