### ISSUE TITLE
Error building latest git on FreeBSD

### ISSUE THREAD

**Issue by nachtbraker** [Motion-Project/motion#1240]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: latest git clone
2. installed as a package or compiled from sources [deb, rpm, git, other]: source
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: FreeBSD 12.1-RELEASE-p10 amd64

After a git pull to update my local sources to the latest revision I get the following errors during compile. My previous successful build was from a couple of months ago, and at that time it built w/o any problem.

$ git clone https://github.com/Motion-Project/motion.git
...
$ cd motion
$ autoreconf -fiv
...
$ ./configure
   **************************
      Configure status       
      motion 4.3.1+dirty20200928-21b6740
   **************************

CFLAGS: -D_THREAD_SAFE -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -g -O2

LIBS:  -pthread   -L/usr/local/lib -ljpeg  -L/usr/local/lib -lmicrohttpd  -L/usr/local/lib -lavutil -lavformat -lavcodec -lswscale -lavdevice  -L/usr/local/lib -lsqlite3 

LDFLAGS:  

OS                  : freebsd12.1
pthread_np          : yes
pthread_setname_np  : no
pthread_getname_np  : no
XSI error           : yes
webp support        : yes
V4L2 support        : yes
BKTR support        : yes
MMAL support        : no
FFmpeg support      : yes
libavformat version : 58.45.100
SQLite3 support     : yes
MYSQL support       : no
PostgreSQL support  : no
MariaDB support     : no

Install prefix:       /usr/local

$ gmake
...
cc -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/usr/local/etc/motion\" -DLOCALEDIR=\"/usr/local/share/locale\" -I/usr/local/include -D_THREAD_SAFE -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include  -g -O2 -MT video_bktr.o -MD -MP -MF $depbase.Tpo -c -o video_bktr.o video_bktr.c &&\
mv -f $depbase.Tpo $depbase.Po
video_bktr.c:349:21: error: no member named 'update_parms' in 'struct params_context'; did you mean 'update_params'?
    if (!cnt->vdev->update_parms) return;
                    ^~~~~~~~~~~~
                    update_params
./motion.h:227:9: note: 'update_params' declared here
    int update_params;                        /*Bool for whether to update the parameters on the device*/
        ^
video_bktr.c:354:44: error: no member named 'usrctrl_count' in 'struct params_context'
    for (indx_user=0; indx_user<cnt->vdev->usrctrl_count; indx_user++){
                                ~~~~~~~~~  ^
video_bktr.c:355:29: error: no member named 'usrctrl_array' in 'struct params_context'
        usritem=&cnt->vdev->usrctrl_array[indx_user];
                 ~~~~~~~~~  ^
video_bktr.c:356:32: error: incomplete definition of type 'struct vdev_usrctrl_ctx'
        if (!strcasecmp(usritem->ctrl_name,"contrast")) bktr_set_contrast(dev,usritem->ctrl_value);
                        ~~~~~~~^
video_bktr.c:347:12: note: forward declaration of 'struct vdev_usrctrl_ctx'
    struct vdev_usrctrl_ctx *usritem;
           ^
video_bktr.c:356:86: error: incomplete definition of type 'struct vdev_usrctrl_ctx'
        if (!strcasecmp(usritem->ctrl_name,"contrast")) bktr_set_contrast(dev,usritem->ctrl_value);
                                                                              ~~~~~~~^
video_bktr.c:347:12: note: forward declaration of 'struct vdev_usrctrl_ctx'
    struct vdev_usrctrl_ctx *usritem;
           ^
video_bktr.c:357:32: error: incomplete definition of type 'struct vdev_usrctrl_ctx'
        if (!strcasecmp(usritem->ctrl_name,"hue")) bktr_set_hue(dev,usritem->ctrl_value);
                        ~~~~~~~^
video_bktr.c:347:12: note: forward declaration of 'struct vdev_usrctrl_ctx'
    struct vdev_usrctrl_ctx *usritem;
           ^
video_bktr.c:357:76: error: incomplete definition of type 'struct vdev_usrctrl_ctx'
        if (!strcasecmp(usritem->ctrl_name,"hue")) bktr_set_hue(dev,usritem->ctrl_value);
                                                                    ~~~~~~~^
video_bktr.c:347:12: note: forward declaration of 'struct vdev_usrctrl_ctx'
    struct vdev_usrctrl_ctx *usritem;
           ^
video_bktr.c:358:32: error: incomplete definition of type 'struct vdev_usrctrl_ctx'
        if (!strcasecmp(usritem->ctrl_name,"brightness")) bktr_set_brightness(dev,usritem->ctrl_value);
                        ~~~~~~~^
video_bktr.c:347:12: note: forward declaration of 'struct vdev_usrctrl_ctx'
    struct vdev_usrctrl_ctx *usritem;
           ^
video_bktr.c:358:90: error: incomplete definition of type 'struct vdev_usrctrl_ctx'
        if (!strcasecmp(usritem->ctrl_name,"brightness")) bktr_set_brightness(dev,usritem->ctrl_value);
                                                                                  ~~~~~~~^
video_bktr.c:347:12: note: forward declaration of 'struct vdev_usrctrl_ctx'
    struct vdev_usrctrl_ctx *usritem;
           ^
video_bktr.c:359:32: error: incomplete definition of type 'struct vdev_usrctrl_ctx'
        if (!strcasecmp(usritem->ctrl_name,"saturation")) bktr_set_saturation(dev,usritem->ctrl_value);
                        ~~~~~~~^
video_bktr.c:347:12: note: forward declaration of 'struct vdev_usrctrl_ctx'
    struct vdev_usrctrl_ctx *usritem;
           ^
video_bktr.c:359:90: error: incomplete definition of type 'struct vdev_usrctrl_ctx'
        if (!strcasecmp(usritem->ctrl_name,"saturation")) bktr_set_saturation(dev,usritem->ctrl_value);
                                                                                  ~~~~~~~^
video_bktr.c:347:12: note: forward declaration of 'struct vdev_usrctrl_ctx'
    struct vdev_usrctrl_ctx *usritem;
           ^
video_bktr.c:362:16: error: no member named 'update_parms' in 'struct params_context'; did you mean 'update_params'?
    cnt->vdev->update_parms = FALSE;
               ^~~~~~~~~~~~
               update_params
./motion.h:227:9: note: 'update_params' declared here
    int update_params;                        /*Bool for whether to update the parameters on the device*/
        ^
video_bktr.c:709:28: error: no member named 'usrctrl_count' in 'struct params_context'
            if (cnt->vdev->usrctrl_count > 0){
                ~~~~~~~~~  ^
video_bktr.c:710:45: error: no member named 'usrctrl_count' in 'struct params_context'
                for (indx=0;indx<cnt->vdev->usrctrl_count;indx++){
                                 ~~~~~~~~~  ^
video_bktr.c:711:37: error: no member named 'usrctrl_array' in 'struct params_context'
                    free(cnt->vdev->usrctrl_array[indx].ctrl_name);
                         ~~~~~~~~~  ^
video_bktr.c:712:32: error: no member named 'usrctrl_array' in 'struct params_context'
                    cnt->vdev->usrctrl_array[indx].ctrl_name=NULL;
                    ~~~~~~~~~  ^
video_bktr.c:715:24: error: no member named 'usrctrl_count' in 'struct params_context'
            cnt->vdev->usrctrl_count = 0;
            ~~~~~~~~~  ^
video_bktr.c:716:28: error: no member named 'usrctrl_array' in 'struct params_context'
            if (cnt->vdev->usrctrl_array != NULL){
                ~~~~~~~~~  ^
video_bktr.c:717:33: error: no member named 'usrctrl_array' in 'struct params_context'
                free(cnt->vdev->usrctrl_array);
                     ~~~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by Mr-Dave** [comment]
Thanks for reporting.  

If you need it right away, looks like you can use the configuration switch of `--without-bktr` since you are using a netcam.

**Comment by nachtbraker** [comment]
Thank you, --without-bktr solved the problem.

Please let me know if there is anything I can do to help or test with the actual fix.
