### ISSUE TITLE
Raspberry pi 4 - video corruption

### ISSUE THREAD

**Issue by kanaida2** [Motion-Project/motion#1247]
0. Reviewed guide and contributing documents? (Yes/No):Yes
1. version [x.y.z, hash, other]: other
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: v4l
5. hardware [x86, ARM, other]: arm
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 
Stretch

Video corruption will eventually occur on the raspberry pi 4.
Especially when heat builds up when saving to usb3 drives. Except it's not heat related. Raspivid continues to work without corruption.

**Comment by Mr-Dave** [comment]
Closing as invalid.  Please review [contributing](https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md) guide and consider that developers may not have a PI4 so any platform specific issues would have to be addressed elsewhere.
