### ISSUE TITLE
Inconsistent netcam frame rate configuration causes out of sync in extpipe

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#1249]
1. version: https://github.com/Motion-Project/motion/commit/c2cef04645d76517519dadcfdb93a56df2a35e2d
4. video stream source: rtsp
6. operating system: 20.04

After upgrading to the latest master and specifying the following frame rates:
```
netcam_rate 12
framerate 10
movie_extpipe x264 ..... --fps %fps
```
the recorded videos appear much slower than with previous version. I suspect that there may be some confusion between 10 and 12 fps which results in more frames coming to extpipe while writing with the lower frame rate value:

```
[NTC] [NET] netcam_rtsp_connect: norm: Netcam capture FPS is 12.
[NTC] [NET] netcam_rtsp_connect: norm: Camera source is 12 FPS
[INF] [ALL] motion_init: Emulating motion
[NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 11 items
[INF] [EVT] event_new_video: Source FPS 10
[NTC] [EVT] event_create_extpipe: pipe: x264 - --input-res 1280x720 --fps 10 --crf 24 --preset ultrafast --quiet -o /home/motion/cam1/01-20201105_12-03.mp4
[NTC] [EVT] event_create_extpipe: cnt->moviefps: 10
[NTC] [EVT] event_newfile: File of type 8 saved to: /home/motion/cam1/01-20201105_12-03
[NTC] [ALL] motion_detected: Motion detected - starting event 1
[INF] [ALL] motion_loop: 98 frames per 10.04 seconds, FPS=9.76
[INF] [ALL] motion_loop: 99 frames per 10.01 seconds, FPS=9.89
^C
[NTC] [EVT] event_newfile: File of type 1 saved to: /home/motion/cam1/01-20201105_12-03.jpg
[NTC] [EVT] event_extpipe_end: CLOSING: extpipe file desc 10, error state 0
aborted at input frame 259, output frame 253
encoded 253 frames, 10.11 fps, 1290.32 kb/
```
The line `[INF] [ALL] motion_loop: 98 frames per 10.04 seconds, FPS=9.76` is added manually to the code to see the real rate at which motion processes frames.

I will try to make more RTSP test to see how many frames exactly comes to motion and gets out of it to stdout, but so far I'm open to suggestions what to try else

**Comment by Mr-DaveDev** [comment]
I am not sure that this would be related to the `capture_rate`/ `netcam_rate`. In the prior versions, Motion always sped up the capture rate to 12 behind the scenes.  The parameter now just allows the user to control it.  

The portion that was new is how to try to handle the situation when the camera FPS is less than the specified capture rate in Motion.  (This portion will be removed given your reported experience of 10 vs 12 FPS).  If you want, you can just comment out [this](https://github.com/Motion-Project/motion/blob/c2cef04645d76517519dadcfdb93a56df2a35e2d/src/netcam_rtsp.c#L1141)  section to allow you to go back to 10 FPS as the capture_rate

**Comment by tosiara** [comment]
No longer reproducible in the latest master

**Comment by tosiara** [comment]
```
[0:motion] [INF] [ALL] width                     1280
[0:motion] [INF] [ALL] height                    960
[0:motion] [INF] [ALL] framerate                 5
...
[2:nc2:test] [NTC] [NET] netcam_rtsp_connect: norm: Camera (test) connected
[2:nc2:test] [INF] [NET] netcam_rtsp_connect: norm: Netcam capture_rate is 11.
[2:nc2:test] [INF] [NET] netcam_rtsp_connect: norm: Camera source is 10 FPS
[1:ml1:test] [INF] [ALL] motion_init: Emulating motion
[1:ml1:test] [INF] [EVT] event_new_video: Source FPS 5
[1:ml1:test] [NTC] [EVT] event_create_extpipe: pipe: x264 - --input-res 1280x960 --fps 5 --crf 24 --preset ultrafast --quiet -o 0-01-20201112190517.mp4
```

[0-01-20201112190517.zip](https://github.com/Motion-Project/motion/files/5532109/0-01-20201112190517.zip)
