### ISSUE TITLE
With picture_output on last image is written with the next incremented event ID

### ISSUE THREAD

**Issue by glennerichall** [Motion-Project/motion#1254]
0. Reviewed guide and contributing documents? (Yes/No): no
1. version [x.y.z, hash, other]: https://github.com/Motion-Project/motion/commit/dc670f5da977465241171fd01dcfc6713f49d8f2
2. installed as a package or compiled from sources [deb, rpm, git, other]: package
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 18.04.4 LTS

Seems that when adding event frames (as pictures with` picture_output on` and `sql_log_picture on`) to a sqlite database (didnt tried others though), last frames are created as next event (ie %v + 1, see event column) with value defined by `text_event` (ie %C) to empty...
Here is the insertion query in config:

    sql_query insert into events(camera, event, time, type, frame, filename) values('%t', '%v.%C', '%Y-%m-%d %T', '%n', %q, '%f')

![image](https://user-images.githubusercontent.com/2382170/98490820-c1b2d880-2200-11eb-9c48-4c989932ee33.png)

**Comment by tosiara** [comment]
Also note, that it's not just about Sqlite, but the picture file itself has also been create with event ID `02`

**Comment by Mr-DaveDev** [comment]
Can anyone test PR #1283 for resolving this issue?

**Comment by tosiara** [comment]
Please give me few days, I will take a look soon

**Comment by tosiara** [comment]
Verified, fixed

**Comment by Mr-Dave** [comment]
THanks for the validation.
