### ISSUE TITLE
Help with Pi Camera and 7" Touch Display

### ISSUE THREAD

**Issue by Schattenruf** [Motion-Project/motion#1256]
Hey guys,

I need your help. I needed to setup a new sdcard after my old one crashed... Problem here: I lost my motion.conf. My goal was it to turn my screen on when motion is captured and off, when the event is over. That worked in my old config... But I cannot seem to get it to work in my actual one.

In the log it states, that it executes the script but nothing happens. I tried to turn it off and on with:
- vcgencmd display_power 1 & 0
- echo 1 >/sys/class/backlight/rpi_backlight/bl_power

That works if I execute those commands seperatly via the script but not if motion does it...

And my camera stream has a problem as well:
My camera is setup and I can see a picture on my stream... BUT it is just frozen, if I move in front of it, it is still the first frame. The framerate is on 15 and the thereshold on 2000.... The log states, that there was motion, but the image just does not change.
Is there any way how I can enable the livestream again and not the first picture it took after the service started?

Thanks!

**Comment by Mr-Dave** [comment]
This really isn't a help forum as indicated in the [contributing guidelines](https://github.com/Motion-Project/motion/blob/dc670f5da977465241171fd01dcfc6713f49d8f2/CONTRIBUTING.md)
