### ISSUE TITLE
please rename "check" target to "maintainer-check"

### ISSUE THREAD

**Issue by infinity0** [Motion-Project/motion#1257]
Hi, I am updating this package in Debian. The current "check" target runs several configure-clean-build cycles with different config options. By convention this is not what the "check" target is supposed to do (self-test the program, not the build scripts), and is confusing Debian tools that interoperate with this convention.

https://www.gnu.org/prep/standards/html_node/Standard-Targets.html

Please rename the check target to something like "maintainer-check" or "build-script-check".

**Comment by Mr-DaveDev** [comment]
Can you confirm that PR #1258  will address this for version 4.3.3?  (A separate PR with similar changes will be completed for the master branch once this is confirmed.)

**Comment by infinity0** [comment]
@Mr-DaveDev looks good, thanks!

**Comment by infinity0** [comment]
BTW, there is no need to rush a release out just for this, I already have a similar patch for the Debian package.

**Comment by Mr-DaveDev** [comment]
OK.  I will then close PR #1258 and push the revision into the master for the next release.  This avoids the extra work of a point release.

**Comment by Mr-Dave** [comment]
Closed via #1260
