### ISSUE TITLE
netcam_rtsp_decoder_error: Normal resolution: avcodec_find_decoder_by_name: Failed,Interrupt False

### ISSUE THREAD

**Issue by ycodryn** [Motion-Project/motion#1259]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: Synology Docker and MotionEye 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: RTSP
5. hardware [x86, ARM, other]: Intel x64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Debian 10

Long story short I always liked motion but after having high cpu usage (50%+) I tried zoneminder and shinobyi, both of them having low cpu usage (8-10%). After seeing the netcam_decoder implemented I made another try on motion but using netcam_decoder h264_vaapi made no change. Using motioneye official docker I had same usage.
Then I thought that motioneye official docker had no vaapi acceleration inside, I made my own dockerfile with compiled  vaapi ffmpeg, enabling acceleration with intel-media-va-driver-non-free, enabling /dev/dri:/dev/dri etc. 
I`m using only record with Movie Passthrough, without motion detection and all 6 cameras with 8 fps.
Again all of this made no change on motion and looking on logs I have netcam_rtsp_decoder_error. Honestly I don`t know what to do anymore.

**motion log:** https://pastebin.com/MTpZzvfF
**vainfo log:** https://pastebin.com/cdidfJdz
**ffmpeg -version log:** https://pastebin.com/pgNmdw6P
**ffmpeg -formats log:** https://pastebin.com/2eMeAmi3
**ffmpeg -encoders log:** https://pastebin.com/DZAa3CvU
**ffmpeg -hwaccels log:** https://pastebin.com/cTsFngkm
**docker_create log:** https://pastebin.com/hgVbG7ri
**dockerfile:** https://pastebin.com/JzC8kNig

**Comment by tosiara** [comment]
Are you running inside a docker? Is GPU accessible inside the docker?

**Comment by ycodryn** [comment]
Yes, I`m running inside a docker and yes the GPU is accessible inside the docker. Docker is running in privileged mode and with ls /dev/dri/* I got /dev/dri/card0  /dev/dri/renderD128.

**Comment by ycodryn** [comment]
I remade my docker using built-in ffmpeg from debian buster, but I have all acceleration drivers built from source and are up to date: 
VA-API version: 1.10 (libva 2.10.0.pre1),
Intel iHD driver for Intel(R) Gen Graphics - 20.4.2 (d5eb02a) and 
motionEye Version | 0.42.1
Motion Version | 4.3.1+git20201119-84a31f7
OS Version | Linux 4.4.59+

Now I have same error [ERR] [NET] netcam_rtsp_decoder_error: norm: avcodec_find_decoder_by_name: Failed but also conf_cmdparse: "netcam_keepalive" replaced with "netcam_params" after version 4.3.1 but I`m guessing that is from motioneye.

**Comment by ycodryn** [comment]
Remade my dockercreate, compiled ffmpeg with vaapi and qsv and tried to use **netcam_decoder h264_vaapi** or **netcam_decoder h264_qsv** and I have same error. 
Now I tried to use **movie_extpipe ffmpeg -y -f rawvideo -pix_fmt yuv420p -video_size %wx%h -framerate %fps -vaapi_device /dev/dri/renderD128 -i pipe:0 -vf 'format=nv12,hwupload' -c:v h264_vaapi %f.mp4** or **movie_extpipe ffmpeg -y -hwaccel qsv -c:v h264_qsv -vcodec h264_qsv ~/out.h264** and that error is gone but I don`t see an decrease of cpu usage.

**Comment by ycodryn** [comment]
> 
> 
> Are you running inside a docker? Is GPU accessible inside the docker?

**lspci** gives me VGA compatible controller: Intel Corporation Device 5a85 (rev 0b) which is Atom E3940 (Apollo Lake) Intel HD Graphics 500

**Comment by Mr-Dave** [comment]
Invalid:  
You have quoted CPU values of other software versus Motion in this issue as well as elsewhere but provided no substantiation.  I have set up the other software and compared the same camera under both software and the usage is comparable.
![image](https://user-images.githubusercontent.com/5959350/101116664-ccb01d00-35a2-11eb-8925-1bca14a07386.png)
  
There are also other items with this issue that I won't go into.  I would recommend that you consult the guide included with the code you downloaded and compiled.
