### ISSUE TITLE
Error with pi_buster_motion_4.3.2-1_armhf.deb

### ISSUE THREAD

**Issue by baimard** [Motion-Project/motion#1262]
0. Reviewed guide and contributing documents? (Yes/No): no
1. version [x.y.z, hash, other]: 4.3.2-1
2. installed as a package or compiled from sources [deb, rpm, git, other]: .deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion standalone on docker image
6. operating system [16.04, Stretch, etc, FreeBSD, other]: docker

Dear,

I'm the maintainer of : https://github.com/baimard/motion-raspbian, I made image for docker in armhf for raspberry pi.

I try to update my docker hub repository with the version 4.3.2-1 but when I try to use in container my new image, I have this error : 

```
baimard@Azur:~ $ docker service logs -f detect_motion1
detect_motion1.1.1xw0wvea3o0m@vert    | motion: error while loading shared libraries: libmmal.so: cannot open shared object file: No such file or directory
```

That not happend with the old package : 

here is my Dockerfile from my repository : 
```
FROM debian:buster-slim

LABEL version="4.3.2-1"
LABEL maintainer="baimard@41m4rd.ovh"
LABEL description="Motion is a highly configurable program that monitors video signals from many types of cameras."

RUN apt-get update && apt-get upgrade -y --no-install-recommends
RUN apt-get install -y mailutils msmtp msmtp-mta sendemail gdebi-core wget
RUN wget https://github.com/Motion-Project/motion/releases/download/release-4.3.2/pi_buster_motion_4.3.2-1_armhf.deb
RUN apt install -y ./pi_buster_motion_4.3.2-1_armhf.deb
RUN apt install -f -y ; apt autoremove --purge

CMD ["motion"]
```

I have build my last image with the buster_motion_4.3.2-1_armhf.deb, that work normaly on a stack swarm of raspberry.

In my previous version, I have used the pi version of the deb package. So, I don't know if that is a real issue ...

regards,
Thank you for your work !

**Comment by tosiara** [comment]
> That not happend with the old package

Which old package do you mean?
Pi version has been built with MMAL support so it requires Rasbian with libmmal installed

**Comment by baimard** [comment]
my bad, I have never used pi_buster_motion_4.3.2-1_armhf.deb package in my old Dockerfile.

My brain not work correctly du to the COVID 19 situation ... :s

Sorry for this issue !
