### ISSUE TITLE
[Feature Request] TLS/SSL termination (SSL offloading) replace all occurrances of http with https within motion

### ISSUE THREAD

**Issue by xekon** [Motion-Project/motion#1266]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]: latest deb ubuntu 20.04 (installed via apt)
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  usb mjpeg
5. hardware [x86, ARM, other]: amd64
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  Ubuntu 20.04

Many web applications are now being served by either HAProxy or Nginx Reverse proxy, this allows you to renew your certs in one central spot, HAProxy and ACME is even built directly in to pfsense, but prior to that I used Nginx to do the same thing.

This would work without issue except that Motion Hard Codes the `<img>` links with http instead of https.

If there were just a simple config option that replaced all occurrences of http with https then my traffic would be encrypted.

So at the moment I am actually about to download the source, do a find replace for all occurances of http and replace with https, build it and give it a go, but a config option would be great.

I will post back after I build this and do my little hack to report back if the streams and page are all properly encrypted without any insecure content on page warnings.

I know its possible to copy the cert directly to the device running motion, but I **really really really** would rather not.

**Comment by Mr-Dave** [comment]
TLS functionality is already built into the Motion webcontrol and streams to provide https pages.    Is this something on automatically revising the specification of the certificate/key files?

**Comment by xekon** [comment]
so the way it works is remote clients connect to a host/domain that is running haproxy that is end to end encryption and then haproxy communicates to the destination (backend) without encryption but to the end user everything is encrypted.

With a setup like this you dont even need to have certs or keys on whatever device is running motion, you only need the certs on your edge router or device that is running either haproxy or nginx.

I found the relevant lines, theres only two entries that need changed:


`sudo nano /home/jake/source/motion/src/netcam_http.c`

```
    if ( netcam->haveproxy) {
        /*
         * Allocate space for a working string to contain the path.
         * The extra 4 is for "://" and string terminator.
         */
        if (url->port != 0) {
            ptr = mymalloc(strlen(url->service) + strlen(url->host) + 7 + strlen(url->path) + 4);
            sprintf((char *)ptr, "https://%s:%d%s", url->host, url->port , url->path);
        }else {
            ptr = mymalloc(strlen(url->service) + strlen(url->host) + strlen(url->path) + 4);
            sprintf((char *)ptr, "https://%s%s", url->host, url->path);
        }
```

however I am having trouble building, so bear with me for a bit until I can find some more recent instructions for building on ubuntu, the ones at here failed:  https://motion-project.github.io/motion_build.html

```
sudo apt install git autoconf automake autopoint build-essential pkgconf libtool git libzip-dev gettext libmicrohttpd-dev \
libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libavdevice-dev \
libjpeg-turbo8 libjpeg-turbo8-dev \
libwebp-dev

git clone https://github.com/Motion-Project/motion.git
cd motion
./configure
```
result is:

`-bash: ./configure: No such file or directory`

**Comment by xekon** [comment]
seems I can either hard code "https" into the relevant <img src> or I can figure out where strm_info.proto is set and adjust it there.

**Comment by xekon** [comment]
this video does a better job of explaining what ssl offloading is: https://www.youtube.com/watch?v=cBLYQ8bbe7c

**Comment by xekon** [comment]
I  have this working, the main benefits of SSL offloading are.

1. the device serving your motion page/stream no longer has the ssl overhead.
2. your certs can be managed from a single point, in my case its pfsense which has ACME.
3. haproxy on my pfsense router handles the certs and does the SSL offloading.

here is what I did but its a super dirty hack:

```
git clone https://github.com/Motion-Project/motion.git
cd motion
cp src/webu_html.c src/webu_html.c.old
sed -i 's/\"http\"/\"https\"/' src/webu_html.c
sed -i 's/\,strm_info\.proto//' src/webu_html.c
sed -i 's/\,webui->hostproto//' src/webu_html.c
sed -i 's/\%s\:\/\//https\:\/\//' src/webu_html.c
sed -i 's/\,webui->cntlst\[0\]->conf\.webcontrol_port//' src/webu_html.c
sed -i 's/\%d\//443/' src/webu_html.c

sudo killall motion
autoreconf -fiv
./configure --prefix=/opt/motion-4.3.2 --with-ffmpeg=/opt/ffmpeg
sudo make clean
sudo rm -rf /opt/motion-4.3.2
make
sudo make install
sudo cp /etc/motion/camera1.conf /opt/motion-4.3.2/etc/motion/camera1.conf
sudo cp /etc/motion/camera2.conf /opt/motion-4.3.2/etc/motion/camera2.conf
sudo cp /etc/motion/motion.conf /opt/motion-4.3.2/etc/motion/motion.conf
sudo /opt/motion-4.3.2/bin/motion
```

It is however working perfectly, no certs are present on the device running Motion, the certs only exist on haproxy.

**Comment by xekon** [comment]
Also to be clear I am not asking for all http to be replaced in motion permanently with https.

I am asking for an option that would allow you to force it to use https as the url even when it really is only http.

**Comment by tosiara** [comment]
Are you using webcontrol over haproxy?
I'm using motion stream through a reverse proxy with HTTPS without any issues

**Comment by xekon** [comment]
After my little hack to Motion, I can use all features including webcontrol over haproxy.
