### ISSUE TITLE
Chrome properly prompts both password but firefox displays broken box when stream auth is enabled.

### ISSUE THREAD

**Issue by Jieiku** [Motion-Project/motion#1267]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]: Motion 4.3.1+dirty20201119-84a31f7
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: usb mjpeg
5. hardware [x86, ARM, other]: amd64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 20.04

in your motion config:
webcontrol_auth_method 2
stream_auth_method 2

Now if you visit your site:  https://motion.example.com in **chrome**, then it will prompt for all passwords as soon as you hit the site, including the streams, and then it displays them correctly.

In firefox it prompts for the webcontrol password, but then displays the streams as a broken box, so you have to click on one of the streams to get the password to prompt, then go back to the webcontrol page and refresh, sometimes you even need to do a Control+F5 to bust the cache.

I am not certain if there is a workaround that could get this working on Firefox better or not, it might just be a browser limitation but I would like to think that maybe there is something that could be done.

**Comment by tosiara** [comment]
Yes, I can confirm that Firefox does not prompt for credentials when loading `<img src=http://localhost:8081/0/stream border=0 width=25%>` from the webcontrol web page

Motion itself cannot do anything about this behaviour. But we will try get in touch with Mozilla to either report a bug or get a clear explanation why this happens. Maybe it is a security feature to protect you from entering credentials into a malicious iframe
