### ISSUE TITLE
Use libmariadb-dev instead of libmariadbclient-dev

### ISSUE THREAD

**Issue by ottok** [Motion-Project/motion#1268]
Hello!

Your current CI uses libmariadbclient-dev. This is fine for now, but in the future when you update the Debian/Ubuntu version you are using in the CI, you should change those to libmariadb-dev (or libmariadb-dev-compat if you need to build something old that does not find the correct soname otherwise).

https://github.com/Motion-Project/motion/search?q=libmariadbclient-dev

**Comment by Mr-Dave** [comment]
Why?  It would seems that the only thing required would be the client libraries rather than all the components to support hosting the database.  It is my understanding that Mariadb can be set up to run the database on one computer and have clients on other machines.

**Comment by ottok** [comment]
Sorry, I wasn't precise with the motivation. The package
`libmariadbclient-dev` has been removed in latest MariaDB 10.5 in Debian
and Ubuntu, and installing libmariadbclient-dev will plain fail in the
future. Thus in future you should start using the package `libmariadb-dev`
instead to achieve the same thing.

**Comment by Mr-Dave** [comment]
Thanks for the clarification.  I see that now in SID.

**Comment by ottok** [comment]
Thanks!
