### ISSUE TITLE
segfault libavformat.so

### ISSUE THREAD

**Issue by mKenfenheuer** [Motion-Project/motion#1269]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: Version 4.3.2 (d603c62)
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb from releases
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam rtmp
5. hardware [x86, ARM, other]: x86_64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: ubuntu 18.04

Motion keeps crashing after a few hours with the following segfault:

`[45221.460546] motion[8481]: segfault at 8 ip 00007f119e075c20 sp 00007ffcc52b61a0 error 4 in libavformat.so.57.83.100[7f119df74000+22a000]`

Any ideas?

[motion.txt](https://github.com/Motion-Project/motion/files/5612057/motion.txt)
[cams.txt](https://github.com/Motion-Project/motion/files/5612242/cams.txt)
[log.txt](https://github.com/Motion-Project/motion/files/5612233/log.txt)

**Comment by mKenfenheuer** [comment]
I'll provide the log file as soon as i have another crash

**Comment by Mr-Dave** [comment]
I would first look into what could be causing the watchdog timeout.  Once the watchdog goes off, thread killing occurs which can cause other problems.  

So, I'd recommend checking to see if the device is out of space, does it occur with fewer cams, etc.  Also, the directory path with double slashes for the files looks unusual and perhaps is causing a lockup.  e.g. `/mnt/motion/video//2020/11/29/11_33_49-Terrasse.mp4`
