### ISSUE TITLE
Kernel panic if resolution above 640x480

### ISSUE THREAD

**Issue by pomputer** [Motion-Project/motion#1270]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.2-1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion, standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L (official Raspberry camera V2)
5. hardware [x86, ARM, other]: ARM (Raspberry Pi zero W)
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Debian Buster (Raspberry Pi OS)

Hi!
My system kernel panics after some time if I use a resolution over 640x480.
Expected result: Not crashing
Actual result: Crashes with kernel panic.

[Log](https://gist.github.com/pomputer/05a81908073404e608de1f41cebdc6e4)

![kernel_panic](https://user-images.githubusercontent.com/51286650/100544720-4c1ab500-3260-11eb-8cb4-f54f40a3e8e2.jpg)

**Comment by Mr-Dave** [comment]
I would recommend reimaging.

**Comment by pomputer** [comment]
I tried this on two different pi's and did the installation from scratch on both of them.
