### ISSUE TITLE
Incorrect PGM file parsing

### ISSUE THREAD

**Issue by geekman** [Motion-Project/motion#1271]
I have encountered a bug when using a `mask_file` exported using Photoshop.

I kept getting this error in the logs, and I made sure I could `less` the mask file from inside the Docker container:
```
get_pgm: Failed reading size in pgm file: No such file or directory
```

After tracing down the error message, it turned out to be this code fragment, which has nothing to do with not being able to find the file at all:

https://github.com/Motion-Project/motion/blob/84a31f7abc49dfe84e5b906bd85272498c16652b/src/picture.c#L887-L892

Additionally, it also highlights an incorrect behaviour when parsing the file. Photoshop generates the PGM header like this:

```
P5
1920
1080
255
<binary data>
```

It looks like the parsing of the PGM file by `get_pgm` is not really correct because the header fields are separated using "whitespace", which could be a newline or space, so a valid PGM could be `P5 1920 1080 255\n` as well.

I found this page here that describes the format: <http://paulbourke.net/dataformats/ppm/>

In the menatime, I worked around the bug by manually replacing the "\n" separating the image width & height by a space in my PGM file.

**Comment by KontorNoLimit** [comment]
Photoshop generates bad PGM file dude. Try GIMP instead

**Comment by tosiara** [comment]
From http://netpbm.sourceforge.net/doc/pgm.html
```
Each PGM image consists of the following:

    A "magic number" for identifying the file type. A pgm image's magic number is the two characters "P5".
    Whitespace (blanks, TABs, CRs, LFs).
    A width, formatted as ASCII characters in decimal.
    Whitespace.
    A height, again in ASCII decimal.
    Whitespace.
    The maximum gray value (Maxval), again in ASCII decimal. Must be less than 65536, and more than zero.
    A single whitespace character (usually a newline).
    A raster of Height rows, in order from top to bottom. Each row consists of Width gray values, in order from left to right. Each gray value is a number from 0 through Maxval, with 0 being black and Maxval being white. Each gray value is represented in pure binary by either 1 or 2 bytes. If the Maxval is less than 256, it is 1 byte. Otherwise, it is 2 bytes. The most significant byte is first. 
```
So, looks like whitespace used by PGM can be anything of `blanks, TABs, CRs, LFs`. In this case both cases are valid:

```
P5
1920
1080
255
<binary data>
```
```
P5
1920 1080
255
<binary data>
```
Marking as bug to either fix the code or move to some image parsing library?
