### ISSUE TITLE
Can't activate rtsp stream instead or in addition to http

### ISSUE THREAD

**Issue by fotisK69** [Motion-Project/motion#1272]
Hi,

i have configured my raspberry pi zero W + raspberry camera using motion on streaming the feed via http and this works well!
But, i am struggling to configure rtsp for the same feed.

How can I configure motion to use in addition to http or only rtsp?

BR

**Comment by Mr-Dave** [comment]
[Contributing Guidelines](https://github.com/Motion-Project/motion/blob/84a31f7abc49dfe84e5b906bd85272498c16652b/CONTRIBUTING.md)
