### ISSUE TITLE
Acces motion stream trew the same url on every network?

### ISSUE THREAD

**Issue by leaner50** [Motion-Project/motion#1277]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: Rpi 
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Rasbian

So i want to acces my motion camera stream from my rpi4 with my pc (that's on the same network) on my home network and on the school network trew some static url like http://picam:8081 because, i don't always know the ipadress from my pi. Is this possible? Yes, How?

Thanks in advance!

**Comment by Mr-Dave** [comment]
This really isn't a help forum.  [Contributing Guide](https://github.com/Motion-Project/motion/blob/a2e7f0dae6f0da12469ed3389e8deb559ad74ad4/CONTRIBUTING.md)
