### ISSUE TITLE
Help enabling h264_mmal

### ISSUE THREAD

**Issue by observer1** [Motion-Project/motion#1278]
0. Reviewed guide and contributing documents? (Yes/No):
not sure if all apropiate

1. version [x.y.z, hash, other]: 
motion/now 4.3.2-1 armhf

2. installed as a package or compiled from sources [deb, rpm, git, other]: 
deb from this site

3. standalone or part of third party [motion, MotionEyeOS, other]: 
motioneye, not MotionEyeOS tried standalone

4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
rtsp

5. hardware [x86, ARM, other]:
 ARM raspberry pi 4

6. operating system [16.04, Stretch, etc, FreeBSD, other]: 
Raspbian

Hi,
I'm trying to enable hardware acel with this camera, it seems to work with ffplay, but in motion it displays this message:

[WRN] [ENC] ffmpeg_set_codec_preferred: Preferred codec h264_mmal not found

the config line I'm using is:

netcam_decoder h264_mmal

Please help me with this

Thanks!!

**Comment by Mr-Dave** [comment]
This really isn't a help forum.  [Contributing Guide](https://github.com/Motion-Project/motion/blob/a2e7f0dae6f0da12469ed3389e8deb559ad74ad4/CONTRIBUTING.md)
