### ISSUE TITLE
Error compilation

### ISSUE THREAD

**Issue by mika-nt28** [Motion-Project/motion#1279]
0. Reviewed guide and contributing documents? (Yes/No): YES
1. version [x.y.z, hash, other]: master
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]:  ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  debian 10

When I lanch compilation i have this error to stop installation
> mmalcam.c:38:10: fatal error: interface/mmal/mmal.h: No such file or directory
#include "interface/mmal/mmal.h"

**Comment by Mr-DaveDev** [comment]
Can you post the entire configure log making sure to include the sections shown in this sample:
``` 
checking MMAL pkg-config path... .:/opt/vc/lib/pkgconfig
checking for MMAL... yes
checking FFmpeg pkg-config path... 
checking for FFmpeg... yes
checking MariaDB pkg-config path... 
checking for MariaDB... no
checking MySQL pkg-config path... 
checking for MySQL... no
checking PostgreSQL pkg-config path... 
checking for PostgreSQL... no
checking sqlite3.h usability... no
checking sqlite3.h presence... no
checking for sqlite3.h... no
checking for kill... /bin/kill
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating po/Makefile.in
config.status: creating man/Makefile
config.status: creating data/camera1-dist.conf
config.status: creating data/camera2-dist.conf
config.status: creating data/camera3-dist.conf
config.status: creating data/camera4-dist.conf
config.status: creating data/motion-dist.conf
config.status: creating data/motion.service
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile

   **************************
      Configure status       
      motion 4.3.1+git20201210-ee2341a
   **************************

CFLAGS: -D_THREAD_SAFE -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include  -I/usr/include/arm-linux-gnueabihf  -g -O2

LIBS:  -pthread   -ljpeg -lmicrohttpd  -L/opt/vc/lib -lmmal -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host -lvcsm -lvcos  -lvchostif  -lavutil -lavformat -lavcodec -lswscale -lavdevice 

LDFLAGS:  


OS                  : linux-gnueabihf
pthread_np          : no
pthread_setname_np  : yes
pthread_getname_np  : yes
XSI error           : no
webp support        : yes
V4L2 support        : yes
BKTR support        : no
MMAL support        : yes
FFmpeg support      : yes
libavformat version : 58.20.100
SQLite3 support     : no
MYSQL support       : no
PostgreSQL support  : no
MariaDB support     : no
 ```

Post the gcc line for  mmalcam.c such as 
```
gcc -DHAVE_CONFIG_H -I. -I..  -Dsysconfdir=\"/home/dave/motion/build/etc/motion\" -DLOCALEDIR=\"/home/dave/motion/build/share/locale\"  -D_THREAD_SAFE -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include  -I/usr/include/arm-linux-gnueabihf  -g -O2 -MT mmalcam.o -MD -MP -MF $depbase.Tpo -c -o mmalcam.o mmalcam.c 
```

Post the results of the following command:
``` export PKG_CONFIG_PATH=.:/opt/vc/lib/pkgconfig ; pkg-config --cflags mmal ```

**Comment by FunkyFab** [comment]
I have exactly the same issue. Can you please tell me how the issue was solved?

**Comment by Mr-Dave** [comment]
There was never a response so the issue was closed.  If you have the issue, then you'll need to provide the items requested.

**Comment by FunkyFab** [comment]
I use a software (Jeedom) that embeds motion in it. The standard install is to build motion from the source. But, now, motion is available as a Debian package. If I install it using the package, then install Jeedom, Jeedom sees that motion is already there, and doesn't try to build it ...
That doesn't solve the compilation issue ... but maybe you don't need to compile it ;-)

**Comment by tosiara** [comment]
Two people reported this issue, but refused to provide any logs. If there is a real issue, it will never get solved, because nobody cares to provide enough info

**Comment by mika-nt28** [comment]
Hello,

I'm sorry, I don't receive au notification reply
This compilation error is only with an Raspberry, on my server I don't have this problem
I run a new installation on my RPI and post this all result

The installtion script is 
`#!/bin/bash
touch /tmp/compilation_motion_in_progress
echo 0 > /tmp/compilation_motion_in_progress
echo "*****************************************************************************************************"
echo "*                                   Installation des dépendance                                     *"
echo "*****************************************************************************************************"
sudo apt-get install -y autoconf
sudo apt-get install -y automake
sudo apt-get install -y autopoint
sudo apt-get install -y build-essential
sudo apt-get install -y pkgconf
sudo apt-get install -y libtool
sudo apt-get install -y libzip-dev
sudo apt-get install -y libjpeg-dev 
sudo apt-get install -y libjpeg8-dev
sudo apt-get install -y libjpeg62-turbo-dev
sudo apt-get install -y git
sudo apt-get install -y libavformat-dev 
sudo apt-get install -y libavcodec-dev 
sudo apt-get install -y libavutil-dev 
sudo apt-get install -y libswscale-dev 
sudo apt-get install -y libavdevice-dev 
sudo apt-get install -y libwebp-dev gettext 
sudo apt-get install -y libmicrohttpd-dev
sudo apt-get install -y libwebp-dev
sudo apt-get install -y gettext
sudo apt-get install -y libmicrohttpd-dev
echo 25 > /tmp/compilation_motion_in_progress
echo "*****************************************************************************************************"
echo "*                                          Installation de FFMPEG                                   *"
echo "*****************************************************************************************************"
sudo apt-get install -y libavformat-dev
sudo apt-get install -y libavcodec-dev
sudo apt-get install -y libavutil-dev
sudo apt-get install -y libswscale-dev
sudo apt-get install -y libavdevice-dev
sudo apt-get install -y ffmpeg
if [ -d "/usr/local/src/ffmpeg" ]; then 
  sudo rm -R /usr/local/src/ffmpeg
fi
#cd /usr/local/src/
#echo 35 > /tmp/compilation_motion_in_progress
#git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
#cd ffmpeg
#echo 40 > /tmp/compilation_motion_in_progress
#./configure --prefix=/usr/local/src/ffmpeg
#echo 45 > /tmp/compilation_motion_in_progress
#make
#sudo make install
echo 50 > /tmp/compilation_motion_in_progress
echo "*****************************************************************************************************"
echo "*                                          Compilation de motion:                                   *"
echo "*****************************************************************************************************"
if [ -d "/usr/local/src/motion" ]; then 
  sudo rm -R /usr/local/src/motion
fi
cd /usr/local/src/
git clone https://github.com/Motion-Project/motion.git
cd motion
git checkout 4.3
echo 55 > /tmp/compilation_motion_in_progress
sudo autoreconf -fiv
echo 60 > /tmp/compilation_motion_in_progress
./configure
echo 70 > /tmp/compilation_motion_in_progress
make
echo 80 > /tmp/compilation_motion_in_progress
sudo make install
echo 95 > /tmp/compilation_motion_in_progress
sudo usermod -a -G motion www-data
echo 100 > /tmp/compilation_motion_in_progress
echo "*****************************************************************************************************"
echo "*                                Installation de motion terminé                                     *"
echo "*****************************************************************************************************"
rm /tmp/compilation_motion_in_progress`
