### ISSUE TITLE
"Bad request" on reverse HTTPS proxy for web stream

### ISSUE THREAD

**Issue by KontorNoLimit** [Motion-Project/motion#1288]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.2-debian-stretch
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L USB UVC
5. hardware [x86, ARM, other]: ARM64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Stretch

I created reverse proxy for Motion http stream in nginx HTTPS server at virtual location /path/to/stream. Both HTTP and HTTPS reverse proxy server can show basic auth login window but when the proxy points to / of Motion stream the webpage shows *"Bad request"*, when points to /0/stream it repeats requiring login. Bugs seem not to be in nginx.

**Comment by Mr-Dave** [comment]
The `/` versus `/0/stream` depends upon how you have specified everything within the Motion configuration files as described in the [guide](https://motion-project.github.io/motion_config.html#OptDetail_Stream).   

The multiple requests for credentials you indicate are not observed when running directly.

**Comment by tosiara** [comment]
@KontorNoLimit can you make `tcpdump` capture on the motion side while getting `Bad request`? This will show what is the issue

**Comment by KontorNoLimit** [comment]
> @KontorNoLimit can you make a `tcpdump` capture on the motion side while getting `Bad request`? This will show what is the issue

Sorry but I cannot fully understand. I promise I will attempt to capture packets later, thanks for giving such an idea

**Comment by tosiara** [comment]
run on motion box: `tcpdump -i eth0 -w motion.pcap`
in your browser load the stream and get Bad request
get back to motion box and hit ctrl+c

open motion.pcap and find the HTTP request to motion (you can apply filter `tcp.port==8081`). there you should see the full HTTP request Nginx sent to motion. Which GET request does it show?

**Comment by KontorNoLimit** [comment]
> run on motion box: `tcpdump -i eth0 -w motion.pcap`
> in your browser load the stream and get Bad request
> get back to motion box and hit ctrl+c
> 
> open motion.pcap and find the HTTP request to motion (you can apply filter `tcp.port==8081`). there you should see the full HTTP request Nginx sent to motion. Which GET request does it show?

I might know what's wrong. The 'Autherization' header has an arribute `uri="/proxy/path"` which might be the reason of Bad request. This GET request has my auth information as well
