### ISSUE TITLE
"Help" Applying ffmpeg filters to stream

### ISSUE THREAD

**Issue by CaioPiccirillo** [Motion-Project/motion#1289]
Hi, 

I'm using version 4.3.1 with Debian 9 (amd64) with bttv card and this card provides interlaced image, I want to deinterlace it  and stream the image because it's used for monitoring traffic on toll systems and our software captures the image through http.
I'm going to use a loopback like "ffmpeg -f v4l2 -i /dev/video0 -vf yadif -f v4l2 /dev/video1" to solve the problem, but I want to know if there's another way to configure it inside motion? Because I want to wrap this loopback with motion when it starts (avoiding using script).

Thanks in advance

**Comment by Mr-Dave** [comment]
Motion does include any of the FFMPEG filtering functionality so the option you indicated is the way to go.

**Comment by CaioPiccirillo** [comment]
> Motion does include any of the FFMPEG filtering functionality so the option you indicated is the way to go. 

I understand that motion support it, but how can I apply it to http stream without creating a v4l2loopback? Older versions of motion had ffmpeg_deinterlace but it was dropped due to ffmpeg upgrade (https://github.com/Motion-Project/motion/issues/96).

**Comment by Mr-Dave** [comment]
That option was not applicable to the situation you reference.  That option was associated with the encoding of movies.

**Comment by CaioPiccirillo** [comment]
How it's not associated? I mentioned that I'm working with bttv card and I want to interlaced the output, but with ffmpeg it's available through yadif which is a filter. I solved it creating a v4l2loopback but I just want to know if there's a simpler way using only motion's parameters.
