### ISSUE TITLE
installing on Centos 7

### ISSUE THREAD

**Issue by ratsaby** [Motion-Project/motion#1291]
I am following the instructions in: 
https://motion-project.github.io/motion_build.html#Configure_Script
I installed the libraries. Then I download motion from Git, unzip and cd to the folder.

But when I try to Configure Script, 
I run
autoreconf

And get:
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:9: error: required file './config.guess' not found
configure.ac:9:   'automake --add-missing' can install 'config.guess'
configure.ac:12: error: required file './config.rpath' not found
configure.ac:9: error: required file './config.sub' not found
configure.ac:9:   'automake --add-missing' can install 'config.sub'
configure.ac:2: error: required file './install-sh' not found
configure.ac:2:   'automake --add-missing' can install 'install-sh'
configure.ac:2: error: required file './missing' not found
configure.ac:2:   'automake --add-missing' can install 'missing'
src/Makefile.am: error: required file './depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf: automake failed with exit status: 1

Any advice?

thanks

**Comment by tosiara** [comment]
In the same doc search for `CentOS 7` for instructions

**Comment by ratsaby** [comment]
I now execute ./motion and it appears to be running.
Is there some GUI App that I can install in Centos which enables to  view the webcam's stream?

**Comment by Mr-Dave** [comment]
Make sure to review the [contributing guidelines](https://github.com/Motion-Project/motion/blob/9d8d01b5a0dc1d532fbaf63729ae2cb2ac49eb63/CONTRIBUTING.md) and the [guide](https://motion-project.github.io/motion_guide.html).  Additional resources even include [videos](https://www.youtube.com/channel/UCZpOjUMnc-uO3qIyZAD_4lg/videos) of the setup of Motion.

**Comment by ratsaby** [comment]
So the above didn't work for me. 
What did work is: I installed the package https://github.com/radiorabe/centos-rpm-motion
I can run ./motion from command line well.
However, if I make a service and run it using systemctl start motion.service 
then I get the error:

motion[15643]: [1:ml1] [ERR] [VID] vid_start: V4L2 device failed to open

Here is the motion.service

[Unit]
Description=motion detection system
Documentation=man:motion(1) https://motion-project.github.io/
Wants=network-online.target
After=network-online.target

[Service]
User=root
ExecStart=/usr/bin/motion -n
ExecReload=/bin/kill -HUP $MAINPID
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
==========================


Any idea why "vid_start: V4L2 device failed to open" via the service? (yet it is successful via direct execution of motion form command line)

**Comment by tosiara** [comment]
Avoid running motion as root. Instead add your current user to `video` group
