### ISSUE TITLE
EXTPIPE records duplicate movies

### ISSUE THREAD

**Issue by dreasb** [Motion-Project/motion#1295]
Version: 4.3.2 (2020-12-25)
Source: Gentoo Linux, build from source with ffmpeg support
Standalone: Motion, ffmpeg, operating system only
Camera: RTSP Network Camera, h264 video stream
Hardware: Intel Pentium J5005, VAAPI with x265 and hevc/x265
Operating System: Gentoo Linux, 64Bit

**Failure**
Extpipe videos will be overwritten. No opportunity to disable default movies from passthrough or system-encoded videos. In consequence GPU videos will be created in parallel / in addition to default video's. Extpipe movies will be overwritten.  

**Reproduce, Option 1**
use ffmpeg command without -y parameter (do not overwrite existing files) will fail
```
emulate_motion on
movie_filename %Y-%m%d_%H-%M-%S_%$
movie_extpipe_use on
movie_expipe ffmpeg ... %f.mkv
```
start motion via command line: "motion -c /etc/motion/motion.conf -n -d 7" and observe ffmpeg failure message

**Reproduce, Option 2**
two video files will be created in parallel within the target directory
```
emulate_motion on
movie_filename %Y-%m%d_%H-%M-%S_%$
movie_extpipe_use on
movie_expipe ffmpeg ... %f.compress.mkv
```
observe the target directory, two video files will be created in parallel

**Remarks**
Works as designed? I cannot imagine. No documentation found. 
Please double check my both configuration files.

**motion.conf**
```
# LOGGING
# --------------------------
log_level 6
log_file /var/log/motion.log

# STORAGE
#- -------------------------
target_dir /home/data/motion

# MOTION HIGHLIGHT BOX
# --------------------------
locate_motion_mode on
locate_motion_style redbox

# COMMON MOTION
# --------------------------
noise_tune on
minimum_motion_frames 20
event_gap 60
pre_capture 0
emulate_motion on

# COMMON MOVIE
# ---------------------------
movie_max_time 15
#movie_codec mp4
#movie_passthrough
movie_filename %Y-%m%d_%H-%M-%S_%$
movie_extpipe_use on
movie_extpipe ffmpeg -y -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -f rawvideo -video_size %wx%h -framerate %fps -i pipe:0 -c:v hevc_vaapi -qp:v 23 -vf 'format=nv12,hwupload' %f.compress.mkv

# COMMON TEXT
# ---------------------------
text_left %Y-%m-%d %H:%M:%S %q
text_right 
text_changes
text_event

# WEB CONTROL INTERFACE
# ---------------------------
webcontrol_port 9000
webcontrol_localhost off
webcontrol_parms 2
webcontrol_interface 0

# STREAM
# ---------------------------
stream_localhost off
stream_auth_method 0
stream_preview_scale 50
stream_preview_newline on
stream_preview_method 0
stream_quality 75
stream_maxrate 3
stream_motion on

camera /etc/motion/camera1.conf
```

**camera1.conf**
```
# NAME OF CAMERA
# ----------------------
camera_id = 1
camera_name = somewhere

# CONNECTION TO CAMERA
# ----------------------

netcam_userpass user:pass
netcam_url rtsp://192.168.x.x/ch0

# CAMERA RESOLUTION 
# ---------------------------------
width 1920
height 1080
framerate 12

# CAMERA TEXT
# ---------------------------------
text_scale 3

# MOTION
# ---------------------------------
threshold 103680
lightswitch_frames 18
lightswitch_percent 100

# STREAM
# ---------------------------------
stream_maxrate 12
stream_port 9001

# EVENTS
# ---------------------------------
on_camera_lost curl -X POST https://api.telegram.org/bot/.../sendMessage -F chat_id='xxx' -F text='...'
```

**Comment by genius3000** [comment]
`movie_output` defaults to on as specified in the documentation[documentation](https://motion-project.github.io/motion_config.html#movie_output). The shipped example config[shipped example config](https://github.com/Motion-Project/motion/blob/master/data/motion-dist.conf.in#L122-L123) also contains it.

**Comment by dreasb** [comment]
I have read the documentation and see many example files.

`movie_output on` - two video files are written or the large one overwrites the extpipe output file (see reproduce option 2 above)
`movie_output off` - no video will be created as far as a motion is detected 

The `movie_output` option did not solve the issue.

**Comment by tosiara** [comment]
Please provide log with `-d 7` and `movie_output off`

**Comment by dreasb** [comment]
I can not reproduce it anymore. Maybe a previous process was running in the background during testing the `movie_output off` setting and I did not spend to much time with the setting parameter. The hint from genius3000 was already the correct one. But from perspective of the documentation and the example files, I would not have come up to the solution.

Just for my understanding, related to the documenation: https://motion-project.github.io/motion_config.html
- `movie_output on/off` controls if ffmpeg libraries are in use to create the movie
- `movie_passthrough on/off` - depends on `movie_output` setting, and makes a passthrough
- `movie_extpipe_use` - controls if in addition the rawvideo pipe can be processed by any external encoder

This was not clear for me before I read your comments.

Just as a proposal: `movie_output` off | ffmpeg | passthrough | extpipe 

From my point of view the issue can be closed, except you want it to append some details to your documentation.

Many thanks for your support, 

Stay Healthy!
