### ISSUE TITLE
Feature request: Create directories with mode 777, allowing umask for configuration

### ISSUE THREAD

**Issue by HenkDemper** [Motion-Project/motion#1297]
Using motion 4.3.2 in daemon mode (as a service), installed using wget & builddeb.sh on Asus Tinkerboard running Debian Stretch (9.13), arm. This works fine.

But I want to both manually delete created video files (.mkv, .mpg, .jpg) inclduing sub-directories and/or use an automatic script that copies/delete these files for archiving, both without requiring root permission. For this, I would like the created files and directories to include the group-write permission, and make sure my user is in the motion group (one-time setup, done).

By default, files created in motion have mode 644 and directories 755. When you change the umask setting from the default 022 to 002 (by adding --umask 002 to line with start-stop-daemon in /etc/init.d/motion), then this will have effect on the files: They will have now have mode 664 on disk as expected, so the file part is solved.

But the directories still have mode 755, even with umask setting 002. This is due to the following line in util.c, where group & other write mode is specifically prohibited:
```c
int mycreate_path(const char *path)
   ...
   mode_t mode = S_IRWXU | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH;
   ...
   if (mkdir(buffer, mode) == -1 && errno != EEXIST)
```
If you want to allow the user to have control over the group/other write access, then I believe the common way is to set mkdir(...,0777) and have the configurable umask setting mask off any bits. So the proposal would be to make the following small change (with little risk imho) to the mode line:
```c
mode_t mode = S_IRWXU | S_IRWXG | S_IRWXO;  // Mode 0777
```
Under default circumstances with umask being 022 this will result in the same directory mode 755 as now, but now users will have the possibility to alter this by changing umask.

This request has been pre-discussed in the motion mailing list and apart from myself at least one other advising user was in favour of this change... I will be happy to test/confirm any change, if applied, as needed.

Many thanks !

Henk Demper

**Comment by ZoneMR** [comment]
+1

It makes no sense to me that group users can have write access to files, but not the folders those files are organised inside. 

Both files and directories created with 0664 would make sense.

**Comment by Mr-DaveDev** [comment]
I just created PR #1370 that is slightly different than the illustrated changes here but I think will resolve the directory permissions.  If anyone can test/validate this, it would be appreciated.

What I'd also ask the community is how to solve the file permissions to get those to 0664.  As I read the original issue, it points to revisions required in init.d in order to get the correct file permissions.  But, I'm not sure that is viable any more.  As indicated in the change log for [bullseye](https://metadata.ftp-master.debian.org/changelogs//main/m/motion/motion_4.3.2-1_changelog), Motion was moved to systemd instead of the init script.  Is there an alternative revision required to that?

**Comment by HenkDemper** [comment]
Hi Dave,

Recalling:

Directories by default created with RWX (R=4, W=2, X=1) for U/G/O, resulting in mode 0777
Files by default created with RW for U/G/O, resulting in mode 0666 (don't need X rights)

Default umask is typically 022 (masking off W bits for G/O), hence this will result in:
Directories mode 0755 and files mode 0644

Changing this to umask 002 (masking off W bit for O only) will result in
Directories mode 0775 and files mode 0664 (group can now delete both)

Then:

1. In #1370 you propose

`mode_t mode = S_IRWXU | S_IRGRP | S_IWGRP | S_IXGRP | S_IROTH | S_IXOTH;`

which means that directories are created with 0775, thereby whatever the umask is not allowing 'others' to delete directories. I would add S_IWOTH (or use S_IRWXU | S_IRWXG | S_IRWXO) to create directories in mode 0777 and use umask for masking specific bits and don't hardcode anything...
(I changed my original comment, some of the S_IRWX* values were invalid).

2. If anyone can test/validate this:
I will be happy to test/confirm at next motion release (from which I normally install/run), or is that too late ?
(and pretty confident the extra bit(s) will do its work)

3. how to solve the file permissions to get those to 0664:
By default umask 022, group can't delete either directories 0755 or files 0644. Both will be solved in one go by setting umask 002, resulting in directories 0775 and files 0664.

I started out changing umask using https://www.computernetworkingnotes.com/linux-tutorials/how-to-change-default-umask-permission-in-linux.html, that didn't work and based on Damian's reply in the motion group and https://serverfault.com/questions/166176/ways-to-set-umask-on-ubuntu-for-daemon-processes I changed /etc/init.d/motion:

`if start-stop-daemon --start --oknodo --exec $DAEMON -b --chuid motion --umask 002 ; then`

That solved the group-write issue for files and you change will solve it for directories as well.

Unfortunately I don't use systemd (on Asus Tinkerboard SBC), so not sure how systemd will handle umask, or what the default motion behaviour should be (default umask typically 022 or force umask 002)...

**Comment by Mr-DaveDev** [comment]
I think I'm going to go with the 775 along with a --umask=002.  That permits a super user to control the permissions via groups and has the files and directories in sync

**Comment by HenkDemper** [comment]
Hi Dave, you can do that and I'm fine, just that we are aware that there will be no way using program-external umask settings to allow the 0775-created groups to become 0777 = other-writable, even if you would use umask=000 (it would stay 0775 then). Why not set create mask to 0777 and put that decision on (super-)user side using umask (022, 002 or 000) outside the application ?
PS: Anyway I will use motion (not other) group, so for me the proposed fix will be an improvement anyway...

**Comment by Mr-Dave** [comment]
Thanks for your patience Henk.  I finally got it and implemented the full revision.
