### ISSUE TITLE
Cameras not working when Motion is in Docker

### ISSUE THREAD

**Issue by jeff-h** [Motion-Project/motion#130]
I'm trying to run motioneye (https://github.com/ccrisan/motioneye) in a Docker container. Everything appears to have worked fine, and motioneye is running fine, except that neither of my two cameras work. Both are network cameras, one is RTSP and the other is http from an Android phone.

I also have a VIrtualbox VM with Ubuntu 16.04 and motioneye installed on it, and it works perfectly there; both cameras work fine, so I know my camera URLs are correct and that in the right environment, Motion is working perfectly with my cameras.

I think Motioneye is fine; I believe it's Motion that's failing to connect to my camera URLs when running inside Docker.

`motion.log` contains many repeats of the following:

```
[1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.1.41:554/onvif1)
[2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (http://192.168.1.13:8080/video)
[2] [ALR] [NET] netcam_handler_loop: Camera handler thread [4] started
[1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://192.168.1.41:554/onvif1): Invalid data found when processing input
[1] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
[1] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.1.41:554/onvif1)
[0] [ERR] [ALL] main: Thread 1 - Watchdog timeout, trying to do a graceful restart
[0] [ERR] [ALL] main: Thread 1 - Watchdog timeout, did NOT restart graceful,killing it!
[0] [ERR] [ALL] main: cleaning Thread 1
```

and Docker is putting dozens of these in OS X's system log:

`13/08/16 9:07:57.278 PM Docker[4187]: dropping unexpected TCP packet sent from 172.17.0.5:35500 to 192.168.1.41:554 (valid sources = 192.168.65.2, 0.0.0.0)`

and then dozens of these:

`Aug 13 21:36:52 jeffs-mac Docker[4187]: Socket.TCPV4.read 192.168.1.41:554: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof`

Any ideas? I'm not experienced with Docker so apologies if this is something trivial.

I should mention, I'm running the Dockerfile that comes with motioneye (https://github.com/ccrisan/motioneye/blob/master/extra/Dockerfile).

**Comment by jogu** [comment]
As far as I can see, motion is doing the right thing, but your Docker configuration is either blocking or just not correctly passing the network traffic. I would guess you probably can't ping the cameras from inside the Docker container either. I think you need help from someone that knows Docker (I don't).

**Comment by jeff-h** [comment]
Thanks for the ping suggestion — I'll check that.

**Comment by jeff-h** [comment]
Oops, I didn't realise you can't `ping` a specific port. I tried `telnet 192.168.1.41 554` both directly from my Mac and from inside the container and both returned:

```
Trying 192.168.1.41...
Connected to 192.168.1.41.
```

As a test, `telnet 192.168.1.41 555` fails in both.

**Comment by jogu** [comment]
I guess I was wrong about ping then. 

It still looks like some kind of weird networking or firewall configuration issue, and the logging from docker appears to confirm that. You need a docker expert. :)

**Comment by jeff-h** [comment]
Thanks for your help — hopefully someone successfully using Docker will notice this and take pity on me :)

**Comment by Mr-Dave** [comment]
Perhaps this user could assist.  https://github.com/kfei/dockmotion

**Comment by Mr-Dave** [comment]
If there is anything identified with the motion application in that environment, please open a new issue

**Comment by jeff-h** [comment]
Just as a final followup; the above issue occurred when running Docker on OS X. I have subsequently switched to running Docker on an Ubuntu 16.04 machine, and in that environment MotionEye (and by implication motion) runs perfectly, connecting to my cameras with no problems whatsoever.
