### ISSUE TITLE
 motion event unique database IDs not supported for PostgreSQL and SQLite3

### ISSUE THREAD

**Issue by wbclay** [Motion-Project/motion#1306]
1. version [x.y.z, hash, other]: dd4b7a16

As noted in dbse.c, dbse_exec_pgsql() and dbse_exec_sqlite3() at remarks after "if (save_id)":
//ToDO: Find the equivalent option for pgsql / sqlite3

**Comment by wbclay** [comment]
submitter has working code ready to push when permission to do so is granted

**Comment by tosiara** [comment]
You are welcome to submit pull request for review

**Comment by Mr-Dave** [comment]
closed via #1310
