### ISSUE TITLE
image capture blocked by PostgreSQL database session recovery

### ISSUE THREAD

**Issue by wbclay** [Motion-Project/motion#1307]
1. version [x.y.z, hash, other]: dd4b7a16

dbse.c, dbse_exec_pgsql(): if a PostgreSQL session is dropped by a DBMS
restart, network disruption, or server delays, thread image capture can be
blocked for several seconds during DB session recovery.

**Comment by wbclay** [comment]
submitter has working code ready to push when permission to do so is granted

**Comment by tosiara** [comment]
You are welcome to submit pull request for review

**Comment by Mr-Dave** [comment]
closed via #1310
