### ISSUE TITLE
[Enhancement] Store video files using AV1

### ISSUE THREAD

**Issue by matebuteler** [Motion-Project/motion#1312]
Hi. I really enjoy using motion, but there's a problem: the video feed is encoded in H.264, and i have really low capacity hard drives. As the AV1 codec is open source, and ffmpeg supports it (https://trac.ffmpeg.org/wiki/Encode/AV1), is there any chance that it would be possible to store video using AV1? I think it would really improve motion.

**Comment by tosiara** [comment]
You didn't seem to follow contribution guide. Check it, it contains all the needed info, like: https://motion-project.github.io/motion_config.html#movie_codec
