### ISSUE TITLE
mmalcam_control_params parameters

### ISSUE THREAD

**Issue by leoheck** [Motion-Project/motion#1315]
Hi, I am fighting with these roi parameters
Where I can find the meaning of these values?
```
mmalcam_control_params -roi 0.5,0.5,0.25,0.25
```
For instance, I am changing these manually, and after 10 changes I still could no crop the right zone. 
I could not find anything on google by searching for `mmalcam_control_params roi`

This page does say nothing about roi
https://motion-project.github.io/motion_config.html#mmalcam_control_params

**Comment by leoheck** [comment]
I could find this

```
  214    {CommandROI,         "-roi",       "roi","Set region of interest (x,y,w,d as normalised coordinates [0.0-1.0])", 1},
```

It is line 214 from here https://fossies.org/linux/motion/src/raspicam/RaspiCamControl.c

So, it means it is, `x,y,w,d`

- x as in - initial position o x-axis
- y as in - initial position o y-axis
- w as in - width of something
- d as in - typo for h, height, or something.

So, where is the origin of the image? Top-Right? Top-Left? Bottom-Right? Bottom-Left? I think x and y are related to that. Where is w,h?

Any help?

**Comment by tosiara** [comment]
```
In general, the command line options that are available via the raspistill / raspivid applications are the options that can be specified in this Motion configuration option
```
https://motion-project.github.io/motion_config.html#mmalcam_control_params
