### ISSUE TITLE
mmalcam_control_params and roi - Motion 4.3.2

### ISSUE THREAD

**Issue by dominik-90** [Motion-Project/motion#1317]
0. Reviewed guide and contributing documents? (Yes/No): **yes**
1. version [x.y.z, hash, other]: **4.3.2**
2. installed as a package or compiled from sources [deb, rpm, git, other]: **deb**
3. standalone or part of third party [motion, MotionEyeOS, other]: **motion and MotionEye**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **mmal - raspberry pi cam v2**
5. hardware [x86, ARM, other]: **RPi 4b**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: **Raspbian Buster**

Hi, I’m not able to run motion with this parameter. I want to crop/zoom picture from RPi camera. I can put roi parameter to `raspistill` command and it works, but when I set roi in motion.conf or put it to Extra Motion Options in MotionEye as `mmalcam_control_params -roi <values>` (like to raspistill) nothing change... I checked and e.g. -vf works and flips the screen.

Any ideas? Should I config something more I forgot?

**Comment by tosiara** [comment]
Can you upload a log with `-d 9` and reproduce the issue?
