### ISSUE TITLE
Video quality issue

### ISSUE THREAD

**Issue by fractal815** [Motion-Project/motion#1318]
0. Reviewed guide and contributing documents? (Yes/No):yes
1. version [x.y.z, hash, other]: 4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: ubuntu

Greetings!    Today I thought I would ask about a long standing problem that I have had with my recorded videos.   
Please view the attached video, and you will instantly see the problem.    Frequently, though not always I see this odd artifact, where only the moving object is shown for several seconds, before the gray background disappears.      below is the config file for the camera, the motion config, a snapshot of the artifact and the problem video.    Thanks in advance for your thoughts and efforts on this...  FB

![image](https://user-images.githubusercontent.com/16502902/107548964-46fdae80-6b9d-11eb-9a3a-4bb3ae18df91.png)

https://user-images.githubusercontent.com/16502902/107548112-431d5c80-6b9c-11eb-8e2b-dc29557d34a6.mp4
[motion.conf.txt](https://github.com/Motion-Project/motion/files/5960169/motion.conf.txt)
[threadfrontyard.conf.txt](https://github.com/Motion-Project/motion/files/5960170/threadfrontyard.conf.txt)

**Comment by tosiara** [comment]
Those are decoding artefacts. Check the log and you should find there ffmpeg complaining about errors
