### ISSUE TITLE
Feature request: trigger script on custom defined area (more specific than predefined area)

### ISSUE THREAD

**Issue by paede81** [Motion-Project/motion#1319]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mjpeg
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: raspbian

I'm looking for a solution, that I can define areas within the image which triggers a dedicated action for this area.
The current predefined areas are not precise enough (1 to 9). The idea is that I can define regions of an image which triggers a dedicated script which motion is defected within this area.

An easy solution would be:
In the config you define something like:
`on_area_50_50_200_200_detected /bin/script.sh`
where the values are:
`on_area_<x-coordinate>_<y-coordinate>_<x-width>_<y-width>_detected: <name of the script>`

A bit more complicated but more comfortable way would be:
Define in the config own defined named areas like:
`<x-coordinate>_<y-coordinate>_<x-width>_<y-width>: <unique name of area>`
`50_50_200_200: door entry`
`200_200_50_50: letter box`
`400_320_100_100: garage`

now you can define custom scripts like:
`on_specific_area_detected: <name of defined area> <name of script>`
like: 
`on_specific_area_detected "door entry" /bin/script_door_movement.sh`
`on_specific_area_detected "garage" /bin/script_garage_movement.sh`

**Comment by tosiara** [comment]
You can use these params for your script to get info about where the motion has been triggered:
```
%i | width of motion area
%J | height of motion area
%K | X coordinates of motion center
 %L | Y coordinates of motion center
```
https://motion-project.github.io/motion_config.html#conversion_specifiers
