### ISSUE TITLE
FPS on recorded videos

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#132]
The fps for movie creation limits the maximum to 30fps.  When the frames are being captured at a rate higher than 30fps, this results in a the movie playing at fast forward speed.

**Comment by tosiara** [comment]
I wonder, does this affect ext_pipe videos? Need to give a try
Also, adding fps related issue here for reference https://github.com/Motion-Project/motion/issues/56

**Comment by Mr-Dave** [comment]
closed by pull #150
