### ISSUE TITLE
Motion area_detect

### ISSUE THREAD

**Issue by alansan2020** [Motion-Project/motion#1328]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]: 4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 20.04

Hi to everyone,

Is it possible to increase the number of area_detect zones (actually limited to 9 zones) for a more precise setting of area-detect zones please?!

best regards

alansan2020

**Comment by tosiara** [comment]
Those are hardcoded, so source code changes are needed to extend it.
But you can try to write your own script that takes X,Y coordinates and WxH of the motion area (where motion has been detected) and handle it in the same way. See: https://motion-project.github.io/motion_config.html#conversion_specifiers
