### ISSUE TITLE
motion web preview and a probably RFC 2616 problem

### ISSUE THREAD

**Issue by menges404** [Motion-Project/motion#1333]
0. Reviewed guide and contributing documents? (Yes/No):yes
1. version [x.y.z, hash, other]:  4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: rpm
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cams: pi,levelone,panasonic,intellinet and V4L
5. hardware [x86, ARM, other]: x84
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Tumbleweed 5.10.16-1-default

first of all: great job! i love motion!

I stumble in trying get a full html preveiw from a motion server with more then 6 cams. 
I'll check the motion html code but found no reason why the web-preview even stops with only 6 cams.
The preview of these 6 cam worked fine.
I'll try different browser - no changes.
I'll try changing configs an cam - no changes.
After searching a while i'll found that there is a (necessary) recommendation to limit 
single domain/host connection to ... 6. (older ones 2) 

so, a workaround (e.g. in Firefox) could be:
    about:config  
and increase the 
    network.http.max-persistent-connections-per-server

maybe this could be a hint in the documentation?  
or maybe a page split every 6 cams? (but i like the full-hd 10 cam overview ;) )

**Comment by tosiara** [comment]
This has been discussed on the mail list, please check maybe your question has been answered:
https://sourceforge.net/p/motion/mailman/message/37037166/
(use View entire thread)
