### ISSUE TITLE
Watchdog timeout did NOT restart, killing it!

### ISSUE THREAD

**Issue by jarus0** [Motion-Project/motion#1334]
Hello there, 
I have attached 2 analog camera through Easycap USB 2.0 (per camera one Easycap)
Individual tested all working well
hardware info:- Raspberry pi 4
```
➜  ~ cat /etc/debian_version
10.8
➜  ~ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
➜  ~ uname -a 
Linux raspberrypi 5.10.23-v7l+ #1406 SMP Mon Mar 15 15:44:40 GMT 2021 armv7l GNU/Linux

```
Installed deb file as instructed [motion](https://github.com/Motion-Project/motion/releases/download/release-4.3.2/buster_motion_4.3.2-1_armhf.deb)

Running both cameras from motion below error come up
```
[0:motion] [ERR] [ALL] motion_watchdog: Thread 2 - Watchdog timeout. Trying to do a graceful restart
[0:motion] [ERR] [ALL] motion_watchdog: Thread 2 - Watchdog timeout did NOT restart, killing it!
```

At  motion run time system info below given
```
HTOP result
CPU process < 10%
Memory Usage < 150M 

(121M/7.69G)
IO process < 10.00 K/s  (sudo iotop --kilobytes --only --delay 1)
```

Below file changes attached
[camera3-dist.conf.txt](https://github.com/Motion-Project/motion/files/6243383/camera3-dist.conf.txt)
[camera4-dist.conf.txt](https://github.com/Motion-Project/motion/files/6243384/camera4-dist.conf.txt)
[motion.conf.txt](https://github.com/Motion-Project/motion/files/6243385/motion.conf.txt)
[log_file.txt](https://github.com/Motion-Project/motion/files/6243389/log_file.txt)

below cmd result attached
```
ffmpeg -f video4linux2 -list_formats all -i /dev/video4
ffmpeg -f video4linux2 -list_formats all -i /dev/video6
[video4linux2,v4l2 @ 0x5161c0] Raw       :     yuyv422 :           YUYV 4:2:2 : 720x480 720x576 640x480 320x240 160x120
```

At lower resolution works
Thanks for looking into it. Waiting for your response.

**Comment by tosiara** [comment]
can you also provide syslog and dmesg right after you reproduced the message?

**Comment by jarus0** [comment]
Thanks for the fast response appreciated 

nothing special in dmesg 
[dmesg.txt](https://github.com/Motion-Project/motion/files/6243462/dmesg.txt)

but Syslog
[syslog.txt](https://github.com/Motion-Project/motion/files/6243461/syslog.txt)

**Comment by tosiara** [comment]
Are you able to capture using ffmpeg simultaneously into the same usb drive?
Like:
ffmpeg -f video4linux2 -i /dev/video0 /mnt/out.mp4 &
ffmpeg -f video4linux2 -i /dev/video1 /mnt/out1.mp4

**Comment by jarus0** [comment]
Yes but look like some problem, See FPS
![Screenshot](https://user-images.githubusercontent.com/29514830/113295900-69e34e00-9316-11eb-8cde-eef544c6616b.png)

**Comment by tosiara** [comment]
Can you make the same screenshot in 60 seconds after you started the last ffmpeg command? I want to see how many frames will that capture, as currently the bottom picture shows only 16 frames compared to 359 on the top.
So far I suspect, that your Raspberry is not capable handling that much of USB bandwidth. Watchdog timeout error usually means that the frame capturing thread was blocked and not responding for too long. Would make sense if your USB V4L driver is blocking it

**Comment by jarus0** [comment]
Problem solved by changing Easycap model (the new easy cap has the option of MJPG, compressed format).

Raw yuyu is not working.

Old Easycap output
```[video4linux2,v4l2 @ 0x17251c0] Raw       :     yuyv422 :           YUYV 4:2:2 : 720x480 720x576 640x480 320x240 160x120```

New Easycap output 
```
[video4linux2,v4l2 @ 0xeaf1c0] Compressed:       mjpeg :          Motion-JPEG : 480x320 640x480 720x480
[video4linux2,v4l2 @ 0xeaf1c0] Raw       :     yuyv422 :           YUYV 4:2:2 : 480x320
```
