### ISSUE TITLE
Missing range in docs of vid_control_params

### ISSUE THREAD

**Issue by Zurd** [Motion-Project/motion#1335]
Missing range for vid_control_params: https://motion-project.github.io/motion_config.html#vid_control_params

I did some testing and brightness, contrast, saturation and hue seems to be from 0 to 256, this information should be added to the documentation.

**Comment by Mr-DaveDev** [comment]
I think if you look further at that section, you'll understand why no ranges are suggested in the documentation.  Your camera had 0 to 256, my sample camera used for documenting that section shows

> The following is a sample output from the log and examples of how to specify the parameters
>     [1:ml1:c1] [INF] [VID] v4l2_ctrls_list: ---------Controls---------
>     [1:ml1:c1] [INF] [VID] v4l2_ctrls_list: V4L2 ID Name and Range
>     [1:ml1:c1] [INF] [VID] v4l2_ctrls_list: ID09963776 Brightness, 0 to 127
>     [1:ml1:c1] [INF] [VID] v4l2_ctrls_list: ID09963777 Contrast, 0 to 63
>     [1:ml1:c1] [INF] [VID] v4l2_ctrls_list: ID09963778 Saturation, -100 to 100
>     [1:ml1:c1] [INF] [VID] v4l2_ctrls_list: ID09963788 White Balance, Automatic, 0 to 4
>  
i.e. Different cameras have different valid ranges.

**Comment by Zurd** [comment]
Oh yes, I see them now, I skipped that section and turns out my range is a bit different from my testing:

```
Apr  5 13:54:59 camera-front motion: [1:ml1:Front] [INF] [VID] v4l2_ctrls_list: ID09963776 Brightness, 0 to 255
Apr  5 13:54:59 camera-front motion: [1:ml1:Front] [INF] [VID] v4l2_ctrls_list: ID09963777 Contrast, 0 to 127
Apr  5 13:54:59 camera-front motion: [1:ml1:Front] [INF] [VID] v4l2_ctrls_list: ID09963778 Saturation, 0 to 127
Apr  5 13:54:59 camera-front motion: [1:ml1:Front] [INF] [VID] v4l2_ctrls_list: ID09963779 Hue, -128 to 127
```

Thanks for the information!
