### ISSUE TITLE
Simultaneous recording and motion detection config confusion.

### ISSUE THREAD

**Issue by jarus0** [Motion-Project/motion#1336]
Hello there,
I gone through the documentation and tried multiple combinations but didn't succeed.

Basically, I want to continue recording movies all time. and make a DB entry whenever motion happens. for that as suggested in the [guide](https://motion-project.github.io/motion_config.html)
```
movie_output off
emulate_motion on    
area_detect '123456789'
on_area_detected /home/suraj/Projects/SecurityCam/test.sh
```
Turning off emulate_motion working as expected but this only records when motion detects.

Thanks for looking into it

**Comment by tosiara** [comment]
If you want to record movie set `movie_output on`

**Comment by tosiara** [comment]
And it is better to ask questions on the mail list as there are more people to answer

**Comment by jarus0** [comment]
I think you haven't read the problem. 
My goal is to 
1) Record 24x7 from the camera.
2) on motion detect run script.

movie_output option has no problem work as expected (on > save video as much time as motion detects).

For recording, all the time set on emulate_motion but then the event never ends. (consequently can't detect further new events / motion)

> [1:ml1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
> Motion Happens from script log.

BTW Thanks for the awesome repository and your time.

**Comment by tosiara** [comment]
Motion can only record movie during an event. So, you can have 24/7 movie recording and a separate independent motion detection. The only possible feature is `timelapse` - it keeps recording regardless of events. Other than that would require v4lloopback piping video stream into both motion and some third party tool for continuous recording, ex, ffmpeg
