### ISSUE TITLE
movie_max_time controls the event's length instead of event_gap

### ISSUE THREAD

**Issue by BasWeg** [Motion-Project/motion#1337]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: apt get
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: USB
5. hardware [x86, ARM, other]: Intel 64Bit
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 20.10

Hi,
I just want to use motion to send mqtt messages if an motion event starts and if it ends.
Therefore I configured:
picture_output off
movie_output off
event_gap 180

Nevertheless I get Motion detected and "End of event" every minute, even with event_gap = 180.
If I change movie_max_time to 600, I get both events every 10minutes. (even if there is motion within 180seconds)

Is this wanted?
Should I change  movie_max_time to 0, to have the correct behavior defined by event_gap?

Best regards
Bastian

**Comment by tosiara** [comment]
Can you provide `-d 7` log for a reproduced issue?

**Comment by BasWeg** [comment]
Yes of course,
I've made two logs, one with movie_max_time =30 and one with movie_max_time = 60; event_gap @ 180
[motion_1min.log](https://github.com/Motion-Project/motion/files/6304676/motion_1min.log)
[motion_30sec.log](https://github.com/Motion-Project/motion/files/6304677/motion_30sec.log)

**Comment by tosiara** [comment]
Yeah, I can see from the log that an event takes movie_max_time long and not event_gap. This is strange
Can you try to update motion to the latest one and test again with event_gap 180 and upload the new log?

**Comment by tosiara** [comment]
Reproduced.
Looks like motion uses `movie_max_time` to control how much time the event takes. This is wrong as `event_gap` controls that.

```
..
08:36:45 motion[150556]: [0:motion] [INF] [ALL] event_gap                 60
08:36:45 motion[150556]: [0:motion] [INF] [ALL] movie_max_time            10
..
08:37:08 motion[150556]: [1:ml1] [INF] [EVT] event_new_video: Source FPS 10
08:37:08 motion[150556]: [1:ml1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
08:37:18 motion[150556]: [1:ml1] [NTC] [ALL] mlp_actions: End of event 1
..
```

**Comment by BasWeg** [comment]
OK, good to read. 
At the moment I've implemented an additional motion-timeout at the MQTT-receiver side.

To update to the latest version (once fixed) in ubuntu I should use the "Installing with a release deb package" instructions, or?
best regards

**Comment by tosiara** [comment]
Same issue with 4.2
```
09:36:58 motion[156735]: [0:motion] [NTC] [ALL] motion_startup: Motion 4.2.2 Started
..
09:36:58 motion[156735]: [0:motion] [INF] [ALL] event_gap                 60
09:36:58 motion[156735]: [0:motion] [INF] [ALL] movie_max_time            10
..
09:37:01 motion[156735]: [1:ml1] [INF] [EVT] event_new_video: Source FPS 10
09:37:01 motion[156735]: [1:ml1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
09:37:11 motion[156735]: [1:ml1] [NTC] [ALL] mlp_actions: End of event 1
09:37:11 motion[156735]: [1:ml1] [INF] [EVT] event_new_video: Source FPS 10
09:37:11 motion[156735]: [1:ml1] [NTC] [ALL] motion_detected: Motion detected - starting event 2
09:37:21 motion[156735]: [1:ml1] [NTC] [ALL] mlp_actions: End of event 2
09:37:40 motion[156735]: [1:ml1] [NTC] [ALL] mlp_actions: End of event 3
```

**Comment by tosiara** [comment]
Same issue with 4.1
```
09:52:10 motion[194445]: [0:motion] [NTC] [ALL] motion_startup: Motion 4.1.1 Started
..
09:52:10 motion[194445]: [0:motion] [INF] [ALL] event_gap                 60
09:52:10 motion[194445]: [0:motion] [INF] [ALL] max_movie_time            10
..
09:52:16 motion[194445]: [1:ml1] [INF] [EVT] event_new_video: Source FPS 2
09:52:16 motion[194445]: [1:ml1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
09:52:26 motion[194445]: [1:ml1] [NTC] [ALL] mlp_actions: End of event 1
```

**Comment by tosiara** [comment]
Same with 4.0 (same 4.1 config used)
```
09:56:10 motion[197409]: [0:motion] [NTC] [ALL] motion_startup: Motion 4.0.1 Started
..
09:56:15 motion[197409]: [1:ml1] [NTC] [EVT] event_new_video Source FPS 2
09:56:15 motion[197409]: [1:ml1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
09:56:25 motion[197409]: [1:ml1] [NTC] [ALL] motion_loop: End of event 1
```

**Comment by tosiara** [comment]
Same with 3.4
```
09:59:23 motion[199114]: [0] [NTC] [ALL] motion_startup: Motion 3.4.1~rc01 Started
..
09:59:30 motion[199114]: [1] [NTC] [EVT] event_new_video FPS 2
09:59:30 motion[199114]: [1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
09:59:40 motion[199114]: [1] [NTC] [ALL] motion_loop: End of event 1
10:00:03 motion[199114]: [1] [NTC] [ALL] motion_loop: End of event 2
```

**Comment by tosiara** [comment]
I even tried ancient 3.2 in a virtual machine - same issue
```
10:29:33 qemu motion: [0] Motion 3.2.12 Started
10:29:33 qemu motion: [0] ffmpeg LIBAVCODEC_BUILD 3547904 LIBAVFORMAT_BUILD 3544067
10:29:33 qemu motion: [0] Thread 1 is from /etc/motion/motion.conf
10:29:33 qemu motion: [0] motion-httpd/3.2.12 running, accepting connections
10:29:33 qemu motion: [0] motion-httpd: waiting for data on port TCP 8080
10:29:33 qemu motion: [1] Thread 1 started
10:29:35 qemu motion: [1] Resizing pre_capture buffer to 1 items
10:29:35 qemu motion: [1] Started stream webcam server in port 8081
10:29:56 qemu user: running logger on_event_start
10:30:06 qemu user: running logger on_event_end
10:30:07 qemu user: running logger on_event_start
10:30:17 qemu user: running logger on_event_end
```
So, it looks like the bug existed from the beginning

**Comment by tosiara** [comment]
From the source it seems like indeed the event is ended as soon as either max_movie_time or event_gap exceeds:
https://github.com/Motion-Project/motion/blob/master/src/motion.c#L2431
But instead of ending an event, max_movie_time should write movie and start a new one

**Comment by BasWeg** [comment]
OK, until the fix is available I will set movie_max_time = 0, then this condition is not executed. 
I do not generate any movies, so in my case it is fine. No hurry :)

**Comment by KennethLavrsen** [comment]
Remember the gap is not defining the length of an event. It defines the period of no motion that ends an event. 
Normally you will have the event as a number much smaller than the movie_max_time. The max time for the movie is meant to limit how long a movie we allow to be recorded so you do not end up with hour long movies because some branch is flapping in the breeze. I have not been an active developer on this project for years but it seems the event is forced to end when the max time for the movie is reached. That sort of makes sense, doesn't it?

**Comment by tosiara** [comment]
To illustrate the current design

Given the current default values:
`event_gap 60`
`movie_max_time 60`
```
|event start | motion for 50 sec | no motion for 50 sec | motion 30 sec| no motion 60 sec             | event end |
             | movie start file 1   |  movie start file 2 | movie start file 3  | movie start file 4  |
```
Total event time: 50 + 50 + 30 + 60 = 190 sec (3 minutes 10 seconds)
Total movies: 4
