### ISSUE TITLE
mmalcam_control_params roi not working

### ISSUE THREAD

**Issue by n0sn3b** [Motion-Project/motion#1338]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mmal
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian

Motion log at debug level 7:
https://gist.github.com/n0sn3b/659a487957abc5538b0d6684adb13954

`cat /etc/motion/motion.conf`:
https://gist.github.com/n0sn3b/633e6382e1d2bcf96630d543434994dd

`mmalcam_control_params -roi 0.1,0.1,0.75,0.75` has no effect on the streamed video.
The same parameters work with raspivid

**Comment by genius3000** [comment]
That log shows motion is using V4L2 via /dev/video0 and not the mmalcam. I have no experience with motion and the mmalcam but to start with, remove 'value' from the `mmalcam_name` configuration line.

**Comment by n0sn3b** [comment]
> That log shows motion is using V4L2 via /dev/video0 and not the mmalcam. I have no experience with motion and the mmalcam but to start with, remove 'value' from the `mmalcam_name` configuration line.

Thanks for the catch. This was one of my last tests where i used the simplest config file as possible and i let that slip. It doesn't change anything though.
I updated the log file and the config file as i just ran it again, with your correction.

I tried removing the bcm2835_v4l2 module to force mmal but no cameras are detected.

**Comment by tosiara** [comment]
There were multiple reports about `roi` not being functional, but nobody actually provided any further data. So, suppose all works fine.
https://github.com/Motion-Project/motion/issues/1004
https://github.com/Motion-Project/motion/issues/1315
https://github.com/Motion-Project/motion/issues/1317
Where did you get the deb file? Can you try older Raspbian and older version of motion?

**Comment by n0sn3b** [comment]
> There were multiple reports about `roi` not being functional, but nobody actually provided any further data. So, suppose all works fine.
> #1004
> #1315
> #1317
> Where did you get the deb file? Can you try older Raspbian and older version of motion?

I got the deb file from the motion github, file buster_motion_4.3.2-1_armhf.deb. I had version 4.1.x before, the one that comes from Raspbian. Same result.

**Comment by tosiara** [comment]
Try installing `pi_buster_motion_4.3.2-1_armhf.deb`

**Comment by n0sn3b** [comment]
> Try installing `pi_buster_motion_4.3.2-1_armhf.deb`
With that version camera is detected as mmal! i can see that -roi now has an effect. It was as simple as this! Thanks Tosaria.

**Comment by n0sn3b** [comment]
May i suggest the documentation here https://motion-project.github.io/4.3.2/motion_config.html be amended to specify that when using a Pi, you should install the "pi_*_motion_*_armhf.deb" and not the generic armhf one?

**Comment by zoff99** [comment]
this is still not working for me.
i am using the latest pi_buster_motion_4.3.2-1_armhf.deb
and -hf -vf is working but roi is doing nothing
