### ISSUE TITLE
stop motion saving mkvs every ten minutes

### ISSUE THREAD

**Issue by Shendrach** [Motion-Project/motion#1342]
Hey guys, 

I've installed motion on my raspberry pi to create one picture every minute from a rtsp camera stream in order to create a timelapse movie from that pictures. However, I only need motion to take the pictures, I will do the timelapse video manually. 

Now I am new to debian, raspberry and all that stuff and it was not an easy task for me to configure the motion. 
conf to take the pictures, save them on my NAS and so on. However, I successfully managed to do that. Now the thing is, motion does not only take one picture every minute, it also saves a mkv video every nine to eleven minutes. I can delete them manually, but I would like to know why motion does that and how to edit the motion.conf to make it stop that. Do you have any idea what the reason for this could be? It costs me like 4,5 gigs a day, which is too much in the long run. 

Thanks in advance and cheers!

**Comment by edzeg** [comment]
In your config turn off movie output:

`movie_output off`

**Comment by Shendrach** [comment]
Thanks a lot. That sounds as simple as I hoped it would be! :)
