### ISSUE TITLE
Text overlays show in live stream but not in saved movies or images (text_left, text_right)

### ISSUE THREAD

**Issue by akomakom** [Motion-Project/motion#1344]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  4.2.2-1ubuntu1
2. installed as a package or compiled from sources [deb, rpm, git, other]:   deb 
3. standalone or part of third party [motion, MotionEyeOS, other]:   standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  net cams (RTSP)
5. hardware [x86, ARM, other]:   x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  Ubuntu 20.04

## problem

`text_left`, `text_right`, `text_changes` and `locate_motion` appear clearly in a live stream (eg http://ip:camport) but not in the recorded (event) movies or images.  Snapshot images **do** have the overlay.

## note
This used to work some time ago, but not sure in which version.

## main config:
(thread configs override a few things)

```go
daemon off           
setup_mode off 
log_file /var/log/motion/motion.log
log_level 6        
target_dir /data/MOTION
videodevice /dev/video0
width 640   
height 480
framerate 8
text_left CAMERA %t
text_right %Y-%m-%d\n%T
emulate_motion off
threshold 1500
despeckle_filter EedDl
minimum_motion_frames 1
event_gap 60
pre_capture 5
post_capture 5
picture_output best
picture_filename %Y%m%d%H%M%S-%q
movie_output on
movie_max_time 1800
movie_quality 45
movie_codec mp4
movie_filename %t-%v-%Y%m%d%H%M%S
webcontrol_port 8180
webcontrol_localhost off
webcontrol_parms 0
stream_localhost off
camera_dir /etc/motion/conf.d
snapshot_interval 3600
on_event_start touch /dev/shm/.motion-cam-%t
on_event_end rm -f /dev/shm/.motion-cam-%t
on_picture_save mkdir -p `dirname %f`/thumb ; convert -resize 160 %f `dirname %f`/thumb/`basename %f`
snapshot_filename %Y-%m-%d/snap-C%t/%H%M%S-snapshot
picture_filename %Y-%m-%d/img-C%t/%H%M%S-%q
movie_filename %Y-%m-%d/movie-C%t/%H%M%S
timelapse_filename %Y-%m-%d/timelapse-C%t
timelapse_interval 60        
timelapse_mode daily  
locate_motion_mode on                       
text_changes on                           
lightswitch_percent 50                                                                                                                                                                           
netcam_keepalive on                                                                             
smart_mask_speed 5                         
stream_maxrate 5  
```

## Typical thread config (6 different cam models/brands)

```go
camera_id 6
stream_port 8186
netcam_url rtsp://X.Y.Z.96:554/12
netcam_highres rtsp://X.Y.Z.96:554/11
width 640
height 352
threshold 9000
threshold_tune off
minimum_motion_frames 1
mask_file /some/path/motion-cam6-mask.pgm
```

## Saved image 
A "best" image saved for a motion event.
Note: larger size, saved from `netcam_highres`
![motion-image-saved](https://user-images.githubusercontent.com/12100822/117505012-5a78a580-af51-11eb-9b83-dc15f090d451.jpg)

## Live image (screenshot)
Grabbed from browser (ip:cam_port)
![motion-image-live](https://user-images.githubusercontent.com/12100822/117505015-5b113c00-af51-11eb-8f1e-1412573c56c8.jpg)

**Comment by genius3000** [comment]
You're using `netcam_highres` which as [documented](https://motion-project.github.io/motion_config.html#netcam_highres) does not include those overlays in saved videos and images.

**Comment by akomakom** [comment]
Completely forgot about that, and google-fu failed me. 

Thanks.  That's too bad, I don't think that my server can handle analyzing this many streams at high res.... We'll see.
