### ISSUE TITLE
No return message for /detection/{pause|start} get functions

### ISSUE THREAD

**Issue by tvc-dps** [Motion-Project/motion#1345]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.2 
2. installed as a package or compiled from sources [deb, rpm, git, other]: buster_motion_4.3.2-1_amd64.deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net_cam rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Debian 4.19.181-1

{IP}:{port}/{camid}/detection/start Start or resume motion detection.
{IP}:{port}/{camid}/detection/pause Pause the motion detection.

Commands do not return an response like expected:
"Camera %d Detection paused%s\nDone %s\n"
"Camera %d Detection resumed%s\nDone %s\n"

**Comment by tosiara** [comment]
What does the command return for you? Please full log including the command you send

**Comment by tvc-dps** [comment]
I am trying to open
http://192.168.1.100:8080/0/detection/start Start or resume motion detection.
http://192.168.1.100:8080/0/detection/pause Pause the motion detection
The above 2 pages do not return anything, but made expected action pause or resume detection for the camera

 http://192.168.1.100:8080/0/detection/status return detection status as expected

**Comment by tvc-dps** [comment]
Let me know if there more need some specific logs

**Comment by Mr-DaveDev** [comment]
Just change the [webcontrol_interface](https://motion-project.github.io/motion_config.html#webcontrol_interface) to 1 or 2

**Comment by tvc-dps** [comment]
> Just change the [webcontrol_interface](https://motion-project.github.io/motion_config.html#webcontrol_interface) to 1 or 2

It solved my problem
Thank you
