### ISSUE TITLE
compile error with latest ffmpeg master: assignment of member ‘video_codec’ in read-only object

### ISSUE THREAD

**Issue by denisio** [Motion-Project/motion#1349]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: github
2. installed as a package or compiled from sources [deb, rpm, git, other]: sources
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp 
5. hardware [x86, ARM, other]:  x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 20.04.2 LTS

I can't build the current version...

1)  git clone https://github.com/ffmpeg/ffmpeg
     cd ffmpeg
     ./configure --prefix=/home/devd/src/ffmpeg/out --enable-libx264 --enable-libx265 --enable-libv4l2 --enable-gpl --enable-pthreads
     make && make install

2) git clone https://github.com/Motion-Project/motion
    cd motion
    autoreconf -fiv
    ./configure --with-ffmpeg=/home/devd/src/ffmpeg/out --without-mysql --without-pgsql --without-sqlite3 --prefix=/home/devd/src/motion/out
    make
.....
/home/devd/src/ffmpeg/out/include/libavcodec/packet.h:474:6: note: declared here
  474 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
ffmpeg.c: In function ‘ffmpeg_passthru_codec’:
ffmpeg.c:1245:46: error: assignment of member ‘video_codec’ in read-only object
 1245 |             ffmpeg->oc->oformat->video_codec = stream_in->codecpar->codec_id;
      |                                              ^
make[2]: *** [Makefile:472: ffmpeg.o] Error 1

**Comment by denisio** [comment]
libavformat/avformat.h

typedef struct AVFormatContext {
    const AVClass *av_class;
    const struct AVInputFormat *iformat;
    const struct AVOutputFormat *oformat;   <<<<<<<<<<<<
    ,,,,,,

**Comment by tosiara** [comment]
Try to checkout ffmpeg stable release, for example:
git checkout release/4.0

**Comment by denisio** [comment]
4.4 - OK
4.3 - OK
4.0 - OK
