### ISSUE TITLE
First New Version

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#135]
Assemble items for next version.

- [x] 1.  Merge the 3.4.1 back into master
- [x] 2.  Revise version number to be 3.4.1+short git hash
- [x] 3.  Identify pulls to be included
- [x] List of changes since 3.4.1
- [x] 4.  Test pulls across distributions
- [x] Validation no security/critical errors introduced.
- [x] 5.  Implement pulls into master
- [x] 6.  Integration test of master with all pulls across distributions.
- [x] FreeBSD
- [x] Fedora
- [x] Debian Jessie
- [x] Debian Wheezy
- [x] 12.04
- [x] 14.04
- [x] 16.04
- [ ]  Arch?
- [x]  PI 1 Raspbian Jessie
- [x]  PI 2/3 Raspbian Jessie
- [ ]  OpenSuse
- [x] 7.  Revise manual.1 to reflect 2016 and maintained by Motion-Project developers and links
- [x] New project page links
- [x] New Options
- [x] 8.  Revise, obtain, validate and merge in the new motion_guide.html
- [x]  New options
- [x]  Revised names
- [x]  BSD and Fedora building instructions in guide.
- [x]  Embed the ConfigureOptionChanges html grid with new options
- [x]  Update CHANGELOG
- [x]  Update README (BSD)
- [x]  Update README(Mac)
- [x]  Update README(Linux)
- [x]  Create Release notes
- [x] 9.  Branch, revise version number to 4.0
- [x] 10.  Merge release-4.0 branch back to master and revise version to 4.0+git short hash
- [x] 11.  Create deb packages, RPMs, and tarball
- [x]  Instructions for signing and creating hash keys for DEBs
- [x]  Instructions for how create RPM file
- [x]  Debian DEBs (Jessie/Wheezy, x64/i386)
- [x]  PI (1 and 2/3)
- [ ]  RPM
- [ ]  12.  Create release in git and revise home page

Please comment on items that are observed to be missing, bad sequences, bad practices or on items to be considered for pulling.  The final list from this issue will then be consolidated and put into a wiki topic as the release checklist.

**Comment by tosiara** [comment]
Should we also use `git` keyword in the version string? Like, `3.4.1-git-2caced3`?

**Comment by Mr-Dave** [comment]
Yes, I think we should.  I just looked at apt and the most common approach that I saw was +gitYYYYMMDD.  However, I don't think that would work for us since it would correspond to date users compiled it instead of the date we committed it.  Looking at the ones with a git hash it was formatted as 3.4.1+git2caced3.  The hash isn't the easiest to interpret but I think it works.

**Comment by Mr-Dave** [comment]
Joseph is this consistent with what you've observed in other applications?  Joerg, any issues/comments?  Note I'm having issues getting a new repo set up which is causing a bit of a delay here.

**Comment by jogu** [comment]
Yes, seems like a decent plan to me. I'm not sure "4. Test pulls across distributions" is necessarily required for every pull request. I'd do it on a risk based approached (ie. if we get a smell that something might cause trouble do the testing, otherwise run with it and we can fix it at 6 and/or when a user spots it).

[I think travis-ci will give us free hosted continuous automatic testing of all pull requests and branches on ubuntu, I'll maybe have a go at setting that up at some point.]

**Comment by Mr-Dave** [comment]
I pushed some items.  Lets see how this works out.  I agree on the cross distribution testing being judgement. I develop on Ubuntu and have lots of VMs saved for those versions.  BSD, RPM based systems and new PI's are where I've observed the issues.

**Comment by Mr-Dave** [comment]
I would like to get together the list of items for inclusion in a release.  The pi cam was the largest one I wanted to make sure was included.  The list I was thinking of would be issues : #88, #103, #159 and resolving pull requests #93, #154 and #158.  We of course will also need to address the manual.1, INSTALL, CHANGELOG and motion_guide.html.  (Any volunteers?)  

If there are other items that you think we need for the first version, please note them here.  Also, if there are other changes (even if not completed), add a issue so we can track them.  Once we establish the list, I'd like to resolve only those issues and go into a code freeze for testing and documentation.

**Comment by jogu** [comment]
I've tried to make progress on all of those.

I would be tempted to drop "Tcp fastopen server #93" from the list; I've commented on the pull request it has a fundamental issue and I don't think it's important. (AIUI there's a system wide configuration system you can set to force sockets to default to fastopen anyway, so there are other ways for users to enable fastopen if they want it.)

**Comment by jogu** [comment]
There's one more I'd like to try and sneak in too, https://github.com/Motion-Project/motion/pull/163 which fixes a problem that always annoys me running on my pi (and when I'm VPNed into my home network where DNS seems to sometimes not do the right thing...).

**Comment by Mr-Dave** [comment]
Ok.  #93 is off the list.  #163 is in.

**Comment by slokhorst** [comment]
@Mr-Dave, maybe you could edit your first post and [add checkboxes](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments). Then it's easier to see what is done and what we can help out with.

**Comment by Mr-Dave** [comment]
@slokhorst  I added checkboxes.  (We will see how it works).  Action items that I would love to get help upon are:  
4.  Look for any possible security holes with respect to the web interface and what we've revised.  
8/11 on building instructions for BSD and Fedora since they are not what I use.  Especially any hints on how to get ffmpeg.
Overall, I'd say that we're in code freeze and testing to validate builds work, documentation is updated and we didn't introduce any new bugs.  There are also obviously some trivial ones in the list that just require a bit of time to research on my part.

**Comment by slokhorst** [comment]
On installing ffmpeg:

For FreeBSD, it is just a simple `pkg install ffmpeg`. I don't think any explanation besides [this](https://github.com/slokhorst/motion/blob/72eccf1b58b54b0d316830f25c3bc0f358b89cbe/README.FreeBSD) is needed. I have verified the build instructions are working with #211.

For Fedora, the easiest is to obtain it via [RPM Fusion](http://rpmfusion.org/):
````bash
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install ffmpeg
````

**Comment by Mr-Dave** [comment]
With the latest pull for ffmpeg regression fixes, I'd like to create the branch to 4.0 and then merge back in with the new version number.  
@jogu Is this the process you were thinking of or do we just need to revise the version number and tag it?  I know we still have the threading and other issues but I want to make sure a release gets out before I have to go back to my working job.  

Once we have it tagged or branched, I will add a new repo to the project "Motion-Packaging" that will contain the debian rules needed to build the packages.  I'm also going to add the bash script which will allow everyone to execute the script to create their own debs.

If anyone sees ANY issues with above, please post.

**Comment by jogu** [comment]
Sounds fine to me.

I'd probably veer towards including the threading fixes in the release if we can, I just put a pull request for them, they've been stable for a few days now.

**Comment by Mr-Dave** [comment]
Version 4.0 released.
