### ISSUE TITLE
SEGV with git master after June 14 updates

### ISSUE THREAD

**Issue by gene-git** [Motion-Project/motion#1353]
git master is crashing with SEGV 

Last commit which works is  34091a770c679da79f5be58f392020a8514521ee from Jan 20.
The next set of commits after this (June 14 I think) now cause motion to crash.

Setup has 10 network cameras. Logs show motion connects to all cameras then logs 'resize' and  crashes:

 ```
netcam_rtsp_connect: highres: Camera (1) connected
 ---
 image_ring_resize: Resizing pre_capture buffer to 4 items
 motion.service: Main process exited, code=killed, status=11/SEGV
```

Server running on intel x64 running fully updates linux. Code is compiled with gcc 11.1.0.

Going back to commit 34091a770 and all works fine again.

**Comment by Mr-DaveDev** [comment]
Thank you for reporting.  

I'll try to look tonight and if I can't recreate I'll need more details on your underlying system to reproduce.  DBS installed/used, underlying distro, params, etc.

**Comment by gene-git** [comment]
Thanks and of course.
No databases involved - just save to files  -  each camera uses rtsp with netcam_high_url and netcam_url.
I can send you configs if that's helpful.  
Distro is arch linux and i'm using ffmpeg 2:4.4

**Comment by Mr-DaveDev** [comment]
It is not crashing for me yet.  Can you post the whole log at the debug level so I can see the config parms as well as the compile options used? (The available/not available section of the log)

**Comment by gene-git** [comment]
Problem went away if I do a full clean before building 
i.e.
`git clean -dffx `

So sorry for not realizing that sooner.
