### ISSUE TITLE
Unable to get single image

### ISSUE THREAD

**Issue by ICEconchy** [Motion-Project/motion#1356]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: Package (Sudo apt-get install motion) 
3. standalone or part of third party [motion, MotionEyeOS, other]:  standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L
5. hardware [x86, ARM, other]:  ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian (Debian)

When using the /current path, the video stream appears instead. Unable to get single image

**Comment by tosiara** [comment]
Can you update to the latest version and check again?

**Comment by ICEconchy** [comment]
![Screenshot_20210629-190203_JuiceSSH](https://user-images.githubusercontent.com/20145992/123845781-80e10e80-d90c-11eb-8660-842175ee4ad1.jpg)
Apparently its the latest version

**Comment by tosiara** [comment]
Pick a Pi build according to your version from: https://github.com/Motion-Project/motion/releases/tag/release-4.3.2
And do `apt-get remove motion ; dpkg -i pi.deb`

**Comment by ICEconchy** [comment]
That fixed it, so the issue is that the repository has a lower version
