### ISSUE TITLE
./configure asking for libjpeg-dev on Mac OS

### ISSUE THREAD

**Issue by namankumar** [Motion-Project/motion#1357]
0. Reviewed guide and contributing documents? (Yes/No): Y
1. version [x.y.z, hash, other]: master, so 4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: trying to compile
3. standalone or part of third party [motion, MotionEyeOS, other]:  standalone as instructed for mac os on: https://motion-project.github.io/motion_build.html
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: n/a
5. hardware [x86, ARM, other]: Macbook Pro M1 (ARM)
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Mac OS 11.4

Hello, running /.configure, results in `configure: error: Required package libjpeg-dev not found, please check motion_guide.html and install necessary dependencies`

I've already installed libjpeg on my machine using homebrew as instructed on motion_build.html. It's also in my path. So I'm not sure what to try next. Please help.

**Comment by tosiara** [comment]
Please provide the full log of ./configure
