### ISSUE TITLE
Is it possible to stop on_event_end from firing, when the service is stopped or on program exit (CTRL+C, pkill, etc.)?

### ISSUE THREAD

**Issue by mortenmoulder** [Motion-Project/motion#1358]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: apt install
3. standalone or part of third party [motion, MotionEyeOS, other]: Standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: N/A
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Debian 10

I have a really simple motion detection system set up. When motion has been detected, change the brightness to 100%. When no motion has been detected, change the brightness to 10%.

If I run motion in a service or via command line, and I exit the program or stop the service, `on_event_end` gets called, which turns my screen brightness down to 10%. My shell script simply contains:

```
#!/bin/sh
xrandr --output eDP1 -d :0 --brightness 1
```

and for undetected:

```
#!/bin/sh
xrandr --output eDP1 -d :0 --brightness 0.1
```

If that's not possible, it would be really nice to have an `on_exit` event or something similar, that runs after `on_event_end`.

**Comment by tosiara** [comment]
Try to update to the latest version `4.3.2`
