### ISSUE TITLE
Add documentation note that PGM files must have 8-bit depth

### ISSUE THREAD

**Issue by mrd** [Motion-Project/motion#1359]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: n/a
5. hardware [x86, ARM, other]: n/a
6. operating system [16.04, Stretch, etc, FreeBSD, other]: n/a

Please add a note to your manual that the mask_file option (and other corresponding options) requires an 8-bit depth PGM file. While programs like GIMP default to 8-bit depth, other programs like ImageMagick default to higher values. When my PGM files were not working, I had to read the source code to discover that '255' is hardcoded into the PGM file parser.

**Comment by tosiara** [comment]
Yeah, make sense. It wouldn't hurt to put a note in the documentation

**Comment by tosiara** [comment]
PR: https://github.com/Motion-Project/motion/pull/1361
