### ISSUE TITLE
Deprecated ffmpeg functions

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#136]
Following warnings appear during compilation:
```
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DMOTION_V4L2_OLD -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"Unofficial-Git-2caced3\" -Dsysconfdir=\"/usr/local/etc\" -I/home/ubuntu/git/ffmpeg/out/include     -c -o netcam_rtsp.o netcam_rtsp.c
netcam_rtsp.c: In function ‘decode_packet’:
netcam_rtsp.c:148:5: warning: ‘avpicture_get_size’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4914) [-Wdeprecated-declarations]
netcam_rtsp.c:152:5: warning: ‘avpicture_layout’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4906) [-Wdeprecated-declarations]
netcam_rtsp.c: In function ‘netcam_read_rtsp_image’:
netcam_rtsp.c:316:13: warning: ‘av_free_packet’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4056) [-Wdeprecated-declarations]
netcam_rtsp.c:325:9: warning: ‘av_free_packet’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4056) [-Wdeprecated-declarations]
netcam_rtsp.c:333:5: warning: ‘av_free_packet’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4056) [-Wdeprecated-declarations]
netcam_rtsp.c: In function ‘netcam_rtsp_open_sws’:
netcam_rtsp.c:578:5: warning: ‘avpicture_get_size’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4914) [-Wdeprecated-declarations]
netcam_rtsp.c: In function ‘netcam_rtsp_resize’:
netcam_rtsp.c:614:5: warning: ‘avpicture_fill’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4899) [-Wdeprecated-declarations]
netcam_rtsp.c:632:5: warning: ‘avpicture_fill’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4899) [-Wdeprecated-declarations]
netcam_rtsp.c:664:5: warning: ‘avpicture_layout’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4906) [-Wdeprecated-declarations]
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DMOTION_V4L2_OLD -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"Unofficial-Git-2caced3\" -Dsysconfdir=\"/usr/local/etc\" -I/home/ubuntu/git/ffmpeg/out/include     -c -o ffmpeg.o ffmpeg.c
ffmpeg.c: In function ‘ffmpeg_put_frame’:
ffmpeg.c:571:13: warning: ‘av_free_packet’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4056) [-Wdeprecated-declarations]
ffmpeg.c:588:5: warning: ‘av_free_packet’ is deprecated (declared at /home/ubuntu/git/ffmpeg/out/include/libavcodec/avcodec.h:4056) [-Wdeprecated-declarations]
ffmpeg.c: In function ‘ffmpeg_open’:
ffmpeg.c:397:30: warning: ignoring return value of ‘avformat_write_header’, declared with attribute warn_unused_result [-Wunused-result]
```

**Comment by Mr-Dave** [comment]
Is this the 3.1 release version of ffmpeg?

**Comment by tosiara** [comment]
This is latest trunk https://github.com/FFmpeg/FFmpeg/

**Comment by Mr-Dave** [comment]
OK, I recall having issues with their master the last time I compiled it.  I'd like to only build/patch towards their latest official release to have some stability in our code.   As ffmpeg continues to evolve, we can see what may be coming in their master but not try to match them commit for commit with what they are doing.

**Comment by tosiara** [comment]
Same warnings for release 3.1

**Comment by Mr-DaveDev** [comment]
FYI:  I am currently working this one along with the other issues with the ffmpeg.  #132, #113 , #112

**Comment by Mr-DaveDev** [comment]
There is a new branch on the MrDaveDev https://github.com/Mr-DaveDev/motion/tree/ffmpeg-fixes which includes proposed fixes/changes for ffmpeg.  

@tosiara The messages above look like those for 3.0.  Can you validate the ffmpeg library version numbers and also check that this is what Motion is using?  Note the last commit in my branch.  Motion will now report ffmpeg library version numbers instead of build numbers.  From what I was able to see in ffmpeg version 3.1, it does not appear that we will be able to support it for quite a while.  Any user needing to build ffmpeg from sources should be directed to use a 2.8 release while this gets sorted out.

**Comment by jogu** [comment]
There are a couple of potential issues I noted with the ffmpeg support, though I'm not sure this ticket is the right place to mention all of them:

1) ffmpeg log level is hardcoded; would be nice to make this a config file option [see     av_log_set_level(AV_LOG_ERROR); in ffmpeg_init, ffmpeg.c]

2) ffmpeg log messages are all reported at INF level (your commit changes it to DBG); would be nice if ffmpeg *errors* were reported at ERR level etc I think [see ffmpeg_avcodec_log, ffmpeg.c]

3) when I enabled debug logging, I get this message:

[1] [INF] [ENC] [Aug 21 20:56:24] ffmpeg_avcodec_log: Using network protocols without global network initialization. Please use avformat_network_init(), this will become mandatory later.

I guess we may want to call avformat_network_init()? [I have ffmpeg 2.6.9 I think, the one in debian stable, though I'm not 100% sure. the motion.log init entry says: ffmpeg_init: ffmpeg LIBAVCODEC_BUILD 3676772 LIBAVFORMAT_BUILD 3676517.]

**Comment by tosiara** [comment]
@Mr-DaveDev , I have checked - 3.0 now silently compiles. 3.1 - still warns

**Comment by Mr-DaveDev** [comment]
@jogu Please see my latest commit for better handling of the messages.  If there are a lot of other issues you observe in the ffmpeg module not related to 3.1, I'd like to open a new issue with a title like _ffmpeg Multiple Problems._  

@tosiara I have created a different issue #144 for the 3.1 warnings _and not compiling_.
