### ISSUE TITLE
Support -hwaccel vaapi for netcam_decoder

### ISSUE THREAD

**Issue by abishekmuthian** [Motion-Project/motion#1371]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86, IvyBridge
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 20.04

netcam_decoder currently expects a ffmpeg decoder like **h264_vaapi**, but it will not work as h264_vaapi is an encoder and the correct way to use the hardware accelerated decoder for a vaapi device [according to FFMPEG is](https://trac.ffmpeg.org/wiki/Hardware/VAAPI),

`-hwaccel vaapi -hwaccel_device /dev/dri/renderD128`

So netcam_decoder should support a string like,

`netcam_decoder -hwaccel vaapi -hwaccel_device /dev/dri/renderD128`

But currently it just seems to be only supporting and therefore hw acclerated decoding is not possible for <gen8+ intel

`netcam_decoder codec`

**Comment by Mr-DaveDev** [comment]
Please upgrade to the current master branch.  The parameter now takes the value of `vaapi` which invokes the hardware accelerated decoding.

**Comment by abishekmuthian** [comment]
Oh thanks I will, So just  to confirm `netcam_decoder vaapi` is all that's required for decoding rtsp with hw acceleration using vaapi driver?

I there an updated documentation which I have missed?

**Comment by abishekmuthian** [comment]
With `netcam_decoder vaapi` I get,

`netcam_rtsp_decoder_error: Normal resolution: avcodec_find_decoder_by_name: Failed,Interrupt False`

Does this mean my camera does not support hw accelerated decoder? I can confirm that ffmpeg/vaapi is working for encoding the videos using movie_extpipe.
