### ISSUE TITLE
Core dump with git master

### ISSUE THREAD

**Issue by gene-git** [Motion-Project/motion#1394]
Have not had time yet to debug - commit  615a3b690b8e5ed4035071 works fine but commit bd4aae0d4ca5c2ccf9bf core dumps fairly quiclkly on startup. 

It logs : `config_camera: Processing camera xxx`
for camera 1 and then camera 2 and then crashes apparently on the 3rd camera config

Running on linux, 10 network cameras.

I'll try get more info later today if possible.

**Comment by Mr-DaveDev** [comment]
Arg...Thank you.....If you have any details on what parameters are different for camera 3 it would help.  Obviously my testing configuration parameters only had the options included in cameras 1/2.

**Comment by gene-git** [comment]
Other than the obvious differences (name, hostname, stream port) camera 3 has a mask file.
Could that be relevant?

**Comment by Mr-DaveDev** [comment]
That is it. Thanks for reporting.

**Comment by gene-git** [comment]
Na, thank **_you_** for all the "hard work" you do!

**Comment by Mr-DaveDev** [comment]
Does the new PR fix your issue?

**Comment by gene-git** [comment]
Sorry to be slow - I did a gitt pull on master and didn't see any changes - how do I pull your fix?

**Comment by gene-git** [comment]
Ah ok - I hadn't done a PR from github to my local repo before - interesting and now I know to do it :)
Rebuilt with your PR and tested - and all seems fine to me

Thank you!!
