### ISSUE TITLE
First picture saving deplyed issue

### ISSUE THREAD

**Issue by ericvan76** [Motion-Project/motion#1396]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version:  4.3.2-1 
2. installed as a package or compiled from sources [deb, rpm, git, other]: pi_buster_motion_4.3.2-1_armhf.deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: Pi4
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian 

Hi,

I have settings to save both picture and movie:
```
picture_output: first
movie_output: on
max_movie_time: 60
event_gap: 60
```

I also have `on_picture_save` script to hook with IFTTT, the reason I use `on_picture_save` instead of `on_event_start` is that I need the first picture in the rich notification.

The problem is the picture is not saved until the event or first movie clip ended, so there is a delay. I know the `best` might need more frames to calculate, but the `first` should be saved immediately.

Here is the log:
```
Aug 17 09:37:31 raspberrypi motion: [1:ml1:TapoCam-Liv] [NTC] [EVT] event_newfile: File of type 8 saved to: /var/lib/motion/2021-08-17/CAM1-20210817-093731.mp4
Aug 17 09:37:31 raspberrypi motion: [1:ml1:TapoCam-Liv] [NTC] [ALL] motion_detected: Motion detected - starting event 2
Aug 17 09:38:34 raspberrypi motion: [1:ml1:TapoCam-Liv] [NTC] [EVT] event_newfile: File of type 1 saved to: /var/lib/motion/2021-08-17/CAM1-20210817-093731-12.jpg
Aug 17 09:38:34 raspberrypi motion: [1:ml1:TapoCam-Liv] [NTC] [ALL] mlp_actions: End of event 2
``` 
Look at the event started at `09:37:31`, as well as the movie starts, but the jpg is saved about a minute later `09:38:34`, due to the event_gap or max_movie_time.

I also tried another solution: use `on_event_start`, and call the API `http://localhost:8080/{camid}/action/snapshot` to trigger a snapshot or use the current image `http://localhost:8081/{camid}/current`, but neither is high resolution.

Hope there is another solution, thanks.

Eric

**Comment by Mr-DaveDev** [comment]
I believe you can compile from source or add commit 62be47c4fe04871e41959c3ce4327591a697d7da to your version.

**Comment by ericvan76** [comment]
Oh thanks @Mr-DaveDev, will do, didn't realise that was reported previously.

**Comment by Mr-DaveDev** [comment]
If this resolves the issue, please close.
