### ISSUE TITLE
Add option to force continuous recording of highres stream

### ISSUE THREAD

**Issue by bkiziuk** [Motion-Project/motion#1399]
0. Reviewed guide and contributing documents? (Yes/No): **Yes**
1. version [x.y.z, hash, other]: **4.3.2**
2. installed as a package or compiled from sources [deb, rpm, git, other]: **deb package**
3. standalone or part of third party [motion, MotionEyeOS, other]: **part of motionEye**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **rtsp**
5. hardware [x86, ARM, other]: **x86**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: **Debian 11**

Hallo,
would it be possible to add an option to force continuous recording of netcam_highres stream even if no motion is detected at the moment?
The reason for this enhancement is that the low bitrate netcam stream is used for motion detection and live view, but there is often a need to review all the footage to find details that happened out of the motion detection triggered event.

**Comment by samtech09** [comment]
You need to turn `emulate_motion` on, then it will be in continuous recording mode.

**Comment by Mr-Dave** [comment]
This would be a user event.  Via the [Webcontrol](https://motion-project.github.io/motion_config.html#OptDetail_Webcontrol) by selecting camera, then Action, Start Event or by executing the following `{IP}:{port}/{camid}/action/eventstart`
