### ISSUE TITLE
Movie files appear black and soundless, but pictures are saved just fine

### ISSUE THREAD

**Issue by TechinicFiles** [Motion-Project/motion#1412]
0. Reviewed guide and contributing documents? (Yes):
1. version [x.y.z, hash, other]: 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: apt-get install
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone?
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: amd64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: ubuntu 20.04 lts

When a motion event occurs, motion takes the pictures and saves them just fine. I can see the data
However when i play the video it also saved in .mov format, the video player is blank and there is no sound. But the file size is 65mb? 

I've checked through the documentation on movie output and everything seems to be in order, why would it output a blank movie file? 

Configs: 

(changed to .txt because of github)

[camera1.conf.txt](https://github.com/Motion-Project/motion/files/7227724/camera1.conf.txt)
[motion.conf.txt](https://github.com/Motion-Project/motion/files/7227725/motion.conf.txt)

Any ideas on how i can get the files to "save" properly? Kinda need to video to monitor CCTV, can't be piecing together image files

**Comment by tosiara** [comment]
Could you provide one of the example movies together with a corresponding log file with `-d 9`?

**Comment by TechinicFiles** [comment]
> Could you provide one of the example movies together with a corresponding log file with `-d 9`?

Can you provide instructions on how to find/generate a logfile please? Also, by example movie, I'm guessing you want one of the recordings? 

Thanks

**Comment by tosiara** [comment]
To generate the detailed log you can either specify `log_file motion.log` and `log_level 9` in you config:
https://motion-project.github.io/motion_config.html#log_file
Or simply run motion as: `motion -c motion.conf -d 9 -n` and copy the output into a txt file

And yes, I need to look into a recorded movie file to verify that it is `blank` as you wrote

**Comment by TechinicFiles** [comment]
Okie dokie, I created a log file with a corresponding movie file. Fresh log after i restarted the service with the changes made to the config. 
[motion.log](https://github.com/Motion-Project/motion/files/7277237/motion.log)

Google Drive was needed for the mov file since its above 10mb
https://drive.google.com/file/d/1OQFv7Bb58dGUwXIXF3uJB1h0A6geWJn4/view?usp=sharing

**Comment by tosiara** [comment]
The video plays fine for me (I can see there is a dog recorded). Maybe there is an issue with your video player

Also note, that motion does not record audio

**Comment by TechinicFiles** [comment]
Thats weird. On my macbook quick time says its not supported. On my windows device, its a black screen that i can't scroll through. It only works on my windows or mac device after i use an online converter. Which brought me to the conclusion that the file was corrupted. 

Could it be a permissions issue?

**Comment by tosiara** [comment]
Try to change format to MKV or MP4:
https://motion-project.github.io/motion_config.html#movie_codec

**Comment by TechinicFiles** [comment]
Okay strange, MKV is working for me now. Originally it was set to mp4 which didn't work.
Thanks for the help
