### ISSUE TITLE
Allow use of by-id links for videodevice name

### ISSUE THREAD

**Issue by bertofurth** [Motion-Project/motion#1415]
Summary:
A simple patch to cater for specifying the unique "by-id" style device name assigned to a camera as the "videodevice" name. 

Details:
At the moment when a V4L "videodevice" is specified in the motion configuration it must be specified as the absolute device name, such as /dev/video0, /dev/video1 etc. 

This issue proposes to make it possible to specify the "videodevice" as a "by-id" style device such as /dev/v4l/by-id/usb-046d_0809_AFB7B98D-video-index0 . This device name is not subject to change at each system reboot or with the addition of new camera devices as it is linked to the unique ID of the camera device itself.

This "by-id" device name is simply a symbolic link to the real device name. For example

    # ls -l /dev/v4l/by-id/
    total 0
    lrwxrwxrwx 1 root root 12 Oct  1 21:37 usb-046d_0809_AFB7B98D-video-index0 -> ../../video0
    lrwxrwxrwx 1 root root 12 Oct  1 21:37 usb-046d_0809_AFB7B98D-video-index1 -> ../../video1`

At the moment, if one of these "by-id" style device names is specified as the "videodevice" in the motion configuration file, motion will not access the real device properly. Here is an example of the logs that are generated when a "by-id" style device name is used

[1:Unknown] [NTC] [VID] [Oct 01 21:37:01] vid_start: Opening V4L2 device
[1:Unknown] [NTC] [VID] [Oct 01 21:37:01] v4l2_device_open: Using videodevice /dev/v4l/by-id/usb-046d_0809_AFB7B98D-video-index0 and input -1
[1:Unknown] [ALR] [VID] [Oct 01 21:37:01] v4l2_device_open: Failed to open video device /dev/v4l/by-id/usb-046d_0809_AFB7B98D-video-index0: No such file or
 directory
[1:Unknown] [ERR] [VID] [Oct 01 21:37:01] vid_start: V4L2 device failed to open

The proposed patch simply checks to see if the specified "videodevice" is a symbolic link, or if it's specified as a non absolute path name. If it is then it resolves the link to the real device name and uses that as the video device from then on. The proposed log message in this case would be as follows.

[1:Unknown] [NTC] [VID] [Oct 03 19:51:31] init_camera_type: Absolute name for videodevice /dev/v4l/by-id/usb-046d_0809_AFB7B98D-video-index0 is /dev/video0

A workaround for this issue is to manipulate the udev rules as per the instructions in the motion configuration guide to ensure that a particular camera always gets the same /dev/videoX entry. That being said, using the "by-id" method is much simpler as it does not require any system reconfiguration. The "by-id" device link for a particular v4l camera *should* always be the same.

0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  4.3.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: source 4.3.2
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L USB
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Linux 5.14

Patch:

    --- src/motion.c.orig	2021-10-03 13:21:29.272001487 +1100
    +++ src/motion.c	2021-10-03 19:38:14.540441622 +1100
    @@ -736,6 +736,7 @@
     
     static int init_camera_type(struct context *cnt){
     
    +    const char *real_video_device;
         cnt->camera_type = CAMERA_TYPE_UNKNOWN;   
     
         #ifdef HAVE_MMAL
    @@ -758,6 +759,16 @@
             return 0;
         }
     
    +    if (cnt->conf.video_device) {
    +	real_video_device = realpath(cnt->conf.video_device, NULL);
    +	if (strcmp(cnt->conf.video_device, real_video_device) != 0) {
    +	    MOTION_LOG(NTC, TYPE_VIDEO, NO_ERRNO,
    +		       _("Absolute name for video_device %s is %s"),
    +		       cnt->conf.video_device, real_video_device);
    +	    free (cnt->conf.video_device);
    +	    cnt->conf.video_device = real_video_device;
    +	}
    +    }
         #ifdef HAVE_BKTR
             if (strncmp(cnt->conf.video_device,"/dev/bktr",9) == 0) {
                 cnt->camera_type = CAMERA_TYPE_BKTR;

**Comment by tosiara** [comment]
There should be no problems using V4L devices by the symlinks, I have been using it for years like that.

```
[0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 1 Camera Name: bird Device: /dev/v4l/by-id/usb-A4_TECH_A4_TECH_HD_PC_Camera_MI1320_SOC-video-index0
[0:motion] [NTC] [ALL] main: Waiting for threads to finish, pid: 30074
[1:ml1:bird] [NTC] [ALL] motion_init: Camera 1 started: motion detection Enabled
[1:ml1:bird] [NTC] [VID] vid_start: Opening V4L2 device
[1:ml1:bird] [NTC] [VID] v4l2_device_open: Using videodevice /dev/v4l/by-id/usb-A4_TECH_A4_TECH_HD_PC_Camera_MI1320_SOC-video-index0 and input -1
[1:ml1:bird] [NTC] [VID] v4l2_device_capability: - VIDEO_CAPTURE
[1:ml1:bird] [NTC] [VID] v4l2_device_capability: - STREAMING
[1:ml1:bird] [NTC] [VID] v4l2_input_select: Name = "Camera 1"- CAMERA
[1:ml1:bird] [NTC] [VID] v4l2_norm_select: Device does not support specifying PAL/NTSC norm
[1:ml1:bird] [NTC] [VID] v4l2_pixfmt_set: Testing palette YUYV (1280x960)
```
You'll need to check your setup once again

**Comment by bertofurth** [comment]
I could have *sworn* this wasn't working yesterday but now it's working. 

I really did see the error message I logged in the bug report.

I have no idea what was happening. Perhaps rebooting my system has fixed it.

I'm sorry to have wasted your time tosiara.

Berto.

On Mon, 4 Oct 2021, at 21:24, tosiara wrote:
> 
> 
> There should be no problems using V4L devices by the symlinks, I have been using it for years like that.
> 
> `[0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 1 Camera Name: bird Device: /dev/v4l/by-id/usb-A4_TECH_A4_TECH_HD_PC_Camera_MI1320_SOC-video-index0
> [0:motion] [NTC] [ALL] main: Waiting for threads to finish, pid: 30074
> [1:ml1:bird] [NTC] [ALL] motion_init: Camera 1 started: motion detection Enabled
> [1:ml1:bird] [NTC] [VID] vid_start: Opening V4L2 device
> [1:ml1:bird] [NTC] [VID] v4l2_device_open: Using videodevice /dev/v4l/by-id/usb-A4_TECH_A4_TECH_HD_PC_Camera_MI1320_SOC-video-index0 and input -1
> [1:ml1:bird] [NTC] [VID] v4l2_device_capability: - VIDEO_CAPTURE
> [1:ml1:bird] [NTC] [VID] v4l2_device_capability: - STREAMING
> [1:ml1:bird] [NTC] [VID] v4l2_input_select: Name = "Camera 1"- CAMERA
> [1:ml1:bird] [NTC] [VID] v4l2_norm_select: Device does not support specifying PAL/NTSC norm
> [1:ml1:bird] [NTC] [VID] v4l2_pixfmt_set: Testing palette YUYV (1280x960)
`

**Comment by tosiara** [comment]
No problem
