### ISSUE TITLE
Problem with single jpg image netcam after update from 4.3.2 -> 4.4.0 on Raspberry Pi3

### ISSUE THREAD

**Issue by int2018** [Motion-Project/motion#1424]
0. Reviewed guide and contributing documents? (Yes/No):Yes
1. version [x.y.z, hash, other]: 4.4.0
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: -
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Buster

Hallo motion project
please advise me to the right forum if the following issue is not related to what is going on here.

Recently I updated version 4.3.2 because I have an issue with a rtsp camera stream, the connection is not possible in motion but works fine in vlc. The update didn't solve the problem but I like the web gui so I stayed on that version.
I have a setup with 3 cameras, one USB and 2 netcams. 
From one net camera I only get a single jpg image per second, not a stream. The camera can steam rtsp but after a while the picture looks like some strange color art. I don't know how to fix this, it seems there is no key frame, so rtsp is useless from that camera. But the single image one per second works fine.

THEN I installed version 4.4.0, keeping my motion.conf and my camera.conf files.
I used this version: /release-4.3.2/pi_buster_motion_4.3.2-1_armhf.deb

But now I only get a gray image from that camera, the other cameras work fine.
What did change in this update?

To confirm everything is ok with my setup, I remove motion and go back to 4.3.2. 
And there I see the jpg image from that camera again, unchanged conf files.

Any suggestions?
Shall I share my conf files?

I will stay on 4,3,2 so there is no issue right now, but I just wanted to let you know that there may be a problem which shows up in the 4.4.0

Best regards

**Comment by Mr-Dave** [comment]
I strongly suspect that this is associated the revision listed as  "Change default processing for http cameras." .  The netcam_url section of the [guide](https://motion-project.github.io/motion_config.html#netcam_url) is slightly different if you read it carefully for version 4.4.  The default now uses FFMPEG to process the http cameras and for your situation, I'd guess you'd need to use the manual method that is now specified using the ```mjpg```  or ```mjpeg``` prefix.

**Comment by int2018** [comment]
Sorry I didn't reply sooner.

Unfortunately I have no success with protocols jpeg:// and mjpg://
Still only grey image.

The log says: 
netcam_rtsp_open_context: norm: Camera image size is invalid

The images size on the camera is set to 1280x720 but I also tried other resolutions.

**Comment by Mr-Dave** [comment]
It is ```mjpeg``` not ```jpeg```

**Comment by int2018** [comment]
The guide says:

mjpeg://
    This is an alternative prefix for http for use when Motion is compiled without ffmpeg.

mjpg://
    This option may process very old netcams with non standard mjpeg formats. 

jpeg://
    This option is for processing a static JPG file that is updated by processes external to Motion. It must be a local file and specified such as jpeg:///path/current.jpg 

Since I am not sure what "very old netcams" means, I tried mjpg://
How can I check if ffmpeg is included in my install?

**Comment by Mr-Dave** [comment]
It will work even if FFMPEG is installed.
