### ISSUE TITLE
How to get rid of the alerts about netcam_params after version 4.3.2 ?

### ISSUE THREAD

**Issue by JC38** [Motion-Project/motion#1433]
Hello,

I've updated my motion version to the latest 4.4.0 and I can see some red alerts about settings. Everything seems to work but I would like to supress these alerts.
Thanks for your help

```
-- Logs begin at Sun 2021-11-14 11:50:18 CET, end at Mon 2021-11-15 09:05:41 CET. --
nov. 14 11:50:19 motioneye systemd[1]: Started motionEye Server.
nov. 14 11:50:24 motioneye meyectl[448]:     INFO: hello! this is motionEye server 0.42.1
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motioneye/motion.conf
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] config_camera: Processing camera config file camera-1.conf
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [ALR] [ALL] conf_cmdparse: "netcam_keepalive" replaced with "netcam_params" after version 4.3.2
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [ALR] [ALL] conf_cmdparse: "netcam_tolerant_check" replaced with "netcam_params" after version 4.3.2
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] config_camera: Processing camera config file camera-2.conf
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [ALR] [ALL] conf_cmdparse: "netcam_keepalive" replaced with "netcam_params" after version 4.3.2
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [ALR] [ALL] conf_cmdparse: "netcam_tolerant_check" replaced with "netcam_params" after version 4.3.2
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] config_camera: Processing camera config file camera-3.conf
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [ALR] [ALL] conf_cmdparse: "netcam_keepalive" replaced with "netcam_params" after version 4.3.2
....
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] config_camera: Processing camera config file camera-12.conf
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [ALR] [ALL] conf_cmdparse: "netcam_keepalive" replaced with "netcam_params" after version 4.3.2
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [ALR] [ALL] conf_cmdparse: "netcam_tolerant_check" replaced with "netcam_params" after version 4.3.2
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] motion_startup: Logging to syslog
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] motion_startup: Motion 4.4.0 Started
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] motion_startup: Using default log type (ALL)
nov. 14 11:50:27 motioneye motion[576]: [0:motion] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
nov. 14 11:50:29 motioneye meyectl[448]:    ERROR: could not find motion camera id for camera with id 13
nov. 14 11:50:29 motioneye meyectl[448]:     INFO: cleanup started
nov. 14 11:50:29 motioneye meyectl[448]:     INFO: wsswitch started
nov. 14 11:50:29 motioneye meyectl[448]:     INFO: tasks started
nov. 14 11:50:29 motioneye meyectl[448]:     INFO: mjpg client garbage collector started
nov. 14 11:50:29 motioneye meyectl[448]:     INFO: server started
```

**Comment by tosiara** [comment]
Update your config to get rid of those warnings. Or if you are using motioneye to generate the config - ask motioneye maintainers to update the template

**Comment by JC38** [comment]
Oh sorry tosiara, I posted my issue into the bad Github project :-(
However, i opened a camera.conf file trying to see if I could manualy do something but I am missing some examples. Don't you have an "old" conf file with its new version that would help me to understand what to change and where with the correct syntax. I read some documentation but I didn't find some samples.
Meanwhile, I will open an issue into the motioneye Github project.

**Comment by Mr-Dave** [comment]
The quoted section below is included in the [guide](https://motion-project.github.io/motion_config.html#configfiles).  The process referenced must be completed outside of the Motioneye application but I would advise against going through the effort.  It would not surprise me at all if the Motioneye application reverts any changes you make since it rewrites configuration files.   


>Deprecated Parameters

> 
> Over the years, Motion has added many new configuration parameters and changed the name of a few of them so that there is some consistency to the parameter names. Since version 3.4.1, when a configuration parameter has a new name or additional functionality, Motion will try to interpret the value specified for the old parameter and translate it to the new parameter. These translations will be reported in the log as Motion is started. To eliminate these warnings, ensure that a webcontrol_port is specified and that the webcontrol_interface is specified as 0 (or not listed). Then start motion, open a browser and navigate to the webcontrol port. When on that page, select write configuration. This will re-write the configuration files with all the current parameters to Motion. Note that depending upon where the configuration files are located, Motion may need to be started using sudo.
> 
> Parameters in distributed configuration files
> 
> As of this writing, Motion includes over 150 parameters. With this volume of parameters, navigating the configuration file with every possible has become onerous. Starting with version 4.2, the distributed configuration files only include a limited subset of the configuration parameters. Users can add to the files as needed the parameters that are applicable to their set up. Users that wish to have every parameter listed and included in the configuration file can follow the process described immediately above in the Remove deprecated section. i.e. Use the webcontrol interface to write out the configuration file.
> 
> Extended descriptions / documentation are not included in the configuration file. This guide should be consulted for documentation of the configuration parameters. 
>
