### ISSUE TITLE
ffmpeg version 3.1

### ISSUE THREAD

**Issue by Mr-DaveDev** [Motion-Project/motion#144]
Motion currently does not support currently support ffmpeg version 3.1 [ffmpeg31.txt](https://github.com/Motion-Project/motion/files/431548/ffmpeg31.txt)  Use versions 3.0 and earlier until this issue is closed.

**Comment by tosiara** [comment]
But I'm able to compile motion against ffmpeg 3.1 built from sources. I only get those warnings during compile. Motion itself builds and runs fine:
```
[0] [NTC] [ENC] ffmpeg_init: ffmpeg libavcodec version 57.48.101 libavformat version 57.41.100
```

**Comment by tosiara** [comment]
I think your issue is that you have to explicitly add some libs into motion's Makefile. On different systems I sometimes get different libs that must be included. See my notes here: http://www.lavrsen.dk/foswiki/bin/view/Motion/FrequentlyAskedQuestions#Compile_ffmpeg_from_sources

According to your linking errors you probably have to add something like -lva and -lvpdau

**Comment by Mr-DaveDev** [comment]
This looks like a upstream problem with ffmpeg.  The purpose of pkg-config is to take care of this for us.  libavutil can now have additional library dependencies that are not reflected in the libavutil.pc.  The file that was built with the published instructions for building on Ubuntu and all options has <code> Libs: -L${libdir}  -lavutil -lm </code> and it needs to be something like <code> Libs: -L${libdir}  -lavutil -lm -lX11 -lvdpau -lva-drm -lva-x11 -lva </code> Since these lib requirements change depending upon how ffmpeg is built, we can not add them here.

**Comment by jogu** [comment]
FWIW I can use motion fine on debian jessie (ie. current stable) with ffmpeg 3.1.3 from debian backports.

There are some warnings both at build at runtime; see https://gist.github.com/jogu/1b3da7fda8ef2d79e897a9618efa02b2
