### ISSUE TITLE
"netcam_url http://" no longer recognizes JPEG

### ISSUE THREAD

**Issue by smurfix** [Motion-Project/motion#1443]
0. Reviewed guide and contributing documents? (Yes/No):Yes
1. version [x.y.z, hash, other]: 4.4.0
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: jpeg
5. hardware [x86, ARM, other]: arm64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Bullseye

motion 4.3 had no problem reading JPEG images from my camera via HTTP.

motion 4.4.0 tries to interpret the URL as an RTSP stream which "fails to open".

https://gist.github.com/smurfix/3c58838813cb231dfc24049796feab33

The syslog in the gist repeats every couple of seconds.

**Comment by tosiara** [comment]
`4.4` now uses ffmpeg to read `http` netcams. RTSP function names may be confusing, but it is not really RTSP.
You can try to change netcam to `mjpeg://` - this should switch to the old way.
Also, run motion with `-d 9` to see why ffmpeg lib is not able to open you camera. It should work fine

**Comment by tosiara** [comment]
Please show:
```
ffprobe http://10.107.1.229:80/oneshotimage1
```

**Comment by smurfix** [comment]
```
Input #0, jpeg_pipe, from 'http://10.107.1.229:80/oneshotimage1':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x1024 [SAR 96:96 DAR 5:4], 25 tbr, 25 tbn, 25 tbc
```

**Comment by tosiara** [comment]
And could you make a full log with `-d 9`?

**Comment by smurfix** [comment]
Sure.

https://gist.github.com/smurfix/0c4a50974dbe425eafe470a04ca65758

**Comment by tosiara** [comment]
Could you meanwhile try to change to `netcam_url mjpeg://10.107.1.229:80/oneshotimage1` and see if that makes any difference?

**Comment by smurfix** [comment]
Works.

**Comment by Mr-Dave** [comment]
Why is this labeled as a bug?

**Comment by tosiara** [comment]
What worked in 4.3 stopped working in 4.4. Isn't it a regression?
Also, ffmpeg detects the source stream, but motion is not able to open it: `av_read_frame: End of file`

**Comment by tosiara** [comment]
@smurfix can you tell more about your stream `http://10.107.1.229:80/oneshotimage1`? What software or hardware produces it? is it a static jpeg file hosted?

**Comment by Mr-Dave** [comment]
I see this as the http defaulting change to use ffmpeg revision.

**Comment by smurfix** [comment]
It's a rather old hardware camera. Ipela SNC-CH160. The `/oneshotimage1` endpoint spits out the current "hi-res" camera image.

**Comment by smurfix** [comment]
```
  HTTP/1.1 200 OK
  Date: Wed, 08 Dec 2021 14:46:49 GMT
  Expires: Wed, 08 Dec 2021 14:46:47 GMT
  Pragma: no-cache
  Cache-control: no-cache
  Content-Type: image/jpeg
  Content-Length: 187023
  Server: gen5th/1.35.00
```

**Comment by Mr-Dave** [comment]
Is it a "stream" or just a single image?  Can you open the stream in ```ffplay``` and see a continuous live image?

**Comment by smurfix** [comment]
It's a single image, otherwise there wouldn't be a `Content-Length:` header.
No. `ffplay` just shows a static image. Bah.
```
Input #0, jpeg_pipe, from 'http://10.107.1.229/oneshotimage1':0/0   
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x1024 [SAR 96:96 DAR 5:4], 25 tbr, 25 tbn, 25 tbc
[swscaler @ 0x7f3b5c0dd980] deprecated pixel format used, make sure you did set range correctly
    Last message repeated 3 times
   5.86 M-V:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
   ^-- this counts up
```
