### ISSUE TITLE
Add movie_min_time

### ISSUE THREAD

**Issue by Zurd** [Motion-Project/motion#1448]
We have movie_max_time as described here: https://motion-project.github.io/motion_config.html#movie_max_time

I think it would be great to have movie_min_time, I'd like to set it at 3 seconds. Any video below 3 seconds won't be recorded. My camera creates too many videos of 2 and 3 seconds where nothing interesting is happening.

Here's what I am using:
threshold 1500
noise_level 30
minimum_motion_frames 3
lightswitch_percent 12
lightswitch_frame 26

**Comment by tosiara** [comment]
This is something like a post-processing of recorded files (upload to cloud, compress, object detection etc) that is usually done by scripts like `on_event_end`

**Comment by genius3000** [comment]
You could try setting `minimum_motion_frames` to `fps * x` where x would be 2 or 3 seconds.

**Comment by Zurd** [comment]
Thanks for the comments. I will not close this feature request yet because nothing is working. It would be so much simpler with a new option **movie_min_time**

**on_event_end**: I'm probably doing something bad but this is not working :(
```
nano /test.sh
#!/bin/bash
FILESIZE=$(stat -c%s "$1")
if [[ "$FILESIZE" -le 999000000 ]]; then
  rm -f "$1"
fi
chmod +x /test.sh
on_event_end /test.sh "%f"
or
on_movie_end /test.sh "%f"
```

**minimum_motion_frames**: seems to make sense, so I'm at 12 framerate, so I put this at 36 but a LOT is not being recorded, that is really bad. And the documentation recommend to set this within 1-5 or below 10 (this should be rewritten lol).

My last option right now is to create a BASH script on my Raspberry Pi or my NAS that will run every minute and will check the new videos, if they are less than X KBs, then delete them. I'd prefer motion to handle this though than to rely on an external script.

**Comment by Zurd** [comment]
I haven't found a perfect solution. Most videos I want to delete are 4 seconds and less and below 1.1 MB but sometimes there is real motion detection with a video of only 3 seconds or at only 1 MB. I can delete videos with length time or file size but both of these solutions aren't perfect. That is mostly because motion doesn't work properly. Videos with real motion detected shouldn't last only 3 seconds and sometimes there's videos with no motion but it's being recorded for 10 seconds.

Deleting by video size is still the best solution for me.

To delete the videos less than 1024k, it's easy and fast:
`find "/your/videos/folder" -type f -size -1024k -delete`

And to delete videos based on video length (need ffmpeg), takes longer to run however:
```
folder='/your/videos/folder'
ls -1 "$folder" | while read file; do
  videoTime=`ffprobe -i "$file" -show_entries format=duration -v quiet -of csv="p=0" | cut -d"." -f1`
  echo $videoTime
  if [[ "$videoTime" -lt 5 ]]; then
    echo "Deleting "$file"";
    rm -f "$folder""$file";
  fi
done




```

**Comment by Mr-Dave** [comment]
Closing
