### ISSUE TITLE
Adding file size as a conversion specifier 

### ISSUE THREAD

**Issue by jjjpanda** [Motion-Project/motion#1449]
0. Reviewed guide and contributing documents? (Yes/No): **Yes**
1. version [x.y.z, hash, other]: **4.4.0**
2. installed as a package or compiled from sources [deb, rpm, git, other]: **deb**
3. standalone or part of third party [motion, MotionEyeOS, other]: **motion**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  **rtsp**
5. hardware [x86, ARM, other]: **x86**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: **20.04**

Hello, I have the following enhancement proposal: a dedicated conversion specifier that holds the file size in bytes for saved/generated pictures and movies. 
This can be used for 
- logging purposes 
- databasing purposes 
- precise auditing/tracking diskspace usage when running motion.

**Comment by tosiara** [comment]
Files size is not always knows until the event finishes, making such modifier useless as there is nothing where you can use it.

**Comment by jjjpanda** [comment]
Couldn't the file size be calculated (or atleast estimated) with the byte length of the buffer? For example, using image_size or dest_image_size from this one function [example from picture.c](https://github.com/Motion-Project/motion/blob/master/src/picture.c#L754)

**Comment by tosiara** [comment]
The final image or movie are being compressed and motion has no idea what the size is until the event is finished. And in case of ext_pipe movie there is no way for motion to know that, only to run an OS script that would query the file system. So, running script on event end would be the correct way to get file size and would cover all the cases.

**Comment by jjjpanda** [comment]
Ah I see the issue... I can run an OS script to get file size after the file is created on_event_end and on_picture_save. Those 2 events work as expected.
The original reason I asked for this enhancement is for databasing purposes, so for my Postgres database this is my workaround:
```
on_picture_save psql -c "COPY motion(file_size, file_name) FROM PROGRAM 'echo $(wc -c %f)' WITH DELIMITER ' ';"
```
Closing this issue because of the points you addressed.
