### ISSUE TITLE
Changing target_dir causes crash

### ISSUE THREAD

**Issue by DoctorAnon** [Motion-Project/motion#1451]
0. Yes
1. Latest
2. npm install
3. standalone
4. webcam
5. x86
6. Ubuntu 20.04 

When i change the default target_dir from `/var/log/motion` to `/media/server/2tb/motion` (a different drive) and then restart motion, everytime it then detects motion (and should save an image to the target dir) it instead just crashes and loses camera feed. I made sure the drive had permissions for owner, group, and other but I am not knowledgeable in this area and it's giving me a headache.

**Comment by tosiara** [comment]
Could you provide a log file with `-d 9` or a crash backtrace?
