### ISSUE TITLE
Plain .jpeg from http no longer working with 4.4

### ISSUE THREAD

**Issue by homepark1** [Motion-Project/motion#1454]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.4
2. installed as a package or compiled from sources [deb, rpm, git, other]: suseleap 15.3 rpm, but also compiled from source today
3. standalone or part of third party [motion, MotionEyeOS, other]: just motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: http:..jpg
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: opensuse leap 15.3

I updated my linux installation with an older version of motion running for years. A simple webserver provides a .jpg by http. 
Now I can see a .jpg being transfered to motion using wireshark, but there is no sign of motion getting this .jpg.
FFmpeg shows mjpeg to be available.
To my understanding using http:// will allow the usage of .jpgs without further decoding parameters, right ?
I compiled ffmpeg, mplayer and motion today with the latest relases. 

```
# The full URL of the network camera stream.
netcam_url http://137.239.30.251/usr/yoics0.jpg 
```

Here's the output of the endless restart-loop of motion trying to get the netcam:

[mm.txt](https://github.com/Motion-Project/motion/files/7793012/mm.txt)

**Comment by tosiara** [comment]
Try to change to `netcam_url mjpg://137.239.30.251/usr/yoics0.jpg`
Does that work?

**Comment by tosiara** [comment]
Adding reference:
https://github.com/Motion-Project/motion/issues/1443
https://github.com/Motion-Project/motion/issues/1424

**Comment by homepark1** [comment]
It works with mjpeg://myserver/picture.jpg.
So first of all: Thanks for your quick help.

I also read these references, but I was confused by the documentation:

Quote:
---
http://This prefix uses the traditional http format and opens a netcam that provides a motion jpg image.
mjpeg://This is an alternative prefix for http for use when Motion is compiled without ffmpeg.
---
As I have ffmpeg compiled into motion and I used http:// before in the same situation, I was not able to guess, that mjpeg might be an option.

**Comment by edlectron** [comment]
> Try to change to `netcam_url mjpeg://137.239.30.251/usr/yoics0.jpg` Does that work?

yesss, I was going crazy with this topic, and all was only change the mjpeg... I was confused by the documentation like [homepark1].

Thanks!!
