### ISSUE TITLE
Preferred codec not working

### ISSUE THREAD

**Issue by unix-world** [Motion-Project/motion#1460]
Motion version 4.4 with FFMpeg 4.4.1 under OpenBSD 7.0 or Debian Linux 11 (both: amd64).
Under OpenBSD I used the packages from ports.
Under Debian I compiled myself.
The bug can be reproduced on any OS from above using the motion 4.4 / ffmpeg 4.4.1.

Bug: The following movie_codec options are unusable: mkv:libx265, mkv:libtheora, mkv:libvpx, hevc.
If I use any of these in motion.conf motion will not record movies and errors are reported only in log_level 6 or above. The reported error comes from ffmpeg: Invalid parameter for codec ...

PS: I kept FFMpeg 4.4.1 and downgraded Motion to version 4.3.2 and works just ok with any of the above options. Only the Motion version 4.4 have this bug.

**Comment by Mr-Dave** [comment]
Confirmed. Thanks for reporting

**Comment by Mr-Dave** [comment]
Proposed [patch](https://gist.github.com/Mr-Dave/0f89cdcf10f3863301bbe19c0f3d0aea)

**Comment by unix-world** [comment]
Thanks. I will try this patch meanwhile.
