### ISSUE TITLE
Webcontrol page only shows 6 cameras

### ISSUE THREAD

**Issue by m2scared** [Motion-Project/motion#1465]
At the default webcontrol page only 6 cameras are being displayed.
The others are marked as pending. This happens on Chrome and Firefox.

0. Reviewed guide and contributing documents? (Yes/No): Yes.
1. version [x.y.z, hash, other]: Motion 4.4.0+git20211023-2645d67
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: no
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: ubuntu 18.04

See: https://gist.github.com/m2scared/78becf9f0066160e9da21a8bfa737eed

**Comment by Mr-Dave** [comment]
Yes.  That is the browser.  

The browsers have a limit on the number of concurrent connections.  Some browsers allow you to increase that limit while the other one does not have such a configuration parameter.

The other option is to change Motion to specify different port numbers for each camera.  The browser limit applies to each IP/Port Number combination separately.

**Comment by m2scared** [comment]
Hi @Mr-Dave,

Thanks. This solved my issue. Do you mind to add it to the documentation? I made a PR.

https://github.com/Motion-Project/motion/pull/1466
