### ISSUE TITLE
 ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by superidol5** [Motion-Project/motion#1539]
0. Reviewed guide and contributing documents? Yes:
1. version? latest: 
2. installed as a package or compiled from sources yes: 
3. standalone or part of third party motion]: 
4. video stream source V4L (USB): 
5. hardware ARM (rspberry pi): 
6. operating system volumio: 

im kind of a noob so i followed the wiki, and everything was working flawlessly until i got to the  `pip install motioneye` command, and it gave me that error:

![image](https://user-images.githubusercontent.com/106981553/172183359-1ad2107a-994b-4890-a42a-f75b38fc53c6.png)

**Comment by Mr-Dave** [comment]
This is posted to wrong location.  This is Motion, not MotionEye
