### ISSUE TITLE
Real time movie

### ISSUE THREAD

**Issue by Avessalom608** [Motion-Project/motion#1540]
How to open a movie in real time before it is fully recorded?
I don't want to wait for the full movie

Rassberrpy pi 3b+

motionEye Version | 0.42.1
Motion Version | 4.3.2
OS Version | Raspbian 11

![Снимок](https://user-images.githubusercontent.com/40124505/172988640-87f0ae75-a0ff-49b7-91f1-49d547cc4ace.PNG)

**Comment by Mr-Dave** [comment]
Wrong repo.
