### ISSUE TITLE
First captured picture after start up is zero length

### ISSUE THREAD

**Issue by pcwalden** [Motion-Project/motion#155]
I have 3 D-Link 930L netcams and using motion 3.4.1+git793080e running 3 camera threads. They all have fixed, non-DHCP, IP addresses. Events are recorded as picture files to a FATS thumbdrive (%Y/%m/%d/%H%M%S-%q). Each camera has its own target_dir.

The problem is that the very first picture captured or snapshot taken after motion start up produces a zero length jpeg file. Each camera thread has the same problem.

Example camera conf file below:

cam1_conf.txt

Here is the log during the start up:
Sep  8 06:10:01 walden1 motion: [0] [NTC] [ALL] conf_load: Processing thread 0 - config file /usr/local/etc/motion/motion.conf
Sep  8 06:10:01 walden1 motion: [0] [NTC] [ALL] config_thread: Processing config file /usr/local/etc/motion/motioncam1.conf
Sep  8 06:10:01 walden1 motion: [0] [NTC] [ALL] config_thread: Processing config file /usr/local/etc/motion/motioncam2.conf
Sep  8 06:10:01 walden1 motion: [0] [NTC] [ALL] config_thread: Processing config file /usr/local/etc/motion/motioncam3.conf
Sep  8 06:10:01 walden1 motion: [0] [NTC] [ALL] motion_startup: Motion 3.4.1+git793080e Started
Sep  8 06:10:01 walden1 motion: [0] [NTC] [ALL] motion_startup: Logging to syslog
Sep  8 06:10:01 walden1 motion: [0] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
Sep  8 06:10:02 walden1 motion: [2] [WRN] [NET] netcam_next: called with no data in buffer
Sep  8 06:10:02 walden1 motion: [1] [WRN] [NET] netcam_next: called with no data in buffer
Sep  8 06:10:02 walden1 motion: [3] [WRN] [NET] netcam_next: called with no data in buffer

**Comment by pcwalden** [comment]
I have another more detailed log with the errors citing the routines that are reporting the problem:

[1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
[1] [NTC] [ALL] create_path: creating directory /home/pwalden/webcam/cam1/2016/09/16
[1] [ERR] [ALL] **myfopen: Error opening file /home/pwalden/webcam/cam1/2016/09/16/113457-01.jpg with mode w: File exists**
[1] [ERR] [ALL] **put_picture: Can't write picture to file /home/pwalden/webcam/cam1/2016/09/16/113457-01.jpg: File exists**
[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /home/pwalden/webcam/cam1/2016/09/16/113458-00.jpg
[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /home/pwalden/webcam/cam1/2016/09/16/113458-01.jpg

**Comment by pcwalden** [comment]
**Another clue: "create_path: creating directory".** This only happens to the first picture file after a new directory is created. I store pictures in a per camera/year/month/day file tree. So the first picture of every day has this error, right after the new day's directory gets created.

**Comment by pcwalden** [comment]
There appears to be a missing second test of fopen results in motion.c myfopen() subroutine.
```
FILE * myfopen(const char *path, const char *mode)
{
    /* first, just try to open the file */
    FILE *dummy = fopen(path, mode);

    /* could not open file... */
    if (!dummy) {
        /* path did not exist? */
        if (errno == ENOENT) {

            /* create path for file... */
            if (create_path(path) == -1)
                return NULL;

            /* and retry opening the file */
            dummy = fopen(path, mode);
/*******  ^^^^^^^ dummy is never tested again after the directory is created.
 *      This block falls directly to the error logger, and leaves a zero length file
  *     created above by the fopen
*/
        }
        /*
         * Two possibilities
         * 1: there was an other error while trying to open the file for the
         * first time
         * 2: could still not open the file after the path was created
         */
        MOTION_LOG(ERR, TYPE_ALL, SHOW_ERRNO, "%s: Error opening file %s with mode %s",
                   path, mode);
        return NULL;
    }

    return dummy;
}
```

**Comment by pcwalden** [comment]
This patch seems to work:
```
diff --git a/motion.c b/motion.c
index 1bf0e26..6f99a05 100644
--- a/motion.c
+++ b/motion.c
@@ -3079,6 +3079,8 @@ FILE * myfopen(const char *path, const char *mode)
             /* and retry opening the file */
             dummy = fopen(path, mode);
         }
+    }
+    if (!dummy) {
         /*
          * Two possibilities
          * 1: there was an other error while trying to open the file for the

```

**Comment by jogu** [comment]
Thanks pcwalden - that looks like a good patch to me. I've tested it here and it seems to work, I'll get it committed.
