### ISSUE TITLE
Excessive messages for lost camera

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#159]
With the change to how avcodec errors are reported, the loss of a netcam connectivity now results in an excessive number of messages to the log.

**Comment by jogu** [comment]
Don't really know what is the best way to address this. Either we put the code back how it was (all ffmpeg logging at a fixed very low level) or perhaps we could log at a level one less than the level ffmpeg tells us - ie. log ffmpeg errors at our NTC level.

I possibly prefer the latter, as avcodec errors are important for the user to see in some cases (eg. if ffmpeg is completely failing to ever connect to the cameral we want the user to see the ffmpeg error that says why). It seems a tricky balance.

**Comment by Mr-Dave** [comment]
I was thinking that we would screen out any messages that had "no route to host".  I was also getting a few on one of my cameras that if they show up for others, we should add.  e.g.  A message that the camera was not conforming to the proper standard of rtsp and avcodec reports it at the error level.  There isn't any configuration option within ffmpeg to fix the fact the manufacturer took a shortcut.
