### ISSUE TITLE
Video file is corrupted

### ISSUE THREAD

**Issue by DiagnozHub** [Motion-Project/motion#1619]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.5.x

### What was the install method?

Installed via package tool

### What is base architecture?

ARM-64bit

### What is the distro being used?

Ubuntu

### Disto version number

focal

### Camera type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

I use option: Movie Passthrough, for write stream directly from camera. 

I found bug: when motion service is crashes (or hard reboot device), a video file is no readable. I think the problem, that some headers don't write into video file in this case.

### Relevant Motion log output (at log_level 8)

```shell
Error in my first message
```

**Comment by Mr-Dave** [comment]
So, if it is a hard boot in the middle of a movie and the movie is corrupted, that isn't a bug.  If you can point to a crash and log it, that is different.
