### ISSUE TITLE
Optimize CPU for ARM embedded system

### ISSUE THREAD

**Issue by leelx78** [Motion-Project/motion#1630]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.5.x

### What was the install method?

Built from source code

### What is base architecture?

ARM-32bit

### What is the distro being used?

Debian

### Disto version number

9

### Camera type(s) being used?

v4l2 USB camera

### Describe the issue/problem and steps to reproduce

Motion works well but unfortunately uses A LOT of processor at 1280x720 (project requirements), i.e. 100% and this is a problem on a small ARM embedded system. Also, CPU remains at 50-60% even when nobody is connected to the stream which is a waste. So my questions are:

1. How do I reduce CPU usage when nobody is connected? I can't afford wasting any CPU time

2. Is there any way to stream the MJPEG camera with minimal CPU overhead? I don't need any resizing, analysis, motion detection or any operation on the images so in principle if we could just take the image and send it that's all I need.

Thanks for the help!

### Relevant Motion log output (at log_level 8)

```shell
Not Applicable
```

**Comment by tosiara** [comment]
You can't reduce CPU usage when using MJPEG, it's gonna be bottleneck on ARM system.

But if you are using USB camera, you can switch pixel format to uncompressed and try custom build of motion with NEON optimizations: https://github.com/tosiara/motion - the usage of CPU will drop significantly.
However, uncompressed forma will use the whole bandwidth of USB, expected limited framerate
