### ISSUE TITLE
jpgs missing from source

### ISSUE THREAD

**Issue by skyglow** [Motion-Project/motion#164]
normal.jpg outputmotion1.jpg outputnormal1.jpg are missing from sources
error happens on make install

==============================================00

sudo make install
Installing files...
--------------------------------------------------------------------------------
mkdir -p /usr/local/bin
mkdir -p /usr/local/share/man/man1
mkdir -p /usr/local/etc/motion
mkdir -p /usr/local/share/doc/motion 
mkdir -p /usr/local/share/motion/examples
install -m 644 motion.1 /usr/local/share/man/man1
install -m 644 CHANGELOG COPYING CREDITS README motion_guide.html mask1.png normal.jpg outputmotion1.jpg outputnormal1.jpg /usr/local/share/doc/motion 
install: cannot stat 'normal.jpg': No such file or directory
install: cannot stat 'outputmotion1.jpg': No such file or directory
install: cannot stat 'outputnormal1.jpg': No such file or directory
Makefile:203: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by jogu** [comment]
Can you check this again in the latest source? I suspect you ran into the issue fixed by https://github.com/Motion-Project/motion/pull/160

**Comment by skyglow** [comment]
yes same issue, my bad
