### ISSUE TITLE
TEXT_SCALE breaks if enough newlines are added to TEXT_LEFT

### ISSUE THREAD

**Issue by stingwraith** [Motion-Project/motion#1660]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.0.x

### What was the install method?

Installed via package tool

### What is base architecture?

x86

### What is the distro being used?

Ubuntu

### Disto version number

20.04

### Camera type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

The TEXT_SCALE setting stops working properly once enough \n(newlines) are added to the string. 

The string is as follows:
"     Outside\n     %Y-%m-%d\n     %T-%q\n\n\n\n\n\n\n"
It should be about halfway up the page, but is only about 1/4 of the way up and is small. If you remove any of the newlines at the end, it goes back to the configured scale.

In these 3 screenshots the size of the text has changed, rather drastically, yet the only change was adding more \n to the string. 
 
![IMG_20230330_124153](https://user-images.githubusercontent.com/30402794/228906672-8c6b3e3a-8698-44e7-b049-a38b7b9bf6ba.jpg)
![IMG_20230330_124217](https://user-images.githubusercontent.com/30402794/228906706-79c88d77-9ff1-4ebc-b481-fd606c1b81af.jpg)
![IMG_20230330_124247](https://user-images.githubusercontent.com/30402794/228906735-a8f864f5-e21b-435f-ba6d-205538a23277.jpg)

As you can probably tell, I'm just trying to get rid of the incorrect time(can't be fixed due to camera firmware issue) at the top left by blocking it with the timestamp from Motion. This, or a crop feature that doesn't appear to exist seemed the most viable solutions. 

### Motion log output at log_level 8

```shell
N/A ATM.
```

**Comment by Mr-Dave** [comment]
If the log is reviewed I believe you'll note that the scale is adjusted due to excessive the length of the message.

**Comment by stingwraith** [comment]
The date and time plus one word is considered excessive? What was the intended use for this feature? I'm just trying to put the text at the top left.. This should be trivial. 

The config how-to says "By combining spaces and new lines '\n' you can place your text anywhere on the picture.". This seems a tad misleading if what you're saying is true. 

Is there any way to get around this and display the text wherever I'd like regardless of size? Maybe a CSS position needs changing?

Any help solving this is very much appreciated ☺️.

**Comment by Mr-Dave** [comment]
The whole length of the string counts for determination of excessive length.

Motion intentionally forces the text into the quadrant to avoid overlap between the various text options and the size of the image.  As a result, getting text into the top left with text scale isn't supported.

The documentation indicating "anywhere" is not correct.   
 
I expect that you'd need to adjust the code to meet your needs.
