### ISSUE TITLE
Cannot make Pi Camera support on Pi2 with Wheezy

### ISSUE THREAD

**Issue by pcwalden** [Motion-Project/motion#169]
I was trying to compile the latest with the new Pi Camera suport on my P12 with Wheezy. Specifically Debian 7.11 with a 4.1.19-v7+ kernel.

I am getting the "the make complaining /opt/vc/include/interface/vcos/vcos_types.h:38:33: fatal error: vcos_platform_types.h: No such file or directory" error that [Mr-Dave reported](https://github.com/Motion-Project/motion/pull/148).

I have installed _libraspberrypi-dev_ and done an apt-get dist-upgrade, make clean, autoreconf -fiv, and ./configure, but I still get the error. 

The _vcos_platform_types.h_ is in _/opt/vc/include/interface/vcos/pthreads_, but the make generating dependencies phase is not picking it up.

My configure output is below:
```
   **************************
      Configure status       
      motion 3.4.1+gitf219f81
   **************************

OS             :     Linux
pthread support:     Yes
jpeg support:        Yes
V4L support:         Yes
V4L2 support:        Yes
SDL support:         No
MMAL support:        Yes
 ... MMAL_CFLAGS: -std=gnu99 -DHAVE_MMAL -Irasppicam -I/opt/vc/include
 ... MMAL_OBJ: mmalcam.o raspicam/RaspiCamControl.o raspicam/RaspiCLI.o
 ... MMAL_LIBS: -L/opt/vc/lib  -lmmal_core -lmmal_util -lmmal_vc_client -lvcos -lvchostif -lvchiq_arm
FFmpeg support:      Yes
 ... FFMPEG_CFLAGS:  
 ... FFMPEG_LIBS: -lavutil -lavformat -lavcodec -lswscale  
SQLite3 support:     No
MYSQL support:       No
PostgreSQL support:  No

CFLAGS:  -g -O2 -D_REENTRANT -DMOTION_V4L2 -DMOTION_V4L2_OLD -DTYPE_32BIT="int" -DHAVE_BSWAP   
LIBS: -lm  -lpthread -ljpeg
LDFLAGS:  

Install prefix:       /usr/local
```

**Comment by tosiara** [comment]
Can you also post your Makefile and full output of configure?

**Comment by jogu** [comment]
We've not been testing with wheezy, only raspbian.

I'm guessing wheezy must have an older version of libraspberrypi-dev. It may be we need to add some extra -I lines to cater for the older version, but I don't know if this will be the only problem.

**Comment by pcwalden** [comment]
@jogu: it's the Raspbian wheezy. The latest is Raspbian jessie. They're both Raspbian, but yes the wheezy is the older, but still maintained version.

I got it to _make_ by adding 2 includes to the _configure.ac_'s MMAL_CFLAGS
`-I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux`

I have yet to test the executable.

I do have a Pi3 with jessie, so I will also try to build it there.

**Comment by pcwalden** [comment]
Looks like this issue is related to Raspbian wheezy. The Pi3 with jessie built straight away.

The main problem I had was that on jessie, the _ffmpeg_ package is now called _libav-tools_ and the _ffmpeg_ program is now called _avconv._ The configure script seemed to process these differences correctly and identified that ffmpeg was available.

**Comment by jogu** [comment]
Great, nice detective work @pcwalden!

If you can, please do submit a pull request with the configure.ac fix if the binary runs okay, it seems sensible for us to support the older OS too.

**Comment by Mr-Dave** [comment]
@pcwalden can you reference a link that contains the raspbian wheezy image?  From what I can see [here](https://www.raspberrypi.org/downloads/raspbian/) it isn't available anymore which makes testing a "challenge"

**Comment by jogu** [comment]
@pcwalden If your makefile tweak is all that is required, I think we're happy to support the older versions - have you been able to check if the version you have works okay with the camera?

**Comment by pcwalden** [comment]
> If your makefile tweak is all that is required, I think we're happy to support the older versions - have you been able to check if the version you have works okay with the camera?

Not yet. I will get to it later this week.

**Comment by pcwalden** [comment]
```
diff --git a/configure.ac b/configure.ac
index 0f18f08..a7a1c02 100644
--- a/configure.ac
+++ b/configure.ac
@@ -401,7 +401,7 @@ AS_IF([test "${HAVE_MMAL}" = "yes" ], [
            AC_SUBST(MMAL_OBJ)
            AC_SUBST(MMAL_LIBS)
            MMAL_OBJ="mmalcam.o raspicam/RaspiCamControl.o raspicam/RaspiCLI.o"
-           MMAL_CFLAGS="-std=gnu99 -DHAVE_MMAL -Irasppicam -I/opt/vc/include"
+           MMAL_CFLAGS="-std=gnu99 -DHAVE_MMAL -Irasppicam -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux"
            MMAL_LIBS="-L/opt/vc/lib  -lmmal_core -lmmal_util -lmmal_vc_client -lvcos -lvchostif -lvchiq_arm"
            AC_DEFINE([HAVE_MMAL], 1, [Define to 1 if we want MMAL])
 ])
```

The extra includes above compile and build on both wheezy and jessie. The jessie buid works as expected, but on wheezy the log does not display the thread [0] number properly. I get the following:

```
$ motion -n
[1995015048] [NTC] [ALL] conf_load: Processing thread 0 - config file /usr/local/etc/motion/motion.conf
[1995015048] [NTC] [ALL] config_thread: Processing config file /usr/local/etc/motion/motioncam1.conf
[1995015048] [NTC] [ALL] config_thread: Processing config file /usr/local/etc/motion/motioncam2.conf
[1995015048] [NTC] [ALL] config_thread: Processing config file /usr/local/etc/motion/motioncam3.conf
[1995015048] [NTC] [ALL] motion_startup: Motion 3.4.1+git709f626 Started
[1995015048] [NTC] [ALL] motion_startup: Logging to syslog
[1995015048] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
[1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (http://192.168.

```

Running it with the gdb debugger, I see that
`logger.c:186   threadnr = (unsigned long)pthread_getspecific(tls_key_threadnr);`
returns the number 1995015048

Something is amiss. Any ideas?

**Comment by pcwalden** [comment]
Reading the logger.c code and using a debugger, it looks like the assumption that pthread_getspecific() would return a NULL if a key is not initially pthread_setspecific()'ed is not working working.
```
    /*
     * If pthread_getspecific fails (e.g., because the thread's TLS doesn't
     * contain anything for thread number, it returns NULL which casts to zero,
     * which is nice because that's what we want in that case.
     */
    threadnr = (unsigned long)pthread_getspecific(tls_key_threadnr);

```
It does not return NULL on my wheezy machine. My jessie machine does return NULL.

Otherwise, except for the logging problems, I cannot see any other problems with thw wheezy build and the patched configure.ac.

**Comment by pcwalden** [comment]
If I instead hack up the generated Makefile to remove all MMAL support, the main thread log entries go back to reporting "0", instead of the "1995015048".

So there is something amiss in the wheezy include file dependencies and I am not sure I want to solve it. It would likely require a fix from the raspbian organization and I suspect they won't do it for wheezy.

I want motion on my wheezy Pi2, but I do not need the mmalcam support. The mmalcam is automatically configured if you have the libraspi-dev package installed, which covers a lot more than just the camera module.

It would be more convenient to have a -**-without-mmalcam** option for the configure script. I am not familiar with how to do that in the _configure.ac_ file.

**Comment by pcwalden** [comment]
I have figured out how to add a --without-mmal option to configure.

I will submit a pull request shortly.

**Comment by pcwalden** [comment]
Building at my end with the --without-mmal option
