### ISSUE TITLE
[configure] --with-jpeg-turbo makes pthread to disappear from Makefile

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#17]
Something happened to pthread detection

Configure output has ptherad:
pthread support:     Yes

But compilation fails:
motion.c:3197: undefined reference to `pthread_getspecific'

Adding -lpthread resolves issue

**Comment by ffontaine** [comment]
I can reproduce the issue with latest version of motion on buildroot.
I will send a pull request but basically:
```
    AC_CHECK_LIB(jpeg, jpeg_start_compress,
        [ TEMP_LIBS="$LIBS"
```
as to be replaced by:
```
    AC_CHECK_LIB(jpeg, jpeg_start_compress,
        [ TEMP_LIBS="$TEMP_LIBS -L${JPEG_TURBO}/lib -ljpeg"
```
otherwise pthread which was added to TEMP_LIBS will be lost.

**Comment by tosiara** [comment]
Thanks!
