### ISSUE TITLE
Translation files build problem in F39

### ISSUE THREAD

**Issue by Vascom** [Motion-Project/motion#1700]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.5.x

### What was the install method?

Built from source code

### What is base architecture?

x86

### What is the distro being used?

Other

### Disto version number

Fedora 39

### Camera type(s) being used?

Other

### Describe the issue/problem and steps to reproduce

Build failed at translation files with errors like this:
```
fi.po:3435: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 1, the character 'l' is not a valid conversion specifier.
/usr/bin/msgfmt: found 1 fatal error

de.po:3461: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 1, the character 'l' is not a valid conversion specifier.
/usr/bin/msgfmt: found 1 fatal error
```
How to fix it?

### Motion log output at log_level 8

```shell
No
```

**Comment by Mr-Dave** [comment]
Is this built from master?  I thought this was fixed with this [PR](https://github.com/Motion-Project/motion/commit/2d8d68cfcc1cf4fc8861671e185fdf235dcf9740) (which is not yet in an official release)

**Comment by Vascom** [comment]
It is built from 4.5.1 release.

**Comment by Mr-Dave** [comment]
Ok.  Closing as this fix is in the master branch.

**Comment by Vascom** [comment]
Thanks. I will try to patch 4.5.1.
May be it's time for new release?
