### ISSUE TITLE
README

### ISSUE THREAD

**Issue by mterzo** [Motion-Project/motion#172]
The README isn't getting any sort of markdown in github.  Any thoughts on moving to something like an RST or MD so we can use markup features in the readme?  Adding a link the travis-ci status would be a convient feature.

Also README.md will take precedence over README.  So just adding one of the markdown types.

There probably could be other documentation clean up as well.  Just wanted to start a conversation on this.

**Comment by tosiara** [comment]
Is it possible to easily maintain both plain text README and marked up README.md? So we are backwards compatible with traditional reading of readme file from console

**Comment by mterzo** [comment]
Could, just not sure if you want to maintain 2 files.

**Comment by tosiara** [comment]
No, I really don't want to manually maintain two files. If there is no automated way to do that - I'd vote to switch to README.md then

**Comment by jogu** [comment]
README.md gets my vote too. markup is easy enough to read on the console if you have to.

**Comment by Mr-Dave** [comment]
Yes, lets move this to a readme.md.

**Comment by Mr-Dave** [comment]
Closed via pull #216
