### ISSUE TITLE
Remove MMAL

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#1723]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.6.x

### What was the install method?

Built from source code

### What is base architecture?

ARM-32bit

### What is the distro being used?

Raspbian

### Disto version number

Bookworm

### Camera type(s) being used?

PI cam via MMAL

### Describe the issue/problem and steps to reproduce

Pi camera via MMAL is no longer functional due to elimination upstream.  Its continued inclusion in Motion confuses users into thinking it is / could be still functional.

This issue is to remove all the MMAL camera configuration options and associated code to keep Motion code current.

### Motion log output at log_level 8

```shell
n/a
```

**Comment by pingufreak** [comment]
https://github.com/motioneye-project/motioneye/issues/2812#issuecomment-1817391735

**Comment by Mr-Dave** [comment]
@pingufreak :  Please expand on your comment.  I've read the Motioneye issue linked but not understand the reason for your listing it here.

**Comment by pingufreak** [comment]
@Mr-Dave Updated

**Comment by Mr-Dave** [comment]
OK.  ....I'm still not following though.  In Motioneye, you can link to this issue to inform those users that that MMAL camera option will be removed.  It is not (and has not been) function for quite some time due to upstream changes.  If Motioneye wishes to still continue using MMAL and freeze at Bulleye, that is fine.   They will just also have to freeze the Motion version at 4.6 since that will be the last that includes it.  As mentioned in the guide and other Motion issues, libcamerify is the supported method of using the Pi camera in Motion going forward and not MMAL.
