### ISSUE TITLE
Web interface does not display video_params correctly

### ISSUE THREAD

**Issue by dwaxweiler** [Motion-Project/motion#1831]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.7.x

### What was the install method?

Installed via package tool

### What is base architecture?

ARM-64bit

### What is the distro being used?

Debian

### Disto version number

11

### Camera type(s) being used?

v4l2 USB camera

### Describe the issue/problem and steps to reproduce

The `video_params` value from the config file is not correctly displayed in Motion's web interface.

It displays only `Brightness=16,` while the configuration file says `Brightness=16,"Focus, Auto"=0,"Focus (absolute)"=350`

With the API call `/0/config/get?query=video_params`, I get the correct value.

### Motion log output at log_level 8

```shell
Dec 11 17:24:17 device motion[4753]: [0:cn0] [DBG] [STR] webu_parseurl: Sent url: /
Dec 11 17:24:17 device motion[4753]: [0:cn0] [DBG] [STR] webu_parseurl: Decoded url: /
Dec 11 17:24:17 device motion[4753]: [0:wu0] [INF] [ALL] webu_answer_ctrl: Connection from: 1.2.3.4
Dec 11 17:24:17 device motion[4753]: [0:cn0] [DBG] [STR] webu_parseurl: Sent url: /0/stream
Dec 11 17:24:17 device motion[4753]: [0:cn0] [DBG] [STR] webu_parseurl: Decoded url: /0/stream
Dec 11 17:24:17 device motion[4753]: [0:cn0] [DBG] [STR] webu_parseurl: camid: >0< cmd1: >stream< cmd2: >< parm1:>< val1:>< parm2:>< val2:><
Dec 11 17:24:17 device motion[4753]: [0:st0] [INF] [ALL] webu_answer_strm: Connection from: 1.2.3.4
Dec 11 17:24:17 device motion[4753]: [0:cn0] [DBG] [STR] webu_parseurl: Sent url: /favicon.ico
Dec 11 17:24:17 device motion[4753]: [0:cn0] [DBG] [STR] webu_parseurl: Decoded url: /favicon.ico
Dec 11 17:24:17 device motion[4753]: [0:cn0] [DBG] [STR] webu_parseurl: camid: >favicon.ico< cmd1: >< cmd2: >< parm1:>< val1:>< parm2:>< val2:><
Dec 11 17:24:17 device motion[4753]: [0:wu0] [INF] [ALL] webu_answer_ctrl: Connection from: 1.2.3.4
Dec 11 17:24:17 device motion[4753]: [0:wu0] [INF] [STR] webu_html_main: Invalid action requested: >favicon.ico< >< ><
```

**Comment by Mr-Dave** [comment]
This will fall into the won't fix category.  Please see (and vote if you want) the [poll](https://github.com/Motion-Project/motion/discussions/1794).
