### ISSUE TITLE
What's up with the old pwc-ioctl.h files?

### ISSUE THREAD

**Issue by slokhorst** [Motion-Project/motion#190]
The following files don't seem to be used anywhere:
* pwc-ioctl.h-10.0.10
* pwc-ioctl.h-10.0.5
* pwc-ioctl.h-pwc8.0
* pwc-ioctl.h-pwc9.0.1

Are they there for a reason, or should we just remove them?

**Comment by Mr-Dave** [comment]
These go back to the initial import and my assumption is that they are variants to use depending upon your particular camera [here](https://github.com/Motion-Project/motion/blob/master/track.c#L15)  I do not know how relevant they are today and whether they are now part of some other official apt package.  There are also a few other excess files like these that need investigation for removal (ffmpeg maxosx, readme axis, etc).  If you know whether these header files are available elsewhere, then I think we can remove them.

**Comment by slokhorst** [comment]
The files seem very similar. The newer versions seem to mostly add stuff in a backward-compatible way.

Because the older files are used nowhere in the current code, I vote we remove them, and just leave the current `pwc-ioctl.h`.

By the way, I am currently trying a macOS build, hopefully I can update that readme soon.
The `README.axis_2100` seems super trivial and I think we should also just remove that.

**Comment by Mr-Dave** [comment]
Yes, those unused pwc files should go along with the axis readme.
