### ISSUE TITLE
Update README.MacOSX

### ISSUE THREAD

**Issue by slokhorst** [Motion-Project/motion#199]
This file is clearly highly outdated. `ffmpeg-0.4.8-macosx.patch` is probably also no longer needed.

I am currently attempting a macOS build, but I'm new to MacPorts. Any help would be appreciated.

**Comment by Mr-Dave** [comment]
The ffmpeg patch is another one that needs to go.  I have zero experience with Mac and in my tenure with the project have not heard from any Mac users or anyone even trying to implement on Mac.  From memory of reviewing the development chain of the application, it was Linux->BSD->Mac.  So rather than jump to the end of the Mac building, it may be worthwhile looking at BSD first.

**Comment by slokhorst** [comment]
I have BSD working, but macOS not yet, unfortunately. Currently failing on:
````
In file included from motion.c:13:
./video_freebsd.h:24:10: fatal error: 'dev/bktr/ioctl_meteor.h' file not found
#include <dev/bktr/ioctl_meteor.h>
````

This file seems to be available on BSD but not macOS. Searching the web, many people who tried compiling Motion on macOS ran into the same problem.

Might be helpful:
* https://sourceforge.net/p/motion/mailman/message/27724764/
* http://www.lavrsen.dk/foswiki/bin/view/Motion/ConfigureTweaks

**Comment by jogu** [comment]
Now that https://github.com/Motion-Project/motion/pull/239  is merged (as well as a couple of little other fixes), macOS should build if the cmake build system in https://github.com/Motion-Project/motion/pull/236 is patched into the tree before builds.

Instructions will need to be updated after cmake is merged in, but this worked for me:

First install homebrew from http://brew.sh

Then run:

```
brew install ffmpeg cmake pkg-config libjpeg
cmake .
make

```

**Comment by slokhorst** [comment]
Sounds good! I will try to finish the cmake stuff somewhere this week (I'm a bit busy at the moment).

By the way, maybe it's better to keep everything except for the basic Linux build guide in the wiki, instead of as files in the repository? That way it's easier to keep them up to date. We can then just add a link to the FreeBSD/macOS guides in the regular `README`.

**Comment by jogu** [comment]
cmake is now merged. I wrote a quick wiki page here:

https://github.com/Motion-Project/motion/wiki/cmake

I'll update the mac readme sometime.
