### ISSUE TITLE
add support for V4L2_PIX_FMT_Y12

### ISSUE THREAD

**Issue by dagmcr** [Motion-Project/motion#202]
Hi,
I'm trying to add support for V4L2_PIX_FMT_Y12 format but I don't know
how to do it well. I know my problem is "v4l2_next", when motion is
getting buffer information and converts data depending on format
selected. Anybody knows or could give me some support?

These are my modifications:

diff --git a/video2.c b/video2.c
index 798f8f8..ab62de8 100644
--- a/video2.c
+++ b/video2.c
@@ -136,6 +136,10 @@
 #define V4L2_PIX_FMT_SPCA508 v4l2_fourcc('S', '5', '0', '8') /* YUVY
per line  */
 #endif

+#ifndef V4L2_PIX_FMT_Y12
+#define V4L2_PIX_FMT_Y12     v4l2_fourcc('Y', '1', '2', ' ') /* 12
Greyscale     */
+#endif
+
 #define ZC301_V4L2_CID_DAC_MAGN       V4L2_CID_PRIVATE_BASE
 #define ZC301_V4L2_CID_GREEN_BALANCE  (V4L2_CID_PRIVATE_BASE+1)

@@ -481,7 +485,8 @@ static int v4l2_set_pix_format(struct context
*cnt, src_v4l2_t * vid_source,
         V4L2_PIX_FMT_UYVY,
         V4L2_PIX_FMT_YUYV,
         V4L2_PIX_FMT_YUV422P,
-        V4L2_PIX_FMT_YUV420 /* most efficient for motion */
+        V4L2_PIX_FMT_YUV420, /* most efficient for motion */
+        V4L2_PIX_FMT_Y12
     };

     int array_size = sizeof(supported_formats) / sizeof(supported_formats[0]);
@@ -1089,6 +1094,9 @@ int v4l2_next(struct context *cnt, struct
video_dev *viddev, unsigned char *map,
             bayer2rgb24(cnt->imgs.common_buffer, map, width, height);
             conv_rgb24toyuv420p(map, cnt->imgs.common_buffer, width, height);
             return 0;
+        case V4L2_PIX_FMT_Y12:
+            // ? ******************************
+            return 0;
         }
     }

and...

diff --git a/motion-dist.conf.in b/motion-dist.conf.in
index 55b7a16..0872abe 100644
--- a/motion-dist.conf.in
+++ b/motion-dist.conf.in
@@ -22,7 +22,7 @@ setup_mode off

 # Use a file to save logs messages, if not defined stderr and syslog
is used. (default: not defined)
-;logfile /tmp/motion.log
+logfile /root/.motion/motion.log

 # Level of log messages [1..9] (EMG, ALR, CRT, ERR, WRN, NTC, INF,
DBG, ALL). (default: 6 / NTC)
 log_level 6
@@ -36,10 +36,10 @@ log_type all

 # Videodevice to be used for capturing  (default /dev/video0)
 # for FreeBSD default is /dev/bktr0
-videodevice /dev/video0
+videodevice /dev/video2

 # v4l2_palette allows to choose preferable palette to be use by motion
-# to capture from those supported by your videodevice. (default: 17)
+# to capture from those supported by your videodevice. (default: 18)
 # E.g. if your videodevice supports both V4L2_PIX_FMT_SBGGR8 and
 # V4L2_PIX_FMT_MJPEG then motion will by default use V4L2_PIX_FMT_MJPEG.
 # Setting v4l2_palette to 2 forces motion to use V4L2_PIX_FMT_SBGGR8
@@ -64,8 +64,9 @@ videodevice /dev/video0
 # V4L2_PIX_FMT_YUYV    : 15 'YUYV'
 # V4L2_PIX_FMT_YUV422P : 16 '422P'
 # V4L2_PIX_FMT_YUV420  : 17 'YU12'
+# V4L2_PIX_FMT_Y12     : 18 'Y12'
 #
-v4l2_palette 17
+v4l2_palette 18

 # Tuner device to be used for capturing using tuner as source
(default /dev/tuner0)
 # This is ONLY used for FreeBSD. Leave it commented out for Linux
@@ -447,7 +448,7 @@ text_double off

 # Target base directory for pictures and films
 # Recommended to use absolute path. (Default: current working directory)
-#target_dir /tmp/motion
+target_dir /root/.motion

 # File path for snapshots (jpeg or ppm) relative to target_dir
 # Default: %v-%Y%m%d%H%M%S-snapshot

Thank you in advance
Daniel

**Comment by Mr-Dave** [comment]
Hi Daniel.  We are trying to get out a release now so we're pretty busy.  I have only had limited experience on the conversion of the picture formats.  My guess right now is that it is going to take some research to figure out how to transform that format into the YUV420 format that Motion uses.

**Comment by dagmcr** [comment]
Hi Mr Dave, thank you for your answer. Finally, I could add support for Y12 (and Y10) format getting the procedure from raw2rgbpnm project. I will try to upload
