### ISSUE TITLE
Please call the next release 3.4.2

### ISSUE THREAD

**Issue by infinity0** [Motion-Project/motion#204]
Hi, I mistakenly released 3.4.1~rc01 as 3.4.1 to Debian because the tag name was called "release-3.4.1". Sorry about that - however also please don't do such things in the future, it's highly confusing... It would also be good if you called the next release version as 3.4.2 and not 3.4.1 in case future people get confused.

**Comment by slokhorst** [comment]
I agree, the current version numbering is quite unclear. The version is clearly marked as "Pre-release" on GitHub, but it is still tagged "release-3.4.1". So just looking at the tag, it is not clear it is an unstable version.

Besides that, we should try to get out a "stable" version ASAP. There are an incredible amount of bugs fixed between 3.2.12 and the current version. It is a shame most people don't benefit from that yet.

**Comment by Mr-Dave** [comment]
I wasn't aware of the deadline.  I was trying to wrap up a new release in the next few weeks and call it 4.0 on a new branch.  Basically get out of this whole 3.x series and put it behind us.  There are years of history of how the 3.4 mess came about that I don't want to go into here.    I can revise the 3.4.1~rc01 to 3.4.1 without any other changes if it would help.  My preference would have been to just put out the 4.0 as the new version to Debian.

**Comment by Mr-Dave** [comment]
Closing.  Tracking new version via #135
