### ISSUE TITLE
netcam_ftp does not support IPv6

### ISSUE THREAD

**Issue by slokhorst** [Motion-Project/motion#210]
The netcam_ftp backend only supports IPv4 netcams.

To add IPv6 compatibility, `gethostbyname()` should be replaced with `getaddrinfo()`. For more hints look at `netcam.c`, which supports IPv6 since 5827d9f450fb17d552f55b0a1eba8384337cc350.

**Comment by slokhorst** [comment]
I would like to try this, but don't have a FTP webcam to test it. Does anyone know how to set up one? Or maybe there is some public one to we can use for testing?

**Comment by Mr-Dave** [comment]
In my years working with Motion, I don't think I've encountered anyone using this functionality.  As I understand the process, Motion will pick up a static image (JPG) from the FTP site and process it.  The general flow would be Webcam puts out a image to the site with a static name.  Motion then opens up the FTP site and grabs that image file and processes it.  Now to test/validate/fix this issue, all you'll need to do is set up any machine with a FTP site and have two images.  Start up Motion pointing it to the site, get it working to grab that static image.  Doing just that should resolve this issue.  If you want to go further, you could manually copy the second image over the one currently on the server and that should have Motion trigger a event.  (Assuming of course that the two images are different).

**Comment by slokhorst** [comment]
Thanks @Mr-Dave, that seems to work!

This is somewhat harder than I thought, as FTP over IPv6 requires the implementation of some additional commands as specified in [RFC 2428](https://tools.ietf.org/html/rfc2428). I'll give it a try..
