### ISSUE TITLE
Motion inbuilt web server not working with IPV4

### ISSUE THREAD

**Issue by parky36** [Motion-Project/motion#217]
I've just started to experiment with motion & Tiny Core Linux. I pulled the source and my first successful build kept giving me error messages when run about being unable to bind to port 8081. The function **http_bindsock()** in the file **stream.c** is focused on IPV6 - which is why it didn't work on my IPV4 system.  My quick  hack was to change the two occurrences of AF_INET6 to AF_INET but it does need to be properly fixed.
David

**Comment by slokhorst** [comment]
The current code should work with both IPv4 and IPv6 since `AF_INET6` is backwards compatible with `AF_INET`.  It works fine here over IPv4.

What error are you getting? Have you manually disabled IPv6 in your kernel?

**Comment by tosiara** [comment]
@parky36, can you paste here the exact `git diff` change you did?
Related pulls https://github.com/Motion-Project/motion/pull/197 and https://github.com/Motion-Project/motion/pull/209 for tracking

**Comment by parky36** [comment]
I grabbed the latest release of Tiny Core - v7.2 that's using Linux kernel 4.2.9.  The machine I'm using it on sits on an IPV4 network.  Having added development tools, some dependencies etc I did a "git clone" and built and installed motion (with most of the without-xxxx options currently set).  I plugged in a USB camera, copied motion-dist.conf to motion.conf and then ran motion.  The log file shows:
.....
```
[1] [NTC] [VID] vid_v4lx_start: Using V4L2
[1] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
[1] [NTC] [STR] http_bindsock: error binding on 127.0.0.1 port 8081
[1] [ERR] [ALL] motion_init: Problem enabling motion-stream server in port 8081: Bad file descriptor
[1] [NTC] [ALL] motion_loop: Thread exiting
[1] [NTC] [VID] vid_close: Closing video device /dev/video0
```
......
After poking around for a while I looked at the function:

```
int http_bindsock(int port, int local, int ipv6_localhost)
{
    int sd = socket(AF_INET6, SOCK_STREAM, 0);

    char *addr_str;
    struct sockaddr_in6 sin;
    bzero(&sin, sizeof(struct sockaddr_in6));
    sin.sin6_family = AF_INET6;
    sin.sin6_port = htons(port);
```

and as a (very) quick fix changed the two instances of **AF_INET6** to **AF_INET**.

After I recompiled the source the bind problem went away and I was able to see the web cam via a browser connected to port 8081.

I've used Tiny Core over the years for various projects without any problems.

**Comment by parky36** [comment]
Doing a quick check it looks like I have to load the extension **ipv6-4.2.9-tinycore.tcz** to get IPV6 support.  I don't have it loaded.
David

**Comment by slokhorst** [comment]
@parky36, thanks for the feedback. I guess the new code doesn't work for kernels without IPv6 support. I didn't know there are still distro's that disable it by default...

So, question: do we want to support kernels which have disabled IPv6 support? All mainstream distro's released since the early 2000s have IPv6 enabled by default (the Linux kernel has it enabled by default). But I guess we can add an option to disable IPv6. Let me know if you think it is worth it.

**Comment by tosiara** [comment]
@slokhorst, I have some openSUSE boxes with IPv6 disabled. I will check how motion works there. Would be great to have backwards compatibility for such systems

**Comment by slokhorst** [comment]
Ok, please test #218.

I don't know if the netcam module still works on IPv6-disabled systems. Would be nice if someone could test that.

**Comment by parky36** [comment]
I did actually manage to connect to an old netcam (Grand IP camera II) for which I have zero documentation - and it was only to the 'stills' interface.  At the moment I guess I'm also not helped by being a complete newbie to motion and its configuration.
A quick grep of the source code (*.c, *.h) shows http_bindsock() having the only reference to AF_INET6.  A quick Google shows that a way of testing for IPV6 support is to look for the presence of the directory /proc/net/if_inet6.  Possibly such a check at the start of the function to determine the correct parameters to use in the bind call maybe all that's necessary?  I hand over to those of you who know the code in depth.

**Comment by slokhorst** [comment]
We could do something like that, but that would only work on Linux. I think a better alternative is to first try the IPv6(+IPv4) approach and if that fails fall back to the IPv4 approach. I have added that to my pull request.

Did you already try out my changes? (`git fetch origin pull/218/head:218 && git checkout 218` and recompile it)
