### ISSUE TITLE
motion loopback support for V4L2

### ISSUE THREAD

**Issue by dpenkler** [Motion-Project/motion#219]
Has anyone got loopback working with only V4L2 ?
The code currently does not compile the initialisation of the _motion_video_pipe_ or _video_pipe_ devices unless:
`#if defined(HAVE_LINUX_VIDEODEV_H) && !defined(WITHOUT_V4L) && !defined(BSD)`

On Debian jessie I have only `HAVE_LINUX_VIDEODEV2_H` defined.
thanks,
-dave

**Comment by Mr-Dave** [comment]
I have not heard of anyone using this and can not confirm it is still functional

**Comment by Mr-Dave** [comment]
It appears that you have forked the project and implemented this in your own fork.  If it is functional, can you consider creating a pull request for the project?  If it is not, can you comment on what is still an issue so that we can consider those issues as it is upgraded to v4l2 in the project.

**Comment by slokhorst** [comment]
This is not that easy. The [vloopback](http://www.lavrsen.dk/svn/vloopback/trunk/) project by Jeroen Vreeken is V4L1-only, so you would need to rewrite that in it's entirety to work on V4L2. 

There is [umlaeute/v4l2loopback](https://github.com/umlaeute/v4l2loopback) which seems to be a V4L2 loopback project. We might be able to interface with that, but I think it would be quite some work. I personally don't use loopback at all, so I'm not really motivated to look into it.
