### ISSUE TITLE
Feature: "Smartly" Record frames throughout an entire "event", not just post_capture

### ISSUE THREAD

**Issue by legoadk** [Motion-Project/motion#222]
Right now, when an "event" begins, the frames that are recorded into a video fall into a few groups:

pre_capture
motion detected frames
post_capture

Given the following configuration:
framerate = 24 (fps)
pre_capture = 12 (frames)
post_capture = 100 (frames)
event_gap = 60 (seconds)

And the following timeline:

5s of motion; 25s of _no_ motion; 10s of motion; 120s of _no_ motion

The resulting video looks like this:

12 frames of pre_capture +
120 frames of motion +
100 frames of post_capture + 
_no new frames for 24.5s_ (dead space, stale frame) +
12 frames of pre_capture +
240 frames of motion +
100 frames of post_capture
(video end)

This is not ideal. If used in a security context, a lot can happen that may not trigger the motion detection during that 24.5s dead space: a burglar could be sifting through your car, for example (true story), so you might be able to see where even a few frames between the last post_capture and the next pre_capture throughout the context of an event might be useful.

Additionally, it seems as though the actual lack of frames during that 24.5s is handled differently by different codecs: in avi, the video simply skips ahead 24.5s -- it shortens the overall length of the video. In mp4/h265, the video actually remains "real-time", but no new frames are shown until 24.5s have passed. This may not be avoidable for technical reasons in each codec, but there is probably a better solution.

There is a "hackish" way to sort-of accomplish this already: set post_capture to the same number of frames that would (approximately) be taken by the event_gap. This, also, is not ideal: You extend the length of each and every video by that many frames; it's not "smart".

What I am proposing is a way to "smartly" capture frames between motion detections throughout the duration of an event. The framerate of these frames could be the same as the rest of the video, or, if deemed necessary, a configuration could be added to scale it back during this time (a la the http stream rate).

**_Consider the following:**_
After a motion trigger, the usual pre_capture, motion frames and post_capture frames are recorded. Additional frames are then buffered until the end of event_gap; if no new motion is recorded during this time, those frames are discarded and the video has ended. 
If another motion event _does_ occur before the end of event_gap, those intermediary frames are written in conjunction with the pre_capture of this next motion sequence, and the cycle begins again.

Yes, the between-motion buffer could be up to `event_gap * framerate` frames at any given time; at higher resolutions and framerates, it could be a very large amount of data. It's certainly a resource hog. It wouldn't be adviseable to use this with limited memory. However, if running on a modern PC, I don't envision this being too bad. 

There may be a way around this buffer, however; I'm not really sure. Perhaps these intermediary frames could be written straight into the video file, and if it turns out that there's no more motion before the end of event_gap, the frames are then _removed_ from the video. My technical knowledge of how this could be done is not strong enough to know if this is possible. Maybe a post-video-capture script could trim the video -- given the number of "useless" frames are passed to it by Motion -- that is, if this video-trimming function can't be built straight in.

Thoughts? Alternatives? Is this something worth looking at?

**Comment by tosiara** [comment]
Do you want to record static picture while there is no motion detected?

**Comment by jogu** [comment]
@tosiara I think this is referring to the case where the frames contain useful movement, but not sufficient movement to count as "motion", the desire is to record the actual captured frames.

@legoadk  I don't follow your maths of how 100 post capture frames at 24 fps takes up 0.5 seconds of the 25 seconds dead space.

Some quick calculations I did suggest that even at a modest 1024x768 (0.7MP), 60 seconds of 24fps raw video is over 2 gigabytes. I think that is too large an amount to keep in RAM even on a modern high spec PC. Even 0.5 gigabytes (that might perhaps be achieved with some compression) is a little much on an average (let's call "average" 8G of RAM) PC running multiple cameras.

I understand the issue. It sounds potentially interesting to solve. I don't know if/which codecs would allow the type of removal of frames from the video you mention.

**Comment by legoadk** [comment]
Yes, I think my math was a bit off on that one, sorry. 100 frames at 24 fps = 4.1s, unless post_capture is at a different frame rate (but I don't think it changes).

Yes, it is quite a lot of data. Maybe it would be simple enough to set post_capture to a number that is roughly what 60s would be (1440 for 24fps), and then just chop 1340 frames off the end of each recording with the "on_movie_end" script... does that event get fired for timelapses, as well?

**Comment by tosiara** [comment]
@jogu , if video stream contains "useful movements", but your motion does not record them - you need to tune your config.

**Comment by jogu** [comment]
@tosiara I think this is a situation where the config cannot be tuned. Maybe "useful movement" is not the right phrase. Maybe "frames that let you see what someone was doing whilst relatively stationary".

The suggestion is basically that if motion deems several sets of movement to be a single event, then the whole of the event should be recorded. Currently motion doesn't record for any bits in the middle that it deems not to be motion.

So, for example, motion might currently record that someone walks up to your window, and 40 seconds later has opened the window - as both are significant movements. It doesn't record how the person got the window open, as that was just some small hand movements that weren't significant to count as motion.

I don't believe you could tune motion to believe that the small hand movements were motion, without also generating a lot of false positives, e.g. from animals.

**Comment by legoadk** [comment]
Indeed; @jogu has understood the premise behind my suggestion well. Even with my threshold at 6000 pixels (after my neigbour's house was broken into two days ago), I filled a folder with 32GB of footage. I'd like to avoid that. Also, the MP4/H264 encoding must be misconfigured because I'm not seeing very good compression going on at all... I got better file sizes when I re-encoded AVI to H264 with a on_movie_end script... but that's a separate issue.

**Comment by tosiara** [comment]
So it is fine for you if a burglar can slowly open the window and it won't get triggered at all?

**Comment by jogu** [comment]
If you mean "am I okay that if the person takes longer than event_gap to open the window then that middle part doesn't get recorded", then yes, it is fine - that seems an acceptable compromise.

It seems to be a fine balance game between avoiding false triggers yet trying to record things that may be important.

If you have an idea for a better solution, we're listening :)

**Comment by Mr-Dave** [comment]
Would capturing every frame in movies for the entire duration of the event address the no motion issue?    Removing the non motion frames from the middle of the video at the end of the process wouldn't really be feasible.  On the size issue, please validate the vbr setting which establishes the quality (which has a direct correlation to the size).  Finally, can you indicate the version/date of the pull of code that you are using for these issues so we can validate that the issues are still present?

**Comment by Mr-Dave** [comment]
I do not see anyway that this can be accomplished.  Storing in memory is too large and performing a post processing cut isn't an option.  After all, he smiled and looked straight into camera right as he was going back out window in the last event.  Doing the hackish method described above with post capture frames is the official method for getting the activity after the event but not large enough to trigger another event.  

I will leave this open for another week for other feedback and I there isn't any suggested course of resolution, we'll close it.

**Comment by jasaw** [comment]
I'm interested in this feature request as well. I know this issue is now closed, but can we do something like this?
In the "event gap" after post capture state, instead of not recording or buffering anything at all, we buffer at 1 fps, same resolution.
Seems like a good compromise to being completely "blind" during the event gap period.
