### ISSUE TITLE
armhf builds

### ISSUE THREAD

**Issue by gtr33m** [Motion-Project/motion#223]
Could you please build armhf deb packages when building i386 and arm64.  Thanks.

**Comment by Mr-Dave** [comment]
Raspian armhf debs were created [here](https://github.com/Motion-Project/motion/releases).  What distribution are you looking for?

**Comment by gtr33m** [comment]
Thanks,

Missed them amongst the others and didn't see then in the middle.

Specifically I am using Armbian, which is Jessie based so should work fine.
I'll test it and confirm back to you.

Regards,

Mark

On 5 Oct 2016 4:38 PM, "Mr-Dave" <notifications@github.com> wrote:

Raspian armhf debs were created here
<https://github.com/Motion-Project/motion/releases>. What distribution are
you looking for?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Motion-Project/motion/issues/223#issuecomment-251586471>,
or mute the thread

**Comment by Mr-Dave** [comment]
Closed due to no follow up.  Arm deb packages included in previous builds.
