### ISSUE TITLE
Code organization. 

### ISSUE THREAD

**Issue by mterzo** [Motion-Project/motion#231]
In my fork I have moved code around. I created src, contrib, tests, man, etc. 

I did this so when I started adding unit tests I don't have a ton of additional source files in the root.

Would this be something your interested in?

**Comment by Mr-Dave** [comment]
I was thinking the same thing but was going to go about it a bit differently or in a more staged approach.  Very shortly I will be creating a new repo for the project just to contain all the packaging stuff.  Next would be to cull out even more of the useless files / redundant files that have accumulated over the years.  The final step would be determine how to organize the remaining.

**Comment by mterzo** [comment]
How would you separate the packaging.

**Comment by Mr-Dave** [comment]
I was just going to start with the debian directory.  The problem I recall when I built all the debs last time was that the dependencies changed over the distros/platforms.  Trying to keep track of all of these variations within the code base would seem to make it into a mess.  I've not thought through the files for RPMs or creating services.  I'm going to take a look at how bigger projects handle this since it would seem to be a common issue.

**Comment by mterzo** [comment]
Would be nice if there was a tool that you create some basic meta data and it translates that into an rpm, deb or an apk.

**Comment by Mr-Dave** [comment]
I have a script 90% done for debs that will copy, git needed repos, determine your version, fix the changelog and leave you with a nice deb for installing.  RPMs and apks will take some research since I've not done them before.  Is that what you are thinking of?

**Comment by mterzo** [comment]
Oh yeah.  I love that script. I used it to generate my dpkgs that I push into a private aptly repo. 

So my thoughts on the packaging was almost more of a product solition, that if I had time / desire to create a simple mark up and then generate something that would create packages for all targeted distros.  My comment was more of a thinking out loud. Only service something like that is package cloud. Though I think it's just a repository. I'm thinking a service similar to Travis CI. 

Back to the original discussion.  I've done the migration over a long time in my repo. I'll need to piece a bunch of commits together that inmade around organization. Once I do that I'll submitting so we have something concrete to talk about.

**Comment by Mr-Dave** [comment]
For reference, the deb package script is [here](https://github.com/Motion-Project/motion-packaging/blob/master/builddeb.sh)  It could probably be polished up some.

**Comment by Mr-Dave** [comment]
Closing this issue since a few of the modules have been revised since this issue was opened and I do not believe it is still a valid issue for tracking.
