### ISSUE TITLE
Motion 4 - TCP Connection failed error when using RTSP

### ISSUE THREAD

**Issue by lolouk44** [Motion-Project/motion#242]
Since version 4, I constantly get this error message:
`[1:nc1] [ERR] [ENC] ffmpeg_avcodec.log: TCP connection to 192.168.0.31:554 failed: Connection refused`

The Camera feed is on RTSP.
I had a quick check as the config option and saw "rtsp_uses_tcp" but doc states is highly recommended to leave it as default (on)
Stream appears to work ok.
any idea?

**Comment by jogu** [comment]
The main change that happened in version 4 is that motion now reports ffmpeg errors at the error log level; previously ffmpeg errors were reported at lower log level meaning you would not see them by default.

We'd need to see a full log with some timestamps to guess what is going on (you can upload it to gist than add the link here); the mostly likely explanation (given you say the stream appears okay) is something like the camera is rebooting, or the camera only supports a single rtsp stream and something is already using it.

**Comment by Mr-Dave** [comment]
I'm going to close this.  I think it may be better to ask the user list.  The change for Version 4 is that it is just reporting the additional message.
