### ISSUE TITLE
Frame timing is off in all videos saved by motion (as part of Motioneye project)

### ISSUE THREAD

**Issue by DoctorJazz** [Motion-Project/motion#246]
I had started [this topic](https://github.com/ccrisan/motioneye/issues/340) on [Motioneye](https://github.com/ccrisan/motioneye) project, but we quickly realized that problem is in motion, used by motioneye. Below is a description of the issue.

After installing Motioneye on raspberry pi 3 with raspbian jessie lite (following instruction from here) I noticed that videos were somewhat weird -- they played back at very high speed. Though videos contained all frames, which can be seen if played back frame by frame in QuickTime player, they all were crammed in a fraction of a second. So I spent some time looking into the pairing of motion and ffmpeg, but couldn't dig up any valuable information on it. One thread mentioned use of "low_cpu" option, but that feature's been depreciated already.

Suspecting that I might had screwed up some settings, I decided to make a clean experiment and install everything from scratch on another raspberry pi 3 board, on a new SD card, and very meticulously followed installation instructions. I kept all default settings, etc, but unfortunately got same result. 

I'm including one of the videos captured by the latter board with cleaner install and almost zero tweaking of default settings. 

[Camera1_22-41-55.mp4.zip](https://github.com/ccrisan/motioneye/files/560346/Camera1_22-41-55.mp4.zip)

**Comment by Mr-Dave** [comment]
Please provide via gist the Motion conf file used as well as the log at the INF log level.  A material amount of fixes were implemented in version 4.0 for this issue.

**Comment by Mr-Dave** [comment]
From the video you posted, it does not appear that you have specified a frame rate in the configuration file.  Please specify a frame rate and if the issue still exists, post the configuration file and log at the INF level and reopen the issue.
