### ISSUE TITLE
Documentation: Unclear how to enable/use MMAL camera

### ISSUE THREAD

**Issue by kadin2048** [Motion-Project/motion#247]
Although MMAL support was added (in #133), it's not necessarily clear or obvious what a user has to do in order to actually use this feature.  Even looking at the source code in the `/raspicam` directory, it's not clear to me what I have to include in the config file in order to switch from motion's normal or traditional operation to the MMAL API.

It would be nice if there was a hint somewhere, perhaps in the `README.txt` inside `/raspicam`?  (That's the first place I looked, at any rate.)

The _really nice_ solution would be if MMAL support were enabled via an explicit config option that was somewhat similar in syntax to the existing `videodevice` parameter, i.e. use `videodevice mmal` (or something like that) to let the user specify that they want to use a MMAL camera?  But as a stopgap, any sort of documentation that suggests or clarifies when MMAL is used (it seems to be when the `videodevice` line is commented out?) would be helpful.

**Comment by kadin2048** [comment]
I'm happy to update the `README.txt` and put in a PR for the change, if someone wants to clarify here what the underlying behavior is, in terms of motion.conf options.

**Comment by Mr-Dave** [comment]
I think the appropriate place for additional clarification would be within the [basic setup](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Basic_Setup) or within the section that describes the [Raspberry Pi Camera](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Options_Raspi_Cameras).  The part that could be missing is the enable via raspi-config although similar to how we describe the setup for RTSP cameras, we recommend here to validate with other applications first such as raspistill which has the documentation on enabling via raspi-config and how to connect the cable.  The defaults in the config for mmal work with just the removal of the comment.

**Comment by pcwalden** [comment]
I have the MMAL working on Raspbian with Jessie. The configure script detects that the mmal libraries are installed and will automatically build mmal camera support into motion. There is a configure option _--without-mmal_ to not build mmal support, which you may need if you are using the older Raspbian whezzy.

You can grep the motion-dist.conf for the mmal options:
```
; mmalcam_name vc.ril.camera
; mmalcam_control_params -hf
```

**Comment by Mr-Dave** [comment]
Please submit a pull request with any revisions that you think would be helpful to the Motion_Guide.html.
