### ISSUE TITLE
install motion - need help ?

### ISSUE THREAD

**Issue by an6059** [Motion-Project/motion#251]
I am running motioneye frontend on debian jessie  with Motion 3.4.1~rc01 

how do I upgrade to this latest 4.01 version ?

simple cli commands would be really helpful 

thank you for any help on this

**Comment by Mr-Dave** [comment]
It would be preferred to ask this on the mailing list.  It is basically download the deb file from the releases page and install it using your preferred installer.  I use gdebi.
