### ISSUE TITLE
Camarte lost after upgrade

### ISSUE THREAD

**Issue by duckietm** [Motion-Project/motion#256]
After upgrade to motioneyeos the camera is lost how do i fix this, this is a Raspb. camera module

in messages:
Oct 31 08:09:00 meye-ab11a962 user.warn motion-mrdave: [1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD

**Comment by tosiara** [comment]
You should first try to report this issue to the motioneyeos maintainer: https://github.com/ccrisan/motioneye
If you still suspect this is motion's issue - compile or install from package a 'vanilla' latest motion and try to run it. If you see the same error - post complete motion's log here

**Comment by Mr-Dave** [comment]
If this remains a problem, please reopen this issue.
