### ISSUE TITLE
[CMake] video_common.c:979:20: warning: variable ‘height’ set but not used

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#258]
Compiling latest trunk:
```
[ 87%] Building C object CMakeFiles/motion.dir/video_common.c.o
/home/odroid/git/motion2/video_common.c: In function ‘vid_next’:
/home/odroid/git/motion2/video_common.c:979:20: warning: variable ‘height’ set but not used [-Wunused-but-set-variable]
         int width, height;
                    ^
/home/odroid/git/motion2/video_common.c:979:13: warning: variable ‘width’ set but not used [-Wunused-but-set-variable]
         int width, height;
             ^
```

**Comment by tosiara** [comment]
Why is it complaining? The variables seem to be used down the code

**Comment by jogu** [comment]
That problem was mentioned somewhere else - it's because cmake isn't enabling one of the V4L2 defines currently.

**Comment by tosiara** [comment]
OK, then it needs to be fixed. How do I pass define to cmake?

**Comment by slokhorst** [comment]
I'm working on it.. We need to detect if V4L2 is available to set the `MOTION_V4L2` define.

In `configure.ac`, there is some check happening if `struct v4l2_buffer` exists.. But is this needed? Isn't it just enough to see if `<linux/videodev2.h>` exists?
Is there a possibility that that file *does* exists but V4L2 is unavailable? Or that the file *doesn't* exist but V4L2 *is* available?

**Comment by jogu** [comment]
The way the current configure is written suggests to me that there is a version of v4l2 where the `struct v4l2_buffer` is in `<linux/videodev.h>`. I have no idea if this is true or not, would have to study the history in the kernel git to check probably. Alternative would be to go for the simple check you suggest for now and revise it if someone reports a failure.

**Comment by slokhorst** [comment]
@jogu sounds good. `<linux/videodev2.h>` is at least available since Linux 2.6.12, when they switched over to Git (2005). So I can't easily trace it back further, but that is probably good enough.

**Comment by tosiara** [comment]
As I recall, V4L1 compatibility include was "libv4l1-videodev.h" rather than "linux/videodev.h". But do we care about V4L1?

**Comment by slokhorst** [comment]
I don't know.. According to [Wikipedia](https://en.wikipedia.org/wiki/Video4Linux), V4L1 was dropped in Linux 2.6.38 (14 March 2011). I don't have such old distro's laying around to test.

**Comment by tosiara** [comment]
Ok, then nevermind

**Comment by tosiara** [comment]
Verified, resolved
