### ISSUE TITLE
Support for Greyscale format images?

### ISSUE THREAD

**Issue by encryptededdy** [Motion-Project/motion#263]
I'm using a thermal imaging camera that outputs frames in the V4L2_PIX_FMT_GREY format. Is it possible to add support for this format in motion?

**Comment by Mr-DaveDev** [comment]
I quickly looked around and didn't see any readily available answers.  This [pull](https://github.com/Motion-Project/motion/pull/212/files) we just did demonstrates the changes that might be needed if you'd like to try yourself.  The difficulty for us is that we don't have a camera ourselves with this format so we'd only be guessing at whether it would be functional which makes for a really long development process.  The other option is to leave this issue open and when we get into that section of the code add our best thoughts on what might work but that could take a while.
