### ISSUE TITLE
segv in netcam_rtsp.c:893

### ISSUE THREAD

**Issue by przemekklosowski** [Motion-Project/motion#264]
When compiling this line ( netcam_rtsp.c:893 ) gets a GCC warning that the if() test is always TRUE because it compares two identical values. On execution, after failing to connect to a RTSP camera due to a problem with authentication, it SEGVs
```
Thread 2 "ml1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6da4700 (LWP 29631)]
netcam_setup_rtsp (netcam=netcam@entry=0x7ffff0000960, url=url@entry=0x7ffff6da2c50) at netcam_rtsp.c:893
893	    if (url->port == url->port) netcam->rtsp->status = RTSP_NOTCONNECTED;
```
because netcam->rtsp is NULL
I think the test was supposed to be just (url->port) or (url->port != NULL)

**Comment by Mr-DaveDev** [comment]
I observed some problems with those lines just yesterday.  The test is supposed to be just a compiler warning killer to remove the unused variable warning.  However when it is actually invoked it causes a segfault.  So the cure is worse than the original problem in this situation.  For the moment, you can just eliminate the line without any consequences.  

Regarding the cause, I do not believe this is authentication.  From what I recall, this section is the notification that you are asking for a RTSP camera but when Motion was compiled, FFMPEG was disabled.  FFMPEG is required for RTSP camera support.  Once ffmpeg is included in the configure, this section is disabled and then any authentication issues could come into play.
