### ISSUE TITLE
Is it possible to query whether a thread is currently detecting motion?

### ISSUE THREAD

**Issue by Whytey** [Motion-Project/motion#266]
Hi,

Is it possible (using the HTTP API or other) to detect whether a camera currently has 'motion' on it?  Or is the only way to run some script at the start and end of motion events?

Cheers,
Whytey

**Comment by tosiara** [comment]
No.
But I'm also interested in this feature. Last time I tried to do it for my
needs, this was the code part that I was editting:

/* Do things only if we have got minimum_motion_frames */
if (img->flags & IMAGE_TRIGGER)
 {/* Take action if this is a new event and we have a trigger image */
if (cnt->event_nr != cnt->prev_event)
 {/** Reset prev_event number to current event and save event time* in both
time_t and struct tm format.*/

**Comment by pcwalden** [comment]
How about something like this:
```
$ lwp-request http://localhost:8080/1/config/list | grep device
<li><a href=/1/config/set?videodevice>videodevice</a> = /dev/video0</li>
$ lwp-request http://localhost:8080/1/detection/status | grep status
<a href=/1/detection>&lt;&ndash; back</a><br><br><b>Thread 1</b> Detection status ACTIVE
```
You will need a better parser to get the device name and detection status. You'll also have to scan through all the configured threads.

**Comment by tosiara** [comment]
No, this will only give you the status (enabled/disabled). But not that
motion has been triggered (when you are inside event)

**Comment by pcwalden** [comment]
Sorry, I guess I did not detect the nuance that one wanted to know if a camera has 'motion' (an event) on it versus has 'motion' (the program) on it.

**Comment by Whytey** [comment]
Since this isn't doable at this point in time, I am happy to just close this issue.
