### ISSUE TITLE
Complete transition to v4l2

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#272]
v4l support was dropped from the kernel in 2011.  The project should eliminate the historic v4l support and upgrade all the components to v4l2.   The only "known" component at this time reliant upon v4l is the loopback functionality referenced in #219 .

**Comment by slokhorst** [comment]
If I understand correctly, this means dropping all code blocks guarded by `#ifdef(HAVE_LINUX_VIDEODEV_H)`.
There are also a few of these in `track.c` (two `lqos_` functions, seemingly related to the "Logitech QuickCam Orbit" camera). Is it possible (and wanted) to port them?

**Comment by Mr-Dave** [comment]
You are correct.  I would like to port the functions to maintain any functionality/code we have but I don't know of anyway to test them.

**Comment by slokhorst** [comment]
With #273, it compiles fine. Unfortunately, I don't have the webcams to test it, but I don't see why it wouldn't work.

**Comment by Mr-Dave** [comment]
I'm opening this issue back up due to issues uncovered with its implementation.  

1.  The flags need to be revised to use something like HAVE_V4L2 instead of WITHOUT_V4L2.
2.  The compiling on FreeBSD now fails.(track.c/track.h)
3.  The BKTR and PWCBSD are not being handled correctly.
4.  There are still components that are looking for v4l palette options or grey images structures.
5.  The call to loopback is passing a redundant pixel format.
6.  Many pixel format declares still refer to v4l names instead of v4l2 names.
