### ISSUE TITLE
Can't compile under FreeBSD 

### ISSUE THREAD

**Issue by dtsname** [Motion-Project/motion#274]
Cannot build on FreeBSD 10.2:

root@stor02:/tmp/motion-release-4.0 # autoconf
root@stor02:/tmp/motion-release-4.0 # ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking for Darwin... no
checking for *BSD... yes
checking Linuxthreads... skipping
Build with PWCBSD support no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking bktr headers in /usr/include/dev/bktr... yes
checking threads... yes
checking for pthread_setname_np... no
checking for sdl... skipped
checking for libjpeg-turbo... skipping
checking for libjpeg-mmx... skipping
checking for jpeg_set_defaults in -ljpeg... yes
checking for pkg-config... yes
./configure: 5196: Syntax error: word unexpected (expecting ")")
root@stor02:/tmp/motion-release-4.0 #

Could someone give an advice?

**Comment by slokhorst** [comment]
Is this with the 4.0 tarball? Can you try with the latest ([4.0.1](https://github.com/Motion-Project/motion/archive/release-4.0.1.tar.gz))?

**Comment by dtsname** [comment]
Thanks, slokhorst. 
autoreconf solved this issue.
