### ISSUE TITLE
Continuous Recording with Motion Detection Notification

### ISSUE THREAD

**Issue by kutysam** [Motion-Project/motion#278]
Hi all,

I've been using motioneyeos with the latest motion.
Raspberry pi 2 with picamera

I have enabled 
Recording Mode: Continuous
Maximum Movie Length: X seconds

Continuous recording works perfectly!

When I enable motion detection, and notifications (webhook),
it will constantly send a notification every X seconds whether there is motion or not.

Is there any way to fix this? Thank you!

**Comment by tosiara** [comment]
I believe, this is something that is related to the motioneyeos, not to motion itself.

**Comment by ccrisan** [comment]
Yeap, this is definitely motionEye-related. I'll post the answer here anyway.

It's simple: *continuous recording* uses the *emulate motion* option to trick motion into thinking that it has motion detected all of the time. And with a max movie length of 60, motion will start a new event (and therefore a new movie) each 60 seconds, which in turn will trigger all the corresponding events.

**Comment by kutysam** [comment]
Thank you for both of your replies! Now i understand it better.

Just a suggestion @ccrisan 
Perhaps there could be an option to 
continuously record video without using motion and another thread for motion to just detect motion and send notifications.

**Comment by Mr-Dave** [comment]
Closed per request
