### ISSUE TITLE
Webcam Pixel format changes

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#279]
Evaluate reworking and incorporating the following [patch](http://www.lavrsen.dk/foswiki/bin/view/Motion/Libv4lConvert) which uses the libv4lconvert in order to handle the pixel conversion for webcams.  

1.  Determine if this library is still supported.  
2.  Determine supported distributions.  
- Linux
- BSD (all flavors)
- MacOS(if MacOS supports any webcams)

3.  If present and supported consider including as required library whenever V4L2 is enabled.

**Comment by tosiara** [comment]
Sounds good. Maybe this will also resolve H.264 feature request: https://github.com/Motion-Project/motion/issues/86
Checked my ARM and x64 installation - all seem to contain libv4lconvert.so files

**Comment by Mr-Dave** [comment]
Just so no one does work on this.   The use of the ffmpeg libraries are also being investigated to determine whether they can support this.
