### ISSUE TITLE
Netcam segfault with 1920x1080 resolution

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#28]
When using a netcam with 1920 x 1080 resolution, motion will usually crash with a segfault when the stream is opened in a browser.

**Comment by tosiara** [comment]
Would that be a solution? https://github.com/dren-dk/motion/commit/be4386e99b12582a4e044051f279dc8ca5e0e2ff

**Comment by dren-dk** [comment]
I've been testing motion with my jpeg write fix for a while now and it seems ok, so I'd expect it to work for others too.

**Comment by tosiara** [comment]
@dren-dk what 1080p source are you using? RTSP? MJPEG? or V4L?

**Comment by dren-dk** [comment]
I'm streaming h264 over RTSP from an onvif camera using ffmpeg.

The specific camera models are linked via the ebay links here (ignore the shittycam):
http://osaa.dk/wiki/index.php/ProjectDontBeADick#IP_camera

This projects readme has some more information about how and why I build motion:
https://github.com/dren-dk/DontBeADick

**Comment by tosiara** [comment]
I have adopted the patch to @Mr-Dave tree: https://github.com/tosiara/motion/commit/ef15c902f514703454c1d2d36699fbc1275646dc and tested with MJPEG netcam 1080p stream - no longer segfaults and seems to work fine
