### ISSUE TITLE
Corrupt saved recordings

### ISSUE THREAD

**Issue by ericjanvanputten** [Motion-Project/motion#281]
based on this issue https://github.com/ccrisan/motioneye/issues/403 I got recommended to post an issue here. 

I have a pi 3 with motioneyeOS 20161125 with motion 4 with 3 rtsp camera's on it running 1280x720p resolution. I encounter some files that are corrupt. however at somemoment it was only creating corrupt files, by reducing the amount of active cameras it seemed to have resolved mostly. but not completely. i'm now slowely adding the cameras again. 2 seems okay, havent tried 3 yet.

I'm unfamiliar with setting the debug mode so please tell me how and i will supply logs.

**Comment by tosiara** [comment]
Is it possible to reproduce the issue using plain motion, without any thirdparty middleware?

**Comment by ericjanvanputten** [comment]
Happy to try certain things, but not sure what you mean?

**Comment by tosiara** [comment]
You need to execute motion binary like `./motion -c motion.conf -d 5 -n`
Where motion.conf is your motion config file, -d 5 means logging level, -n means to run in foreground
Not sure where is your motion.conf is located, should be somewhere in motioneye installation

**Comment by ccrisan** [comment]
@ericjanvanputten, in motionEyeOS, you're supposed to:
1. log in remotely (via SSH/putty) or use a monitor+keyboard 
2. stop motionEye:

        /etc/init.d/S85motioneye stop

3. run motion manually, as @tosiara said:

        cd /data/etc
        motion -c motion.conf -d 5 -n

**Comment by tosiara** [comment]
Is there any update on this issue?

**Comment by ericjanvanputten** [comment]
I suspect its related to the Pi 3 being overwhelmed. It still most most of the time do fine but some files are corrupted (1 in 20-50 or something).

I think I will this one rest untill I OR get the orange pi zero's in place, or i cant wait and hookup a second Pi3 to take half the load :)

**Comment by tosiara** [comment]
Lets close this issue for now. You can reopen if you experience the same problem with the new setup
