### ISSUE TITLE
connection to Ip camera fails on freebsd

### ISSUE THREAD

**Issue by santonatale** [Motion-Project/motion#285]
Hi,

I noticed that motion is no longer able to connect to any ip cameras foscam with mjpeg ( I checked 8 ) at least on freebsd 11-STABLE.
The detail of the error shown is:

[2:] [INF] [NET] netcam_http_request: about to try to connect, time #0
[2:] [INF] [NET] netcam_connect: disconnecting netcam since keep-alive not set.
[2:] [INF] [NET] netcam_connect: with no keepalive, new socket created fd 4
[2:] [INF] [NET] netcam_connect: re-using socket 4 since keepalive is set.
[2:] [ERR] [NET] netcam_connect: connect() failed (22): Invalid argument
[2:] [INF] [NET] netcam_connect: disconnecting netcam (4)
[2:] [ERR] [NET] Failed to open camera - check your config and that netcamera is online
[2:] [ERR] [NET] netcam_http_request: Failed to read first camera header - giving up for now
[2:] [DBG] [ALL] motion_loop: vid_return_code 1
[3:] [DBG] [ALL] motion_loop: vid_return_code 1
[1:] [WRN] [ALL] motion_loop: Retrying until successful connection with camera

With version before 4 it works like a charm.
Thank you,

**Comment by tosiara** [comment]
Looks similar to https://github.com/Motion-Project/motion/issues/267

**Comment by santonatale** [comment]
Hi tosiara, thank you for looking into this.
I am not sure it is the same issue of #267 : I forgot to mention the platform is x86_64 (it is a xeon based server).
Do you know the fixes mentioned in #267 been committed to master branch ?
Thank you,

**Comment by santonatale** [comment]
No, I've just installed the port "motion" from the ports collection. It seems to be built with the 4.0.1 branch. I'll try to build the master repo and get back for a feedback.
Thank you so far,

**Comment by santonatale** [comment]
Hi,
I tried to build the master branch, but the problem is still there.
I am available if I can be of help debugging it.
Best,

**Comment by jogu** [comment]
Can you share the full log file right from the point motion starts please? As a gist would be great.

**Comment by santonatale** [comment]
Hi jogu,

sure, [here](https://gist.github.com/santonatale/23459d47e39efcafde6d05fd4379757a) it is.
Thank you,

**Comment by jogu** [comment]
Thanks! I don't really know what is going on.

I guess their could be a bug in our netcam connect code. The user in #267 was not using a netcam.

I'm fairly certain I've tried on MacOS (which previously showed some of the same problems as FreeBSD) and it worked okay. I don't have access to a FreeBSD easily, if anyone else can debug a patch would be welcome :)

**Comment by santonatale** [comment]
Hi jogu, thank you very much for your time anyway.
Just as an additional help, if somebody has the chance to look into this, [here](https://gist.github.com/santonatale/5a5389d3f53931ae0dda7be92ced0ea1) is another gist with the content of ktrace of the motion pid during some seconds of retries.
Thank you,

**Comment by jogu** [comment]
Ah, actually - you're using a http netcam. I never tested one of those, all mine are rtsp. I bet it just needs the same fix applying, fixing the sizeof argument to connect().

**Comment by slokhorst** [comment]
I think #287 should fix it. Can you try it out?
```bash
git fetch origin pull/287/head:pr287
git checkout pr287
make && etc
```

**Comment by santonatale** [comment]
Hi slokhorst,
it works!! Thank you very much!!
I'll try to send an email to the freebsd port maintainer to notify this.
All the best,
