### ISSUE TITLE
Axis cameras authorization failed

### ISSUE THREAD

**Issue by danbuntu** [Motion-Project/motion#289]
Hello

We have some axis M1004-W cameras they we are trying to add to motion eye.

We have added them via rtsp://[IP]/axis-media/media.amp and with a username and password. Motion eye finds the cameras and added them but they show no video.

In the logs we see:

[2] [ALR] [NET] rtsp_connect: unable to open input(rtsp://[IP]:554/axis-media/media.amp): -825242872 - Server returned 401 Unauthorized (authorization failed)

This would suggest that the username or password is wrong. However we know they are correct as we can use the same rstp stream, user and password in vlc and they open fine.

We can also set the camera to 'Enable anonymous viewer login' and they work.

Any ideas what we're doing wrong here please?

**Comment by tosiara** [comment]
Usually the url should contain user and password, like: `rtsp://[IP]/axis-media/media.amp?user=a&password=b`, but that depends on the camera vendor

**Comment by jogu** [comment]
I believe the authentication for RTSP streams is at least 95% handled by ffmpeg, so it could be an upstream bug. Do you know what version of ffmpeg you're using?

It would be handy if you can capture (using wireshark/tcpdump or similar) a working authentication sequence from VLC and a failed one from motion.

**Comment by danbuntu** [comment]
I just tried Tosiaras suggestion and this doesn't work i'm afraid.

The ffmpeg version we're using is:

 2.8.10-0ubuntu0.16.04.1

We're on a fresh install of ubuntu 16.06

**Comment by jogu** [comment]
Can you try a command like:

ffmpeg -i [url with username + password that works in VLC] -acodec copy -vcodec copy abc.mp4

**Comment by Mr-Dave** [comment]
@danbuntu :  Can you also try the following:  
1.  Temporarily turn off the authentication for the camera and validate that the connection works.

2.  Turn back on the authentication and try using the basic authentication method of
<code> rtsp://username:password@IPAddress:554/....</code>

3.  In addition to the option @jogu  mentioned for testing, you can also try 
<code> ffplay rtsp://username:password@IPAddress:554/....</code>
or 
<code> ffplay rtsp://IPAddress:554/.....</code>

If you've been able to resolve this, please make sure to close this issue.

**Comment by danbuntu** [comment]
I managed to get these working over the weekend.
I found this resource:

https://www.ispyconnect.com/man.aspx?n=Axis#

From there I found our make of camera and fiddled with the various urls untill I got it to work.

The final one for the axis cameras was:


http://10.0.74.27/axis-cgi/mjpg/video.cgi
