### ISSUE TITLE
High resolution causes core dump

### ISSUE THREAD

**Issue by steveww** [Motion-Project/motion#290]
Running on Raspberry Pi Jessie with the Pi Camera, setting the resolution above 640 x 480 causes a segv and core dump.

**Comment by Mr-Dave** [comment]
Jessie/Pi/Pi Camera for high resolutions has not crashed for the developers so we will need to see the full logs(startup to crash).   Please post on gist or something similar and provide the link here.

**Comment by steveww** [comment]
Attached is the config file, core dump an logs.
[Archive.zip](https://github.com/Motion-Project/motion/files/692418/Archive.zip)

**Comment by slokhorst** [comment]
In `motion.log`:
```
config image height (730) is not modulo 8
```

Can you try again with a height of e.g. 720 or 736?

**Comment by Mr-Dave** [comment]
I'm confused.  The log is indicating version 3.4.1, the opening of a webcam and the modulo 8 problem.  The issue is indicating a Pi cam which was added in version 4.0.  Is the problem with a webcam that is attached to a Pi rather than the PI/MMAL camera module?

**Comment by steveww** [comment]
The initial report was against 3.4.1 and yes it works just fine with the Pi camera using /dev/video0.

I have just cloned the Git repo and built it. I can confirm that the behaviour is the same; core dump. However setting the resolution to 1296 x 728 all neatly divisible by 8 all works like a charm and no core dumps.

IMHO a core dump is a bit of a harsh penalty for a minor misconfiguration. The code should handle this more gracefully.

**Comment by slokhorst** [comment]
I agree we should crash more gracefully, until we can do something about #92.
