### ISSUE TITLE
Enhancement Request: Preserve event id across restarts

### ISSUE THREAD

**Issue by steveww** [Motion-Project/motion#291]
Keep the event count between restarts, keep current event id in a file e.g. /var/lib/motion/motion.id
Have option in the config to enable / disable this feature.

**Comment by Mr-Dave** [comment]
Can you provide a description of why this would be desired?  With multiple threads/cameras executing at the same time with different event numbers, it would be very problematic to implement and always be accurate.

**Comment by steveww** [comment]
I had forgotten about multiple camera on one instance of motion.
From a UI point of view having a unique event id for each detection would make it easier to track. If this id gets reset if the motion daemon restarts it makes it difficult to keep track.

It may not be required to keep track of individual id for each camera, one id per motion daemon may be enough.

**Comment by tosiara** [comment]
Some time ago I thought about this feature to implement. Like, you want to update thr config, restart motion, but keep the id so it keeps going counting. But then I changed my mind. I really don't care what number prefix my recorded files have as they anyway have timestamp and can be sorted. More, when I see that index restarted it tells me that motion has unexpectedly restarted and I need to look into logs to see why

**Comment by steveww** [comment]
I am happy to help. As I don't really know the code base, would you give me a pointer to where the event counter is implemented? I will take a look to see what is involved.

**Comment by Mr-Dave** [comment]
I'd say that the official method of keeping a unique id is similar to what @tosiara  is doing.  Use a combination of the camera ID with a date/time stamp.

**Comment by jogu** [comment]
I'd agree with Mr-Dave / tosiara.

Maybe we should probably change the default behaviour? I suspect many people end up using the event ids purely because they are the default.

eg. default for movie_filename is %v-%Y%m%d%H%M%S

My personal setting is movie/%$/%Y%m%d/%H%M%S-%v

I don't really know why I have the %v there still. Probably only because it was there in the default...

**Comment by tosiara** [comment]
@steveww , if you are interested in the implementation, start from looking at the following code which sets `event_nr=1`: https://github.com/Motion-Project/motion/blob/master/motion.c#L798

**Comment by steveww** [comment]
Thanks for the tip however I have found a way around this limitation. I may still implement this functionality in the future when I have finished some other stuff I am working on.

**Comment by Mr-Dave** [comment]
Closing this issue as we will not be implementing this.
