### ISSUE TITLE
Issue/Contributing Template Revisions

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#298]
Github has the ability to display the following message and a hyperlink at the top of the screen whenever a new issue is being created:

  * Please review the guidelines for contributing to this repository.  

When users select the hyperlink, The template narrative is displayed.  The following is a draft of a narrative.  I really want to hear from others on this and consider considering everything from the tone to the actual content of the message.  

I am putting this as a issue for the moment but if easier, I can put it as pull request.

# How to contribute

Issues on the github site are intended to discuss code problems, crashes and application enhancments.  If you are having a issue with the setup, 
configuration or use of Motion, we have the following additional resources which are better suited to meet these needs.

  * User guide:  [Motion User Guide](http://htmlpreview.github.com/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html)
  * User Group List:  [Motion User](https://lists.sourceforge.net/lists/listinfo/motion-user)
  * IRC:  [#motion](irc://chat.freenode.net/motion) on freenode

It is very important to use these resources for non-code issues since it engages a much wider audience who may have experience resolving
the particular issue you are trying to resolve.  

##  Submitting Problems

Before submitting a issue, please make sure that you are using either the latest release as posted 
[here](https://github.com/Motion-Project/motion/releases) or that you have built the latest source code 
from the github master branch.

If the issue still remains with the current version, please validate that the issue has not already been reported
by searching through the issue log.  

Next, we will need to be provided the following in order to replicate and ultimately resolve the issue:

  * A complete Motion log for a single run from startup to shutdown at the NTC/6 log level.
  * The motion.conf file as well as well as any associated camera.conf files.  
  * The expected versus actual result

The preferred method of providing these files is by posting them on [gist](https://gist.github.com/).  Only provide 
the link to the gist files within the issue.  It is recommended that any IP addresses and/or usernames and passwords included in 
either file be masked to preserve your privacy.  Don't forget that the log file may be reporting these things as well.

Note that the developers do not use any front-end application to use Motion and we'll need the actual logs from the Motion
application rather than logs from the front-end application.

##  Submitting an Enhancement Request

Motion has a extremely large number of configuration options.  With so many options, it is important to include a description
of how/why the enhancement will be used.  It is possible that the existing options can be configured to address the need.  
(Which could then lead to a different enhancement than originally contemplated of making those options easier to use or documented
better.)

## Submitting changes

Generally, it is best to first submit a issue on the particular enhancement prior to a pull request.  This allows the particular
item to be discussed and determine how it would fit into the application.

As pull requests are prepared, in addition to the actual code, please also consider:

  * Changes needed to the Motion_Guide.html which is our user guide.
  * Changes to the motion.1 file which is the manual
  * Changes to the configuration templates of motion.conf, camera1.conf, etc.

Thanks,
Motion-Project Team.

**Comment by tosiara** [comment]
Looks good to me. I would like to see how that looks live

**Comment by Mr-Dave** [comment]
That is what I had wanted to see as well so I put it into one of my old [repos](https://github.com/Mr-Dave/comparebase).  Open an issue on it and you'll see a new header with the link.

**Comment by tosiara** [comment]
Looks really cool

What do you think about having some *mandatory* fields that user must provide if filing an issue, like:
1. version (x.y.z or git hash)
2. installed as a package or compiled from sources?
3. standalone or part of third party (like MotionEyeOS)
4. video stream source: V4L (card or USB), net cam (mjpeg, rtsp, other), mmal
5. hardware: x86, ARM, other
6. operating system: Linux (which), FreeBSD, other

?

**Comment by Mr-Dave** [comment]
I was thinking the three bullet points on "what we need" are mandatory and that includes the log and config files which shows most of these items.  Items 5/6 are not currently printed in the log and we should see about how to get them shown there.  I think it is just much easier to indicate "Provide the logs and config files" rather than trying to enumerate what might be needed for each situation.

**Comment by Mr-Dave** [comment]
closed via pull #304

**Comment by tosiara** [comment]
I would like also to create an issue template: https://help.github.com/articles/creating-an-issue-template-for-your-repository/
```
    version [x.y.z or git hash]: 
    installed as a package or compiled from sources: 
    standalone or part of third party (like MotionEyeOS): 
    video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:
    hardware [x86, ARM, other]:
    operating system [Linux (which), FreeBSD, other]: 
```

**Comment by tosiara** [comment]
Created pull for review: https://github.com/Motion-Project/motion/pull/327

**Comment by Mr-Dave** [comment]
Revised title.   "Issues" template needs to reference guidelines included in the "Contributing" template since users are not reading the "Contributing".
