### ISSUE TITLE
Can't authorize RTSP Amcrest camera

### ISSUE THREAD

**Issue by Drackene** [Motion-Project/motion#300]
I've ran into an issue in getting my Amcrest to work HTTP or RTSP. I am able to authenticate both protocols locally and externally with various browsers and media streamers. I found the various CGI strings for Amcrest/Foscam cameras, no luck. The camera shows up "Unknown" when trying to add through the UI, but has no errors, then asks to refresh, no camera feed.

Camera brand: Amcrest
Model: IP2M-841B

rtsp://###:###@10.10.1.10 works on everything but motioneye

Here is the log with username and password censored:
[1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://###:###10.10.1.10:554)
[1] [ALR] [NET] rtsp_connect: unable to open input(rtsp://10.10.1.10:554): -825242872 - Server returned 401 Unauthorized (authorization failed)

Edit: OS is Ubuntu 16.04.1 LTS Desktop KVM
Network is e1000 virtual adapter bridged to a 4x1 Gbps bond.
I initially tried with the admin account, but I also created another user in the admin group, which credentials still returned 401.

Please advise

**Comment by tosiara** [comment]
Have you tried contacting motioneye support?

**Comment by Drackene** [comment]
I originally did, but there was an open issue on their board with a very similar 401 unable to authenticate, and someone recommended posting here instead of there.

**Comment by jogu** [comment]
I have that exact same camera, so it definitely works with any recent version of motion.

This is the URL I am using:

rtsp://admin:XXXXXXX@192.168.1.xx/cam/realmonitor?channel=1&subtype=1

(replace XXXX with password)

The URL showing in your log file looks invalid to me, it is missing the /cam/etc part.

I'd try using the admin account to start with, a lot of these camera have oddities with extra users.

**Comment by jogu** [comment]
(As I mentioned that I use this camera, I should also add: I really don't recommend amcrest cameras. I've had truly appalling experiences with amcrest support, and I suspect that the only reason they get decent ratings on amazon is that amcrest have frequently offered the cameras at huge discounts in exchange for people writing reviews on amazon - I know because that's how I got this one. I'd recommend reolink cameras instead, here's an amazon uk link to their cameras: http://amzn.to/2j1fBgY )

**Comment by Drackene** [comment]
I do regret buying the cameras, everything from packaging to reviews to capabilities made me choose this brand. Now I am stuck with losing config options on the devices every once in a while. I had been manually editing the config file after trying every combination. 

I can verify that the link below does not work for me. I am also running 

Anyway I just tried rtsp://admin:#####@10.10.1.10/cam/realmonitor?channel=1&subtype=1
Shows up as invalid link and can't add
If I removed the /cam/... the camera shows up and lets me add, but does not stream once added. 

But again, rtsp stream works to any other application. This is also the second install I have done of motion. 

Motioneye is running the latest and greatest, but motion itself seems to be:
motion is already the newest version (3.2.12+git20140228-8build1).

Is that the best version for motioneye or should I compile the latest version of motion for motioneye?

**Comment by jogu** [comment]
My url was referring to what should be in the motion configuration file. I have no knowledge at all about what motioneye supports.

However I think the major issue is the old version of motion - you really want at least motion 4.0. https://github.com/Motion-Project/motion/releases has a package for xenial that I presume is suitable.

**Comment by Drackene** [comment]
I'll browse their forums to check to see if I can verify any compatible updates. I've attached my thread-1.conf file. I obviously haven't set anything up yet as I don't have a stream, but as far as getting a stream, can you confirm any differences?

[thread-1.txt](https://github.com/Motion-Project/motion/files/709751/thread-1.txt)

**Comment by Drackene** [comment]
Xenial and a little tweaking of dependencies worked! 
Thanks for your assistance

**Comment by Jeremy-Flaugh** [comment]
This is related but not...
I bumped into thread while researching my issues with amcrest and OMXplayer. I was able to open the following ULS's in VLC.
rtsp://admin:Password@192.168.76.75:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
rtsp://admin:Password@192.168.76.75:554/cam/realmonitor?channel=1&subtype=1
rtsp://admin:Password@192.168.76.75/cam/realmonitor?channel=1&subtype=1
But not in OMX player... Just displayed a blank screen.
I found some info on another cam over at spiceworks and applied it to my amcrest. I removed the & from the URL and OMXplayer was able to play the feed. This might apply to motion.

Example  rtsp://admin:Password@192.168.76.75:554/cam/realmonitor?channel=1subtype=1
