### ISSUE TITLE
Update motion-dist.conf and show all %variables that can be used

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#302]
Currently config file explains possible variables three times:

https://github.com/Motion-Project/motion/blob/master/motion-dist.conf.in#L376
```
############################################################
# Text Display
# %Y = year, %m = month, %d = date,
# %H = hour, %M = minute, %S = second, %T = HH:MM:SS,
# %v = event, %q = frame number, %t = camera id number,
# %D = changed pixels, %N = noise level, \n = new line,
# %i and %J = width and height of motion area,
# %K and %L = X and Y coordinates of motion center
# %C = value defined by text_event - do not use with text_event!
# You can put quotation marks around the text to allow
# leading spaces
############################################################
```
https://github.com/Motion-Project/motion/blob/master/motion-dist.conf.in#L434
```
############################################################
# Target Directories and filenames For Images And Films
# For the options snapshot_, picture_, movie_ and timelapse_filename
# you can use conversion specifiers
# %Y = year, %m = month, %d = date,
# %H = hour, %M = minute, %S = second,
# %v = event, %q = frame number, %t = camera id number,
# %D = changed pixels, %N = noise level,
# %i and %J = width and height of motion area,
# %K and %L = X and Y coordinates of motion center
# %C = value defined by text_event
# Quotation marks round string are allowed.
############################################################
```
https://github.com/Motion-Project/motion/blob/master/motion-dist.conf.in#L616
```
############################################################
# External Commands, Warnings and Logging:
# You can use conversion specifiers for the on_xxxx commands
# %Y = year, %m = month, %d = date,
# %H = hour, %M = minute, %S = second,
# %v = event, %q = frame number, %t = camera id number,
# %D = changed pixels, %N = noise level,
# %i and %J = width and height of motion area,
# %K and %L = X and Y coordinates of motion center
# %C = value defined by text_event
# %f = filename with full path
# %n = number indicating filetype
# Both %f and %n are only defined for on_picture_save,
# on_movie_start and on_movie_end
# Quotation marks round string are allowed.
############################################################
```
Should we describe them globally instead? One block at the top or bottom that describes all available variables.
As with this pull request https://github.com/Motion-Project/motion/pull/301 we will have ability to easily extend variables, I think it is worth to clean up the config so new variables can be added at single place

**Comment by pascal-fb-martin** [comment]
You might want to look at conf.c too. (BTW, what is the -s option?)

**Comment by tosiara** [comment]
Command line? -s means to start in setup mode

**Comment by pascal-fb-martin** [comment]
Well.. what does "setup mode" means? Never used it: I just 
followed/adjusted the default motion.conf

**Comment by tosiara** [comment]
Setup mode is used to tune threshold and mask values. Motion will show you black screen with blue motion pixels and show noise and threshold values, also dump them into console. So you can measure them according to your area/conditions and then update your config. It's more like debug dry run

**Comment by Mr-Dave** [comment]
I am not sure including everything in the default configuration file is best.  I think we can definitely go to just a single section but think it would be better to point users to the guide for the full documentation.

**Comment by tosiara** [comment]
Added new variable into default config: https://github.com/Motion-Project/motion/pull/314
As it is a new feature we should make it visible to users who use config as documentation
