### ISSUE TITLE
motion error on ubuntu 16.04 on rpi3

### ISSUE THREAD

**Issue by richardsith** [Motion-Project/motion#309]
after I've installed & modify motion package on ubuntu 16.04 for rpi3  when try to check its status I saw an ERR (Permission denied). I'm doing everything with sudo.

```
$: sudo service motion status
  motion.service - LSB: Start Motion detection
   Loaded: loaded (/etc/init.d/motion; bad; vendor preset: enabled)
   Active: active (exited) since Thu 2017-01-26 22:56:45 UTC; 6min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 407 ExecStart=/etc/init.d/motion start (code=exited, status=0/SUCCESS)

Jan 26 22:56:45 ubuntu-minimal systemd[1]: Starting LSB: Start Motion detection...
Jan 26 22:56:45 ubuntu-minimal motion[407]:  * Starting motion detection daemon motion
Jan 26 22:56:45 ubuntu-minimal motion[407]:    ...done.
Jan 26 22:56:45 ubuntu-minimal systemd[1]: Started LSB: Start Motion detection.
Jan 26 22:56:47 ubuntu-minimal motion[461]: [23733568] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motion/motion.conf
Jan 26 22:56:47 ubuntu-minimal motion[461]: [23733568] [NTC] [ALL] motion_startup: Motion 3.2.12+git20140228 Started with SDL support
Jan 26 22:56:47 ubuntu-minimal motion[461]: [23733568] [ERR] [ALL] myfopen: Error opening file /var/log/motion/motion.log with mode a: Permission denied
Jan 26 22:56:47 ubuntu-minimal motion[461]: [23733568] [EMG] [ALL] motion_startup: Exit motion, cannot create log file /var/log/motion/motion.log: Permission denied
Jan 26 23:02:59 ubuntu-minimal systemd[1]: Started LSB: Start Motion detection.
```
Someone can help me? thanks

**Comment by Mr-Dave** [comment]
I think that this is a issue that might be better addressed on the mailing list as described in our [contributing guide](https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md)

**Comment by richardsith** [comment]
I've resolved thanks

**Comment by KanimozhiP** [comment]
Can you plz, explain me how did you resolve this problem?

Thanks in advance...

**Comment by rudolfbyker** [comment]
When you run motion for the first time, it creates `/var/run/motion` and `/var/log/motion` and `/var/lib/motion`. If you ran it by issuing `sudo motion` from the command line, those folders will be created as belonging to the root user. When running it as a service, however, it will run as the `motion` user, and then it can't access folders that belong to `root`. To fix this problem, give them to the motion user: `sudo chown motion:motion /var/run/motion` etc.
