### ISSUE TITLE
Add webp image compression support

### ISSUE THREAD

**Issue by jayslovak** [Motion-Project/motion#310]
I am using motion to generate jpeg snapshots at regular intervals, each frame takes up to 1MB of space using my compression settings and camera resolution (3200x2400 px). This eats a lot of space on my NFS server (8 cameras are capturing the images).

I am proposing to implement webp image compression support in motion. Webp is a new format proposed by Google which uses key-frame image compression from their VP8 video codec. Webp is free and efficient codec that is seeing initial support in Firefox and Chrome.

Webp brings many improvements over venerable jpeg (better compression/quality, transparency and animation support, lossless compression mode and so on). I am seeing compression improvements over 80% on my sample content (images from Raspberry pi camera), which translates into significant disk utilization savings.

I have developed a patch implementing webp in my motion fork, the code is non-intrusive and integrates well. Currently only basic webp compression is implemented (no EXIF data, no grey-scale mode and no advanced compression tuning is possible). It is a compiled in by default, but can be disabled and jpeg still is the config file default.

My [fork](https://github.com/jayslovak/motion) compiles on Linux on x86-64 and armhf (Raspbian). Please let me know if you would be interested in pulling in the changes.

**Comment by tosiara** [comment]
Looks good and worth testing. Can you please issue a pull request so we can review and comment inline if needed?
Thnaks

**Comment by jayslovak** [comment]
Yes, done.
#311

**Comment by Mr-Dave** [comment]
I'm going to do a bit of investigating on the webp to determine its acceptance and history across the distributions to determine whether it defaults to included or is a option to add.  On web stream side, there is going to be a lot to consider.

**Comment by jayslovak** [comment]
Is there anything I can do to help? I would love to see this merged.

**Comment by Mr-Dave** [comment]
I didn't see an issue with the storing of the images in my search.  I just need to find some time for integration testing this with some of the other larger changes currently being worked.  At some time after it is merged, it is also going to require some additional work in the [packaging repo](https://github.com/Motion-Project/motion-packaging) to the debian rules and builddeb.sh script.

**Comment by jayslovak** [comment]
I hope this [pull request](https://github.com/Motion-Project/motion-packaging/pull/1) helps.
