### ISSUE TITLE
motion 4.0-1 on Ubuntu arm64 (Pine64 with ubuntu-Image Xenial)

### ISSUE THREAD

**Issue by Leonid1973** [Motion-Project/motion#317]
Hello,
i'm running motion on a Pine 64 with Ubuntu Image (Xenial 16.04). Pine64 is a Single-Chip Computer arm64.
Motion runs fine but the installed motion version is 3.2.12+git20140228.
Is it possible to Update to motion Version 4.0.1? I didn't find a binary...
Can somebody help?

Best regards
Leo

**Comment by tosiara** [comment]
Probably, yes. Check https://github.com/Motion-Project/motion/releases

**Comment by Leonid1973** [comment]
No, i was on this site... there is no version for arm64... and when i install motion from the official paket sources then it is Version 3.2.12
How can i update to version 4.0.1?

**Comment by tosiara** [comment]
Sorry, I missed that. No we don't provide arm build yet
You can either contact the image provider or compile from sources

**Comment by Mr-Dave** [comment]
Please try this new [deb](https://github.com/Motion-Project/motion/releases/download/release-4.0.1/xenial_motion_4.0.1-1_arm64.deb) which is now on the releases page.  If it works, can you close this issue.

**Comment by Leonid1973** [comment]
Hello Mr-Dave,
thank you very much for your help. I downloaded and installed the deb without any problems. It works perfect.

Best Regards
Leo
