### ISSUE TITLE
Use motion inside ionic framework application as a compiled Cordova plugin?

### ISSUE THREAD

**Issue by jordanlance** [Motion-Project/motion#323]
Would it be possible to use motion inside ionic framework application as a compiled Cordova plugin?
Anyone has done this has some references, information on how to do this?

I want to use motion in a personal project for detecting motion in video

**Comment by Mr-Dave** [comment]
I have never heard of such a thing.  Should probably check with the ionic cordova people.

[Contributing guide](https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md)
