### ISSUE TITLE
When configured using CMAKE - significant CPU usage increase

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#326]
I have pulled the latest source on my one of the test ARM devices and noticed significant CPU usage increase using the same config file when configuring using CMAKE:
```
PKG_CONFIG_PATH=/home/ubuntu/ffmpeg/out/lib/pkgconfig cmake .
```

![motion-cpu](https://cloud.githubusercontent.com/assets/3600973/23299514/7fc91246-fa8a-11e6-8a79-d0a3eb8e9cae.png)

When configured and compiled using autotools - no such issue

**Comment by tosiara** [comment]
@slokhorst , tagging you as the one who contributed to CMAKE

**Comment by tosiara** [comment]
Did a small test and seems like manually adding those cflags to CMakeList.txt resolves the issue: `-g -O2`

**Comment by slokhorst** [comment]
Yes, by default all optimization is turned off. If you pass `-D CMAKE_BUILD_TYPE=Release` to the CMake command, it will turn on optimization. We should definitely document this somewhere. (Or maybe even set the default build type to `Release`, although this disables debugging features).

**Comment by tosiara** [comment]
What do you mean by "debugging features"? -g flag?

**Comment by slokhorst** [comment]
Yes, I believe the following flags are appended in case of GCC (differs per compiler obviously):
`CMAKE_BUILD_TYPE=Debug`: `-g`
`CMAKE_BUILD_TYPE=Release`: `-O3 -DNDEBUG`

**Comment by tosiara** [comment]
Ok. So what cons can be against making Release the default one?

**Comment by slokhorst** [comment]
That debugging no longer works. But it's probably better to set it to `Release`, and tell developers/bug-reporter to set it to `Debug` if they want to do debugging.

**Comment by tosiara** [comment]
What if we use the same flags as autotools configure uses: `-g -O2`?

**Comment by slokhorst** [comment]
`-g` introduces a size and performance penalty and thus hurts the optimization. GCC also doesn't recommend to use `-g` and `-O` together: 

> GCC allows you to use -g with -O.  The shortcuts taken by optimized code may occasionally be surprising: some variables you declared may not exist at all; flow of control may briefly move where you
>        did not expect it; some statements may not be executed because they compute constant results or their values are already at hand; some statements may execute in different places because they have
>        been moved out of loops.

**Comment by tosiara** [comment]
Alright, so release cflags are currently a bit messy. We probably all agree that we need to 1) correct them so -g is not used with -O 2) make clags the same for both autotools and cmake. The only question whether we want default to be Release or Debug?
Who volunteers to fix that and pull?

**Comment by tosiara** [comment]
Meanwhile, I can confirm that configuring using CMAKE this way:
```
PKG_CONFIG_PATH=/home/ubuntu/ffmpeg/out/lib/pkgconfig cmake -D CMAKE_BUILD_TYPE=Release .
```
generates the same cflags as autotools: `-g -O2`

**Comment by Mr-Dave** [comment]
_"Who volunteers to fix that and pull?"_ Lets hold off on this for the moment.  I would like to re-assess where we are at with the build system.

**Comment by tosiara** [comment]
@slokhorst , can you make `Release` the default one? At least we will be in sync with autotools

**Comment by tosiara** [comment]
Overall, what is our current cmake status? Are we going to support it so it is up to date with automake?

**Comment by jogu** [comment]
I think we only really only want to support one build system, so one should really go.

cmake works much better for me (and in general I believe is easier to understand and maintain, particularly from where we currently are with autotools), but as I understand it doesn't work for mr-dave as there's an extra step to do when he's changing between different versions of ffmpeg for testing purposes.

I don't really know how we should move forward.

**Comment by iskunk** [comment]
I don't think keeping both build systems going is a big deal, as long as major refactorings aren't common. Look at PCRE, for example---they support both.

Making `Release` the default seems to be the way to go here. Is @slokhorst no longer available? I have CMake experience; I could look at this...

**Comment by tosiara** [comment]
Can you also review release flags for autotools? I beleive, -g and -O2 should be mutual exclusive, should't it? And also no need to specify them twice on command line:
```
gcc -g -O2 -I/usr/local/include -g -O2 -D_THREAD_SAFE  -Wall -DVERSION=\"4.0.1+git6e6d83c\" -Dsysconfdir=\"/usr/local/etc\" -I/usr/include/arm-linux-gnueabihf    -c -o logger.o logger.c
gcc -g -O2 -I/usr/local/include -g -O2 -D_THREAD_SAFE  -Wall -DVERSION=\"4.0.1+git6e6d83c\" -Dsysconfdir=\"/usr/local/etc\" -I/usr/include/arm-linux-gnueabihf    -c -o conf.o conf.c
gcc -g -O2 -I/usr/local/include -g -O2 -D_THREAD_SAFE  -Wall -DVERSION=\"4.0.1+git6e6d83c\" -Dsysconfdir=\"/usr/local/etc\" -I/usr/include/arm-linux-gnueabihf    -c -o draw.o draw.c
..
.
```

**Comment by iskunk** [comment]
`-g -O2` are the default flags in Autotools for GCC. Yes, debugging symbols and optimization don't usually go together, but with GCC at least it's usable. From the man page:
```
GCC allows you to use -g with -O.  The shortcuts taken by optimized
code may occasionally produce surprising results: some variables
you declared may not exist at all; flow of control may briefly move
where you did not expect it; some statements may not be executed
because they compute constant results or their values were already
at hand; some statements may execute in different places because
they were moved out of loops.

Nevertheless it proves possible to debug optimized output.  This
makes it reasonable to use the optimizer for programs that might
have bugs.
```

The CFLAGS get specified twice because we're using a home-rolled Makefile template that wasn't put together very carefully. (I've made some fixes to `Makefile.in` in my tree, but not enough to fix that bit, as it wasn't my focus.)

**Comment by iskunk** [comment]
Okay, here's a rough-draft fix for the topical problem. Add this to the very top of `CMakeLists.txt`, before the `project()` line:
```
IF(DEFINED CMAKE_BUILD_TYPE)
  SET(INIT_CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE})
ELSEIF(DEFINED ENV{CFLAGS} OR DEFINED CMAKE_C_FLAGS)
  SET(INIT_CMAKE_BUILD_TYPE None)
ELSE()
  SET(INIT_CMAKE_BUILD_TYPE Release)
ENDIF()
SET(CMAKE_BUILD_TYPE ${INIT_CMAKE_BUILD_TYPE} CACHE STRING "Choose the type of build, options are: None(CFLAGS/CMAKE_C_FLAGS used) Debug Release RelWithDebInfo MinSizeRel.")
```

This makes a "Release" build the default, without getting in the way if the user specifies custom flags via `CFLAGS` or `CMAKE_C_FLAGS`.

There are probably some corner cases where this won't work---I believe it's not possible for this variable to be frobbed in cmake-gui, because it only has an effect on the first configure run. I'm assuming the user would be specifying this on the (non-GUI) CMake command line, e.g. `cmake -DCMAKE_BUILD_TYPE=debug ...`.

Let me know if you find other cases where this breaks and it probably shouldn't...

**Comment by tosiara** [comment]
PR created https://github.com/Motion-Project/motion/pull/444, closing issue
