### ISSUE TITLE
Motion 4.0.1 on Orangepi with Armbian

### ISSUE THREAD

**Issue by Kobbe1** [Motion-Project/motion#336]
Hi guys,
I am running motion 3.4.1 with motioneye just fine, with a mjpeg network camera, a local cheap usb camera and the inbuilt OV camera.
 
I wanted to upgrade to 4.0.1 too see if I miss any new features.

The binary releases for the Raspi do install, but motion complains about missing mmal libraries at startup, so I compiled motion with ffmpegsupport but without mmal successfully. Motion now starts.

So far so good, however the local USB camera is detected but not working (not showing a picture) and also prevents the other 2 cameras from working. If I disable it the other 2 works.
I tried downgrading ffmpeg to 3.1 without success.

I don't have a log file right now.
I am hoping someone has seen this before and can make a quick sugestion.

Best,

-T
Btw - tried posting this to the sf group list but did not work.

**Comment by tosiara** [comment]
We need to look into motion's log. Can you provide it?

**Comment by tosiara** [comment]
I'm running 4.0.1 on OrangePi Zero just fine

**Comment by Kobbe1** [comment]
On re-trying things work as they should, not sure what was the issue 1st time. Thanks for the help.
