### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by aaomidi** [Motion-Project/motion#341]
Hey!

I was wondering is there windows support for this? Or maybe using the new lxss system?

Thanks!

**Comment by Mr-Dave** [comment]
No.  There is not direct Windows support.  A virtualization method is generally how it is currently accomplished.

**Comment by aaomidi** [comment]
Is there a guide on that?

**Comment by Mr-DaveDev** [comment]
If you just search for "virtualize linux on windows" there will be guides.

**Comment by aaomidi** [comment]
Oh alright, so through a virtual machine.

Thanks!
