### ISSUE TITLE
Help/bug in motion.conf

### ISSUE THREAD

**Issue by pvklink** [Motion-Project/motion#347]
I can't get motion control working in my RPI

i installed debian jessie
RPI 3 b
IP camera DAHUA IPC A35P

I just installed a DAHUA IPC A35P. and the web and app are working great!

I have the app working over internet,
streams are stored on my nas
and the last thing to do is domoticz integration.

I installed motion on the rpi:
sudo apt-get install motion
sudo nano /etc/default/motion
start_motion_daemon=yes and saved the file
sudo /etc/init.d/motion start

and finaly edit motion.conf with
-----------------------------------------
netcam_url rtsp:// <user>:<pwd>@<ipcam>/cam/realmonitor?channel=1&subtype=0.
rtsp_uses_tcp off

and get errors like this: (strange because i do get a live stream in VLC with the same URL !!!! is this a Bug?

[1] [CRT] [NET] [Mar 08 19:48:27] netcam_start: Invalid netcam_url ( rtsp:// <user>:<pwd>@<ipcam>/cam/realmonitor?channel=1&subtype=0.)

[1] [WRN] [ALL] [Mar 08 19:48:27] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)

What else parameters do i have to set to get my motion control to work
Or is it that the url could be correct but other parameters are wrong?

Who can help me?, i think i am almost there....

**Comment by tosiara** [comment]
The url looks invalid to me too: `rtsp:// :@/cam/realmonitor?channel=1&subtype=0.`
There is no host name, colon without user name and there is space which is not allowed in url. Also dot at the end is suspicious. I have no idea how VLC can play this url. The url should look like this:
```
rtsp://user:password@host/cam/realmonitor?channel=1&subtype=0
```

**Comment by pvklink** [comment]
Thanks, the cut and paste options went wrong.  
rtsp://admin:admin@192.168.178.56/cam/realmonitor?channel=1&subtype=0. is eaxtly what i have done...

**Comment by tosiara** [comment]
What motion version are you running?

**Comment by pvklink** [comment]
i just removed everything...
sudo apt-get remove motion
sudo apt-get purge --auto-remove motion

Do you have a description to install a working motion? I doubt if ffmpeg was part of my installation

**Comment by tosiara** [comment]
Older version does not support RTSP
Install latest release from here: https://github.com/Motion-Project/motion/releases

**Comment by pvklink** [comment]
:-) was just reading that !
Which deb package do i have to use on a rpi3b with debian jessie, the pi_jessie_motion_4.0.1-1_armhf.deb ?

Can i use this procedure?
sudo apt-get install gdebi-core
sudo gdebi {deb package name}
mkdir .motion
cp /etc/motion/motion-dist.conf ~/.motion/motion.conf
sudo nano ~/.motion/motion.conf
motion

**Comment by tosiara** [comment]
Sorry, I don't have Rpi3 near, so can't advise you how to install deb

**Comment by pvklink** [comment]
I think this file is ok, main part of the procedure wend well.. Only the etc/motion/motion-dist.conf does not exist, so the rest wend wrong...

**Comment by pvklink** [comment]
It works!! YES !

(i rebooted the rpi)
still some questions for my documentation
- do you install motion with user root or pi?
- when i reboot the device does motion automatically start?
- how to i manualy start motion,
  by > motion or
  by > sudo start service motion ?
