### ISSUE TITLE
Tested motion 4.01 with NAs en domoticz , some questions/wishes

### ISSUE THREAD

**Issue by pvklink** [Motion-Project/motion#350]
I have MOTION 4.01 working and it works GREAAAAAAAAAAAAAAAAAAAAAT !
If i can test something for you, let me hear, your welcome!

Have my rpi(3b) with debian jessie and motion connected to my cam(dahua ipc a35), my storage is on my QNAP nas en my notifications go to domoticz and even lights go with domoticz after motion :-)

Still have some small questions/problems/ wishes and then i have a 1000 % perfect system!

- how to stop and start motion, sudo service motion stop,  doesnt work well
i get errors that the port is busy or it does not start or stop at all
- when i reboot the device it does not start motion automatically !
   id did try> sudo update-rc.d service enable, this did not work !!!
These are important because i want to make a switch in domoticz to start/stop monitoring.

Wishes: 
- autodelete recording files after parameter=value in configfile

Thanks for the great work, this version of motion is more than great!!!!

Peter

**Comment by pvklink** [comment]
I have made bash script to start and stop motion from within domoticz. Works great!
Only disadvantage is that when starting motion there is triggered a mtion event and my alarm switch within domoticz will be triggered. Is there a way that the startup proces of motion will not trigger an motion aea event, or eventtriggering 1 minute after activate motionproces ? Perhaps jou can add a parameter in the config file for this?

**Comment by tosiara** [comment]
If you get some errors starting/stopping motion - please post here the details and log files
For autodelete it is not so trivial, as for example, extpipe can store video files in a custom location (cloud, sftp etc). I use my own cron script to move old files

**Comment by jogu** [comment]
Closing this; questions like this are best asked on the motion user's mailing list. If there's a bug we need the full detail (logs etc).
