### ISSUE TITLE
libmmal_vc_client.so might not get linked

### ISSUE THREAD

**Issue by huin** [Motion-Project/motion#351]
Running motion 4.0.1 on a Raspberry Pi 2 or 3 with Arch Linux.

The default build of motion 4.0.1 provided by Arch Linux was not picking up the mmal component for the Raspberry Pi. After a lot of debugging, I eventually realised that it was because the motion binary was not being linked against libmmal_vc_client.so - which is required to use the camera with the mmal* configuration directives.

It seems that the mmal library uses GCC __attributes__(constructor,used) on the critical function defined in libmmal_vc_client.so to register the camera component.

It appears that no symbol from libmmal_vc_client.so is referenced from motion, so the linker might choose not to dynamically link it at all. Certainly it was not linked when I reproduced the build. I wrote and applied the following patch, which seems to resolve the issue with my own build of motion:

https://github.com/huin/archpkgs/blob/master/motion-mmal/motion.patch

The key part being for --as-needed not being in effect when linking against libmmal_vc_client.so.

**Comment by huin** [comment]
For some more context: on my raspberry pi running arch,  autoconf was running the final GCC command to link the motion binary with a `-Wl,...` flag that included `--as-needed`.

**Comment by Mr-Dave** [comment]
Thanks for posting this.  We'll get this in.
