### ISSUE TITLE
event motion area detected triggers an event when starting the motion proces

### ISSUE THREAD

**Issue by pvklink** [Motion-Project/motion#354]
I have made bash script to start and stop motion from within domoticz. Works great!
Only disadvantage is that when starting motion there is triggered motion event and my alarm switch within domoticz will be triggered. Is there a way that the startup proces of motion will not trigger an motion aea event, or eventtriggering 1 minute after activate motionproces ? Perhaps jou can add a parameter in the config file for this?

**Comment by tosiara** [comment]
Probably, this would be interesting feature. For example if you need to start motion and then leave the building without triggering event.

So far I could only recommend you a workaround by stating motion in disabled mode and then turn motion detection back on manually:
```
-m                      Disable motion detection at startup.
# curl http://127.0.0.1:8080/0/detection/start
```

**Comment by iskunk** [comment]
Couldn't this be achieved using the Web interface API? You should be able to pause/restart motion detection dynamically at runtime this way:
```
    http://localhost:8080/0/detection/pause
    http://localhost:8080/0/detection/start
```

**Comment by Mr-Dave** [comment]
I am inclined to also opt for the script solution rather than yet another configuration parameter.  This seems to be easily accomplished via modification to the existing script by adding in the pause.  e.g.  Have script start Motion paused, have script wait, then send the request to start.

I will leave this open for additional comments for a few days and then be closing it.

**Comment by naggie** [comment]
Motion always detects motion immediately after startup when using rtsp for me. I'm using a Hikvision Hiwatch D120. I wonder if it's seeing a blank frame and then the real image or something -- I think a wait of a second or so for stabilisation would be good in this case, unless the behaviour is considered a bug.

**Comment by tosiara** [comment]
Record changed pixels to see what triggers: https://motion-project.github.io/motion_config.html#output_debug_pictures
Can you share a video so we can evaluate if it is a bug or not?

**Comment by naggie** [comment]
Thanks @tosiara -- I'll give that a shot tonight.
