### ISSUE TITLE
problem with on_event_start and arecord

### ISSUE THREAD

**Issue by Jo-Pitts** [Motion-Project/motion#361]
All,
firstly - I'm not sure if this is the right place for this.
secondly - I'm no linux expert (by a million miles!)

I have the following line in my /etc/motion/motion.conf file
`on_event_start sh /media/motion/onevent`

the onevent script has the following in it
```
#!/bin/sh
now=$(date)

echo "$now - starting recording"
arecord -D plughw:1,0 -f cd /media/motion/bob.wav

now=$(date)
echo "$now - ending recording"
```

I know that the onevent script is getting run (I tried it with a simple file copy command - which worked).

However, nothing happens with the arecord command when called from on_event_start.  However, if I run the script from the shell (i.e. sudo sh onevent), the recording does work.

I have chowned the /media/motion folder to the motion user.

I know that I need to change the arecord parameters to have a date/time stamped file name.  I'm just making this as simple as possible for now to get things working.

Regards
Jo

**Comment by iskunk** [comment]
Can the `motion` user read from the audio device? (This probably requires that the `motion` user be added to the `audio` group.)

**Comment by Jo-Pitts** [comment]
Daniel,
I'll try that.  I had come to the conclusion that it was probably a
permissions issue, but had no idea what to do about it.

I'll experiment, and come back to you ASAP.

Cheers
Jo

**Comment by Jo-Pitts** [comment]
Daniel,
that worked.  I added the motion user to the audio group and I can now
record.

What I can't do is kill the arecord process in the on_event_end command.
sudo killall arecord works from the command line, but not from within the
motion servce.  I even tried adding the motion user to the sudo group.
Any further thoughts?

**Comment by iskunk** [comment]
I'm not sure what might be happening there, but what may be helpful is to redirect the output (stdout+stderr) of the `killall` command to a file. This way, you should be able to see any error messages.

**Comment by Jo-Pitts** [comment]
Daniel,
This is my command
sudo killall arecord &> /home/motion/log

it sits in a file called oneventend (also in the /home/motion directory).

the on_event_end event calls the oneventend file

the log file gets created, but is completely empty.

Thoughts (sorry, bit of a noob here)

Cheers
Jo

**Comment by iskunk** [comment]
Is there a need to fork the command with `&`? I would do
```
sudo killall arecord >/home/motion/log 2>&1
```

**Comment by Jo-Pitts** [comment]
OK.. so your way worked (I just did what google told me :) )

The output is this

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified

which is all well and good, but I have no idea what to do with that
information LOL

remember this is the motion user executing this (motion is running as a
daemon/service)

Cheers

**Comment by Whytey** [comment]
Adding the user to the Sudo group isn't enough. It needs to be able to run
the killall command without needing to authenticate.  This is done through
editing the sudoers file.

I think ;-)

**Comment by iskunk** [comment]
There shouldn't be a need to run this through `sudo` in the first place, because the process being killed is owned by the same user (`motion`) doing the killing.

I'd remove the `sudo` invocation, and remove the `motion` user from the `sudo` group. (That's a security issue waiting to happen.) Instead, see what `killall` itself is telling you.

**Comment by Jo-Pitts** [comment]
Daniel,
so that ended up being stupidly easy.

(and yes - I have removed motion from the sudo group as well).

So... now I've got a .wav file, and an .avi file.  Which brings me to the
question I asked on stackoverflow:
http://stackoverflow.com/questions/43221567/linux-use-a-filename-to-dve-parameters-from

Any thoughts on that (offtopic) conundrum?

**Comment by iskunk** [comment]
You can use the `date` command to generate your timestamp string. For example,
```
filename=`date --iso-8601=sec`.wav
```

Good luck exploring :-)  Be sure to close this issue if it's done.

**Comment by Jo-Pitts** [comment]
I've got reliable timestamps. The question is around how do I pass the
timestamp contained in the marker file name to ffmpeg (I think it will use
grep and regex but I have no idea).

Cheers

**Comment by Jo-Pitts** [comment]
All,
I've nearly got this behaving.

I have the following code in a script (/motion/home/oneventend) which gets
called by the on_event_end event in motion:
------------------
#!/bin/bash

pkill -SIGINT -f "^arecord"


myarr=($( ls /home/motion/marker* | grep marker | awk -F'[_]' '{print $2}'))

for i in "${myarr[@]}"
do
   :
  ffmpeg -i "/home/motion/$i.wav" -i "/home/motion/$i.avi"
"/home/motion/$i.mp4"


done

/home/motion/cleanup
-----------




This script works fine when called with sudo /home/motion/oneventend

**Comment by Jo-Pitts** [comment]
All,
I've nearly got this behaving.

I have the following code in a script (/motion/home/oneventend) which gets
called by the on_event_end event in motion:
------------------
#!/bin/bash

pkill -SIGINT -f "^arecord"


myarr=($( ls /home/motion/marker* | grep marker | awk -F'[_]' '{print $2}'))

for i in "${myarr[@]}"
do
   :
  ffmpeg -i "/home/motion/$i.wav" -i "/home/motion/$i.avi"
"/home/motion/$i.mp4"


done

/home/motion/cleanup
-----------

This script works fine when called with sudo /home/motion/oneventend.

The intent of the script is to:

   1. Stop arecord
   2. find all instances of a file starting with marker and then place the
   balance of the filename into an array
   3. iterate through the array converting separate .wav and .avi files
   (also with the same filename as placed in the array) into a single file
   4. clean up the original files.


however when called by the on_event_end event I get the following error
being logged

/home/motion/oneventend: 6: /home/motion/oneventend: Syntax error: "("
unexpected

which is this line
myarr=($( ls /home/motion/marker* | grep marker | awk -F'[_]' '{print $2}'))

Any help on why this is?  Some weird sort of permissions issue?

Regards
Jo

**Comment by tosiara** [comment]
Closing as initial issue is resolved, and script issue is not related to motion
