### ISSUE TITLE
Update ffmpeg_variable_bitrate description in web config

### ISSUE THREAD

**Issue by cvigo** [Motion-Project/motion#362]
According to the motion.conf comments, values are 

> the range 2 - 31 where 2 means best quality and 31 is worst.

But 2 gives me very bad quality.
31 is much better but still worse than de streaming quality

**Comment by tosiara** [comment]
What version are you running?
There were issues with vbr, but all are resolved: https://github.com/Motion-Project/motion/issues/113

**Comment by cvigo** [comment]
4.0.1+git8a1b9a9 compiled from master a week ago

**Comment by tosiara** [comment]
Can you please create a sample video and provide your motion log + full config?

**Comment by cvigo** [comment]
yes, this afternoon

**Comment by cvigo** [comment]
Sample video, config and debug log [here](https://drive.google.com/open?id=0B990r2WNBqWmb0d6UThWOTZJTmc)

**Comment by tosiara** [comment]
Can someone familiar with ffmpeg comment if there is anything wrong? Where did number 49 come from? Why is keyframe interval incompatible? @Mr-Dave ?
```
[1428882968:motion] [NTC] [ENC] [Mar 28 19:08:31] ffmpeg_global_init: ffmpeg libavcodec version 57.64.101 libavformat version 57.56.101
[1:ml1:Salon-venta] [NTC] [EVT] [Mar 28 19:10:25] event_new_video Source FPS 22
[1:ml1:Salon-venta] [INF] [ENC] [Mar 28 19:10:25] ffmpeg_set_quality vbr/crf for codec: 49
[1:ml1:Salon-venta] [NTC] [EVT] [Mar 28 19:10:25] event_newfile: File of type 8 saved to: /usr/local/data/motion/2017.03.28--19:10:23-motion-CAM1.mp4
[1:ml1:Salon-venta] [NTC] [ALL] [Mar 28 19:10:25] motion_detected: Motion detected - starting event 1
[1:ml1:Salon-venta] [INF] [ENC] [Mar 28 19:10:25] ffmpeg_avcodec_log: specified frame type (3) at 0 is not compatible with keyframe interval
[1:ml1:Salon-venta] [NTC] [ALL] [Mar 28 19:11:45] preview_save: different filename or picture only!
[1:ml1:Salon-venta] [NTC] [EVT] [Mar 28 19:11:45] event_newfile: File of type 1 saved to: /usr/local/data/motion/2017.03.28--19:10:24-motion-CAM1.jpg
[1:ml1:Salon-venta] [NTC] [ALL] [Mar 28 19:11:45] mlp_actions: End of event 1
```

**Comment by genius3000** [comment]
I'm not sure about the above questions regarding the log messages, but as for the config setting of vbr, the example config comment has changed, as the option values have changed:
``# or the range 1 - 100 where 1 means worst quality and 100 is best.``

So, I would try running maybe 50 to see what that provides and go up/down from there to find what you like best. Obviously 100 would be best quality, but at the cost of increased size.

**Comment by tosiara** [comment]
Thanks, good point.
Default config:
```
# Enables and defines variable bitrate for the ffmpeg encoder.
# ffmpeg_bps is ignored if variable bitrate is enabled.
# Valid values: 0 (default) = fixed bitrate defined by ffmpeg_bps,
# or the range 1 - 100 where 1 means worst quality and 100 is best.
ffmpeg_variable_bitrate 0
```
@cvigo 's config:
```
# Enables and defines variable bitrate for the ffmpeg encoder.
# ffmpeg_bps is ignored if variable bitrate is enabled.
# Valid values: 0 (default) = fixed bitrate defined by ffmpeg_bps,
# or the range 2 - 31 where 2 means best quality and 31 is worst.
ffmpeg_variable_bitrate 2
```
@cvigo can you please update your config to use the latest template and try again? Looks like it is outdated and does not reflect latest fixes to variable framerate

**Comment by cvigo** [comment]
Thanks

The problem is that, when motion writes the config files (write command on the GUI) the wrong comment is restored (2 means best quality and 31 is worst)

**Comment by genius3000** [comment]
@cvigo glad it's working for you now, and thanks for the catch on the web config writing, that is indeed a bug.
Reference to code causing this:
https://github.com/Motion-Project/motion/blob/master/conf.c#L786

For the project contributors/maintainers: I could fix this up and try to check over the rest for any variance from the example conf. I may not get to it today, but within the next week I should definitely have time. If someone else is wanting to get to this sooner, please let me know that you have it covered, thanks.

**Comment by tosiara** [comment]
> The problem is that, when motion writes the config files (write command on the GUI) 
GUI? Which gui? Are you using MotionEYE?

**Comment by cvigo** [comment]
no, just the simple web interface that comes with motion

**Comment by tosiara** [comment]
Ok, so this need to be updated then. Reopening the issue for visibility

**Comment by jogu** [comment]
Thanks @cvigo - a merge request with a fix for that bit of code would be very welcome 👍

**Comment by jogu** [comment]
This is fixed now, right? Reopen if not.

**Comment by AndreKR** [comment]
Is there a relationship between `ffmpeg_variable_bitrate` and rate factor? So if I know I want x264 with a CRF of 25, can I convert that into a `ffmpeg_variable_bitrate` value?

**Comment by genius3000** [comment]
@AndreKR Yes, `ffmpeg_variable_bitrate` is a 0-100% scaled representation of CRF (for most encoders). The relevant code is [here](https://github.com/Motion-Project/motion/blob/master/ffmpeg.c#L565).  
`((100-ffmpeg->vbr) * 51)/100`  
So the (code) default of 45% would be a CRF of 28.

**Comment by AndreKR** [comment]
For completeness, for the mpeg4 (DivX) codec the formula [seems to be](https://github.com/Motion-Project/motion/blob/c1db494aaf2ae3f48ade6a90981bcb0b7cbaf3f0/ffmpeg.c#L577):
![2018-06-13_1023](https://user-images.githubusercontent.com/1188538/41338930-e5b5b5a8-6ef3-11e8-8343-e8004c883f39.png)
So for example for a `qscale` of 3, `ffmpeg_variable_bitrate` has to be set to:
`100 - cuberoot((3 * 118 - 1) * 125) = 35`.

**Comment by francisuk1989** [comment]
interesting so heres an example i have tested today with an rtsp @ 1024kbps/15fps
> ffmpeg_variable_bitrate 70
> ffmpeg_video_codec mp4:h264_omx
for an 4:12 capture, this brings an MP4 to about 334 MB (350,890,618 bytes) in size

normal would you say for 4:12 video?
