### ISSUE TITLE
Further privacy-mask performance improvements

### ISSUE THREAD

**Issue by iskunk** [Motion-Project/motion#364]
I read #340 and #343 with interest, and would like to contribute a bit of follow-on work to @pascal-fb-martin's optimizations.

First, [a new test program](https://github.com/Motion-Project/motion/files/895004/imagespeed2.c.txt), with the original `improved()` routine and a new `improved2()` equivalent.

This makes use of Intel intrinsic types to process more than 8 bytes at a time, while keeping the platform-specific stuff to a minimum. (This approach can later be fleshed out to use ARM NEON types [as supported by the RaspberryPi 2] and others, but I have no test platform for those.)

(Note that there is no need to use actual intrinsic calls like `_mm256_or_si256()`, because the compiler knows to put those in when it sees an operation on these vector types. So no new `#ifdef`s are needed in the main code.)

Some timing runs from a Linux/x86-64 system:
```
$ gcc -O0 -DNO_INTRINSICS -o imagespeed2 imagespeed2.c 
imagespeed2.c:22:3: warning: #warning "using 64-bit vectors" [-Wcpp]
 # warning "using 64-bit vectors"
   ^
$ ./imagespeed2 
Testing privacy mask loop (repeat 100000 times)
Execution time (improved loop): 9.483 sec.
Execution time (improved2 loop): 7.846 sec.

$ gcc -O0 -o imagespeed2 imagespeed2.c 
imagespeed2.c:17:4: warning: #warning "using 128-bit vectors" [-Wcpp]
 #  warning "using 128-bit vectors"
    ^
$ ./imagespeed2 
Testing privacy mask loop (repeat 100000 times)
Execution time (improved loop): 9.484 sec.
Execution time (improved2 loop): 4.125 sec.

$ gcc -O0 -mavx -o imagespeed2 imagespeed2.c 
imagespeed2.c:14:4: warning: #warning "using 256-bit vectors" [-Wcpp]
 #  warning "using 256-bit vectors"
    ^
$ ./imagespeed2 
Testing privacy mask loop (repeat 100000 times)
Execution time (improved loop): 9.499 sec.
Execution time (improved2 loop): 2.324 sec.
```

(I don't have a new enough system to test with `-mavx512f`.)

When compiler optimization is enabled, the performance impact is smaller but still there when using >=128-bit vectors:

```
$ gcc -O3 -DNO_INTRINSICS -o imagespeed2 imagespeed2.c
imagespeed2.c:22:3: warning: #warning "using 64-bit vectors" [-Wcpp]
 # warning "using 64-bit vectors"
   ^
$ ./imagespeed2 1000000
Testing privacy mask loop (repeat 1000000 times)
Execution time (improved loop): 25.970 sec.
Execution time (improved2 loop): 28.575 sec.

$ gcc -O3 -o imagespeed2 imagespeed2.c
imagespeed2.c:17:4: warning: #warning "using 128-bit vectors" [-Wcpp]
 #  warning "using 128-bit vectors"
    ^
$ ./imagespeed2 1000000
Testing privacy mask loop (repeat 1000000 times)
Execution time (improved loop): 25.868 sec.
Execution time (improved2 loop): 19.887 sec.

$ gcc -O3 -mavx -o imagespeed2 imagespeed2.c
imagespeed2.c:14:4: warning: #warning "using 256-bit vectors" [-Wcpp]
 #  warning "using 256-bit vectors"
    ^
$ ./imagespeed2 1000000
Testing privacy mask loop (repeat 1000000 times)
Execution time (improved loop): 25.329 sec.
Execution time (improved2 loop): 18.998 sec.
```

I've written the new code to use a union instead of type aliasing, which improves legibility and is more compiler-friendly. These larger vector types do need to be aligned, so I also revised `mymalloc()` to return suitably aligned addresses using `posix_memalign()`.

If this looks good, I'll prepare a pull request.

**Comment by Mr-Dave** [comment]
In reviewing the above, I saw the intrinsics types as part of the optimization.  Intrinsics are not part of my background so please forgive any questions which seem trivial.

Considering that the Motion application is packaged on a unknown platform by Debian/Ubuntu/Raspbian and VMs or bootstraps by myself, is the improvement only going to be realized by users that build for themselves and implement it upon that machine?  

Is there a potential problem if the system that built the package was able to define a particular type e.g. <code>-mavx512f</code> but the system upon which it was installed could not?

If either of the above are true, then isn't the following test result the comparison that would be applicable to most users since we'd have to turn off the intrinsics for packaging?
````
    $ gcc -O3 -DNO_INTRINSICS -o imagespeed2 imagespeed2.c
    imagespeed2.c:22:3: warning: #warning "using 64-bit vectors" [-Wcpp]    
    # warning "using 64-bit vectors"    
        ^    
    $ ./imagespeed2 1000000    
    Testing privacy mask loop (repeat 1000000 times)    
    Execution time (improved loop): 25.970 sec.    
    Execution time (improved2 loop): 28.575 sec.    
````

**Comment by iskunk** [comment]
Hi @Mr-Dave,

> Considering that the Motion application is packaged on a unknown platform by Debian/Ubuntu/Raspbian and VMs or bootstraps by myself, is the improvement only going to be realized by users that build for themselves and implement it upon that machine?

The improvement seen in packaged builds will depend on how the distros do their builds, of course. I believe most distros that ship for "i386" actually target i686, for example (previously it used to be i486).

> Is there a potential problem if the system that built the package was able to define a particular type e.g. -mavx512f but the system upon which it was installed could not?

Oh, naturally. If you compile the code such that it takes advantage of some new CPU feature, then unless you do some kind of "blended" optimization build, it will fail (probably with SIGILL) on CPUs lacking that feature.

> If either of the above are true, then isn't the following test result the comparison that would be applicable to most users since we'd have to turn off the intrinsics for packaging?

I don't think intrinsics need to be completely switched off for packaging. If we look at 128-bit words, those came with the original SSE, and that debuted in 1999 with the Pentium III. I don't know the story on ARM/Raspbian, but given the media applications that run there, I'd be surprised if there wasn't any usable SIMD stuff.

**Comment by Mr-Dave** [comment]
I am going to pass on this.
