### ISSUE TITLE
Array overrun in process_image_ring()

### ISSUE THREAD

**Issue by iskunk** [Motion-Project/motion#365]
In running Motion (Git master) under Valgrind, I'm seeing a read past the end of an array at the following line in `motion.c`, function `process_image_ring()`:
```
    /* If image is flagged to be saved and not saved yet, process it */
    do {
        /* Check if we should save/send this image, breakout if not */
        if ((cnt->imgs.image_ring[cnt->imgs.image_ring_out].flags & (IMAGE_SAVE | IMAGE_SAVED)) != IMAGE_SAVE)
/* OVERRUN IS HERE --------------^^^^^^^^^^^^^^^^^^^^^^^^^^ */
            break;

        /* Set inte global context that we are working with this image */
        cnt->current_image = &cnt->imgs.image_ring[cnt->imgs.image_ring_out];
```

Experimentally, I added this assertion just before the line, and the assertion failed:
```
        assert(cnt->imgs.image_ring_out < cnt->imgs.image_ring_size);
```

The problem appears to be that when the image ring buffer is resized to a smaller size in `process_image_ring()`, the active "cursors" within the buffer are not reset to remain inside the buffer. Adding these two lines appears to make the problem go away:
```
diff --git a/motion.c b/motion.c
index 9e68a6b..8460ecb 100644
--- a/motion.c
+++ b/motion.c
@@ -128,6 +148,9 @@ static void image_ring_resize(struct context *cnt, int new_size)
             cnt->current_image = NULL;
 
             cnt->imgs.image_ring_size = new_size;
+
+            cnt->imgs.image_ring_in = 0;
+            cnt->imgs.image_ring_out = 0;
         }
     }
 }
```

(A comment in the header to `image_ring_resize()` indicates that the images in the ring buffer are not saved across the resize, so resetting the "cursors" to zero unconditionally seems to make sense.)

**Comment by tosiara** [comment]
This seems to be a small change. Are we just waiting for PR?
@jogu have you checked this one?

**Comment by jogu** [comment]
The suggested change makes sense to me, so yeah a PR would be good, please!

**Comment by tosiara** [comment]
@iskunk can you please prepare PR for this patch? Thanks!

**Comment by iskunk** [comment]
Gladly :-)  Set the two vars to zero, and I also threw in the assertion for good measure.
