### ISSUE TITLE
Video produced by motion contains no motion

### ISSUE THREAD

**Issue by tonyfalc** [Motion-Project/motion#371]
I am have configured motion to produce video of motion events (as well as a jpg of the frame containing the "most" motion). The relevant configuration parameters (from motion.conf) are

minimum_motion_frames 1 
pre_capture 2
post_capture 10
gap 60

output_normal best
output_motion off
quality 75
ppm off

ffmpeg_cap_new on
ffmpeg_cap_motion off
ffmpeg_timelapse 0
ffmpeg_variable_bitrate 0
ffmpeg_video_codec mpeg4

text_right %Y-%m-%d\n%T-%q
jpeg_filename %v-%Y%m%d%H%M%S-%q
movie_filename %v-%Y%m%d%H%M%S

While I am seeing jpgs that contain motion, the videos (.avi) contain none. When I look at the time stamps, it seems like the video precedes all the motion. For example:

-rw-r--r--  1 motion motion   80450 Apr 13 09:22 02-20170413092204.avi
-rw-r--r--  1 motion motion    8417 Apr 13 09:22 02-20170413092205-00.jpg

If I am reading this correctly, the frame (jpg) I am seeing is the first one produced at 9:22:05, while the video file was produced one second earlier (9:22:04). The video itself (which is time-stamped) says 9:22:03.

I am clearly missing something here; any help figuring this out would be much appreciated.

-Tony

**Comment by tosiara** [comment]
What version are you using? We have no such config option `ffmpeg_cap_new on`
It has been renamed long time ago. Can you  update to the latest version and try to reproduce again?
