### ISSUE TITLE
on_camera_found is not known

### ISSUE THREAD

**Issue by telemaxx** [Motion-Project/motion#373]
"on_camera_lost" i can use with succsess, but the opposit "on_camera_found" is not known.
If i use that in my config file, i get an error.
The Doku says the option is availible:
http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#on_camera_found
but when i list the options inside the webinterface, i dont see such an option.
My config line:
`on_camera_found "echo 'Camera found again' | mail -s 'Camera conected' mymail@mail.info"`

Is the Doku wrong or do we have a Bug?

Thanks in advance.

**Comment by genius3000** [comment]
What version of motion are you running?
The event "on_camera_found" was added after the 4.0.1 release and only exists in the master branch so far. If you aren't running a 'built from master (after Jan. 12, 2017)' version, you don't have that event available.

**Comment by jogu** [comment]
I think I'd tend to agree with genius3000 - please let us know if you still see an issue when running the version from master.

(I suspect we should perhaps add links to the matching guide for the release to the release downloads page if we haven't already...)

**Comment by telemaxx** [comment]
ok,i use the 4.01 from the release download page.

Are there somewhere "ready to fly"  deb packages for raspbian Jessie? 

i would like to avoid to build that stuff myself, seems to be a bit complicate.

**Comment by jogu** [comment]
We don't have a firm date for the next release I'm afraid. Sometime we should perhaps try setting up some nightly builds, but I don't think anyone has time for that just now.

**Comment by telemaxx** [comment]
if the weather is bad this weekend i will try to build myself.
i think there is somewhere a
"Build motion in 10 easy steps for dummies"
Description...

**Comment by jogu** [comment]
Just follow the documentation here:

http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Abbreviated_Building

**Comment by genius3000** [comment]
@jogu (this is going a little off-topic but...) I've been meaning to setup a build server for learning experience basically. Probably next week I could have something functional, maybe. I think I'll open a new issue for discussion once I've got it functional.

**Comment by telemaxx** [comment]
@Jogu and genius3000 thank for the support.
Now i have the last version running and fully functional 😃😃😃
I had to replace 
libjpeg62 and libjpeg62-dev
against the -turbo Versions libjpeg62-turbo and libjpeg62-dev-turbo

and the binaries  are now in /usr/local/bin
So I had to uninstall the old motion.

Thanks a lot,
Telemaxx
