### ISSUE TITLE
netcam.c compilation error when compiling without ffmpeg on RPi3

### ISSUE THREAD

**Issue by bcgwebdesign** [Motion-Project/motion#382]
Great work team - I'm not that confident about adding to the project but came across a compilation error when compiling last source on my RPi3.

netcam.c was not compiling because rtsp_context->active was not defined for struct rtsp_context (line 1879 of netcam.c)

not sure if this is the appropriate fix, but duplicating the 'active'  member variable in the #else version of the struct declaration makes things all compile no problem.

**Comment by tosiara** [comment]
Can you post your `./configure` and `make` logs?

**Comment by bcgwebdesign** [comment]
Thanks - here they are

[config.log.txt](https://github.com/Motion-Project/motion/files/984616/config.log.txt)
[make.log.fail.txt](https://github.com/Motion-Project/motion/files/984624/make.log.fail.txt)

**Comment by iskunk** [comment]
This one's mine.

**Comment by bcgwebdesign** [comment]
hey @iskunk - fyi - just grabbed that updated file from your fork and compiles fine for me many thanks

**Comment by iskunk** [comment]
Thanks for checking the pull request, @bcgwebdesign. Please let us know if you see another other breakage!
