### ISSUE TITLE
Chopped video

### ISSUE THREAD

**Issue by atatistcheff** [Motion-Project/motion#386]
I am having an issue with frames not being assembled properly.  I'm not even sure what to call this.  It happens with all of my higher definition USB cameras -  1280x720 cameras with or without night IR mode.  However, when using something like a Logitech USB webcam it never happens.    This happens on Raspberry Pi and now the problem is much worse on the ODROID C2. I get the picture shown about every other frame in the video.   It occurs on the web streaming video as well as in the .avi file written to disk.  Any help would be appreciated!

![screenshot 2017-05-14 16 36 53](https://cloud.githubusercontent.com/assets/13168324/26038595/149c30ac-38c9-11e7-9502-ace487055b15.png)

**Comment by tosiara** [comment]
Which version are you running?
Can you provide full detailed `-d 7` motion logs for every camera that is affected?

**Comment by atatistcheff** [comment]
Attaching two logs.  The odroid log is using 4.01 the rpi log is using 3.2.12.  This is two different USB cameras one on an odroid CD and the other on a Raspberry Pi (I believe it's a Pi2).  The issue is much worse on the odroid.  On the Pi you see a few stray frames every minute.  On the odroid it is sometimes multiple frames one after another and the best we can hope for is one or two uncorrupted frames in a row.

[logs.zip](https://github.com/Motion-Project/motion/files/1001386/logs.zip)

**Comment by tosiara** [comment]
How did you install motion? Built from source, installed from github release or used your distro repo?

**Comment by atatistcheff** [comment]
Using the distro repo (apt-get) for 3.2.12 and the dpkg file for 4.0.1.  However, I've done some further testing.   I tried both VLC and Cheese on the X desktop and Cheese works perfectly while VLC shows the same chop as motion.  VLC will work fine for a few seconds and then go into a fit of distorted frames the same as motion.  However, if I use Cheese the video looks fine.  Whatever VLC/motion have in common is causing this issue while Cheese seems to be immune.

**Comment by tosiara** [comment]
Maybe vlc and cheese are using different input pixel format? You should localize the issue using vlc by playing with V4L params

**Comment by atatistcheff** [comment]
More testing, the previous test was on the Odroid C2 using Ubuntu 16.04.  I have now changed to Armbian and after installing motion 3.2.12 the issue has gone away.  No idea what the difference is but there is apparently something in Ubuntu that is causing issues for these cameras.  So it's clearly not a motion issue but still something nice to know I suppose.
