### ISSUE TITLE
Motion detection graph over time

### ISSUE THREAD

**Issue by tehKaiN** [Motion-Project/motion#391]
I've started [this issue](https://github.com/ccrisan/motioneye/issues/538) on motioneye, but it looks like that there is a need to make some changes in motion itself to make it happen.

AFAIK motion detection is done by comparing count of pixel changing over time with percentage threshold configurable in camera settings. I'd like to be able to do graph of this count across a single day, so I'd be able to decide how many pixels changed is true motion and how many is not and tune my settings accordingly.

Also, since motioneye exposes motion detection threshold as changed pixel percentage, would it be possible to add option to display changed pixel percentage instead of plain count in top-right corner?

**Comment by tosiara** [comment]
You can run motion in setup mode `-s` and see all the values. Would that help you to tune threshold value?

**Comment by tehKaiN** [comment]
That would mean that I'd have to sit and look at numbers all the time.

I'm not able to test threshold by walking around the whole monitored area. A better option for me would be to have a graph from entire windy or rainy day. Noise value should then become more apparent and I could see characteristics of hi change "islands" on graph and also set minimum consecutive frame count to detect motion.

I'm afraid that I also don't have enough resources for smart mask - I'm running orangepi one with 2 ip cams. If motioneye is not eating my whole cpu power, I have just barely enough cpu power to detect motion by threshold with 15fps. Or maybe, is there a way to do faster motion detection using aux stream and recording from main stream?

**Comment by jogu** [comment]
Pull requests that implement something like this would be welcome. I suggest discussing the exact approach here on this ticket before starting coding.

**Comment by iskunk** [comment]
Motion detection using the aux/sub-stream is an open issue: #123.

As for what you're requesting... an easy way of doing this would be to write out the detection values (for every frame?) to a plain text file, and then you could use Gnuplot or a similar graphing program to view the results. MotionEye, of course, could do its own UI around that.

Would that be workable?

**Comment by tehKaiN** [comment]
That would be cool!
Also, since such log would only weigh about 5MiB (32-bit int for each frame or plaintext?) for 24h of logging at 15fps, I'd like to have it saved for every day in different file, with date as a file name.

I'm still uncertain if there is a need to have every frame changes logged or just an average from each second, but I guess we'll have to look at the output to see what delivers better results.

**Comment by iskunk** [comment]
The log should probably be a bit more verbose than that, but the understanding would be that this is only for setup/calibration, not regular day-to-day use.

I thought about averages, too. Since that's throwing away information, that would probably need to wait until the MotionEye folks can say that this would be fine.

**Comment by iskunk** [comment]
Okay, I've pushed a very rudimentary implementation of this to [my branch](https://github.com/iskunk/motion/tree/iskunk-wip).

In your Motion config, set `changes_log_file /path/to/changes-log.txt` and run as usual.

The file format includes the following information:
* Unix timestamp and intra-second shot number of frame, as a way of identifying the frame globally (there may be a better way than this but it's not obvious to me)
* Number of pixels changed (not including those within the noise margin, natch)
* Flag to indicate if a light switch was detected
* Flag to indicate if camera is considered to be moving

No entry is printed out for frames that were not processed by the motion detector.

More work is going to be needed, of course---in order for MotionEye to be able to use this effectively, the logging will need to be dynamically controllable via the Web interface. But this should at least get the ball rolling on what you can do with such a log file, and how the logging can be improved.

**Comment by cimba007** [comment]
Hello,

is there any progress on this topic? I don't have the resource to look into building motion from @iskunk repository myself .. Is it possible to get a package for debian stretch to just drop and install to test the implementation?

**Comment by iskunk** [comment]
@cimba007, this feature is nowhere near ready for end users. What I posted was an experimental version  to get feedback (which, alas, was not forthcoming).

Even if this were fully implemented and working, MotionEye would then need some updates to actually use the information being produced.

**Comment by Mr-Dave** [comment]
I do not see this being implemented.  @tosiara has specified the method by which this can be accomplished using the existing functionality in the setup mode.  Specifying a output log file while running in setup mode at the INF level sends all the messages including the raw changes detected to the file.
