### ISSUE TITLE
Scaleable text

### ISSUE THREAD

**Issue by colinl** [Motion-Project/motion#395]
I have been looking at the addition of a config parameter to allow scaling of text, rather than just the doubling that is currently available via text_double. As a feasibility test I have hacked in the feature using a compile time directive to specify the scaling (an integer 2, 3, 4 etc) on the scaleable_text branch of my fork [1]. I am proposing a new configuration item text_scale which would be set to the scaling required. To provide backwards compatibility, if this is not set then text_double would continue to work as currently. If text_scale is set then text_double would be ignored. Would a PR along these lines be acceptable?

[1] https://github.com/colinl/motion/tree/scaleable_text

**Comment by tosiara** [comment]
Created PR for review: https://github.com/Motion-Project/motion/pull/421

**Comment by tosiara** [comment]
Let's consider a config param that specifies text size, `text_double yes/no` changed into `text_scale 1-10`

**Comment by colinl** [comment]
That is what I already proposed I think (text_scale).
