### ISSUE TITLE
Version 4.0.1 not compiling on Raspberry Pi 8.0

### ISSUE THREAD

**Issue by benclewett** [Motion-Project/motion#397]
Raspbian GNU/Linux 8 (jessie)

vloopback_motion.c: In function ‘v4l_startpipe’:
vloopback_motion.c:181:26: error: storage size of ‘vid_pic’ isn’t known
     struct video_picture vid_pic;

Any ideas?

**Comment by tosiara** [comment]
Can you provide full compile log?
