### ISSUE TITLE
Kernel Panic after connecting to motion on port 8081

### ISSUE THREAD

**Issue by benclewett** [Motion-Project/motion#398]
This may not be 100% motion, however I am having a lot of problems finding the solution to this issue and somebody here might know the answer.

Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

Using 'modprobe bcm2835-v4l2' and motion 3.2.1, binding to /dev/video0, streaming on port 8081.

Stable before I connect a browser.  Then a few seconds of good quality video, and then a kernel panic.

I have seen similar posts from other people on various PI forums, but no definite answers.

Anything you can think of I can try?

Thanks,

Ben

**Comment by tosiara** [comment]
First thing is to upgrade to the latest motion

**Comment by benclewett** [comment]
Many thanks for getting back to me.

My version is the latest published for Raspbian.

It seems I may have had a voltage problem.  I swapped battery on my PI and
motion works perfectly.  I would guess that the camera and extra CPU
processing exceeded the power from the battery, and gave the symptoms of a
kernel panic.

Last thing I would have thought of!

Ben

**Comment by tosiara** [comment]
Check https://github.com/Motion-Project/motion/releases there should be 4.0.1 for raspberry

**Comment by tosiara** [comment]
Have you tried the latest version?
