### ISSUE TITLE
Enhancement Request - Daily Digest of Motion Videos

### ISSUE THREAD

**Issue by rayperkins1** [Motion-Project/motion#404]
I would like a way to get a single video file for all the motion events in the last 24 hours, aka a daily digest that I can quickly review by watching one file.  I have come up with a few hacks to make this work and I find it very useful, but not reliable.

A better man than I could write better scripts, but I think the concept of a daily digest would be a useful feature for your project.  For example:  I am currently exporting the digest to my mythtv DVR so it is just another show I watch every day.  I find this the only way to stay engaged in reviewing events long term.

My scripts originally concatenated all the video streams from the last 24 hours.  This was done using version 3.2.  When I got a new camera that only did RSTP I built a new VM to use 4.0 and wound up having problems with my old method.  At this point a dailty cron script creates a video file from all the jpegs created in the last 24 hours.  The results are decent, but events are not reliably chronological. 

Thanks for all  your hard work on this project, it has been extremely useful to me.

**Comment by tosiara** [comment]
What is the problem with 4.0 concatenating video files? What codec are you using?

**Comment by iskunk** [comment]
@tosiara, I believe @rayperkins1 was using his own scripts to concatenate the videos, not Motion itself.

@rayperkins1: This is an interesting use case. I think it may already be possible to get this result---if you set a very large `event_gap` value (e.g. 100000, more than one day), and trigger the "makemovie" action via the Web interface once a day. That would mean the entire day is just one very long event, but the video should then have the form you want. Does that sound workable?

**Comment by rayperkins1** [comment]
I am not great with the video tools and/or scripting with them.  The specific problem seemed to be that even though I had the frame rate set to 10 sometimes the files would be 9 FPS and sometimes they were 10 FPS.  This would cause the concatenation to fail.

A few hours after submitting this ticket I spotted the possibility of using event_gap even though it specifically says not to use it for too long of a time.  I foresee a problem where the event_gap timer starts on the first detected motion and not a specific time, so the closing of the video file will occur at random times.  I want to move a single video file from motion to my DVR everyday at 6 PM, so if the file is still open I am not sure what happens.  Could be some file system type problems when trying to copy an open file, could be some playback problems depending on the player and codec etc of the file.  I was thinking I could try to get away with this by restarting the motion service everyday right before gathering the video file.  I need to check on my assumption that a service restart would nicely closeout the open video file.

Thanks again!

**Comment by iskunk** [comment]
You are right that `event_gap` starts counting down when detected motion ends; that is why the "makemovie" action may be useful. It forcibly causes Motion to finish out any in-progress movie(s), and start a new one for any future events.

A general restart will do this by-the-by, but there should not be a need to resort to that.

**Comment by rayperkins1** [comment]
This sounds promising, I was not aware of the makemovie feature.  I have the webserver enabled and can see the option there.  Unfortunately I don't seem to have a motion-control utility.  I just installed ubuntu 16.04 and installed the rpm from the git page for xenial.  Do you have any tips for finding/installing motion-control?  Is there a seperate packet or something?

**Comment by iskunk** [comment]
I'm not aware of any specific "motion-control" utility. if you're looking to interact with the Web interface via a script, `curl` or `wget` will do the job handily.

**Comment by rayperkins1** [comment]
Thanks, I get it now.  I was looking at old docs, the motion-control utility was deprecated after 3.1:
http://www.lavrsen.dk/foswiki/bin/view/Motion/FrequentlyAskedQuestions#How_do_I_make_time_based_motion_settings_63

**Comment by tosiara** [comment]
> The specific problem seemed to be that even though I had the frame rate set to 10 sometimes the files would be 9 FPS and sometimes they were 10 FPS. This would cause the concatenation to fail.

Cameras are known to provide inconsistent frame rate, especially USB in low light. But how are you going to solve this problem with motion? Are you expecting motion to provide you static frame rate in all files before concatenating them?

I have no problem concatenating motion's movies using ffmpeg:
```
# mediainfo 875-20170626_19-23.mp4 877-20170626_19-43.mp4 870-20170626_18-49.mp4 | grep fps
Frame rate                               : 5.000 fps
Frame rate                               : 12.000 fps
Frame rate                               : 10.000 fps

# cat concat.txt
file 875-20170626_19-23.mp4
file 877-20170626_19-43.mp4
file 870-20170626_18-49.mp4

# ffmpeg -f concat -safe 0 -i concat.txt -c copy output.mp4 > /dev/null

# mediainfo output.mp4 | grep fps
Frame rate                               : 3.113 fps
Original frame rate                      : 5.000 fps
Minimum frame rate                       : 0.002 fps
Maximum frame rate                       : 10 240.000 fps
```

**Comment by tosiara** [comment]
@rayperkins1 do you have any arguments why it is better to create digest using motion rather than external cron script?

**Comment by rayperkins1** [comment]
What I decided to do was turn off the movie creating within motion and am
instead using a cron job to create movies out of the collection of jpgs
once per day.  This seems to be working so far.  At this point I am dialing
in things specific to the cameras, like what camera I use, camera
placement, using masking and tweaking the various settings in motion.

**Comment by tosiara** [comment]
Ok, thanks
