### ISSUE TITLE
Feature request: Support external triggers

### ISSUE THREAD

**Issue by jasaw** [Motion-Project/motion#405]
Allow USR1 and USR2 signals to be used:
1. To force a recording, i.e. external trigger OR image motion trigger = record video
2. In combination with image based motion detection to trigger a recording, i.e. external trigger AND image motion trigger = record video

USR1 to start external trigger, USR2 to stop external trigger.

USR1 is currently used, but I don't know in what scenario it is useful in its current implementation. I apologize for my ignorance.

**Comment by jogu** [comment]
I think this is possible via webcontrol ( http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Options_Stream_Webcontrol ), which also provides more granularity (apply to just one camera, or to all cameras).

1 is I think covered by 'makemovie', 2 by 'detection'.

I can't see a strong reason for doing anything with signals.

**Comment by jasaw** [comment]
@jogu I'm sorry, I may have misunderstood the motion documentation. Maybe lack of documentation. Can you please elaborate more on how exactly do I use both the "makemovie" and "detection" methods you mentioned?

1. How do I use "makemovie" to force a recording even when image-based detection has not triggered?

2. What HTTP APIs are available under "detection" that allows me to tell motion to only start recording when both external and image-based detections have triggered?

**Comment by jasaw** [comment]
@jogu I get the "detection" part. The external event handler does a "detection start" via HTTP API when it triggers, and "detection pause" when it's not triggered. In effect, we get external trigger AND image motion trigger = record video

I still don't get how "makemovie" achieves the OR scenario.

**Comment by tosiara** [comment]
makemovie forces movie file flush, it is not related to event control

**Comment by jogu** [comment]
Sorry, wrong thing. I'm sure there's a way to force movie production via the web interface; I guess it must be emulate_motion: http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#emulate_motion

(Btw, questions about how to use motion are best asked on the motion-users mailing list where you'll get a large audience.)
