### ISSUE TITLE
Camera led indicator configuration

### ISSUE THREAD

**Issue by tetebueno** [Motion-Project/motion#406]
Couldn't find a config option to disable camera led indicator for web cameras and such. If there's no such thing, it'd be nice to have it in order to avoid using tape to cover it when leaving cameras for surveillance purposes.
I can think of an indicator_led configuration option with 0/1 based value in each camera config file to control such behaviour. Default value can be current behaviour so no changes are made if option is not set.

That's it. Hope it helps.
Cheers.

**Comment by tosiara** [comment]
Not every UVC camera has interface to control LED. A would say I only saw 1 (one) in my life

**Comment by iskunk** [comment]
You want an option  to _prevent_ the camera LED from turning on when the camera is in use?

If you're already inclined to put tape over the lens, this is exactly what you _don't_ want to happen. In theory, nation-state intelligence services are able to turn on cameras without the LED giving them away, and this is generally considered a Bad Thing(tm) by everyone else.

Unless I'm misreading the request, this doesn't make any sense to me...

**Comment by tetebueno** [comment]
@iskunk, the first sentence is what I'd be trying to achieve. I don't think the second one is related, in fact, based on the theory of the intelligence bad guys turning cameras on without the LED indicating so, I'd be looking for using the same approach to avoid my cameras to reveal they're on while burglars are at home.

@tosiara, I believe the behaviour when camera does not support this would be a simple warning in the log indicatind the option will be ignored.

**Comment by iskunk** [comment]
So what you want is to be able to do like the intelligence boys do :->

Putting aside all issues of technical feasibility, I don't think this is a good feature to have, just on principle. Not only can it be abused, it contravenes the notion that cameras ought not to have software-controllable LEDs at all.

The best that I think can be done here is to have a separate utility (that may be specific to the camera manufacturer/model) to control the LED, if the LED is controllable at all, and use that together with Motion. If your only option is to put a piece of tape over the LED, that's actually a good thing. It means the LED isn't just for show.

**Comment by tetebueno** [comment]
Argument is valid. Will close issue.
