### ISSUE TITLE
stream_port specification clarification

### ISSUE THREAD

**Issue by dorvan** [Motion-Project/motion#408]
Looking to github repo's documentation relative 4.0.1 and using motion 4.0.1

> 
> stream_port
>     Type: Integer
>     Range / Valid values: 0 - 65535
>     Default: 0 (disabled)
> The mini-http server listens to this port for requests (default: 0 = disabled) TCP port on which 
> motion will listen for incoming connects with its webcam server. Note that each camera must  
> have its own unique port number and it must also be different from the control_port number. 
> A good value to select is 8081 for camera 1, 8082 for camera 2, 8083 for camera 3 etc etc. 
> This must be placed in motion.conf and not in a camera config file. 
> 

so: 
**This must be placed in motion.conf and not in a camera config file.** 
Ok, how?

```
camera /cfg/anthillacontroller/motion/cam01.conf
stream_port 7781
camera /cfg/anthillacontroller/motion/cam02.conf
stream_port 7782
camera /cfg/anthillacontroller/motion/cam03.conf
stream_port 7783

```

in this way does not works.

Thanks

**Comment by tosiara** [comment]
Github issue tracker is supposed to post technical issues, not user questions
For help related question please use mail list, not issues tracker
https://lists.sourceforge.net/lists/listinfo/motion-user

**Comment by dorvan** [comment]
@tosiara considering it's an issue on documentation (how it's documented), in the master repo, i think it's related to development, not to user manual. it's a functional verification, following the aligned (???) docs. so, please reopen it, can be a bug. with your and mine availability to discuss on it.

**Comment by dorvan** [comment]
This on a mailing list cause an infinite non-sense thread, not user related...

**Comment by jogu** [comment]
I'd tend to agree that this line is wrong:

https://github.com/Motion-Project/motion/blob/master/motion_guide.html#L4766

I think it should say 'must be placed in camera config file, if there is more than one camera', or something like that.

**Comment by dorvan** [comment]
Thanks @jogu to confirm. Sometimes @tosiara thinks i was crazy or stupid or both....
@tosiara thanks for your work.

**Comment by tosiara** [comment]
Dup https://github.com/Motion-Project/motion/issues/409
