### ISSUE TITLE
Bug: stream_port documentation on master does not permit streams usage on a multi netcam install 

### ISSUE THREAD

**Issue by dorvan** [Motion-Project/motion#409]
also referring to #408 as description, 

There is an error on documentation or on the stream_port function where in webcontrol, checking the configuration, can be defined by camera config, and specifing ports inside the global configuration, cause the last value define to be read, also behind camera specifications.

if this it's related to camera name (usually defined in camera configurations) why in the documentation it's wrote to define it on globals, so related to thread 0? 

Looking to github repo's documentation relative 4.0.1 and using motion 4.0.1

> 
> stream_port
>     Type: Integer
>     Range / Valid values: 0 - 65535
>     Default: 0 (disabled)
> The mini-http server listens to this port for requests (default: 0 = disabled) TCP port on which 
> motion will listen for incoming connects with its webcam server. Note that each camera must  
> have its own unique port number and it must also be different from the control_port number. 
> A good value to select is 8081 for camera 1, 8082 for camera 2, 8083 for camera 3 etc etc. 
> This must be placed in motion.conf and not in a camera config file. 
> 

so: 
**This must be placed in motion.conf and not in a camera config file.** 

Following the file of documentation, how define it in the suggested way, 
without a misconfiguration of camera threads?

```
camera /cfg/anthillacontroller/motion/cam01.conf
stream_port 7781
camera /cfg/anthillacontroller/motion/cam02.conf
stream_port 7782
camera /cfg/anthillacontroller/motion/cam03.conf
stream_port 7783

```
in the documented way, it does not works.

_Is it an error related to documentation?
Is it an error related to a not documented change in 4.0.1?
Is it an error related to thread forking?_

**Comment by dorvan** [comment]
@tosiara @jogu I've added here more informations, @tosiara  do you need something more detailed, here?

**Comment by tosiara** [comment]
Can you create a pull request with the fix?

**Comment by dorvan** [comment]
no, sorry, I'm not a C developer. I can only find fuc*ing bugs, because I test everything I use in scientific way. 

I can help you to find fuc*ing bugs, and reporting **without pressing you opening a bug**, but simply opening an issue **asking** for a confirmation on your side, this looking the complex history of motion project and fragmentation between motion development, documentation and use cases.

I make what can I do, otherwise I can be a simple user....

**Comment by dorvan** [comment]
Only the last camera thread is considered, and last stream port specified (only one) if is defined in camera files all streams results broken.

**Comment by dorvan** [comment]
@tosiara it's a bug on docs, or on software?

**Comment by dorvan** [comment]
@jogu  seems you have to specify stream_port to 0 (zero) on global conf (motion.conf) and camera stream_port on the camera conf file...
