### ISSUE TITLE
how to trigger motion to do a snapshot?

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Motion-Project/motion#413]
I have running motion, to get webcamstream for my Website.
Now i want to trigger motion to save a snapshot on demand.
How can i do it on commandline or with http?

I tried to use fswebcam, but device is busy because motion uses stream. 
Now i could stop motion, make snapshot with fswebcam, start motion. But it should also work with motion alone!?

**Comment by ccrisan** [comment]
You can't do that with motionEye yet. Sorry.

**Comment by tosiara** [comment]
`curl -s http://localhost:8080/0/action/snapshot > /dev/null`

**Comment by tosiara** [comment]
Did that help?

**Comment by ginolhac** [comment]
just because I found it while looking for a way to force a snapshot using python (so `telepot` commanded from telegram)

```
import requests
requests.get('http://localhost:8080/0/action/snapshot')
```
