### ISSUE TITLE
Question:  Can I motion detect on stream and capture on another

### ISSUE THREAD

**Issue by RossWilliamson** [Motion-Project/motion#415]
New to motion and to clarify I'm using motioneye as a front end.  I was wondering if it was possible do motion detect on a low resolution stream and then capture some images on a high resolution stream (in order to get a good view of the perpetrator...)  If there is a forum I should be asking this then please let me know and close this issue.

**Comment by tosiara** [comment]
There is user mail list: https://lists.sourceforge.net/lists/listinfo/motion-user
