### ISSUE TITLE
i have a few question and i have a bug

### ISSUE THREAD

**Issue by igran** [Motion-Project/motion#425]
1. version [4.0.1-1] 
2. installed as a package or compiled from sources [deb-from-github]: 
3. standalone or part of third party [motion]: 
4. video stream source [ net cam (rtsp)]: 
5. hardware [x86]: 
6. operating system [Linux learning-shad 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linu]: 

hi I have some questions and one bug
1) how to enable a permanent record, but to work the motion detector?
bug
when I watch live from minihttpd image has inverted colors. to record normal color. see below

![image](https://user-images.githubusercontent.com/1798337/28430790-76b72ca6-6d8a-11e7-8b39-012a46b974ee.png)

**Comment by tosiara** [comment]
Sorry, I didn't understand neither the question, nor the bug
The picture looks to be a valid setup mode, nothing wrong there

**Comment by igran** [comment]
in default mode motion start record only motion detected/ i want record always and i want motion detection/ now i use option "emulate_motion=yes" for always record but in this mode motion trigger isn't work

**Comment by tosiara** [comment]
You can use timelapse, but it has limitation of only 1 fps
If it is a netcam - you can use ffmpeg to continuously record your stream. No need to bother motion
If it is V4L - you can set up vl4loopback and use ffmpeg to record

Unfortunately, there is no such feature in motion to always record and do motion detection at the same time

**Comment by Mr-Dave** [comment]
Closing.  As @tosiara mentioned, the image is correct as provided under setup mode.  See the [guide](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#setup_mode) for additional details regarding this mode.

**Comment by igran** [comment]
e
