### ISSUE TITLE
warning: unused variable 'curtname'

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#427]
```
gcc -g -O2 -D_THREAD_SAFE  -Wall -DVERSION=\"4.0.1+git280141f\" -Dsysconfdir=\"/usr/local/etc\" -I/usr/include/arm-linux-gnueabihf    -c -o netcam_rtsp.o netcam_rtsp.c
netcam_rtsp.c: In function 'netcam_rtsp_open_context':
netcam_rtsp.c:586:14: warning: unused variable 'curtname' [-Wunused-variable]
         char curtname[16] = "unknown";
              ^
```

**Comment by jogu** [comment]
That probably means that built has ended up without the HAVE_PTHREAD_SETNAME_NP, which is a problem in itself.

https://github.com/Motion-Project/motion/commit/4b76ddaf96ded77a76b0b8a46c33b13f400667a8 will be the cause. Currently we don't have the pthread detection in cmake, I guess maybe you built with cmake?

**Comment by tosiara** [comment]
No, I used traditional `autoreconf -fiv`

**Comment by mterzo** [comment]
Same issue. `ubuntu 16.04`

```
gcc -O2 -D_THREAD_SAFE  -Wall -DVERSION=\"4.0.1+git280141f\" -Dsysconfdir=\"/etc\" -I/usr/include/x86_64-linux-gnu    -c -o netcam_rtsp.o netcam_rtsp.c
netcam_rtsp.c: In function 'netcam_rtsp_open_context':
netcam_rtsp.c:586:14: warning: unused variable 'curtname' [-Wunused-variable]
         char curtname[16] = "unknown";
              ^
```

**Comment by genius3000** [comment]
I see the same on Ubuntu 16.04, I don't know much about 'autoconf' but some Googling gave me an idea. In the commit referenced by @jogu I changed "AC_LINK_IFELSE" to "AC_COMPILE_IFELSE" and it correctly found the function available.  
This may still be incorrect, but it does seem to work.

**Comment by tosiara** [comment]
@genius3000 which source line are you referencing?

**Comment by genius3000** [comment]
configure.ac:116

**Comment by tosiara** [comment]
Created PR: https://github.com/Motion-Project/motion/pull/439

**Comment by tosiara** [comment]
CMAKE still has this issue:
```
[ 54%] Building C object CMakeFiles/motion.dir/netcam_rtsp.c.o
/home/srv/git/motion/netcam_rtsp.c: In function ‘netcam_rtsp_open_context’:
/home/srv/git/motion/netcam_rtsp.c:586:14: warning: unused variable ‘curtname’ [-Wunused-variable]
         char curtname[16] = "unknown";
              ^
```
@slokhorst or @jogu do you have any chance to look into this?

**Comment by tosiara** [comment]
As a result all threads have name "unknown":
```
[1:unknown] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
[1:unknown] [NTC] [VID] vid_start: Opening V4L2 device
[1:unknown] [NTC] [VID] v4l2_start: Using videodevice /dev/video0 and input -1
[0:unknown] [NTC] [STR] http_bindsock: listening on 127.0.0.1 port 8080
[0:unknown] [NTC] [STR] httpd_run: Started motion-httpd server on port 8080 (auth Disabled)
```

**Comment by slokhorst** [comment]
You can do something like this in `CMakeLists.txt`:
```cmake
list(APPEND CMAKE_REQUIRED_DEFINITIONS -D_GNU_SOURCE)
list(APPEND CMAKE_REQUIRED_FLAGS -pthread)
check_symbol_exists("pthread_setname_np" "pthread.h" HAVE_PTHREAD_SETNAME_NP)
```

And then add this to `config.h.in`:
```cmake
#cmakedefine HAVE_PTHREAD_SETNAME_NP
```

Sorry for being absent for a while.. have been quite busy... I'll try to look at the remaining CMake issues soon, too.
