### ISSUE TITLE
Separate options for timelapse and movies

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#43]
Currently single option used for both timlepase and movies format: ffmpeg_video_codec
Is it possible to record timelapse and movie in separate formats? Let say, timlepase in SWF (MPEG2) and movies in MPEG4?

**Comment by tosiara** [comment]
Reopening for review
Would it be worth to introduce separate config options for timelapse and movie codecs?

**Comment by hvdwolf** [comment]
Like mentioned in the #507 issue. 
No, this is not a duplicate (my #507 issue). I was filing a bug report: Something that worked in 3.2.12 AND is still literally mentioned in the 4.0.1 (and above) documentation, does no longer work. By carefully "seducing" me to even better functionality, you change my bug report into a feature request.

Your issue [#43](Separate options for timelapse and movies) is a feature request. Based on all IT standards (and let's take ITIL as big example), an incident (bug) is something different then a change request, and requires different attention.

**Comment by tosiara** [comment]
Can you be exact where it is mentioned on the documentation that timelapse framerate is half of the movies? I didn't find it "literally mentioned" in the link you have provided
It was a bug in 3.2. Now it works as designed - fps should be the same as movie files. If you want old behavior - you can always roll back to an older version

**Comment by hvdwolf** [comment]
I'm sorry. It was the option above that one.
[ffmpeg_timelapse](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#ffmpeg_timelapse)

**Comment by tosiara** [comment]
```
ffmpeg_timelapse
    Type: Boolean
    Range / Valid values: 0 - 2147483647
    Default: 0 (disabled)
Create a timelapse movie saving a picture frame at the interval in seconds set by this parameter. 
```
So this param means that every Nth second motion will put a frame into timelapse file. This is not related to the resulting frame rate at all. File's frame rate is set on timelapse file open and movie's frame rate is used there

**Comment by hvdwolf** [comment]
I do understand that, and when using ffmpeg -i <movie> or using mediainfo <movie>, it does indeed give the framerate like specified in the framerate variable (and always did this). But as I already mentioned, the files are almost 10 times as big. That was what triggered me first.

And to prove my words: When doing a fast and simple conversion like `ffmpeg -i timelapse_movie.avi -c:v mpeg4 -threads 2  -f mp4 other_timlapse_movie.mp4`
it mentions something like `Input #0, avi, from '20170919-zolder-timelapse.avi':
  Metadata:
    encoder         : Lavf56.25.101
  Duration: 01:45:46.00, start: 0.000000, bitrate: 1001 kb/s
    Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1000 kb/s, 5 fps, 5 tbr, 5 tbn, 5 tbc`
This is 6346 seconds. At ½ fps (like specified), this would be 3173 frames.
However, when it is done converting it mentions:
`frame=31730 fps= 24 q=4.7 Lsize=  155071kB time=01:45:46.00 bitrate= 200.2kbits/s`
31730/6346 = 4,996 frames per second (some dropped frames I assume)
Whereas the "old" files were really around 3173 frames.

**Comment by tosiara** [comment]
@Mr-Dave, just to make sure: was the bitrate option also separated?

**Comment by Mr-Dave** [comment]
No it was not duplicated.  If required, users should set up a separate camera configuration file or run a separate instance.

**Comment by tosiara** [comment]
Please elaborate, how can I set up H264 MKV with 1M bitrate for movies and MPG timelapse with 4M bitrate?
