### ISSUE TITLE
Geo location for motion [feature]

### ISSUE THREAD

**Issue by hieronymousch** [Motion-Project/motion#436]
Hi,

I'm running motion on a raspberry zero on my motorcycle as a camera logging device.
It would be nice if I could combine the images with geo location data from a GPS device.
Are you guys planning something like that? Would be handy to participate for Mapillary

Thanks,

J

**Comment by genius3000** [comment]
I'm thinking with the external dependency on GPS info, this might be best handled with a script called by `on_picture_save`  
From [this post](https://photo.stackexchange.com/a/62413) it looks like `exiftool` can be used to geo-tag an image file.

motion is normally used in a static location, I don't foresee GPS capabilities being added to it. Interesting use-case you have though, never would of thought of doing that.

**Comment by tosiara** [comment]
Yes, an external script updating exif would be a solution
No plans yet to implement any kind of exif manipulation by moiton

**Comment by hieronymousch** [comment]
Ok, thanks for your quick reply. I'll have a look at the script option.

⁣Verzonden door TypeApp ​

Op 29 jul. 2017 19:41, om 19:41, tosiara <notifications@github.com> schreef:
