### ISSUE TITLE
On mobiles text inside the WEB UI is to small. w/o zooming not comfortable to use

### ISSUE THREAD

**Issue by telemaxx** [Motion-Project/motion#437]
1. version [x.y.z, hash, other]: Motion 4.0.1+git23f3d5c
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: ARM
6. operating system [Linux (which), FreeBSD, other]: raspbian Jessie

Inside the webui eg:
http://192.168.0.111:8070/1/config/list
the text is to small, when using on a mobilephone.

**Solution:**
I changed webhttpd.c
Direct after line 31:
`"<head><title>Motion "VERSION"</title></head>\n"`
i insert:
`"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=yes\">"`

On my Samsung mobile it looks good now.

[Doku:](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/UsingtheViewport/UsingtheViewport.html)

**Comment by tosiara** [comment]
If you would like to contribute further here is an enhancement filed for web interface: https://github.com/Motion-Project/motion/issues/381

**Comment by jogu** [comment]
@telemaxx This sounds good - if you could submit a pull request please that would be great!
