### ISSUE TITLE
Discussion on some patches in progress

### ISSUE THREAD

**Issue by genius3000** [Motion-Project/motion#442]
I'm opening this issue to track and discuss on what I have in mind for some patches.
#### List
- [x] Web Control shows wrong count of cameras ~~and a duplicated preview~~ when running more than one camera.
- [x] Config write (from Web Control) duplicates the `camera` lines if they were read in as `thread` lines (bug #307).
- [x] Config write (from Web Control) always prints `camera_dir` as enabled and has a default value missing part of the 'default' path (compared to when Makefile installs it).

##### Web Control Cameras Count
This one just requires some added logic for checking if we are single threaded (single file, one cam) or multi-threaded but could be one cam (motion.conf and camera1.conf) or two+ cams. I've got a working test case, just need to simplify the code from little hack fixes.

##### Config write issues
1. The duplicate writing of `camera` lines currently needs a catch in the printing loop, that if the param_name is 'thread' to skip it. This is the most efficient way I can see to handle this right now.
Would a better method of skipping deprecated values be wanted for future use-cases? It could be a flag in the `struct config_param` or even a string pointing to the new value.
2. The `camera_dir` issue needs a catch in the printing loop, similar to the current catch for the camera config files.

I'll put in the Pull Requests as I get each patch to where I'm happy with it.
Feedback is welcome from users, contributors, and especially the Project maintainers.

**Comment by genius3000** [comment]
A new thought on changed/removed/deprecated config options is to create a struct of:
```
name
last_version_used
info
```
Then a list of those and when a config param is read in, fails to find a match, it will check the deprecated list, before logging an "unknown config option". This way we can still give a specific log message on the deprecated option but don't end up with future issues of duplicate writing, etc.

**Comment by genius3000** [comment]
A WIP on the Web Cam count can be seen [here](https://github.com/Motion-Project/motion/compare/master...genius3000:master+web_cam_count).
Fairly simple fix for the count and "Camera" vs "Cameras".

What I'm still looking into is the Preview Section. I had my configuration incorrect in that I left `stream_port` active in `motion.conf` and used the same port in `camera1.conf`. This causes the Preview Section to show that port for both threads 0 and 1.
I'm sure there's a value that can be checked in thread 0 to know if it has an active camera or not to match that `stream_port`.

**Comment by Mr-Dave** [comment]
With respect to the depreciated options, I would like to move forward with the elimination of them as being valid and not replicate the process used for "thread".  With respect specifically to the thread option, I'm in favor of eliminating it now rather than adding lots of code to prevent it from being written twice.   

On the code referenced in the branch to report invalid vs depreciated changes, I have not tested it yet but looks like the desired path forward.  

Can you provide a update on how that branch fits in with your other PR?  e.g.  Should we be evaluating that PR and then looking at the branch change or cancel and create a new one, etc.

**Comment by jogu** [comment]
IMHO completely removing support for options we've decided to rename leads to a lot of puzzlement for users (and hence support queries from them), particularly ones that receive motion via a distro and get a motion upgrade as part of a major OS upgrade. As a user it's really frustrating when software breaks after an OS upgrade as the developers have deemed to make your configuration invalid. (Sometimes the distros write scripts to rewrite config files on upgrade, but I don't think motion is big enough for them to go to the effort of doing that for motion.)

If it's a relatively small amount of work I'd prefer to keep support for the old options and perhaps log a message that they're deprecated (and what they should be replaced by) on startup.

**Comment by Mr-Dave** [comment]
Yes, I see your point.  Definitely need to report them out preferably at a high level like WRN.  There does seem to be some sort of cutoff though perhaps based upon what was included in active distributions.

**Comment by genius3000** [comment]
Thanks for the feedback guys, I've been busy with work the past week but can get back into this now.  
In regards to my existing PR vs. WIP branch, there's still 3/4 commits in the PR that can be reviewed, regardless of thoughts on the other direction. One commit is a fix for some issues I found with the 'camera_dir' option while testing for the 'thread' writing issue. I can always revert the 'thread' fix in favor of the other WIP.  
My WIP branch for deprecated config options currently logs an error at startup of when and why an option was deprecated. It does not use it though. I may be able to allow a way to set the new option in the struct without hitting the same write out issue as we have now. I do understand the reason to keep a renamed option working for a version or two. We just want to accomplish this cleanly and without multiple edge-cases in the code (imo).

**Comment by genius3000** [comment]
I've updated my [WIP branch](https://github.com/Motion-Project/motion/compare/master...genius3000:master+config_deprecated) with the ability to do backwards compatibility. You can set the 'conf_value' and 'copy_func' just like with the active config params. Doing it this way, copies the configured value to the correct config option, without risk of printing out the deprecated option.  

I've tested this successfully with:
- 'thread' -> 'camera' using config_camera
- 'text_dbl' -> 'text_double' using copy_bool
- 'steam_port' -> 'stream_port' using copy_int
- 'on_cam_found' -> 'on_camera_found' using copy_string
- 'test' -> nothing (0) using NULL

@Mr-Dave if this looks like an acceptable direction to go, I'll create a PR for it and rebase my PR #446 removing the 'thread' fix. There will be a conflict with the comment changes overlapping, I could probably remove that and redo it with one that shouldn't conflict.

**Comment by Mr-DaveDev** [comment]
Yes, this looks good.  I'll do some additional testing after the PR/Rebase
