### ISSUE TITLE
how to switch motion detection by timer

### ISSUE THREAD

**Issue by igran** [Motion-Project/motion#448]
1. version [4.0.1-1] 
2. installed as a package or compiled from sources [deb-from-github]: 
3. standalone or part of third party [motion]: 
4. video stream source [ net cam (rtsp)]: 
5. hardware [x86]: 
6. operating system [Linux learning-shad 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux]:
I need to turn off the detector during working hours and turn on when the work day is over.
I have 2 solutions
1) turn off the domain using cron
2) use http api.
If there are better methods than mine, please tell about them.

**Comment by tosiara** [comment]
If you are asking how to turn off motion detection by timer, then yes, you can use a script with http api command and run it using cron
