### ISSUE TITLE
Rasberry PI installing assumes the system is debian based.

### ISSUE THREAD

**Issue by cyford** [Motion-Project/motion#469]
1. version [x.y.z, hash, other]: 
4.0.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
conpied as source
3. standalone or part of third party [motion, MotionEyeOS, other]: 
standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
having issues with rtsp as my main issue - as motion dies/crashes if i attempt to use it..      however motion is looking for ffmpeg debian dependencies so its not recognizing ffMPEG as installed

5. hardware [x86, ARM, other]:  arm/ rasbery pi 3
6. operating system [Linux (which), FreeBSD, other]:  Centos

configure: error: Required ffmpeg packages 'libavutil-dev libavformat-dev libavcodec-dev libswscale-dev' were not found.  Please check motion_guide.html and install necessary dependencies or use the '--without-ffmpeg' configuration option.

ofc i also tried :  ./configure --with-ffmpeg=/usr/lib/arm-linux-gnueabihf 
same issue

**Comment by genius3000** [comment]
Found this [post](https://www.centos.org/forums/viewtopic.php?t=58548) that may help. Essentially make sure you have pkg-config installed and do (before configure):
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```
