### ISSUE TITLE
"Motion Guide" link from https://motion-project.github.io is not working

### ISSUE THREAD

**Issue by markwest1972** [Motion-Project/motion#478]
Clicking on this link results in a redirect to http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html.

The only text displayed is "No definition found for Table headers".

Tested in Safari and Firefox.

**Comment by Mr-Dave** [comment]
This appears to be something associated with github and it is now functional.

**Comment by and712** [comment]
Also not working for me

**Comment by tosiara** [comment]
This is problem with the online render service, not the motion guide:
http://htmlpreview.github.io/?https://www.w3schools.com/

https://github.com/htmlpreview/htmlpreview.github.com/issues/16#issuecomment-191125674

**Comment by Mr-Dave** [comment]
As a additional resource, the guide is installed with Motion as /usr/share/doc/motion/motion_guide.html  (assuming a standard apt-get install)

**Comment by Mr-Dave** [comment]
Closing this as it seems resolved by the other application that renders the page or pressing refresh
