### ISSUE TITLE
Motion for IPV6

### ISSUE THREAD

**Issue by alfinsyuqra** [Motion-Project/motion#486]
dear all , 

my device is raspberry pi b with wheezy OS , 
and now i have installed motion service using :
#apt-get install motion 
 and i made it , it's work great but only on IPV4 network , actually i need the motion to work on IPV6 network , and we know  motion version 3.2.12 not support for IPV6 network , 

what is the solution for my problem sir , i know the motion version.4.0.0 or 4.1.0 is support for IPV6 but it's for jessi OS , 
i try to force install the motion version 4.0.0 on my pi , but i get some warning like this  :

(i have renamed the pi_jessie_motion_4.0-1_armhf.deb to be motion.deb before)
-------------------------------------------------------
root@raspberrypi:/home/pi# sudo gdebi motion.deb 
 package lists... Done
Building dependency tree
Reading state information... Done
Building data structures... Done
Building data structures... Done
This package is uninstallable
Dependency is not satisfiable: libavcodec56 (>= 6:11~beta1)|libavcodec-extra-56                                                                                         (>= 6:11.7)

root@raspberrypi:/home/pi# 

so what is the best way for me now sir?
 
so much appreciated for help ,

thank's
regard 
alfin

**Comment by Mr-Dave** [comment]
It is probably better to discuss this via the IRC or mailing list as described in the [contributing guide](https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md).

**Comment by alfinsyuqra** [comment]
ok sir , i will see you there
