### ISSUE TITLE
Elimination of Developer Warnings

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#489]
Since the release of 4.0 some of the changes implemented have resulted in new developer compiler warnings that were not detected during the pulls/merges.  This issue is to track the removal of these warnings so we can get back to a "compile with zero warnings state"  

The particular commits include:  

1. Image flip #390 
2. jpeg utils #455 
3. config #446 
4. privacy mask #343 
 
Details of the warning messages can be viewed in the [travis log](https://travis-ci.org/Motion-Project/motion/jobs/271248983) or by using the --with-developer-flags.

Once these warnings are resolved, a additional change for this issue will be to revise the configure script to treat all warnings as errors so they can be observed prior to pulls being merged.

**Comment by genius3000** [comment]
I see your current PR fixes what I introduced in conf.c, thanks for that. Just out of curiosity (and my learning), are the cast alignment warnings not really worth worrying about (I see you removed it from the flags in the PR as well)?

**Comment by Mr-Dave** [comment]
I wanted to learn about the cast warnings as well and welcome comments from the community on its value.   

From what I was able to find, the warnings are indicating that the compiler needed to take an extra 3 to 7 bytes to get it aligned correctly for the calculation.  This warning was really important back when I worked on a VAX or if working on an embedded system but today even with the PI's we are not rationing memory to this degree.   

The preferred approach of course is to simply eliminate the need to cast anything but I'm not sure that would be feasible.  If it is a easy fix, I'd put back in the warning check but if it means refactoring the code and making it more complex/convoluted just to eliminate the warning with no real gain, then I think our time is better spent elsewhere.

Again, I invite the community to comment.

**Comment by iskunk** [comment]
Incidentally, in my iskunk-wip branch I have a rewrite of the privacy-mask code to use unions instead of casting (which is the pedantically-correct way to do this), as part of #364. Gives a performance improvement and gets rid of the warnings to boot.

**Comment by Mr-Dave** [comment]
Closing issue.  If time permits, may address the align at a future date.
