### ISSUE TITLE
Pixel formats need permanent ID instead of current array order index

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#494]
Here: https://github.com/Motion-Project/motion/blob/master/netcam_rtsp.c#L535

Should rather use these macros:
```
V4L2_PIX_FMT_H264
V4L2_PIX_FMT_MJPEG
```
I couldn't make an easy fix because those macros are not globally defined in a header, but rather initialized in the `video_v4l2.c`. So leaving this for the author of the last change @Mr-Dave

**Comment by Mr-Dave** [comment]
Those are v4l2 options and we are using ffmpeg.  Is there documentation from ffmpeg that these are the correct options?  From what was observed when this option was created, the current method is correct.

**Comment by tosiara** [comment]
I mean, this line
```
 if (netcam->cnt->conf.v4l2_palette == 8)
```
should look like
```
 if (netcam->cnt->conf.v4l2_palette == V4L2_PIX_FMT_MJPEG)
```

**Comment by Mr-Dave** [comment]
The "8" is our Motion numbering scheme and would not correlate with the v4l2 values.  The fundamental issue is actually much broader than just section of code.  It would be part of a general clean up of the variables, names, options and acceptable values.

**Comment by tosiara** [comment]
Ah, so "8" is not a number behind the macros, but just an array index of all the supported pixel formats?

**Comment by Mr-Dave** [comment]
Yes, that numbering is all dependent upon the sequence as described [here](https://github.com/Motion-Project/motion/blob/5a03718a4b0359bd81d09036ef066cd62a562ea0/video_v4l2.c#L430) which should not be confused with the sequence that is [here](https://github.com/Motion-Project/motion/blob/5a03718a4b0359bd81d09036ef066cd62a562ea0/motion.h#L106)
