### ISSUE TITLE
Incomplete frames with active despeckle filter

### ISSUE THREAD

**Issue by 0x00** [Motion-Project/motion#504]
1. version 3.2.12+git20140228
2. installed as a package
3. standalone
4. net cam (file and http)
5. hardware arm (raspberry pi)
6. Raspbian GNU/Linux 8.0 (jessie)

I have a very similar problem related to http://www.lavrsen.dk/foswiki/bin/view/Motion/SupportQuestion2009x10x15x234431 with incomplete frames. 

But when I disable the despeckle filter, the problem is gone. 
Only in complete dark places I receive still incomplete frames.

**Comment by Mr-Dave** [comment]
You will first need to upgrade to a supported version.  Link to download deb [here](https://github.com/Motion-Project/motion/releases/download/release-4.0.1/pi_jessie_motion_4.0.1-1_armhf.deb).  Instructions for upgrading are in the [guide](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Install_Deb)  

If the problem persists, we'd need to see the configuration/log, etc as described in the [contributing guide](https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md)

**Comment by 0x00** [comment]
I'd upgraded and the problem was gone. Thank you very much.
