### ISSUE TITLE
grey scale video

### ISSUE THREAD

**Issue by hannesa2** [Motion-Project/motion#506]
1. 4.0.0
2. installed as a package
3. standalone
4. video stream source CSI (https://eckstein-shop.de/Waveshare-Raspberry-Pi-Zero-Zero-W-V13-Camera-Ribbon-Cable-15cm-Bandkabel?curr=EUR&gclid=EAIaIQobChMIqsKRiYOu1gIVnYeyCh354A0vEAQYBCABEgIlhPD_BwE)
5. hardware ARM
6. Raspberian Linux

I want to have a bandwidth saving greyscale video output and I already asked via mailing list.
Thank you, I got a fast response from @tosiara 

> There is no such option. Should be an easy source code change to allow it

Yes I will try (but I've less C experience) but I'm lost. Please can someone point me to right places where I have to change something (and what)

**Comment by tosiara** [comment]
You can start with this:
Checkout this PR locally: https://github.com/Motion-Project/motion/pull/454
Look for a function called `scale_half_yuv420p`. You can modify it to save only gray channel (luma). Optionally you can comment out the scale down if you don't need it.
At the end you should get a secondary stream with gray color space and/or lower resolution. You should save a lot of internet bandwidth this way

I have had an idea to implement it, but unfortunately had no time yet. If you keep your changes in a branch, we could merge it upstream in future

**Comment by hannesa2** [comment]
To be honest, I've no idea, how to do so but I found out in v4.1 there is 
`palette_array[20].v4l2id = V4L2_PIX_FMT_GREY;` 
in `static void v4l2_palette_init(palette_item *palette_array){` in file `video_v4l2.c`
does it help to reduce data to be transfer during live stream ?

**Comment by Mr-Dave** [comment]
The changing of the palette to grey will not reduce the bandwidth of the stream.  Currently the only method to reduce the stream is using the `substream_port` option.

If you are interested in adjusting the code to do this, it would be within the `picture.c` module and changing the functions which are doing the JPG compression.  I believe the functions already exist and were left in the module specifically for this issue.  I just haven't found time to work through all the other required revisions to implement those functions and close this issue.
