### ISSUE TITLE
Motion Log files and Configuration requests

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#509]
We need to update contribution guide and create a wiki article to instruct users how to remove all the passwords from config and log files

**Comment by tosiara** [comment]
Potential issues are:

1. Camera username and password stored in config: all them are in plain text
netcam_url http://camera/stream?user=admin&password=admin
netcam_url http://admin:admin@camera/stream
netcam_userpass admin:admin
stream_authentication admin:admin
webcontrol_authentication admin:admin
database_password admin

2. Public IP address or domain name as part of netcam url: may be attacked, unauthorized access
netcam_url http://camera.publicdomain.com/stream

3. Log containing netcam url: it may leak credentials as part of url or base64 encoded
Network Camera thread starting... for url (http://camera/stream?user=admin&password=admin)
Authorization: Basic YWRtaW46YWRtaW4=

4. Other private info may appear in log: server headers, user path, script parameters, etc

To verify, grep files before uploading:
```
grep -i "netcam_url\|netcam_userpass\|stream_authentication\|webcontrol_authentication\|database_password\|Network Camera\|Authorization: Basic\|http://\|https://\|ftp://\|password\|target_dir\|on_picture_save\|on_movie_end" motion.log motion.conf
```


Please replace all sensitive strings with `***removed***`

**Comment by tosiara** [comment]
Created a wiki article: https://github.com/Motion-Project/motion/wiki/Privacy

**Comment by tosiara** [comment]
https://github.com/Motion-Project/motion/pull/510

**Comment by Mr-Dave** [comment]
Revising the title of this issue to address underlying problem.  

1. Need to not put any of this to a log file to begin with 

2. Need to have a log level so all of the other configuration parameters are printed so we never will ask for a configuration file.
