### ISSUE TITLE
Cant delete no motion (freeze) frames in video

### ISSUE THREAD

**Issue by s7e7v7e7n7** [Motion-Project/motion#511]
Hi, I'm not sure if this is a problem. But I could not find a solution. I will ask for your help.

Time counting continues in the no motion frames on the recording. Like this timeline;

0:00motionstart(record)..........0:15nomotion(still record one frames)...........0:35motionstart(record continue)..........0:45event end record stop /

(In the above example, there is a 20 second freeze one frame in mp4 video) 

how can i delete no motion frames (freeze frames) in video ? 

I am using rpi3 + v2 pi cam

I hope you understand. Thank you.

**Comment by jasaw** [comment]
Which version of motion software are you running?

I think you're talking about "no motion gap" in the recorded video. "no motion gaps" are already cut out of the recorded video in latest master. Please try the latest master.

**Comment by s7e7v7e7n7** [comment]
actually i use motion Version 4.0

Are you talking about "event_gap"?

Now im using "event_gap 25" 

but when i setup "event_gap 0" , this time there are too many video files.

Do you have any a suggestion for this?

**Comment by jasaw** [comment]
Yes, please try the latest master. A few video recording issues have been fix in latest master.

**Comment by s7e7v7e7n7** [comment]
I think Version 4.0 is latest. and i use this version... I do not know maybe this problem is my raspberry device.

Anyway, thank you very much for your help and interest.

**Comment by tosiara** [comment]
Is it still an issue?

**Comment by s7e7v7e7n7** [comment]
yes its continue... i cant find any solution and i use last version

**Comment by tosiara** [comment]
Can you upload your motion log to gist to check if you are using the latest version?

**Comment by Mr-Dave** [comment]
Closing for lack of follow up.
