### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by juxorevo** [Motion-Project/motion#512]
Step 5/7 : RUN dpkg -i --force-depends pi_stretch_motion_4.0.1-1_armhf.deb
 ---> Running in 1028f511dfa8
dpkg: error processing archive pi_stretch_motion_4.0.1-1_armhf.deb (--install):
 package architecture (armhf) does not match system (armel)
Errors were encountered while processing:
 pi_stretch_motion_4.0.1-1_armhf.deb

I can't install in docker image (stretch) the motion project.

Do you have a docker image ?

**Comment by tosiara** [comment]
There is no docker image in the official releases https://github.com/Motion-Project/motion/releases
