### ISSUE TITLE
Video and Still Image Address

### ISSUE THREAD

**Issue by sroettgermann** [Motion-Project/motion#518]
1. version [x.y.z, hash, other]: 
motion Version 4.0.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
git
3. standalone or part of third party [motion, MotionEyeOS, other]: 
motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
V4L usb
5. hardware [x86, ARM, other]: 
ARM
6. operating system [Linux (which), FreeBSD, other]: 
raspbian

Hi there. 
Where can I find the specific address for live video and still images to access from another machine to the machine where motion is running. 
What I want: access from one Raspberry Pi to another Raspberry Pi where motion is installed with a USB webcam plugged in. I hope it is clear what I want to know.

**Comment by genius3000** [comment]
To access the live stream from motion you'll need the port specified in the config (`stream_port`) and the IP address of the host (run `ip a`). You can verify that motion is steaming by running `ss -tlnp` and look for either the process motion or the port configured as stream_port.

**Comment by sroettgermann** [comment]
Okay. That's not the problem. I can stream the video via http://IPOFTHERASPBERRYPI:8081, but I want to devide between video and still image? How is that possible? Is there a separate port for this?

**Comment by genius3000** [comment]
Motion streams MJPEG, there is no still image (or snapshot) available through a HTTPd interface, as far as I know. If you're trying to get snapshots saved to a remote host you could use ffmpeg and grab just one frame from the stream.

**Comment by sroettgermann** [comment]
Ah okay. Thats something I didn't know already. Thank you!
