### ISSUE TITLE
OpenCV Support

### ISSUE THREAD

**Issue by TannerS** [Motion-Project/motion#523]
Does this library support OpenCV to detect motion? Well i guess I should say motion tracking and/or motion detection with OpenCV?

**Comment by iskunk** [comment]
Nope! Motion uses its own home-rolled algorithms for motion detection.

We currently don't have any kind of plug-in architecture that would allow building and enabling some sort of "OpenCV module," either.

**Comment by TannerS** [comment]
Thanks for the reply. I have a few more questions, should I ask here or is
there somewhere else I can ask?

I am interested in a few features and wish to get more details about

**Comment by iskunk** [comment]
For more free-ranging discussions, there's a mailing list: https://lists.sourceforge.net/lists/listinfo/motion-user

Here, it's usually specific stuff that gets addressed.

**Comment by Mr-Dave** [comment]
Closing Issue.

**Comment by tosiara** [comment]
For OpenCV related questions see mail list archive, there were similar questions in the past: https://sourceforge.net/p/motion/mailman/motion-user/. Also you can check: https://github.com/sgjava/install-opencv

**Comment by Patrickyp** [comment]
I have a different question.  I would like to stream video over network using Motion and process the resulting frames using Opencv.  Is that possible or no?
