### ISSUE TITLE
logging for auth login attempts against live stream

### ISSUE THREAD

**Issue by Salzorian** [Motion-Project/motion#525]
log the remote IP and port of any connections against the motion live stream server.

Former project owner(?) already created a patch for this.
--> http://www.lavrsen.dk/foswiki/bin/view/Motion/LoggingAgainstMotionStreamAuthPatch

This also is necessary to use tools like fail2ban i guess.

**Comment by Mr-Dave** [comment]
This issue has already been addressed and closed via #348 and PR #434.

**Comment by Salzorian** [comment]
Sry, i did not realized the issue already exist. (googled a lot)
Can you estimate a releasedate for a motion version including this feature?
(so i can get it through apd-get on my pi)
