### ISSUE TITLE
New Release Needed

### ISSUE THREAD

**Issue by nfettinger** [Motion-Project/motion#529]
The last official release was over a year ago. An effort should be made to wrap up existing features and perform regression testing for a new release tag.

**Comment by rawtaz** [comment]
@Mr-Dave Why was this closed without any reply? What's your take on what @nfettinger suggested?

**Comment by Mr-Dave** [comment]
Issues written as this one primarily attract "Yes, you should do that" responses which are actually counter productive to actually doing the activities that make a release happen.  As it stands, if you review the commit frequency and notes you should see that I am moving towards getting updated release out.
