### ISSUE TITLE
VMware Ubuntu 16.04 Run Error:"Watchdog timeout, trying to do a graceful restart!"

### ISSUE THREAD

**Issue by Liang728829** [Motion-Project/motion#532]
The log: [motion.log](https://github.com/Motion-Project/motion/files/1436693/motion.log)

![install function](https://user-images.githubusercontent.com/27732935/32313147-4fd0b18a-bfdc-11e7-92d0-8d6592581e20.PNG)

When I run motion, there is an error: Watchdog Timeout. Are using the default parameters, without any changes
1. version : motion-master latest code of November 1, 2017
2. installed as a package or compiled from sources: git clone sources code
3. standalone or part of third party : motion
4. video stream source : V4L USB (Laptop itself camera)
5. hardware : x64 linux
6. operating system [Linux (which)]: Used VMware to run the Ubuntu system

**Comment by Mr-Dave** [comment]
1.  Can you ensure that the camera is functional using a different application such as vlc, ffplay or ffmpeg?
2.  If the camera is functional, change the `log_level` to `9` and provide that log?

**Comment by Liang728829** [comment]
I tried again, it may be my camera problem, ffmpeg can not capture the camera's data, the generated file is empty.Thank U
