### ISSUE TITLE
Release 4.1

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#533]
The following is a short checklist of items for the next release (4.1)  Current enhancements listed on the project issue page will be addressed in a later release.  (i.e. Issues with numbers less than 532)

- [x] Document Known Issues :  Issues #363, #366, #521 to be listed as known issues for addressing in later release.
- [x] Determine included enhancements
- [x] Update CHANGELOG.
- [x] Determine if Debian Issue Log indicates additional bugs to address.
- [x] motion_guide.html update
- [x] motion.1 update
- [x] Revise year in the Copyright printed via `motion -h`
- [x] Ubuntu 17.10 Testing/Updates
- [x] FreeBSD 11.1 Testing/Updates
- [x] Raspbian Testing Pi Cam, v4l2, rtsp
- [x]  Release notes
- [x] Base System builds (Ubuntu 14+, Debian, Raspbian, arm64, FreeBSD)
- [x] Validate motion-packaging repository/script
- [x] Validate no git dependencies in package.
- [x] Incorporate user testing bugs reported.
- [x] Build packages

All users are encouraged to perform testing on their own systems and report issues

**Comment by tosiara** [comment]
Great! I will now merge the latest master into my tree and run few smoke tests on my ARM test lab

**Comment by tosiara** [comment]
One thing, the compilation output has changed and looks a bit different. Is that by design?
```
$ make
Welcome to the setup procedure for Motion, the motion detection daemon! If you get
error messages during this procedure, please report them to the mailing list. The
Motion Guide contains all information you should need to get Motion up and running.

Version: 4.0.1+gitfbb3c2e
Platform: Linux (if this is incorrect, please read README.FreeBSD)

Generating dependencies, please wait...

Compiling Motion object files...
--------------------------------------------------------------------------------
-e      Compiling motion.c into motion.o...
-e      Compiling logger.c into logger.o...
-e      Compiling conf.c into conf.o...
-e      Compiling draw.c into draw.o...
-e      Compiling jpegutils.c into jpegutils.o...
-e      Compiling video_loopback.c into video_loopback.o...
-e      Compiling video_v4l2.c into video_v4l2.o...
-e      Compiling video_common.c into video_common.o...
-e      Compiling video_bktr.c into video_bktr.o...
-e      Compiling netcam.c into netcam.o...
-e      Compiling netcam_http.c into netcam_http.o...
-e      Compiling netcam_ftp.c into netcam_ftp.o...
-e      Compiling netcam_jpeg.c into netcam_jpeg.o...
-e      Compiling netcam_wget.c into netcam_wget.o...
-e      Compiling track.c into track.o...
-e      Compiling alg.c into alg.o...
-e      Compiling event.c into event.o...
-e      Compiling picture.c into picture.o...
-e      Compiling rotate.c into rotate.o...
-e      Compiling webhttpd.c into webhttpd.o...
-e      Compiling stream.c into stream.o...
-e      Compiling md5.c into md5.o...
-e      Compiling netcam_rtsp.c into netcam_rtsp.o...
-e      Compiling ffmpeg.c into ffmpeg.o...
--------------------------------------------------------------------------------
Motion object files compiled.

Linking Motion...
--------------------------------------------------------------------------------
gcc  -o motion motion.o logger.o conf.o draw.o jpegutils.o video_loopback.o video_v4l2.o video_common.o video_bktr.o netcam.o netcam_http.o netcam_ftp.o netcam_jpeg.o netcam_wget.o track.o alg.o event.o picture.o rotate.o webhttpd.o stream.o md5.o netcam_rtsp.o ffmpeg.o  -lm  -pthread -ljpeg   -lavutil-ffmpeg -lavformat-ffmpeg -lavcodec-ffmpeg -lswscale-ffmpeg -lavdevice-ffmpeg
--------------------------------------------------------------------------------
Motion has been linked.

Build complete, run "make install" to install Motion!
```

Is there a way to get "old-style" verbose output?

**Comment by Mr-Dave** [comment]
This was the out of tree build change.  We can see about making the output more verbose after the release.  

Have any functional deficiencies been observed?  

I am looking at merging the changelog PR in the next day or so to make the release official and would like to get the community feedback prior to that merge.

**Comment by tosiara** [comment]
I haven't observed any issues. ARM with extpipe runs smooth as usual
