### ISSUE TITLE
Unable to login to motion when using Digest_auth behind proxy

### ISSUE THREAD

**Issue by amanusk** [Motion-Project/motion#540]
1. version fbb3c2e0222301dbc399c8eb0add4412572cee4c
2. compiled from sources
3. standalone 
4. USB net cam
5. x86
6. Ubuntu 16.04 

[Gist of log and conf] (https://gist.github.com/amanusk/d030da44431a016d0bb70dad0168a118)

Description: 
I have motion setup behind an apache web server. 
Set up like this:
```
<VirtualHost *:443>
    DocumentRoot "/var/www/html"
    ServerName myserver.com

    ProxyPass /camera http://localhost:7070
    ProxyPassReverse /camera http://localhost:7070

</VirtualHost>
```
When using digest_auth (Authentication method 2) I am only able to login when accessing the port directly on the local network.   
Using the same password and username, I am able to login when accessing the server on say:
10.0.0.3:7070 (server IP on local network)

And unable when accessing:
https://myserver.com/camera

The problem does not exist when using plain text authetication (method 1). With plain text auth, I can access from both networks.

**Comment by tosiara** [comment]
Confirmed. I'm looking into it

**Comment by tosiara** [comment]
So far I suspect that the issue is caused by Apache closing the upstream connection. With the new connection motion expects a new nonce to be sent, but your browser sends the one from the previous request

**Comment by Mr-Dave** [comment]
Just to be clear.  Within Motion, I am pretty sure the webcontrol port does not support digest authentication.  That enhancement was only added to the stream port when the prior developers implemented it.

**Comment by amanusk** [comment]
@Mr-Dave I am referring to the stream port

**Comment by tosiara** [comment]
Yes, I have been testing only stream, not webcontrol

**Comment by Mr-Dave** [comment]
Since I do not send the streams external or run apache, someone will need to write up and submit a "How to" guide on setting this up.  I'd prefer that it be written so we can incorporate it into either the guide or as part of the FAQ.  Being especially explicit on what security risks it poses and ways to mitigate those risks.

**Comment by amanusk** [comment]
I can try creating such a write-up.
