### ISSUE TITLE
crop/roi before processing&streaming

### ISSUE THREAD

**Issue by pabloandresm** [Motion-Project/motion#543]
Hi,

I was wondering if there is a way to crop the image before processing and streaming.

An option like “-roi x,y,w,h” (raspivid), or the “crop=w:h:x:y” (mplayer).

I am asking this for projects like a digital door’s peep hole, when we don’t need the exterior of the image.

I know you can do masks for the motion detection, but a crop would allow for example to crop out a 640x480 size image to stream, from a 1280x1024 original size, reducing the streaming bandwidth needs.

Thanks

**Comment by Mr-Dave** [comment]
There is no way to do this within the application and I do not anticipate that would be added.  The current functionality does provide for a substream which lowers the stream bandwidth by 50%.   

If required, for your application, this could be accomplished via ffmpeg and a loopback device as described in the guide for processing static files in the basic setup section of the [Motion guide](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Basic_Setup).
