### ISSUE TITLE
4.1 on Ubuntu 14.04 - bad version number

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#546]
Configure on Ubuntu 14.04.5 LTS:
```
   **************************
      Configure status       
      motion 4.1+git
   **************************
```
$ ./version.sh:
```
fatal: unknown date format format:%Y%m%d
```
$ git --version:
```
git version 1.9.1
```

**Comment by Mr-Dave** [comment]
This was recognized in the testing.   For those on 14.04 who build their own, it would just report unknown.  Those with recent distros, it will report a date which is much easier to trace.

**Comment by tosiara** [comment]
On 14.04 it isn't returning 'uknown', it is just "4.1":
```
$ ./version.sh 
fatal: unknown date format format:%Y%m%d
4.1+git
```

**Comment by Mr-Dave** [comment]
I'll push a change on it.  Didn't know how much effort to put into the old version.
