### ISSUE TITLE
Motion build failure with musl toolchain (i586-buildroot-linux-musl)

### ISSUE THREAD

**Issue by ffontaine** [Motion-Project/motion#550]
1. version [x.y.z, hash, other]: 4.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: sources
3. standalone or part of third party [motion, MotionEyeOS, other]: other (buildroot)
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: none
5. hardware [x86, ARM, other]:  x86
6. operating system [Linux (which), FreeBSD, other]: Linux (with i586-buildroot-linux-musl toolchain)

Motion has been integrated in buildroot. When updating from version 4.0.1 to 4.1, autobuilder returned the following error when building motion with musl toolchain which as pthread_setname_np but not pthread_getname_np: http://autobuild.buildroot.net/results/65534775c5977e2424c5f5c63c46f9d0f39d7e1b/motion-release-4.1/config.log

A patch has been sent and applied to buildroot to fix this issue: https://patchwork.ozlabs.org/patch/840967. This buildroot patch is composed of two motion patches.

First patch has been sent upstream (PR #549) and consists of checking "correctly" the availability of pthread_setname_np through AC_LINK_IFELSE with pthread in LIBS instead of using AC_COMPILE_IFELSE (which always succeeds even if pthread_getname_np is not there)

Second patch will be sent if first one is accepted. This second patch add a check to pthread_getname_np using AC_LINK_IFELSE.

**Comment by Mr-Dave** [comment]
I would like to add this environment/distro into the test cycle in order to catch these items in all future changes but I do not have any experience with buildroot.  Do you know if there is a docker image that can be used to emulate the buildroot and possibly the commands to get the required libraries?  Anything to get me started on the changes to the travis.yml would be helpful.

With respect to the second patch, the preference would be to have the change in logger.c use the util function.  I had on my mental list of things to do finding all these calls and consolidating them to use the util function but now that a change is required, it would be best to just do it now.

**Comment by ffontaine** [comment]
OK, I have updated the second patch (see PR #549).

**Comment by Mr-Dave** [comment]
As someone who has used musl, is any quick way you know of to resolve the determination of strerror_r XSI vs GNU [here](https://github.com/Motion-Project/motion/blob/ccbe2f59272b029b49a106224e8bde7114da0814/motion.h#L104)?  It seems musl has decided to not provide a variable that can be tested and the wrong variant strerror_r is being picked up in [logger.c](https://github.com/Motion-Project/motion/blob/ccbe2f59272b029b49a106224e8bde7114da0814/logger.c#L256)

**Comment by ffontaine** [comment]
Indeed, musl only provides the XSI function. I would suggest to remove the 3 lines from motion.h and to check for the XSI strerror_r signature in configure.ac. I can update the PR with a new commit so you can review it. The main issue is that I must remove AC_GNU_SOURCE from configure.ac otherwise _GNU_SOURCE is defined for the whole configure tests. So I have to add it back to pthread_setname_np and pthread_getname_np checks as those functions depends on _GNU_SOURCE.

**Comment by Mr-Dave** [comment]
I don't think that I'm ready to go to the extent of the PR at the moment with the project.  It seems to be cascading into something much bigger and at the moment, there are lots of other items that need my attention.  

I would think that we should just be able to add in the test for the XSI strerror_r into configure.ac and remove the existing If/defines in the motion.h

**Comment by Mr-Dave** [comment]
I put out PR #568  which demonstrates the resolution.  

For the Ubuntu builds, Motion uses the gnu variant of strerror_r.  This can be seen in the travis build logs.  Here is the link to the Ubuntu 17.10 build [log](https://travis-ci.org/Motion-Project/motion/jobs/313783975).  Line 2163 indicates the XSI is set to "no" which is what we want. 

For Alpine (which I've read uses musl), this is link to the build [log](https://travis-ci.org/Motion-Project/motion/jobs/313783976).  Line 642 indicates the XSI is set to "yes" and further down also indicates it now compiles with no warnings or errors.  

This PR has also been checked independently under FreeBSD and the Apple travis build log which designates using the XSI variant of strerror as we want.
