### ISSUE TITLE
Perform auto-brightness using V4L2_CID_EXPOSURE_ABSOLUTE

### ISSUE THREAD

**Issue by bmerry** [Motion-Project/motion#552]
1. version [x.y.z, hash, other]: release-4.1-1-gccbe2f5
2. installed as a package or compiled from sources [deb, rpm, git, other]: from source
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: USB webcam (Logitech C120)
5. hardware [x86, ARM, other]: Raspberry Pi
6. operating system [Linux (which), FreeBSD, other]: Raspbian

On my camera (Logitech C120) setting the v4l2 brightness control just affects a digital gain, but does not affect exposure time, so it doesn't prevent CCD saturation. It also has poor built-in auto-exposure, which oversaturates in sunlight, which is why I want to use motion to control the exposure.

I have a [commit](https://github.com/bmerry/motion/commit/4191cb107117fecee99ea04daa32b6da9605a95a) on my fork that implements this, but by replacing the existing auto-brightness logic. I don't know if this will produce good results for everyone or if there needs to be an additional switch so that one can opt in/out of this alternative approach.

**Comment by Mr-Dave** [comment]
What if we were to use the autobright parameter to determine which variables are impacted?  e.g.  The current parameter is a simple `on/off`  The proposal would be to have functionality to specify the controls impacted such as the following options.  

`auto_brightness off`
`auto_brightness brightness`
`auto_brightness brightness,gain`
`auto_brightness exposure` 
`auto_brightness exposure=-1,brightness` 

Where Motion would use the parameters listed and inverse the effect if the user specifies `=-1` for the option.  The user could then mix and match parameters.  We'd parse based upon the `,` and search for the `=-1` to see whether to inverse the change.

(I would also ask the community to comment on whether this would be too complex of a parameter specification method for general users to understand even if described in the guide.)

**Comment by bmerry** [comment]
This certainly sounds flexible. What exactly would it mean to have more than one setting? You'd distribute the adjustments across multiple settings? Maybe someone will need it, but it sounds like it creates a very big search space for the user.

I'm still not totally happy with the auto-tuning in my setup: I had to widen the hysteresis window a *lot* and also adjust the other compile-time constants, and even so it tends to oscillate at certain light levels. To make this solution work for everyone I think it would be necessary to expose the autobrightness knobs as config.

I also suspect I could get better results with a different transfer function than 255 - x (e.g. maybe it needs to be some sort of exponential to account for linear- vs log-scale). Possibly instead of `=-1` one could put the name of a predefined transfer function on the right of the `=`, which would allow more transfer functions to be added in future.

**Comment by Mr-Dave** [comment]
The multiple setting would function like the existing routine that adjusts both the brightness as well as the gain.  Not sure how appropriate that is but I was thinking to at least duplicate the existing functionality.  

Your idea of a set of predefined functions  sounds much better and I'll use that instead of just the `-1'.

Finally, on adding an additional configuration option for turning the exposure to manual.  I'm contemplating just adding functionality to allow the user to change every single control found on the camera via a new single `v4l2_control_parms` option.  That should then be able to address #551, #582 as well as be used in this issue.
