### ISSUE TITLE
Motion 4.1-1 continues to retrieve images from netcams while in pause mode.

### ISSUE THREAD

**Issue by picameratk** [Motion-Project/motion#553]
Motion 4.1-1 continues to retrieve images from netcams while in pause mode.  I would like to suggest that when motion is paused the cameras are not accessed and a significant load on wifi is eliminated when not needed,  
1. Version - pi_jessie_motion_4.1-1_armhf.deb 
2. Installed as a package. 
3. Standalone. 
4. Only netcams 
5. Raspberry Pi 3 - ARM 
6. Linux motionpi3 4.9.61-v7+ #1049 SMP Fri Nov 10 15:32:51 GMT 2017 armv7l GNU/Linux

**Comment by tosiara** [comment]
The "pause" function is suppose to only pause the motion detection, not the entire process. As there are other things that keep working during motion is paused: live stream, snapshot, timelapse, etc

If you want to "pause the entire process" why not simply kill motion and restart it later when you need?

**Comment by picameratk** [comment]
I knew someone chose the word pause, instead of stop, for a good reason and your first paragraph was very informative.

I would like to be able to STOP the motion detection process using the web interface of motion rather than killing the motion process on the Pi since the web interface is easier to use on my iPhone.

Tom Kennelly

**Comment by Mr-Dave** [comment]
Closing as invalid.  Pause does stop the Motion detection processes.  To stop the capture of images you will need to close Motion.
