### ISSUE TITLE
Image saving when high resolution specified

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#554]
1. version 4.1
2. installed as a package or compiled from sources git
3. standalone or part of third party standalone
4. video stream source [V4L (card or USB), net cam rtsp
5. hardware x86
6. operating system linux

Motion does not save the correct images when "best", "center", "first" is selected.

**Comment by Mr-Dave** [comment]
Specify the regular netcam resolution and also a netcam_highres where the highres image size is much larger.  It seems to be taking the the low res image and putting it into a buffer sized for high res.

**Comment by tosiara** [comment]
Ah, so it only happens when using pass-through?
