### ISSUE TITLE
jpgutl_error_exit: Improper call to JPEG library in state 202

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#555]
1. version [x.y.z, hash, other]: 4.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L MJPEG
5. hardware [x86, ARM, other]: ARM
6. operating system [Linux (which), FreeBSD, other]: Ubuntu 14

One of my ARM devices' motion process died last night. The last syslog message was:
```
Nov 30 00:50:05 mk808 motion: [1:ml1] [ERR] [ALL] jpgutl_error_exit: Quantization table 0x00 was not defined
Nov 30 00:50:05 mk808 motion: [1:ml1] [ERR] [ALL] jpgutl_error_exit: Improper call to JPEG library in state 202
```
Could it be a bug in recent JPEG code changes or just a one time error because of some corruption in memory?

**Comment by tosiara** [comment]
I have seen this commit related to Ubuntu14: https://github.com/Motion-Project/motion/commit/b744c3ca25fc83306c06585206f3f48d9f7a5ffb#diff-5e87bf9a4d4e3451cf8c5fd26947f5f4

**Comment by Mr-Dave** [comment]
I am unable to reproduce this error on x64/i386 with my v4l2 mjpg streaming camera.  Is this a plain 14.04 install with standard packages?  Which jpg library is installed?

**Comment by tosiara** [comment]
This is ARM, plain `Ubuntu 14.04.5 LTS` and a UVC V4L MJPEG camera
The system had 30+ days uptime running motion when this occurred. It was some kind of USB camera glitch, like a single (or few) broken MJPEG frames. However this caused motion process termination, which I believe should not happen
```
$ uptime
 09:55:45 up 37 days, 16:48,  1 user,  load average: 0.37, 0.17, 0.15
motion@mk808:~$ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l
motion@mk808:~$ uname -a
Linux mk808 3.0.8+ #1 SMP PREEMPT Thu Nov 29 23:53:42 CET 2012 armv7l armv7l armv7l GNU/Linux
```
There was nothing logged in syslog related to the driver

**Comment by Mr-DaveDev** [comment]
I'll need to see the log at the debug level.
