### ISSUE TITLE
Docker for Raspberry Image

### ISSUE THREAD

**Issue by juxorevo** [Motion-Project/motion#556]
1. version [x.y.z, hash, other]: 4.0.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: COMPILED
3. standalone or part of third party [motion, MotionEyeOS, other]:  motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  rtsp
5. hardware [x86, ARM, other]: ARM (raspberry)
6. operating system [Linux (which), FreeBSD, other]:  debian

I have create a Docker Image : 

https://github.com/juxorevo/dockerMotion

https://hub.docker.com/r/juxo/motion-raspbian/

**Comment by Mr-Dave** [comment]
Moved to [related projects](https://github.com/Motion-Project/motion/wiki/Related-Projects) page.  Thanks.
