### ISSUE TITLE
Detect camera signal lost

### ISSUE THREAD

**Issue by martyouel** [Motion-Project/motion#558]
Hi,

Informations [1. 4.1.1    2. deb    3. MotionEye   4. rstp    5. ARM   6. RaspBian]

I'm using MotionEye since a while. I switched my main camera to a cheap HD camera and now i'm streaming the signal through rtsp on a WIFI network.
I got about 3-4 times a day a signal lost and each time Motion/MotionEye can't reconnect to the stream. When I detect this I just do a restart of the MotionEye service and everything's come back.

When the signal is lost there's a timestamp that is shown to display at what time the signal has been lost. Where this information is stored ? Maybe I could use this to build a script to detect if the signal has been lost and then restart my motioneye service.
Or anybody has another idea ?

Thanks in advance

**Comment by tosiara** [comment]
First, try to run motion standalone: https://github.com/Motion-Project/motion/wiki/motioneye

**Comment by martyouel** [comment]
Ok, I tried this. It showed me some access error while writing event.
I fixed this.

Now, Motion run good. 
Should I put it in a process and then restart motioneye ? 
Because by running this : motion -c motion.conf -d 6 -n 
motion is running in my session ? and without motioneye I have no web interface.

Thanks

**Comment by tosiara** [comment]
Did you get the same error when running motion standalone?

**Comment by Mr-Dave** [comment]
Issue seems to be resolved.
