### ISSUE TITLE
MOTION: the image is reversed like in a mirror

### ISSUE THREAD

**Issue by Pat054** [Motion-Project/motion#559]
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
3. standalone or part of third party [motion, MotionEyeOS, other]: 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: 
6. operating system [Linux (which), FreeBSD, other]:

**Comment by Pat054** [comment]
Good evening, 
I use Motion. The image of my camera is inverted (reflected) as if I were looking at the image in a mirror. Is there a parameter in the motion.conf file to put the image back correctly? 
In the meantime, cordially. 
Patric

**Comment by tosiara** [comment]
`flip_axis`
https://github.com/Motion-Project/motion/blob/master/motion-dist.conf.in#L74

**Comment by Mr-Dave** [comment]
An additional source is the online [documentation](https://motion-project.github.io/motion_config.html#flip_axis)

**Comment by Pat054** [comment]
bonjour, 
j'ai rajouté flip_axis v ou flip_axis h dans le fichier motion.conf puis j'ai redémarré ma caméra (raspberry pi3) mais rien n'y fait : l'image est toujours inversée (réfléchie). J'ai l'impression que l'instruction flip_axis ne fonctionne pas. Une autre idée? 
Cordialement.
Patric

**Comment by Pat054** [comment]
Hello,
I added flip_axis v or flip_axis h in the file motion.conf then I restarted my camera (raspberry pi3) but nothing works: the image is always reversed (reflected). I feel that the flip_axis instruction does not work. An other idea?
Cordially.
Patric

**Comment by tosiara** [comment]
It works only in latest version. But you did not specify anything about what version you were using

**Comment by Pat054** [comment]
How to know the version of motion installed on my raspberry pi3?
Does the command "sudo apt-get update" update motion ?,

**Comment by Mr-Dave** [comment]
May want to review the documentation on [Command line options: ](https://motion-project.github.io/motion_config.html#Command_Line_Options) -h or look at the log.

See also the first paragraph in the [install from apt](https://motion-project.github.io/motion_build.html#Install_Apt)

**Comment by Pat054** [comment]
it seems to be complicated all this. To go to the latest version of motion: is "apt-get update" enough?

**Comment by Pat054** [comment]
by entering the command "motion -h", I have this: motion version 3.2.12.

**Comment by Pat054** [comment]
Hello,

I found and I realized at first a MOTION uninstall with:
sudo apt-get remove motion
sudo apt-get purge motion
sudo apt-get autoremove

then I made a MOTION installation by following the https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/release-4.1/motion_guide.html#Install_Deb tel guide than:
Installing with a release deb package

The only problem is that the following statement in the guide is incomplete:
wget https://github.com/Motion-Project/motion/releases/{deb package name}

The instruction and the full path is: wget https://github.com/Motion-Project/motion/releases/download/release-4.1/pi_jessie_motion_4.1-1_armhf.deb

Again thank you cordially.

Patric

PS: By the way, now the image of the camera is no longer reversed, I put: flip_axis v in motion.conf
