### ISSUE TITLE
RTSP authentication with username only? 

### ISSUE THREAD

**Issue by roaringbits** [Motion-Project/motion#565]
I'm trying to integrate two Guudgo SC-02 camera's, which have a RSTP stream which I can access just fine through VLC. 

Only the username is set (admin) and cannot be changed, and I'm trying to configure the stream to authenticate without the password (also cannot be set).

If I set no password (see below), motion does no authentication at all, but I would expect motion to use at least the username;

_netcam_userpass admin:
netcam_url rtsp://192.168.0.xxx:554/_

Is there any way to allow this? The result URL should be;

**rtsp://admin@192.168.0.xxx:554/**

1. version [x.y.z, hash, other]: 4.0.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [Linux (which), FreeBSD, other]: ubuntu

**Comment by tosiara** [comment]
Hm, so you mean you have credentials that consist of only a user name and an empty password and cannot be changed? It could be a bug that motion doe not expect empty password. This would need to be checked

Meanwhile, have you tried `rtsp://admin:@192.168.0.xxx:554/`

**Comment by roaringbits** [comment]
Yes, this results in the following:

[3:ml3] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://admin:@192.168.0.31:554/)
[3:ml3] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 401 Unauthorized
[3:ml3] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://192.168.0.31:554/): Server returned 401 Unauthorized (authorization failed)

**Comment by tosiara** [comment]
Ok, then we need to wait for @Mr-Dave 's input whether empty password works in motion's rtsp

**Comment by Mr-Dave** [comment]
Based upon the above, what are the results when you do not specify the username at all?  Typically, if there is no password, that means, there is no authentication at all.  Also, you should try the exact url (rtsp://admin:@192.168.0.xxx:554/) in ffplay and validate it works there.

**Comment by roaringbits** [comment]
No username at all returns a 401 as well.

When using ffplay on my laptop it works, but on my server I get this:

Input #0, rtsp, from 'rtsp://admin:@192.168.0.31:554/':  0B f=0/0   
  Metadata:
    title           : h264.mp4
    comment         : TAS-Tech Live Cast
  Duration: N/A, start: 0.755000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p, 1280x720, 8 fps, 25 tbr, 90k tbn, 16 tbc
SDL: could not set video mode - exiting

Going to look into that now

**Comment by Mr-Dave** [comment]
Please make sure to update the status after you have upgraded to Motion version 4.1

**Comment by roaringbits** [comment]
Upgrading fixed my issue, thanks! :)
