### ISSUE TITLE
Code Clean Up

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#566]
- [x] Remove the dead code associated with processing of VIDEO_PALETTE_GREY format image processing.   All source images are converted to the V4L2 format V4L2_PIX_FMT_YUV420 as they are captured so the historical code which processes differently based upon the img.type=VIDEO_PALETTE_GREY is now obsolete.

- [ ]   Consolidate the jpg utilities.  Currently there are redundant functions of the jpg utilities / calls / processing in the picture.c, jpegutils.c and netcam_jpeg.c functions.  Revise code to consolidate the functionality into jpegutils.c

- [ ]   Resolve the headers within headers within headers situation.

- [x]   Break excessively long functions into logical and manageable calls to smaller functions so that future enhancements can be implemented with less effort and fewer errors.  ~~e.g. The webhttpd.c track function is currently over 700 lines which precludes modernizing the current web interface.~~

- [x]   Rewrite and completely replace webhttpd.c module.
- [x]   Consolidate the get/set threadname calls into the "util" functions.

- [x]   Remove the netcam_mjpg format.  This was a experimental format override for http that does not appear to function.

- [ ]   Consolidate utility functions into new common module.  e.g. `mystrdup` is defined in conf.c but used in many modules, 

- [ ]   Remove / evaluate redundant and obsolete variables in Motion context.  e.g. timenow

- [ ]   Revise the database functions and functionality to consolidate them and have fewer #IF conditions in the main line code.  

- [ ]   Implement function and variable naming convention to indicate where they are located and what they contain.

- [x]  Review and revise default values to optimize to most common options.  Ensure that the documentation, code and distributed configuration file are in sync.  e.g.  `despeckle_filter`, `ffmpeg_duplicate_frames`

- [x]  Since there are over 140 configuration parameters (not counting the custom conversion specifiers), revise the motion-dist.conf file to only include the most common options, eliminate the rarely used options listed and reference the documentation for the full list. e.g. The `track`, `database` and options not needed for a basic setup.  

- [ ]  Implement a subdirectory organizational structure of src, data, scripts, docs. 

- [x]   Rename the ffmpeg and picture configuration options to `movie_` and `picture_`

**Comment by Felixrising** [comment]
Refactor code to support alternative motion sensing code as plugins, e.g. OpenCV
