### ISSUE TITLE
Invalid RTSP url segfault with coredump

### ISSUE THREAD

**Issue by sosconsult** [Motion-Project/motion#572]
1. version [x.y.z, hash, other]: 4.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: pacman 
3. standalone or part of third party [motion, MotionEyeOS, other]: motion (with postgresql)
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx 
6. operating system [Linux (which), FreeBSD, other]: ArchLinux

Dear all,
had a lot of trouble with installing and configuring. When using a http://cam-ip.jpg camera interface I received permanent messages of " netcam_read_html_jpeg: disconnecting netcam since keep-alive not set." messages. So I tried to work with the rtsp:// interface. when starting motion with systemctl command motion chrashed with a coredump.

Here the message log:
```
Dec 13 16:15:40 gaisb_str_15 sudo[25481]: sosobserve : TTY=pts/4 ; PWD=/home/sosobserve ; USER=root ; COMMAND=/usr/bin/systemctl restart motion
Dec 13 16:15:40 gaisb_str_15 sudo[25481]: pam_unix(sudo:session): session opened for user root by sosobserve(uid=0)
Dec 13 16:15:40 gaisb_str_15 systemd[1]: Started Motion daemon.
-- Subject: Unit motion.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit motion.service has finished starting up.
-- 
-- The start-up result is RESULT.
Dec 13 16:15:40 gaisb_str_15 sudo[25481]: pam_unix(sudo:session): session closed for user root
Dec 13 16:15:40 gaisb_str_15 motion[25484]: [-1238882368:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motion/motion.conf
Dec 13 16:15:40 gaisb_str_15 motion[25484]: [-1238882368:motion] [ALR] [ALL] conf_cmdparse: Unknown config option "jpeg_filename"
Dec 13 16:15:40 gaisb_str_15 motion[25484]: [-1238882368:motion] [NTC] [ALL] config_camera: Processing camera config file /etc/sosobserve/cam1.conf
Dec 13 16:15:40 gaisb_str_15 motion[25484]: [-1238882368:motion] [NTC] [ALL] config_camera: Processing camera config file /etc/sosobserve/cam2.conf
Dec 13 16:15:40 gaisb_str_15 motion[25484]: [-1238882368:motion] [NTC] [ALL] config_camera: Processing camera config file /etc/sosobserve/cam3.conf
Dec 13 16:15:40 gaisb_str_15 motion[25484]: [-1238882368:motion] [NTC] [ALL] motion_startup: Using default log level (NTC) (6)
Dec 13 16:15:40 gaisb_str_15 motion[25484]: [-1238882368:motion] [NTC] [ALL] motion_startup: Motion 4.1 Started
Dec 13 16:15:40 gaisb_str_15 motion[25484]: [-1238882368:motion] [NTC] [ALL] motion_startup: Logging to file (/tmp/motion.log)
Dec 13 16:15:40 gaisb_str_15 kernel: ml1[25485]: segfault at 0 ip 00005606b5e735a8 sp 00007f771b8e1a70 error 4 in motion[5606b5e44000+4b000]
Dec 13 16:15:40 gaisb_str_15 systemd[1]: Started Process Core Dump (PID 25488/UID 0).
-- Subject: Unit systemd-coredump@2-25488-0.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-coredump@2-25488-0.service has finished starting up.
-- 
-- The start-up result is RESULT.
Dec 13 16:15:40 gaisb_str_15 systemd[1]: motion.service: Main process exited, code=killed, status=11/SEGV
Dec 13 16:15:40 gaisb_str_15 systemd[1]: motion.service: Failed with result 'signal'.
Dec 13 16:15:40 gaisb_str_15 systemd-coredump[25489]: Process 25484 (motion) of user 0 dumped core.
                                                      
                                                      Stack trace of thread 25485:
                                                      #0  0x00005606b5e735a8 n/a (motion)
                                                      #1  0x00005606b5e5a89c n/a (motion)
                                                      #2  0x00005606b5e50bf2 n/a (motion)
                                                      #3  0x00005606b5e51e46 n/a (motion)
                                                      #4  0x00007f772da4008a start_thread (libpthread.so.0)
                                                      #5  0x00007f772d77747f __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 25486:
                                                      #0  0x00007f772d7521da build_trtable (libc.so.6)
                                                      #1  0x00007f772d75c880 re_search_internal (libc.so.6)
                                                      #2  0x00007f772d75d99a regexec@@GLIBC_2.3.4 (libc.so.6)
                                                      #3  0x00005606b5e5b0ab n/a (motion)
                                                      #4  0x00005606b5e73880 n/a (motion)
                                                      #5  0x00005606b5e5a89c n/a (motion)
                                                      #6  0x00005606b5e50bf2 n/a (motion)
                                                      #7  0x00005606b5e51e46 n/a (motion)
                                                      #8  0x00007f772da4008a start_thread (libpthread.so.0)
                                                      #9  0x00007f772d77747f __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 25484:
                                                      #0  0x00007f772da4a230 __nanosleep (libpthread.so.0)
                                                      #1  0x00005606b5e4d3ec main (motion)
                                                      #2  0x00007f772d6a1f6a __libc_start_main (libc.so.6)
                                                      #3  0x00005606b5e4db1a n/a (motion)
                                                      
                                                      Stack trace of thread 25487:
                                                      #0  0x00007f772d768b3b write (libc.so.6)
                                                      #1  0x00007f772d6fa2cd _IO_file_write@@GLIBC_2.2.5 (libc.so.6)
                                                      #2  0x00007f772d6f95af new_do_write (libc.so.6)
                                                      #3  0x00007f772d6fb4c9 _IO_do_write@@GLIBC_2.2.5 (libc.so.6)
                                                      #4  0x00007f772d6f93d8 _IO_file_sync@@GLIBC_2.2.5 (libc.so.6)
                                                      #5  0x00007f772d6ee2cd _IO_fflush (libc.so.6)
                                                      #6  0x00005606b5e540e1 n/a (motion)
                                                      #7  0x00005606b5e5a893 n/a (motion)
                                                      #8  0x00005606b5e50bf2 n/a (motion)
                                                      #9  0x00005606b5e51e46 n/a (motion)
                                                      #10 0x00007f772da4008a start_thread (libpthread.so.0)
                                                      #11 0x00007f772d77747f __clone (libc.so.6)
-- Subject: Process 25484 (motion) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 25484 (motion) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
Dec 13 16:20:01 gaisb_str_15 crond[25513]: pam_unix(crond:session): session opened for user root by (uid=0)
Dec 13 16:20:01 gaisb_str_15 CROND[25514]: (root) CMD (/home/sosobserve/scripts/apptest.sh)
Dec 13 16:20:01 gaisb_str_15 CROND[25513]: pam_unix(crond:session): session closed for user root
**********************************************************************************************************************
###################################################################################
**********************************************************************************************************************
```
Frankly I have no clue why this occurred. Pleas help. I work with three INSTAR cameras which are capable for either jpeg, mjpeg or rtsp interfaces.

Kind regards

Franz

**Comment by tosiara** [comment]
Hm, this one `[-1238882368:motion]` looks to be an invalid thread name
`Unknown config option "jpeg_filename"` means you are using very old config file
Can you try to take https://github.com/Motion-Project/motion/blob/master/motion-dist.conf.in, configure a single camera and see if that crashes?

**Comment by sosconsult** [comment]
Thanks for the quick response,
I tried to run motion with this conf and changed only the netcam value url to netcam_value rtsp://10.0.0.22:RTPS-port/12 and the corresponding netcam_userpass value. Nothing else.

here the new log:

Dec 13 17:35:19 gaisb_str_15 sudo[26373]: sosobserve : TTY=pts/5 ; PWD=/home/sosobserve ; USER=root ; COMMAND=/usr/bin/systemctl restart motion
Dec 13 17:35:19 gaisb_str_15 sudo[26373]: pam_unix(sudo:session): session opened for user root by sosobserve(uid=0)
Dec 13 17:35:19 gaisb_str_15 systemd[1]: Started Motion daemon.
-- Subject: Unit motion.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit motion.service has finished starting up.
-- 
-- The start-up result is RESULT.
Dec 13 17:35:19 gaisb_str_15 sudo[26373]: pam_unix(sudo:session): session closed for user root
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [267835328:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motion/motion.conf
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [267835328:motion] [NTC] [ALL] motion_startup: Motion 4.1 Started
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [267835328:motion] [NTC] [ALL] motion_startup: Logging to syslog
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [267835328:motion] [NTC] [ALL] motion_startup: Using log type (ALL) log level (NTC)
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [267835328:motion] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version 57.107.100 libavformat version 57.83.100
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [0:motion] [NTC] [ALL] main: Camera ID: 0 is from /etc/motion/motion.conf
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [0:motion] [NTC] [ALL] main: Camera ID: 0 Camera Name: (null) Service: rtsp:
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [0:motion] [NTC] [ALL] main: Stream port 8081
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [0:motion] [NTC] [ALL] main: Waiting for threads to finish, pid: 26379
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [0:wc0] [NTC] [STR] http_bindsock: listening on 127.0.0.1 port 8080
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [0:wc0] [NTC] [STR] httpd_run: Started motion-httpd server on port 8080 (auth Disabled)
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [1:ml1] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
Dec 13 17:35:19 gaisb_str_15 motion[26379]: [1:ml1] [NTC] [VID] vid_start: Opening Netcam RTSP
Dec 13 17:35:19 gaisb_str_15 kernel: ml1[26380]: segfault at 0 ip 000056190e3e85a8 sp 00007fdb5175ea70 error 4 in motion[56190e3b9000+4b000]
Dec 13 17:35:19 gaisb_str_15 systemd[1]: Started Process Core Dump (PID 26382/UID 0).
-- Subject: Unit systemd-coredump@9-26382-0.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-coredump@9-26382-0.service has finished starting up.
-- 
-- The start-up result is RESULT.
Dec 13 17:35:20 gaisb_str_15 systemd[1]: motion.service: Main process exited, code=killed, status=11/SEGV
Dec 13 17:35:20 gaisb_str_15 systemd[1]: motion.service: Failed with result 'signal'.
Dec 13 17:35:20 gaisb_str_15 systemd-coredump[26383]: Process 26379 (motion) of user 0 dumped core.
                                                      
                                                      Stack trace of thread 26380:
                                                      #0  0x000056190e3e85a8 n/a (motion)
                                                      #1  0x000056190e3cf89c n/a (motion)
                                                      #2  0x000056190e3c5bf2 n/a (motion)
                                                      #3  0x000056190e3c6e46 n/a (motion)
                                                      #4  0x00007fdb638bd08a start_thread (libpthread.so.0)
                                                      #5  0x00007fdb635f447f __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 26381:
                                                      #0  0x00007fdb635ebdb3 __select (libc.so.6)
                                                      #1  0x000056190e3e3147 n/a (motion)
                                                      #2  0x000056190e3e3a0d n/a (motion)
                                                      #3  0x00007fdb638bd08a start_thread (libpthread.so.0)
                                                      #4  0x00007fdb635f447f __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 26379:
                                                      #0  0x00007fdb638c7230 __nanosleep (libpthread.so.0)
                                                      #1  0x000056190e3c23ec main (motion)
                                                      #2  0x00007fdb6351ef6a __libc_start_main (libc.so.6)
                                                      #3  0x000056190e3c2b1a n/a (motion)
-- Subject: Process 26379 (motion) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 26379 (motion) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
Dec 13 17:36:09 gaisb_str_15 sshd[26245]: Received disconnect from 10.10.0.1 port 39988:11: disconnected by user
Dec 13 17:36:09 gaisb_str_15 sshd[26245]: Disconnected from user sosobserve 10.10.0.1 port 39988
Dec 13 17:36:09 gaisb_str_15 sshd[26243]: pam_unix(sshd:session): session closed for user sosobserve
Dec 13 17:36:09 gaisb_str_15 systemd-logind[294]: Removed session c8.
-- Subject: Session c8 has been terminated
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID c8 has been terminated.

#############################################################################


I of course would accept to use the http plus .jpg interface if we could that one make running.

kind regards
Franz

**Comment by sosconsult** [comment]
Eurecka!
Found at least the reason that causes the the crash. It is the ":RTSP-Port/12 suffix at the rtsp://url. When removing I get no more chrash.

this is the log when removing that suffix:
Dec 13 17:59:32 gaisb_str_15 sudo[26551]: sosobserve : TTY=pts/5 ; PWD=/home/sosobserve ; USER=root ; COMMAND=/usr/bin/systemctl restart motion
Dec 13 17:59:32 gaisb_str_15 sudo[26551]: pam_unix(sudo:session): session opened for user root by sosobserve(uid=0)
Dec 13 17:59:33 gaisb_str_15 systemd[1]: Started Motion daemon.
-- Subject: Unit motion.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit motion.service has finished starting up.
-- 
-- The start-up result is RESULT.
Dec 13 17:59:33 gaisb_str_15 sudo[26551]: pam_unix(sudo:session): session closed for user root
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [-981485632:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motion/motion.conf
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [-981485632:motion] [NTC] [ALL] motion_startup: Motion 4.1 Started
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [-981485632:motion] [NTC] [ALL] motion_startup: Logging to syslog
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [-981485632:motion] [NTC] [ALL] motion_startup: Using log type (ALL) log level (NTC)
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [-981485632:motion] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version 57.107.100 libavformat version 57.83.100
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [0:motion] [NTC] [ALL] main: Camera ID: 0 is from /etc/motion/motion.conf
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [0:motion] [NTC] [ALL] main: Camera ID: 0 Camera Name: (null) Service: rtsp:
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [0:motion] [NTC] [ALL] main: Stream port 8081
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [0:motion] [NTC] [ALL] main: Waiting for threads to finish, pid: 26555
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [VID] vid_start: Opening Netcam RTSP
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [0:wc0] [NTC] [STR] http_bindsock: listening on 127.0.0.1 port 8080
Dec 13 17:59:33 gaisb_str_15 motion[26555]: [0:wc0] [NTC] [STR] httpd_run: Started motion-httpd server on port 8080 (auth Disabled)
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc:
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: ****************************************************************
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: The network camera is sending pictures in a different
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: size than specified in the configuration file.
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: The picture is being transcoded into the size
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: requested in the configuration.  If possible change
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: netcam or configuration to indicate the same size
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: to possibly lower CPU usage.
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: Netcam: 1280 x 720 => Config: 320 x 240
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc: ****************************************************************
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_resize_ntc:
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [3:nc3] [NTC] [NET] netcam_rtsp_handler: Normal resolution: Camera handler thread [3] started
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [STR] http_bindsock: listening on 127.0.0.1 port 8081
Dec 13 17:59:39 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [ALL] motion_init: Started motion-stream server on port 8081 (auth Disabled)
Dec 13 17:59:46 gaisb_str_15 motion[26555]: [3:nc3] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
Dec 13 17:59:46 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [EVT] event_newfile: File of type 8 saved to: ./01-20171213175946.mkv
Dec 13 17:59:46 gaisb_str_15 motion[26555]: [1:ml1] [NTC] [ALL] motion_detected: Motion detected - starting event 1

################################################################################

I will now try to make it running. Are you interested in further details of this incident? If yes please let me know. If not I will place a "Problem solved" statement as soon I succeeded with all cameras at this forum.
Thank you very much for being so helpful.

Kind regards

Franz

**Comment by tosiara** [comment]
Can you please prove the full url that caused the segfault? We will try to reproduce it

**Comment by sosconsult** [comment]
ok
netcam_url rtsp://10.0.0.22                           ---> no crash
netcam_url rtsp://10.0.0.22:RTSP-Port/12   ---> crash with coredump

Here the cam details: INSTAR IN-5907HD

**Comment by sosconsult** [comment]
I would be ready to give you direct ssh access to cameras and motion server

**Comment by tosiara** [comment]
No need to ssh access yet, thanks
So it is "RTSP-Port" in text, not the real port number?

**Comment by sosconsult** [comment]
seems so. I could try a different port to verify if you want

**Comment by tosiara** [comment]
I can confirm that invalid URL like `netcam_url rtsp://192.168.0.1:RTSP-Port/12` will segfault motion:
```
[1:ml1] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
[1:ml1] [NTC] [VID] vid_start: Opening Netcam RTSP
[1:ml1] [INF] [NET] netcam_rtsp_set_parms: Setting up Normal resolution stream.
Segmentation fault
```

**Comment by sosconsult** [comment]
Finally problem solved. Thank you very much for being so helpful. motion works without the port-suffix.
