### ISSUE TITLE
motion detection duration 10 seconds

### ISSUE THREAD

**Issue by gjsbe** [Motion-Project/motion#577]
1. version 4.1.1-1
2. installed as binary or compiled
3. standalone 
4. source mjpeg video
5. hardware vm x64
6. archlinux 

Hi, 
I have a mjpeg stream from a vga monitor with 2 fps.
When something on the monitor change I would like to trigger an event and capture jpeg of the changed frame. 
Example: I have a document opened on the monitor, when I change page I need to capture the changed frame, with motion detection, the on_event_start event is triggered correctly, but the event_end is triggered only after 10-11 seconds. Why if I made a single page scroll to the document and set event_gap to 0? If I set event gap to 1 motion triggers 10-11 events of the same jpg.
Another problem: Why it generates 10-11 jpegs with the same image?
I can change the sources, It's not the first time I do it, but I would like to understand If there is a problem or if you can help me to find the right place to do it.
I find that there is a history buffer of 10 seconds, is the problem related to it?
Thank you very much
Regards
Alfredo

**Comment by tosiara** [comment]
Try to record debug movies to see maybe motion still sees pixel changing during those 10 seconds

**Comment by gjsbe** [comment]
Hi,
You're right, with debug on I see differences between the jpegs.
But it is a screenshot that changes in less than one second, and the stream is 2 fps.
Why i see differences for 10 seconds? it can be some noise?

**Comment by tosiara** [comment]
How do you stream the screen? If it is some compressed format then compression artifacts may appear like changed pixels

**Comment by gjsbe** [comment]
Hi, I use vlc with this configuration:

vlc "dshow://AV.io HDMI Video" :dshow-aspect-ratio=16:9 :sout=#transcode{vcodec=MJPG,vb=4096,fps=2,scale=1,width=1920,height=1080,acodec=none}:duplicate{dst=http{mux=mpjpeg,dst=:8080/},dst=display} :sout-keep

**Comment by tosiara** [comment]
So that's probably artifacts of mjpeg compression

**Comment by gjsbe** [comment]
but there's a think I don't understand... I there are artifacts it should trigger motion detection, instead it generates so many jpegs only after I change screen and after 10 seconds event end, but I set event_gap to 0 so it should continue.

**Comment by tosiara** [comment]
I don't see what happens in your stream's debug video after motion has been triggered. If you can share it I would probably be able to explain

**Comment by gjsbe** [comment]
Here's my motion.conf e camera1.conf file (I split it so I hope it use 2 threads).

[camera1.txt](https://github.com/Motion-Project/motion/files/1562993/camera1.txt)
[motion.txt](https://github.com/Motion-Project/motion/files/1562994/motion.txt)

Follows event log:

[log.txt](https://github.com/Motion-Project/motion/files/1563013/log.txt)

Here is the video of captured output with vlc client.

[vlc-output.avi.zip](https://github.com/Motion-Project/motion/files/1563015/vlc-output.avi.zip)

And finally the zip of jpeg with ghost images:

[ghosts.zip](https://github.com/Motion-Project/motion/files/1563016/ghosts.zip)

This is the command I used to launch vlc streaming:

vlc "dshow://AV.io HDMI Video" :dshow-aspect-ratio=16:9 :sout=#transcode{vcodec=MJPG,vb=4096,fps=2,scale=1,width=1920,height=1080,acodec=none,deinterlace}:duplicate{dst=http{mux=mpjpeg,dst=:8080/},dst=display} :sout-keep

Thank you very much

**Comment by gjsbe** [comment]
I tried also without deinterlace but without success, I think to try to stream with rtsp, to see if something changes...

**Comment by tosiara** [comment]
I have checked your ghost images and it is clearly seen as jpeg artifacts around the text. I don't know if MJPEG supports lossless compression, but at lest try to increase the bitrate, this should reduce compression artifacts

**Comment by gjsbe** [comment]
Hi,
You're right, there are jpeg artifacts caused by mjpeg transcode compression.
I decided to try another solution, without motion at this point, because now I miss mjpeg streaming producer.
Thank you very much for your help.
