### ISSUE TITLE
IP Camera can't be referenced by hostname with underscores

### ISSUE THREAD

**Issue by ShanDestromp** [Motion-Project/motion#580]
1. at least versions 4.0-4.1.1
2. 4.0 as Debian 9 stable, 4.1 and 4.1.1 obtained from this repo
3. Standalone (technically motioneyes but tested directly with `motion -c motion.conf -d 6 -n`)
4. RTSP Ip camera
5. x64
6. Debian 9

I have a dozen cameras and I prefer to reference my cameras by hostname as it's far easier to remember "CAM_Front_Door" than it is 192.168.x.xxx.  With motion 4.1 and 4.1.1 motion will immediately segfault if a hostname is utilized in `netcam_url`; 4.0 will just spit out

> [1:ml1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://cam_front_door:554/h264Preview_01_main)
> [1:ml1] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://cam_front_door:554/h264Preview_01_main)

Machine can ping via hostname and it's not a firewall issue or "other" (VLC and other RTSP-capable software can access via the cameras hostnames fine).

Works:  `netcam_url rtsp://192.168.2.18:554/h264Preview_01_main`
Does not: `netcam_url rtsp://cam_front_door:554/h264Preview_01_main`

**Comment by Mr-Dave** [comment]
Can you test the latest git to see if it at least avoids the segfault?  There was a revision a few days ago addressing the parsing of the URL.  It probably won't solve using names instead of IPs but should stop it from segfaulting.

**Comment by ShanDestromp** [comment]
Unless I'm unusually slow today it doesn't look like your travis setup saves artifacts so I'll have to spin up a VM and try and build it myself.

**Comment by tosiara** [comment]
The problem here is underscore symbol which is not allowed in hostname. Try changing it to dash `-`

**Comment by tosiara** [comment]
Sorry for wikipedia link, just a quick search, but it looks like underscores in hostnames are not allowed by rfc:
```
The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the minus sign ('-')
```

**Comment by ShanDestromp** [comment]
I had to look it up; and it turns out that per [RFC952](https://tools.ietf.org/html/rfc952) you're correct, my hostnames ARE invalid.  I do find it numerous that across virtually any thinkable configuration (Windows, Linux, BSD etc etc) I've never had a problem before until now.  Seems whomever wrote the relevant portion of Motion has higher standards than basically the rest of the world :-)

**Comment by ShanDestromp** [comment]
Closing this, properly formatting my hostnames (no underscores) and things work fine.

**Comment by tosiara** [comment]
@Mr-Dave , I have checked that ffmpeg is able to open rtsp stream with such hostnames fine. Should we reduce url restrictions and allow rtsp streams from hostnames that contain underscores?
