### ISSUE TITLE
Changing the html content of the webcontrol feed

### ISSUE THREAD

**Issue by Zumbalamambo** [Motion-Project/motion#583]
I would like to change the html contents of the webcontrol feed. May I know how do I do that ?

**Comment by Mr-Dave** [comment]
That would be within the webhttpd module.  I would note that changes to that module were not being contemplated until some of the items in issue #566 were addressed.  Particularly the removal of the dead code, the splitting of the excessively long functions into smaller components and splitting the logic for the with/without html configuration item, etc.

**Comment by Zumbalamambo** [comment]
@Mr-Dave  Thank you... I just want to make the video to fit screen 100 percent even if the resolution of the video is small... basically i want to stretch to fill...

**Comment by Zumbalamambo** [comment]
or is it possible to access the rtsp url of two cameras that Im using? if so instead of loading it in webpage, I can load it in an individual videoviews which might solve this .

**Comment by Mr-Dave** [comment]
No, that wouldn't be possible.

**Comment by Zumbalamambo** [comment]
is it possible to stream via rtsp and access the rtsp url?

**Comment by Mr-Dave** [comment]
Closing as this venue is not really a question/answer forum.  

If code revisions are provided via a pull request that revise the existing MPJPEG feed into a RTSP feed, we will review them at that time.  Likewise for revisions to the web interface feed.
