### ISSUE TITLE
motion_4.1-1 installation problems

### ISSUE THREAD

**Issue by parmiani** [Motion-Project/motion#585]
Hello,
i tried to install the latest version of motion but i encountered an error:

pi@raspberrypi:~ $ sudo dpkg -i pi_stretch_motion_4.1-1_armhf.deb
Selecting previously unselected package motion.
(Reading database ... 115711 files and directories currently installed.)
Preparing to unpack pi_stretch_motion_4.1-1_armhf.deb ...
Unpacking motion (4.1-1) ...
dpkg: dependency problems prevent configuration of motion:
motion depends on libavcodec57 (>= 7:3.2.8) | libavcodec-extra57 (>= 7:3.2.8); however:
Package libavcodec57 is not installed.
Package libavcodec-extra57 is not installed.
motion depends on libavdevice57 (>= 7:3.2.8); however:
Package libavdevice57 is not installed.
motion depends on libavformat57 (>= 7:3.2.8); however:
Package libavformat57 is not installed.
motion depends on libavutil55 (>= 7:3.2.8); however:
Package libavutil55 is not installed.
motion depends on libswscale4 (>= 7:3.2.8); however:
Package libswscale4 is not installed.

dpkg: error processing package motion (--install):
dependency problems - leaving unconfigured
Processing triggers for systemd (215-17+deb8u6) ...
Processing triggers for man-db (2.7.0.2-5) ...
Errors were encountered while processing:
motion

Someone has this problem?

Thanks
Alessandro

**Comment by Mr-Dave** [comment]
Please consult the guide/ [instructions](https://motion-project.github.io/motion_build.html).

**Comment by parmiani** [comment]
Thanks for the suggestion
I tried but i received an error:

pi@raspberrypi:~ $ sudo gdebi pi_stretch_motion_4.1-1_armhf.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Building data structures... Done
Building data structures... Done
This package is uninstallable
Dependency is not satisfiable: libavcodec57 (>= 7:3.2.8)|libavcodec-extra57 (>= 7:3.2.8)

Alessandro
