### ISSUE TITLE
Video frames problem

### ISSUE THREAD

**Issue by parmiani** [Motion-Project/motion#587]
Hello,

i have installed motioneye and motion  (pi_jessie_motion_4.1.1-1_armhf.deb) on my raspberry pi 3 and i have connected the network camera Sricam SP007. The output stream is on rtsp://192.168.x.x:554/onvif1 with a resolution of 1280x720 that is also the resolution of the camera . I see that randomly same frames of the output stream are "damaged". A picture is attached:

![motion1](https://user-images.githubusercontent.com/29644088/34342249-fecfb25c-e9a9-11e7-85f6-d48ef8ded9f3.jpg)

This creates problems, specially because causes false positive events in motion detection systems.
I checked the output stream of the camera with the suggested application of Sricam and i didn't find any problem.
Someone has a suggestion for me?

Thanks
Alessandro

**Comment by Mr-Dave** [comment]
[Support](https://motion-project.github.io/motion_support.html)
