### ISSUE TITLE
(null) camera name appears in the log

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#593]
Are those `(null)` by design?
```
[0:motion] [NTC] [ALL] main: Camera ID: 0 Camera Name: (null) Service: rtsp:
[1:ml1] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
```
What should I expect to see instead of null?

**Comment by Mr-Dave** [comment]
Yes, there wasn't really a good alternative that came to mind.  This is where the IP address formerly was reported.  Since there wasn't a camera name specified in the configuration, NULL is accurate and indicates the user specified.  I suppose it changed to camera1, camera2, etc.

**Comment by tosiara** [comment]
Remind me please, how do I assign a name to a camera?

**Comment by tosiara** [comment]
Found it, `camera_name`
