### ISSUE TITLE
Web control not working correct version 4.x

### ISSUE THREAD

**Issue by hinkma** [Motion-Project/motion#606]
1. version 4.1.1: 
2. installed as a package [deb]: 
3. standalone or part of third party [motion and motioneye]: 
4. video stream source [net cam (rtsp)]: 
5. hardware [ARM, raspberry pi 3]: 
6. operating system [Rasbian latest]: 

Motion version 4.x emulate_motion=on (off) not working.

curl http://my.motioneye.com:7999/0/config/set?emulate_motion=on
Give response: Not Valid Command.

**Comment by genius3000** [comment]
What is `webcontrol_parms` set to in your motion config? My first guess is you've upgraded and are missing this parameter, which defaults to 0 (meaning no config parameters available through web control). You can view the guide on this parameter [here](https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_config.html#webcontrol_parms).  
If this isn't the case, you'll likely have to supply a debug log of trying, unless someone spots the issue prior to that.

**Comment by timdonovanuk** [comment]
I think web control is kinda fubared now too:

curl http://localhost:7999/1/config/set?text_left=foo

<!DOCTYPE html>
<html>
<body>
<h1>Not Valid Command</h1>
<p>The requested URL is not valid Command.</p>
</body>
</html>

**Comment by ccrisan** [comment]
Port 7999 suggests motionEye and motionEye does not set webcontrol_parms. I did not know about this option before, but I'll make sure to fix it asap in the following motionEye release.

I believe this issue can be closed as it's something that needs to be addressed in motionEye.

**Comment by timdonovanuk** [comment]
Hey @ccrisan thanks! I've set webcontrol_parms 1 in /etc/motion/motion.conf and it didn't work..but then I just set it in /etc/motioneye/motion.conf and all is good. Thanks again
