### ISSUE TITLE
New Configuration option:  v4l2_control_params

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#608]
Opening this as a separate issue for visibility

In order to allow for the specification of any control on a v4l2 device, change the method by which parameters are specified.  

In the current configuration structure, each unique parameter to the device must be added as a separate configuration option or manually specified to the device prior to starting Motion.  This method is not conducive to user interaction by requiring interactions outside of the application, proliferates the number of configuration options and occupies developer time to implement new configuration options.

The proposed revised approach would be similar to the method of specifying configuration parameters to [mmalcam_control_params](https://motion-project.github.io/motion_config.html#mmalcam_control_params).  Multiple configuration options would all be specified on a single line with a delimiter.  All options that exist for the device would be listed in the log at the INF level so the user could review the parameters and set them as desired.  Users would be able to reference the desired option by either specifying the unique ID associated with the control or by specifying the long name (which may be quite verbose and require placing the option in quotes).

Current specification method:
`hue 130`
`brightness 160`
`power_line_frequency 0 `
`contrast 0`
`saturation 0`

New specification method:
`v4l2_control_parms hue=130,brightness=160,"Auto Exposure"=1, ID009a0914=3`

While the choice of including a option for specifying the parameter via the ID parameter is not ideal, the alternative of having the application try to make up its own short name would be problematic.  Likewise only permitting the long name could lead to difficulties given the complexity of how some of the parameters are named by the driver.

The following [link](https://gist.github.com/Mr-Dave/d6e8ad1f4b9cf62016684db77e8fcac0) provides an example of what would be displayed in the log for a PI cam that is using the v4l2 driver.  

It is believed that by implementing this method the issues raised in #551 and #582 as well as numerous issues raised in the mailing list over the years could be addressed.

The implementation of this as a new configuration option would also depreciate the configuration options of: `hue, contrast, brightness, saturation and power_line_frequency`

Reference for visibility:  @ccrisan

**Comment by ccrisan** [comment]
Makes sense and seems to be a good approach. I've been asked many times to allow users to tweak various v4l2 parameters via motionEye's UI and this looks like a good opportunity to finally implement it.
