### ISSUE TITLE
Allow for disconnect/reconnect of V4L2 devices

### ISSUE THREAD

**Issue by lobor** [Motion-Project/motion#613]
Hello,

I want disable motion_loop, i create interface for add a video. But when there are not /dev/video, a loop search when i plug caméra, detect it and launch stream.

It's possible to add configuration like `watchfod: "off"` ?

Thanks

**Comment by Mr-Dave** [comment]
Can you confirm that the requested need is:
a1.  Be able to start Motion without a V4L2 device.
a2.  Add a new device to the hardware 
a3.  Add the device to Motion configuration file via the web-interface or a different method and use it.
or
b1.  Start Motion with the device attached
b2.  Disconnect the device from the hardware
b3.  Reconnect the device to the hardware
b4.  Have Motion recognize the attachment and begin detection again.

And the issue being observed in the current code is that the watchdog timeout is being triggered and this would be a way to turn off the watchdog.

Is this a correct interpretation of the situation?  If yes, then are there any other scenarios to be considered?

**Comment by lobor** [comment]
Yes, is correct interpretation, for scenarios a

**Comment by Mr-Dave** [comment]
OK.  We can add it to the enhancement list.  I anticipate that it would be handled similar to how the network cameras work without any additional configuration option.  When users start Motion for network cameras and there is not a network available it will attempt to connect, fail and then it continues to try to reconnect until the network comes online.
