### ISSUE TITLE
Setup mode doesnt print to terminal

### ISSUE THREAD

**Issue by josvanr** [Motion-Project/motion#617]
Hello

I'm trying to run motion in setup mode but it doesnt seem to print much
to the terminal. Movies are recorded, and also stuff is written to the log.
Previously (in 14.04) this was written to the terminal, but now after 
upgrading, I only see:

root@hpux:/b/l1# motion -sc motion.conf
[7864704] [NTC] [ALL] conf_load: Processing thread 0 - config file motion.conf
[7864704] [NTC] [ALL] motion_startup: Motion 3.2.12+git20140228 Started with SDL support
[7864704] [NTC] [ALL] motion_startup: Logging to file (/var/log/motion/motion.log)

that's it

I also set daemon off
and setup_mode on

it seems to be reading the right config file, because all other settings seem to be
reflected in the recorded movies. 

For now I'm using tail -f on the log file...

Jos

-------------------------------------------------------------------

motion Version 3.2.12+git20140228
ubuntu 16.04
v4l cam
hp envy 17 2630QM

**Comment by Mr-Dave** [comment]
Jos, you may want to check your configuration file and also make sure to review the [support](https://motion-project.github.io/motion_support.html) and [guide](https://motion-project.github.io/motion_guide.html).  Note however that the version you referenced is four years old...

**Comment by josvanr** [comment]
4 years, ah..  hmm thnx maybe I should first try and compile the newest
one..
