### ISSUE TITLE
Ffmpeg output movie appears accelerated

### ISSUE THREAD

**Issue by josvanr** [Motion-Project/motion#618]
Hello,
I'm configuring motion with my webcam, and tried to use the mjpeg palette to get a better frame rate. With yu12 it maxes out at 5 fps. With mjpeg I manage to get 30 fps, but unfortunately, the movie output by ffmpeg now looks like a time lapse (both mplayer and vlc). When it records 1 minute (duration of the event), the output movie is only 7 seconds long. With yu12 everything appears normal.  Entries in the log file appear ok as far as I can tell. Any suggestions?

I attached my motion.conf, the log and the output from mplayer when I  play the file. 

1. version : 3.2.12+git20140228
2. installed as a package or compiled from sources : compiled from git
3. standalone or part of third party: motion
4. video stream source: v4l usb
5. hardware : x86
6. operating system : xubuntu 16.04
camera: logitech c920

[motion.3.conf.txt](https://github.com/Motion-Project/motion/files/1639256/motion.3.conf.txt)
[log.txt](https://github.com/Motion-Project/motion/files/1639257/log.txt)
[mplayer-output.txt](https://github.com/Motion-Project/motion/files/1639259/mplayer-output.txt)

**Comment by tosiara** [comment]
Please update to the latest version 4.1

**Comment by josvanr** [comment]
hello tosiara

I'm terribly sorry, apparently there was a mix up of 2 binaries. Thnx for pointing out the latest version. It seems to work now !
