### ISSUE TITLE
Makefile.in needs .PHONY: install

### ISSUE THREAD

**Issue by rotx** [Motion-Project/motion#620]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1+git20180111-999a374
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net (rtsp)
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: macOS

Under macOS 10.13 (High Sierra), compilation works fine (using `./configure --without-pgsql`), but the `make install` step fails. `Makefile.in` is missing a line that tells make that 'install' is not a file:
`.PHONY: install`
Without this, it will just say:
`make: 'install' is up to date.`

**Comment by Mr-Dave** [comment]
Thanks for reporting.  This has been pushed into the latest commit on the master branch.
