### ISSUE TITLE
Include all streams of camera in passthrough mode

### ISSUE THREAD

**Issue by RafisKh** [Motion-Project/motion#621]
Hi.
It would be very excellent if in stream from IP cameras, in passthrough mode, the soundtrack remained.
It is possible?

**Comment by Mr-Dave** [comment]
I am pretty sure it is possible but it would need to be submitted as a PR for consideration since it is not a current priority of the project.

**Comment by Mr-Dave** [comment]
Closing as there has been no PR provided.  An external script could always be created by the user and executed to provide the recording of all streams if desired.
