### ISSUE TITLE
Impossible to install motion on Ubuntu 16.04 Arm cpu

### ISSUE THREAD

**Issue by Marthinius** [Motion-Project/motion#623]
Hello everyone !!!

I followed the tutorial here : https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian.

My problem now is that when I run the command: **dpkg -i pi_jessie_motion_4.0.1-1_armhf.deb**

```
(wget https://github.com/Motion-Project/motion/releases/download/release-4.0.1/pi_jessie_motion_4.0.1-1_armhf.deb`

dpkg -i pi_jessie_motion_4.0.1-1_armhf.deb
Selecting previously unselected package motion.
(Reading database ... 76184 files and directories currently installed.)
Preparing to unpack pi_jessie_motion_4.0.1-1_armhf.deb ...
Unpacking motion (4.0.1-1) ...
dpkg: dependency problems prevent configuration of motion:
 motion depends on libavcodec56 (>= 6:11~beta1) | libavcodec-extra-56 (>= 6:11.7); however:
  Package libavcodec56 is not installed.
  Package libavcodec-extra-56 is not installed.
 motion depends on libavformat56 (>= 6:11~beta1); however:
  Package libavformat56 is not installed.
 motion depends on libavutil54 (>= 6:11~beta1); however:
  Package libavutil54 is not installed.
 motion depends on libjpeg62-turbo (>= 1.3.1); however:
  Package libjpeg62-turbo is not installed.
 motion depends on libmysqlclient18 (>= 5.5.24+dfsg-1); however:
  Package libmysqlclient18 is not installed.
 motion depends on libpq5; however:
  Package libpq5 is not installed.
 motion depends on libswscale3 (>= 6:11~beta1); however:
  Package libswscale3 is not installed.

dpkg: error processing package motion (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (229-4ubuntu21) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 motion)
```
I found this advice: https://github.com/ccrisan/motioneye/issues/530

But i dont know what command is:  **-f update to update dependencies**

Could you help with installation ?

**Comment by tosiara** [comment]
Would that help?
https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt/159114

**Comment by Marthinius** [comment]
I tried the command to correct dependencies: **sudo apt-get install -f**
But instead of repairing motion (4.0.1-1) , it offered me removal motion...
The only version I can install is motion (3.2.12+git20140228-8build1) 
Unfortunately, this version does not support rtsp authentification for Ip camera (no video) -motioneye. So I need a version 4 ...

**Comment by genius3000** [comment]
You're trying to install a package built for Debian Jessie on Ubuntu Xenial. As well as an old version already.  
Have a look at the [releases page](https://github.com/Motion-Project/motion/releases)
You should use the 4.1.1 release built for xenial for your CPU (arm64).

**Comment by Mr-Dave** [comment]
It would probably be best to read **our** instructions for installing and reporting issues on github
https://motion-project.github.io/motion_support.html
