### ISSUE TITLE
Motion 4.0-1 on Ubuntu armhf  with Image Xenial

### ISSUE THREAD

**Issue by Marthinius** [Motion-Project/motion#625]
Hello,
i'm running motion on a **OrangePi one** with Ubuntu Image (**Xenial** 16.04). OrangePi One is Computer **armhf.**
The installed motion version is 3.2.12+git20140228.
Is it possible to Update to motion Version 4.0.1? I didn't find a binary...
I need it (rtsp authentification error with 3.2 motion version)
Can somebody help?

Best regards

Martin

**Comment by Mr-Dave** [comment]
You would need to build this yourself.  See support page, https://motion-project.github.io/motion_support.html or script referenced in download section https://motion-project.github.io/motion_download.html or the building guide https://motion-project.github.io/motion_build.html
