### ISSUE TITLE
Option to disable motion detection

### ISSUE THREAD

**Issue by lcharles123** [Motion-Project/motion#626]
Hello
I propose a inclusion of the value 0 to treshold in motion detection group
i.e.
threshold 0

so it will disable motion detection at all and the stream will be write to file (only as a movie, disabling output_pictures by default) directly.
I think with this change, fps and CPU load can be improved.
thanks!

**Comment by Mr-Dave** [comment]
How would this be different than pause?

**Comment by TopperBG** [comment]
Will save continuous to file and don't analyze for motion event. That's what I understand.
It's good point.

**Comment by Mr-Dave** [comment]
So, the request is to allow Motion to be a DVR?

**Comment by tosiara** [comment]
Set `emulate_motion on` and start motion with disabled motion detection switch `-m`

**Comment by tosiara** [comment]
But if you want to save even more cpu - use this instead of motion:
```
ffmpeg -i rtsp://camera/stream -acodec copy -vcodec copy movie.mp4
```

**Comment by Mr-Dave** [comment]
Closing as invalid.  The option/feature request seems to be available via the current configuration parameters.  emulate on, output_pictures off
