### ISSUE TITLE
Chmod && Chown for motion.conf

### ISSUE THREAD

**Issue by juxorevo** [Motion-Project/motion#627]
0 : ?
Version : 4.1 (docker) juxo/motion-raspbian
2 compiled from GIT
3. motion
4 rtsp
5 arm
6 raspbian

What's the correct chmod et chown for motion.conf ?

Because when I try to accès to the configuration via web browser on local:8080, i have blank page with no items to configure. But the web browser work correctly

regards

**Comment by Mr-Dave** [comment]
https://motion-project.github.io/motion_support.html
