### ISSUE TITLE
Access the binary motion images

### ISSUE THREAD

**Issue by andreburnier** [Motion-Project/motion#628]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: ?
2. installed as a package or compiled from sources [deb, rpm, git, other]: ?
3. standalone or part of third party [motion, MotionEyeOS, other]: MotionEyeOS
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: ?
5. hardware [x86, ARM, other]: Raspberry Pi 3B
6. operating system [16.04, Stretch, etc, FreeBSD, other]: MotionEyeOS

Hello,
I'm working on a artistic project that needs to track the motion of people on the camera, so I decided to try out MotioneyeOs. I sent this question to their github and they suggested asking here. I'm looking how to access - and save - the binary images of the motion tracking to get the silhouette of moving bodies. Something similar to this image: https://youtu.be/nP6yerqf6eY?t=4m23s
I've tested the debug files option available, but they don't work as I intend.

I'm no programming expert, so I'm not sure where and how I could tweak the code to access these images - or even if this is possible or not. Any help is appreciated.

**Comment by Mr-Dave** [comment]
There is an assumption that these type of images exist in the system.  Generally they do not and the Motion debug images are "created".  There are no plans to create any additional debug images similar to those referenced.  You are free to review the Motion code to implement your own changes to meet your needs.  img_norm is a fairly widely used variable name across the application that contains the image.
