### ISSUE TITLE
Video Strange Freeze

### ISSUE THREAD

**Issue by elcanux** [Motion-Project/motion#644]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1 amd64
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: use with motionEye 0.38
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam rtsp
5. hardware [x86, ARM, other]: amd64
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Debian 8.10

Net Cam are : 
1. SV3C IPCAM (Firmware V2.3.4.2103-S50-NTD-B20170508B) [1080P POE Dome IP Camera (SV-D02POE-1080P) ](http://www.sv3c.com/1080P-POE-Dome-IP-Camera-SV-D02POE-1080P-.html)
2. SV3C IPCAM (Firmware V2.3.4.2103-S50-NTD-B20170508B) [1080P POE Varifocal Bullet IP Camera (SV-B11VPOE-1080P)](http://www.sv3c.com/1080P-POE-Varifocal-Bullet-IP-Camera-SV-B11VPOE-1080P-.html)

Problem:
Hi, After a few days, randomly, one of camera starts to 'freeze' in motion, but if I connect to the camera directly I do not have this problem of freeze. 
To correct this, I have to relaunch motion and everything goes back in order for a few days...
I have the same freeze on motion 4.0
Below the 'freeze' capture
![camera-freeze](https://user-images.githubusercontent.com/1751626/36017837-a99c006c-0d79-11e8-9267-278b7f2da6ae.png)
Do you have an idea of the problem, a setting?

**Comment by elcanux** [comment]
I have found video encoder configuration on ipcam
![camera-video](https://user-images.githubusercontent.com/1751626/36021071-f761f738-0d84-11e8-903e-7b7c5e5e03f3.png)

**Comment by Mr-Dave** [comment]
Looks like a udp image rather than tcp.  

https://motion-project.github.io/motion_support.html
