### ISSUE TITLE
draw.c: new text size check incorrect

### ISSUE THREAD

**Issue by genius3000** [Motion-Project/motion#648]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1+git (latest master)
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: *
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 16.04

In the recent commit dbd7817 for text_scale a log message is added when the text would be too large for the image.  
When the video device is unavailable, it tries to add the text "UNABLE TO OPEN VIDEO DEVICE\nSINCE \<date\> \<time\>". On a 640x480 image (likely most others) this is incorrectly seen as too big and causes a lot of log spam along with no message added. Commenting out the `return 1;` and letting it draw shows the text on the image correctly as it previously did.
Perhaps the check was only considering bottom positioned text and this is set to add to the top.

**Comment by apiszcz** [comment]
See the text to large error on identical configuration that works in many places with prior version.

**Comment by Mr-Dave** [comment]
closed per recent PR
