### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by evilblade666** [Motion-Project/motion#651]
I'm trying to run motion on my Raspberry Pi 3 (on Raspbian Stretch). Tried installing it with apt-get, dpkg -i from a deb package and compiling it from source from here. But no matter how i install it I only get "Segmentation fault" when I run motion with _any_ keys. That's it, no additional info on what could cause the problem :( It doesn't even create a log file to look into.
Could someone sudjest what could _possibly_ be wrong?

P.S. Camera is USB (Playstation Eye if it matters). But I tried to run it without connecting the camera to USB port - same result.

**Comment by ccrisan** [comment]
A broken ffmpeg may cause motion to crash. Before compiling with debug info and collecting a crash backtrace (which is the normal thing to do in this case), I'd recommend making sure that ffmpeg itself doesn't crash.

**Comment by evilblade666** [comment]
It does! Says the same "segmentation fault".. guess this message actually came from it, not motion itself..
OK, thanks for the tip, will look further into...
