### ISSUE TITLE
No Jpeg Movies recorded by camera1 ( also camera2)

### ISSUE THREAD

**Issue by hgestel** [Motion-Project/motion#652]
Since installation of motion on RPI zero W,  I have no jpeg (snapshot link is made, but no jpeg) 
following message :  (many of them)
netcam_init_jpeg: no new pic, no signal rcvd 
in log file /var/log/motion.log.
version info:
motionEye Version | 0.38
Motion Version | 4.1
OS Version | Raspbian 9.3
What can I do to find rootcause?

**Comment by Mr-Dave** [comment]
https://motion-project.github.io/motion_support.html
