### ISSUE TITLE
Downloading video clips to ipad

### ISSUE THREAD

**Issue by Rowleygreen** [Motion-Project/motion#653]
i have motioneye on running on rasberry Pi zero
Very good apart from when I download video files they have a double ending 
I.e. *.mp4.mpg
The files type is not recognised by either my mac desktop or iPad so I cannot run them
I can download the files to iCloud but , 
I tried deleting the .mpg part or the .mp4 part either way the ending is reinstated by my iPad
Please can you give me detail of a solution.

**Comment by Mr-Dave** [comment]
https://motion-project.github.io/motion_support.html

**Comment by ccrisan** [comment]
@Rowleygreen this is (was) a [motionEye](https://github.com/ccrisan/motioneye) bug recently fixed in https://github.com/ccrisan/motioneye/commit/a765b701c80d65305cbcf794accaacd63b705cdf. You should upgrade to 0.38.1.

**Comment by Rowleygreen** [comment]
Hi
I appreciate your helpful reply and like the application a lot , thanks for all your work.
I pressed update software in motioneye install on my rasp Pi zero from remote log in over internet. The s/w updated from 0.36.1 to 0.37.1. It now says s/w is up to date!
How can I get it to move to 0.38.1 please?

Regards
John Sharman

**Comment by ccrisan** [comment]
@Rowleygreen are you sure you're not on motionEyeOS instead of motionEye? If that's the case, you'll have to wait till the next release (no, there's no ETA).
