### ISSUE TITLE
lastsnap.jpg missing

### ISSUE THREAD

**Issue by leoheck** [Motion-Project/motion#659]
0. Reviewed guide and contributing documents? (Yes/No): **No**, I would like to contribute with the manpage.
1. version [x.y.z, hash, other]: **4.1 (or 4.1.1, I don't know for sure, the --v shows 4.1 but I thought I was using the last version)**
2. installed as a package or compiled from sources [deb, rpm, git, other]: **built it myself**
3. standalone or part of third party [motion, MotionEyeOS, other]: **standalone**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **HD Pro Webcam C920**
5. hardware [x86, ARM, other]: RPi3 (armv7l)
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian 9.3 (Stretch)

Hi, I don't know if I am doing something wrong but I don't have a symbolic link pointing to the last picture. Also, I could not pass the image name to my script using `"%f"` on `on_event_end` event. 

What I am trying to do. I would like to be notified when a movie ends, Then, I would like to send a picture to me. This is why I am looking for the `laststnap.jpg`. If I can use this `laststnap.jpg` I can avoid the `%f`.

**Comment by leoheck** [comment]
The "%f" --> filename with fullpath does not work.

**Comment by tosiara** [comment]
Snapshot is not a picture saved by motion during an event. Snapshot is made using http api or through the web control interface

**Comment by tosiara** [comment]
`on_event_end` is executed when event is finished, so you know when event has finished
If you want to get picture - use ` on_picture_save`

**Comment by leoheck** [comment]
@tosiara thanks for the explanation about the snapshot.

I will also try that on `image_save`.

But I would like to have a single picture when the movie ends. However the `"%f"` is empty in this case.
My `motion.conf` has this:
```
############################################################
# External Commands, Warnings and Logging:
# You can use conversion specifiers for the on_xxxx commands
# %Y = year, %m = month, %d = date,
# %H = hour, %M = minute, %S = second,
# %v = event, %q = frame number, %t = camera id number,
# %D = changed pixels, %N = noise level,
# %i and %J = width and height of motion area,
# %K and %L = X and Y coordinates of motion center
# %C = value defined by text_event
# %f = filename with full path <============================= LOOK HERE
# %n = number indicating filetype
# Both %f and %n are only defined for on_picture_save, <===== LOOK HERE
# on_movie_start and on_movie_end <========================== LOOK HERE
# Quotation marks round string are allowed.
############################################################
```

Is this a bug or am I understanding it wrong?

Ah, it will be nice to have a symbolic link to the last_image and the last_movie too.

**Comment by leoheck** [comment]
Oh, so I am closing this because I am retarded. thanks @tosiara .

**Comment by majuss** [comment]
I also don't have a lastsnap :( I'am taking 15 pictures per second.
