### ISSUE TITLE
ffmpeg_mov issue

### ISSUE THREAD

**Issue by Olegone23** [Motion-Project/motion#667]
0. Reviewed guide and contributing documents? (Yes/No):
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
3. standalone or part of third party [motion, MotionEyeOS, other]: 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: 
6. operating system [16.04, Stretch, etc, FreeBSD, other]:

**Comment by Olegone23** [comment]
Motion ver: 3.2.12 (badly need the one):
No way to save movies in 'mov' format, help pls. where to dig.
Log below:

Mar  5 18:17:51 AstraBox14 motion: [0] Motion 3.2.12 Started
Mar  5 18:17:51 AstraBox14 motion: [0] ffmpeg LIBAVCODEC_BUILD 3482368 LIBAVFORMAT_BUILD 3478785
Mar  5 18:17:51 AstraBox14 motion: [0] Thread 1 is from thread-1.conf
Mar  5 18:17:51 AstraBox14 motion: [0] Thread 2 is from thread-2.conf
Mar  5 18:17:51 AstraBox14 motion: [0] motion-httpd/3.2.12 running, accepting connections
Mar  5 18:17:51 AstraBox14 motion: [0] motion-httpd: waiting for data on port TCP 7999
Mar  5 18:17:51 AstraBox14 motion: [2] Thread 2 started
Mar  5 18:17:51 AstraBox14 motion: [2] Camera thread starting...
Mar  5 18:17:51 AstraBox14 motion: [1] Thread 1 started
Mar  5 18:17:51 AstraBox14 motion: [1] Camera thread starting...
Mar  5 18:17:51 AstraBox14 motion: [2] Streaming camera
Mar  5 18:17:51 AstraBox14 motion: [2] Boundary string [boundarydonotcross]
Mar  5 18:17:51 AstraBox14 motion: [2] Resizing pre_capture buffer to 1 items
Mar  5 18:17:51 AstraBox14 motion: [2] Camera handler thread [3]  started
Mar  5 18:17:51 AstraBox14 motion: [2] Started stream webcam server in port 8082
Mar  5 18:17:51 AstraBox14 motion: [2] Resizing pre_capture buffer to 21 items
Mar  5 18:17:51 AstraBox14 motion: [2] netcam_next called with no data in buffer
Mar  5 18:17:51 AstraBox14 motion: [1] Streaming camera
Mar  5 18:17:51 AstraBox14 motion: [1] Boundary string [myboundary]
Mar  5 18:17:51 AstraBox14 motion: [2] netcam_next called with no data in buffer
Mar  5 18:17:51 AstraBox14 motion: [2] netcam_next called with no data in buffer
Mar  5 18:17:51 AstraBox14 motion: [1] Resizing pre_capture buffer to 1 items
Mar  5 18:17:51 AstraBox14 motion: [1] Camera handler thread [4]  started
Mar  5 18:17:51 AstraBox14 motion: [1] Started stream webcam server in port 8081
Mar  5 18:17:51 AstraBox14 motion: [1] Resizing pre_capture buffer to 21 items
Mar  5 18:17:51 AstraBox14 motion: [2] netcam_next called with no data in buffer
Mar  5 18:17:51 AstraBox14 motion: [1] netcam_next called with no data in buffer
Mar  5 18:18:06 AstraBox14 motion: [1] ffmpeg_avcodec_log: err{or,}_recognition separate: 1; 1#012 - flag 48
Mar  5 18:18:06 AstraBox14 motion: [1] ffmpeg_avcodec_log: err{or,}_recognition combined: 1; 1#012 - flag 48
Mar  5 18:18:06 AstraBox14 motion: [1] ffmpeg_avcodec_log: broken ffmpeg default settings detected#012 - flag 16
Mar  5 18:18:06 AstraBox14 motion: [1] ffmpeg_avcodec_log: use an encoding preset (e.g. -vpre medium)#012 - flag 16
Mar  5 18:18:06 AstraBox14 motion: [1] ffmpeg_avcodec_log: preset usage: -vpre <speed> -vpre <profile>#012 - flag 16
Mar  5 18:18:06 AstraBox14 motion: [1] ffmpeg_avcodec_log: speed presets are listed in x264 --help#012 - flag 16
Mar  5 18:18:06 AstraBox14 motion: [1] ffmpeg_avcodec_log: profile is optional; x264 defaults to high#012 - flag 16
Mar  5 18:18:06 AstraBox14 motion: [1] avcodec_open - could not open codec: Operation now in progress
Mar  5 18:18:06 AstraBox14 motion: [1] ffopen_open error creating (new) file [/var/lib/motioneye/Camera1/2018-03-05/18-18-06.mov]: Operation now in progress
Mar  5 18:18:06 AstraBox14 motion: [1] Calling vid_close() from motion_cleanup
Mar  5 18:18:06 AstraBox14 motion: [1] vid_close: calling netcam_cleanup
Mar  5 18:18:06 AstraBox14 motion: [1] netcam camera handler: finish set, exiting

**Comment by tosiara** [comment]
Use latest motion, it supports mov:
```
# Container/Codec output videos
# Valid values: mpeg4, msmpeg4, swf,flv, ffv1, mov, mp4, mkv, hevc
ffmpeg_video_codec mkv
```

**Comment by Olegone23** [comment]
Do u have any other solutions, I really need version 3.2.12?

**Comment by tosiara** [comment]
Sorry, no. If you want to keep using this old version - select another available codec

**Comment by Olegone23** [comment]
Could u know what file to check for the issue?(motion c++)

**Comment by Olegone23** [comment]
I mean I have no time to compare all files from old to new version of motion

**Comment by tosiara** [comment]
Difference is so huge, you won't be able to compare anything. You can look into ffmpeg.c  as start point
Also, you can try extpipe - this supports external encoder
https://github.com/Motion-Project/motion/blob/master/motion-dist.conf.in#L289

**Comment by Olegone23** [comment]
Thank u! I will try, my first idea was create a  service which will convert from one format to mov!
