### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by totovr** [Motion-Project/motion#670]
0. Reviewed guide and contributing documents? (Yes):
1. version [4.0]: 
2. installed as a package or compiled from sources [other]: 
3. standalone or part of third party [motion]: 
4. video stream source [other]: 
5. hardware [ARM]: 
6. operating system [Raspbian]:

Hello! I followed the [next tutorial](https://hackernoon.com/spy-your-pet-with-a-raspberry-pi-camera-server-e71bb74f79ea) to setup the software in a Raspberry Pi 3 with the Pi camera, but when I access to the server I cant see any streaming

**Comment by tosiara** [comment]
The tutorial is wrong. Setting `webcontrol_port 8081` will enable control web page on port 8081, not streaming. The default settings are:
```
stream_port 8081
webcontrol_port 8080
```

**Comment by totovr** [comment]
I note that after changed it yesterday! now I could setup the server in a ***Raspberry 3***

![screenshot from 2018-03-09 23-01-48](https://user-images.githubusercontent.com/15333235/37211020-ef5d1df4-23ed-11e8-85ba-977561465c45.png)

**Comment by tosiara** [comment]
You will be only able to see this preview at web control page in browse (port 8080)
If you want to see live stream in VLC - you must use stream port (8081)
