### ISSUE TITLE
Get continuous images 

### ISSUE THREAD

**Issue by Unbekannter** [Motion-Project/motion#671]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: master
2. installed as a package or compiled from sources [deb, rpm, git, other]: source git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: usb
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  ubuntu (raspbian)

I tried to get continuous images from motion (without detection), but all variants which are documentated doesn't works.

If i set emulate_motion on, i get continuous images but only after 15 seconds.
But if i set snapshot_interval to 1, it starts directly but only one picture per second. 
After 15 seconds with this option activated and emulate_motion is on, i get continuous images.

Why can i get only one image per second with snapshot and its start directly, but the emulate_motion which delivers more images starts only after 15 seconds?

Or is there any way to set snapshot time under 1 second? Or milli seconds instead of seconds?

Greets

**Comment by Mr-Dave** [comment]
Have you reviewed the logs with timestamps to determine what process is taking too long?  (When log is routed to a file via the configuration option, it includes a timestamp)
