### ISSUE TITLE
Can't build v4.1 on Raspberry

### ISSUE THREAD

**Issue by hannesa2** [Motion-Project/motion#677]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]: **4.1**
2. installed as a package or compiled from sources [deb, rpm, git, other]: **git**
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: USB
5. hardware [x86, ARM, other]: **armv6l** and **armv7l**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Rasperian Stretch

Following the install instruction https://rawgit.com/Motion-Project/motion/master/motion_build.html

```
sudo apt-get install autoconf automake build-essential pkgconf libtool libzip-dev libjpeg-dev git libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libavdevice-dev libwebp-dev
cd ~
git clone https://github.com/Motion-Project/motion.git
git checkout origin/4.1
cd motion
autoreconf -fiv
./configure
make
```

I run into 

> Linking Motion...
> --------------------------------------------------------------------------------
> gcc  -o motion motion.o logger.o conf.o draw.o jpegutils.o video_loopback.o video_v4l2.o video_common.o video_bktr.o netcam.o netcam_http.o netcam_ftp.o netcam_jpeg.o netcam_wget.o track.o alg.o event.o picture.o rotate.o webhttpd.o stream.o md5.o netcam_rtsp.o ffmpeg.o mmalcam.o raspicam/RaspiCamControl.o raspicam/RaspiCLI.o  -lm  -pthread -ljpeg -lpq    -L/opt/vc/lib -lmmal_core -lmmal_util -Wl,--push-state,--no-as-needed -lmmal_vc_client -Wl,--pop-state -lvcos -lvchostif -lvchiq_arm -L/usr/local/lib -lavdevice -lavfilter -lswscale -lpostproc -lavformat -lavcodec -lvorbisenc -lvorbis -ltheoraenc -ltheoradec -logg -lspeex -lrtmp -lgmp -lopencore-amrwb -lopencore-amrnb -lmp3lame -lfdk-aac -lass -lz -pthread -lswresample  -lavutil -lm  
> /usr/bin/ld: cannot find -lass
> collect2: error: ld returned 1 exit status

any ideas how to get rid of it ?

**Comment by Mr-Dave** [comment]
I have not seen this issue before and I build the releases directly on PI's using the script shown without any issue.

It is a lib associated with ffmpeg so I would suggest trying to reboot....maybe install the regular ffmpeg application (`apt-get install ffmpeg`).  Make sure that running ffmpeg standalone isn't reporting any problems....

Also, if you are just looking for the version 4.1 without any of the revisions, this has already been packaged for a pi and is on our releases page.  See the section immediately above the the section you referenced in the guide for how to install from a deb file.

**Comment by tosiara** [comment]
```
libass is a portable subtitle renderer for the ASS/SSA (Advanced Substation Alpha/Substation Alpha) subtitle format
```
Your ffmpeg was built with a dependancy on `libass`, try installing it `apt-get install libass-dev` and rerun make

**Comment by hannesa2** [comment]
@tosiara Thank you, your recommendation solved it
