### ISSUE TITLE
Version generated is one day behind

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#683]
That doesn't make sense to me:
```
$ date
Mon Mar 26 11:17:05 EEST 2018
$ ./version.sh
4.1.1+git20180325-f3d5dc8
```
Why the build's version has "yesterday" date?

**Comment by genius3000** [comment]
It's using the date of the last commit:
```
9:    GIT_COMMIT=$GIT_COMMIT`git show -s --date=format:'%Y%m%d' --format=%cd-%h` 2>/dev/null
```
I believe it's preferred this way (over actual build date) for reproducible builds (for packaging, etc).

**Comment by tosiara** [comment]
Ah, ok. That confused me a bit
