### ISSUE TITLE
netcam image width (1277) is not modulo 16

### ISSUE THREAD

**Issue by Olegone23** [Motion-Project/motion#684]
Dear support,

Seesm stuck with "netcam image width (1277) is not modulo 16" issue, motion version 3.2.12.
I thought the issue is already fixed.

Could u pls. show the way where to dig in???

Kind Regards,
Oleg

**Comment by tosiara** [comment]
Update to the latest version 4.x

**Comment by Olegone23** [comment]
Sorry, can't do that! Need this version, for old Linux build.
Would you be so kind to propose a way to resolve the issue?

Kind Regards,
Oleg

**Comment by tosiara** [comment]
Unfortunately, no. If you want to use the old version - please use supported resolution

**Comment by Olegone23** [comment]
it means that 1920 X 1080 is a limit?

**Comment by tosiara** [comment]
There is no limit. It's just 1920x1080 not compatible.
```
1920/16=120
1080/16=67.5
```
You can only use resolution where both numbers cam be divided by 16
For example, 800x600 is also not supported by the old version, while 1920x1200 or 4096x2160 are supported

**Comment by Olegone23** [comment]
If I try to correct netcam.c and picture.c files,  is it reasonable?

Kind Regards,
Oleg

**Comment by tosiara** [comment]
You can try, why not?

**Comment by tosiara** [comment]
You said that you want to use old version, but now you want to change it?
You will have to implement image padding. Otherwise you will get crashes. Look at this change a start point: https://github.com/Motion-Project/motion/commit/bfbfebadccfa68403fe769ffc6555a72f8319f75. There may be more changes related, search the entire git log manually

**Comment by Olegone23** [comment]
Thks and Rrds, for detailed explanation!
