### ISSUE TITLE
Could not be installed after the last Raspbian X64 update upgrade

### ISSUE THREAD

**Issue by ConsGab** [Motion-Project/motion#685]
0. Reviewed guide and contributing documents? (Yes/No): yves
1. version [x.y.z, hash, other]: pi_stretch_motion_4.1.1-1_armhf.deb
2. installed as a package or compiled from sources [deb, rpm, git, other]:  from deb
3. standalone or part of third party [motion, MotionEyeOS, other]: Motion on Raspbian
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Stretch; Update and upgrade today.

Dear support, 
Hello every one, 
I am not abble to install motion after the last uptdate and upgrade, I did one hour before.
Please find the following messages, Could you help me, I don't know what I can do.

Kind Regards,

***************
 $ sudo  apt-get install ffmpeg v4l-utils
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
v4l-utils is already the newest version (1.12.3-1).
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation :

Les paquets suivants contiennent des dépendances non satisfaites :
 ffmpeg : Dépend: libavcodec57 (>= 7:3.2.10) mais ne sera pas installé ou
                   libavcodec-extra57 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libavdevice57 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libavfilter6 (>= 7:3.2.10) mais ne sera pas installé ou
                   libavfilter-extra6 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libavformat57 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libavresample3 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libavutil55 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libpostproc54 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libsdl2-2.0-0 (>= 2.0.4) mais il n'est pas installable
          Dépend: libswresample2 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libswscale4 (>= 7:3.2.10) mais ne sera pas installé
          Dépend: libva1 (>= 1.7.3) mais il n'est pas installable
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
************************
 $ sudo  dpkg -i pi_stretch_motion_4.1.1-1_armhf.deb
Sélection du paquet motion précédemment désélectionné.
(Lecture de la base de données... 34510 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de pi_stretch_motion_4.1.1-1_armhf.deb ...
Dépaquetage de motion (4.1.1-1) ...
dpkg: des problèmes de dépendances empêchent la configuration de motion :
 motion dépend de libavcodec57 (>= 7:3.2.9) | libavcodec-extra57 (>= 7:3.2.9) ; cependant :
  Le paquet libavcodec57 n'est pas installé.
  Le paquet libavcodec-extra57 n'est pas installé.
 motion dépend de libavdevice57 (>= 7:3.2.9) ; cependant :
  Le paquet libavdevice57 n'est pas installé.
 motion dépend de libavformat57 (>= 7:3.2.9) ; cependant :
  Le paquet libavformat57 n'est pas installé.
 motion dépend de libavutil55 (>= 7:3.2.9) ; cependant :
  Le paquet libavutil55 n'est pas installé.
 motion dépend de libmariadbclient18 (>= 5.5.36) ; cependant :
  Le paquet libmariadbclient18 n'est pas installé.
 motion dépend de libpq5 ; cependant :
  Le paquet libpq5 n'est pas installé.
 motion dépend de libswscale4 (>= 7:3.2.9) ; cependant :
  Le paquet libswscale4 n'est pas installé.

dpkg: erreur de traitement du paquet motion (--install) :
 problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour systemd (232-25+deb9u2) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.6.1-2) ...
Des erreurs ont été rencontrées pendant l'exécution :
 motion

**Comment by Mr-Dave** [comment]
Please make sure to use the instructions on how to install from OUR build [guide](https://motion-project.github.io/motion_build.html)

The following is not correct.  `sudo dpkg -i pi_stretch_motion_4.1.1-1_armhf.deb'

**Comment by ConsGab** [comment]
I am going to follow the instructions of your link.
Thanks
