### ISSUE TITLE
Allow mask_privacy to be removed from live stream

### ISSUE THREAD

**Issue by kimmogensen** [Motion-Project/motion#688]
Hi developers

My feature request is related to the mask feature. Would it be possible to add a subfeature to the mask, so the user in some way can define the mask and then decide if the mask should:
1) mask motion (as it works now)
2) mask recordings
3) mask live picture
Each setting ideally configurable by the user without bindings between the settings.

In my country (Denmark), citizens may only store recordings from cccams showing ground on your own perimeter. It is not allowed to store recordings from public areas though it is allowed to watch the stream directly without mask.

I have done some research on google, and did not find any other software with this feature, so I guess it could give the Motioneye OS an edge...

Thank you for excellent work!

Best regards
Kim Mogensen

**Comment by Mr-Dave** [comment]
The configuration option of [mask_file](https://motion-project.github.io/motion_config.html#mask_file) I think addresses request 1.  

The option of [mask_privacy](https://motion-project.github.io/motion_config.html#mask_privacy) I believe addresses request 2.  Note that this option may or may not be within the Motioneye application.  Motioneye is a different project/application that wraps around this application.  The option is however completely functional when running Motion as a standalone application.   

The third request is the only one I believe can not currently be accomplished.  Apply a privacy mask to the recorded files/pictures but view via the web interface the un-masked files.  

Correct?

**Comment by kimmogensen** [comment]
Hello Mr-Dave

That's exactly how it is!.  And especially option 2 is a keybreaker for me
to start up my little surveillance investment, using 4 raspberry with
camera. About the third option, I understand that it is currently
unavailable. Seeing the picture online without the mask(s). It could be
solved by installing another camera preferably into the same housing. And
then there is fallback on the system :-)

I was sent to this project by Mr. Calin Crisan, I see you have it
implemented, so now I will aim for using your framework as standalone on
one path, another path is to dive more into the MotionEyeOS project to see
if I missed something.

Great job you guys do, it's truly appreciated.

Best Regards
Kim Mogensen

**Comment by Mr-Dave** [comment]
Completed

**Comment by Zw1d** [comment]
> Completed

Do you mean it should now mask the live stream? Doesn't seem to work in my case.
