### ISSUE TITLE
WebUI sometimes shows incorrect values for individual camera configs

### ISSUE THREAD

**Issue by genius3000** [Motion-Project/motion#691]
0. Reviewed guide and contributing documents? (Yes/No): **Yes**
1. version [x.y.z, hash, other]:  **4.1.1+git20180325-f3d5dc8**
2. installed as a package or compiled from sources [deb, rpm, git, other]: **git**
3. standalone or part of third party [motion, MotionEyeOS, other]: **motion**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **mjpeg**
5. hardware [x86, ARM, other]: **x86**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: **Ubuntu 16.04**

I noticed that viewing the configuration with a single camera selected, things like `camera_id` and `rotate` show the main config values and not the correct camera values.  
I believe I've narrowed this down to just integers or specifically any config param using `copy_int` and `print_int`. In `webu.c : webu_html_config()`, `val_main` calls `print_int` to get the main thread value and then `val_thread` calls `print_int` for each thread. Problem is, `print_int` must be returning the same buffer each time, therefore `val_main == val_thread` for anything from `print_int`.  
I'd like to leave this to @Mr-Dave and/or the other maintainers to decide if `print_int` should be re-worked or just handle it with a copy in `webu_html_config()`.

**Comment by Mr-Dave** [comment]
We'll make a copy of the parm values in `webu_html_config`
