### ISSUE TITLE
Motion 3.12 or older

### ISSUE THREAD

**Issue by Olegone23** [Motion-Project/motion#697]
0. Reviewed guide and contributing documents? (Yes/No):
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
3. standalone or part of third party [motion, MotionEyeOS, other]: 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: 
6. operating system [16.04, Stretch, etc, FreeBSD, other]:

**Comment by Olegone23** [comment]
Hi Tosiara,
Is it possible to find a motion version with RTSP support (may be make it from source), the main point is the that OS must be: Wheezy or   Precise.  I've tried several ones but without success the issue is that libc6 must be higher then 2.13 .  
Any suggestions are  appreciated . 
Thks&Rgrds, 
Oleg

**Comment by tosiara** [comment]
> libc6 must be higher then 2.13

Where did this requirement come from?

**Comment by Olegone23** [comment]
Just check the dependencies file in (deb). 
Also I can't see   netcam_rtsp.c, netcam_rtsp.h files  in any 3.12 versions of motion.
But if we look at version 3.4.1 we can find there netcam_rtsp.c, netcam_rtsp.h
Means rtsp could work only from the 3.4.1 version? And what's about MrDave version of motion?
Kind Regards,
Oleg

**Comment by tosiara** [comment]
Why can't you compile 4.x version from sources?

**Comment by Olegone23** [comment]
But do u realy think libc6 (2.13)  will be enough to make version 4 from sources?

**Comment by Olegone23** [comment]
As I mentioned upper my linux versions are Wheezy or Precise (core), that is my concern!

**Comment by tosiara** [comment]
Why do you think there is a restriction on which libc version you have?

**Comment by Olegone23** [comment]
I've tried to install all versions upper 3.2.12 (precompiled) and all depends on libc6 >=2.15.
But may be I am wrong?
Kind Regards,
Oleg

**Comment by tosiara** [comment]
I'm talking about compiling from sources

**Comment by Olegone23** [comment]
ok, got u, let me try to compile version 4 from sources. So I am still  not so familar with linux sorry.
But which repositories u could suggest?
Kind Regards,

**Comment by tosiara** [comment]
I know for sure that on Ubuntu 12 motion compiles just out of the box. Follow the installation manual that is available in readme

**Comment by Olegone23** [comment]
Thank u. Pls. close the ticket!
