### ISSUE TITLE
issue with FFMPEG while making from source

### ISSUE THREAD

**Issue by Olegone23** [Motion-Project/motion#698]
0. Reviewed guide and contributing documents? (Yes/No):
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
3. standalone or part of third party [motion, MotionEyeOS, other]: 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: 
6. operating system [16.04, Stretch, etc, FreeBSD, other]:

**Comment by Olegone23** [comment]
Hi Tosiara,
I am trying to compile the motion from source and get following issue, could u pls. advice what to check?

Motion version: 3.4; 4.0; 4.1

\"/usr/local/etc\"     -c -o ffmpeg.o ffmpeg.c
ffmpeg.c: In function ‘get_oformat’:
ffmpeg.c:151:35: error: ‘CODEC_ID_MPEG2VIDEO’ undeclared (first use in this function)
ffmpeg.c:151:35: note: each undeclared identifier is reported only once for each function it appears in
ffmpeg.c:159:35: error: ‘CODEC_ID_MSMPEG4V2’ undeclared (first use in this function)
ffmpeg.c:166:27: error: ‘CODEC_ID_FLV1’ undeclared (first use in this function)
ffmpeg.c:170:35: error: ‘CODEC_ID_FFV1’ undeclared (first use in this function)
ffmpeg.c:180:25: error: ‘CODEC_ID_H264’ undeclared (first use in this function)
ffmpeg.c: In function ‘ffmpeg_open’:
ffmpeg.c:261:45: error: ‘CODEC_ID_NONE’ undeclared (first use in this function)
ffmpeg.c:295:24: error: ‘CODEC_ID_H264’ undeclared (first use in this function)

Kind Reagrds,
Oleg

**Comment by tosiara** [comment]
Try to compile ffmpeg from sources too. Follow this instruction: https://github.com/tosiara/motion/wiki/ffmpeg

**Comment by Mr-Dave** [comment]
Looks resolved.
