### ISSUE TITLE
jpgutl_error_exit: Unsupported marker type 0x3c

### ISSUE THREAD

**Issue by Uatschitchun** [Motion-Project/motion#699]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: motion 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: DEB
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L
5. hardware [x86, ARM, other]: i386
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  Xenial (16.04)

```
Apr  7 10:37:22 atom motion: [1:ml1] [ERR] [ALL] jpgutl_error_exit: Unsupported marker type 0x3d
Apr  7 10:37:22 atom motion: [1:ml1] [CRT] [VID] vid_mjpegtoyuv420p: Corrupt image ... continue
```

Result is, no vids are created if motion is detected ;(

Version 4.1 crashes with:
```
Apr  7 10:32:54 atom motion: [1:ml1] [ERR] [ALL] jpgutl_error_exit: Unsupported marker type 0x40
Apr  7 10:32:54 atom kernel: [ 6895.006085] show_signal_msg: 39 callbacks suppressed
Apr  7 10:32:54 atom kernel: [ 6895.006102] ml1[12830]: segfault at 8e0f0000 ip 8e0f0000 sp af782b6c error 14
```
If more infos are needed, let me know

**Comment by Uatschitchun** [comment]
```
Apr  7 11:08:10 atom motion: [1:ml1] [ERR] [ALL] jpgutl_error_exit: Unsupported marker type 0x4d
Apr  7 11:08:10 atom motion: [1:ml1] [CRT] [VID] vid_mjpegtoyuv420p: Corrupt image ... continue
Apr  7 11:08:44 atom motion: [1:ml1] [ERR] [ALL] jpgutl_error_exit: Unsupported marker type 0x4c
Apr  7 11:08:44 atom motion: [1:ml1] [CRT] [VID] vid_mjpegtoyuv420p: Corrupt image ... continue
Apr  7 11:08:47 atom motion: [1:ml1] [ERR] [ALL] jpgutl_error_exit: Unsupported marker type 0x4d
Apr  7 11:08:47 atom motion: [1:ml1] [CRT] [VID] vid_mjpegtoyuv420p: Corrupt image ... continue
```

**Comment by Uatschitchun** [comment]
I had
`output_pictures best` 
in my conf. Changed that to "on" and the error seems gone !?

**Comment by Mr-Dave** [comment]
There were a few changes. Can you build from source to see if the issue remains?  General building instructions are in the [build guide](https://motion-project.github.io/motion_build.html)  Or if you want to create your own deb file, there is a link to a build script on the main [download page](https://motion-project.github.io/motion_download.html).

**Comment by tosiara** [comment]
Can you provide the full log and your config?

**Comment by Uatschitchun** [comment]
paste.ubuntu.com/p/VtcyGjJpV3/

**Comment by tosiara** [comment]
And which camera are you using? vid:pid?

**Comment by Uatschitchun** [comment]
uvcvideo: Found UVC 1.00 device WC060 Series HD Webcam (177f:0060)

**Comment by Uatschitchun** [comment]
And is it correct, that only the first taken picture of a timelapse movie gets written into log? 
And with snapshots, is it also correct, that if I set the interval to 1 snapshot per day (86400s), the first snapshot gets written 1 day after starting motion?

**Comment by Mr-Dave** [comment]
I will let you experiment with the timelapse/snapshot interval.  If there are updates needed to the guide on these, please feel free to submit a PR on the guide.  

With respect to the "errors" reported in the log, this looks like intermittent problems decoding a few of the frames from the camera.  Could be bandwidth or firmware issues.  Generally, these get reported for each and every frame that is missed and I've contemplating just putting them at the debug notification level.  

If you want, you can try the other palette option which is listed for your camera(see guide).  This would however use more bandwidth on the USB hub which may or may not pose an issue with your computer.  i.e. Use mjpg and have compressed images that may send to Motion a few corrupt frames but use less bandwidth or use the palette option for 422 format and have uncompressed images.

**Comment by Uatschitchun** [comment]
Ok, changed palette to YUYV and the corrupt image messages are gone. Had a little fear, as I'm using a DVB-S receiver on that USB-Hub, too, but all seems fine.

**Comment by tosiara** [comment]
Can you grab a single raw jpeg frame, zip it and share here?
For example, you can use this code: https://github.com/tosiara/v4l-capture-bench
`./v4l2-capture -c 1 -o 1> test.jpg`

**Comment by tosiara** [comment]
Check what was your current pixel format: `v4l2-ctl --all`
If it is not MJPEG, set it before capturing: `v4l2-ctl -v width=1280,height=720,pixelformat=0`

**Comment by Uatschitchun** [comment]
```
Driver Info (not using libv4l2):
        Driver name   : uvcvideo
        Card type     : WC060 Series HD Webcam
        Bus info      : usb-0000:00:04.1-3
        Driver version: 4.4.117
        Capabilities  : 0x84200001
                Video Capture
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps   : 0x04200001
                Video Capture
                Streaming
                Extended Pix Format
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
        Width/Height      : 1280/960
        Pixel Format      : 'MJPG'
        Field             : None
        Bytes per Line    : 0
        Size Image        : 2457600
        Colorspace        : sRGB
        Transfer Function : Default
        YCbCr Encoding    : Default
        Quantization      : Default
        Flags             :
Crop Capability Video Capture:
        Bounds      : Left 0, Top 0, Width 1280, Height 960
        Default     : Left 0, Top 0, Width 1280, Height 960
        Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 1280, Height 960
Selection: crop_bounds, Left 0, Top 0, Width 1280, Height 960
Streaming Parameters Video Capture:
        Capabilities     : timeperframe
        Frames per second: 15.000 (15/1)
        Read buffers     : 0
                     brightness (int)    : min=-10 max=10 step=1 default=0 value=0
                       contrast (int)    : min=0 max=20 step=1 default=10 value=10
                     saturation (int)    : min=0 max=10 step=1 default=5 value=5
 white_balance_temperature_auto (bool)   : default=1 value=1
                          gamma (int)    : min=100 max=200 step=1 default=150 value=150
                           gain (int)    : min=32 max=48 step=1 default=34 value=34
           power_line_frequency (menu)   : min=0 max=2 default=1 value=2
      white_balance_temperature (int)    : min=2800 max=6500 step=1 default=6500 value=6500 flags=inactive
                      sharpness (int)    : min=0 max=10 step=1 default=4 value=4
         backlight_compensation (int)    : min=0 max=2 step=1 default=0 value=0
                  exposure_auto (menu)   : min=0 max=3 default=3 value=3
              exposure_absolute (int)    : min=8 max=16384 step=1 default=512 value=512 flags=inactive
```
[test.zip](https://github.com/Motion-Project/motion/files/1912445/test.zip)

**Comment by tosiara** [comment]
I can open and view your image, however jpeginfo reports the image is corrupted:
```
$ jpeginfo -c test.jpg
test.jpg 1280 x 960  24bit n/a   N  311048  Corrupt JPEG data: 655 extraneous bytes before marker 0xd9  [WARNING]
```

**Comment by Uatschitchun** [comment]
Ok, so that seems a mjpeg problem with my camera? As said, after changing mode to YUYV the errors are gone and jpeginfo on all of my snapshots doesn't report an error...

**Comment by tosiara** [comment]
This could be either your camera's bug or libjpeg's (that used by motion and jpeginfo). You can try to compile latest libjpeg and feed it to motion during compile. And test

Snapshots are encoded by motion later from raw image so it should not be affected

**Comment by tosiara** [comment]
Tested with the latest libjpeg-9c - same issue:
`Corrupt JPEG data: 657 extraneous bytes before marker 0xd9`

**Comment by Mr-Dave** [comment]
Comments indicate issue is resolved.
