### ISSUE TITLE
Streaming video no longer streams in Chrome/Safari on iOS 11.3

### ISSUE THREAD

**Issue by jeffmurchison** [Motion-Project/motion#700]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.0.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L USB
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian

-------

I've been running Motion on a couple of raspberry pis and so far it has been working quite well. The other day though I noticed that when I loaded the streams on my phone, they were no longer working properly. The only thing I had changed was updating my phone from iOS 11.0.x to 11.3.

In Chrome, it just presents a generic error that says "Cannot determine file size" while in Safari the stream will load but will not refresh automatically. That is, it will load a single frame and won't update until you refresh the page manually.

I've looked on other iOS devices running earlier versions of iOS as well as through browsers on various desktop systems and they're all functioning just fine. Can anyone else confirm this issue on newer iOS devices?

**Comment by tosiara** [comment]
Can you confirm, you type `http://motion_ip:8081` in the address bar and immediately get an error "Cannot determine file size"? Can you provide a screenshot?

**Comment by uomogamma** [comment]
I’ve tryied too. I can confirm.

**Comment by tosiara** [comment]
Can you confirm, you type http://motion_ip:8081 in the address bar and immediately get an error "Cannot determine file size"? Can you provide a screenshot?

**Comment by uomogamma** [comment]
Yes sure. How can I post here a screenshot? Sorry but I’m new here. Anyway, with safari or firefox, for example calling port 8081 will serve a statoc image instead a streaming... using chrome, it send back the error “Cannot determine file size”

**Comment by tosiara** [comment]
Try to set `webcontrol_localhost off` and open `http://motion:8080` in the problematic browser, there should also be a live preview shown. Does this one work fine?

**Comment by mindcont** [comment]
@tosiara 
Maybe I didn't express myself clearly. After launching the motion, use the PC desktop chrome to view the video. Successful. However, using the iPhone Safari browser does not display properly. I suspect that some of Safari's security settings have only been visited once and have not been refreshed repeatedly.

**Comment by tosiara** [comment]
I understand. So please change your motion config to have `webcontrol_localhost off` then open from your iphone safari `http://motion:8080`

**Comment by mindcont** [comment]
Take steps as you said , when i take `webcontrol_localhost off` , open my iphone safari to `http://motion:8080`, i just came in the `HTTP Control Panel `. There is no difference with PC local access `http://127.0.0.1:8080` to get the `Control Panel`.

But when use my iphone visit the `Live Webcam Server Prot 8081` as `http://motion:8081`, just got the static image as same as **Safari screenshot**.

During this period, I discovered that the difference between the two is that the PC Chrome side will automatically refresh, but safari not, they request resources once.

**Comment by tosiara** [comment]
I can confirm it's bug in iOS, not motion. You can test any other MJPEG stream, like http://200.36.58.250/mjpg/video.mjpg?resolution=320x240, and you will see that it is not refreshing either

**Comment by mindcont** [comment]
Yep, cool man~
It is not refreshing either. Now I turn to using [VLC](https://www.videolan.org/vlc/index.html) to observe the `Live Webcam Server Prot 8081` as `http://motion:8081`.

By the way, the stream looks very nice. thanks 🙏

**Comment by uomogamma** [comment]
I’ve found a workaround solution. Just put the ip:port inside a <img src> tag... it will work on latest ios 11.3 safari.

**Comment by uomogamma** [comment]
Inside a #<img src> tag...

**Comment by uomogamma** [comment]
Sorry... inside a img src tag... the forum remove the brackets... ;-)

**Comment by tosiara** [comment]
That's why I asked you to open `http://motion:8080` - there should be an img scr preview of the stream. But you did not report that you saw the stream correctly

**Comment by mszel42** [comment]
@tosiara I experienced the very same through the motionEyeOS, made it work using the embed url: 

I don't know if it this option is motionEyeOS specific or not,  but this might help fixing the issue. 
![screen shot 2018-04-24 at 4 56 55 am](https://user-images.githubusercontent.com/6556358/39163725-079e505c-477c-11e8-89a7-09358f779c1b.png)

**Comment by uomogamma** [comment]
The solution is simply put it in an img src tag, inside an html page...


..


Il 24 apr 2018, 09:23 +0200, Calin Crisan <notifications@github.com>, ha scritto:

**Comment by tosiara** [comment]
@uomogamma , motion does not host any html pages. But you can install apache or nginx and host your own HTML

**Comment by polp6880** [comment]
Did anyone find a solution for this please? I added an <img> tag with src="https://url:8081" into an html page but I still get the same effect in Safari on my iphone, ie, I have to refresh for the image to update :(

**Comment by ace02000** [comment]
fixed in iOS 11.4 !

**Comment by mindcont** [comment]
fixed in iOS 11.4 too !😁

**Comment by VenkateshPS** [comment]
I tried on iOS 11.4 safari loads with a black screen

**Comment by zafirf** [comment]
@polp6880
Any solution on this? I have the same problem

**Comment by tosiara** [comment]
Try this test url, does it load in your Safari?
http://pendelcam.kip.uni-heidelberg.de/mjpg/video.mjpg
