### ISSUE TITLE
Dump V4L device name or vid:pid into log

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#702]
1. version [x.y.z, hash, other]: https://github.com/Motion-Project/motion/commit/182c8a34d5fca316e5a8f4ae7e350a97e86a6b07
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L

I noticed that with the recent changes we no longer log details about V4L camera, like it was previously:
```
vid_start: Opening V4L2 device
v4l2_start: Using videodevice /dev/video0 and input -1
v4l2_get_capability:
#012------------------------
#012cap.driver: "uvcvideo"
#012cap.card: "Vimicro USB Camera (Altair)"
#012cap.bus_info:"usb-usb20_host-1"
#012cap.capabilities=0x04000001
#012------------------------

```
Details about the hardware are still sometimes important. Do you thing it is worth dumping device details into log at least with `-d 7` level?

**Comment by Mr-Dave** [comment]
Well, it is still available at the debug level.  [Reference line](https://github.com/Motion-Project/motion/blob/ff794450d0f19a33703584dc922c6e480136e989/video_v4l2.c#L1299)

It was demoted to debug because I can not recall it ever being information that assisted in diagnosing an issue.

**Comment by tosiara** [comment]
Can we move it to the same logging level as used to dump the config? `-d 7`?

**Comment by tosiara** [comment]
Anyway, at least now I know that it is logged under `-d 8`. Thanks
