### ISSUE TITLE
How many cameras motion supports

### ISSUE THREAD

**Issue by Olegone23** [Motion-Project/motion#703]
0. Reviewed guide and contributing documents? (Yes/No):
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
3. standalone or part of third party [motion, MotionEyeOS, other]: 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: 
6. operating system [16.04, Stretch, etc, FreeBSD, other]:

**Comment by Olegone23** [comment]
Hi Tosiara,
One small question, what do u think if its possible to hold 16s 2Mps cameras for motion at once?
I mean just image we have good server with 16 cores CPU and hardware raid.
is it enough for motion to pick up all streams?

Kind Regards,
Oleg

**Comment by tosiara** [comment]
Github's issue tracker is not a way to contact me with personal messages. Please use mail list to ask questions as there are more experienced people to answer
