### ISSUE TITLE
How to use webcontrol

### ISSUE THREAD

**Issue by mika-nt28** [Motion-Project/motion#704]
0. Reviewed guide and contributing documents? (Yes):
1. version [current git]: 
2. installed as a package or compiled from sources [git]: 
3. standalone or part of third party [motion]: 
4. video stream et cam (mjpeg, rtsp, other), mmal]: 
5. hardware other
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 

Hello,
I'm update Motion with the current version, and my plugin using the WebControl doesn't works.
I set the parameter file with 
`$file='/usr/local/etc/motion/motion.conf';
		if($fp = fopen($file,"w")){
			fputs($fp,'daemon on');
			fputs($fp, "\n");
			fputs($fp,'setup_mode off');
			fputs($fp, "\n");
			fputs($fp,'logfile /etc/motion/motion.log');
			fputs($fp, "\n");
			fputs($fp,'log_level 6');
			fputs($fp, "\n");
			fputs($fp,'log_type all');
			fputs($fp, "\n");
			fputs($fp,'webcontrol_port '.config::byKey('Port', 'motion'));
			fputs($fp, "\n");
			fputs($fp,'webcontrol_localhost off');
			fputs($fp, "\n");
			fputs($fp,'webcontrol_interface 1');
			fputs($fp, "\n");
			fputs($fp,'webcontrol_parms 2');
			fputs($fp, "\n");
			foreach(eqLogic::byType('motion') as $Camera){		
				if($Camera->getIsEnable()){
					if(file_exists('/etc/motion/camera'.$Camera->getId().'.conf')){
						fputs($fp,'camera /etc/motion/camera'.$Camera->getId().'.conf');
						fputs($fp, "\n");
					}
				}
			}
		}`
I added this parameter in the Camera file to link with my motion plugin
`fputs($fp, 'camera_id '.$this->getId());`
When I put this request, I have no answer
http://192.168.0.1:8080/66/detection/pause
or
http://192.168.0.1:8080/66/action/snapshot
But this request
http://192.168.0.1:8080/
Reply
Motion 4.1.1+git20180405-182c8a3 Running [3] Cameras 0 1 2 3

**Comment by tosiara** [comment]
Why are you specifying camera index "66" in your request? You must use an available index, like http://192.168.0.1:8080/0/detection/pause

**Comment by mika-nt28** [comment]
66 is my camera_id

**Comment by tosiara** [comment]
Your ids are: `Cameras 0 1 2 3`

**Comment by genius3000** [comment]
@mika-nt28 unfortunately the webcontrol URLs use the camera `thread` number rather than the config option of `camera_id`. I do though see merit to what you were aiming for here, as using the `camera_id` would be more reliable when using scripting and adding/removing cameras, as the thread numbers would change for some/all cameras.  
As a current stop-gap, the thread numbers **should** increment from 1 and follow the order that the camera config files are read in.  
I looked through the old http code and it also used `thread` in the URLs, are you saying this worked using `camera_id` before? I'd be quite surprised if it did. I'll look into the feasibility of utilizing the `camera_id` in the URLs when I have the time.

**Comment by mika-nt28** [comment]
Ok, I misunderstood what the camera_id was for.
I handed the code with the thread search but when I list configuration, I doesn't parametre configured

> [2018-04-12 11:59:38][DEBUG] : Exectution de la commande: http://192.168.0.100:8080/3/config/list
[2018-04-12 11:59:38][DEBUG] : Retours de la commande:   daemon = on    process_id_file = (null)    setup_mode = off    logfile = /etc/motion/motion.log    log_level = 6    log_type = all    camera_id = 0    camera_name = (null)    videodevice = /dev/video0    vid_control_params = (null)    v4l2_palette = 17    input = -1    norm = 0    frequency = 0    auto_brightness = 0    tunerdevice = (null)    roundrobin_frames = 1    roundrobin_skip = 1    switchfilter = off    netcam_url = (null)    netcam_highres = (null)    netcam_userpass = (null)    netcam_keepalive = off    netcam_proxy = (null)    netcam_tolerant_check = off    rtsp_uses_tcp = on    mmalcam_name = (null)    mmalcam_control_params = (null)    rotate = 0    width = 352    height = 288    framerate = 100    minimum_frame_time = 0    despeckle_filter = (null)    locate_motion_mode = off    locate_motion_style = box    text_right = %Y-%m-%d
%T    text_left = (null)    text_changes = off    text_event = %Y%m%d%H%M%S    text_scale = 1    flip_axis = none    emulate_motion = off    threshold = 1500    threshold_tune = off    noise_level = 32    noise_tune = on    area_detect = (null)    mask_file = (null)    mask_privacy = (null)    smart_mask_speed = 0    lightswitch_percent = 0    lightswitch_frames = 5    minimum_motion_frames = 1    event_gap = 60    pre_capture = 0    post_capture = 0    quiet = on    target_dir = (null)    output_pictures = on    output_debug_pictures = off    quality = 75    picture_type = jpeg    snapshot_interval = 0    snapshot_filename = %v-%Y%m%d%H%M%S-snapshot    picture_filename = %v-%Y%m%d%H%M%S-%q    exif_text = (null)    ffmpeg_output_movies = off    ffmpeg_output_debug_movies = off    max_movie_time = 3600    ffmpeg_bps = 400000    ffmpeg_variable_bitrate = 0    ffmpeg_video_codec = mpeg4    ffmpeg_duplicate_frames = off    movie_filename = %v-%Y%m%d%H%M%S    timelapse_interval = 0    timelapse_mode = daily    timelapse_codec = mpeg4    timelapse_fps = 30    timelapse_filename = %Y%m%d-timelapse    ffmpeg_passthrough = off    video_pipe = (null)    motion_video_pipe = (null)    use_extpipe = off    ipv6_enabled = off    stream_port = 0    substream_port = 0    stream_quality = 50    stream_motion = off    stream_maxrate = 1    stream_localhost = on    stream_limit = 0    stream_preview_scale = 25    stream_preview_newline = off    webcontrol_port = 8080    webcontrol_localhost = off    webcontrol_interface = 1    sql_log_picture = on    sql_log_snapshot = on    sql_log_movie = off    sql_log_timelapse = off    sql_query_start = (null)    sql_query_stop = (null)    sql_query = (null)    database_type = (null)    database_dbname = (null)    database_host = localhost    database_port = 0    database_busy_timeout = 0    track_type = 0    track_auto = off    track_port = (null)    track_motorx = 0    track_motorx_reverse = off    track_motory = 0    track_motory_reverse = off    track_maxx = 0    track_minx = 0    track_maxy = 0    track_miny = 0    track_homex = 128    track_homey = 128    track_iomojo_id = 0    track_step_angle_x = 10    track_step_angle_y = 10    track_move_wait = 10    track_speed = 255    track_stepsize = 40    track_generic_move = (null)    camera = (null)    camera_dir = (null)

**Comment by mika-nt28** [comment]
Hi,

I have changed my plugin code for check all thread with the "camera_id" parametre but Motion reply  Bad Request

> [2018-04-17 13:47:57][DEBUG] : Connexion au motion 192.168.0.100:8080
[2018-04-17 13:47:57][DEBUG] : Exectution de la commande: http://192.168.0.100:8080/
[2018-04-17 13:47:57][DEBUG] : Retours de la commande: Motion 4.1.1+git20180411-ff79445 Running [2] Cameras 0 1 2
[2018-04-17 13:47:57][DEBUG] : Exectution de la commande: http://192.168.0.100:8080/0/config/get?camera_id
[2018-04-17 13:47:57][DEBUG] : Retours de la commande: Bad Request
[2018-04-17 13:47:57][DEBUG] : Exectution de la commande: http://192.168.0.100:8080/1/config/get?camera_id
[2018-04-17 13:47:57][DEBUG] : Retours de la commande: Bad Request
[2018-04-17 13:47:57][DEBUG] : Exectution de la commande: http://192.168.0.100:8080/2/config/get?camera_id
[2018-04-17 13:47:57][DEBUG] : Retours de la commande: Bad Request

**Comment by tosiara** [comment]
Unfortunately, the latest version has some breaking changes in webcontrol. https://github.com/Motion-Project/motion/issues/661#issuecomment-381152393

**Comment by mika-nt28** [comment]
Ok, I don't understand how to update my plugin for used WebControl with snapshots, movies, and detection activation

There are important to linked my camera_id with Thread Id

**Comment by genius3000** [comment]
oOo wait, I see another bug here actually. The `text_list` function is only printing out the config values for `thread 0`, not the requested thread. That's why the `camera_id` in the `list` dump above is **0**.   
It should be an easy fix, but I'd like to have time to test before PR'ing it (day or two).

**Comment by genius3000** [comment]
Yes, in the new web interface `/get` isn't available, you'll have to use `/list` (after the bugfix). I'll look into re-implementing the `get` function, but not promising anything.

**Comment by genius3000** [comment]
@mika-nt28 the config list bug has been fixed in commit `00d3b25` to the master branch. You'll get the correct results from `http://addr:port/1/config/list ` now (replace '1' with the wanted thread). Mr-Dave is working on the other concerns recently brought up regarding the webinterface.

**Comment by mika-nt28** [comment]
Ok is good for linked ID thread et my Id plugin.
Now I doesn't have a reply with detection status or snapshot

> [2018-04-18 08:26:09][DEBUG] : Retours de la commande: Motion 4.1.1+git20180417-00d3b25 Running [2] Cameras 0 1 2
[2018-04-18 08:26:09][DEBUG] : Exectution de la commande: http://192.168.0.1:8080/1/detection/status 
[2018-04-18 08:26:09][DEBUG] : Retours de la commande:
[2018-04-18 08:26:09][DEBUG] : Exectution de la commande: http://192.168.0.1:8080/0/detection/connection
[2018-04-18 08:26:09][DEBUG] : Retours de la commande:
[2018-04-18 08:27:32][DEBUG] : Exectution de la commande: http://192.168.0.1:8080/1/action/snapshot
[2018-04-18 08:27:32][DEBUG] : Retours de la commande:

**Comment by genius3000** [comment]
The `/detection/status ` and `/detection/connection ` aren't yet implemented. There's an open PR adding those.  
As for `/action/snapshot `, it is implemented and should be working. **Note:** it doesn't return anything but a `200 OK`. Check your snapshots folder for whether it works or not. Having some sort of reply on success may need to be added yet.

**Comment by mika-nt28** [comment]
It's ok for snapshat and movies

I wait the PR correction detection State
Can you alert me when this option are implémented

**Comment by Mr-DaveDev** [comment]
After the next PR gets merged, the next one will not be until August/September. So I would recommend participating in the testing now rather than waiting for an alert.

**Comment by mika-nt28** [comment]
I deploy in my plugin the github master branch.
How participating in the testing now rather than waiting for an alert.

**Comment by mika-nt28** [comment]
Hi,

It's possible to use detection/start or detection/pause now?

**Comment by tosiara** [comment]
Yes, it is in this PR: https://github.com/Motion-Project/motion/pull/707
You can check out it locally and build:
```
git fetch origin pull/707/head:webapi
git checkout webapi
```

**Comment by mika-nt28** [comment]
Hi,
I have no reply to detection/status request

> [2018-05-16 08:45:57][DEBUG] : Exectution de la commande: http://192.168.0.1:8080/1/detection/status
[2018-05-16 08:45:57][DEBUG] : Retours de la commande:

**Comment by tosiara** [comment]
Have you tried the pull request per my previous comment?

**Comment by tosiara** [comment]
'Status' web request has not been released yet.
But if you want you can use it now by compiling from the sources as per comment https://github.com/Motion-Project/motion/issues/704#issuecomment-385888992

**Comment by Mr-Dave** [comment]
resolved.
