### ISSUE TITLE
Some webcontrol security concerns

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#709]
I have these concerns:

1. http api command "Quit" kills the process remotely. This allows an attacker to cause DoS, as there is no way to restart the process remotely the same way. If motion killed, the admin would need to get either physically to the box, or use SSH connection. Easy to kill motion using CSRF (see 3)
Is there any use case where the admin would need to kill motion, and not restart?

2. Any params that allows code execution should be not allowed to be changed remotely. Like extpipe command and any scripts on_*. If an attacker obtains credentials for the web interface it could allow to run arbitrary processes on the motion box same user as motion runs. I know some people use "root" as motion user, so this would be very dangerous

3. No CSRF protection. That means, that an attacker could trick the admin to visit a malicious web page that could submit config change request on behalf of admin. While there are critical config changes allowed at runtime - this exposes some risk to admins that allowed remote connections to webcontrol or are working on the same box. For example, `<img src="http://localhost:8080/0/action/quit">`

4. XSS is possible. For example, put this into config: `camera_name <script>alert(1)</script>`. All untrusted strings that are being outputted to the web UI must be html-encoded. All strings that come from config or any other user input are untrusted

**Comment by Mr-Dave** [comment]
Thanks for writing these up.  

These are issues that have existed for the life of the application(pre-2015) and stress the guide instructions of not running as `sudo` and to not forward the Motion ports externally.  

I'd also reference issue #540 where I specifically requested documentation from other users regarding how to set up Motion behind a reverse proxy and documenting the associated security considerations.  Unfortunately, knowledgeable users have not responded to that issue so I have been unable to update the Motion documentation with a recommended approach.

I believe that the `webcontrol_parms` helps mitigate some of these.  e.g. Using the `webcontrol_interface` default of 0 means no configuration options can be changed.

If you find particular configuration options that need the security level revised, please submit a PR.

**Comment by tosiara** [comment]
Some time ago there were plans to move to an http library. Why haven't we gone that path?

**Comment by Mr-Dave** [comment]
I suppose we could now that the code is maintainable.  Can you validate that it is available on all the platforms and put together a PR that implements it for both the html as well as the text?

**Comment by Mr-Dave** [comment]
Just a follow up.  I did look briefly at the library and I am not seeing how using it would address the concerns referenced in the first comment.   To me, it seems like these are addressed by the `webcontrol_parms` and the fact that it can not be changed remotely.  It can only be changed by editing the configuration file.

**Comment by Mr-DaveDev** [comment]
Note that I am proposing to close this issue with PR #758   If you have any comments, please post them.

**Comment by tosiara** [comment]
Agree
