### ISSUE TITLE
Is there a way to filter out auto focus pictures?

### ISSUE THREAD

**Issue by pmmcmullen94** [Motion-Project/motion#711]
0. Reviewed guide and contributing documents? (Yes/No): Somewhat
1. version [x.y.z, hash, other]: Latest
2. installed as a package or compiled from sources [deb, rpm, git, other]: Package
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: USB webcam (Microsoft LifeCam 4000)
5. hardware [x86, ARM, other]: Raspberry Pi
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian Stretch

I have a camera that autofocuses periodically (it seems to happen a lot) that I am using as a usb security camera hooked to my home automation server. When the image autofocuses, motion detects it as an event and fires off a bunch of pictures. Is there a recommended/possible way to ignore these other than finding a way to lock disable on my camera? Thanks in advance.

**Comment by tosiara** [comment]
Does your camera support manual focus? Check with `v4l2-ctl --all`

**Comment by Mr-Dave** [comment]
Comments indicate issue resolved.
