### ISSUE TITLE
Frame shifts when taking snapshots

### ISSUE THREAD

**Issue by vinjegaard** [Motion-Project/motion#714]
I have a USB webcam connected to a raspberry pi. I take snapshots every 5 minutes, it works great but  every now and then I get an image that looks like this:
![01-20180515152000-snapshot](https://user-images.githubusercontent.com/8505555/40062760-3b52d102-585c-11e8-9142-dc97da707c31.jpg)
Is this motions fault and/or is it something motion can prevent?

**Comment by vinjegaard** [comment]
@tosiara I'm running motion Version 4.0.
I get these corrupted images a couple times a day, so maybe every 20-30 snapshots.
[motion.log](https://github.com/Motion-Project/motion/files/2019764/motion.log)
[motion.txt](https://github.com/Motion-Project/motion/files/2019766/motion.txt)
(renamed motion.conf to motion.txt)

Thanks!

**Comment by Mr-Dave** [comment]
You should consider upgrading to validate that the problem exists in the current master.  

I'd also recommend reconsidering setting auto brightness and instead leave that to the camera.  It uses a lot of CPU and user experiences with it have been "marginal"

[Download page](https://motion-project.github.io/motion_download.html) (which references a script for building a deb if you want that)

[Build from source page](https://motion-project.github.io/motion_build.html) as an alternative.

**Comment by tosiara** [comment]
I think the problem here could be two images written to the same file. I recall someone had similar issue
Do you have any scripts that copy or move files?

**Comment by vinjegaard** [comment]
@Mr-Dave I will update to master and see if the issue persists.
@tosiara Interesting! I have mounted my local server samba share to the raspberry pi and set the folder to the public drive.

**Comment by Mr-Dave** [comment]
If issue persists in current master branch code, please comment with new logs and images and I will reopen issue.
