### ISSUE TITLE
Track with PTZ camera IP

### ISSUE THREAD

**Issue by mika-nt28** [Motion-Project/motion#718]
0. Reviewed guide and contributing documents? (Yes):
1. version [4.1.1+git20180417-00d3b25]: 
2. installed as a package or compiled from sources [git]: 
3. standalone or part of third party [motion]: 
4. video stream source [net cam (mjpeg, )]: 
5. hardware [other]: 
6. operating system [Stretch]: 

Hi,

It is possible to track with my PTZ camera IP

**Comment by Mr-Dave** [comment]
[Support Page](https://motion-project.github.io/motion_support.html)
