### ISSUE TITLE
Timelapse stopping while ffmpeg_output - usage question

### ISSUE THREAD

**Issue by svacher** [Motion-Project/motion#721]
0. Reviewed guide and contributing documents : Yes
1. version :  4.1.1
2. installed as a package or compiled from sources : git
3. standalone or part of third party : motion
4. video stream source :  mmal
5. hardware : ARM - RPI3
6. operating system : Stretch

Hi,

Is it normal that timelapse video is stopping (timelapse_interval 10) if motion is detected (ffmpeg_output_movies on) ?
It make timelapse writing new file because using time for no overwrite it (timelapse_filename %Y%m%d-%H%M%S-timelapse).

If yes, is there a solution for having a normal timelapse with no cut (every 10 seconds for example, with no missing picture) and motion movies on the other side ?

Thank you for your reponses...

**Comment by Mr-Dave** [comment]
Please update to the current master branch and determine whether this persists.  If so, please provide all the configuration parameters with respect to timelapse and movies so that it can be replicated.

**Comment by svacher** [comment]
Ok, i'll do it this week.

Thanks.

**Comment by svacher** [comment]
The problem continue with this version.
See my config file and the genereted files for help :
[files.txt](https://github.com/Motion-Project/motion/files/2092922/files.txt)
[motion.conf.txt](https://github.com/Motion-Project/motion/files/2092932/motion.conf.txt)

Thanks

**Comment by svacher** [comment]
Hi,
I suspect that under-voltage on RPI 3 could be the problem...
A will change power and tell you.

Thanks

**Comment by Mr-Dave** [comment]
My testing shows this to be working ok.  It is possible that the camera is getting reset and causing the multiple timelapse files.  To avoid this, you can simply change the file name for time lapse from `%Y%m%d-%H%M%S-timelapse` to `%Y%m%d-timelapse`  This naming would be consistent with the rollover mode specified of `daily` and the type of mpg.  All timelapse files for a particular day will be put into the file with that day stamp.

As an aside, I would welcome any translation corrections for the webcontrol page!  The particular items on the  page that need validation are listed [here](https://github.com/Motion-Project/motion/blob/c1db494aaf2ae3f48ade6a90981bcb0b7cbaf3f0/po/fr.po#L3195) and if you find anything that needs to be changed, open a new issue with the correction or provide a PR.

**Comment by svacher** [comment]
Ok, i use Y%m%d-%H%M%S because before reinstall all for debug, i used mpeg4 format for timelapse. So i'll use mpg codec with %Y%m%d-timelapse.

For translation corrections, I will be happy to help.

I think issue can be closed.
Thanks for your help.
