### ISSUE TITLE
Invalid URL for mjpeg protocol 

### ISSUE THREAD

**Issue by ralfeus** [Motion-Project/motion#722]
0. Reviewed guide and contributing documents? (Yes/No): **Yes**
1. version [x.y.z, hash, other]: **3.2.12+git20140228**
2. installed as a package or compiled from sources [deb, rpm, git, other]:  **apt**
3. standalone or part of third party [motion, MotionEyeOS, other]: **motion**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **net cam (mjpeg)**
5. hardware [x86, ARM, other]: **virtual on x86**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: **Linux ubuntu 4.4.0-127-generic #153-Ubuntu**

While using mjpeg protocol for stream URL I'm getting following error:

> [1] [ALR] [NET] [Jun 06 14:15:30] netcam_start: Network Camera thread starting... for url (mjpeg://10.10.10.10:80/mjpeg.cgi)
> [1] [CRT] [NET] [Jun 06 14:15:30] netcam_start: Invalid netcam_url (mjpeg://10.10.10.10:80/mjpeg.cgi)

When I replace to mjpg I get following:

> [1] [ALR] [NET] [Jun 06 14:22:51] netcam_start: Network Camera thread starting... for url (mjpg://10.10.10.10:80/mjpeg.cgi)
> [1] [NTC] [NET] [Jun 06 14:22:51] netcam_setup_mjpg: connected, going on to read and decode MJPG chunks.
> [1] [WRN] [NET] [Jun 06 14:22:51] netcam_read_mjpg_jpeg: Invalid header received, reconnecting
> [1] [NTC] [NET] [Jun 06 14:22:51] netcam_read_first_header: Removed netcam Keep-Alive flagdue to apparent closed HTTP connection.
> [1] [ERR] [NET] [Jun 06 14:22:51] netcam_http_request: Error reading first header - re-trying
> [1] [WRN] [NET] [Jun 06 14:22:51] netcam_read_mjpg_jpeg: Invalid header received, reconnecting
> [1] [WRN] [NET] [Jun 06 14:22:52] netcam_read_mjpg_jpeg: Invalid header received, reconnecting

When using http protocol it works fine:

> [1] [ALR] [NET] [Jun 06 14:16:19] netcam_start: Network Camera thread starting... for url (http://10.10.10.10:80/mjpeg.cgi)
> [1] [NTC] [NET] [Jun 06 14:16:19] netcam_setup_html: connected, going on to read image.
> [1] [NTC] [ALL] [Jun 06 14:16:20] image_ring_resize: Resizing pre_capture buffer to 1 items
> [1] [ALR] [NET] [Jun 06 14:16:20] netcam_handler_loop: Camera handler thread [-3] started
> [1] [WRN] [NET] [Jun 06 14:16:20] netcam_next: called with no data in buffer
> [1] [NTC] [NET] [Jun 06 14:16:21] netcam_read_html_jpeg: Potential split boundary - 2895 chars flushed, 1 re-positioned
> [1] [NTC] [NET] [Jun 06 14:16:21] netcam_read_html_jpeg: Potential split boundary - 1447 chars flushed, 1 re-positioned
> [1] [NTC] [NET] [Jun 06 14:16:22] netcam_read_html_jpeg: Potential split boundary - 1447 chars flushed, 1 re-positioned

**Comment by Mr-Dave** [comment]
This is a duplicate.  This is listed in #566 to be removed.
