### ISSUE TITLE
The web control interface of Motion seems to be "lost" as a concept

### ISSUE THREAD

**Issue by KennethLavrsen** [Motion-Project/motion#738]
Hi Mr. Dave

When we originally changed the remote interface from xml-rpc to http the goal was to make remote control of Motion easy for anyone because the xml-rpc interface was pretty geeky.

We made a webinterface where all commands were done with GET and not with POST. This way you could do what you wanted in a normal browser and copy and paste the URL from the browser to the program or script that you wanted to control motion. It made hacking things up for non programmers easy.

E.g. I have a script that changes the displayed text in my camera adding rotating when the user turns the pan control (which is independent on the Motion as program. It is just a PHP programing getting URLs from the Motion server when the servo starts panning and when it is done. Easy.

But with the version I just installed I cannot see anything in the URL. It is hidden from me. So I go to the new Motion Guide where the information is also well hidden but if you go to a web control option and scroll up you see the original documentation that states that all is done with GET.

This totally blows away the whole idea with the web control interface. When I change to text mode it does not help me at all. I have ZERO user interface. I cannot navigate to anywhere. I just get the list of threads and nowhere to click. It is a dead interface. You have to know the URLs to use that. It is totally useless.

The only way to use the control now is to read the source code and I am not even sure the GET methods will still work. I am a bit sad about this.

**Comment by Mr-Dave** [comment]
Well, I'm not sure that I'd agree with the title to this issue.  The text interface operates just like the previous text interface which according to the historical and current documentation is intended for those using a external program to interact with Motion.  The item that is missing is the documentation of the items which I stated in a different issue does need to get added since it didn't exist in the initial guide.  The commands that existed in the previous interface via the GET except `status` and `detection` are still processed under both `text` and `html`

**Comment by Mr-Dave** [comment]
Please keep in mind that this is in the master branch and is _**not an official release** ._

**Comment by Mr-Dave** [comment]
I've added this a an additional task under #661 which identifies some of the outstanding issues to resolve.  

With respect to the example, there is an existing more verbose example of the setting of the `text_left` parameter provided in the web control section of the master branch documentation [here](https://rawgit.com/Motion-Project/motion/master/motion_config.html#OptDetail_Stream_Webcontrol)
