### ISSUE TITLE
V4L2 pixel format 422P

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#740]
0. Reviewed guide and contributing documents? (Yes/No): **yes**
1. version [x.y.z, hash, other]: https://github.com/Motion-Project/motion/commit/1b320733e88b1001febd0b9d7d0a9f6b4f7c7e21
2. installed as a package or compiled from sources [deb, rpm, git, other]: **git**
3. standalone or part of third party [motion, MotionEyeOS, other]: **motion**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **V4L2 Orange Pi camera module**
5. hardware [x86, ARM, other]: **ARM Orange Pi Lite**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: **16.04**

I'm testing Orange Pi dev board with camera module. The module supports different raw pixel formats, like 422P, YV12 and UYVY

When setting pixel format to 422P `v4l2_palette 16` I get corrupted image (screenshot):

![image](https://user-images.githubusercontent.com/3600973/41847758-d241f84e-7883-11e8-8b79-9006e9f30df7.png)

YV12 and UYVY formats give correct image (screenshot):

![image](https://user-images.githubusercontent.com/3600973/41847859-377d891c-7884-11e8-8d5c-c765231e7d5b.png)

I need some help identifying whether it is camera providing wrong format, or motion failing to read image

Two sample files: [sample_raw_images.zip](https://github.com/Motion-Project/motion/files/2132909/sample_raw_images.zip)

**Comment by Mr-Dave** [comment]
You could use the static file method as described in the [guide](https://motion-project.github.io/motion_config.html#Basic_Setup_Static) on a known good source and change the format to 422P

**Comment by tosiara** [comment]
Thanks for the tip. Looks like it may be a bug

I created a picture (screenshot from camera) and streamed it using ffmpeg to v4l2loopback device:
```
$ ffmpeg -re -f image2 -loop 1 -i 1600x1200.png.jpg -f v4l2 -pix_fmt yuv422p /dev/video1
ffmpeg version 2.8.14-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[mjpeg @ 0xad2730] Changeing bps to 8
Input #0, image2, from '1600x1200.png.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1600x1200 [SAR 72:72 DAR 4:3], 25 fps, 25 tbr, 25 tbn, 25 tbc
[swscaler @ 0xaf4300] deprecated pixel format used, make sure you did set range correctly
Output #0, v4l2, to '/dev/video1':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: rawvideo (Y42B / 0x42323459), yuv422p, 1600x1200 [SAR 1:1 DAR 4:3], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc56.60.100 rawvideo
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> rawvideo (native))
Press [q] to stop, [?] for help
frame=  234 fps=4.1 q=-0.0 Lsize=N/A time=00:00:09.36 bitrate=N/A
video:877500kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exiting normally, received signal 2.
```
Motion with `v4l2_palette 16 ` gave similar corrupted image:

![image](https://user-images.githubusercontent.com/3600973/41850245-8b1be9da-788c-11e8-973f-86baf9f0e81b.png)

**Comment by tosiara** [comment]
Using `netcam_url v4l2:///dev/video0` and `v4l2_palette 16` works fine, good picture:
```
[1:ml1] [INF] [NET] netcam_rtsp_set_path: Setting up v4l2 via ffmpeg netcam
[1:ml1] [INF] [NET] netcam_rtsp_set_v4l2: Normal resolution: Requested v4l2_palette option: 16
[1:ml1] [INF] [NET] netcam_rtsp_set_v4l2: Normal resolution: Requested FOURCC code: 422P
```

**Comment by Mr-Dave** [comment]
Adding RGB as indicated in #746 to the list of pixel formats to resolve.

**Comment by wgprojects** [comment]
For other users - as recommended in #746 and by tosiara above, `netcam_url v4l2:///dev/video0` resolves the incorrect colours for an RGB pixel format 10, compared to `videodevice /dev/video0`. 
Perhaps interestingly, I did not observe the 'broken image' artifacts above, just the wrong palette.

**Comment by tosiara** [comment]
Verified fixed
