### ISSUE TITLE
Raspberry pi sudo apt-get install motion yields "E: Unable to locate package motion"

### ISSUE THREAD

**Issue by jbrownkramer** [Motion-Project/motion#742]
I am running Raspian 4.9.59-v7

I entered
````
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install motion -y
````
And got `E: Unable to locate package motion`

**Comment by jbrownkramer** [comment]
Another sudo apt-get update did the trick, for some reason.

**Comment by mariotti** [comment]
Just in case.
I had the same problem: update/upgrade, then the error.
And rerunning the apt-get did not work.
I had to rerun 'apt-get update' to get back the list of packages.
Then it worked.

The why is a different question. Is the upgrade step missing some refresh?
