### ISSUE TITLE
segmentation fault with current libav

### ISSUE THREAD

**Issue by mo22** [Motion-Project/motion#743]
on 65117293b72b5c99e13a94262a64765030c6baf3, osx, ffmpeg 4.0.1 i get a segmentation fault on motion with ffmpeg_output_movies enabled.
cause is that ffmpeg->oc->url is null but is written to in ffmpeg_set_outputfile:
sprintf(ffmpeg->oc->url, "%s", ffmpeg->filename);

```
diff --git a/ffmpeg.c b/ffmpeg.c
index 1f9b600..0f12b2a 100644
--- a/ffmpeg.c
+++ b/ffmpeg.c
@@ -794,11 +794,23 @@ static int ffmpeg_set_outputfile(struct ffmpeg *ffmpeg){
     int retcd;
     char errstr[128];

+printf("dbg1=%p\n", ffmpeg);
+printf("dbg2=%p\n", ffmpeg->oc);
+printf("dbg3=%p\n", ffmpeg->oc->url);
+printf("dbg4=%p\n", ffmpeg->oc->filename);
+printf("dbg5=%s\n", ffmpeg->filename);
+// dbg1=0x101d009f0
+// dbg2=0x104000000
+// dbg3=0x0
+// dbg4=0x104000038
```

**Comment by Mr-Dave** [comment]
This is caused by a change in ffmpeg.  You will need to build from source from the master if you are going to use that version of ffmpeg.

**Comment by mo22** [comment]
I used the master branch and built it from source. I had to comment out the sprintf(ffmpeg->oc->url) line so it does not segfault as oc->url is a nullptr
