### ISSUE TITLE
Stream preview newline breaks menu buttons

### ISSUE THREAD

**Issue by wgprojects** [Motion-Project/motion#750]
0. Reviewed guide and contributing documents? (Yes/No): **Yes**
1. version [x.y.z, hash, other]: **43b9c2**
2. installed as a package or compiled from sources [deb, rpm, git, other]:  **git**
3. standalone or part of third party [motion, MotionEyeOS, other]: **standalone**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **mmal**
5. hardware [x86, ARM, other]: **ARM**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian Jessie

Expected behaviour: Setting 'stream_preview_newline on' does not break menu buttons.
Actual behaviour: Browser (Firefox & Chrome) report issues with the generated javascript, and the Cameras / Action buttons stop working.

Here is my recommended patch, which adds ;\n and aligns the formatting a bit:

```
diff --git a/webu.c b/webu.c
index c6c3505..68018c8 100644
--- a/webu.c
+++ b/webu.c
@@ -1490,7 +1490,7 @@ static void webu_html_script_camera_all(struct context **cnt, struct webui_ctx *
         if (cnt[indx]->conf.substream_port) strm_port = cnt[indx]->conf.substream_port;
 
         if (cnt[indx]->conf.stream_preview_newline){
-            snprintf(response, sizeof (response),"%s","    preview = preview + \"<br>\" ");
+            snprintf(response, sizeof (response),"%s","        preview = preview + \"<br>\";\n ");
             written = webu_write(webui->client_socket, response, strlen(response));
         }
 
```

**Comment by Mr-Dave** [comment]
Thanks.  I've just added this change into my @Mr-DaveDev mhttp branch which is going to include some large changes to the webu code to address some of the issues listed here.
