### ISSUE TITLE
hevc encoding quality

### ISSUE THREAD

**Issue by bol-van** [Motion-Project/motion#753]
Tried encoding output in hevc. It produces very small files with awful quality. Bps does not affect anything

**Comment by Mr-Dave** [comment]
Have you reviewed the [guide](https://motion-project.github.io/motion_config.html)?

**Comment by bol-van** [comment]
I start with working config : 
```
ffmpeg_video_codec mp4
ffmpeg_variable_bitrate 0
ffmpeg_passthrough 0
ffmpeg_bps 1500000

```
get h264 coded mp4's sized ~1-2-3Mb
Now change codec to 'hevc".
get h265 coded mp4's sized 50-70 Kb

Change codec to "mkv:h265"
get h264 (!) codec mkvs

Its not working

**Comment by bol-van** [comment]
> By specifying the container (mkv) and then appending a semicolon and the ffmpeg codec name Motion will attempt to use the specified codec for the container. This permits options such as encoding the h265 codec into a mkv container instead of mp4 by specifying the option as mkv:h265

Docs say I should use semicolon but example contain colon

With colon :h265  part is ignored.
With semicolon

ffmpeg_get_oformat: codec option value mkv;h265 is not supported

**Comment by genius3000** [comment]
Maybe ffmpeg will recognize 'hevc', ie: `mkv:hevc` ?  
Back to the original issue, what is the actual quality (bps or Kbps) of the created hevc mp4s in comparison to the h264 ones?

**Comment by bol-van** [comment]
I already tried mkv:hevc and it also produced h264 video.  Part after colon seem to be completely ignored.

rtsp source is 30 fps  vbr

produced file :
bitrate is 359 kbps
fps 4.192
Duration : 0.6 sec

1) Configured bps is ignored
2) Most of the frames are thrown away. 
3) Captured video should be ~10 seconds long but its only 0.6 sec

My assumption  CPU power is not enough to code it in realtime and it throws most frames, composing the video from the others with no timestamp change
I tried encoding mp4 to hevc using ffmpeg and the speed is about ~0.1 .. 0.12 

Then I set framerate to 4 and video time increased to 3 seconds. Framerate was 10.  Looks like framerate cant be less than 10. But it proves my idea about CPU.  
So conclusion is : CPU must be capable of encoding frames in realtime, there's no buffering. And there're some bugs about bps and colon

**Comment by bol-van** [comment]
I'm running motion latest snapshot from here.
My system is celeron J1900.  Its baytrail atom based system, not too fast.
During incoding all cores are 100% loaded, so its clear cpu is overloaded and motion cant buffer.

Thanx for variable_bitrate idea.  In hevc case its the only setting that actually changes bitrate.  Bps settings does not work.

**Comment by genius3000** [comment]
Ah yes definitely CPU then. I'll give hevc with static bps a try later, interesting that it's not working. Maybe it's related to not being able to keep up at all times. I had similar trouble with 2 netcams at 720p on a VM on a dual core Intel chip, couldn't keep up and videos suffered. Same/better settings on a more powerful computer fixed that.

**Comment by bol-van** [comment]
HEVC require much more computational power than AVC.
On systems not capable of realtime encoding  delayed processing is possible.
Enable passthrough mode and write on_movie_end  script  that runs ffmpeg

`on_movie_end /etc/motion/movie_end.sh %f`

```
#!/bin/sh
FILE=$1
VBITRATE=1200000
TMP265=/tmp/video265_$$.mp4
ffmpeg -y -i $FILE -f mp4 -c hevc -b:v $VBITRATE $TMP265 &&
{
 # success
 mv -f $TMP265 $FILE
}
```

**Comment by bol-van** [comment]
I checked same config on a faster system (Core I7  4770K)
Constant bitrate value change nothing in case of HEVC

**Comment by Mr-Dave** [comment]
The method of setting quality on HEVC is the CRF which is set using the `ffmpeg_variable_bitrate`.  Motion has the input on a scale of 1 to 100 and translates that to the CRF scale.
