### ISSUE TITLE
[Help wanted] Can add camera but can't read rtsp in motionEye

### ISSUE THREAD

**Issue by BobMorane31** [Motion-Project/motion#759]
Hello !
I'm trying to setup a surveillance system at home. Here is my configuration :

*  **PI zero w** : streams video using raspivid & vlc : 
```
raspivid -o - -t 0 -w 800 -h 600 -fps 20 -b 180000 | cvlc -vvv stream:///dev/stdin --sout '#rtp{access=udp,sdp=rtsp://:8554/stream}' :demux=h264
```

* **Laptop** : Xubuntu + motionEye (for testing, I install motionEye on my server when it works ...)
  *  **VLC** successfully reads the rtsp flow from the PI.
  * **motionEye** : I can add the camera (as a network cam) but I only see a grey screen in the motionEye preview with the following message : "**Unable to open video device**".
What seems strange to me is that motionEye gives me the fps received (24.4/20.3 fps) on the bottom left corner ...

I also have this issue reported in the log:
```
[1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method SETUP failed: 461 Client error
[1:ml1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://192.168.1.103:8554/stream): Protocol not supported
```
But i thought rtsp protocol was supported ... 

Any idea about what is going wrong ??
Thanks :)

(transferred from motionEye forum : [937](https://github.com/ccrisan/motioneye/issues/937))

### Config
motion 4.1.1 +  motionEye 0.39.2 running on XUbuntu 18.04 (laptop)
Streaming video from RPI zero w with RPI cam V1.3

**Comment by genius3000** [comment]
Some searching suggests that error is due to ffmpeg trying to access your UDP stream using TCP. Check your motion config for `rtsp_uses_tcp` and set it to `off` (adding if it's missing) as it defaults to `on`. I'm also seeing suggestions to switch your stream to TCP, but can't personally comment on that.

**Comment by BobMorane31** [comment]
@genius3000 : I set `rtsp_uses_tcp=off` in motion.conf file, but it doesn't work either.

I'm absolutely not familiar at all with TCP & UDP. I think I'll have to search for some basic knowledge about this ...
I tried to setup the stream another way from the PI : 
```
raspivid -o - -t 0 -n -w 600 -h 400 -fps 12 | cvlc -vvv stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554/}' :demux=h264
```
but had no luck with either `rtsp_uses_tcp=on`  or `rtsp_uses_tcp=off` ...

**Comment by tosiara** [comment]
`rtsp_uses_tcp off`

**Comment by ccrisan** [comment]
@BobMorane31 I belive you have to change that into your `thread-1.conf` file rather than in your `motion.conf`. Also, if that proves to be the fix to your problem, you should add it as TCP RTSP camera in motionEye, rather than UDP.

**Comment by BobMorane31** [comment]
@tosiara Yes, thanks for the correction (I did not put the `=` on the conf file).
@ccrisan I did it too, but it did not change anything.

Here is my conf file. If you can see anything strange  ...
```
ffmpeg_output_movies off
height 600
stream_quality 85
threshold 3123
quality 85
noise_level 31
ffmpeg_output_debug_movies off
smart_mask_speed 0
pre_capture 1
noise_tune on
rtsp_uses_tcp off
stream_maxrate 5
output_pictures off
stream_localhost on
ffmpeg_variable_bitrate 75
ffmpeg_video_codec mp4:h264_omx
text_changes off
movie_filename %Y-%m-%d/%H-%M-%S
auto_brightness off
stream_port 8081
rotate 0
stream_auth_method 0
lightswitch 0
framerate 2
emulate_motion off
snapshot_filename
despeckle_filter
snapshot_interval 0
minimum_motion_frames 20
stream_motion off
target_dir /\home\yann\Video
netcam_url rtsp://192.168.1.103:8554/stream
text_double off
width 800
post_capture 1
stream_authentication user:
output_debug_pictures off
on_picture_save /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" picture_save %t %f
on_movie_end /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" movie_end %t %f
text_left
picture_filename
locate_motion_style redbox
locate_motion_mode off
netcam_keepalive off
max_movie_time 0
on_event_end /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" stop %t
text_right
on_event_start /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" start %t
event_gap 30
netcam_tolerant_check on
mask_file

```

I'll have a look on vlc side to see if there are other ways to stream video. My goal is to have fluid movies as I do not manage to have a good fps another way.

**Comment by TopperBG** [comment]
@BobMorane31 uninstall Motion which believe is installed with apt-get package system and use git clone and manual install it. Than Motion will be v.4.1.1 and will not have a problem with RTSP streams.

**Comment by BobMorane31** [comment]
@Mr-Dave I assumed the vlc streaming was correct as I could read it in vlc on server side. But maybe the stream was only readable with vlc ...
@TopperBG I tried this yesterday but it didn't work

Finally, I managed to get a fluid movie streaming with [uv4l](https://www.linux-projects.org/uv4l/) in mjpeg format and successfully read it in motionEye on the server. So I give up the vlc part.

Big thanks to everybody for your help!

**Comment by ozett** [comment]
@BobMorane31 
i had similar problems, tried similar thinks.

may you can post the uv4l streaming url you have used?
could help me.

or some words how you start u4vl?

thanks a lot,
still tinkering with this 😵

**Comment by Kallagan99** [comment]
Hello !

I've a similar issue. No pbme to get the RTSP stream trough VLC.
Motion is fine with 2 cameras. The 3rd one can't be seen into MotionEye. I can add it but I can't get the RTSP stream. I tried the "netcam_use_tcp off" option. Didn't work.

Thanks for your help

**Comment by ouafnico** [comment]
Hi

Got the same problem.
I tried multiple ways, creating rtsp with raspvid and cvlc, or uv4l but does not work.

Rtsp is working on VLC, but motioneye keep saying unable to open video device.
I'm trying to create mjpg with uv4l...

**Comment by ouafnico** [comment]
Seems to work with a rtsp server explained here :
https://sylvaindurand.org/surveillance-camera-with-raspberry-pi/

Using the camera on motioneye works.
