### ISSUE TITLE
Hardware accelerated JPEG on RPI?

### ISSUE THREAD

**Issue by roger-** [Motion-Project/motion#760]
I believe the RPI has a hardware accelerator (OMX) that supports JPEG. Has anyone looked into integrating this to improve performance with MJPEG?

**Comment by jasaw** [comment]
Look at this simple demo software that uses OMX to accelerate JPEG encoding.
https://github.com/hopkinskong/rpi-omx-jpeg-encode

**Comment by Mr-Dave** [comment]
This would also be something for the jpeg developers that distribute the library with Raspbian.
