### ISSUE TITLE
video signal lost

### ISSUE THREAD

**Issue by j-m-baker** [Motion-Project/motion#761]
Hello,

I'm using a ReoLink 410S camera, so a decent brand, and I'm struggling with seeing this message in the motion logs:

[1:ml1:Drive2] [NTC] [ENC] [Jul 12 15:46:18] ffmpeg_set_codec: Low fps. Encoding 4 frames into a 10 frames container.
[1:ml1:Drive2] [NTC] [EVT] [Jul 12 15:46:18] event_newfile: File of type 8 saved to: /data/cameras/active/drive2/motion/2018-07-12/154617.avi
[1:ml1:Drive2] [NTC] [ALL] [Jul 12 15:46:18] motion_detected: Motion detected - starting event 119
[1:ml1:Drive2] [NTC] [ALL] [Jul 12 15:47:28] event_image_preview: different filename or picture only!
[1:ml1:Drive2] [NTC] [EVT] [Jul 12 15:47:28] event_newfile: File of type 1 saved to: /data/cameras/active/drive2/pictures/2018-07-12/154618-00.jpg
[1:ml1:Drive2] [NTC] [ALL] [Jul 12 15:47:28] mlp_actions: End of event 119
[1:ml1:Drive2] [NTC] [ENC] [Jul 12 15:48:54] ffmpeg_set_codec: Low fps. Encoding 4 frames into a 10 frames container.
[1:ml1:Drive2] [NTC] [EVT] [Jul 12 15:48:54] event_newfile: File of type 8 saved to: /data/cameras/active/drive2/motion/2018-07-12/154854.avi
[1:ml1:Drive2] [NTC] [ALL] [Jul 12 15:48:54] motion_detected: Motion detected - starting event 120
[2:nc2:Drive2] [ERR] [NET] [Jul 12 15:49:11] netcam_rtsp_handler: Normal resolution: Bad image.  Reconnecting with camera....
[1:ml1:Drive2] [NTC] [ALL] [Jul 12 15:49:40] mlp_capture: Video signal lost - Adding grey image
[1:ml1:Drive2] [NTC] [ALL] [Jul 12 15:50:03] event_image_preview: different filename or picture only!
[1:ml1:Drive2] [NTC] [EVT] [Jul 12 15:50:03] event_newfile: File of type 1 saved to: /data/cameras/active/drive2/pictures/2018-07-12/154854-03.jpg
[1:ml1:Drive2] [NTC] [ALL] [Jul 12 15:50:03] mlp_actions: End of event 120
[1:ml1:Drive2] [NTC] [ALL] [Jul 12 15:50:51] mlp_capture: Video signal re-acquired
There is only one camera connected (Drive2) on version:

[0:motion] [NTC] [ALL] [Jul 12 08:33:04] motion_startup: Motion 4.1.1+gitUNKNOWN Started

Running on Ubuntu 18.04. I'm also seeing occasional image failures from this camera, ie corruption in the image. Yet, it works fine viewing from the reolink web app. The camera is cabled and pinging does not reveal packet loss.

With respect to the image corruption, a recent ffmpeg is installed:

$ ffmpeg
ffmpeg version 3.4.2-2 Copyright (c) 2000-2018 the FFmpeg developers

The camera is set to 1080P with 4fps, to stop the host being hammered with images.

Where do I start debugging?

Thanks

**Comment by tosiara** [comment]
Try to view the stream directly using ffplay and see if there are any errors logged in console. Maybe the camera produces a stream that is incompatible with ffmpeg

**Comment by j-m-baker** [comment]
Seems to work well with ffplay.

**Comment by j-m-baker** [comment]
ffplay  rtsp://xx:yy@192.168.0.xxx:554/h264Preview_01_main
ffplay version 3.4.2-2 Copyright (c) 2003-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu2)
  configuration: --prefix=/usr --extra-version=2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, rtsp, from 'rtsp://xx:yy@192.168.0.xxx:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1072, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

**Comment by j-m-baker** [comment]
Actually I see this error, but am not sure what it means:

 Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1072, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
[h264 @ 0x7f264c5b5f40] error while decoding MB 45 36, bytestream -13
[h264 @ 0x7f264c5b5f40] concealing 3724 DC, 3724 AC, 3724 MV errors in P frame
[h264 @ 0x7f264c5d2260] error while decoding MB 17 23, bytestream -15
[h264 @ 0x7f264c5d2260] concealing 5312 DC, 5312 AC, 5312 MV errors in P frame
[h264 @ 0x7f264c89ba80] error while decoding MB 84 53, bytestream -11
[h264 @ 0x7f264c89ba80] concealing 1645 DC, 1645 AC, 1645 MV errors in P frame

**Comment by j-m-baker** [comment]
The distortion continues with passthrough mode enabled too.

**Comment by Mr-Dave** [comment]
Distortion has historically always been associated with using UDP instead of TCP.  The `rtsp_uses_tcp on` is virtually a mandatory requirement.  (UDP means that frames can and will be dropped in transport)

I would also suggest turning up the frame rate on the camera and possibly adjusting the I frame rate that it provides.  Although you may think that turning it down on the camera would save bandwidth, I don't think that it does.  Motion is "pulling" from the camera at a particular FPS rather than the camera "pushing" at a FPS.  

As a result with the setting of UDP (`rtsp_uses_tcp off`) in Motion and the camera only providing 4 FPS, Motion may be missing key frames and is not able to decode what is being captured so it restarts the camera thread.

**Comment by j-m-baker** [comment]
rtsp_uses_tcp was already on, but increasing the framerate (to 10) seems to have resolved image corruption.

With respect to the camera framerate, if that's 25 does it have any affect on motion? ie when the RTSP stream is open, is the camera sending 25 frames a second to the camera, or does the camera simply pull them?

**Comment by Mr-Dave** [comment]
I do not know all the nuances of the RTSP protocol.  I do know that Motion is on its "own" loop of grabbing images from the camera irrespective of the FPS setting specified in the camera.  

If any of the corrupted images return, I'd suggest an even higher FPS setting on the camera or lowering the I frame interval.

**Comment by j-m-baker** [comment]
I keep seeing this:

[1:ml1:Drive2] [NTC] [ALL] [Jul 14 16:54:36] mlp_capture: Video signal lost - Adding grey image

How can I diagnose it some more?

**Comment by tosiara** [comment]
From the log you provided it is hard to say how soon the issue occurs and how long ffplay was running. Motion uses ffmpeg to read RTSP stream. If ffplay really plays the stream fine and writes no error to the console, then we should find steps to reproduce and investigate why motion fails
Can you provide steps to reproduce? Dump raw stream? Provide full detailed log `-d 9`?
