### ISSUE TITLE
Motion Detection remains ON

### ISSUE THREAD

**Issue by kduytsch** [Motion-Project/motion#765]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb (install via motioneye)
3. standalone or part of third party [motion, MotionEyeOS, other]: motioneye
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  net cam
5. hardware [x86, ARM, other]: rasPi 3
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Jessie

I played a lot with the web interface to stop/pause the motion detection /1/detection/pause|start, but seems this gets lost after a restart (not running in daemon mode, started by motioneye, using systemctl).
Even if in the config file I have :
thread-1.conf:# @motion_detection off
thread-2.conf:# @motion_detection off

when I restart, I get "Camera 1 Detection status ACTIVE", same for 2

Any idea ? I wanted to use the web API to de-activate remotely the detection, which works until I have to restart (or it restarts by itself (triggered by motioneye)). So I was thinking that "# @motion_detection off" parameter was there for that, but doesn't seems to be the case (or not anymore ?)

Thank you

**Comment by j-m-baker** [comment]
I thought it was ffmpeg_output_movies off, but that doesn't stop motion either.

**Comment by Mr-Dave** [comment]
We will consider adding it to the configuration file (it has never existed).  It is currently only a [command line parameter](https://motion-project.github.io/motion_config.html#Command_Line_Options) `-m`

**Comment by kduytsch** [comment]
So correct me if I'm wron,g, but the only way to achieve this is to use 
the http API and resend the same command each time motion was restarted ?

**Comment by Mr-Dave** [comment]
Yes, unless you add the command line parameter when you start Motion.

**Comment by Mr-Dave** [comment]
Closing via #1374
