### ISSUE TITLE
PPM images are corrupted - last line is missing color

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#768]
I used this 32x32 image to feed motion:

![32x32](https://user-images.githubusercontent.com/3600973/42821110-7cf0f192-89e0-11e8-91d3-9b8ed9dc097e.png)

`ffmpeg -re -f image2 -loop 1 -i 32x32.png -f v4l2 -pix_fmt rgb24 /dev/video1`

Saving PPM image from motion gives this result:

![rgb ppm](https://user-images.githubusercontent.com/3600973/42821314-f225a41c-89e0-11e8-9f9a-f5cd987b89b1.png)

Despite some color loss during 420p conversion, there is also an entire line of pixels that are missing color at all:

![image](https://user-images.githubusercontent.com/3600973/42821524-653ecf0a-89e1-11e8-8b5a-644379802a7a.png)

This line always appears no matter what input source and pixel format is there
JPEGs are saved fine

Sample images attached: [images.zip](https://github.com/Motion-Project/motion/files/2201921/images.zip)

**Comment by Mr-Dave** [comment]
@tosiara , just to be clear on my question.  From the internet search on this file format, it appears that it was created to send images via email before emails allowed attachments and you could just paste in this format as text.  

Can you think of any reasonable scenario in which someone would want to use it?  Wouldn't it be reasonable to indicate that in the rare situation it is desired, they would need to invoke their own image conversion on the resulting JPGs?

**Comment by tosiara** [comment]
JPEG is lossy format. PPM is uncompressed bitmap with 24 bits per pixel, same as windows BMP format. I agree that this file format is pretty exotic. The only reason I was using this format was that I needed lossless picture format for monitoring of my engineering system.
Leaving only lossy formats jpg and webp would be very sad. But we could replace PPM with some more used lossless format, like PNG or lossless option for WEBP. However both of them require extra library/dependancy for writing

**Comment by Mr-Dave** [comment]
I don't think that I'll be working on this.  

I think the fact that we are lossy just by virtue of conversion of colors negates any perceived value of a lossless format.  WEBP is already built and maybe set it to lossless when quality is specified at 100 or maybe use `extpipe`  and ffmpeg to output to a lossless format images.

**Comment by tosiara** [comment]
Let's keep this open for a while, I will try to figure out if PPM can be fixed

**Comment by tosiara** [comment]
PR created https://github.com/Motion-Project/motion/pull/776
