### ISSUE TITLE
Feature Request: Add a configuration for audio input devices

### ISSUE THREAD

**Issue by Heiko-san** [Motion-Project/motion#770]
It would really be great if you could specify a microphone or any audio input device, that gets recorded along with the video data while an event is in progress.

What I currently do is bypassing motion's ffmpeg interface and feed video data through a loopback device, then I trigger ffmpeg externally recording the loopback device and the microphone using the triggers on_event_start and on_event_end.
This really works great but is a lot of tinkering and while motion could add the required options for audio recording internally, so the user would only need to specifiy the device and maybe some recording options like codec and so.

**Comment by Mr-Dave** [comment]
I do not anticipate incorporating sound.  Lots of additional programming complications and in many places, it isn't permitted to record audio.
