### ISSUE TITLE
pass through for jpeg/mjpeg

### ISSUE THREAD

**Issue by username7291** [Motion-Project/motion#773]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  3.2.12
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standallone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L/Netcam 
5. hardware [x86, ARM, other]:  x86, ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]:  Kali/Rasbian

I use motion to detect Motion but have to run a second program to record the stream.
Motion records very low fps(even if you have GHZ multicore cpu), the second program records the full fps the cam/netcam gives. The problem is now
1. the program looks for a File that motion creates and then starts the records until no motion. With that you lose the some frames at the begining.
2. there is no reason why motion after the detection not inself take the fast jpeg/mjpeg stream and pass it to ffmpeg(i have set anyway all Timestamps to off, the Filename has the Time of the event).
I read mp4 cams get a pass trough, mjpeg/jpeg users want this too please.

**Comment by genius3000** [comment]
You should probably upgrade to the current release and see how that works.

**Comment by Mr-Dave** [comment]
I would agree.  The answers to our template questions seem inconsistent.    With respect to wanting a pass-through for MJPEG, we will need you to be a bit more specific.

**Comment by Mr-Dave** [comment]
Passthough and high resolution processing is already functional using a mjpeg streamer source in conjunction with `netcam_url` or `netcam_highres` when using the `mjpeg` prefix

A PR for revisions to the guide including mjpeg will close this issue.
