### ISSUE TITLE
webu: Invalid action requested

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#778]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]: latest, https://github.com/Motion-Project/motion/commit/0572a64ba90e01b6b33d8d1f7d53b9e64da6ce61
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: v4l
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 16.04

Related config options:
```
stream_localhost no
webcontrol_localhost no
webcontrol_interface 1
```

When accesing web interface http://motion:8080 from a remote machine using Chrome browser I get a correct response:
```
Motion 4.1.1+git20180806-1dada36 Running [1] Camera
0
```
But there is an error logged by motion:
```
[0:wu0] [INF] [STR] webu_text_main: Invalid action requested: >< ><
```

However, if I use curl from localhost - no such message logged

**Comment by Mr-Dave** [comment]
This is caused by the browser sending a request for `favicon.ico`  so the message is accurate.  We probably just need to expand upon the message and include the `camid`.  You should be able to see the request sent by the browser by changing the log level to DBG.
