### ISSUE TITLE
mlp_retry: Camera has finally become available (while camera is not present)

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#779]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]: latest, https://github.com/Motion-Project/motion/commit/0572a64ba90e01b6b33d8d1f7d53b9e64da6ce61
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: v4l
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 16.04

I noticed the following strange sequence while running motion without USB camera connected:
```
[1:ml1:bal] [NTC] [VID] vid_start: Opening V4L2 device
[1:ml1:bal] [NTC] [VID] v4l2_device_open: Using videodevice /dev/webcam0 and input -1
[1:ml1:bal] [ALR] [VID] v4l2_device_open: Failed to open video device /dev/webcam0: No such file or directory
[1:ml1:bal] [ERR] [VID] vid_start: V4L2 device failed to open
[1:ml1:bal] [NTC] [ALL] mlp_retry: Camera has finally become available
Camera image has different width and heightfrom what is in the config file. You should fix that
Restarting Motion thread to reinitialize all image buffers to new picture dimensions
```
From what I see motion incorrectly detects camera while there is clearly no camera available

**Comment by Mr-Dave** [comment]
I think this is just a logging issue. There is not any specific checking of the camera status before it reports this message that the camera is found.
