### ISSUE TITLE
Motion servos volowing

### ISSUE THREAD

**Issue by GJAN-PI** [Motion-Project/motion#792]
I installed Motioneye on a Raspberry pi 2, everything works properly. But, when a movement is seen, a red rectangle comes across the camera image. My question is whether it is possible to read the location of this rectangle (the four corners). It is then possible for me to use this data to make my servo engines follow the movement. Oeps It is following

**Comment by Mr-Dave** [comment]
I will point out that you deleted and did not answer the template questions to make this a valid issue for reporting on the github issue tracker.  See [Support](https://motion-project.github.io/motion_support.html)

This functionality and a sample script is included in the [motion guide](https://rawgit.com/Motion-Project/motion/master/motion_config.html#The_Config_Files)  (It is recent so you must build Motion from source.  I did also just notice that the description in the `track_type` is not accurate.  Setting `track_type 4` invokes the `track_generic_move` which can also take in as parameters all of the usual Motion conversion options.)
