### ISSUE TITLE
Documentation: Start Motion Service in Boot System [v4.1.x]

### ISSUE THREAD

**Issue by carlymx** [Motion-Project/motion#801]
Hi.

First of all give thanks for this great software.

I have an OrangePi Zero to control my 3D Printer and so far I have been using Motion from the Ubuntu repository in version 3.2.12 without problems.

I wanted to use the latest version 4.1.1 and I have managed to run and configure my CAM and it looks much better than before. Good job.

I want to start the 'Daemon' service when the system starts, with version 3.2.12 I edited the file:

**'/ etc / default / motion'**
  **'start_motion_daemon = yes'**

and I could start the service with:

**'sudo service motion start'**

But in this version I am not able to get it, I searched for the '_motion_guide.html_' without success.
Can you help me?

Thank you.

[ESP:Original]
>Hola.
> 
> Antes de nada dar las gracias por este magnifico software.
> 
> Tengo una OrangePi Zero para controlar mi Impresora 3D y hasta ahora he estado usando Motion del repositorio Ubuntu en su versión 3.2.12 sin problemas.
> 
> He querido usar la ultima versión 4.1.1 y he conseguido hacer funcionar y configurar mi CAM y se ve mucho mejor que antes. Buen trabajo.
> 
> Deseo iniciar el servicio 'Daemon' cuando se inicie el sistema, con la versión 3.2.12 editaba el archivo:
> 
> **'/etc/default/motion'**
> **'start_motion_daemon = yes'**
> 
> y ya podia iniciar el servicio con:
> 
> **'sudo service motion start'**
> 
> Pero en esta versión no soy capaz de conseguirlo, he buscado por la **'motion_guide.html'** sin exito.
> 
> Pueden ayudarme?
> 
> Gracias.
> 

**EDIT-1:**
Hi.

The server works perfectly if I start it with 'motion -b' and it shows with great quality the images of the Cam.

I have discovered in '/ usr / local / share / motion / examples' the executable 'motion.init-Debian' which after many tests I have done the following:

- I created a new super user called 'motion' pass 'motion' (the service forced me to do so)
- I have copied and renamed the file 'motion.init-Debian' to '/etc/init.d/motion'
- I have also created the execution of the file on the restart with 'sudo crontab' in this way '@reboot /etc/init.d/motion start'

When restarting the Motion Daemon in appearance it seems to start correctly and is executed by the user 'motion' but there is a problem ... The image looks gray and indicates that the capture device is not found (attached image)

If I kill the service and run it manually with '/etc/init.d/motion start' it does exactly the same thing. I kill the process and start with 'motion -b' and it works perfectly.

Can you help me where I fail?

Thank you.
![2018-09-16](https://user-images.githubusercontent.com/24634598/45591960-3e1f3900-b961-11e8-8eca-c0e64a621232.png)

[ESP:Original]

> Hola.
> 
> El servidor funciona perfectamente si lo inicio con 'motion -b' y muestra con gran calidad las imágenes de la Cam.
> 
> He descubierto en '/usr/local/share/motion/examples' el ejecutable 'motion.init-Debian' el cual después de muchas pruebas he hecho lo siguiente:
> 
> - He creado un nuevo super usuario llamado 'motion' pass 'motion' (el servicio me obligaba a ello)
> - He copiado y renombrado el archivo 'motion.init-Debian' a '/etc/init.d/motion'
> - También he creado la ejecución del archivo en el reinicio con 'sudo crontab' de esta manera '@reboot /etc/init.d/motion start'
> 
> Al reiniciar el Daemon de Motion en apariencia parece que inicia correctamente y lo ejecuta el usuario 'motion' pero hay un problema... La imagen se ve en gris e indica que no se encuentra el dispositivo de captura (adjunto imagen)
> 
> Si mato el servicio y lo ejecuto manualmente con '/etc/init.d/motion start' hace exactamente lo mismo. Mato el proceso e inicio con 'motion -b' y funciona perfectamente.
> 
> ¿Pueden ayudarme donde fallo?
> 
> Gracias.

**Comment by Mr-Dave** [comment]
I have revised title to be a documentation issue because this is something that should be included in the guide.  I think that service also needs to get some attention.  Using Ubuntu 16.04, it worked without revision from the release deb but it does not look like it is functioning on all the systems. 

With respect to Motion working while running OK while as a normal user and not running as service, I suspect that it is because of permissions.  Check the permission groups that the user `motion` has versus your regular permissions.  The default deb package install creates the user called `motion` and then adds that user to the `video` group.  Not sure if there are other groups that the orange pi needs.
