### ISSUE TITLE
New Version (4.2/4.2.1)

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#803]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  Motion 4.1.1+dirty20180910-b8aa381
2. installed as a package or compiled from sources [deb, rpm, git, other]: Git
3. standalone or part of third party [motion, MotionEyeOS, other]: Standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Debian Stretch

Any interest from the community of preparing a 4.2 release based upon current master?  Which (if any) of the open issues does the community deem critical for inclusion?

**Comment by tosiara** [comment]
I don't see any reason why we couldn't release 4.2

**Comment by leppis** [comment]
I'm having trouble building this in Raspbian Wheezy (disabling mmal), while the 4.1.1 builds all right.

Errors during compilation of 062a328 or b8aa381:
`-e 	Compiling webu.c into webu.o...
webu.c: In function ‘webu_mhd_send’:
webu.c:1062:52: error: ‘MHD_HTTP_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN’ undeclared (first use in this function)
webu.c:1062:52: note: each undeclared identifier is reported only once for each function it appears in
webu.c: In function ‘webu_mhd_flags’:
webu.c:1742:60: error: ‘MHD_USE_DUAL_STACK’ undeclared (first use in this function)
Makefile:131: recipe for target 'webu.o' failed
make: *** [webu.o] Error 1
`

**Comment by Mr-Dave** [comment]
Thanks for reporting.  Unfortunately, Wheezy is at [EOL](https://wiki.debian.org/DebianReleases) so it is not supported.  You will need to upgrade your distribution if you wish to use a updated version.

**Comment by Mr-Dave** [comment]
Short task list:

1. Update travis to include debian stretch/jessie
2. ~~Eliminate the legacy sub stream method (legacystream PR)~~
3. ~~Regress on the static file processing via netcam  (mjpg-file PR)~~
4. ~~Add the threshold_maximum configuration option (threshold-max PR)~~
5. Add config parms somewhere to be found by xgettext
6. Update po files for latest code.
7. Guide Update
     - a.  How to set up to start automatically.
     - b.  Instruction on how to put "all" configuration options into the motion.conf file
     - c.  Instructions on how to upgrade and eliminate depreciation warnings.
     - d.  Use the webcontrol preview to do side by side setup.
     - e.  Configuration files section.  Default sys location for motion.conf is incorrect.
     - f.  Update version number on alpha list header
     - g.  How to set up the motion detection
     - f.  Adjust font on options-topic / alpha (looks smaller)
     - g.  Valid values for movie_codec.  Remove ogg.
     - h.  Remove live stream reference of the http control in first sentence.
     - i.  Add reference to motion image streams with the sub-streams, static images.
19. ~~Remove substream port writing out to the parms(legacystream PR)~~
20. ~~Regress to implement the 1990's web interface(1990s PR)~~
21. Manual update
     - Header date
     - Copyright date
23. Test BSD, Raspbian, PI camera
24. Review and revise INSTALL e.g. correct for libjpeg8
25. Update Changelog
26. Write release notes
27. Update version.sh
28. Tag as a release
29. Update/revise builddeb.sh script and debian rules
30. Build deb packages
31. Update IRC banner
32. Update news, documentation, home web pages, screen print webcontol. 
33. Wikipedia update.
34. Consider instructional youtube videos
     - Install from apt / gdebi
     - Install from source
     - Build a deb
     - Basic setup
     - Save new config to eliminate depreciated warnings/have all options in conf file
     - What is Noise, threshold, despeckle, etc
     - Set up for movie/debug via web interface
     - Masks (smart, privacy, motion)
     - Script Execution
     - API uses

**Comment by leppis** [comment]
>  Wheezy is at [EOL](https://wiki.debian.org/DebianReleases) so it is not supported. You will need to upgrade your distribution if you wish to use a updated version.

Thank you, that was indeed the reason. I upgraded to Jessie and now it compiles!
