### ISSUE TITLE
Feature Request: Need to differentiate the object movement from the picture change

### ISSUE THREAD

**Issue by eliassun** [Motion-Project/motion#805]
It is useful to know if the motion event is caused by the object movement (e.g. human movement) or the picture changed (e.g. just light on/off, or the shadow swing of a tree). 
With the feature, we can decide to if we are going to watch the motion event when we receive a notification.

**Comment by Mr-Dave** [comment]
From what I have been able to determine, I think this would require re-writing the whole application into C++

**Comment by eliassun** [comment]
That is too big...Let me figure out if another software tensorflow can process the video made by motion

**Comment by eliassun** [comment]
Ok. Thanks

**Comment by bernd-wechner** [comment]
FYI: 

https://isocpp.org/wiki/faq/mixing-c-and-cpp
https://www.oracle.com/technetwork/articles/servers-storage-dev/mixingcandcpluspluscode-305840.html

In short, not a crisis.
