### ISSUE TITLE
distorted colours on motion snapshot

### ISSUE THREAD

**Issue by sashash77** [Motion-Project/motion#806]
0. Reviewed guide and contributing documents? (Yes/No): Yes :)
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: over motioneye
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: netcam rtsp
5. hardware [x86, ARM, other]: ARM, Raspberry 3, wanscam hw0043
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian

First of all - big thanks :) 
Issue: From time to time colours of snapshoted picture switched to distorted "mode"
earlier it was less often, and now more often
It looks like somth goes wrong on camera, but in camera web panel it looks fine, and (main) - reloading of motion (or motioneye or whole RaspPi) without reloading camera - always helps
Than colours becomes normal, and after some random time period I can found it broken again.
I have only one camera of that manufacture . Another one works good with rtsp, but it is significantly different device.
I can believe that it is camera issue, but may be you have some ideas how to workaround it.

![2018-09-27-13-14-22-cam1](https://user-images.githubusercontent.com/43668095/46196217-1770e300-c30f-11e8-8e7b-7f00fdf5bcc1.jpg)
![2018-09-28-10-56-41-cam1](https://user-images.githubusercontent.com/43668095/46196220-18a21000-c30f-11e8-9a53-42536f5bb9f8.jpg)

**Comment by sashash77** [comment]
I tried different resolutions (to prevent converting problems) - nothing helps.

one more point - when shatshots become distorted, picture on motion web or motioneye web distorted also.

**Comment by tosiara** [comment]
This looks like a broken network packet that caused rtsp decompression to fail. Often happens when UDP is used. If you increase motion logging you would probably see some ffmpeg decompression warnings at that time

**Comment by sashash77** [comment]
Should it fix itself ?
main problem is that is not fixes itself. Broken colours could stay for a looong looogn time... But when I reload motion - it fixes immediately.

**Comment by tosiara** [comment]
I think, broken colors main remain until a key frame received from camera. Do you have access to video stream settings of your camera? If yes, try to tune settings to include key frame every 1 second and see if that changes anything

**Comment by sashash77** [comment]
Thanks for advice...
I've changed "key frame interval" on camera and now will check result...
