### ISSUE TITLE
JPG Url 

### ISSUE THREAD

**Issue by Maja61** [Motion-Project/motion#810]
0. Reviewed guide and contributing documents? (Yes/No):Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: package
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mjpeg
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Stretch

Hi,

is it possible to get a jpg from the stream via an URL? i want to grap from another Raspi a jpg from the url via wget. 

thanks

**Comment by tosiara** [comment]
`ffmpeg http://localhost/1/stream -vframes 1 snapshot.jpg`
Please use mail list for questions
