### ISSUE TITLE
ubuntu install instructions need updated

### ISSUE THREAD

**Issue by blindrain** [Motion-Project/motion#821]
0. Reviewed guide and contributing documents? (Yes/No):Yes
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
3. standalone or part of third party [motion, MotionEyeOS, other]: 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: x86_x64
6. operating system ubuntu 18.04  

Step 1 is not able to be completed on ubuntu 18.04  all 3 packages do not exist.

**Comment by Mr-Dave** [comment]
You will need to be more specific preferably by providing a link to the instruction.  I do not see or recall any instruction that is numbered as "Step 1."  My testing pulls in all the required packages on 18.04.

**Comment by blindrain** [comment]
https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu

Sorry step 2.


Since step 1 says to skip .


Robert F.D. Whitacre

317-449-9320

"If you don't build your dream, someone will hire you to build theirs"

**Comment by tosiara** [comment]
You should report it to motioneye, not motion
