### ISSUE TITLE
Here's a nice on_movie_end script (not an issue)

### ISSUE THREAD

**Issue by dtbaker** [Motion-Project/motion#835]
I wanted to post motion events to slack in the form of a small thumbnail that showed frame changes and snapshots from the video file. This way a motion event could be summarised into a nice little 100k JPEG and sent to my phone. 

Here's the result. The top of the thumbnail is a black and white mask showing all the frame changes, followed by 6 thumbnails from various parts of the video stream. All combined into a single image.

![slack-image](https://user-images.githubusercontent.com/543073/48042162-28452c00-e1cc-11e8-88d8-d5ffd39bd4bd.png)

I can now quickly look at these thumbnails :point_up:  and know if it's something worth looking at. 

In my motion camera thread config I have:

```
on_movie_end /path/to/file.sh video %t %f
```

Inside `file.sh` I have this:

```
#!/bin/bash
if [ "$1" == "video" ]; then
    # pull out changed frames from video and mash them together with some bash magic.
    if [ `echo "$3"|grep mp4` ]; then
        thumbs=`mktemp -d`
        if [ ! -z "$thumbs" ]; then
            ffmpeg -i $3 -vf "select='not(mod(n,3))',setpts='N/(25*TB)'" -filter:v scale="608:-1" -f image2 $thumbs/o%03d.png
            if [ ! -z "$(ls -A $thumbs)" ]; then
                source=`ls $thumbs/o*|head -n 1`
                mkdir $thumbs/diff/
                for image in `ls $thumbs/o*.png`; do
                    if [ ! "$image" == "$source" ]; then
                        thumbname=${image##*/}
                        compare -compose Src -highlight-color Black -lowlight-color White -fuzz 30% $source $image $thumbs/diff/$thumbname
                        convert $thumbs/diff/$thumbname -fuzz 10% -transparent white $thumbs/diff/$thumbname
                    fi
                done
                convert $thumbs/diff/* -layers merge $thumbs/compare.png
                convert $thumbs/compare.png -resize 608x $thumbs/compare-small.jpg
                images=`ls $thumbs/o*.png|shuf -n 4|sort`
                montage $images -geometry 300x+2+2 $thumbs/montage.jpg
                convert $thumbs/compare-small.jpg $thumbs/montage.jpg -append $thumbs/slack.jpg
                #curl -F file="@$thumbs/slack.jpg" -F channels=alerts-cameras -H "Authorization: Bearer xoxp-PUT-YOUR-SLACK-LEGACY-API-TOKEN-HERE" https://slack.com/api/files.upload
            fi
            rm -rf $thumbs # eek!
        fi
    fi
fi
```

Just sharing it here while it's fresh in my brain - hope someone finds it useful down the track 

Much <3 to motion + imagemagick

**Comment by retrostrobe** [comment]
Such an amazing script, thanks for sharing. I'm yet to try it out, but it looks very promising. 

How do you generate the first 3 lines of text?

**Comment by dtbaker** [comment]
The motion detected Slack message is a separate bash script attached to on_motion_begin or similar.

The other open/close stuff is unrelated to motion, it's physical sensors wired into door frames piping through to the same Slack channel.
