### ISSUE TITLE
Enhancement various minor improvements to systemd unit file

### ISSUE THREAD

**Issue by tim-seoss** [Motion-Project/motion#869]
Hi,

I've made a few minor tweaks to the motion systemd unit file for local use, so I thought I'd see if there was interest in merging them upstream...

. Fix no license info
. Remove redunant pid file (not needed by systemd for non-forking services, and not generated by motion in the default config anyway).
. Add autorestart (and document options to tweak).
. Add reload
. Document the use of the systemd journal

I'll submit a pull request...

**Comment by Mr-Dave** [comment]
Since you seem to use systemd, I'm hoping that you can also answer a couple of other questions regarding it.  (I anticipate Motion will transition to using `systemd` as the default once 14.04 hits EOL in April)

- Is there any short description that can be added to the guide.  Here is the [link](https://motion-project.github.io/motion_config.html#basic_setup_service) to the existing section on setting up as a service but it only says that a `motion.system` file is available. It would be helpful to have even a single statement of what to "do" with it.  (I've just never looked into it)  If you can leave as comment here or add to the `motion_config.html` in the source code that would be great.

- The historical process has been to run Motion as user `motion` that is a member of the `video` group.    Looking at the service file, it seems that systemd would run as root.  Do you know of any limitations of running as a user `motion` associated with systemd?

**Comment by tim-seoss** [comment]
> * Is there any short description that can be added to the guide.  Here is the [link](https://motion-project.github.io/motion_config.html#basic_setup_service) to the existing section on setting up as a service but it only says that a `motion.system` file is available. It would be helpful to have even a single statement of what to "do" with it.  (I've just never looked into it)  If you can leave as comment here or add to the `motion_config.html` in the source code that would be great.

OK, I'll look at updating the docs, but briefly...

My understanding is that system-wide unit files should be installed in `/etc/systemd/system/` (for "local" files installed by the sysadmin - this would be appropriate for motion if e.g. you're installing the corresponding binaries under `/usr/local/`), whereas packaged software should have their unit files installed in a system-specific directory (`/lib/systemd/system/` on Debian and derived distros, and `/usr/lib/systemd/system/` on RHEL7).

You would then tell systemd to read the new unit file with `systemctl daemon-reload`, and use `systemctl [start|stop|status|reload|disable|enable|mask|edit] motion` etc. to make use of the unit file.  The non-obvious ones being `edit` to modify the unit file to suit your local requirements (without actually touching the original unit file, so that it won't break on package upgrades or binary reinstalls), and `mask` to permanently disable the unit (in a way which will also survive package upgrades/reinstalls).

> * The historical process has been to run Motion as user `motion` that is a member of the `video` group.    Looking at the service file, it seems that systemd would run as root.  Do you know of any limitations of running as a user `motion` associated with systemd?

No problem, I'll add that, and update the pull request.  May not get onto that until tomorrow tho'.

I think it would probably also be useful to honour existing `start_motion_daemon=no` settings in /etc/default/motion, so I'll take a look at adding that too...

**Comment by tim-seoss** [comment]
The init file in git (`motion.init-Debian.in`) doesn't currently match the one shipped by Debian in the packaged version of motion.  Debian doesn't start motion if `$start_motion_daemon` isn't set to `yes` (in `/etc/default/motion`).

The documentation in git (`motion_config.html`) does reference the `/etc/default/motion` setting, and instructs the user to set it to `yes` before motion will run.

I can add a test to the systemd unit file to check this setting (so that the current Debian init file behaviour is preserved).  I suppose the motion.init-Debian.in should also be revised to make it consistent with the docs (or perhaps it should just use the one that Debian currently ships?).

Thoughts?

**Comment by tim-seoss** [comment]
BTW, have closed the pull request #870 in the meantime whilst we sort out the scope fully...

**Comment by Mr-Dave** [comment]
Sorry for the delay.  Got pulled into something else.  

>I think it would probably also be useful to honour existing start_motion_daemon=no settings in /etc/default/motion (so that upgraded systems don't suddenly start running motion when they'd previously been manually disabled), so I'll take a look at adding that too... Any thoughts?
...
>I can add a test to the systemd unit file to check this setting (so that the current Debian init file behaviour is preserved)

Yes, that would be good.  We need to be consistent with the packaged version of Motion from Debian as well as from any distributed debs on the site or built from source. 


>> I suppose the motion.init-Debian.in should also be revised to make it consistent with the docs (or perhaps it should just use the one that Debian currently ships?).<<

I had actually forgotten about that file.  With the limited resources of the project, I would be inclined to remove the file and only maintain the one within the packaging repo unless there are reasons to keep it here for systemd.  (In which case, I would remove it from the packaging repo)  We just can't be maintaining the same file twice otherwise this situation will occur again.

**Comment by tim-seoss** [comment]
> I had actually forgotten about that file. With the limited resources of the project, I would be inclined to remove the file and only maintain the one within the packaging repo unless there are reasons to keep it here for systemd.

There's not reason to keep that init file around for systemd.  It should probably either be kept in sync with the one in the Debian package, or alternatively removed.  There is also a freebsd init file in git BTW, if motion is packaged for freebsd already, then the same would probably go for that file I suppose?

There is a fair bit of security hardening which could be done using the systemd unit file as detailed in: http://0pointer.net/public/systemd-nluug-2014.pdf

This is good but many of these options could conceivably break some setups which would rely on some of the removed permissions for scripts which are triggered by motion.  The options could be:

- Enabled, and comments added to the documentation (and config file) detailing how to disable if necessary
- Added, but commented out
- Omitted entirely (as they are at the moment), or only added selectively (e.g. `PrivateTmp=yes`).

**Comment by Mr-Dave** [comment]
I reviewed the document briefly and think by running as user "motion" it should be fairly secure and I'm reluctant to tighten it up too much and break existing systems.  

With respect to the freebsd init and for that matter the rpm spec file, I'd like to leave those alone for the moment.  I need to investigate further how  bsd ports and RPM fusion set things up for services (if at all).

**Comment by tim-seoss** [comment]
I've reworked things to incorporate the changes above.  I've also added some addition security-related settings, but have left them commented-out by default.

I've not removed the init script yet, as I wondered if it might be best to take the latest Debian systemv init file from the current downstream Debian and also offer that along side the systemd unit file on a "it's still there, but not supported unless someone wants to step-up" basis?

Debian officially supports running without systemd (although systemd has been the default for a while now).  ISTR that systemd will fall back to the init file if there's no service file present, so no harm shipping both?  FWIW, removing init files has been known to trigger systemd opponents to go non-linear in the past...

I'll see if I can reopen the PR in the meantime if you'd like to review things.

**Comment by tim-seoss** [comment]
BTW, I haven't done the documentation updates, pending whatever change is decided on about removing the init script, but I could add these to the PR as necessary...

**Comment by tim-seoss** [comment]
Any thoughts on this?  Do the changes so-far look OK?

Thanks!

Tim.

**Comment by tim-seoss** [comment]
Bump.

**Comment by Mr-DaveDev** [comment]
This is my usual time of year that I do not do coding/review/development.  

https://motion-project.github.io/motion_news.html

**Comment by tim-seoss** [comment]
OK.

**Comment by Mr-Dave** [comment]
Closing. Thanks for the PR and it is merged.
