### ISSUE TITLE
feature request: on_timelapse_end event config option added

### ISSUE THREAD

**Issue by steveneighbour** [Motion-Project/motion#872]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]:  4.2.1+git
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Docker/Ubuntu

I'm using the timelapse features and it's working great.  I understand there to be 2 options, mp4 encoded streams with files over-written if motion restarts or mpeg encoded with files appended if motion restarts.  Both of these work as intended, but i was wondering if it was possible to add an option to re-encode after the mpeg timelapse completes?

As an example, when a movie event completes i have this config to perform an action (in this case extract motion frames via ffmpeg and create an image montage)

on_movie_end /usr/local/etc/motion/file.sh video %t %f %$

Would it be possible to add an additional config item, to trigger an action when a timelapse video event  completes?

eg

on_timelapse_end /usr/local/etc/motion/file.sh video %t %f %$

I'd use this to re-encode the mpeg timelapse to a much smaller filesize and optionally send it as an alert

**Comment by genius3000** [comment]
From a quick look through the event code, `on_movie_end` should be triggered by the timelapse movie ending also. If so, could you just use the file type to determine that it's a timelapse file and act accordingly in the script?  
I don't use timelapse but totally get what you're after here. It looks like adding another exec event won't be much. I just know there's a lot of config options already, adding more needs to be well justified.

**Comment by steveneighbour** [comment]
thanks for checking that out - that makes sense, i can modify my existing script to re-encode the movie if it has a .mpg extension.  Will have a look

**Comment by Mr-Dave** [comment]
Closing. It seems that this is possible with the existing functionality.  In addition to looking for a mpg, you could also set up a separate subdirectory for the timelapse vs other movies.

**Comment by steveneighbour** [comment]
for anyone else, here is what works for me

```
on_movie_end /usr/local/etc/motion/file.sh %f %$
```

file.sh then contains logic to recompress a timelapse (mine will always be mpg and none of my cameras use mpg)

```
if [[ "$1" == *".mpg"* ]]; then
    mkdir -p "/var/lib/motion/timelapse/`date +%d-%m-%Y`"
    ffmpeg -i $1 -vf scale=-1:720 -c:v libx264 -crf 23 -preset ultrafast -c:a copy "/var/lib/motion/timelapse/`date +%d-%m-%Y`/`echo $2`.mp4"
    ffmpeg -i $1 -b 1500k -vf scale=-1:480 -c:v libx264 -crf 23 -preset ultrafast -c:a copy "/var/lib/motion/timelapse/`date +%d-%m-%Y`/`echo $2`.480p.mp4"
    #rm -f $1
fi
```

Will see if this runs as expected tonight
