### ISSUE TITLE
can't find motion-control program

### ISSUE THREAD

**Issue by nrobert13** [Motion-Project/motion#873]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: opkg ( openwrt )
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: v4l
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: openwrt 

Hi guys,

this guide, https://www.lavrsen.dk/foswiki/bin/view/Motion/LogitechSphereControl mentions a motion-control program, but I cannot find this program anywhere in the source code. How can I compile it?

Thanks.

**Comment by Mr-Dave** [comment]
I will reference again the current guide [tracking](https://motion-project.github.io/motion_config.html#OptDetail_Tracking) section as well as the [webcontrol](https://motion-project.github.io/motion_config.html#OptDetail_Webcontrol) section of the guide.  I am guessing the url that you reference is from the old wiki.
