### ISSUE TITLE
emulate_motion and Captured Before not working as expected

### ISSUE THREAD

**Issue by 19grad** [Motion-Project/motion#876]
with reference to this issue in the motioneye forum
https://github.com/ccrisan/motioneye/issues/1057

The parameter "Captured Before" didn't work with an emulate_motion as i expected

i set "captured before" to 100 frames 
and trigger an emulate motion with
  http://IP:7999/1/config/set?emulate_motion=1
  http://IP:7999/1/config/set?emulate_motion=0
Motion will record a video but without the "captured before"  frames
So i can't see what happens before i trigger the video

motionEye Version | 0.39.2
Motion Version | 4.1.1
OS Version | motionEyeOS 20180627
Raspberry Pi 3B+

**Comment by tosiara** [comment]
Confirmed, when setting emulate_motion=1 at runtime from text-only webcontrol interface there are no pre-capture frames written. The same happens if you trigger "Action -> Start Event" through the css version of webcontrol - no pre-capture written
Setting as bug and adding @Mr-Dave to comment
