### ISSUE TITLE
I can't take snapshots. 

### ISSUE THREAD

**Issue by leoheck** [Motion-Project/motion#886]
Using motion **pi_stretch_motion_4.2.1-1_armhf.deb**

It looks like an issue related to the permissions.
This is the default motion.config, using `systemcl` to start it.

What should I do to fix this? I am assuming that this should work out of the box since the config is the default. Am I right?

![image](https://user-images.githubusercontent.com/1277920/51085633-6a866e80-1723-11e9-835a-3845b34953c2.png)

**Comment by leoheck** [comment]
I see that default target dir is not set.

```
# Target directory for pictures, snapshots and movies
; target_dir value
```

**Comment by leoheck** [comment]
Alright, it is working.

I just set the permissions like this to make sure it won't fail.
![image](https://user-images.githubusercontent.com/1277920/51085750-cef5fd80-1724-11e9-8b93-dae44d46a495.png)

The image is being created fine but it is not being displayed with this command/url:
```http://localhost:8080/0/action/snapshot ``

With previous motion versions, I was able to do this. **Is it still possible? How can I do it?**

**Comment by leoheck** [comment]
I am trying to use it with Octoprint server. The issue I have is there are no images being displayd with this URL `http://localhost:8080/0/action/snapshot`
 
![image](https://user-images.githubusercontent.com/1277920/51085974-ad4a4580-1727-11e9-9f48-9fca2e68fa5c.png)

**Comment by leoheck** [comment]
Related to https://github.com/Motion-Project/motion/issues/526

**Comment by Mr-DaveDev** [comment]
"Snapshots" save images to the disk not to the http stream.  See documentation on the [streams](https://motion-project.github.io/motion_config.html#OptDetail_Stream)

**Comment by leoheck** [comment]
@Mr-DaveDev I see. Previews versions have this HTTP server able to take snapshots this way. Do you know why this was removed? I feel that many users/applications make use of this feature.

**Comment by tosiara** [comment]
If you want to see a snapshot in browser, use `http://motion:8081/1/current`
If you want to save a snapshot picture, use `http://motion:8080/1/action/snapshot`
For usage questions please use mail list

**Comment by Mr-DaveDev** [comment]
Just to be clear for future readers of the issues.  The following statement is **not** accurate.  

> @Mr-DaveDev I see. Previews versions have this HTTP server able to take snapshots this way. Do you know why this was removed? I feel that many users/applications make use of this feature.

Motion has **never** provided a image via the url by `http://motion:8080/1/action/snapshot` so this is NOT a change from prior versions.

**Comment by van-ant** [comment]
if you want to get snapshot working with octoprint goto https://github.com/bchanudet/OctoPrint-Octorant/issues/24 and check out my comment (van-ant) for a solution

**Comment by Enoril** [comment]
You can use {IP}:{port0}/{camid}/**current** and obtain the image needed for the time-lapse
Or /**source** if you don't want the bottom left & right texts

cf the [documentation ](https://motion-project.github.io/motion_config.html#OptDetail_Stream)

```
[...]
    {IP}:{port0}/{camid}/stream Primary stream for the camera
[...]
    {IP}:{port0}/{camid}/source Source image from the camera
    {IP}:{port0}/{camid}/current Static JPG for the camera
```

http://rasprint.lan.jean-rodriguez.fr:8081/0/current
