### ISSUE TITLE
Letsencrypt WebContol Access

### ISSUE THREAD

**Issue by xgridder** [Motion-Project/motion#890]
I am trying to establish Motion TLS connection with Letsencrypt
certificate and somehow it doesn't work. I mean I cannot access
WebControl in TLS mode. Here are my settings in motion.conf

webcontrol_auth_method 2

webcontrol_authentication user:password

webcontrol_tls on

webcontrol_cert /path/to/cert.pem

webcontrol_key /path/to/privkey.pem

I checked logs as well but there is nothing related to it.

If webcontrol_tls is set to off, I can access WebControl. I mean motion
is up and running. If TLS is on, Firefox is saying that:

Secure Connection Failed

The connection was interrupted while the page was loading.
The page you are trying to view cannot be shown because the authenticity
of the received data could not be verified.
Please contact the website owners to inform them of this problem.

I am currently running Motion as root.

**Comment by xgridder** [comment]
Set up with proxy pass and it worked.

**Comment by eliottlerouge** [comment]
Hey I have the same problem. Could you explain me how you did the proxy pass ?
