### ISSUE TITLE
compiler is twitchy on truncating formats

### ISSUE THREAD

**Issue by PeterHolik** [Motion-Project/motion#906]
for me works

    /* Exif requires this exact format */
    snprintf(datetime_buf, 21, "%04d:%02d:%02d %02d:%02d:%02d",
            (timestamp_tm.tm_year + 1900) & 0xffff,
            (timestamp_tm.tm_mon + 1) & 0x0f,
            timestamp_tm.tm_mday,
            timestamp_tm.tm_hour,
            timestamp_tm.tm_min,
            timestamp_tm.tm_sec);

**Comment by tosiara** [comment]
Can you explain what is this issue about?

**Comment by PeterHolik** [comment]
TODO Find better method in

https://github.com/Motion-Project/motion/blob/master/picture.c

    localtime_r(&tv1.tv_sec, &timestamp_tm);
    /* Exif requires this exact format */
    /* The compiler is twitchy on truncating formats and the exif is twitchy
     * on the length of the whole string.  So we do it in two steps of printing
     * into a large buffer which compiler wants, then print that into the smaller
     * buffer that exif wants..TODO  Find better method
     */
    snprintf(tmpbuf, 45, "%04d:%02d:%02d %02d:%02d:%02d",
            timestamp_tm.tm_year + 1900,
            timestamp_tm.tm_mon + 1,
            timestamp_tm.tm_mday,
            timestamp_tm.tm_hour,
            timestamp_tm.tm_min,
            timestamp_tm.tm_sec);
snprintf(datetime_buf, 22,"%.21s",tmpbuf);

**Comment by Mr-Dave** [comment]
Thank you.  That one was really annoying me and I didn't see the solution.  

(I had not really planned on including these revisions for Cosmic/Alpine but needed to get them in for a clean PR/build and get a release out for addressing the 4.2.1 issue with MotionEye #894).

I will leave this issue open for inclusion in a later PR.
