### ISSUE TITLE
Problem with quality

### ISSUE THREAD

**Issue by lukaszog** [Motion-Project/motion#909]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.0
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: V4L - USB
5. hardware [x86, ARM, other]: ARM 
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian 9.6

A few words about my camera:
```
pi@raspberrypi:~ $ v4l2-ctl --list-devices
Pupil Cam2 ID0: Pupil Cam2 ID0 (usb-3f980000.usb-1.2.3):
	/dev/video1
pi@raspberrypi:~ $ ffmpeg -f v4l2 -list_formats all -i /dev/video1
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[video4linux2,v4l2 @ 0x1ae15c0] Raw       :     yuyv422 :           YUYV 4:2:2 : 400x400 192x192
[video4linux2,v4l2 @ 0x1ae15c0] Compressed:       mjpeg :          Motion-JPEG : 400x400 192x192
```
I'm using Motion to stream video from USB camera. I use this camera to track eye and I have problem with good quality. This is a prat of my config file
```
width 192
height 192
framerate 90
v4l2_palette 16
ffmpeg_video_codec mpeg4
```
and output (print screent from browser):
![oko_motion](https://user-images.githubusercontent.com/5604018/52526426-cd364000-2cb8-11e9-984d-951db338f902.png)

As you can see the quality is very poor. Next, I do stream using VLC:

`cvlc v4l2:///dev/video1:width=192:height=192:chroma=H264 --sout '#transcode{vcodec=h264,venc=x264{preset=ultrafast,tune=zerolatency,intra-refresh,lookahead=10,keyint=15},scale=auto,acodec=none,scodec=none}:http{mux=ts,dst=:9999/}' :no-sout-all :sout-keep`

And the output image:
![vlc_stream](https://user-images.githubusercontent.com/5604018/52526445-0f5f8180-2cb9-11e9-94c7-453964cc4344.png)

as you can see the quality is mutch better than motion output. Why? It's sth with my configuration?

**Comment by tosiara** [comment]
Try to specify `v4l2_palette 8`

**Comment by lukaszog** [comment]
I do this but it's the same problem with quality.

**Comment by tosiara** [comment]
Can you upload a log when using `v4l2_palette 8`?

**Comment by Mr-Dave** [comment]
Closing for lack of response.  It would also be requested to upgrade to a more recent version of Motion to see if issue persists.
