### ISSUE TITLE
Question: toggle between two USB cameras /dev/video0 and /dev/video1

### ISSUE THREAD

**Issue by mightycoco** [Motion-Project/motion#911]
Is it possible to switch the device from /dev/video0 to /dev/video1 while streaming? So that stream http://host:8081/0/stream can be toggled showing /dev/video0 and /dev/video1? 
Maybe a http api command?

I tried to change the config value of device=/dev/video0 to device=dev/video1 via the API but that didn't have an effect. The /0/stream was still showing the stream from /dev/video0

**Comment by Mr-Dave** [comment]
This is not going to be possible to have only one camera set up and toggle between them.  There is a LOT of start-up stuff that is particular to the device.  You would need to set it up as two cameras.
