### ISSUE TITLE
Problem with rtsp camera

### ISSUE THREAD

**Issue by lgouj** [Motion-Project/motion#914]
Hello,
I hope this post is at the right place.
I have an IP camera (keekoon) that I want to use with motion on a raspberry pi2 (stretch version). This camera uses rtsp and works well with vlc or ffmpeg (even if there are some error messages when I launch the app).
I have installed MrDave version of motion 4.2.2 (https://github.com/Motion-Project/motion). The result is a grey screen telling "unable to open video device"...the motion log file is linked at the end of the message. The netcam url appears as "<redacted.>" in the log file, but the format in motion.conf is rtsp://admin:@192.168.XX.XX/rtsp_live0.
Is there something wrong in the parameters ?
Before that version of motion, I have tried with the package on https://github.com/Motion-Project/motion/releases/pi_stretch_motion_4.2.2-1.deb with the same result.
Thanks for your help.

here is the motion log file : 
https://gist.github.com/lgouj/94d3a30de25018de75cd3c688f4be17a

**Comment by Mr-Dave** [comment]
Generally, it is better to fill out the issue template questions so we know particulars about the set up you have and ask how to use questions via the mailing list.  The github issues are generally development / code stuff.  

Reviewing your issue/log, it sort of falls in the middle.  It seems that the camera may be connecting very slowly and Motion is failing to get an image.  If you want to try to adjust the code, it probably needs to increase the timeout and retries and `netcam_rtsp.c`  

If you want to avoid the Motion code, try to increase the I frame/key frame rate _in the camera_ which could allow it to send to the decoder in Motion enough information to get an image and decode it.   The key thing in the log is all those 'avcodec_log' messages and the _camera_ parameters rather than the Motion parameters.    

You can also try to turn the `netcam_use_tcp` off. (which is the default for players) but while it may get you to connect to the camera, it will not give acceptable results for motion detection since a solid reliable TCP connection is needed for quality pics.  Motion will probably "smear" a lot of them.

**Comment by lgouj** [comment]
Thanks.
I had a look at the _netcam_rtsp.c_ file. Where can I find the timeout ? I've seen the parameter _rtsp_data->interruptduration_ in 3 functions : _netcam_rtsp_read_image_ (fixed to 10s), _netcam_rtsp_set_parms_ (idem) and _netcam_rtsp_open_context_ (20s). Should I change this parameter ? in the three functions ?

**Comment by tosiara** [comment]
You mentioned that your camera works with ffmpeg. Can you run `ffplay rtsp://your/url`, leave it to run for 1 minute and paste here the full output of ffplay?

**Comment by lgouj** [comment]
Hello Here the requested output of ffplay on the terminal window, after 1min.regards
ffplay version 3.2.12-1~deb9u1+rpt1 Copyright (c) 2003-2018 the FFmpeg developers  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared  libavutil      55. 34.101 / 55. 34.101  libavcodec     57. 64.101 / 57. 64.101  libavformat    57. 56.101 / 57. 56.101  libavdevice    57.  1.100 / 57.  1.100  libavfilter     6. 65.100 /  6. 65.100  libavresample   3.  1.  0 /  3.  1.  0  libswscale      4.  2.100 /  4.  2.100  libswresample   2.  3.100 /  2.  3.100  libpostproc    54.  1.100 / 54.  1.100[h264 @ 0x683033d0] out of range intra chroma pred mode  0B f=0/0   [h264 @ 0x683033d0] error while decoding MB 8 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 7 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 7[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] reference overflow 16 > 15 or 0 > 15 0B f=0/0       Last message repeated 1 times[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] deblocking_filter_idc 4 out of range 0B f=0/0   [h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] top block unavailable for requested intra mode  [h264 @ 0x683033d0] error while decoding MB 9 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 7 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 7[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] reference overflow 16 > 15 or 0 > 15 0B f=0/0       Last message repeated 1 times[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] deblocking_filter_idc 4 out of range 0B f=0/0   [h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] top block unavailable for requested intra mode  [h264 @ 0x683033d0] error while decoding MB 4 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 7 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 7[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] reference overflow 16 > 15 or 0 > 15 0B f=0/0       Last message repeated 1 times[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] deblocking_filter_idc 4 out of range 0B f=0/0   [h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] top block unavailable for requested intra mode  [h264 @ 0x683033d0] error while decoding MB 4 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 7 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 7[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] reference overflow 16 > 15 or 0 > 15 0B f=0/0       Last message repeated 1 times[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] deblocking_filter_idc 3 out of range 0B f=0/0   [h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] top block unavailable for requested intra mode -1[h264 @ 0x683033d0] error while decoding MB 7 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 7 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 7[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] reference overflow 16 > 15 or 0 > 15 0B f=0/0       Last message repeated 1 times[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] deblocking_filter_idc 3 out of range 0B f=0/0   [h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] cbp too large (62) at 31 00KB sq=    0B f=0/0   [h264 @ 0x683033d0] error while decoding MB 31 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 7 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 7[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] reference overflow 16 > 15 or 0 > 15 0B f=0/0       Last message repeated 1 times[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] deblocking_filter_idc 3 out of range 0B f=0/0   [h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] negative number of zero coeffs at 26 0B f=0/0   [h264 @ 0x683033d0] error while decoding MB 26 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 7 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 7[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] reference overflow 16 > 15 or 0 > 15 0B f=0/0       Last message repeated 1 times[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] deblocking_filter_idc 3 out of range 0B f=0/0   [h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] P sub_mb_type 20 out of range at 11 00B f=0/0   [h264 @ 0x683033d0] error while decoding MB 11 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 8 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 8[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] reference overflow 18 > 15 or 0 > 15 0B f=0/0       Last message repeated 1 times[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame![h264 @ 0x683033d0] top block unavailable for requested intra mode -1[h264 @ 0x683033d0] error while decoding MB 2 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] top block unavailable for requested intra mode  [h264 @ 0x683033d0] error while decoding MB 4 0[h264 @ 0x683033d0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x683033d0] illegal reordering_of_pic_nums_idc 8 0B f=0/0   [h264 @ 0x683033d0] illegal modification_of_pic_nums_idc 8[h264 @ 0x683033d0] decode_slice_header error[h264 @ 0x683033d0] no frame!Input #0, rtsp, from 'rtsp://admin:@192.168.X.X/rtsp_live0':=0/0     Duration: N/A, start: 0.040000, bitrate: N/A    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 25 fps, 25 tbr, 90k tbn, 180k tbc[h264 @ 0x680e60e0] illegal modification_of_pic_nums_idc 7[h264 @ 0x680e60e0] decode_slice_header error[h264 @ 0x680e60e0] no frame![h264 @ 0x680e7a00] reference overflow 16 > 15 or 0 > 15[h264 @ 0x680e7a00] decode_slice_header error[h264 @ 0x680e7a00] no frame![h264 @ 0x680eb0f0] deblocking_filter_idc 4 out of range[h264 @ 0x680eb0f0] decode_slice_header error[h264 @ 0x680eb0f0] no frame![h264 @ 0x67e27ef0] top block unavailable for requested intra mode  [h264 @ 0x67e27ef0] error while decoding MB 9 0[h264 @ 0x67e27ef0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x67e8a3c0] illegal modification_of_pic_nums_idc 7[h264 @ 0x67e8a3c0] decode_slice_header error[h264 @ 0x67e8a3c0] no frame![h264 @ 0x680e60e0] reference overflow 16 > 15 or 0 > 15[h264 @ 0x680e60e0] decode_slice_header error[h264 @ 0x680e60e0] no frame![h264 @ 0x680e7a00] deblocking_filter_idc 4 out of range 0B f=0/0   [h264 @ 0x680e7a00] decode_slice_header error[h264 @ 0x680e7a00] no frame![h264 @ 0x680eb0f0] top block unavailable for requested intra mode[h264 @ 0x680eb0f0] error while decoding MB 4 0[h264 @ 0x67e27ef0] illegal modification_of_pic_nums_idc 7[h264 @ 0x67e27ef0] decode_slice_header error[h264 @ 0x67e27ef0] no frame![h264 @ 0x680eb0f0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x67e8a3c0] reference overflow 16 > 15 or 0 > 15[h264 @ 0x67e8a3c0] decode_slice_header error[h264 @ 0x67e8a3c0] no frame![h264 @ 0x680e60e0] deblocking_filter_idc 4 out of range[h264 @ 0x680e60e0] decode_slice_header error[h264 @ 0x680e60e0] no frame![h264 @ 0x680e7a00] top block unavailable for requested intra mode  [h264 @ 0x680e7a00] error while decoding MB 4 0[h264 @ 0x680e7a00] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x680eb0f0] illegal modification_of_pic_nums_idc 7[h264 @ 0x680eb0f0] decode_slice_header error[h264 @ 0x680eb0f0] no frame![h264 @ 0x67e27ef0] reference overflow 16 > 15 or 0 > 15[h264 @ 0x67e27ef0] decode_slice_header error[h264 @ 0x67e27ef0] no frame![h264 @ 0x67e8a3c0] deblocking_filter_idc 3 out of range[h264 @ 0x67e8a3c0] decode_slice_header error[h264 @ 0x67e8a3c0] no frame![h264 @ 0x680e7a00] illegal modification_of_pic_nums_idc 7B f=0/0   [h264 @ 0x680e7a00] decode_slice_header error[h264 @ 0x680e7a00] no frame![h264 @ 0x680e60e0] top block unavailable for requested intra mode -1[h264 @ 0x680e60e0] error while decoding MB 7 0[h264 @ 0x680eb0f0] reference overflow 16 > 15 or 0 > 15[h264 @ 0x680eb0f0] decode_slice_header error[h264 @ 0x680eb0f0] no frame![h264 @ 0x67e27ef0] deblocking_filter_idc 3 out of range[h264 @ 0x67e27ef0] decode_slice_header error[h264 @ 0x67e27ef0] no frame![h264 @ 0x680e60e0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x67e8a3c0] cbp too large (62) at 31 07KB sq=    0B f=0/0   [h264 @ 0x67e8a3c0] error while decoding MB 31 0[h264 @ 0x680e60e0] illegal modification_of_pic_nums_idc 7[h264 @ 0x680e60e0] decode_slice_header error[h264 @ 0x680e60e0] no frame![h264 @ 0x680e7a00] reference overflow 16 > 15 or 0 > 15[h264 @ 0x680e7a00] decode_slice_header error[h264 @ 0x680e7a00] no frame![h264 @ 0x67e8a3c0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x680eb0f0] deblocking_filter_idc 3 out of range[h264 @ 0x680eb0f0] decode_slice_header error[h264 @ 0x680eb0f0] no frame![h264 @ 0x67e8a3c0] illegal modification_of_pic_nums_idc 7[h264 @ 0x67e8a3c0] decode_slice_header error[h264 @ 0x67e8a3c0] no frame![h264 @ 0x680e60e0] reference overflow 16 > 15 or 0 > 15[h264 @ 0x680e60e0] decode_slice_header error[h264 @ 0x680e60e0] no frame![h264 @ 0x67e27ef0] negative number of zero coeffs at 26 0[h264 @ 0x67e27ef0] error while decoding MB 26 0[h264 @ 0x680e7a00] deblocking_filter_idc 3 out of range[h264 @ 0x680e7a00] decode_slice_header error[h264 @ 0x680e7a00] no frame![h264 @ 0x67e27ef0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x680eb0f0] P sub_mb_type 20 out of range at 11 00B f=0/0   [h264 @ 0x67e27ef0] illegal modification_of_pic_nums_idc 8[h264 @ 0x67e27ef0] decode_slice_header error[h264 @ 0x67e27ef0] no frame![h264 @ 0x67e8a3c0] reference overflow 18 > 15 or 0 > 15[h264 @ 0x67e8a3c0] decode_slice_header error[h264 @ 0x67e8a3c0] no frame![h264 @ 0x680eb0f0] error while decoding MB 11 0[h264 @ 0x680eb0f0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x680eb0f0] illegal modification_of_pic_nums_idc 8B f=0/0   [h264 @ 0x680eb0f0] decode_slice_header error[h264 @ 0x680eb0f0] no frame![h264 @ 0x680e60e0] top block unavailable for requested intra mode -1[h264 @ 0x680e60e0] error while decoding MB 2 0[h264 @ 0x680e60e0] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[h264 @ 0x680e7a00] top block unavailable for requested intra mode  [h264 @ 0x680e7a00] error while decoding MB 4 0[h264 @ 0x680e7a00] concealing 3600 DC, 3600 AC, 3600 MV errors in P frame[swscaler @ 0x6474dfc0] deprecated pixel format used, make sure you did set range correctly  68.17 M-V: -4.529 fd= 303 aq=    0KB vq=    0KB sq=    0B f=0/0 




    Le jeudi 28 février 2019 à 10:29:33 UTC+1, tosiara <notifications@github.com> a écrit :  
 
 
You mentioned that your camera works with ffmpeg. Can you run ffplay rtsp://your/url, leave it to run for 1 minute and paste here the full output of ffplay?

**Comment by tosiara** [comment]
I see a lot of errors related to decoding, but I'm not sure if those are really critical. If ffplay is able to display picture, but motion is not - then it's an issue
If you could temporary expose your camera to the internet using port forwarding I could perform some tests to see what may be the issue. Use my GPG public key to encrypt the info in case you want to try (https://api.github.com/users/tosiara/gpg_keys)

**Comment by lgouj** [comment]
I'm not sure : you speak of the port of the IP camera, or the port of the motion software (ie 8081) ?I 've never heard about gpg before. Do I have to install it (on windows 10 for instance) to encrypt the requested IP address and port in order to send it to you ?I don't remember if I told that motion is running on a raspberry pi. Regards 

    Le vendredi 1 mars 2019 à 10:44:02 UTC+1, tosiara <notifications@github.com> a écrit :  
 
 
I see a lot of errors related to decoding, but I'm not sure if those are really critical. If ffplay is able to display picture, but motion is not - then it's an issue
If you could temporary expose your camera to the internet using port forwarding I could perform some tests to see what may be the issue. Use my GPG public key to encrypt the info in case you want to try (https://api.github.com/users/tosiara/gpg_keys)

**Comment by tosiara** [comment]
I would need your camera RTSP port (default TCP/UDP 554), not motion
You can follow this example how to encrypt a message (see bottom): https://github.com/Motion-Project/motion/wiki/Privacy

**Comment by lgouj** [comment]
Please, find my message below.
-----BEGIN PGP MESSAGE-----

hQEMAzwWtUGzwX+nAQf+LtTL1dFl0ldUGbt2iXPreH/LmW0uF7HWUCth6+ICOfmz
PABTNCAIXlJQZObX2SxfPkm1UL7t266fbXZ2vg4p2t3eKYTQlvpli7O/sFkAa6Wt
mQ3lItYkD6gEItv/EB6ABYKSUkbw7a4av97S0cnZTYXVLcQD0XKfGQ4vP7IBF2i9
osbE/dJ8A72iQyDtTFeihgtmWxoNujBDKIypD3nfud74QlXWaqNbDen0Qak4HU5d
+2n3sNdAreLYVJ3dHt/tntg0exuYvvoQ/2UlSABjR8FANJix1XUJgEdpO5kKw3oN
zk4xZubZ/GVdzQxUIkl7Q9ecRxx2PoL8aFQ/4Ub9UtKtAUXOD4FE248rSFMWTdTa
pGPNNqQX3/sGePiySugsi2Wpq7TWhIOgklBzxWRcFXwXhE8nznMaERVizgsADK7p
fyVQZl3aKS/vGiTwGlaP1lQpV9a4J+6x9IcU3MZL4MNixv8ovmDgBoiqGDXg0E5f
uagZ5PHzeuhQFWDLXDcT46DIRtW8m3l7YedsSvZyVskC/PcibO9Zi4WLGY7xOlFM
gNTq9wlyzMhEQfPN+5Y=
=3Rjh
-----END PGP MESSAGE-----



    Le vendredi 1 mars 2019 à 12:58:28 UTC+1, tosiara <notifications@github.com> a écrit :  
 
 
I would need your camera RTSP port (default TCP/UDP 554), not motion
You can follow this example how to encrypt a message (see bottom): https://github.com/Motion-Project/motion/wiki/Privacy

**Comment by tosiara** [comment]
Thanks, I did a test and all worked just perfectly. You can now stop port forwarding
Tested on a low power ARM device
Full log: https://gist.github.com/tosiara/b67766bce48a78fa373149d066e26b7b
Sample picture:

![image](https://user-images.githubusercontent.com/3600973/53873790-bd84ef80-4009-11e9-84c2-75c980224c0b.png)

I can only recommend you to start from scratch, install or compile motion and use motion-dist.conf for the start. Everything should work fine

**Comment by lgouj** [comment]
ok, so you think it's an installation problem. I'll try to desinstall/reinstall motion.

3 last questions :- in your motion-rtsp.conf file, you used exactly the same address I've sent you ?- I don't understand the interest of using a separate config file (camera-dist.conf), if I put all the lines in the motion.conf file ?
- Did you use the motion version available at : https://github.com/Motion-Project/motion ? (Mr Dave 4.2.2).Thanks for your support.
    Le mercredi 6 mars 2019 à 11:18:41 UTC+1, tosiara <notifications@github.com> a écrit :  
 
 
Thanks, I did a test and all worked just perfectly. You can now stop port forwarding
Tested on a low power ARM device
Full log: https://gist.github.com/tosiara/b67766bce48a78fa373149d066e26b7b
Sample picture:



I can only recommend you to start from scratch, install or compile motion and use motion-dist.conf for the start. Everything should work fine

**Comment by tosiara** [comment]
Yes, I used https://github.com/Motion-Project/motion, compiled from sources
Used the exact URL you provided me
If you are using a single camera, you don't have to use camera thread. Just modify the main config file
Here are my changes to the dist config:
```
$ diff -u motion/motion-dist.conf motion-rtsp.conf
--- motion/motion-dist.conf     2019-02-21 19:28:32.122905511 +0200
+++ motion-rtsp.conf    2019-03-06 12:13:04.402454132 +0200
@@ -79,7 +79,7 @@
 ; vid_control_params value

 # The full URL of the network camera stream.
-; netcam_url value
+netcam_url rtsp://*************

 # Name of mmal camera (e.g. vc.ril.camera for pi camera).
 ; mmalcam_name value
@@ -92,13 +92,13 @@
 ############################################################

 # Image width in pixels.
-width 640
+width 1280

 # Image height in pixels.
-height 480
+height 720

 # Maximum number of frames to be captured per second.
-framerate 15
+framerate 30

 # Rotate image this number of degrees. The rotation affects all saved images as
 # well as movies. Valid values: 0 (default = no rotation), 90, 180 and 270.
@@ -178,7 +178,7 @@
 ############################################################

 # Create movies of motion events.
-movie_output on
+movie_output off

 # Maximum length of movie in seconds.
 movie_max_time 60
@@ -211,7 +211,7 @@
 webcontrol_port 8080

 # Restrict webcontrol connections to the localhost.
-webcontrol_localhost on
+webcontrol_localhost off

 # Type of configuration options to allow via the webcontrol.
 webcontrol_parms 0
@@ -224,7 +224,7 @@
 stream_port 8081

 # Restrict stream connections to the localhost.
-stream_localhost on
+stream_localhost off

 ##############################################################
 # Camera config files - One for each camera.
```

**Comment by lgouj** [comment]
I 've started from scratch (fresh and clean install of raspbian stretch). Installed motion like indicated in https://motion-project.github.io/motion_build.html (abbreviated building guide). No error message during the installation. But it doesn't work...However, I've found that I can also watch the stream of my camera using http protocol. Using this http address, motion is working well. I'll use this address, instead of rtsp.thx



    Le mercredi 6 mars 2019 à 14:35:22 UTC+1, tosiara <notifications@github.com> a écrit :  
 
 
Yes, I used https://github.com/Motion-Project/motion, compiled from sources
Used the exact URL you provided me
If you are using a single camera, you don't have to use camera thread. Just modify the main config file
Here are my changes to the dist config:
$ diff -u motion/motion-dist.conf motion-rtsp.conf
--- motion/motion-dist.conf     2019-02-21 19:28:32.122905511 +0200
+++ motion-rtsp.conf    2019-03-06 12:13:04.402454132 +0200
@@ -79,7 +79,7 @@
 ; vid_control_params value

 # The full URL of the network camera stream.
-; netcam_url value
+netcam_url rtsp://*************

 # Name of mmal camera (e.g. vc.ril.camera for pi camera).
 ; mmalcam_name value
@@ -92,13 +92,13 @@
 ############################################################

 # Image width in pixels.
-width 640
+width 1280

 # Image height in pixels.
-height 480
+height 720

 # Maximum number of frames to be captured per second.
-framerate 15
+framerate 30

 # Rotate image this number of degrees. The rotation affects all saved images as
 # well as movies. Valid values: 0 (default = no rotation), 90, 180 and 270.
@@ -178,7 +178,7 @@
 ############################################################

 # Create movies of motion events.
-movie_output on
+movie_output off

 # Maximum length of movie in seconds.
 movie_max_time 60
@@ -211,7 +211,7 @@
 webcontrol_port 8080

 # Restrict webcontrol connections to the localhost.
-webcontrol_localhost on
+webcontrol_localhost off

 # Type of configuration options to allow via the webcontrol.
 webcontrol_parms 0
@@ -224,7 +224,7 @@
 stream_port 8081

 # Restrict stream connections to the localhost.
-stream_localhost on
+stream_localhost off

 ##############################################################
 # Camera config files - One for each camera.
