### ISSUE TITLE
webu_ans when using just motion.conf

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#916]
0. Reviewed guide and contributing documents? (Yes/No):yes
1. version [x.y.z, hash, other]: 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: 18.04

Validate that when using just the motion.conf file without any camera.conf files that the webu_ans is correctly assigning the webu->cnt to the main context (0) rather than context 1.  Test by having just the motion.conf file and then requesting the stream for camera 1 instead of 0.

**Comment by tosiara** [comment]
I can also confirm the segfault
