### ISSUE TITLE
Feature request: "Heartbeat" event

### ISSUE THREAD

**Issue by vkulpa** [Motion-Project/motion#919]
I haven't investigate it deeply but sometime `motion` process dies without any information in the end of log file. I use `log_type all` and `log_level 7 (INF)`

I think it's a good point to add "heartbeat". For example, `on_heartbeat_event` and `heart_interval` to config file. Also, might be useful to have ability pass "active camera connections" and their "detection statuses" etc.

I know, I could put `monit` to check the `motion` process but I think maybe it makes sense to have some option and run `mosquito_pub` or any other external command.

**Comment by tosiara** [comment]
Camera status is available over the HTTP API. If you want to track motion health using some external process, use HTTP API, for example, using curl command

**Comment by quantenschaum** [comment]
I run motion on docker and use `curl -sf http://localhost:5050/0/detection/connection` as [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck).

**Comment by angrycoding** [comment]
I'm just controlling the process itself, and if it dies - restarting it automatically. Simple to do in plain bash script if not running as daemon.

**Comment by quantenschaum** [comment]
Just want to mention `run-one-constantly`.
http://blog.dustinkirkland.com/2013/09/introducing-run-one-constantly-run-one.html

**Comment by vkulpa** [comment]
Thanks all for the responses. Yes, there different ways to monitor it. Closing issue.
