### ISSUE TITLE
Supporting resolutions that are not divisible by 8

### ISSUE THREAD

**Issue by vilhelmgray** [Motion-Project/motion#92]
I have a **Woshida T7866WIP** which produces a snapshot JPEG image with a resolution of `320x180`. The height of 180 pixels is not divisible by 8, so motion gives an error as expected when I point `netcam_url` to the snapshot images. I'm able to get around this by using ImageMagick to pad the images with empty space to increase the height to 184, thus allowing motion to work correctly by using the modified images.

Is there a software limitation that prevents motion from simply padding the images with empty space in order to support arbitrary resolutions?

**Comment by Mr-Dave** [comment]
The original code was established to work off of multiples of 16 and making the changes last year to allow multiples of 8 highlighted a lot of dependencies that were embedded into the logic of the code.  In particular the color space conversion routines, jpg processing etc.  The thought of just using a slightly larger image that was contemplated but I seem to recall that this occasionally triggered seg faults as the images were processed.  For the new code that I added for the netcams,  I added the scaling functionality.  This works by default with the rtsp.  For a http jpeg netcam, I added the mjpeg:// prefix option to the netcam.  The "made up" prefix was an extension of how the historic code was deciding code paths so it was perpetuated.  The mjpeg is changed into a http as the image is retrieved.  This does come at a cost though.  Must have ffmpeg and more CPU as the image is rescaled as captured.  Even if that does solve your problem right now, we can leave this issue open for investigation in a subsequent test / fix.  (Trying to allow it isn't hard, it would be in the netcam.c module where it captures the first image and gets the dimensions ...the hard part is making sure that all the other stuff doesn't break.)

**Comment by vilhelmgray** [comment]
Let me know if I understand correctly: the http:// prefix option attempts to use the JPEG image unmodified as motion receives it, while the mjpeg:// prefix scales the image to a correct size (via ffmpeg) before processing?

**Comment by Mr-Dave** [comment]
I need to make sure that it is clear the two options go down completely different code paths.  It is not just the scaling.  With that technical clarification, then yes.  The http option will not do any sort of scaling and will process the image without adjustment.  With the mjpeg option, if the configuration file has a different resolution than what the camera is sending, then it will rescale the image to "honor" the configuration specified resolution.  As a result, you would put a resolution that is a multiple of 8 within the configuration and Motion should rescale the netcam picture to that resolution.

**Comment by vilhelmgray** [comment]
That's interesting, I'll have to check out the `mjpeg://` prefix option and see how the latency compares with my current scaling via ImageMagick solution.

I also agree that it would be good to keep this issue open for investigation regardless.
