### ISSUE TITLE
[Documentation] Remove commas from command ./builddeb.sh myname, myemail, master, n, any

### ISSUE THREAD

**Issue by whois1230** [Motion-Project/motion#921]
Hello, I tried to build a .deb package as described here: https://motion-project.github.io/motion_build.html It all went fine untill I ran `./builddeb.sh myname, myemail, master, n, any` I ran it twice, and the second time, after installing all of the dependencies I got this: 
`user@debian:~$ ./builddeb.sh myname, myemail, master, n, any

Using Username: myname,, User Email: myemail,, Git Branch: master,, Install Pkgs: n,, Arch: any

All packages installed
Cloning into 'motion'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 6588 (delta 13), reused 31 (delta 13), pack-reused 6548
Receiving objects: 100% (6588/6588), 5.37 MiB | 1.10 MiB/s, done.
Resolving deltas: 100% (4919/4919), done.
error: pathspec 'master,' did not match any file(s) known to git.
Unknown branch
user@debian:~$ 
`

**Comment by tosiara** [comment]
Try to run the command without commas, like:
`./builddeb.sh myname myemail master n any`

**Comment by romaxstd** [comment]
I had the same issue, can confirm that removing the commas from the command resolved the problem.
