### ISSUE TITLE
What do D: L: N: mean using stream_preview_method 3 ?

### ISSUE THREAD

**Issue by DavidMorp** [Motion-Project/motion#922]
0. Reviewed guide and contributing documents? Yes
1. version [4.2.2]
2. installed as a package or compiled from sources [docker: motionproject/motion]
3. standalone or part of third party [motion]
4. video stream source [net cam (rtsp)]
5. hardware [amd64]
6. operating system [16.04] 

I am sorry if this is a stupid question but I could not find that anywhere in the docs.
I am trying to fine tune the motion activation: I am following all the steps (at: [The most difficult step in the above process](https://motion-project.github.io/motion_config.html)) but I fail to fully understand which parameters I am looking for in order to adopt a more rigorous method than "Did this trigger it?".
What do D: L: N: mean using stream_preview_method 3 ?
Also please advise if this is not the place/there are better places to ask this kind of question.
Screenshot attached:
![2019-03-08 13_29_42-motion](https://user-images.githubusercontent.com/17404997/54031296-459ffc00-41a6-11e9-9cb3-3a60ec96c550.png)

**Comment by tosiara** [comment]
It is preferred to ask questions in mail list: https://sourceforge.net/p/motion/mailman/
