### ISSUE TITLE
Pass-through dont produce a valid file-format 

### ISSUE THREAD

**Issue by username7291** [Motion-Project/motion#924]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]:  git
3. standalone or part of third party [motion, MotionEyeOS, other]:  standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: netcam/mjpeg
5. hardware [x86, ARM, other]:  arm
6. operating system [16.04, Stretch, etc, FreeBSD, other]: jessie

I seen pass-through is now available for netcams. Downloaded the newest Version and tryed it.
The source is mjpeg-streamer with "mjpeg:192...."
The produced file is always .mp4 (dont matter what i select movie_codec).
Motion makes some invalid header and passes the whole HTTP after it.
Means Header-JPEG-HTTP-JPEG. You must remove the http stuff like "--boundarydonotcross" and "Content-Type" not pass it into the movie file. It cant be played, dont matter what player.
To make a valid format, from a pre splitted HTTP mjpeg stream, is this command line for example:
"ffmpeg -framrate 10 -i /tmp/movie%%*.jpg -codec copy /tmp/output.mkv"

**Comment by tosiara** [comment]
I think, MJPEG has never been tested with pass through. Let me take a look

**Comment by tosiara** [comment]
I have checked and it works fine. The produced file is alwaus MP4 and this is by design:
```
[1:ml1] [INF] [NET] util_check_passthrough: pass-through is enabled but is still experimental.
[1:ml1] [NTC] [ENC] ffmpeg_passthru_codec: pass-through mode enabled.  Changing to MP4 container.
[1:ml1] [INF] [ENC] ffmpeg_passthru_codec: Pass-through stream opened
[1:ml1] [NTC] [EVT] event_newfile: File of type 8 saved to: /home/ubuntu/0-01-20190312104900.mp4
```
File details:

```
Video
ID                                       : 1
Format                                   : JPEG
Codec ID                                 : mp4v-6C
Duration                                 : 18 s 351 ms
Bit rate mode                            : Constant
Bit rate                                 : 3 338 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 1.362 FPS
Minimum frame rate                       : 0.766 FPS
Maximum frame rate                       : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 1.182
Stream size                              : 7.30 MiB (100%)
```
If you would like to investigate this, please provide your config and log

**Comment by username7291** [comment]
Are you able to play your file? If yes with what player?
VLC display a single frame, Media Player Classic Black Picture,  Windows Media Player Black Picture, Iceweasel "Video file is corrupt", found a very tollerant Video player on another Linux computer it play it but in slowmotion cause FPS is wrong.
Do you look into the file with a HEX Editor/Okteta to verify that
no wrong stuff is in there?
I attach the header for me. Your header says too "JPEG" it must be
Format                                   : V_MJPEG
Codec-ID                                 : V_MJPEG
of course the Random Values
Frame rate mode                          : Constant
Frame rate                    : 10,000 FPS
to be a Video and playable, and of course the HTTP stuff are not
allowed in the File.

Format                                   : MPEG-4
Format-Profil                            : Base Media
Codec-ID                                 : isom (isom/iso2/mp41)
Dateigröße                               : 3,47 MiB
Dauer                                    : 10s 3 ms
Modus der Gesamtbitrate                  : konstant
Gesamte Bitrate                          : 2 911 kb/s
Kodierendes Programm                     : Lavf57.72.101

Video
ID                                       : 1
Format                                   : JPEG
Codec-ID                                 : mp4v-6C
Dauer                                    : 10s 3 ms
Bitraten-Modus                           : konstant
Bitrate                                  : 2 910 kb/s
Breite                                   : 1 280 Pixel
Höhe                                     : 720 Pixel
Bildseitenverhältnis                     : 16:9
Modus der Bildwiederholungsrate          : variabel
Bildwiederholungsrate                    : 4,599 FPS
minimale Bildwiederholungsrate           : 3,348 FPS
maximale Bildwiederholungsrate           : 25,000 FPS
ColorSpace                               : YUV
ChromaSubsampling/String                 : 4:2:2
BitDepth/String                          : 8 bits
Bits/(Pixel*Frame)                       : 0.687
Stream-Größe                             : 3,47 MiB (100%)

[0:motion] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version 57.96.101 libavformat version 57.72.101
[0:motion] [NTC] [ALL] translate_init: Language: English
[0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 0 is from motion.conf
[0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 0 Camera Name: (null) Service: mjpeg
[0:motion] [NTC] [ALL] main: Waiting for threads to finish, pid: 2633
[1:ml1] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
[1:ml1] [NTC] [VID] vid_start: Opening Netcam RTSP
[1:ml1] [INF] [NET] netcam_rtsp_set_parms: Setting up Normal resolution stream.
[1:ml1] [INF] [NET] util_check_passthrough: pass-through is enabled but is still experimental.
[1:ml1] [INF] [NET] Above message repeats 1 times
[1:ml1] [INF] [NET] netcam_rtsp_set_path: Setting up http via ffmpeg netcam
[1:ml1] [INF] [NET] netcam_rtsp_set_http: Normal resolution: Setting http input_format mjpeg
[1:ml1] [INF] [NET] netcam_rtsp_open_context: Normal resolution: Opened camera((null))
[1:ml1] [INF] [ENC] ffmpeg_avcodec_log: deprecated pixel format used, make sure you did set range correctly
[1:ml1] [INF] [NET] netcam_rtsp_copy_stream: Stream copied for pass-through
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: 
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: ******************************************************
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: The image sent is being 
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: trancoded to YUV420P.  If possible change netcam 
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: picture format to YUV420P to possibly lower CPU usage.
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: ******************************************************
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: 
[1:ml1] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
[1:ml1] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
[2:nc2] [NTC] [NET] netcam_rtsp_handler: Normal resolution: Camera handler thread [2] started
[2:nc2] [INF] [NET] netcam_rtsp_set_http: Normal resolution: Setting http input_format mjpeg
[2:nc2] [INF] [NET] netcam_rtsp_open_context: Normal resolution: Opened camera((null))
[2:nc2] [INF] [ENC] ffmpeg_avcodec_log: deprecated pixel format used, make sure you did set range correctly
[2:nc2] [INF] [NET] netcam_rtsp_copy_stream: Stream copied for pass-through
[2:nc2] [NTC] [NET] netcam_rtsp_connect: Normal resolution: Camera ((null)) connected
[1:ml1] [INF] [NET] netcam_rtsp_pktarray_resize: Normal resolution: Resized packet array to 30
[1:ml1] [INF] [EVT] event_new_video: Source FPS 11
[1:ml1] [INF] [NET] util_check_passthrough: pass-through is enabled but is still experimental.
[1:ml1] [NTC] [ENC] ffmpeg_passthru_codec: pass-through mode enabled.  Changing to MP4 container.
[1:ml1] [INF] [ENC] ffmpeg_passthru_codec: Pass-through stream opened
[1:ml1] [NTC] [EVT] event_newfile: File of type 8 saved to: 12032019101912.mp4

Config:
daemon off
log_level 5
pid_file /var/run/motion/motion.pid 
setup_mode off
videodevice /dev/video0
v4l2_palette 9
input -1
norm 0
frequency 0
rotate 0
width 1280
height 720
framerate 11
minimum_frame_time 0
netcam_url mjpeg://192.****
movie_passthrough on
netcam_tolerant_check off
auto_brightness off
roundrobin_frames 1
roundrobin_skip 1
roundrobin_switchfilter off
threshold 4400
threshold_tune off
noise_level 32
noise_tune on
smart_mask_speed 0
minimum_motion_frames 1
pre_capture 0
post_capture 8
event_gap 3
movie_max_time 0
emulate_motion off
picture_output off
picture_output_motion off
picture_quality 85
picture_type jpeg
movie_output on
movie_output_motion off
timelapse_interval 0
timelapse_mode daily
movie_bps 3000000
movie_quality 0
movie_codec mpeg4
locate_motion_mode off
text_right
text_changes off
text_event %d%m%Y%H%M%S
text_scale off
target_dir *
snapshot_filename %v-%Y%m%d%H%M%S-snapshot
picture_filename %v-%Y%m%d%H%M%S-%q
movie_filename %d%m%Y%H%M%S
timelapse_filename %Y%m%d-timelapse
stream_port 0
stream_quality 80
stream_motion off
stream_maxrate 1
stream_localhost off
stream_limit 2
stream_auth_method 0
webcontrol_port 8080
webcontrol_localhost on
webcontrol_interface on
on_event_end echo  '0' > /tmp/MDFIFO
sql_query insert into security(camera, filename, frame, file_type, time_stamp, event_time_stamp) values('%t', '%f', '%q', '%n', '%Y-%m-%d %T', '%C')

**Comment by tosiara** [comment]
This part of your log is suspicious:
```
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: ******************************************************
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: The image sent is being
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: trancoded to YUV420P. If possible change netcam
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: picture format to YUV420P to possibly lower CPU usage.
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: ******************************************************
```
Can you provide the output of `ffprobe -f mjpeg http://192.****`?
In my test it is:
```
Input #0, mjpeg, from 'http://webcam01.bigskyresort.com/mjpg/video.mjpg':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], 25 tbr, 1200k tbn, 25 tbc
```
Try to run a test with this public MJPEG stream: `mjpeg://webcam01.bigskyresort.com/mjpg/video.mjpg`

**Comment by username7291** [comment]
ffprobe:
Input #0, mjpeg, from 'http://192.***':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 1280x720, 25 tbr, 1200k tbn, 25 tbc

Cameras may send different contains. Usual its <HTTP header with contentlength of the next jpeg><JPEG><HTTP contentboundarydonotcross,contentype,contentlength of the next jpeg><JPEG> and so on. Motion remove the header but not the http stuff between jpegs.
Cant try the Public cam, motion says it cant open it(tryed too with ip instead of domainname).

**Comment by username7291** [comment]
Some chars are not work here.
"HTTP HEADER" "JPEG" "HTTP contentboundarydonotcross,contentype,contentlength of the next jpeg" "JPEG" an so on.

**Comment by tosiara** [comment]
Can you find some other MJPEG source to test with?

**Comment by username7291** [comment]
Cause you develop on motion i assume you can feed in a File instead a real camera?
https://ufile.io/ah14k
Thats a stream from a camera i get with wget. Of course wget crops the first header. If you add the wrong header from motion in front of it, its that what motion outputs for me as .mp4
You could also setup mjpeg-streamer, it just needs a webcam and a linux computer.
Access local "netcam_url mjpeg://127.0.0.1:8040/?action=stream"

**Comment by tosiara** [comment]
Sorry, I don't get you. Can you test pass-through with some other public MJPEG stream on the internet? So that I can test the same stream in case you still have the issue

**Comment by username7291** [comment]
your camera link is a public camera and it doesnt work with motion(at all). I try searching a public mjpg camera since a while but i find none working one all 404, or doesnt exist anymore. I continue searching but it would be much more easy to use a local camera with mjpg-streamer feeding motion.

**Comment by username7291** [comment]
Sorry there are no public mjpeg cameras, i search 1 hour now. They use only plain jpg, that is no stream, all others are not online anymore.

**Comment by tosiara** [comment]
So, what you are saying, you can reproduce this issue using a local mjpg-streamer?

**Comment by username7291** [comment]
yes of course, always reproduceable. You require only mjpeg-streamer and a webcam. I use a raspberrypi(Nr.1) with mjpeg-streamer and a raspberrypi(Nr.2) for motion but both cantoo run on a single raspberry. Its the same Output.

**Comment by username7291** [comment]
By the way, motion cant work with a public cam and "mjpeg:" prefix. It works with "http:" prefix, but then motion disables passthrough. "vid_start: Netcam RTSP failed to open"
I tryed to feed motion from another Computer into motion "netcam_url *****://192.*.*.*:8081/" that doesn work too. Its another long standing bug. Motion can´t displayed in Browsers too. Firefox+Firefox Mobile display 1 Frame then "connection interrupted", Andoid Browser shows only a failed download, internet explorer nothing, SmartTV Browser "Download not possible". But cause motion cant passthrough the stream to the webinterface it would have 2-3fps only cause i use mjpeg-streamer anyway.

**Comment by tosiara** [comment]
I have verified the following MJPEG sources with pass-through enabled:
```
netcam_url mjpeg://webcam01.bigskyresort.com/mjpg/video.mjpg
netcam_url v4l2:///dev/video1
netcam_url mjpeg://localhost:8082/?action=stream
```
all worked fine, no HTTP garbage found in the resulting MP4, file is playable in VLC
Also, I can watch motion stream in both desktop Firefox, desktop Chrome and Android Firefox

If you would like to get help setting up your motion, please use user mail list: https://sourceforge.net/p/motion/mailman/

**Comment by username7291** [comment]
Are you really a develloper? If something works for YOUR INSTALLATION it means not it works for everyone else. If you use external parts, for example ffmpeg the whole think depents on the version.
Like motion(config options renames often) ffmpeg use bad developer style and break up compatiblity with new version.
If you pretend "netcam_url mjpeg://webcam01.bigskyresort.com/mjpg/video.mjpg" work its wrong.
Why else i get "INF ENC ffmpeg_avcodec_log: Port missing in uri"?
And why it works if i use "netcam_url mjpeg://webcam01.bigskyresort.com:80/mjpg/video.mjpg"
If you unable to develop for 1000 different ffmpeg versions f***king include one that works!!!

Its right the new motion version can display a stream in firefox, the old version dont.
But the garbadge is too in the file produced with the Public cam. I guess motion depents on a special ffmpeg Version,but you doesnt include it and doesnt say which Version number works. Bad developing.

**Comment by Mr-Dave** [comment]
Redacted Comment
