### ISSUE TITLE
It is possible to store the images captured by a camera in 2 directories at the same time

### ISSUE THREAD

**Issue by oriolrg** [Motion-Project/motion#925]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
3. standalone or part of third party [motion, MotionEyeOS, other]:  motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  mjpeg
5. hardware [x86, ARM, other]: 
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 16

I need to store the images at the same time in two different disks. I have considered the option of having 2 configuration files for the same camera and different target_dir, but it is not optimal I think. Is there any option to place 2 target_dir?

**Comment by jobenvil** [comment]
bitte nimm es mir nicht übel, aber warum auf Valencià?

**Comment by tosiara** [comment]
Ust use a script with `on_picture_save` to copy the file

**Comment by oriolrg** [comment]
> Use a script with `on_picture_save` to copy the file

This works when I save a movie?

**Comment by tosiara** [comment]
For movie you can trigger `on_movie_end`
I recommend you to take a look at documentation: https://motion-project.github.io/motion_config.html
