### ISSUE TITLE
Hikvision acces over NAT

### ISSUE THREAD

**Issue by planetcaravan87** [Motion-Project/motion#926]
Hi there,

I've just installed Motion and Motioneye.

motionEye Version | 0.39.3
Motion Version | 4.0
OS Version | Debian 9.8

I've installed it on Debian via apt-get on a brand new virtual machine.

I've got this scenario:
- Motion on site A 
- Hikvision camera (DS-2CD2042WD-I) on site B
The two sites are on different network (over internet)

I want to add the Hikvision camera on Motion.

Here is the configuration:
![Screenshot - 12_03_2019 , 11_38_28](https://user-images.githubusercontent.com/48476309/54194103-c2d7b380-44bb-11e9-9360-109275080980.png)

I opened the 554 port and on site A I can open the stream using VLC but I can't see it on Motion.
This is the log I got:

`[1:ml1] [NTC] [VID] [Mar 12 11:18:40] vid_v4lx_start: Using videodevice /dev/video0 and input -1
[1:ml1] [ALR] [VID] [Mar 12 11:18:40] vid_v4lx_start: Failed to open video device /dev/video0: No such file or directory
`

After submit, I got only grey screen and no video stream.

![immagine](https://user-images.githubusercontent.com/48476309/54194335-4b565400-44bc-11e9-8dda-c715e28ca68d.png)

It was my fault? Do I have to insert any other settings?
Putting camera and Motion on the same network I've got no problem.

**Comment by tosiara** [comment]
Probably, motioneye generated bad config file as your motion tries to open V4L device instead of netcam. You should report this issue in Motioneye repo, not motion's

**Comment by planetcaravan87** [comment]
I've looked better in the motion.log and I got this:

`
[1:ml1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://XXXX:49158/Streaming/Channels/2)
[1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 401 Unauthorized
[1:ml1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://admin:thecorrectpassword@XXXXX:49158/Streaming/Channels/2): Server returned 401 Unauthorized (authorization failed)`

I've used the same credentials on VLC and all is working fine

**Comment by tosiara** [comment]
Are "admin" and "thecorrectpassword" correctly specified in your motion config file as `netcam_userpass`?

**Comment by planetcaravan87** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Yes                                                                                                                                                                                                                                                                                                                                                   Da: notifications@github.comInviato: 13 marzo 2019 10:42 AMA: motion@noreply.github.comRispondi a: reply@reply.github.comCc: ameschino@gmail.com; author@noreply.github.comOggetto: Re: [Motion-Project/motion] Hikvision acces over NAT (#926)  Are "admin" and "thecorrectpassword" correctly specified in your motion config file as netcam_userpass?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by tosiara** [comment]
Can you run motion standalone and provide the full log?
