### ISSUE TITLE
netcam_url is JPEG and netcam_highres is rtsp, doesn't work

### ISSUE THREAD

**Issue by Whytey** [Motion-Project/motion#931]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: Version 4.2.2
2. installed as a package or compiled from sources [deb, rpm, git, other]: Installed from your deb
3. standalone or part of third party [motion, MotionEyeOS, other]: Standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mixed
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Ubuntu 18.04

Hikvision DS-2CD3345-I

I would like to be able to specify a netcam_url that provides a jpeg image as the low res stream and an associated netcam_highres that is RTSP.  I have tried a few different ways to configure my camera and motion but I can only seem to get it to work if I use a RTSP stream for both normal and highres streams.

Working config (normal is rtsp, highres is rtsp):
```
netcam_url rtsp://192.168.0.120:554/ch1/sub/av_stream
netcam_highres rtsp://192.168.0.120:554/ch1/main/av_stream
netcam_userpass xxx:yyy
netcam_use_tcp on
netcam_keepalive off
stream_port 8081
movie_passthrough on
netcam_tolerant_check off
```

Not working config (normal is jpeg (single image) and highres is rtsp):
```
netcam_url http://192.168.0.120:80/Streaming/channels/101/picture
netcam_highres rtsp://192.168.0.120:554/ch1/main/av_stream
netcam_userpass xxx:yyy
netcam_use_tcp on
netcam_keepalive off
stream_port 8081
movie_passthrough on
netcam_tolerant_check off
```

Is this per design?  Why (since I don't understand the dependency)?

I have been using motion for a long time with just JPEG input and it has worked well in terms of the quality to CPU tradeoff.  I would like to continue taking high-quality snapshots whilst at the same-time using the same input stream for motion detection but having the ability to capture the highres stream at the same time, for little additional overhead.

Thanks,
Whytey

**Comment by tosiara** [comment]
Personally, I have never tested mixed pixel formats with passthrough. This needs to be verified

**Comment by tosiara** [comment]
I have checked and all worked fine

First of all, for passthrough mjpeg must use mjpeg:// as prefix:
https://motion-project.github.io/motion_config.html#movie_passthrough
```
For mjpeg cameras, the url must be specified using the mjpeg prefix rather than as http
```
Additionally, you need to specify port in the URL, otherwose you will get:
```
[1:ml1:motion] [INF] [ENC] ffmpeg_avcodec_log: Port missing in uri
```
I used the following config params - small rtsp, highres - mjpeg:
```
netcam_url rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
netcam_highres mjpeg://webcam01.bigskyresort.com:80/mjpg/video.mjpg
```

**Comment by Whytey** [comment]
Hi, I've also gotten it to work similar to your setup but with rtsp being the high-res stream. I encountered the port issue you noted also.

I was looking to use a normal resolution stream that wasn't an actual mjpeg source bit just a single jpeg image that updated continuously. That didn't seem possible based on my testing. 

Should it be possible? If not, what's the technical reason why? Any ideas of how to work around it?

**Comment by tosiara** [comment]
If you feed jpegs for "normal" resolution and you have "highres" specified for passthrough, then you should be fine to feed jpegs there over http
