### ISSUE TITLE
Missing the old style

### ISSUE THREAD

**Issue by krambriw** [Motion-Project/motion#933]
0. Reviewed guide and contributing documents? (Yes/No):Y
1. version [x.y.z, hash, other]: 4.1.1 and later
2. installed as a package or compiled from sources [deb, rpm, git, other]:deb, git 
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:USB only 
5. hardware [x86, ARM, other]: x86, ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: stretch, jessie, ubuntu 18 

I really miss the old style web gui look for configuration, it was simple but easy to use. Like in 4.1.1
In later version like 4.2.2 it is maybe nicer but more time consuming. I have reverted back to editing config files directly

**Comment by tosiara** [comment]
Have checked this?
https://motion-project.github.io/motion_config.html#webcontrol_interface

**Comment by krambriw** [comment]
Oooops, sorry

My very best regards, Walter
