### ISSUE TITLE
start stop motion service gives an unwanted recording/motion

### ISSUE THREAD

**Issue by pvklink** [Motion-Project/motion#936]
Hi, I use the motion version installed with: sudo apt-get install motion. I use the latest rasbian on a rpi 3b.

My problem:
my domotica starts and stops the motion service when nobody is at home. When the service is started, it also starts recording default like there was a motion. I dont want a recording when the service is started or restarted, is that possible?

I know that i dont have the latest motion software. Is it possible to upgrade tot the latest beta with the commands below with the knowledge that i started my configuration with  (sudo apt-get install motion)

Question: can i give these commands on my existing configuration?
wget https://github.com/Motion-Project/motion/releases/{deb package name}
sudo apt-get install gdebi-core
sudo gdebi {deb package name}

**Comment by tosiara** [comment]
Motion should not start recording after starting the service. You should try to enable `movie_output_motion` and check maybe your camera really gets changed pixels at start

**Comment by tosiara** [comment]
If you have questions about configuring motion - please use mail list: https://sourceforge.net/p/motion/mailman/motion-user/
