### ISSUE TITLE
netcam_highres and manual screenshots

### ISSUE THREAD

**Issue by aLiEnHeAd13** [Motion-Project/motion#942]
Hi,
I'm using motoneyeOS 0.40 with motion 4.2.2

I configured my cam with a low-res viewing stream and a high-res rtsp recording stream via the `netcam_highres` option. `movie_passthrough` is not set.
The motion detected screenshots and movies are high-res but manual screenshots are low-res.
In my opinion manual screenshots should use the high resolution as well.

**Comment by tosiara** [comment]
I will try to verify this

**Comment by tosiara** [comment]
Confirmed bug. Manual screenshot is saved from "Normal resolution".
Movie, picture and timelapse are saved correctly from "High resolution"

**Comment by angrycoding** [comment]
> Confirmed bug. Manual snapshot is saved from "Normal resolution".
> Movie, picture and timelapse are saved correctly from "High resolution"

Actually there must be some preference in order for user to choose from which stream he wants to take a screenshot. I can imagine the situation where taking a screenshot from low - res stream might be required.

**Comment by aLiEnHeAd13** [comment]
> 
> Actually there must be some preference in order for user to choose from which stream he wants to take a screenshot.

That would be the movie_passthrough option https://motion-project.github.io/motion_config.html.
But when this option was not set, all captured images (motion detected an manual) should use the hi-res stream

**Comment by angrycoding** [comment]
> > Actually there must be some preference in order for user to choose from which stream he wants to take a screenshot.
> 
> I think that would be the movie_passthrough option.

No. There might be situations where you need to use movie_passtrough and still being able to set where exactly you want to take screenshot from (primary or secondary stream).

**Comment by eddyg** [comment]
Has there been any decision on resolving this issue?

I'd _really_ like a way to snapshot the `netcam_highres` stream...
