### ISSUE TITLE
Restart: motion detected

### ISSUE THREAD

**Issue by pi1993** [Motion-Project/motion#943]
I've got some problems with the Raspberry Pi 3 B+ and Motion. I just downloaded the version two weeks ago. I have to make a batch program, who stop the motion services, makes a picture with raspistill and restart the motion services. 

The config file of motion is all mostly by default. If motion detects motion, I will get a mail with a python script. It works pretty well, if the box is dark. I just got a mail, if someone opened the door. But if the light is on in the box, i always get a Mail when motion start again. (Every time a picture is made) I can't find the problem. 

At the moment the camera works with 360x480 pixel. If the threshold is on 20'000, it don't get a mail by restart(what is good). But this is like 20% movement on the picture and i don't get it if motion is normally running. I also tried with light = 100. But the same problem... By restart motion is detected... Do you have an idea, how it could work without the threshold on 20'000? I have 10 of this raspis to config. It would be nice, if the solution is an onliner... 

Thanks for any advice.

**Comment by tosiara** [comment]
Better to ask questions on user list, not on bug tracker
