### ISSUE TITLE
[Documentation] Error with html preview

### ISSUE THREAD

**Issue by kutysam** [Motion-Project/motion#944]
https://github.com/Motion-Project/motion/releases

The documentation for the 4.2.2 release can be found in the "Motion 4.2.2 Guide"

https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/release-4.2.2/motion_guide.html

Clicking on Motion 4.2.2 guide directs us to the link above. CSS etc, are out of order.

**Comment by tosiara** [comment]
https://github.com/Motion-Project/motion/issues/607#issuecomment-355844946

**Comment by Mr-Dave** [comment]
Looks like the previous sites used for rendering pages directly from repos no longer work.  Unless someone else provides a solution, the course of action will be to remove the viewing of the git master from the documentation page and then manually replicate somewhere else.

**Comment by Mr-Dave** [comment]
Resolved
