### ISSUE TITLE
Invalid data found when processing RTSP input

### ISSUE THREAD

**Issue by mtekeli** [Motion-Project/motion#946]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]: MotionEyeOS dev20190511
2. installed as a package or compiled from sources [deb, rpm, git, other]: https://github.com/ccrisan/motioneyeos/releases
3. standalone or part of third party [motion, MotionEyeOS, other]: MotionEyeOS
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Buildroot of MotionEyeOS

My camera works with VLC (I can stream) but not with MotionEyeOS. I successfully added the camera but when it tries to open it says unable to open the device.

**Here is the stream url: rtsp://192.168.1.7:554/onvif1 (working fine with VLC)
Camera: Sricam SP020**

/var/log/messages

> 

> May 18 09:03:11 meye-e73aba9a user.notice motion: [0:motion] [NTC] [ALL] motion_start_thread: Camera ID: 1 Camera Name: Camera1 Service: rtsp:
May 18 09:03:11 meye-e73aba9a user.notice motion: [1:ml1:Camera1] [NTC] [ALL] motion_init: Camera 1 started: motion detection Enabled
May 18 09:03:11 meye-e73aba9a user.notice motion: [1:ml1:Camera1] [NTC] [VID] vid_start: Opening Netcam RTSP
May 18 09:03:12 meye-e73aba9a user.err motion: [1:ml1:Camera1] [ERR] [NET] netcam_rtsp_open_context: Normal resolution: Unable to open camera(Camera1): Invalid data found when processing input
May 18 09:03:12 meye-e73aba9a user.notice motion: [1:ml1:Camera1] [NTC] [NET] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
May 18 09:03:12 meye-e73aba9a user.err motion: [1:ml1:Camera1] [ERR] [VID] vid_start: Netcam RTSP failed to open
May 18 09:03:12 meye-e73aba9a user.warn motion: [1:ml1:Camera1] [WRN] [ALL] motion_init: Could not fetch initial image from camera
May 18 09:03:12 meye-e73aba9a user.warn motion: [1:ml1:Camera1] [WRN] [ALL] motion_init: Motion continues using width and height from config file(s)
May 18 09:03:12 meye-e73aba9a user.notice motion: [1:ml1:Camera1] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
May 18 09:03:12 meye-e73aba9a user.notice motion: [1:ml1:Camera1] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 21 items

Unfortunately there seems to be no MJPEG stream from this camera. So RTSP is my only chance to get it working.

UPDATE: A full log
[full_log.txt](https://github.com/Motion-Project/motion/files/3193918/full_log.txt)

**Comment by tosiara** [comment]
please provide full log with `-d 7`

**Comment by mtekeli** [comment]
@tosiara I updated the issue

**Comment by tosiara** [comment]
```
[1:ml1:Camera1] [INF] [NET] netcam_rtsp_set_rtsp: Normal resolution: Setting rtsp transport to tcp
[1:ml1:Camera1] [INF] [ENC] ffmpeg_avcodec_log: Nonmatching transport in server reply
[1:ml1:Camera1] [ERR] [NET] netcam_rtsp_open_context: Normal resolution: Unable to open camera(Camera1): Invalid data found when processing input
```
Verify if your camera supports TCP or UDP:
`ffplay  -rtsp_transport tcp rtsp://192.168.1.7:554/onvif1`

**Comment by mtekeli** [comment]
Looks like it does not.

ffplay -rtsp_transport tcp rtsp://192.168.1.8:554/onvif1
> [rtsp @ 0x7fdf0288ae00] Nonmatching transport in server reply=0/0
> rtsp://192.168.1.8:554/onvif1: Invalid data found when processing input

ffplay rtsp://192.168.1.8:554/onvif1
>   Metadata:
    title           : H.264 Video, RtspServer_0.0.0.2
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 1280x720, 12.50 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

**Comment by tosiara** [comment]
If your camera is UDP only, you have to put into your config `netcam_use_tcp off`

**Comment by mtekeli** [comment]
I put that into `motion.conf` and when I opened the web page I was able to stream from the camera.

```bash
[root@meye-e73aba9a ~]# cat /data/etc/motion.conf
# @normal_password
# @enabled on
# @show_advanced on
# @admin_username admin
# @admin_password 876a381c782e9682ffdf8a67d79e71a5cdb99d28
# @normal_username user
netcam_use_tcp off

webcontrol_interface 1
setup_mode off
webcontrol_parms 2
webcontrol_localhost on
webcontrol_port 7999

camera camera-1.conf
```

Many thanks @tosiara 
/Close

**Comment by scorninpc** [comment]
nowadays, using `rtsp_uses_tcp off` instead `netcam_use_tcp off` works like a charm.

**Comment by battlet01** [comment]
I was following this thread as I am having the same issue. Only difference is I fail using either UDP and TCP. 
rtsp://blah:blah@192.168.1.58:554: Invalid data found when processing input 
This is regardless of UDP/TCP
I motion I see that same.

[2:ml2:Master Came] [ERR] [NET] netcam_rtsp_open_context: Normal resolution: Unable to open camera(Master Camera): Invalid data found when processing input
[2:ml2:Master Came] [ERR] [VID] vid_start: Netcam RTSP failed to open

The interesting thing is I can pull it up in vlc.  The odd part is I can do this without any paths such an /onvif1. Matter of fact it will work with almost any path. The camera is a HIJUNMI, but I cannot find any sort of documentation from the vendor/manufacturer.

**Comment by tosiara** [comment]
@battlet01, test using `ffplay`. If it plays - motion will work too

**Comment by LoicTryToDev** [comment]
I everyone,

I have the same issue than @bottlet01.
The stream working just fine on VLC, but absolutely no way getting stream from node-rtsp-stream, nor node-onvif and  ispy.

I am just turning creazy. It's like IPC360 (cam IPC365) team's did their job pretty well and prevent us from getting stream from their IP Cam.

I don't understand how VLC is working so easily while others just don't, is not there a way copying VLC's process ?

Hope you can help me, my last option is to buy another ip cam. Maybe you could advise me with a brand and model easily compatible with node-rtsp-stream, node-onvif and/or ispy. They do have a huge database, but I can't trust it since IPC365 is part of it and it's not working. I'd rather not buying and test all the database :-)

(sorry for my english)

Wich you all a good day,

LoicTryToDev

**Comment by tosiara** [comment]
@LoicTryToDev, test using ffplay. If it plays - motion will work too

**Comment by eusoubrasileiro** [comment]
@LoicTryToDev  I have the same problem as you. My Camera is Yoosee It works pretty well on `VLC`, `Agent DVR` or `iSpy`. 
I am also using Ubuntu 18 in a _Windows 10 - Wsl 2_ . In my case I get ffplay receives a `segmentation fault`

**Comment by lgonzale44** [comment]
**Here with my IPC365 ip cam. Same issue. VLC works great and motion didnt recognize. This is part of the log**

[1:Unknown] [INF] [NET] [Jun 05 11:20:40] netcam_rtsp_set_parms: Setting up Normal resolution stream.
[1:Unknown] [INF] [NET] [Jun 05 11:20:40] netcam_rtsp_set_path: Setting up rtsp via ffmpeg netcam
[1:Unknown] [INF] [NET] [Jun 05 11:20:40] netcam_rtsp_set_rtsp: Normal resolution: Setting rtsp transport to udp
[1:Unknown] [ERR] [NET] [Jun 05 11:20:40] netcam_rtsp_open_context: Normal resolution: Unable to open camera((null)): Invalid data found when processing input
[1:Unknown] [INF] [NET] [Jun 05 11:20:40] netcam_rtsp_cleanup: Normal resolution: Shutting down network camera.
[1:Unknown] [NTC] [NET] [Jun 05 11:20:40] netcam_rtsp_cleanup: Normal resolution: Shut down complete.
[1:Unknown] [ERR] [VID] [Jun 05 11:20:40] vid_start: Netcam RTSP failed to open
[1:Unknown] [WRN] [ALL] [Jun 05 11:20:40] motion_init: Could not fetch initial image from camera


**Try ffmpeg under other OS and still fails:**
C:\Program Files (x86)\FFmpeg for Audacity>ffmpeg -i rtsp://admin:123456@192.168.0.3
rtsp://admin:123456@192.168.0.3: Invalid data found when processing input
Conversion failed!

By the moment, my conclusion is ICP365 isn't compatible with "motion".

**Comment by eusoubrasileiro** [comment]
If you suspect it's something related with RTSP setup.
This might help someone else. [How I solved all my problems.](https://stackoverflow.com/q/66280861/1207193) For those cheap cameras (or not so cheap) that are not very RTSP/ONVIF compliant!

**Comment by lgonzale44** [comment]
Appears to be a code problem with the camera...
http://www.toughdev.com/content/2019/09/reverse-engineering-the-360eyes-pro-ipc365-wireless-cctv-camera/

There is a serious issue with the RTSP implementation on this camera caused by a typo before the ssrc parameter during the RTP setup phase. The following is the data sent by the camera:

Transport: RTP/AVP;unicast;client_port=8000-8001;server_port=9000-9001,ssrc=1234
Notice the comma before ssrc which should have been a semicolon. The correct data should have been:

Transport: RTP/AVP;unicast;client_port=8000-8001;server_port=9000-9001;ssrc=1234
The above typo prevents the camera from being used in iSpy or FFmpeg but HappyTime RTSP client has no issues. VLC has no issues playing back the video, but does not split the recorded files properly when used on the iPC365’s RTSP stream. This issue prevented me from using my Raspberry Pi with FFmpeg to remotely capture the camera video footage, and I decided to spend some time finding a solution.

**Comment by tosiara** [comment]
Related: https://github.com/Motion-Project/motion/issues/1071

**Comment by eusoubrasileiro** [comment]
@lgonzale44 since its a RTSP setup issue. You might try some ffmpeg [hacking (little customizations) like I did ](https://stackoverflow.com/q/66280861/1207193).

**Comment by stigfagrell** [comment]
Hi!
I find a work around by patching ffmpeg

> Transport: RTP/AVP;unicast;client_port=8000-8001;server_port=9000-9001,ssrc=1234 Notice the comma before ssrc which should have been a semicolon. The correct data should have been:

In libavformat/rtsp.c
function rtsp_parse_transport()
ner the end changing 

            if (*p == ';')
                p++;
to 
            if (*p == ';' || *p == ',')
                p++;

**Comment by eusoubrasileiro** [comment]
@stigfagrell awesome, I will try someday your solution if it applies to make case. Supporting comma and semicolon cool.
[The problem I faced,](https://stackoverflow.com/questions/66280861/ffmpeg-nonmatching-transport-in-server-reply-but-openrtsp-works) and probably most people here are facing, is due these crazy cameras not being really RTSP compliant. 
Those hackings solve the problems but they are also a pain, due the fact that probably each new crazy camera might have some other noncompliance on its setup message (mistyped etc).
