### ISSUE TITLE
It looks like the latest version does not have pi_jessie_motion_4.2.2-1_armhf.deb version but it does have a stretch version.  Is it possible to have a jessie armhf version?

### ISSUE THREAD

**Issue by bkoblenz** [Motion-Project/motion#947]
0. Reviewed guide and contributing documents? (Yes/No):
1. version [x.y.z, hash, other]: 
2. installed as a package or compiled from sources [deb, rpm, git, other]: 
3. standalone or part of third party [motion, MotionEyeOS, other]: 
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: 
5. hardware [x86, ARM, other]: 
6. operating system [16.04, Stretch, etc, FreeBSD, other]:

**Comment by tosiara** [comment]
Please use mail list for questions
https://sourceforge.net/p/motion/mailman/motion-user/?viewmonth=201902

**Comment by bkoblenz** [comment]
I tried to follow the link, but the service is unavailable.  So maybe it is
appropriate to hit reply all!

Sorry for asking an inappropriate question on github.

However, I am still interested in a 4.2.2 version of motion for a jessie
installation of raspberry pi (that is already running 4.1.1).
Is there a pi_jessie_motion_4.2.2-1_armhf.deb version that I can wget?  Of
some directions for upgrading jessie from 4..1.1 to 4.2.2?

I am particularly interested in the new movie_passthrough feature.

thanks
-brian


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
