### ISSUE TITLE
Documentation: lightswitch_percent an upper or lower threshold

### ISSUE THREAD

**Issue by gaenserich** [Motion-Project/motion#948]
There is an ambiguity in the documention (both https://motion-project.github.io/motion_config.html#lightswitch_percent and in the man page) regarding the `lightswitch_percent` parameter: Will motion suspend motion detection when the total area that changes intensity is **greater than** or **less than** this percentage?

**Comment by genius3000** [comment]
**greater than** 
The thought is that a lot of the picture changes due to the light change (each pixel gets brighter or a change from day/night mode).

**Comment by gaenserich** [comment]
Fixed in https://github.com/Motion-Project/motion/pull/949
