### ISSUE TITLE
Can Live Stream over https?

### ISSUE THREAD

**Issue by monzuguan** [Motion-Project/motion#957]
0. Reviewed guide and contributing documents? (Yes/No):Yes
1. version : motion Version 3.4.0-Git-78ba2da
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: USB uvc cam
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: OpenWrt
Can Live Stream over https or  uhttpd /motion path instead?

**Comment by tosiara** [comment]
No, version 3.4 does not support streaming over https. You will need to upgrade to 4.2.2 and compile with libmicrohttpd
