### ISSUE TITLE
[h264_omx] Bitrate integer oveflow causes 4kbps video encoder bit rate

### ISSUE THREAD

**Issue by jasaw** [Motion-Project/motion#958]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: various version since July 2017
2. installed as a package or compiled from sources [deb, rpm, git, other]: other
3. standalone or part of third party [motion, MotionEyeOS, other]: MotionEyeOS
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mmal
5. hardware [x86, ARM, other]: ARM
6. operating system [16.04, Stretch, etc, FreeBSD, other]: MotionEyeOS
7. video encoder: h264_omx (Raspberry Pi all models)

Occasionally, motion software sets the default 4kbps bit rate when encoding videos. When it's working correctly, the bit rate should be in the Mbps range. I am seeing this bug about once a week, but don't know how to trigger it. Maybe there's a race condition somewhere in motion software?

This is the log from one of the MotionEyeOS users:
>Jun 17 20:37:59 Cam-Terasa user.info motion: [1:ml1:Cam-Terasa] [INF] [ENC] ffmpeg_set_quality: h264_omx codec vbr/crf/bit_rate: 4000
Jun 17 20:07:56 Cam-Terasa user.info motion: [1:ml1:Cam-Terasa] [INF] [ENC] ffmpeg_set_quality: h264_omx codec vbr/crf/bit_rate: 3375000

Original bug report here:
https://github.com/ccrisan/motioneyeos/issues/1900

**Comment by tosiara** [comment]
Do you have full log for this issue?

**Comment by tosiara** [comment]
So far this code is responsible for the 4000 bitrate: https://github.com/Motion-Project/motion/blob/master/ffmpeg.c#L558
```
if ((strcmp(ffmpeg->codec->name, "h264_omx") == 0) || (strcmp(ffmpeg->codec->name, "mpeg4_omx") == 0))
{
   // H264 OMX encoder quality can only be controlled via bit_rate
   // bit_rate = ffmpeg->width * ffmpeg->height * ffmpeg->fps * quality_factor
   ffmpeg->quality = (ffmpeg->width * ffmpeg->height * ffmpeg->fps * ffmpeg->quality) >> 7;
   // Clip bit rate to min
   if (ffmpeg->quality < 4000) // magic number
         ffmpeg->quality = 4000;
```
The pictures in motioneye bug shows that produced videos are 3fps and 8fps. Framerate differs more than 2.5 times. And as you can see OMX quality param depends on the framerate. This may explain the issue

Anyway, the code looks very hackish. From this PR https://github.com/Motion-Project/motion/pull/477 @jasaw  was the author, so maybe you could comment?

**Comment by jasaw** [comment]
@tosiara Thanks for looking into this. It does appear that `ffmpeg->fps` variable keeps changing. It's set [here](https://github.com/Motion-Project/motion/blob/c43a56095e78a41e337010f8a1e016a4bf57014f/event.c#L1014) in event.c when it sets up the ffmpeg struct, based on `cnt->movie_fps`, so that means `cnt->movie_fps` changes significantly? It's probably better to use `cnt->conf.framerate` instead of `ffmpeg->fps`, but what's the preferred way of getting this `cnt->conf.framerate` into ffmpeg?

The quality of the encoded video ranges from 0 to a maximum that is calculated from width * height * fps. Setting quality to the maximum value means no video compression, which defeats the purpose of using the encoder, so I multiply the maximum with some arbitrary "quality factor" that still produces good quality video with no noticeable drop in video quality, and also does not choke the I/O when writing to disk/sdcard. This "quality factor" multiplier ended up being a right shift of 7 bits.
This video quality setting is very hacky because it's a trade-off between perceived acceptable quality vs other limitations in a typical system, which is subjective.

**Comment by tosiara** [comment]
`cnt->movie_fps` reflects the real framerate your camera provides. For example, if you specify in the config 100 fps, but your camera only supports 30 - you are in trouble. Another example, you can specify 30fps, which is valid, but because of auto exposure and low light camera drops to 10 fps - you are again in trouble.
That's why motion uses `cnt->movie_fps` as it contains the latest real frame rate. Not always accurate, but it is better than rely on config value
You would need to debug, why your quality calculated is low, but the framerate is still high. Maybe there is another issue. Like in the original bug you mentioned: the first file has 3fps and 7120kbps, the second file - 8fps and 99kbps. Given that resolution has not changed what was the value of `ffmpeg->quality` before the calculation?
I'd add more logging there, recompile and try to solve the puzzle

**Comment by jasaw** [comment]
The fmpeg->quality before calculations comes from cnt->conf.movie_quality, which does not change. The only variable here is ffmpeg->fps.

Assuming movie_quality was set to 75, at 1600x1200 resolution, at 7fps we get a bit over 7 Mbps. To get 99kbps, the fps needs to drop to less than 0.1 fps. ffmpeg->fps looks wrong to me. Either way, quality calculation should be based on cnt->conf.framerate

**Comment by Mr-DaveDev** [comment]
I believe the cause is that he intermediate step of the calculation exceeds the size of an `int` on a 32 bit machine.  Rather than bit shifting, probably best to just do normal math and take ((h * w )/128)*fps * quality

**Comment by jasaw** [comment]
@Mr-DaveDev has a good point. The calculation will overflow on a 32-bit machine. Better to do the calculation is 64-bit, then drop it back down to 32-bit.
See https://github.com/Motion-Project/motion/pull/959

**Comment by tosiara** [comment]
Confirmed, 32 bit integer will overflow, for example 1600x1200, 75 quality, 15fps
