### ISSUE TITLE
Not able to use mask file

### ISSUE THREAD

**Issue by RenaKunisaki** [Motion-Project/motion#960]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.0
2. installed as a package or compiled from sources [deb, rpm, git, other]: apt
3. standalone or part of third party [motion, MotionEyeOS, other]: Raspbian package
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: Raspberry Pi camera
5. hardware [x86, ARM, other]: Raspberry Pi 3b
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian; 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux

At startup, messages in the log suggest it's trying to *write* to the mask file:

```
[1:ml1] [NTC] [ALL] [Jun 19 19:44:24] image_ring_resize: Resizing pre_capture buffer to 1 items
[1:ml1] [ERR] [ALL] [Jun 19 19:44:24] create_path: Problem creating directory value : Permission denied
[1:ml1] [ERR] [ALL] [Jun 19 19:44:24] motion_init: Error opening mask file value /var/lib/motion/mask.pgm: Permission denied
[1:ml1] [ERR] [ALL] [Jun 19 19:44:24] create_path: Problem creating directory value : Permission denied
[1:ml1] [ERR] [ALL] [Jun 19 19:44:24] put_fixed_mask: can't write mask file value /var/lib/motion/mask.pgm - check access rights to target directory: Permission denied
[1:ml1] [ERR] [ALL] [Jun 19 19:44:24] motion_init: Failed to read mask image. Mask feature disabled.
```

The file exists and should be usable:
```
$ stat /var/lib/motion/mask.pgm 
  File: /var/lib/motion/mask.pgm
  Size: 921662    	Blocks: 1808       IO Block: 4096   regular file
Device: b302h/45826d	Inode: 3355        Links: 1
Access: (0644/-rw-r--r--)  Uid: (  110/  motion)   Gid: ( 1000/      pi)
Access: 2019-06-19 14:51:02.444655092 -0400
Modify: 2019-06-19 14:51:04.374629574 -0400
Change: 2019-06-19 15:04:07.345095923 -0400
 Birth: -

$ ls -al /var/lib/motion/
total 1028
drwxr-s---  3 motion adm  114688 Jun 19 15:00 .
drwxr-xr-x 42 root   root   4096 Jun 16 16:17 ..
-rw-r--r--  1 motion pi   921662 Jun 19 14:51 mask.pgm
drwxr-sr-x  3 motion adm    4096 Jun 19 15:04 recordings
```

Besides that, the program is working.
[motion.conf](https://github.com/Motion-Project/motion/files/3308279/motion.conf.txt)

**Comment by RenaKunisaki** [comment]
https://gist.github.com/RenaKunisaki/c3a57294a49874e1e1bb23166b222f4f motion.log

**Comment by tosiara** [comment]
`Permission denied` means that the user you are using to run motion has no permission.
How do you run motion? Which user are you suing: root, motion or pi?

**Comment by RenaKunisaki** [comment]
It's running as `motion`. `/var/lib/motion` is readable and owned by `motion` and group `adm` just like the `mask.pgm` file.

It looks like it's trying to write to the mask file?

**Comment by tosiara** [comment]
Make a test, put the mask in your user's home directory. Will it work that way?

**Comment by tosiara** [comment]
yes, it seems to write:
```
put_fixed_mask: can't write mask file value /var/lib/motion/mask.pgm - check access rights to target directory: Permission denied
```

**Comment by tosiara** [comment]
/**
 * put_fixed_mask
 *      If a mask file is asked for but does not exist this function
 *      creates an empty mask file in the right binary pgm format and
 *      and the right size - easy to edit with Gimp or similar tool.
 */

**Comment by tosiara** [comment]
Your config is malformed:
```
mask_file value /var/lib/motion/mask.pgm
```
Remove "value"

**Comment by RenaKunisaki** [comment]
Aha, whoops. I thought "value" was part of the message, didn't realize it had got into the config somehow.
