### ISSUE TITLE
[github] Travis CI fails since May 2019 - Ubuntu 17.10 /bin/bash: autoreconf: command not found

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#962]
I noticed that all PRs submitted since May are failing Travis checks:

![image](https://user-images.githubusercontent.com/3600973/59840326-cc927200-935a-11e9-9e48-58354db42265.png)

The only check that fails is Ubuntu 17.10:

![image](https://user-images.githubusercontent.com/3600973/59840510-285cfb00-935b-11e9-98d9-db20c7c1f47d.png)

```
/bin/bash: autoreconf: command not found
```

**Comment by Mr-DaveDev** [comment]
Docker/Ubuntu appears to have dropped 17.10 support a bit before EOL so the travis file will need to be updated to remove it from the test cycle.
