### ISSUE TITLE
[feature request] Per-camera config param to start thread with motion detection paused

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#964]
Right now there only one way to start motion with detection paused: -m command line switch. This will pause motion detection on all threads.
A user would like to be able to pause motion detection on start per camera. A new camera config param required to achieve that, like `motion_paused off` which will be `off` by default

**Comment by angrycoding** [comment]
It's actually very good idea to introduce such param. To overcome this limitation in my setup I'm currently using workaround - omitting netcam_url, and setting it up later through webcontrol interface.
