### ISSUE TITLE
This is how it should be spelled out. fix it im on Mint OS and not working on here (64 bit). Thanks.

### ISSUE THREAD

**Issue by jamieduk** [Motion-Project/motion#965]
PS this is for the following os:

This script is only functional for Debian, Ubuntu and Raspbian

so before you start thats a good thinkg to check first before wasting your time.

git clone https://github.com/Motion-Project/motion.git

sudo apt install -y gdebi-core 

wget https://raw.githubusercontent.com/Motion-Project/motion-packaging/master/builddeb.sh

sudo chmod +x *.sh

Now run the script.

./builddeb.sh myname, myemail, master, n, any 

or for anonamouse

./builddeb.sh 

Install
https://motion-project.github.io/motion_build.html

Usage

https://motion-project.github.io/motion_guide.html

Motion
Status

The build status from travis-ci for the master branch is: Build Status
Description

Motion is a program that monitors the video signal from one or more cameras and is able to detect if a significant part of the picture has changed. Or in other words, it can detect motion.
Documentation

The documentation for Motion is contained within the file motion_guide.html.

The offline version of this file is available in the doc/motion directory. The online version of the motion_guide.html file can be viewed here

In addition to the detailed building instructions included within the guide, the INSTALL file contains abbreviated building instructions.
Resources

Please join the mailing list here

We prefer support through the mailing list because more people will have the benefit from the answers. A archive of mailing list discussions can be viewed here
License

Motion is mainly distributed under the GNU GENERAL PUBLIC LICENSE (GPL) version 2 or later. See the copyright file for a list of all the licensing terms of the various components of Motion.

The file CREDITS lists the many people who have contributed to Motion over the years.
Contributing

Issues and Patches should be submitted via github and include detail descriptions of the issue being addressed as well as any documentation updates that would be needed with the change.

**Comment by tosiara** [comment]
Sorry, what is your issue?
