### ISSUE TITLE
ipv6 streaming doesn't seem to work

### ISSUE THREAD

**Issue by l29ah** [Motion-Project/motion#97]
I put this in the config file:
```
ipv6_enabled on
stream_port 8081
stream_localhost off
```
And i see it listening only on ipv4 in `netstat -nlp`, also
```
Feb 19 00:45:31 [motion] [1] [NTC] [STR] http_bindsock: motion-stream testing : IPV4 addr: 0.0.0.0 port: 8081
Feb 19 00:45:31 [motion] [1] [NTC] [STR] http_bindsock: motion-stream Bound : IPV4 addr: 0.0.0.0 port: 8081
Feb 19 00:45:31 [motion] [1] [NTC] [ALL] motion_init: Started motion-stream server in port 8081 auth Enabled
```
in the log.

**Comment by tosiara** [comment]
What OS are you using?

**Comment by l29ah** [comment]
Gentoo Linux.

**Comment by l29ah** [comment]
https://github.com/Mr-Dave/motion/blob/master/stream.c#L721
puzzles me a bit wrt http://long.ccaba.upc.edu/long/045Guidelines/eva/ipv6.html

**Comment by Mr-Dave** [comment]
This isn't my area of specialty and this was unchanged from the source that I forked from.  If you have a readily available fix, I'd be interested in seeing it.

**Comment by tosiara** [comment]
Is there someone who can confirm this issue?

**Comment by slokhorst** [comment]
Seems to work fine here.

With `ipv6_enabled off`, when I go to `http://[::1]:8081/` in my browser, I get `ERR_CONNECTION_REFUSED`.

With `ipv6_enabled on`, when I go to `http://[::1]:8081/` in my browser, I get a nice motion webcam feed.

Unfortunately I an unable to test this over an actual network at the moment, but I don't see why that wouldn't work.

(Using Arch Linux x86_64)

**Comment by slokhorst** [comment]
Okay, I think I can reproduce IPv6 working *and* not working. (Arch Linux x86_64, `ipv6_enabled on` in all test cases)

`webcontrol_localhost on`:
`curl [::1]:8080/` -> **HTTP/1.1 200 OK**

`webcontrol_localhost off`:
`curl [::1]:8080/` -> **Failed to connect to ::1 port 8080: Connection refused**

I have the same pattern with `stream_localhost` and port 8081.

Very weird! So it seems that IPv6 (at least locally, `::1`), only works when `{webcontrol,stream}_localhost` is set to `on`, and does not work when it is set to `off`.

**Comment by slokhorst** [comment]
Hmm.. Now I also have the issue that when I set `webcontrol_localhost on`, I can no longer connect over IPv4 (`127.0.0.1:8080/`). It does work when I set `webcontrol_localhost off`.

**Comment by tosiara** [comment]
Very nice research. Thanks!

**Comment by slokhorst** [comment]
@l29ah, can you confirm that IPv6 works when you set `stream_localhost on`?

**Comment by slokhorst** [comment]
Found the problem!!!

`getaddrinfo()` returns all the addresses we want to listen on (IPv4 *and* IPv6). Then it loops through them, but [stops](https://github.com/Motion-Project/motion/blob/fcde5a2dfb63581017d1cef85a757d5e9ca7c714/stream.c#L770) once it is successfully listening on one of them (IPv4 **or** IPv6). So it will never listen on both.

I'm new to C/sockets but i'll try to find a fix.

**Comment by jogu** [comment]
TBH I think the current code is more complex than it needs to be.

I don't think we really need to use getaddrinfo (and it's known to have some weird issues - https://blog.powerdns.com/2014/05/21/a-surprising-discovery-on-converting-ipv6-addresses-we-no-longer-prefer-getaddrinfo/ )

For the ipv6+ipv4 localhost only case, we need two sockets - http://stackoverflow.com/questions/2277536/dual-stack-ipv6-ipv4-on-localhost has some hints.

For the ipv6 part, I believe we need something like this:

struct sockaddr_in6 sin6;
...
bzero(&sin6, sizeof(struct sockaddr_in6));
sin6.sin6_family = AF_INET6;
sin6.sin6_port = htons(23);
sin6.sin6_addr = in6addr_loopback;
...
if(bind(s, (struct sockaddr *)&sin6, sizeof(sin6)) == -1)
...
(then listen() etc are per present code)

(code taken from http://menehune.opt.wfu.edu/Kokua/Irix_6.5.21_doc_cd/usr/share/Insight/library/SGI_bookshelves/SGI_Developer/books/IRIX_NetPG/sgi_html/ch03.html )

There's a similar simple way for ipv4.

If localhost is off, we can create a single socket that works for both:

serveraddr.sin6_family = AF_INET6;
serveraddr.sin6_port   = htons(SERVER_PORT);
serveraddr.sin6_addr   = in6addr_any;

Or at least that's my understanding. I've not had to do much ipv6.

**Comment by slokhorst** [comment]
With your pointers, I have almost got everything working!
Like you said, the only problem is with local-only IPv4. It's really anoying you can't do something like `sin6.sin6_addr = in4addr_loopback;`

**Comment by slokhorst** [comment]
I have found a solution to circumvent the problem!

This is the interesting code that remains:
````C
int sd = socket(AF_INET6, SOCK_STREAM, 0);

struct sockaddr_in6 sin6;
bzero(&sin6, sizeof(struct sockaddr_in6));
sin6.sin6_family = AF_INET6;
sin6.sin6_port = htons(port);
if(local) {
    if(local_ipv4) //listen only on 127.0.0.1
        sin6.sin6_addr = in6addr_loopback4;
    else //listen only on ::1
        sin6.sin6_addr = in6addr_loopback;
} else {
    sin6.sin6_addr = in6addr_any;
}
int no = 0;
setsockopt(sd, IPPROTO_IPV6, IPV6_V6ONLY, (void *)&no, sizeof(no));
````

(`in6addr_loopback4` is the [IPv4 localhost mapped to an IPv6 address](http://stackoverflow.com/a/2868101), and it works great!)

The user now can choose between 3 options:
* Listen on all adresses (IPv4 & IPv6) (`local = FALSE`)
* Listen on localhost (IPv4 only) (`local = TRUE && local_ipv4 = TRUE`)
* Listen on localhost (IPv6 only) (`local = TRUE && local_ipv4 = FALSE`)

It is currently impossible to listen on both IPv4 and IPv6 localhost. Now this might be a bit 'weird', but I cannot think of any scenario where this would be an actual problem.

The alternative is to accept all connections, and then manually filter out both localhosts, but I'm not sure if it's worth the hassle. The codebase that now remains is much, much simpler.

**Comment by slokhorst** [comment]
I have opened #197 to be able to discuss the code easier. Please go there for comments on my proposed changes.
