### ISSUE TITLE
Extremely high CPU usage

### ISSUE THREAD

**Issue by MPK1** [Motion-Project/motion#976]
Hi,

I know that this issue is already known, but I can't believe it should be that big.

I run the latest motioneye docker container on my v-server (8 cores, 30GB RAM, SSD,...).
Motioneye is using the whole CPU (its on 100% all the time).
I'm using it with 26 RTSP cams, but without motion detection, just for live viewing.
There is nothing else running on the server, and if I stop motioneye the CPU usage drops down to 1%.

Is there anything I can do to reduce the CPU load, because right now everything is lagging very hard...

Thank you!

**Comment by tosiara** [comment]
1. motioneye is a different project - https://github.com/ccrisan/motioneye
2. when filing a bug yu should provide all the required information instead of just deleting the template https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md
3. for usage questions please use maillist https://lists.sourceforge.net/lists/listinfo/motion-user

**Comment by darkplatinum** [comment]
> 1. motioneye is a different project - https://github.com/ccrisan/motioneye
https://github.com/ccrisan/motioneye/issues/1374

**Comment by ccrisan** [comment]
@MPK1 see https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue. You'll need to isolate the issue and see if Motion is indeed the one causing problems. If that's the case, I believe these guys will try to help you.

**Comment by usernamepi** [comment]
Without using hardware acceleration, most of the processing power when using motion is taken by decoding and (even more) by encoding of video. Very little processing power is needed by the actual motion detection part.
If you have hardware acceleration available (for instance: intel graphics with Quick Sync Video) you could configure motion to use that, this will free up the cores from the encoding and decoding  tasks.

You stated that you are processing 26 RTSP streams with 8 cores.
That's at least already 26 decoders (at how many fps, at which resolution, which codec?)
How are they processed ?
Are you creating timelaps video for all streams => 26 encoders (albeit at low fps) 
Are you creating clips of motion events => 0 upto 26 encoders (usually at full fps)
Which codecs are used?
 x265/HEVC needs considerably more computing power compared to x264.

**Comment by sagaranand015** [comment]
> If you have hardware acceleration available (for instance: intel graphics with Quick Sync Video) you could configure motion to use that, this will free up the cores from the encoding and decoding tasks.

Is there some documentation on how to achieve this? I tried building ffmpeg with Intel Quick Sync enabled, but not sure how motion can use this. TIA.
