### ISSUE TITLE
accept rtmp input

### ISSUE THREAD

**Issue by Classsic** [Motion-Project/motion#98]
Is there a way to accept rtmp as input? is very similar to rtsp stream.

**Comment by Mr-Dave** [comment]
There is a currently a criteria that limits the prefix on the parameters.  If you can play the stream via FFPLAY, then it could be a simple hack within the code to replace the rtsp with rtmp and I'd believe it would work.  I'll leave this open for tracking for a future release.  If you do try the hack, please post a follow up comment to let us know whether to implement in this fork.

**Comment by tosiara** [comment]
I can confirm it just a prefix. You can rewrite your netcam url to be rtsp and specify rtmp port, like:

`rtsp://dev.wowza.longtailvideo.com:1935/vod/_definst_/sintel/640.mp4`

And motion will perfectly eat this stream
