### ISSUE TITLE
netcam_start: Invalid netcam service 'rtsp' - must be http, ftp, mjpg, mjpeg, v4l2 or file.

### ISSUE THREAD

**Issue by julienrobin28** [Motion-Project/motion#985]
Despite the fact the /etc/motion/motion.conf file is supposed to work with rtsp:// streams, motion fails because rtsp:// seems not to be in the list of working protocols with motion. This makes no sense.

```
# Full Network Camera URL.  Valid Services: http:// ftp:// mjpg:// rtsp:// mjpeg:// file:// rtmp://
netcam_url value rtsp://192.168.28.230:554/11
```

Into the log file : 
`netcam_start: Invalid netcam service 'rtsp' - must be http, ftp, mjpg, mjpeg, v4l2 or file.`

0. Reviewed guide and contributing documents? (Yes/No): No
1. version [x.y.z, hash, other]: 4.1.1-1.1+b2 (debian buster)
2. installed as a package or compiled from sources [deb, rpm, git, other]: installed as package from "apt install motion"
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: both on x86_64 and arm (Raspberry Pi / Buster)
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Debian 10 and Raspbian 10.

**Comment by Mr-Dave** [comment]
I would recommend consulting the guide or instructional videos that demonstrate Motion and the use of a RTSP camera.  May also want to consider as a possibility that the parameter was incorrectly specified.  

>netcam_url **_value_** rtsp://192.168.28.230:554/11

**Comment by julienrobin28** [comment]
OMG, really sorry about that, I spent several hours missing this.
