### ISSUE TITLE
H264 Motion Detection + rtsp html5 player

### ISSUE THREAD

**Issue by dddsssasa** [Motion-Project/motion#987]
Any future plans for compressed domain motion detector ?

https://www.google.cz/search?q=h264+motion+detector+github

also good idea replace stream preview using html5_rtsp_player and connect it to rtsp camera substream, I think it should improve fluently live preview, and remove all decoding from motion

**Comment by tosiara** [comment]
Duplicate https://github.com/Motion-Project/motion/issues/941
