### ISSUE TITLE
Switching streams in web view manually

### ISSUE THREAD

**Issue by Phlak106** [Motion-Project/motion#994]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: latest
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mpeg file now, multiple webcams in future
5. hardware [x86, ARM, other]: Raspberry Pi
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Raspbian 

I would like to switch between streams in the web view manually and possibly automatically in the future based on a machine learning model's opinion of which stream is more interesting. My C is a little rusty. Can someone point me to where the stream is chosen for display in the live webstream (localhost:8081) display?

I see there is a SIGUSR1 but I was reading other articles that this isn't really what I want to hook up to. Is that correct? Is it better to create a new event type and wire it up that way?

This is for a sports scenario so I would also like to use this kind of user input to eventually capture an instant replay. Any thoughts on this kind of feature would be appreciated.

**Comment by tosiara** [comment]
What do you mean by `I would like to switch between streams in the web view manually`? Can you provide more details with screenshots please?

**Comment by Mr-DaveDev** [comment]
When the stream is assigned unique ports (8081, 8082,..) then it is started on each camera thread [here](https://github.com/Motion-Project/motion/blob/ff903de2e3d6320f13841a91e4080c1220c38059/webu.c#L1975).  As a result, each stream does know about or interact with any other stream.  In this situation, you would need to do a lot of cross threading to get images from one thread and push them out to the stream that was started on a different thread. 

I think a better approach for your objective would be to use the new single port option which provides streams on 8081/1, 8081/2, etc  See [documentation](https://motion-project.github.io/motion_config.html#OptDetail_Stream) on how the URLs work.

The selection of what camera thread is used for a particular url is [here](https://github.com/Motion-Project/motion/blob/ff903de2e3d6320f13841a91e4080c1220c38059/webu.c#L336)
