### ISSUE TITLE
No need "MAX_PATH-1" for snprintf

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#996]
```
event.c: In function ‘event_create_extpipe.part.7’:
event.c:854:56: error: ‘__builtin_snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
```
https://github.com/Motion-Project/motion/commit/24a0619b5ce17c16e843c6615ed299bf8c077d7e
```
- snprintf(cnt->extpipecmdline, PATH_MAX - 1, "%s", stamp);
+ snprintf(cnt->extpipecmdline, PATH_MAX, "%s", stamp);
```

**Comment by vilhelmgray** [comment]
This is fixed in https://github.com/Motion-Project/motion/pull/993.

**Comment by tosiara** [comment]
Personally, I'd like that PR to be splited into 4 related to: MMAL, whitespace, strcat and memcpy. Putting all them together into one PR: 1) makes it harder to review 2) makes it harder to track which PR created issues in future

**Comment by vilhelmgray** [comment]
@tosiara I'm not the author of that PR, but I agree since it's not good to have unrelated patches grouped together like it currently is. Please let dfgweb know so they can update their pull request and open a new one for just the warning fixes.

**Comment by tosiara** [comment]
Resolved in: https://github.com/Motion-Project/motion/pull/1010
